### ISSUE TITLE
Comments in project.json gives exception

### ISSUE THREAD

**Issue by nickvane** [dotnet/coreclr#1005]
When using 

    {
      "version": "1.0.0-*",
      "title": "",
      "description": "",

      "frameworks": {
        "dnx451": {
          "frameworkAssemblies": {
            "System.Xml": "4.0.0.0"
          }
        }
    	//,"dnxcore50": {
        //  "dependencies": {
        //    "System.Collections": "4.0.10-beta-22816",
        //  }
        //}
      }
    }

as project.json, gives following exception:

    Microsoft.Framework.Runtime.FileFormatException: Illegal character / /. ---> Microsoft.Framework.Runtime.Json.JsonDeserializerException: Illegal character / /.
       at Microsoft.Framework.Runtime.Json.JsonBuffer.Read()
       at Microsoft.Framework.Runtime.Json.JsonDeserializer.DeserializeObject(JsonToken head, JsonBuffer buffer)
       at Microsoft.Framework.Runtime.Json.JsonDeserializer.DeserializeInternal(JsonToken next, JsonBuffer buffer)
       at Microsoft.Framework.Runtime.Json.JsonDeserializer.DeserializeObject(JsonToken head, JsonBuffer buffer)
       at Microsoft.Framework.Runtime.Json.JsonDeserializer.DeserializeInternal(JsonToken next, JsonBuffer buffer)
       at Microsoft.Framework.Runtime.Json.JsonDeserializer.Deserialize(TextReader reader)
       at Microsoft.Framework.Runtime.Project.GetProjectFromStream(Stream stream, String projectName, String projectPath, ICollection`1 diagnostics)
       at Microsoft.Framework.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
       --- End of inner exception stack trace ---
       at Microsoft.Framework.Runtime.Project.TryGetProject(String path, Project& project, ICollection`1 diagnostics)
       at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__73.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at     System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass72_0.<<ExecuteCommand>b__0>d.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Microsoft.Framework.PackageManager.RestoreCommand.    <ExecuteCommand>d__72.MoveNext()
    ----------
    Restore failed
    Illegal character / /.

When doing dnu restore with 1.0.0-beta5-11781 coreclr x86.
This worked with 1.0.0-beta4 coreclr x86

**Comment by kangaroo** [comment]
This is the new spec: https://github.com/aspnet/Announcements/issues/24

**Comment by nickvane** [comment]
Lol, ok clear.
I'll close it.
