### ISSUE TITLE
[Arm64][R2R] [1-Failure] tests fail with Could not load type 'System.Runtime.CompilerServices.IsJitIntrinsic'

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#10069]
Failing Test

<pre>
JIT/Directed/pinvoke/preemptive_cooperative/preemptive_cooperative.cmd
</pre>

Test Output

<pre>
Output: TEST_CMD_LINE: JIT\Directed\pinvoke\preemptive_cooperative> C:\Users\DDJOIN\arm64_ci\tests\JIT\Directed\pinvoke\preemptive_cooperative\preemptive_cooperative.cmd
BEGIN EXECUTION
" C:\Users\DDJOIN\arm64_ci\tests\Tests\Core_Root\crossgen.exe" /Platform_Assemblies_Paths C:\Users\DDJOIN\arm64_ci\tests\Tests\Core_Root;C:\Users\DDJOIN\arm64_ci\tests\JIT\Directed\pinvoke\preemptive_cooperative preemptive_cooperative.exe
Microsoft (R) CoreCLR Native Image Generator - Version 4.5.22220.0
Copyright (c) Microsoft Corporation.  All rights reserved.
Warning: Could not load type 'System.Runtime.CompilerServices.IsJitIntrinsic' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. while resolving 0x1000007 - System.Runtime.CompilerServices.IsJitIntrinsic.
Native image C:\Users\DDJOIN\arm64_ci\tests\JIT\Directed\pinvoke\preemptive_cooperative\preemptive_cooperative.ni.exe generated successfully.
"C:\Users\DDJOIN\arm64_ci\tests\Tests\Core_Root\corerun.exe" preemptive_cooperative.exe
Created
Unhandled Exception: Destroyed
System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.IsJitIntrinsic' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
at Repro.atoi(IntPtr handle, UInt32 dwMilliseconds)
at Repro.GCHole()
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
at System.Threading.ThreadHelper.ThreadStart()
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED
</pre>

**Comment by jashook** [comment]
Excluded see #2434
