### ISSUE TITLE
[x86/Linux] Vector3Interop test failures

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#10161]
Reverse P/Invoke test in ``JIT.SIMD.Vector3Interop_r`` failed:
```
FAILED   - [ 5474 :    7 sec ] JIT/SIMD/Vector3Interop_r/Vector3Interop_r.sh
...
               callBack_RPInvoke_Vector3Arg:
                   iVal 123
                   Sum0,1,2 = 1400, 14, 140
                   str abcdefg
               RPInvoke Vector3Arg test failed
```

**Comment by parjong** [comment]
``v1`` and ``v2`` seem to be reversed:
```
    // Argument pass test
    // Test if the managed side correctly reads 12-byte Vector3 argument from the native side
    // and meet the backend assumption 1 and 2.
    static void callBack_RPInvoke_Vector3Arg(
        int i,
        Vector3 v1,
        [MarshalAs(UnmanagedType.LPStr)] string s,
        Vector3 v2)
    {
        // sum = (1, 2, 3) dot (1, 2, 3) = 14
        float sum0 = Vector3.Dot(v1, v1);
        // sum = (10, 20, 30) dot (10, 20, 30) = 1400
        float sum1 = Vector3.Dot(v2, v2);
        // sum = (10, 20, 30) dot (1, 2, 3) = 140
        float sum2 = Vector3.Dot(v2, v1);

        Console.WriteLine("callBack_RPInvoke_Vector3Arg:");
        Console.WriteLine("    iVal {0}", i);
        Console.WriteLine("    Sum0,1,2 = {0}, {1}, {2}", sum0, sum1, sum2);
        Console.WriteLine("    str {0}", s);

        result = (sum0 == 14) && (sum1 == 1400) && (sum2 == 140) && (s == "abcdefg") && (i == 123);
    }
```

**Comment by parjong** [comment]
@jkotas @BruceForstall Could you let me know why x86 pushes arguments from left to right? Is there any problem with R2L order?

**Comment by jkotas** [comment]
> I guessed that windows native compiler uses L2R order. 

This is microoptimization from the early .NET days. The arguments in IL are pushed L2R order, and so this allowed the JIT to generate slightly better code with less work for push/pop architectures like x86. I suspect that the difference is neglible today. However, number of other implementation details picked up dependency on this order, and so changing it would not be exactly trivial task.

It has nothing to do with windows native compilers.

**Comment by jkotas** [comment]
For reverse PInvoke, the IL stub generator should be taking care of reversing the argument order.

**Comment by parjong** [comment]
Is there any reverse P/Invoke IL stub? It seems that reverse P/Invoke uses ``UMThunkStub`` which is statically compiled.

**Comment by jkotas** [comment]
Yes, there is reverse P/Invoke IL stub.

**Comment by jkotas** [comment]
Another option: teach the true native calling convention and use that for reverse PInvoke.

**Comment by parjong** [comment]
@jkotas Thanks. I thought that there is no stub between ``UMThunkStub`` and the target managed code. I'll take a look at reverse P/Invoke stub.

**Comment by parjong** [comment]
#10217 makes some progress, but it looks like another issue (maybe #10133?):
```
callBack_RPInvoke_Vector3Arg:
    iVal 123
    Sum0,1,2 = 14, 1400, 140
    str abcdefg
callBack_RPInvoke_Vector3Arg_Unix:
    1, 2, 3
    10, 20, 30
    Sum0,1,2,3 = 14, 1400, 140, 936
callBack_RPInvoke_Vector3Arg_Unix2:
    1, 2, 3
    4, 5, 6
    7, 8, 9
    Sum0,1,2,3,4,5 = 14, 77, 194, 32, 122, 1045

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at RPInvokeTest.test()
   at Test.Main()
```

**Comment by parjong** [comment]
It seems that this test now hits #10027:
```
Program received signal SIGSEGV, Segmentation fault.
0xf25e46d0 in ?? ()
(gdb) bt
#0  0xf25e46d0 in ?? ()
#1  0xf718a1bd in UMThunkStub () at /home/parjong/projects/dotnet/coreclr/src/vm/i386/umthunkstub.S:98
#2  0xf7fd11b2 in nativeCall_RPInvoke_Vector3Ret (notify=0xf63497d6) at /home/parjong/projects/dotnet/coreclr/tests/src/JIT/SIMD/Vector3TestNative.cpp:372
```
