### ISSUE TITLE
[x86/Linux] JIT.Methodical.eh.nested.nonlocalexit.throwinfinallyrecursive_20 failure

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#10187]
Following tests fail on x86/Linux.
- JIT/Methodical/eh/nested/nonlocalexit/throwinfinallyrecursive_20_d/throwinfinallyrecursive_20_d.sh
- JIT/Methodical/eh/nested/nonlocalexit/throwinfinallyrecursive_20_r/throwinfinallyrecursive_20_r.sh

Backtrace:

```
in foo i = 1
-in foo try
--in foo try
---in foo try
----in foo try
-----in foo try
------in foo try
-------in foo try
--------in foo try
---------in foo try
----------in foo try
-----------in foo try
------------in foo try
-------------in foo try
--------------in foo try
---------------in foo try
----------------in foo try
Program received signal SIGSEGV, Segmentation fault.
0xf6d6d92a in MethodTable::GetFlag (this=0x2d002c,
    flag=MethodTable::enum_flag_HasComponentSize)
    at /home/hanjoung/ws/dotnet/coreclr/src/vm/methodtable.h:3997
3997            return m_dwFlags & flag;

(gdb) bt                                                                                                                              [27/9295]
#0  0xf6d6d92a in MethodTable::GetFlag (this=0x2d002c, flag=MethodTable::enum_flag_HasComponentSize) at /home/hanjoung/ws/dotnet/coreclr/src/vm
/methodtable.h:3997
#1  0xf6d7e55f in MethodTable::HasComponentSize (this=0x2d002c) at /home/hanjoung/ws/dotnet/coreclr/src/vm/methodtable.h:1825
#2  0xf6e6e63f in MethodTable::GetComponentSize (this=0x2d002c) at /home/hanjoung/ws/dotnet/coreclr/src/vm/methodtable.h:1847
#3  0xf6e64dc1 in MethodTable::SanityCheck (this=0x2d002c) at /home/hanjoung/ws/dotnet/coreclr/src/vm/methodtable.cpp:7586
#4  0xf6e69dc7 in MethodTable::Validate (this=0x2d002c) at /home/hanjoung/ws/dotnet/coreclr/src/vm/methodtable.cpp:9633
#5  0xf6e79992 in Object::ValidateInner (this=0xf2f0a028, bDeep=1, bVerifyNextHeader=1, bVerifySyncBlock=1) at /home/hanjoung/ws/dotnet/coreclr
/src/vm/object.cpp:1720
#6  0xf6e78389 in Object::Validate (this=0xf2f0a028, bDeep=1, bVerifyNextHeader=1, bVerifySyncBlock=1) at /home/hanjoung/ws/dotnet/coreclr/src/
vm/object.cpp:1696
#7  0xf6e7810a in Object::ValidatePromote (this=0xf2f0a028, sc=0xffffc048, flags=4) at /home/hanjoung/ws/dotnet/coreclr/src/vm/object.cpp:1315
#8  0xf7591352 in WKS::GCHeap::Promote (ppObject=0xffffcb8c, sc=0xffffc048, flags=4) at /home/hanjoung/ws/dotnet/coreclr/src/gc/gc.cpp:33685
#9  0xf701c3e1 in GcEnumObject (pData=0xffffbca8, pObj=0xffffcb8c, flags=4) at /home/hanjoung/ws/dotnet/coreclr/src/vm/gcenv.ee.cpp:80
#10 0xf6d8a4f7 in EECodeManager::EnumGcRefs (this=0x8078ec0, pContext=0xffffb360, pCodeInfo=0xffffb208, flags=0, pCallBack=0xf701c2e0 <GcEnumOb
ject(void*, OBJECTREF*, unsigned int)>, hCallBack=0xffffbca8, relOffsetOverride=4294967295) at /home/hanjoung/ws/dotnet/coreclr/src/vm/eetwain.
cpp:4738
#11 0xf701cc60 in GcStackCrawlCallBack (pCF=0xffffafe8, pData=0xffffbca8) at /home/hanjoung/ws/dotnet/coreclr/src/vm/gcenv.ee.cpp:323
#12 0xf6ecfc76 in Thread::MakeStackwalkerCallback (this=0x8087498, pCF=0xffffafe8, pCallback=0xf701c7a0 <GcStackCrawlCallBack(CrawlFrame*, void
*)>, pData=0xffffbca8, uFramesProcessed=10) at /home/hanjoung/ws/dotnet/coreclr/src/vm/stackwalk.cpp:865
#13 0xf6ed0004 in Thread::StackWalkFramesEx (this=0x8087498, pRD=0xffffb360, pCallback=0xf701c7a0 <GcStackCrawlCallBack(CrawlFrame*, void*)>, p
Data=0xffffbca8, flags=34048, pStartFrame=0x0) at /home/hanjoung/ws/dotnet/coreclr/src/vm/stackwalk.cpp:946
#14 0xf6ed0f58 in Thread::StackWalkFrames (this=0x8087498, pCallback=0xf701c7a0 <GcStackCrawlCallBack(CrawlFrame*, void*)>, pData=0xffffbca8, f
lags=34048, pStartFrame=0x0) at /home/hanjoung/ws/dotnet/coreclr/src/vm/stackwalk.cpp:1029
#15 0xf701dd1b in ScanStackRoots (pThread=0x8087498, fn=0xf7591010 <WKS::GCHeap::Promote(Object**, ScanContext*, unsigned int)>, sc=0xffffc048)
 at /home/hanjoung/ws/dotnet/coreclr/src/vm/gcenv.ee.cpp:555
#16 0xf701d8c1 in GCToEEInterface::GcScanRoots (fn=0xf7591010 <WKS::GCHeap::Promote(Object**, ScanContext*, unsigned int)>, condemned=0, max_ge
n=2, sc=0xffffc048) at /home/hanjoung/ws/dotnet/coreclr/src/vm/gcenv.ee.cpp:584
#17 0xf744689f in GCScan::GcScanRoots (fn=0xf7591010 <WKS::GCHeap::Promote(Object**, ScanContext*, unsigned int)>, condemned=0, max_gen=2, sc=0
xffffc048) at /home/hanjoung/ws/dotnet/coreclr/src/gc/gcscan.cpp:170
#18 0xf756a605 in WKS::gc_heap::mark_phase (condemned_gen_number=0, mark_only_p=0) at /home/hanjoung/ws/dotnet/coreclr/src/gc/gc.cpp:19484
#19 0xf75606ef in WKS::gc_heap::gc1 () at /home/hanjoung/ws/dotnet/coreclr/src/gc/gc.cpp:15244
#20 0xf7582416 in WKS::gc_heap::garbage_collect (n=0) at /home/hanjoung/ws/dotnet/coreclr/src/gc/gc.cpp:16745
#21 0xf7553167 in WKS::GCHeap::GarbageCollectGeneration (this=0x8089190, gen=0, reason=reason_alloc_soh) at /home/hanjoung/ws/dotnet/coreclr/sr
c/gc/gc.cpp:35075
#22 0xf7557848 in WKS::gc_heap::try_allocate_more_space (acontext=0x80874d4, size=19056, gen_number=0) at /home/hanjoung/ws/dotnet/coreclr/src/
gc/gc.cpp:13048
---Type <return> to continue, or q <return> to quit---
#23 0xf75579d5 in WKS::gc_heap::allocate_more_space (acontext=0x80874d4, size=19056, alloc_generation_number=0) at /home/hanjoung/ws/dotnet/cor
eclr/src/gc/gc.cpp:13344
#24 0xf75e4dcb in WKS::gc_heap::allocate (jsize=19056, acontext=0x80874d4) at /home/hanjoung/ws/dotnet/coreclr/src/gc/gc.cpp:13375
#25 0xf75cfae2 in WKS::GCHeap::Alloc (this=0x8089190, context=0x80874d4, size=19056, flags=0) at /home/hanjoung/ws/dotnet/coreclr/src/gc/gc.cpp:34421
#26 0xf7023e9d in Alloc (size=19056, bFinalize=0, bContainsPointers=0) at /home/hanjoung/ws/dotnet/coreclr/src/vm/gchelpers.cpp:140
#27 0xf70230b3 in SlowAllocateString (cchStringLength=9520) at /home/hanjoung/ws/dotnet/coreclr/src/vm/gchelpers.cpp:904
#28 0xf70587a4 in FramedAllocateString (stringLength=9520) at /home/hanjoung/ws/dotnet/coreclr/src/vm/jithelpers.cpp:2935
#29 0xf26cf080 in ?? ()
... more frames ...
```

**Comment by wateret** [comment]
It crashed while allocating memory and GC is triggered inside a finally funclet.
