### ISSUE TITLE
xunit wrapper failure when a test times out

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/coreclr#1039]
The wrapper currently imposes a 3 minute limit per-test. If this timeout is reached the wrapper can fail with an unhandled exception and bring down xunit:
```
C:\Repos\coreclr\bin\tests\Windows_NT.x64.debug\JIT\Directed\cmov\Double_Or_Op.cmd Timed Out

c:\Repos\coreclr\tests\src\TestWrappers_x64_debug\JIT\JIT.XUnitWrapper.cs(12015): error :    at JIT._Directed_cmov_Double_Or_Op_._Directed_cmov_Double_Or_Op_cmd() in c:\Repos\coreclr\tests\src\TestWrappers_x64_debug\JIT\JIT.XUnitWrapper.cs: line 12015 [C:\Repos\coreclr\tests\runtest.proj]

Unhandled Exception:
System.ObjectDisposedException: Safe handle has been closed
   at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Microsoft.Win32.Win32Native.SetEvent(SafeWaitHandle handle)
   at System.Threading.EventWaitHandle.Set()
   at CoreclrTestLib.CoreclrTestWrapperLib.<>c__DisplayClass5.<RunTest>b__0(Object sender, DataReceivedEventArgs e) in c:\Repos\coreclr\tests\src\Common\Coreclr.TestWrapper\CoreclrTestWrapperLib.cs:line 41
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
```

**Comment by krk** [comment]
repro :+1:
