### ISSUE TITLE
FileNotFoundException building coreclr

### ISSUE THREAD

**Issue by hughbe** [dotnet/coreclr#10487]
Clean repository up to date with` apple/master`. Visual Studio 2017 developer command prompt with all the correct components. `build.cmd`:

```
Starting Build at 14:22:11.50
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26228.9
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
Tools are already initialized.
Running: C:\Users\hughb\Documents\GitHub\coreclr\Tools\dotnetcli\dotnet.exe C:\Users\hughb\Documents\GitHub\coreclr\Tools\run.exe C:\Users\hughb\Documents\GitHub\coreclr\config.json build -Project=C:\Users\hughb\Documents\GitHub\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="C:\Users\hughb\Documents\GitHub\coreclr\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
BUILD: Restoring the OptimizationData Package
Tools are already initialized.
Running: C:\Users\hughb\Documents\GitHub\coreclr\Tools\dotnetcli\dotnet.exe C:\Users\hughb\Documents\GitHub\coreclr\Tools\run.exe C:\Users\hughb\Documents\GitHub\coreclr\config.json sync -optdata

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'. The system cannot find the file specified.
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
BUILD: Error: Failed to restore the optimization data package.

```

**Comment by jkotas** [comment]
@dotnet/dnceng Crash in run.exe tool

**Comment by dagood** [comment]
What commit is `apple/master` at? That fork is a 404 for me.

**Comment by dagood** [comment]
I can find two other times this happened, pre-VS2017:
https://github.com/dotnet/coreclr/issues/7245
https://github.com/dotnet/coreclr/pull/7985#issuecomment-258544963
Based on that, it seems to be intermittent. I couldn't repro using my VS2017 prompt on `dotnet/master`, but I most likely don't have the same install settings.

There should be a copy of `Newtonsoft.Json.dll` 9.0.1.19813 sitting in `Tools` that `dotnet` should be finding--can you make sure that exists? Otherwise, I think some fusion log output would be helpful. (https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md)

**Comment by hughbe** [comment]
Sorry I meant `dotnet/master`. I've been contributing to `apple/swift` a bit recently so always get confused!

**Comment by hughbe** [comment]
I can't reproduce this anymore. Seems like something non deterministic
