### ISSUE TITLE
[RyuJIT/ARM32] Abort on FailFast

### ISSUE THREAD

**Issue by mskvortsov** [dotnet/coreclr#10729]
PR #10609 uncovered (or introduced?) several failures across the full testsuite run:
```
Assert failure(PID 2250 [0x000008ca], Thread: 2250 [0x08ca]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
    File: /home/mskvortsov/git/coreclr/src/vm/jithelpers.cpp Line: 5555
    Image: /home/mskvortsov/clr/corerun

Aborted
```
The test cases are:
```
GC/API/GC/GetGeneration_fail/GetGeneration_fail.exe
GC/Features/LOHCompaction/lohcompactapi2/lohcompactapi2.exe
GC/Features/Pinning/PinningOther/PinnedCollect/PinnedCollect.exe
GC/Features/Pinning/PinningOther/PinnedHandle/PinnedHandle.exe
GC/Features/Pinning/PinningOther/PinnedObject/PinnedObject.exe
Interop/MarshalAPI/Miscellaneous/MarshalClassTests/MarshalClassTests.exe
Interop/MarshalAPI/OffsetOf/OffsetOf/OffsetOf.exe
Interop/NativeCallable/NativeCallableTest/NativeCallableTest.exe
...
```

**Comment by mskvortsov** [comment]
@alpencolt Could you take a look?

**Comment by alpencolt** [comment]
I will check. It can reproduce only on release build.

**Comment by alpencolt** [comment]
Cannot reproduce on latest versions `coreclr` and `corefx`. Only `OffsetOf.exe` and `NativeCallableTest.exe` are failed. First uses structures, which aren't implemented in ARM32. The second are failed on legacy backend but with another exception:
```C#
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'NativeCallableDll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Program.NativeMethods.CallManagedAdd(IntPtr callbackProc, Int32 n)
   at TestNativeCallable()
   at Program.TestNativeCallableValid()
   at Program.Main()
Aborted

```
Task can be postponed I think.

**Comment by mskvortsov** [comment]
@alpencolt That exception means you missed `libNativeCallableDll.so` and others (see `bin/Product/Linux.arm.Debug/bin` of coreclr build output).

**Comment by mskvortsov** [comment]
Another FailFast on current tip (`cb371832`):
```
COMPlus_AltJit=func3 clr-checked/corerun tests-release/JIT/jit64/localloc/call/call07_dynamic/call07_dynamic.exe

Assert failure(PID 25823 [0x000064df], Thread: 25823 [0x64df]): !"About to FailFast. set ComPlus_AssertOnFailFast=0 if this is expected"
    File: /home/mskvortsov/git/coreclr/src/vm/jithelpers.cpp Line: 5555
    Image: /home/mskvortsov/clr-checked/corerun

Aborted
```

**Comment by mskvortsov** [comment]
The func3's prolog looks strange, or at least inefficient:
```
G_M31595_IG01:
000000  E92D 4FF0      push    {r4,r5,r6,r7,r8,r9,r10,r11,lr}
000004  B085           sub     sp, 20
000006  46E9           mov     r9, sp
000008  F10D 0B30      add     r11, sp, 48
00000C  2400           movs    r4, 0
00000E  F8C9 4004      str     r4, [r9+4]	// [V11 GsCookie]
000012  F8C9 400C      str     r4, [r9+12]	// [V13 LocAllocSP]
000016  F8C9 D00C      str     sp, [r9+12]	// [V13 LocAllocSP]
00001A  F245 6478      movw    r4, 0x5678
00001E  F2C1 2434      movt    r4, 0x1234
000022  F8C9 4004      str     r4, [r9+4]	// [V11 GsCookie]
```

**Comment by mskvortsov** [comment]
Incorrect dereference happens at the second store on the 7th iteration of the loop:
```
   0xb1dd1034:	add.w	r1, r2, #4000	; 0xfa0
   0xb1dd1038:	str.w	lr, [r9, #8]
   0xb1dd103c:	str.w	r1, [lr, r2, lsl #2]
   0xb1dd1040:	adds	r2, r2, #1
   0xb1dd1042:	cmp	r2, r0
   0xb1dd1044:	blt.n	0xb1dd1072
   0xb1dd1046:	movw	r0, #4336	; 0x10f0
   0xb1dd104a:	movt	r0, #45808	; 0xb2f0
   0xb1dd104e:	ldr	r0, [r0, #0]
   0xb1dd1050:	movw	r2, #57708	; 0xe16c
   0xb1dd1054:	movt	r2, #46537	; 0xb5c9
   0xb1dd1058:	ldr	r2, [r2, #0]
   0xb1dd105a:	mov	r1, r4
   0xb1dd105c:	mov.w	r3, #1000	; 0x3e8
   0xb1dd1060:	movw	r12, #2481	; 0x9b1
   0xb1dd1064:	movt	r12, #45533	; 0xb1dd
   0xb1dd1068:	blx	r12
   0xb1dd106a:	cmp	r0, #0
   0xb1dd106c:	bne.n	0xb1dd107e
   0xb1dd106e:	movs	r7, #0
   0xb1dd1070:	b.n	0xb1dd1106
   0xb1dd1072:	ldr.w	lr, [r9, #8]
   0xb1dd1076:	b.n	0xb1dd1034
```

**Comment by mskvortsov** [comment]
Here is full list of current FailFast failures:
```
Interop/MarshalAPI/OffsetOf/OffsetOf/OffsetOf.sh
Interop/NativeCallable/NativeCallableTest/NativeCallableTest.sh
JIT/jit64/localloc/call/call07_dynamic/call07_dynamic.sh
JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.sh
JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh
JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
```

**Comment by alpencolt** [comment]
Bug was caused by usage ARM conditional execution without setting proper flags. I will prepare fix today.
