### ISSUE TITLE
[x86/Linux] ReadyToRun TCs fail, again.

### ISSUE THREAD

**Issue by ragmani** [dotnet/coreclr#10931]
```
Program received signal SIGSEGV, Segmentation fault.
0xf6dbfb94 in Module::IsReadyToRun (this=0x3cb800) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/ceeload.h:3053
3053	        return m_pReadyToRunInfo != NULL;
(gdb) bt
#0  0xf6dbfb94 in Module::IsReadyToRun (this=0x3cb800) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/ceeload.h:3053
#1  0xf72040fc in Module::GetNativeOrReadyToRunImage (this=0x3cb800) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/ceeload.cpp:4338
#2  0xf6eef56c in StubDispatchFixupWorker (pTransitionBlock=0xffffc284, siteAddrForRegisterIndirect=4074884992, sectionIndex=0, pModule=0x3cb800)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/virtualcallstub.cpp:1234
#3  0xf7189fd4 in StubDispatchFixupStub () at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/i386/asmhelpers.S:743
#4  0x10baea55 in ?? ()
#5  0x10bb0afd in ?? ()
#6  0xf7189e39 in CallDescrWorkerInternal () at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/i386/asmhelpers.S:304
#7  0xf6f2a18d in CallDescrWorker (pCallDescrData=0xffffcb18) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/callhelpers.cpp:135
#8  0xf6f29f3d in CallDescrWorkerWithHandler (pCallDescrData=0xffffcb18, fCriticalCall=0) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/callhelpers.cpp:78
#9  0xf6f2be13 in MethodDescCallSite::CallTargetWorker (this=0xffffce10, pArguments=0xffffce80, pReturnValue=0xffffcb98, cbReturnValue=8)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/callhelpers.cpp:645
#10 0xf6d06b2f in MethodDescCallSite::Call_RetOBJECTREF (this=0xffffce10, pArguments=0xffffce80) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/callhelpers.h:436
#11 0xf719c6f2 in AppDomain::DoSetup (this=0x80799b0, setupInfo=0xffffd208) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/appdomain.cpp:4743
#12 0xf6cfb5c3 in CorHost2::_CreateAppDomain (this=0x8056830, wszFriendlyName=0x8056868 u"unixcorerun", dwFlags=336, wszAppDomainManagerAssemblyName=0x0, wszAppDomainManagerTypeName=0x0, nProperties=5, 
    pPropertyNames=0x8056890, pPropertyValues=0x80568b0, pAppDomainID=0xffffd5d0) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/corhost.cpp:756
#13 0xf6cfeb2c in CorHost2::CreateAppDomainWithManager (this=0x8056830, wszFriendlyName=0x8056868 u"unixcorerun", dwFlags=336, wszAppDomainManagerAssemblyName=0x0, wszAppDomainManagerTypeName=0x0, 
    nProperties=5, pPropertyNames=0x8056890, pPropertyValues=0x80568b0, pAppDomainID=0xffffd5d0) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/corhost.cpp:922
#14 0xf6c7fdc0 in coreclr_initialize (exePath=0x8052014 "/home/jang/DotNet/enable_x86/work/ragmani/overlay.debug/corerun", appDomainFriendlyName=0x804e500 "unixcorerun", propertyCount=5, 
    propertyKeys=0xffffd614, propertyValues=0xffffd600, hostHandle=0xffffd5d4, domainId=0xffffd5d0) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/dlls/mscoree/unixinterface.cpp:219
#15 0x0804c4cb in ExecuteManagedAssembly (currentExeAbsolutePath=0x8052014 "/home/jang/DotNet/enable_x86/work/ragmani/overlay.debug/corerun", 
    clrFilesAbsolutePath=0x80520b4 "/home/jang/DotNet/enable_x86/work/ragmani/overlay.debug", 
    managedAssemblyAbsolutePath=0x80520fc "/home/jang/DotNet/enable_x86/work/ragmani/unittest/readytorun/mainv2/mainv2.exe", managedAssemblyArgc=0, managedAssemblyArgv=0x0)
    at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:404
#16 0x0804b216 in corerun (argc=2, argv=0xffffd7e4) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/coreclr/hosts/unixcorerun/corerun.cpp:149
#17 0x0804b34a in main (argc=2, argv=0xffffd7e4) at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/coreclr/hosts/unixcorerun/corerun.cpp:161
(gdb) frame 3           
#3  0xf7129684 in StubDispatchFixupStub () at /home/jang/DotNet/enable_x86/work/ragmani/coreclr/src/vm/i386/asmhelpers.S:743
warning: Source file is more recent than executable.
743	    call        C_FUNC(StubDispatchFixupWorker)
(gdb) disas
Dump of assembler code for function StubDispatchFixupStub:
   0xf712966d <+0>:	push   %ebp
   0xf712966e <+1>:	mov    %esp,%ebp
   0xf7129670 <+3>:	push   %ebx
   0xf7129671 <+4>:	push   %esi
   0xf7129672 <+5>:	push   %edi
   0xf7129673 <+6>:	push   %ecx
   0xf7129674 <+7>:	push   %edx
   0xf7129675 <+8>:	mov    %esp,%esi
   0xf7129677 <+10>:	pushw  $0x0
   0xf712967a <+13>:	pushw  $0x0
   0xf712967d <+16>:	push   %eax
   0xf712967e <+17>:	push   %esi
   0xf712967f <+18>:	call   0xf6e73250 <StubDispatchFixupWorker(TransitionBlock*, TADDR, DWORD, Module*)>
=> 0xf7129684 <+23>:	pop    %edx
   0xf7129685 <+24>:	pop    %ecx
   0xf7129686 <+25>:	pop    %edi
   0xf7129687 <+26>:	pop    %esi
   0xf7129688 <+27>:	pop    %ebx
   0xf7129689 <+28>:	pop    %ebp
   0xf712968a <+29>:	jmp    *%eax
   0xf712968c <+31>:	ret    
End of assembler dump.
```

**Comment by ragmani** [comment]
This is a problem similar to [#10383](https://github.com/dotnet/coreclr/pull/10383).

**Comment by ragmani** [comment]
after #10932.
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) bt
#0  0x00000000 in ?? ()
#1  0xffffce28 in ?? ()
```

It seems that the stack alignment(16 bytes) is broken at "call   *0x300010c8" and "call   *0x300010d0".
```
(gdb) x/39i 0x30005f04
   0x30005f04:	push   %ebp		// esp: 0xffffc62c
   0x30005f05:	mov    %esp,%ebp	// esp: 0xffffc628
   0x30005f07:	push   %edi		// esp: 0xffffc628
   0x30005f08:	push   %esi		// esp: 0xffffc624
=> 0x30005f09:	call   *0x300010c4
   0x30005f0f:	mov    %eax,%esi
   0x30005f11:	mov    %esi,%ecx
   0x30005f13:	xor    %edx,%edx
   0x30005f15:	call   *0x300010c8	// esp is changed from 0xffffc620 to 0xffffc618
   0x30005f1b:	mov    0x30001358,%edi	// esp: 0xffffc618
   0x30005f21:	mov    (%edi),%edx
   0x30005f23:	mov    0x30001354,%ecx
   0x30005f29:	mov    (%ecx),%ecx
   0x30005f2b:	sub    $0xc,%esp
   0x30005f2e:	push   %ecx
   0x30005f2f:	mov    0x4(%esi),%ecx
   0x30005f32:	call   *0xc(%esi)
   0x30005f35:	add    $0x10,%esp
   0x30005f38:	mov    %eax,%ecx
   0x30005f3a:	mov    0x3000135c,%edx
   0x30005f40:	mov    (%edx),%edx
   0x30005f42:	call   *0x30001110
   0x30005f48:	call   *0x300010cc
   0x30005f4e:	mov    %eax,%esi
   0x30005f50:	mov    (%edi),%edx
   0x30005f52:	mov    %esi,%ecx
   0x30005f54:	call   *0x300010d0	// esp is changed from 0xffffc618 to 0xffffc614
   0x30005f5a:	mov    0x30001360,%edx
   0x30005f60:	mov    (%edx),%edx
   0x30005f62:	mov    0x4(%esi),%ecx
   0x30005f65:	call   *0xc(%esi)
   0x30005f68:	mov    %eax,%ecx
   0x30005f6a:	mov    0x30001364,%edx
   0x30005f70:	mov    (%edx),%edx
   0x30005f72:	call   *0x30001110
   0x30005f78:	pop    %esi		// esp: 0xffffc614
   0x30005f79:	pop    %edi		// esp: 0xffffc618
   0x30005f7a:	pop    %ebp		// esp: 0xffffc61c
   0x30005f7b:	ret  			// esp: 0xffffc620	esp should be 0xffffc62c
```

**Comment by ragmani** [comment]
This is "call   *0x300010c8"
```
- call   *0x300010c8  (0x30002245)
(gdb) x/39i 0x30002245
=> 0x30002245:	xor    %eax,%eax	// esp: 0xffffc61c
   0x30002247:	push   $0x3
   0x30002249:	pushl  0x30001000
   0x3000224f:	jmp    *0x30001028	// esp: 0xffffc614



- jmp    *0x30001028
(gdb) disas
Dump of assembler code for function DelayLoad_Helper_ObjObj:
=> 0xf7182941 <+0>:	push   %esi	// esp: 0xffffc614
   0xf7182942 <+1>:	push   %edi	// 0xffffc610
   0xf7182943 <+2>:	push   %ecx	// 0xffffc60c
   0xf7182944 <+3>:	push   %edx	// 0xffffc608
   0xf7182945 <+4>:	mov    0x10(%esp),%ecx	//0xffffc604
   0xf7182949 <+8>:	mov    0x14(%esp),%edx
   0xf718294d <+12>:	mov    %ebx,0x10(%esp)
   0xf7182951 <+16>:	mov    %ebp,0x14(%esp)
   0xf7182955 <+20>:	lea    0x14(%esp),%ebp
   0xf7182959 <+24>:	mov    %esp,%esi
   0xf718295b <+26>:	push   $0x3	// 0xffffc604
   0xf718295d <+28>:	push   %ecx	// 0xffffc600
   0xf718295e <+29>:	push   %edx	// 0xffffc5FC
   0xf718295f <+30>:	push   %eax	// 0xffffc5f8
   0xf7182960 <+31>:	push   %esi	// 0xffffc5f4
   0xf7182961 <+32>:	call   0xf72df440 <DynamicHelperWorker(TransitionBlock*, TADDR*, DWORD, Module*, INT)>	// esp: 0xffffc5f0
   0xf7182966 <+37>:	test   %eax,%eax	// esp: 0xffffc604
   0xf7182968 <+39>:	jne    0xf7182974 <DelayLoad_Helper_ObjObj+51>	// esp: 0xffffc604
   0xf718296a <+41>:	mov    (%esi),%eax				
   0xf718296c <+43>:	add    $0x8,%esp
   0xf718296f <+46>:	pop    %edi
   0xf7182970 <+47>:	pop    %esi
   0xf7182971 <+48>:	pop    %ebx
   0xf7182972 <+49>:	pop    %ebp
   0xf7182973 <+50>:	ret    
   0xf7182974 <+51>:	pop    %edx
   0xf7182975 <+52>:	pop    %ecx
   0xf7182976 <+53>:	pop    %edi
   0xf7182977 <+54>:	pop    %esi
   0xf7182978 <+55>:	pop    %ebx
   0xf7182979 <+56>:	pop    %ebp
   0xf718297a <+57>:	jmp    *%eax		// esp: 0xffffc61c
End of assembler dump.




- jmp    *%eax
=> 0xf45ef744:	pop    %eax		// esp: 0xffffc61c  	ebp: 0xffffc628		// pop ret address(0x30005f1b)
   0xf45ef745:	push   $0xf45f09b8	// esp: 0xffffc620
   0xf45ef74a:	push   $0xf63535dc	// esp: 0xffffc61c	
   0xf45ef74f:	push   %eax		// esp: 0xffffc618     
   0xf45ef750:	jmp    0xf4540c90	// esp: 0xffffc614		0xffffc61c 




- jmp    0xf4540c90
=> 0xf4540c90:	push   %ebp		// esp: 0xffffc614
   0xf4540c91:	mov    %esp,%ebp
   0xf4540c93:	sub    $0x8,%esp	// esp: 0xffffc60c
   0xf4540c96:	mov    %ecx,-0x4(%ebp)
   0xf4540c99:	mov    %edx,-0x8(%ebp)
   0xf4540c9c:	cmpl   $0x0,0xf6356518
   0xf4540ca3:	je     0xf4540caa
   0xf4540ca5:	call   0xf700de40 <JIT_DbgIsJustMyCode()>
   0xf4540caa:	nop
   0xf4540cab:	mov    -0x4(%ebp),%edx
   0xf4540cae:	lea    0x4(%edx),%edx
   0xf4540cb1:	mov    -0x4(%ebp),%eax
   0xf4540cb4:	call   0xf7183370 <JIT_WriteBarrierEAX>		// esp: 0xffffc608
   0xf4540cb9:	mov    -0x4(%ebp),%eax	// esp: 0xffffc608
   0xf4540cbc:	mov    0x8(%ebp),%edx
   0xf4540cbf:	mov    %edx,0xc(%eax)
   0xf4540cc2:	mov    -0x4(%ebp),%eax
   0xf4540cc5:	mov    0xc(%ebp),%edx
   0xf4540cc8:	mov    %edx,0x10(%eax)
   0xf4540ccb:	nop
   0xf4540ccc:	mov    %ebp,%esp
   0xf4540cce:	pop    %ebp		
   0xf4540ccf:	ret    			// esp: 0xffffc614
```

**Comment by ragmani** [comment]
This is "call   *0x300010d0"
```
- call   *0x300010d0 (0x30002245)
=> 0x30002245:	xor    %eax,%eax	// esp: 0xffffc614
   0x30002247:	push   $0x3		// esp: 0xffffc614
   0x30002249:	pushl  0x30001000	// esp: 0xffffc610
   0x3000224f:	jmp    *0x30001028	// esp: 0xffffc60c

- jmp    *0x30001028
(gdb) disas
Dump of assembler code for function DelayLoad_Helper_ObjObj:
=> 0xf7182941 <+0>:	push   %esi	// esp: 0xffffc60c
   0xf7182942 <+1>:	push   %edi	// esp: 0xffffc608
   0xf7182943 <+2>:	push   %ecx	// esp: 0xffffc604
   0xf7182944 <+3>:	push   %edx	// esp: 0xffffc600
   0xf7182945 <+4>:	mov    0x10(%esp),%ecx	// esp: 0xffffc5fc
   0xf7182949 <+8>:	mov    0x14(%esp),%edx
   0xf718294d <+12>:	mov    %ebx,0x10(%esp)
   0xf7182951 <+16>:	mov    %ebp,0x14(%esp)
   0xf7182955 <+20>:	lea    0x14(%esp),%ebp
   0xf7182959 <+24>:	mov    %esp,%esi
   0xf718295b <+26>:	push   $0x3	// esp: 0xffffc5fc
   0xf718295d <+28>:	push   %ecx	// esp: 0xffffc5f8
   0xf718295e <+29>:	push   %edx	// esp: 0xffffc5f4
   0xf718295f <+30>:	push   %eax	// esp: 0xffffc5f0
   0xf7182960 <+31>:	push   %esi	// esp: 0xffffc5ec
   0xf7182961 <+32>:	call   0xf72df440 <DynamicHelperWorker(TransitionBlock*, TADDR*, DWORD, Module*, INT)>	// esp: 0xffffc5e8
   0xf7182966 <+37>:	test   %eax,%eax	// esp: 0xffffc5fc	
   0xf7182968 <+39>:	jne    0xf7182974 <DelayLoad_Helper_ObjObj+51>
   0xf718296a <+41>:	mov    (%esi),%eax
   0xf718296c <+43>:	add    $0x8,%esp
   0xf718296f <+46>:	pop    %edi
   0xf7182970 <+47>:	pop    %esi
   0xf7182971 <+48>:	pop    %ebx
   0xf7182972 <+49>:	pop    %ebp
   0xf7182973 <+50>:	ret    
   0xf7182974 <+51>:	pop    %edx	// esp: 0xffffc5fc
   0xf7182975 <+52>:	pop    %ecx	// esp: 0xffffc600
   0xf7182976 <+53>:	pop    %edi	// esp: 0xffffc604
   0xf7182977 <+54>:	pop    %esi	// esp: 0xffffc608
   0xf7182978 <+55>:	pop    %ebx	// esp: 0xffffc60c
   0xf7182979 <+56>:	pop    %ebp	// esp: 0xffffc610
   0xf718297a <+57>:	jmp    *%eax	// esp: 0xffffc614
End of assembler dump.




- jmp    *%eax
=> 0xf45ef764:	pop    %eax		// esp: 0xffffc614
   0xf45ef765:	push   $0x30005318	// esp: 0xffffc618		
   0xf45ef76a:	push   %eax		// esp: 0xffffc614		//
   0xf45ef76b:	jmp    0xf21fe950	// esp: 0xffffc610




- jmp    0xf21fe950
=> 0xf21fe950:	call   0xf7182727 <PrecodeFixupThunk>	// esp: 0xffffc610
   0xf21fe955:	pop    %esi
   0xf21fe956:	add    %al,(%eax)
   0xf21fe958:	add    %al,(%esi)
   0xf21fe95a:	xchg   %eax,%edi
   0xf21fe95b:	cmc    


- call   0xf7182727 <PrecodeFixupThunk>
=> 0xf7182727 <PrecodeFixupThunk>:	pop    %eax	// esp: 0xffffc60c
   0xf7182728 <PrecodeFixupThunk+1>:	push   %esi	// esp: 0xffffc610
   0xf7182729 <PrecodeFixupThunk+2>:	push   %edi	// esp: 0xffffc60c
   0xf718272a <PrecodeFixupThunk+3>:	movzbl 0x2(%eax),%esi	// esp: 0xffffc608
   0xf718272e <PrecodeFixupThunk+7>:	movzbl 0x1(%eax),%edi
   0xf7182732 <PrecodeFixupThunk+11>:	mov    0x3(%eax,%esi,8),%eax
   0xf7182736 <PrecodeFixupThunk+15>:	lea    (%eax,%edi,4),%eax	
   0xf7182739 <PrecodeFixupThunk+18>:	pop    %edi	// esp: 0xffffc608
   0xf718273a <PrecodeFixupThunk+19>:	pop    %esi	// esp: 0xffffc60c
   0xf718273b <PrecodeFixupThunk+20>:	jmp    0xf7182897 <ThePreStub>	// esp: 0xffffc610





// It seems normally.
- jmp    0xf7182897 <ThePreStub>
=> 0xf7182897 <ThePreStub>:	push   %ebp		// esp: 0xffffc610
   0xf7182898 <ThePreStub+1>:	mov    %esp,%ebp	// esp: 0xffffc60c
   0xf718289a <ThePreStub+3>:	push   %ebx		// esp: 0xffffc60c
   0xf718289b <ThePreStub+4>:	push   %esi		// esp: 0xffffc608
   0xf718289c <ThePreStub+5>:	push   %edi		// esp: 0xffffc604
   0xf718289d <ThePreStub+6>:	push   %ecx		// esp: 0xffffc600
   0xf718289e <ThePreStub+7>:	push   %edx		// esp: 0xffffc5fc
   0xf718289f <ThePreStub+8>:	mov    %esp,%esi	// esp: 0xffffc5f8
   0xf71828a1 <ThePreStub+10>:	lea    -0x8(%esp),%ebx
   0xf71828a5 <ThePreStub+14>:	and    $0xf,%ebx
   0xf71828a8 <ThePreStub+17>:	sub    %ebx,%esp
   0xf71828aa <ThePreStub+19>:	push   %eax		// esp: 0xffffc5f8
   0xf71828ab <ThePreStub+20>:	push   %esi		// esp: 0xffffc5f4
   0xf71828ac <ThePreStub+21>:	test   $0xf,%esp	// esp: 0xffffc5f0
   0xf71828b2 <ThePreStub+27>:	je     0xf71828b5 <ThePreStub+30>
   0xf71828b4 <ThePreStub+29>:	int3   
   0xf71828b5 <ThePreStub+30>:	call   0xf72d8360 <PreStubWorker(TransitionBlock*, MethodDesc*)>	// esp: 0xffffc5f0		
   0xf71828ba <ThePreStub+35>:	mov    %esi,%esp	// esp: 0xffffc5f8
   0xf71828bc <ThePreStub+37>:	pop    %edx		// esp: 0xffffc5f8
   0xf71828bd <ThePreStub+38>:	pop    %ecx		// esp: 0xffffc5fc
   0xf71828be <ThePreStub+39>:	pop    %edi		// esp: 0xffffc600	
   0xf71828bf <ThePreStub+40>:	pop    %esi		// esp: 0xffffc604
   0xf71828c0 <ThePreStub+41>:	pop    %ebx		// esp: 0xffffc608
   0xf71828c1 <ThePreStub+42>:	pop    %ebp		// esp: 0xffffc60c
   0xf71828c2 <ThePreStub+43>:	jmp    *%eax		// esp: 0xffffc610
   0xf71828c4 <ThePreStub+45>:	ret    


// It seems normally.
- jmp    *%eax
=> 0xf22008f0:	push   %ebp		// esp: 0xffffc610
   0xf22008f1:	mov    %esp,%ebp	// esp: 0xffffc60c
   0xf22008f3:	sub    $0x8,%esp	// esp: 0xffffc604
   0xf22008f6:	mov    %ecx,-0x4(%ebp)
   0xf22008f9:	mov    %edx,-0x8(%ebp)
   0xf22008fc:	cmpl   $0x0,0xf6356518
   0xf2200903:	je     0xf220090a
   0xf2200905:	call   0xf700de40 <JIT_DbgIsJustMyCode()>
   0xf220090a:	nop
   0xf220090b:	mov    -0x4(%ebp),%edx
   0xf220090e:	lea    0x4(%edx),%edx
   0xf2200911:	mov    -0x8(%ebp),%eax
   0xf2200914:	call   0xf7183370 <JIT_WriteBarrierEAX>
   0xf2200919:	mov    -0x4(%ebp),%eax
   0xf220091c:	mov    0x8(%ebp),%edx
   0xf220091f:	mov    %edx,0xc(%eax)
   0xf2200922:	nop
   0xf2200923:	mov    %ebp,%esp	// esp: 0xffffc60c
   0xf2200925:	pop    %ebp		
   0xf2200926:	ret    
```

**Comment by ragmani** [comment]
cc @parjong

**Comment by parjong** [comment]
#10410 seems to be related. There may be some readytorun helpers (and thunks) that still use STDCALL (instead of CDECL).

**Comment by ragmani** [comment]
```
- jmp    0xf4540c90
=> 0xf4540c90:	push   %ebp		// esp: 0xffffc614
   0xf4540c91:	mov    %esp,%ebp
   0xf4540c93:	sub    $0x8,%esp	// esp: 0xffffc60c
   0xf4540c96:	mov    %ecx,-0x4(%ebp)
   0xf4540c99:	mov    %edx,-0x8(%ebp)
   0xf4540c9c:	cmpl   $0x0,0xf6356518
   0xf4540ca3:	je     0xf4540caa
   0xf4540ca5:	call   0xf700de40 <JIT_DbgIsJustMyCode()>
   0xf4540caa:	nop
   0xf4540cab:	mov    -0x4(%ebp),%edx
   0xf4540cae:	lea    0x4(%edx),%edx
   0xf4540cb1:	mov    -0x4(%ebp),%eax
   0xf4540cb4:	call   0xf7183370 <JIT_WriteBarrierEAX>		// esp: 0xffffc608
   0xf4540cb9:	mov    -0x4(%ebp),%eax	// esp: 0xffffc608
   0xf4540cbc:	mov    0x8(%ebp),%edx
   0xf4540cbf:	mov    %edx,0xc(%eax)
   0xf4540cc2:	mov    -0x4(%ebp),%eax
   0xf4540cc5:	mov    0xc(%ebp),%edx
   0xf4540cc8:	mov    %edx,0x10(%eax)
   0xf4540ccb:	nop
   0xf4540ccc:	mov    %ebp,%esp
   0xf4540cce:	pop    %ebp		
   0xf4540ccf:	ret    			// esp: 0xffffc614
```
```
- jmp    *%eax
=> 0xf22008f0:	push   %ebp		// esp: 0xffffc610
   0xf22008f1:	mov    %esp,%ebp	// esp: 0xffffc60c
   0xf22008f3:	sub    $0x8,%esp	// esp: 0xffffc604
   0xf22008f6:	mov    %ecx,-0x4(%ebp)
   0xf22008f9:	mov    %edx,-0x8(%ebp)
   0xf22008fc:	cmpl   $0x0,0xf6356518
   0xf2200903:	je     0xf220090a
   0xf2200905:	call   0xf700de40 <JIT_DbgIsJustMyCode()>
   0xf220090a:	nop
   0xf220090b:	mov    -0x4(%ebp),%edx
   0xf220090e:	lea    0x4(%edx),%edx
   0xf2200911:	mov    -0x8(%ebp),%eax
   0xf2200914:	call   0xf7183370 <JIT_WriteBarrierEAX>
   0xf2200919:	mov    -0x4(%ebp),%eax
   0xf220091c:	mov    0x8(%ebp),%edx
   0xf220091f:	mov    %edx,0xc(%eax)
   0xf2200922:	nop
   0xf2200923:	mov    %ebp,%esp	// esp: 0xffffc60c
   0xf2200925:	pop    %ebp		
   0xf2200926:	ret    
```
" 0xf4540ccf: ret" was changed from "ret 0x8" and  "0xf2200926: ret" was changed from "ret 0x4" after [#10410](https://github.com/dotnet/coreclr/pull/10410).

**Comment by ragmani** [comment]
The readytorun TCs(mainv1 and mainv2) passed after #11063 .
