### ISSUE TITLE
JIT causes ArgumentNullException

### ISSUE THREAD

**Issue by Sebmaster** [dotnet/coreclr#10994]
(hoping I'm in the right repo for this one)

I'll check if I can create a much smaller repro case than the full project I'm currently working on, but the JIT in .NET core is causing my program to reproducibly crash (on only 1 system config) with this exception:

```
Parameter name: source
    at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
    at PoE.Program.<>c__DisplayClass4_0.<UpdateBatch>b__2(TermsQueryDescriptor`1 t) in /app/src/PoE/Program.cs:line 36
    at Nest.Extensions.InvokeOrDefault[T,TReturn](Func`2 func, T default)
    at Nest.QueryContainerDescriptor`1.WrapInContainer[TQuery,TQueryInterface](Func`2 create, Action`2 assign)
    at Nest.DeleteByQueryDescriptor`1.<>c__DisplayClass5_0.<Query>b__0(IDeleteByQueryRequest a)
    at Nest.Fluent.Assign[TDescriptor,TInterface](TDescriptor self, Action`1 assign)
    at Nest.ElasticClient.DeleteByQueryAsync[T](Func`2 selector, CancellationToken cancellationToken)
```
where the line in question is:
```csharp
await client.DeleteByQueryAsync<ElasticData>(desc => desc.Query(q => q.Terms(t => t.Field(d => d.stash.id).Terms(
    stashes.Select(s => s.id)
))));
```

The reason I assumed it was the JIT was that `COMPlus_JITMinOpts=1` helped initially, however I'm now able to reproduce this with that env var set as well (still works on all other system configs though).

**System Info**
Happens on:
Executing it in a container, from `microsoft/dotnet:1.1-runtime`.

`uname -a`: `Linux host 4.9.16-coreos-r1 #1 SMP Fri Mar 31 02:07:42 UTC 2017 x86_64 Intel(R) Xeon(R) CPU E5-2676 v3 @ 2.40GHz GenuineIntel GNU/Linux` (CoreOS 1298.7.0)
`dotnet --version`: ` Version  : 1.1.0, Build: 928f77c4bc3f49d892459992fb6e1d5542cb5e86`

Does not happen on:

* Docker for Windows
  `uname -a`: `Linux 50a02cec4a11 4.9.13-moby #1 SMP Sat Mar 25 02:48:44 UTC 2017 x86_64 GNU/Linux`
  `dotnet --version`: ` Version  : 1.1.0, Build: 928f77c4bc3f49d892459992fb6e1d5542cb5e86`
* Native execution with a .NET core on Windows
  `dotnet --version`: `1.0.0-rc4-004771`

Is this already known/fixed so I don't have to dig into a repro? Tried searching in the issues but couldn't find anything, really.

**Comment by Sebmaster** [comment]
Nevermind. Not the CLRs fault.
