### ISSUE TITLE
[ARM/Linux] System.Runtime.CompilerServices.Unsafe.Tests failures (System.DataMisalignedException)

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#11200]
Unaligned access on double and struct seems to throw ``System.DataMisalignedException``:
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.CompilerServices.Unsafe.Tests
Discovered:  System.Runtime.CompilerServices.Unsafe.Tests
Starting:    System.Runtime.CompilerServices.Unsafe.Tests
   System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Struct()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Double [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Double()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Struct()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Double [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Double()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Struct()
   System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_Ptr_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_Ptr_Struct()
Finished:    System.Runtime.CompilerServices.Unsafe.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.CompilerServices.Unsafe.Tests  Total: 113, Errors: 0, Failed: 6, Skipped: 0, Time: 306.077s
```

**Comment by parjong** [comment]
Here is the jit disasm of ``WriteUnaligned_ByRef_Struct``:
```
; Assembly listing for method System.Runtime.CompilerServices.UnsafeTests:WriteUnaligned_ByRef_Struct()
; Emitting BLENDED_CODE for generic ARM CPU
; optimized code
; r11 based frame
; partially interruptible
; Final local variable assignments
;
;  V00 loc0         [V00,T03] (  4,  4   )     ref  ->   r1         class-hnd
;  V01 loc1         [V01    ] (  3,  3   )  struct (16) [sp+0x00]   do-not-enreg[XS] must-init addr-exposed double-align
;* V02 loc2         [V02    ] (  0,  0   )     int  ->  zero-ref    ld-addr-op double-align
;  V03 tmp0         [V03,T00] (  4,  8   )   byref  ->   r3
;* V04 tmp1         [V04    ] (  0,  0   )   byref  ->  zero-ref
;* V05 tmp2         [V05    ] (  0,  0   )   byref  ->  zero-ref
;* V06 tmp3         [V06    ] (  0,  0   )     int  ->  zero-ref    ld-addr-op double-align
;* V07 tmp4         [V07    ] (  0,  0   )     int  ->  zero-ref
;  V08 tmp5         [V08,T01] (  3,  6   )     ref  ->   r4         class-hnd exact
;* V09 tmp6         [V09    ] (  0,  0   )  double  ->  zero-ref
;  V10 tmp7         [V10,T02] (  3,  6   )     ref  ->   r4         class-hnd exact
;  V11 tmp8         [V11    ] (  2,  2   )     int  ->  [sp+0x00]   do-not-enreg[X] addr-exposed V01.Int32(offs=0x00) P-DEP
;  V12 tmp9         [V12    ] (  2,  2   )  double  ->  [sp+0x08]   do-not-enreg[X] addr-exposed V01.Double(offs=0x08) P-DEP
;  V13 tmp10        [V13,T04] (  2,  2   )     int  ->   r2         V02.Int32(offs=0x00) P-INDEP
;  V14 tmp11        [V14,T05] (  2,  2   )  double  ->   f8:f9      V02.Double(offs=0x08) P-INDEP
;  V15 tmp12        [V15,T06] (  2,  2   )     int  ->   r2         V06.Int32(offs=0x00) P-INDEP
;  V16 tmp13        [V16,T07] (  2,  2   )  double  ->   f8:f9      V06.Double(offs=0x08) P-INDEP
;# V17 OutArgs      [V17    ] (  1,  1   )  lclBlk ( 0) [sp+0x00]
;
; Lcl frame size = 20

G_M5608_IG01:
000000  E92D 4810      push    {r4,r11,lr}
000004  B085           sub     sp, 20
000006  F10D 0B18      add     r11, sp, 24
00000A  2000           movs    r0, 0
00000C  9000           str     r0, [sp] // [V01 loc1]
00000E  9001           str     r0, [sp+0x04]    // [V01 loc1+0x04]
000010  9002           str     r0, [sp+0x08]    // [V01 loc1+0x08]
000012  9003           str     r0, [sp+0x0c]    // [V01 loc1+0x0c]

G_M5608_IG02:
000014  F249 30FA      movw    r0, 0x93fa
000018  F2C7 400A      movt    r0, 0x740a
00001C  2111           movs    r1, 17
00001E  F244 6399      movw    r3, 0x4699
000022  F2C7 6372      movt    r3, 0x7672
000026  4798           blx     r3               // CORINFO_HELP_NEWARR_1_VC
000028  4601           mov     r1, r0
00002A  F101 0309      add     r3, r1, 9
00002E  F64C 5215      movw    r2, 0xcd15
000032  F2C0 725B      movt    r2, 0x75b
000036  F648 705C      movw    r0, 0x8f5c
00003A  F2CF 50C2      movt    r0, 0xf5c2
00003E  F645 4428      movw    r4, 0x5c28
000042  F2C4 040B      movt    r4, 0x400b
000046  EC44 0B14      vmov.i2d d8, r0, r4
00004A  601A           str     r2, [r3]
00004C  ED83 4B02      vstr    d8, [r3+8]
000050  A800           add     r0, sp, 0        // [V01 loc1]
000052  F645 73E1      movw    r3, 0x5fe1
000056  F6C6 7328      movt    r3, 0x6f28
00005A  4798           blx     r3               // System.Runtime.CompilerServices.Int32Double:Aligned(ref):struct
...
```

**Comment by parjong** [comment]
\CC @hqueue @hseok-oh @sjsinju @jyoungyun @lemmaa

**Comment by parjong** [comment]
@BruceForstall Could you please reopen this issue? #11224 resolves two double-related failures, but struct-related cases still fails:
```
$ corerun ./xunit.console.netcore.exe *.Tests.dll -notrait Benchmark=true -notrait category=nonnetcoreapptests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.CompilerServices.Unsafe.Tests
Discovered:  System.Runtime.CompilerServices.Unsafe.Tests
Starting:    System.Runtime.CompilerServices.Unsafe.Tests
   System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_ByRef_Struct()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_Ptr_Struct()
   System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.ReadUnaligned_ByRef_Struct()
   System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_Ptr_Struct [FAIL]
      System.DataMisalignedException : A datatype misalignment was detected in a load or store instruction.
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.WriteUnaligned_Ptr_Struct()
Finished:    System.Runtime.CompilerServices.Unsafe.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.CompilerServices.Unsafe.Tests  Total: 113, Errors: 0, Failed: 4, Skipped: 0, Time: 114.342s
```
