### ISSUE TITLE
AssemblyLoadContext.GetAssemblyName throws unexpected exception

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#11499]
In this simple test program
```
using System;
using System.Runtime.Loader;

namespace Test
{
    public class Program
    {
        public static void Main(String [] args)
        {
            AssemblyLoadContext.GetAssemblyName(args[0]);
        }
    }
}
```

The program is expected to throw `BadImageFormatException` if it cannot load the file specified.
However, it throws a `MissingMethodException`.

```
CoreRun.exe Program.exe <native.dll>

Unhandled Exception: System.MissingMethodException: .ctor ---> System.MissingMethodException: .ctor
   --- End of inner exception stack trace ---
   at System.Reflection.AssemblyName.nGetFileInformation(String s)
   at Test.Program.Main(String[] args)

D:\coreclr\bin\tests\Windows_NT.x64.Release\Tests\Core_Root>
```

**Comment by jkotas** [comment]
Regression introduce by https://github.com/dotnet/coreclr/pull/11314

**Comment by karelz** [comment]
Post-ZBB as it was created very late. Looks like must-have for 2.0.
