### ISSUE TITLE
[x86/Linux] Regression on thread-related tests (when tracing is enabled)

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#11539]
0d5d0b40c4ecb3f7f4fcdc83a5a51a2ee65dfc89 shows regressions on thread-related tests:
```
  JIT.Performance.CodeQuality.SIMD.RayTracer.RayTracer.RayTracer
  JIT.Regression.CLR-x86-JIT.V2.0-Beta2.b425314.b425314.b425314
  JIT.Regression.CLR-x86-JIT.V2.0-Beta2.b426654.b426654.b426654
  JIT.superpmi.superpmicollect.superpmicollect
  baseservices.threading.generics.Monitor.EnterExit01.EnterExit01
  baseservices.threading.generics.Monitor.EnterExit02.EnterExit02
  baseservices.threading.generics.Monitor.EnterExit03.EnterExit03
  baseservices.threading.generics.Monitor.EnterExit04.EnterExit04
  baseservices.threading.generics.Monitor.EnterExit05.EnterExit05
  baseservices.threading.generics.Monitor.EnterExit06.EnterExit06
  baseservices.threading.generics.Monitor.EnterExit07.EnterExit07
  baseservices.threading.generics.Monitor.EnterExit08.EnterExit08
  baseservices.threading.generics.Monitor.EnterExit09.EnterExit09
  baseservices.threading.generics.Monitor.EnterExit10.EnterExit10
  baseservices.threading.generics.Monitor.EnterExit11.EnterExit11
  baseservices.threading.generics.Monitor.EnterExit12.EnterExit12
  baseservices.threading.generics.Monitor.EnterExit13.EnterExit13
  baseservices.threading.generics.Monitor.EnterExit14.EnterExit14
  baseservices.threading.generics.Monitor.TryEnter01.TryEnter01
  baseservices.threading.generics.Monitor.TryEnter03.TryEnter03
  baseservices.threading.generics.Monitor.TryEnter04.TryEnter04
  baseservices.threading.generics.Monitor.TryEnter05.TryEnter05
  baseservices.threading.generics.Monitor.TryEnter06.TryEnter06
  baseservices.threading.generics.TimerCallback.thread01.thread01
  baseservices.threading.generics.TimerCallback.thread02.thread02
  baseservices.threading.generics.TimerCallback.thread03.thread03
  baseservices.threading.generics.TimerCallback.thread04.thread04
  baseservices.threading.generics.TimerCallback.thread05.thread05
  baseservices.threading.generics.TimerCallback.thread06.thread06
  baseservices.threading.generics.TimerCallback.thread07.thread07
  baseservices.threading.generics.TimerCallback.thread08.thread08
  baseservices.threading.generics.TimerCallback.thread09.thread09
  baseservices.threading.generics.TimerCallback.thread10.thread10
  baseservices.threading.generics.TimerCallback.thread11.thread11
  baseservices.threading.generics.TimerCallback.thread12.thread12
  baseservices.threading.generics.TimerCallback.thread13.thread13
  baseservices.threading.generics.TimerCallback.thread14.thread14
  baseservices.threading.generics.TimerCallback.thread15.thread15
  baseservices.threading.generics.TimerCallback.thread16.thread16
  baseservices.threading.generics.TimerCallback.thread17.thread17
  baseservices.threading.generics.TimerCallback.thread18.thread18
  baseservices.threading.generics.TimerCallback.thread19.thread19
  baseservices.threading.generics.TimerCallback.thread20.thread20
  baseservices.threading.generics.TimerCallback.thread21.thread21
  baseservices.threading.generics.TimerCallback.thread22.thread22
  baseservices.threading.generics.TimerCallback.thread23.thread23
  baseservices.threading.generics.TimerCallback.thread24.thread24
  baseservices.threading.generics.TimerCallback.thread25.thread25
  baseservices.threading.generics.TimerCallback.thread26.thread26
  baseservices.threading.generics.TimerCallback.thread27.thread27
  baseservices.threading.generics.TimerCallback.thread28.thread28
  baseservices.threading.generics.TimerCallback.thread29.thread29
  baseservices.threading.generics.TimerCallback.thread30.thread30
  baseservices.threading.generics.TimerCallback.tighttimercallback.tighttimercallback
  baseservices.threading.generics.WaitCallback.thread01.thread01
  baseservices.threading.generics.WaitCallback.thread02.thread02
  baseservices.threading.generics.WaitCallback.thread03.thread03
  baseservices.threading.generics.WaitCallback.thread04.thread04
  baseservices.threading.generics.WaitCallback.thread05.thread05
  baseservices.threading.generics.WaitCallback.thread06.thread06
  baseservices.threading.generics.WaitCallback.thread07.thread07
  baseservices.threading.generics.WaitCallback.thread08.thread08
  baseservices.threading.generics.WaitCallback.thread09.thread09
  baseservices.threading.generics.WaitCallback.thread10.thread10
  baseservices.threading.generics.WaitCallback.thread11.thread11
  baseservices.threading.generics.WaitCallback.thread12.thread12
  baseservices.threading.generics.WaitCallback.thread13.thread13
  baseservices.threading.generics.WaitCallback.thread14.thread14
  baseservices.threading.generics.WaitCallback.thread15.thread15
  baseservices.threading.generics.WaitCallback.thread16.thread16
  baseservices.threading.generics.WaitCallback.thread17.thread17
  baseservices.threading.generics.WaitCallback.thread18.thread18
  baseservices.threading.generics.WaitCallback.thread19.thread19
  baseservices.threading.generics.WaitCallback.thread20.thread20
  baseservices.threading.generics.WaitCallback.thread21.thread21
  baseservices.threading.generics.WaitCallback.thread22.thread22
  baseservices.threading.generics.WaitCallback.thread23.thread23
  baseservices.threading.generics.WaitCallback.thread24.thread24
  baseservices.threading.generics.WaitCallback.thread25.thread25
  baseservices.threading.generics.WaitCallback.thread26.thread26
  baseservices.threading.generics.WaitCallback.thread27.thread27
  baseservices.threading.generics.WaitCallback.thread28.thread28
  baseservices.threading.generics.WaitCallback.thread29.thread29
  baseservices.threading.generics.WaitCallback.thread30.thread30
  baseservices.threading.monitor.enter.monitorenter.monitorenter
  baseservices.threading.monitor.isentered.monitorisentered.monitorisentered
  baseservices.threading.regressions.13662.13662-a.13662-a
  baseservices.threading.regressions.13662.13662-b.13662-b
  baseservices.threading.regressions.13662.13662-simple.13662-simple
  baseservices.threading.regressions.30032.30032.30032
  baseservices.threading.regressions.beta1.347011.347011
  baseservices.threading.regressions.beta2.437044.437044
  baseservices.threading.regressions.devdiv489437.test489437.test489437
  baseservices.threading.regressions.whidbey_m3.200176.200176
  baseservices.threading.threadstatic.threadstatic07.threadstatic07
```

All the regression hit the following assertion failure:
```
 Assert failure(PID 26684 [0x0000683c], Thread: 26684 [0x683c]): !curThread->HasUnbreakableLock() && (curThread->m_StateNC & Thread::TSNC_OwnsSpinLock) == 0
````

**Comment by parjong** [comment]
@jkotas @janvorli Is there any changes on threading?

**Comment by jkotas** [comment]
I am not aware of anything. What is the stacktrace where this assert hits?

**Comment by parjong** [comment]
It seems that this issue is related with event pipe:
```
(gdb) bt
...
#9  0xf6c18f57 in DbgAssertDialog (szFile=0xf7962017 "/home2/parjong/projects/dotnet/coreclr/src/vm/callhelpers.cpp", iLine=129,
    szExpr=0xf79620e3 "!curThread->HasUnbreakableLock() && (curThread->m_StateNC & Thread::TSNC_OwnsSpinLock) == 0") at /home2/parjong/projects/dotnet/coreclr/src/utilcode/debug.cpp:735
#10 0xf6e821e3 in CallDescrWorker (pCallDescrData=0xffff7f28) at /home2/parjong/projects/dotnet/coreclr/src/vm/callhelpers.cpp:128
#11 0xf6e81fb3 in CallDescrWorkerWithHandler (pCallDescrData=0xffff7f28, fCriticalCall=0) at /home2/parjong/projects/dotnet/coreclr/src/vm/callhelpers.cpp:78
#12 0xf6e824d9 in DispatchCallDebuggerWrapper(CallDescrData*, ContextTransitionFrame*, int)::$_1::operator()(DispatchCallDebuggerWrapper(CallDescrData*, ContextTransitionFrame*, int)::Param*) const (
    this=0xffff7ed0, pParam=0xffff7ed8) at /home2/parjong/projects/dotnet/coreclr/src/vm/callhelpers.cpp:169
#13 0xf6e82318 in DispatchCallDebuggerWrapper (pCallDescrData=0xffff7f28, pFrame=0x0, fCriticalCall=0) at /home2/parjong/projects/dotnet/coreclr/src/vm/callhelpers.cpp:173
#14 0xf6e826a1 in DispatchCallSimple (pSrc=0xffff80d8, numStackSlotsToCopy=0, pTargetAddress=4098012688, dwDispatchCallSimpleFlags=2) at /home2/parjong/projects/dotnet/coreclr/src/vm/callhelpers.cpp:222
#15 0xf6d4d560 in MethodTable::RunClassInitEx (this=0xf44571a0, pThrowable=0xffff8400) at /home2/parjong/projects/dotnet/coreclr/src/vm/methodtable.cpp:3294
#16 0xf6d4f22c in MethodTable::DoRunClassInitThrowing (this=0xf44571a0) at /home2/parjong/projects/dotnet/coreclr/src/vm/methodtable.cpp:3529
#17 0xf6d50989 in MethodTable::CheckRunClassInitThrowing (this=0xf44571a0) at /home2/parjong/projects/dotnet/coreclr/src/vm/methodtable.cpp:3686
#18 0xf6f486ae in JIT_GetSharedGCStaticBase_Helper (dwClassDomainID=1349, pLocalModule=0xf62a2018) at /home2/parjong/projects/dotnet/coreclr/src/vm/jithelpers.cpp:1472
#19 0xf6f480e9 in JIT_GetSharedGCStaticBase_Portable (dwClassDomainID=1349, moduleDomainID=4129955864) at /home2/parjong/projects/dotnet/coreclr/src/vm/jithelpers.cpp:1416
#20 0xf62b24c1 in ?? ()
#21 0xf442bef4 in ?? ()
#22 0xf442b9c5 in ?? ()
#23 0xf442b4e2 in ?? ()
#24 0xf710bd21 in UMThunkStub () at /home2/parjong/projects/dotnet/coreclr/src/vm/i386/umthunkstub.S:102
#25 0xf6f0a341 in EventPipeProvider::InvokeCallback (this=0x80fc810) at /home2/parjong/projects/dotnet/coreclr/src/vm/eventpipeprovider.cpp:181
#26 0xf6f0a210 in EventPipeProvider::SetConfiguration (this=0x80fc810, providerEnabled=true, keywords=-1, providerLevel=Verbose) at /home2/parjong/projects/dotnet/coreclr/src/vm/eventpipeprovider.cpp:125
#27 0xf6f0515f in EventPipeConfiguration::RegisterProvider (this=0x805cc98, provider=...) at /home2/parjong/projects/dotnet/coreclr/src/vm/eventpipeconfiguration.cpp:88
#28 0xf6f09dad in EventPipeProvider::EventPipeProvider (this=0x80fc810, providerID=..., pCallbackFunction=0xf62b2616, pCallbackData=0x0) at /home2/parjong/projects/dotnet/coreclr/src/vm/eventpipeprovider.cpp:34
#29 0xf6f038f5 in EventPipeInternal::CreateProvider (providerID=..., pCallbackFunc=0xf62b2616) at /home2/parjong/projects/dotnet/coreclr/src/vm/eventpipe.cpp:321
```

**Comment by jkotas** [comment]
cc @brianrob

**Comment by jkotas** [comment]
Brian, could you please take a look? It is likely affecting all platforms.

**Comment by brianrob** [comment]
This is affecting all platforms.  The EventPipe holds a Crst while it calls into EventSources to enable them.  It looks like the assert just fires on x86.  @jkotas, I take it regardless of the fact that an assert is not firing on x64 that it is unsafe to hold the Crst while calling into managed code on all platforms/architectures?  I'll work on a fix for this.

**Comment by parjong** [comment]
This issue does not appear any more.

**Comment by brianrob** [comment]
I actually suspect that this is a real issue that will appear if tracing is enabled.  Re-opening so that I can investigate.

**Comment by brianrob** [comment]
After talking with @jkotas, moving this to 2.1.  This doesn't affect 2.0 Windows which is the only place we ship x86 - this only runs on Linux which is x64 only.
