### ISSUE TITLE
[x86/Linux] segmentation fault with sos command

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#11704]
#11666 and #11701 resolves undefined references on SOS plugin on x86/Linux, and thus we could load SOS plugin. 

Unfortunately, sos command results in segmentation fault:
```
$  lldb-3.6 -o "plugin load dotnet-overlay/Linux.x86.Debug.Debug/libsosplugin.so" dotnet-overlay/Linux.x86.Debug.Debug/corerun coreclr-analyze/throw/bin/Debug/netcoreapp1.0/hello.dll
(lldb) target create "dotnet-overlay/Linux.x86.Debug.Debug/corerun"
Current executable set to 'dotnet-overlay/Linux.x86.Debug.Debug/corerun' (i386).
(lldb) settings set -- target.run-args  "coreclr-analyze/throw/bin/Debug/netcoreapp1.0/hello.dll"
(lldb) plugin load dotnet-overlay/Linux.x86.Debug.Debug/libsosplugin.so
(lldb) r
Process 17011 launching
Process 17011 launched: '/home2/parjong/projects/dotnet/dotnet-overlay/Linux.x86.Debug.Debug/corerun' (i386)
Hello World!
Nice to meet you! 3

Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.
   at ConsoleApplication.Program.Throw() in /home/parjong/projects/dotnet/coreclr-analyze/throw/src/Program.cs:line 22
   at ConsoleApplication.Program.Main(String[] args) in /home/parjong/projects/dotnet/coreclr-analyze/throw/src/Program.cs:line 12
Process 17011 stopped
* thread #1: tid = 17011, 0xf7fd9d80, name = 'corerun', stop reason = signal SIGABRT
    frame #0: 0xf7fd9d80
-> 0xf7fd9d80: popl   %ebp
   0xf7fd9d81: popl   %edx
   0xf7fd9d82: popl   %ecx
   0xf7fd9d83: retl
(lldb) sos Help
Segmentation fault (core dumped)
```

**Comment by parjong** [comment]
#11705 resolves this.
