### ISSUE TITLE
Second crossgen of System.Private.Corelib.dll produces bad native image

### ISSUE THREAD

**Issue by briansull** [dotnet/coreclr#11761]
Currently our builds produce a crossgen-ed System.Private.CoreLib.dll that contains a native image section.
Re-running crossgen again using that as the input produced a slightly different version with some code differences.  These difference are found when class static array aggregates are directly initialized to a static data array that is contained in the RVA static area.  When the new twice crossgen-ed version of System.Private.CoreLib.dll  is used there will be a crash or other incorrect program behavior.

To Repro: perform a build and run:

crossgen System.Private.Corelib.dll
ren System.Private.Corelib.dll System.Private.Corelib.dll.orig
ren System.Private.Corelib.ni.dll System.Private.Corelib.dll

Run any test

```
Assert Failure
Expression: [Recursive resource lookup bug]
Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_DivideByZero
Stack Trace:
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.DivideByZeroException..ctor()
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Globalization.CultureData.GetCultureData(String cultureName, Boolean useUserOverride)
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32 lcid, String name, String altName)
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(Assembly a, UltimateResourceFallbackLocation& fallbackLocation)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(Type resourceSource)
   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.DivideByZeroException..ctor()
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Globalization.CultureData.GetCultureData(String cultureName, Boolean useUserOverride)
   at System.Globalization.CultureInfo.InitializeFromName(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo.GetCultureByName(String name, Boolean userOverride)
   at System.Globalization.CultureInfo.GetUserDefaultCulture()
   at System.Globalization.CultureInfo.Init()
   at System.Globalization.CultureInfo..cctor()
   at System.StringComparer..cctor()
   at System.AppDomainSetup.SetCompatibilitySwitches(IEnumerable`1 switches)
   at System.AppDomain.PrepareDataForSetup(String friendlyName, AppDomainSetup setup, Evidence providedSecurityInfo, Evidence creatorsSecurityInfo, IntPtr parentSecurityDescriptor, String sandboxName, String[] propertyNames, String[] propertyValues)

```

I have also seen other failure modes.

**Comment by briansull** [comment]
A typical diff can be found in this method: System.Math:.cctor()


Before (working codegen)
```
; Assembly listing for method System.Math:.cctor()
; Emitting BLENDED_CODE for X64 CPU with SSE2
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 tmp0         [V00,T00] (  6, 12   )     ref  ->  rdi         class-hnd
;  V01 OutArgs      [V01    ] (  1,  1   )  lclBlk (32) [rsp+0x00]  
;  V02 cse0         [V02,T01] (  6,  6   )    long  ->  rsi        
;
; Lcl frame size = 40

G_M15634_IG01:
       57                   push     rdi
       56                   push     rsi
       4883EC28             sub      rsp, 40

G_M15634_IG02:
       488B3500000000       mov      rsi, qword ptr [(reloc)]
       488BCE               mov      rcx, rsi
       BA71000000           mov      edx, 113
       E800000000           call     CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
       F20F100500000000     movsd    xmm0, qword ptr [reloc @RWD00]
       F20F1180B8070000     movsd    qword ptr [rax+07B8H], xmm0
       488D0D00000000       lea      rcx, [(reloc)]
       BA10000000           mov      edx, 16
       E800000000           call     CORINFO_HELP_NEWARR_1_VC
       488BF8               mov      rdi, rax
       488D1500000000       lea      rdx, [(reloc)]
       488D4F10             lea      rcx, bword ptr [rdi+16]
       41B880000000         mov      r8d, 128
       E800000000           call     CORINFO_HELP_MEMCPY
       488BCE               mov      rcx, rsi
       BA71000000           mov      edx, 113
       E800000000           call     CORINFO_HELP_GETSHARED_GCSTATIC_BASE
       488D8850010000       lea      rcx, bword ptr [rax+336]
       488BD7               mov      rdx, rdi
       E800000000           call     CORINFO_HELP_ASSIGN_REF
       90                   nop      

G_M15634_IG03:
       4883C428             add      rsp, 40
       5E                   pop      rsi
       5F                   pop      rdi
       C3                   ret      

; Total bytes of code 120, prolog size 6 for method System.Math:.cctor()
; ============================================================
```
After (non-working codegen)

```
; Assembly listing for method System.Math:.cctor()
; Emitting BLENDED_CODE for X64 CPU with SSE2
; optimized code
; rsp based frame
; partially interruptible
; Final local variable assignments
;
;  V00 tmp0         [V00,T00] (  4,  8   )     ref  ->  rdi         class-hnd
;* V01 tmp1         [V01    ] (  0,  0   )  struct ( 8) zero-ref   
;  V02 tmp2         [V02,T02] (  2,  2   )     ref  ->  rdx         V01.m_ptr(offs=0x00) P-INDEP
;  V03 OutArgs      [V03    ] (  1,  1   )  lclBlk (32) [rsp+0x00]  
;  V04 cse0         [V04,T01] (  6,  6   )    long  ->  rsi        
;
; Lcl frame size = 40

G_M15634_IG01:
       57                   push     rdi
       56                   push     rsi
       4883EC28             sub      rsp, 40

G_M15634_IG02:
       488B3500000000       mov      rsi, qword ptr [(reloc)]
       488BCE               mov      rcx, rsi
       BA71000000           mov      edx, 113
       E800000000           call     CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
       F20F100500000000     movsd    xmm0, qword ptr [reloc @RWD00]
       F20F1180B8070000     movsd    qword ptr [rax+07B8H], xmm0
       488D0D00000000       lea      rcx, [(reloc)]
       BA10000000           mov      edx, 16
       E800000000           call     CORINFO_HELP_NEWARR_1_VC
       488BF8               mov      rdi, rax
       488D0D00000000       lea      rcx, [(reloc)]
       E800000000           call     CORINFO_HELP_FIELDDESC_TO_STUBRUNTIMEFIELD
       488BD0               mov      rdx, rax
       488BCF               mov      rcx, rdi
       E800000000           call     System.Runtime.CompilerServices.RuntimeHelpers:InitializeArray(ref,struct)
       488BCE               mov      rcx, rsi
       BA71000000           mov      edx, 113
       E800000000           call     CORINFO_HELP_GETSHARED_GCSTATIC_BASE
       488D8850010000       lea      rcx, bword ptr [rax+336]
       488BD7               mov      rdx, rdi
       E800000000           call     CORINFO_HELP_ASSIGN_REF
       90                   nop      

G_M15634_IG03:
       4883C428             add      rsp, 40
       5E                   pop      rsi
       5F                   pop      rdi
       C3                   ret      

; Total bytes of code 121, prolog size 6 for method System.Math:.cctor()
; ============================================================
```

The non workering version have a call to the the JIT helper CORINFO_HELP_FIELDDESC_TO_STUBRUNTIMEFIELD followed by a call to CompilerServices.RuntimeHelpers:InitializeArray

Where as the working code start ioff using a BlkCopy which is either expanded inline to turns into a call to MemCpy for larger arrays.

**Comment by briansull** [comment]
The following early out in zapinfo.cpp is causing the issue:


```
    // FieldDesc::SaveContents() does not save the RVA blob for IJW modules.  [BUG]
    if (!m_pImage->m_ModuleDecoder.IsILOnly())
        return NULL;
```

**Comment by briansull** [comment]
@jkotas PTAL

**Comment by jkotas** [comment]
From @briansull :

> Can we get this in the release/2.0.0 branch.
> Without this, It is difficult to do IBC training/optimizations

**Comment by gkhanna79** [comment]
@jkotas can this be closed if the fix is in 2.0.0 branch?

**Comment by mzji** [comment]
This bug is still happens:
```
fail: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[0]
      An unhandled exception has occurred: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
      Parameter name: bytes
System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'Unicode (UTF-8)' fallback 'System.Text.EncoderReplacementFallback'.
Parameter name: bytes
   at System.Text.Encoding.ThrowBytesOverflow()
   at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
   at System.Text.UTF8Encoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS baseEncoder)
   at System.Text.EncoderNLS.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
   at System.Text.EncoderNLS.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.FlushInternal(Boolean flushEncoder)
   at Microsoft.AspNetCore.WebUtilities.HttpResponseStreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.ViewResult.<ExecuteResultAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeResultAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextResultFilterAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Core.Internal.ResourceInvoker.<InvokeAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
Assert Failure
Expression: [Recursive resource lookup bug]
Description: Infinite recursion during resource lookup within System.Private.CoreLib.  This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names.  Resource name: Arg_DivideByZero
Stack Trace:
   at System.SR.InternalGetResourceString(String key)

   at System.SR.GetResourceString(String resourceKey, String defaultString)

   at System.DivideByZeroException..ctor()

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)

   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)

   at System.Resources.RuntimeResourceSet.GetString(String key, Boolean ignoreCase)

   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)

   at System.SR.InternalGetResourceString(String key)

   at System.SR.GetResourceString(String resourceKey, String defaultString)

   at System.DivideByZeroException..ctor()

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)

   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)

   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)

   at System.Resources.RuntimeResourceSet.GetString(String key, Boolean ignoreCase)

   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)

   at System.SR.InternalGetResourceString(String key)

   at System.SR.GetResourceString(String resourceKey, String defaultString)

   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)

   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)

   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)

   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)

   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)

   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)

   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)

   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)

   at System.Resources.ResourceManager.GetString(String name)

   at System.SR.GetResourceString(String resourceKey, String defaultString)

   at System.Net.Sockets.Socket.GetException(SocketError error, Boolean wrapExceptionsInIOExceptions)

   at System.Net.Sockets.Socket.CompleteSendReceive(Socket s, Int32TaskSocketAsyncEventArgs saea, Boolean isReceive)

   at System.Net.Sockets.Socket.<>c.<.cctor>b__316_1(Object s, SocketAsyncEventArgs e)

   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)

   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncFailure(SocketError socketError, Int32 bytesTransferred, SocketFlags flags)

   at System.Net.Sockets.SocketAsyncEventArgs.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlaApplication is shutting down...
pped* nativeOverlapped)

   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__200_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)

   at System.Threading.ThreadPoolBoundHandleOverlapped.CompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)

   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
```
This is part of captured console output of my server application using ASP.Net Core 2.0 Preview 1.

**Comment by gkhanna79** [comment]
The issue in question pertained to recompiling of a precompiled managed assembly, which is development time (usually NET Core team specific) scenario. I doubt you are running into it @mzji. Also, it has been fixed for Preview2.

I believe you are running into possibly a different issues - please file an issue in CoreFX repo with the repro steps.

**Comment by mzji** [comment]
@gkhanna79 Ok, thanks. Will try to issue another one in CoreFX's repo.
