### ISSUE TITLE
Exception when doing `dnu restore`

### ISSUE THREAD

**Issue by shaded-enmity** [dotnet/coreclr#1181]
I'm getting this exception when invoking `dnu restore`

```
Unhandled Exception: System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.TaskAwaiter`1' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  at EntryPoint.Main (System.String[] arguments) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.TaskAwaiter`1' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
  at EntryPoint.Main (System.String[] arguments) [0x00000] in <filename unknown>:0 
```

Output of `dnvm list`:

```
$ dnvm list                                                                                                                                                                             

Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta6-12120    mono         ~/.dnx/runtimes      default
       1.0.0-beta6-12120    coreclr x64  ~/.dnx/runtimes      

```

And output of `mono -V`:

```
$ mono -V
Mono JIT compiler version 2.10.8 (tarball Sun Aug 17 19:00:51 UTC 2014)
Copyright (C) 2002-2011 Novell, Inc, Xamarin, Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          debugger softdebug 
        LLVM:          supported, not enabled.
        GC:            Included Boehm (with typed GC and Parallel Mark)
```

This is on `Fedora 21 x64`. 
I've compiled CoreCLR from `master`, `HEAD` is at `3d8e9b6cb7a8d57ad836cd4748a7260e57477ed3`.

If Mono's version is `2.10.8` then I should probably get `4.x.x`? Or is it possible to switch the stack to use `2.x`?

**Comment by akoeplinger** [comment]
Mono 2.x isn't supported for dnx as it is way too old, you need 4.x.

**Comment by shaded-enmity** [comment]
Now I've installed Mono `4.0.1-44`, under the `dnvm` mono runtime the example works correctly and prints "Hello World", but if I switch to CoreCLR runtime I get this:

```
$ dnx . run
System.InvalidOperationException: Failed to resolve the following dependencies for target framework 'DNXCore,Version=v5.0':
   System.Console 4.0.0-beta

Searched Locations:
  /home/shaded-enmity/Repos/{name}/project.json

Try running 'dnu restore'.

   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

I've tried `dnu restore` under the CoreCLR runtime but it fails.

@akoeplinger

**Comment by akoeplinger** [comment]
@shaded-enmity `dnu restore` doesn't work on CoreCLR yet. You need to switch to Mono, run `dnu restore` there and then switch back to CoreCLR

**Comment by shaded-enmity** [comment]
Yes, that's what I did, the backtrace from `dnx . run` above is what I get after:

* Successfully running `dnu restore` under the Mono runtime
* Successfully running `dnvm use 1.0.0-beta6-12120 -r coreclr` to switch back to CoreCLR

@akoeplinger

**Comment by akoeplinger** [comment]
hmm, can you post your project.json?

**Comment by shaded-enmity** [comment]
Found the problem, I was stupid the first time around and executed `dnu restore` outside the directory with `project.json`:

```
$ dnu restore
Microsoft .NET Development Utility Mono-x64-1.0.0-beta6-12120
```

I think the command should report that nothing was done due to the absence of `project.json`, and possibly return a non-zero return code.

**Comment by shaded-enmity** [comment]
On a related note, what libraries/packages are supported, I get this error while executing the "Hello World" program with `Thread.Sleep` added.

The program works under the Mono runtime.

```
$ dnvm use 1.0.0-beta6-12120 -r mono
Adding /home/shaded-enmity/.dnx/runtimes/dnx-mono.1.0.0-beta6-12120/bin to process PATH

$ dnu restore
Microsoft .NET Development Utility Mono-x64-1.0.0-beta6-12120

Restoring packages for /home/shaded-enmity/Repos/coreclr-experiments/project.json
  CACHE https://www.nuget.org/api/v2/
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Runtime'
  CACHE https://www.nuget.org/api/v2/package/System.Runtime/4.0.20-beta-22231
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='System.Threading.Tasks'
  CACHE https://www.nuget.org/api/v2/package/System.Threading.Tasks/4.0.10-beta-22231
Writing lock file /home/shaded-enmity/Repos/coreclr-experiments/project.lock.json
Restore complete, 258ms elapsed

$ dnvm use 1.0.0-beta6-12120 -r coreclr
Adding /home/shaded-enmity/.dnx/runtimes/dnx-coreclr-linux-x64.1.0.0-beta6-12120/bin to process PATH

$ dnx . run
Microsoft.Framework.Runtime.Roslyn.RoslynCompilationException: /home/shaded-enmity/Repos/coreclr-experiments/hello.cs(9,3): error CS0234: The type or namespace name 'Thread' does not exist in the namespace 'System.Threading' (are you missing an assembly reference?)
   at Microsoft.Framework.Runtime.Roslyn.RoslynProjectReference.Load(IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName, IAssemblyLoadContext loadContext)
   at Microsoft.Framework.Runtime.Loader.ProjectAssemblyLoader.Load(AssemblyName assemblyName)
   at dnx.host.LoaderContainer.Load(AssemblyName assemblyName)
   at dnx.host.DefaultLoadContext.LoadAssembly(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.AssemblyLoaderCache.GetOrAdd(AssemblyName name, Func`2 factory)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyName(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.Loader.LoadContext.Microsoft.Framework.Runtime.IAssemblyLoadContext.Load(AssemblyName assemblyName)
   at Microsoft.Framework.Runtime.AssemblyLoadContextExtensions.Load(IAssemblyLoadContext loadContext, String name)
   at Microsoft.Framework.Runtime.DefaultHost.GetEntryPoint(String applicationName)
   at Microsoft.Framework.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Framework.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at dnx.host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env)
   at dnx.host.RuntimeBootstrapper.ExecuteAsync(String[] args)
   at dnx.host.RuntimeBootstrapper.Execute(String[] args)
```

**Comment by akoeplinger** [comment]
@shaded-enmity `Thread.Sleep` is in the `System.Threading.Thread` package in .NET Core (this is contrary to Mono/Full .NET where that API was in mscorlib, so you always had access to it).

You need to add that package as a dependency in your project.json. A good site for finding which API is in which package is http://packagesearch.azurewebsites.net/?q=sleep.

**Comment by shaded-enmity** [comment]
@akoeplinger Great, that did the trick, thanks!
