### ISSUE TITLE
[RyuJIT/arm32] Assertion failed 'varTypeIsSIMD(arg)'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#11840]
At lower.cpp Line: 971

Example:
```
Assert failure(PID 8388 [0x000020c4], Thread: 5164 [0x142c]): Assertion failed 'varTypeIsSIMD(arg)' in 'BooleanIConvertibleToDecimal:PosTest1():bool:this' (IL size 88)

    File: c:\gh\coreclr\src\jit\lower.cpp Line: 971
    Image: c:\brucefo\tests\Windows_NT.arm.Checked\Tests\Core_Root\CoreRun.exe
```

Tests with this assert:
```
CoreMangLib\cti\system\boolean\BooleanIConvertibleToDecimal\BooleanIConvertibleToDecimal.cmd
CoreMangLib\cti\system\boolean\BooleanIConvertibleToType\BooleanIConvertibleToType.cmd
CoreMangLib\cti\system\byte\ByteIConvertibleToDecimal\ByteIConvertibleToDecimal.cmd
CoreMangLib\cti\system\convert\ConvertToDecimal\ConvertToDecimal.cmd
CoreMangLib\cti\system\convert\ConvertToDecimal14\ConvertToDecimal14.cmd
CoreMangLib\cti\system\convert\ConvertToDecimal15\ConvertToDecimal15.cmd
CoreMangLib\cti\system\convert\ConvertToDecimal5\ConvertToDecimal5.cmd
CoreMangLib\cti\system\convert\ConvertToDecimal6\ConvertToDecimal6.cmd
CoreMangLib\cti\system\decimal\DecimalCtor1\DecimalCtor1.cmd
CoreMangLib\cti\system\decimal\DecimalCtor2\DecimalCtor2.cmd
CoreMangLib\cti\system\decimal\DecimalCtor3\DecimalCtor3.cmd
CoreMangLib\cti\system\decimal\DecimalCtor6\DecimalCtor6.cmd
CoreMangLib\cti\system\iconvertible\IConvertibleToDecimal\IConvertibleToDecimal.cmd
JIT\Methodical\divrem\div\r4div_cs_d\r4div_cs_d.cmd
JIT\Methodical\divrem\div\r4div_cs_do\r4div_cs_do.cmd
JIT\Methodical\divrem\div\r4div_cs_r\r4div_cs_r.cmd
JIT\Methodical\divrem\div\r4div_cs_ro\r4div_cs_ro.cmd
JIT\Methodical\divrem\div\r8div_cs_d\r8div_cs_d.cmd
JIT\Methodical\divrem\div\r8div_cs_do\r8div_cs_do.cmd
JIT\Methodical\divrem\div\r8div_cs_r\r8div_cs_r.cmd
JIT\Methodical\divrem\div\r8div_cs_ro\r8div_cs_ro.cmd
JIT\Methodical\divrem\rem\r4rem_cs_d\r4rem_cs_d.cmd
JIT\Methodical\divrem\rem\r4rem_cs_do\r4rem_cs_do.cmd
JIT\Methodical\divrem\rem\r4rem_cs_r\r4rem_cs_r.cmd
JIT\Methodical\divrem\rem\r4rem_cs_ro\r4rem_cs_ro.cmd
JIT\Methodical\divrem\rem\r8rem_cs_d\r8rem_cs_d.cmd
JIT\Methodical\divrem\rem\r8rem_cs_do\r8rem_cs_do.cmd
JIT\Methodical\divrem\rem\r8rem_cs_r\r8rem_cs_r.cmd
JIT\Methodical\divrem\rem\r8rem_cs_ro\r8rem_cs_ro.cmd
JIT\Methodical\MDArray\DataTypes\decimal_cs_d\decimal_cs_d.cmd
JIT\Methodical\MDArray\DataTypes\decimal_cs_do\decimal_cs_do.cmd
JIT\Methodical\MDArray\DataTypes\decimal_cs_r\decimal_cs_r.cmd
JIT\Methodical\MDArray\DataTypes\decimal_cs_ro\decimal_cs_ro.cmd
JIT\opt\virtualstubdispatch\manyintf\ctest_cs_d\ctest_cs_d.cmd
JIT\opt\virtualstubdispatch\manyintf\ctest_cs_r\ctest_cs_r.cmd
```

**Comment by jyoungyun** [comment]
I'm going to look this issue.

Below unittests are failed with the same assert in raspberry pi3.
```
GC/Features/HeapExpansion/bestfit_1
GC/Features/HeapExpansion/bestfit/bestfit
GC/Features/HeapExpansion/bestfit-finalize
GC/Features/HeapExpansion/bestfit-threaded
GC/LargeMemory/Allocation/largeexceptiontest
GC/LargeMemory/API/gc/gettotalmemory
GC/LargeMemory/API/gc/keepalive
GC/LargeMemory/API/gc/suppressfinalize
GC/Scenarios/Dynamo/dynamo
GC/Scenarios/FinalizeTimeout/FinalizeTimeout
GC/Scenarios/LeakWheel/leakwheel
GC/Scenarios/ServerModel/servermodel
Interop/MarshalAPI/MarshalStructure/MarshalStructure
JIT/Methodical/divrem/div/r4div_cs_do
JIT/Methodical/divrem/div/r4div_cs_d
JIT/Methodical/divrem/div/r4div_cs_ro
JIT/Methodical/divrem/div/r4div_cs_r
JIT/Methodical/divrem/div/r8div_cs_do
JIT/Methodical/divrem/div/r8div_cs_d
JIT/Methodical/divrem/div/r8div_cs_ro
JIT/Methodical/divrem/div/r8div_cs_r
JIT/Methodical/divrem/rem/r4rem_cs_do
JIT/Methodical/divrem/rem/r4rem_cs_d
JIT/Methodical/divrem/rem/r4rem_cs_ro
JIT/Methodical/divrem/rem/r4rem_cs_r
JIT/Methodical/divrem/rem/r8rem_cs_do
JIT/Methodical/divrem/rem/r8rem_cs_d
JIT/Methodical/divrem/rem/r8rem_cs_ro
JIT/Methodical/divrem/rem/r8rem_cs_r
JIT/Methodical/divrem/rem/r8rem_cs_ro
JIT/Methodical/divrem/rem/r8rem_cs_r
JIT/Methodical/MDArray/DataTypes/decimal_cs_d
JIT/Methodical/MDArray/DataTypes/decimal_cs_do
JIT/Methodical/MDArray/DataTypes/decimal_cs_r
JIT/Methodical/MDArray/DataTypes/decimal_cs_ro
JIT/opt/virtualstubdispatch/manyintf/ctest_cs_d
JIT/opt/virtualstubdispatch/manyintf/ctest_cs_r
JIT/Performance/CodeQuality/BenchmarksGame/regexdna/regexdna
JIT/Performance/CodeQuality/SciMark/SciMark
JIT/Performance/CodeQuality/Serialization/Serialize
JIT/Regression/CLR-x86-JIT/V1-M09/b13647/b13647
JIT/Regression/CLR-x86-JIT/V1-M09/b16294/b16294
JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b51817/b51817
JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b425314/b425314
JIT/Regression/VS-ia64-JIT/M00/b140298/b140298
readytorun/tests/generics
Regressions/common/AboveStackLimit
Regressions/common/CompEx
Regressions/common/date
Regressions/common/Marshal
Regressions/common/pow3
Regressions/common/ToLower
Regressions/common/Unsafe
```

**Comment by jyoungyun** [comment]
The related test code:
```
DateTimeOffset dto = new DateTimeOffset(1000, TimeSpan.Zero);
```
This code occurs the same error message with `Assertion failed 'varTypeIsSIMD(arg)'`.
Jit dump before morphing:
```
fgMorphTree BB02, stmt 4 (before)
               [000020] --CXG--------             *  CALL      void   System.DateTimeOffset..ctor
               [000006] L------------ this in r0  +--*  ADDR      byref
               [000005] -------------             |  \--*  LCL_VAR   struct(AX) V01 loc0
               [000008] ------------- arg1        +--*  CAST      long <- int
               [000007] -------------             |  \--*  CNS_INT   int    0x3E8
               [000012] ---XG-------- arg2        \--*  OBJ(8)    struct
               [000010] -------------                |     /--*  CNS_INT   int    4 Fseq[#FirstElem]
               [000011] ----G--------                |  /--*  ADD       byref
               [000009] ----G--------                |  |  \--*  FIELD     ref    Zero
               [000019] --CXG--------                \--*  COMMA     byref
               [000018] H-CXG--------                   \--*  CALL help int    HELPER.CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
               [000014] ------------- arg0                 +--*  CNS_INT   int    0x75904018
               [000015] ------------- arg1                 \--*  CNS_INT   int    123
```
Jit dump after morphing:
```
fgMorphTree BB02, stmt 4 (after)
               [000020] --CXG+-------             *  CALL      void   System.DateTimeOffset..ctor
               [000012] --CXG+-N-----             |  /--*  IND       struct
               [000010] -----+-------             |  |  |     /--*  CNS_INT   int    4 Fseq[#FirstElem]
               [000011] ----G+-------             |  |  |  /--*  ADD       byref
               [000009] ----G+-------             |  |  |  |  \--*  CLS_VAR   ref    Hnd=0x71012de0 Fseq[Zero]
               [000019] --CXG+-------             |  |  \--*  COMMA     byref
               [000018] H-CXG+-------             |  |     \--*  CALL help int    HELPER.CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
               [000014] -----+------- arg0 in r0  |  |        +--*  CNS_INT   int    0x75904018
               [000015] -----+------- arg1 in r1  |  |        \--*  CNS_INT   int    123
               [000041] -ACXG---R--L- arg2 SETUP  +--*  ASG       struct (copy)
               [000039] D------N-----             |  \--*  LCL_VAR   struct V02 tmp0
               [000042] ------------- arg2 in out+00+--*  LCL_VAR   struct V02 tmp0
     (  3,  3) [000006] L------------ this in r0  +--*  ADDR      byref
     (  3,  2) [000005] ----G--N-----             |  \--*  LCL_VAR   struct(AX) V01 loc0
     (  2,  4) [000008] ------------- arg1 r2,r3  \--*  CAST      long <- int
     (  1,  3) [000007] -------------                \--*  CNS_INT   int    0x3E8
```

The 000042 gentree node seems to be wrapped in GT_OBJ.

**Comment by jyoungyun** [comment]
After adding fgMorphStructArgs function and make a new node for addressing, the gentree is changed like below:
```
fgMorphTree BB02, stmt 4 (after)
               [000020] --CXG+-------             *  CALL      void   System.DateTimeOffset..ctor
               [000012] --CXG+-N-----             |  /--*  IND       struct
               [000010] -----+-------             |  |  |     /--*  CNS_INT   int    4 Fseq[#FirstElem]
               [000011] ----G+-------             |  |  |  /--*  ADD       byref
               [000009] ----G+-------             |  |  |  |  \--*  CLS_VAR   ref    Hnd=0x71082de0 Fseq[Zero]
               [000019] --CXG+-------             |  |  \--*  COMMA     byref
               [000018] H-CXG+-------             |  |     \--*  CALL help int    HELPER.CORINFO_HELP_GETSHARED_NONGCSTATIC_BASE
               [000014] -----+------- arg0 in r0  |  |        +--*  CNS_INT   int    0x75979018
               [000015] -----+------- arg1 in r1  |  |        \--*  CNS_INT   int    270
               [000041] -ACXG---R--L- arg2 SETUP  +--*  ASG       struct (copy)
               [000039] D------N-----             |  \--*  LCL_VAR   struct V02 tmp0
               [000049] ------------- arg2 in out+00+--*  OBJ(8)    struct
               [000048] L------------             |  \--*  ADDR      int
               [000042] -------------             |     \--*  LCL_VAR   struct V02 tmp0
     (  3,  3) [000006] L------------ this in r0  +--*  ADDR      byref
     (  3,  2) [000005] ----G--N-----             |  \--*  LCL_VAR   struct(AX) V01 loc0
     (  2,  4) [000008] ------------- arg1 r2,r3  \--*  CAST      long <- int
     (  1,  3) [000007] -------------                \--*  CNS_INT   int    0x3E8
```

And the assersion is fixed. I will post PR soon.

**Comment by jyoungyun** [comment]
After merging the above patch, 46 of the 52 tests passed.

Failed TC
```
FAILED   - JIT/Methodical/divrem/div/r4div_cs_do/r4div_cs_do.sh
FAILED   - JIT/Methodical/divrem/div/r4div_cs_ro/r4div_cs_ro.sh
               Assert failure(PID 3695 [0x00000e6f], Thread: 3695 [0x0e6f]): Assertion failed 'currentInterval->assignedReg != nullptr && currentInterval->assignedReg->regNum == assignedRegister && currentInterval->assignedReg->assignedInterval == currentInterval' in 'r4div:Main():int' (IL size 26300)
               
                   File: /opt/code/src/jit/lsra.cpp Line: 7594
                   Image: /home/pi3/Downloads/ryujit/overlay-0710-fixed/corerun
FAILED   - JIT/Methodical/MDArray/DataTypes/decimal_cs_d/decimal_cs_d.sh
FAILED   - JIT/Methodical/MDArray/DataTypes/decimal_cs_do/decimal_cs_do.sh
FAILED   - JIT/Methodical/MDArray/DataTypes/decimal_cs_r/decimal_cs_r.sh
FAILED   - JIT/Methodical/MDArray/DataTypes/decimal_cs_ro/decimal_cs_ro.sh
               BEGIN EXECUTION
               /home/pi3/Downloads/ryujit/overlay-0710-fixed/corerun decimal_cs_d.exe
               
               Unhandled Exception: System.OverflowException: Value was either too large or too small for an Int32.
                  at System.Decimal.ToInt32(Decimal d)
                  at System.Convert.ToInt32(Decimal value)
                  at decimalMDArrTest.Main()
```

**Comment by jyoungyun** [comment]
The second error was already fixed by @hseok-oh patch (https://github.com/dotnet/coreclr/pull/12710).

**Comment by BruceForstall** [comment]
I'm going to close this issue. Different asserts will have different issues opened.
