### ISSUE TITLE
CI Jobs Failing Due to Linker

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#11856]
This is failing both perf jobs.
From https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_perflab_Windows_NT_x64_smoketest_prtest/824/consoleText:

Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: <unspecified> ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'csc, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Mono.Linker.LinkContext.Resolve(IMetadataScope scope) in /home/sven/src/dotnet/linker/linker/Mono.Linker/LinkContext.cs:line 197
   at Mono.Linker.Steps.ResolveFromXmlStep.GetAssembly(LinkContext context, String assemblyName) in /home/sven/src/dotnet/linker/linker/Mono.Linker.Steps/ResolveFromXmlStep.cs:line 399
   at Mono.Linker.Steps.ResolveFromXmlStep.ProcessAssemblies(LinkContext context, XPathNodeIterator iterator) in /home/sven/src/dotnet/linker/linker/Mono.Linker.Steps/ResolveFromXmlStep.cs:line 85
   at Mono.Linker.Steps.ResolveFromXmlStep.Process() in /home/sven/src/dotnet/linker/linker/Mono.Linker.Steps/ResolveFromXmlStep.cs:line 76
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.ResolveFromXmlStep.Process() in /home/sven/src/dotnet/linker/linker/Mono.Linker.Steps/ResolveFromXmlStep.cs:line 78
   at Mono.Linker.Steps.BaseStep.Process(LinkContext context) in /home/sven/src/dotnet/linker/linker/Mono.Linker.Steps/BaseStep.cs:line 52
   at Mono.Linker.Pipeline.Process(LinkContext context) in /home/sven/src/dotnet/linker/linker/Mono.Linker/Pipeline.cs:line 129
   at Mono.Linker.Driver.Run() in /home/sven/src/dotnet/linker/linker/Mono.Linker/Driver.cs:line 194
   at Mono.Linker.Driver.Main(String[] args) in /home/sven/src/dotnet/linker/linker/Mono.Linker/Driver.cs:line 56

**Comment by brianrob** [comment]
@russellhadley, @swaroop-sridhar, @sbomer, PTAL.

@DrewScoggins, @valenis, FYI.

**Comment by russellhadley** [comment]
Looks like it's coming out of the Roslyn build.  @swaroop-sridhar can you take a look?

**Comment by swaroop-sridhar** [comment]
Yes, I'm trying to fix it -- can disable the Roslyn test in the interim to get the builds to pass.

**Comment by swaroop-sridhar** [comment]
https://github.com/dotnet/coreclr/pull/11858

**Comment by brianrob** [comment]
@swaroop-sridhar, thanks much.

**Comment by RussKeldorph** [comment]
@swaroop-sridhar @russellhadley Please correct triage if necessary.

**Comment by swaroop-sridhar** [comment]
This issue is now fixed in master and release/2.0.0
