### ISSUE TITLE
[Arm64/Unix] 'SHA1' threw an exception. ---> System.ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#11862]
On recent tip, `JIT/Performance/CodeQuality/Roslyn/CscBench/CscBench.sh` is failing 

```
'SHA1' threw an exception. ---> System.ArgumentNullException: Value cannot be null
```

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib

**Comment by sdmaclea** [comment]
Full Backtrace
```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'SHA1' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at Roslyn.Utilities.PortableShim.SHA1..cctor()
   --- End of inner exception stack trace ---
   at Roslyn.Utilities.SHA1CryptoServiceProvider..ctor()
   at Microsoft.CodeAnalysis.CryptographicHashProvider.ComputeSha1(Byte[] bytes)
   at Microsoft.CodeAnalysis.AssemblyIdentity.CalculatePublicKeyToken(ImmutableArray`1 publicKey)
   at Microsoft.CodeAnalysis.AssemblyIdentity.get_PublicKeyToken()
   at Microsoft.CodeAnalysis.CSharp.Emit.AssemblyReference.Microsoft.Cci.IAssemblyReference.get_PublicKeyToken()
   at Microsoft.Cci.MetadataWriter.AssemblyReferenceComparer.GetHashCode(IAssemblyReference reference)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Cci.MetadataWriter.HeapOrReferenceIndex`1.AddItem(T item, Int32 index)
   at Microsoft.Cci.MetadataWriter.HeapOrReferenceIndexBase`1.Add(T item)
   at Microsoft.Cci.MetadataWriter.HeapOrReferenceIndexBase`1.GetOrAdd(T item)
   at Microsoft.Cci.FullMetadataWriter.GetOrAddAssemblyRefIndex(IAssemblyReference reference)
   at Microsoft.Cci.MetadataWriter.CreateInitialAssemblyRefIndex()
   at Microsoft.Cci.MetadataWriter.CreateIndices()
   at Microsoft.Cci.MetadataWriter.SerializeMetadataAndIL(BlobBuilder metadataWriter, BlobBuilder debugMetadataWriterOpt, PdbWriter nativePdbWriterOpt, BlobBuilder ilWriter, BlobBuilder mappedFieldDataWriter, BlobBuilder managedResourceDataWriter, Int32 methodBodyStreamRva, Func`2 calculateMappedFieldDataStreamRva, Int32& moduleVersionIdOffsetInMetadataStream, Int32& pdbIdOffsetInPortablePdbStream, Int32& entryPointToken, MetadataSizes& metadataSizes)
   at Microsoft.Cci.PeWriter.WritePeToStream(MetadataWriter mdWriter, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt)
   at Microsoft.Cci.PeWriter.WritePeToStream(EmitContext context, CommonMessageProvider messageProvider, Func`1 getPeStream, Func`1 getPortablePdbStreamOpt, PdbWriter nativePdbWriterOpt, String pdbPathOpt, Boolean allowMissingMethodBodies, Boolean deterministic, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.SerializeToPeStream(CommonPEModuleBuilder moduleBeingBuilt, EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, Func`1 testSymWriterFactory, DiagnosticBag diagnostics, Boolean metadataOnly, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(EmitStreamProvider peStreamProvider, EmitStreamProvider pdbStreamProvider, EmitStreamProvider xmlDocumentationStreamProvider, EmitStreamProvider win32ResourcesStreamProvider, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CompilationTestData testData, Func`1 getHostDiagnostics, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Compilation.Emit(Stream peStream, Stream pdbStream, Stream xmlDocumentationStream, Stream win32Resources, IEnumerable`1 manifestResources, EmitOptions options, IMethodSymbol debugEntryPoint, CancellationToken cancellationToken)
   at CscBench.CompileBench()
   at CscBench.Bench()
   at CscBench.Main()
```

**Comment by sdmaclea** [comment]
This is no longer an issue with latest tip.

**Comment by sdmaclea** [comment]
@jashook FYI
