### ISSUE TITLE
[x86/Linux] m_pLayouts[IMAGE_LOADED] == NULL assert failure

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#11866]
I observed the following assert failure while running FX unittest:
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Dynamic.Runtime.Tests
Discovered:  System.Dynamic.Runtime.Tests
Starting:    System.Dynamic.Runtime.Tests

Assert failure(PID 18638 [0x000048ce], Thread: 18653 [0x48dd]): m_pLayouts[IMAGE_LOADED] == NULL
    File: /var/jenkins/workspace/CLR/x86_Chk_RT/repo/code/src/vm/peimage.cpp Line: 1107
    Image: /var/jenkins/workspace/FX/FX_x86_Checked_Test/working/overlay/dotnet
```

**Comment by parjong** [comment]
@jkotas @janvorli #11867 seems to address this issue, but I'm not sure whether it is a correct way to resolve this issue. Could you let me know whether it is possible to invoke PEImage::Load multiple times?

**Comment by jkotas** [comment]
Regression introduced by https://github.com/dotnet/coreclr/pull/10772

**Comment by parjong** [comment]
Here is the backtrace when hitting this assert failure:
```
Assert failure(PID 297 [0x00000129], Thread: 305 [0x0131]): m_pLayouts[IMAGE_LOADED] == NULL
    File: /home2/parjong/projects/dotnet/coreclr/src/vm/peimage.cpp Line: 1107
    Image: /home2/parjong/projects/dotnet/toolchain-local/fx/session/20170523_235941/overlay/corerun


Program received signal SIGABRT, Aborted.
[Switching to Thread 0xef82eb40 (LWP 305)]
0xf7fd9d80 in __kernel_vsyscall ()
(gdb) bt
#0  0xf7fd9d80 in __kernel_vsyscall ()
#1  0xf7ce2687 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#2  0xf7ce5ab3 in __GI_abort () at abort.c:89
#3  0xf78ad946 in PROCAbort () at /home2/parjong/projects/dotnet/coreclr/src/pal/src/thread/process.cpp:3023
#4  0xf78a8481 in PROCEndProcess (hProcess=0xffffff01, uExitCode=123456789, bTerminateUnconditionally=1) at /home2/parjong/projects/dotnet/coreclr/src/pal/src/thread/process.cpp:1391
#5  0xf78a85f1 in TerminateProcess (hProcess=0xffffff01, uExitCode=123456789) at /home2/parjong/projects/dotnet/coreclr/src/pal/src/thread/process.cpp:1307
#6  0xf6c64ca2 in TerminateOnAssert () at /home2/parjong/projects/dotnet/coreclr/src/utilcode/debug.cpp:183
#7  0xf6c65f3e in _DbgBreakCheck (szFile=0xf795a3f6 "/home2/parjong/projects/dotnet/coreclr/src/vm/peimage.cpp", iLine=1107, szExpr=0xf795a6dc "m_pLayouts[IMAGE_LOADED] == NULL", fConstrained=0)
    at /home2/parjong/projects/dotnet/coreclr/src/utilcode/debug.cpp:436
#8  0xf6c666c5 in _DbgBreakCheckNoThrow (szFile=0xf795a3f6 "/home2/parjong/projects/dotnet/coreclr/src/vm/peimage.cpp", iLine=1107, szExpr=0xf795a6dc "m_pLayouts[IMAGE_LOADED] == NULL", fConstrained=0)
    at /home2/parjong/projects/dotnet/coreclr/src/utilcode/debug.cpp:548
#9  0xf6c66d47 in DbgAssertDialog (szFile=0xf795a3f6 "/home2/parjong/projects/dotnet/coreclr/src/vm/peimage.cpp", iLine=1107, szExpr=0xf795a6dc "m_pLayouts[IMAGE_LOADED] == NULL")
    at /home2/parjong/projects/dotnet/coreclr/src/utilcode/debug.cpp:735
#10 0xf6dd9d5b in PEImage::Load (this=0xeba0a8d0) at /home2/parjong/projects/dotnet/coreclr/src/vm/peimage.cpp:1107
#11 0xf6dc319b in PEFile::LoadLibrary (this=0xeba0b278, allowNativeSkip=1) at /home2/parjong/projects/dotnet/coreclr/src/vm/pefile.cpp:326
#12 0xf724a989 in DomainFile::LoadLibrary (this=0xeba0aa78) at /home2/parjong/projects/dotnet/coreclr/src/vm/domainfile.cpp:990
#13 0xf7249886 in DomainFile::DoIncrementalLoad (this=0xeba0aa78, level=FILE_LOAD_LOADLIBRARY) at /home2/parjong/projects/dotnet/coreclr/src/vm/domainfile.cpp:578
#14 0xf71477d8 in AppDomain::TryIncrementalLoad (this=0x8088d88, pFile=0xeba0aa78, workLevel=FILE_LOAD_LOADLIBRARY, lockHolder=...) at /home2/parjong/projects/dotnet/coreclr/src/vm/appdomain.cpp:5921
#15 0xf714657f in AppDomain::LoadDomainFile (this=0x8088d88, pLock=0xeba0ada0, targetLevel=FILE_LOADED) at /home2/parjong/projects/dotnet/coreclr/src/vm/appdomain.cpp:5853
#16 0xf7146cfd in AppDomain::LoadDomainAssemblyInternal (this=0x8088d88, pIdentity=0xef8283c8, pFile=0xeba0b278, targetLevel=FILE_LOADED) at /home2/parjong/projects/dotnet/coreclr/src/vm/appdomain.cpp:5683
#17 0xf7137885 in AppDomain::LoadDomainAssembly (this=0x8088d88, pSpec=0xef8283c8, pFile=0xeba0b278, targetLevel=FILE_LOADED) at /home2/parjong/projects/dotnet/coreclr/src/vm/appdomain.cpp:5570
#18 0xf71ab4a4 in Module::LoadAssembly (this=0xefa2f860, pDomain=0x8088d88, kAssemblyRef=587202627, szWinRtTypeNamespace=0x0, szWinRtTypeClassName=0x0)
    at /home2/parjong/projects/dotnet/coreclr/src/vm/ceeload.cpp:5688
#19 0xf717fa3b in Assembly::FindModuleByExportedType (this=0x815afc0, mdType=654313302, loadFlag=Loader::Load, mdNested=33554432, pCL=0xef828870) at /home2/parjong/projects/dotnet/coreclr/src/vm/assembly.cpp:1014
#20 0xf71d8e2c in EEClassHashTable::UncompressModuleAndClassDef (this=0xef98c368, Data=0x80000ead, loadFlag=Loader::Load, ppModule=0xef828874, pCL=0xef828870, pmdFoundExportedType=0xef82885c)
    at /home2/parjong/projects/dotnet/coreclr/src/vm/classhash.cpp:173
#21 0xf71e469c in ClassLoader::FindClassModuleThrowing (this=0x815c9e8, pOriginalName=0xef828be8, pType=0xef828be0, pmdClassToken=0xef828870, ppModule=0xef828874, pmdFoundExportedType=0xef82885c,
    pFoundEntry=0xef828860, pLookInThisModuleOnly=0xefa2f860, loadFlag=Loader::Load) at /home2/parjong/projects/dotnet/coreclr/src/vm/clsload.cpp:1919
#22 0xf71de2b4 in ClassLoader::LoadTypeHandleThrowing (this=0x815c9e8, pName=0xef828be8, level=CLASS_LOADED, pLookInThisModuleOnly=0xefa2f860) at /home2/parjong/projects/dotnet/coreclr/src/vm/clsload.cpp:2029
#23 0xf71dded4 in ClassLoader::LoadTypeHandleThrowIfFailed (this=0x815c9e8, pName=0xef828be8, level=CLASS_LOADED, pLookInThisModuleOnly=0xefa2f860) at /home2/parjong/projects/dotnet/coreclr/src/vm/clsload.cpp:559
#24 0xf71e7f7f in ClassLoader::LoadTypeDefOrRefThrowing (pModule=0xefa2aea0, typeDefOrRef=16777255, fNotFoundAction=ClassLoader::ThrowIfNotFound, fUninstantiated=ClassLoader::FailIfUninstDefOrRef,
    tokenNotToLoad=0, level=CLASS_LOADED) at /home2/parjong/projects/dotnet/coreclr/src/vm/clsload.cpp:3049
#25 0xf6dfd967 in SigPointer::GetTypeHandleThrowing (this=0xef829170, pModule=0xefa2aea0, pTypeContext=0xef829158, fLoadTypes=ClassLoader::LoadTypes, level=CLASS_LOADED, dropGenericArgumentLevel=0, pSubst=0x0,
    pZapSigContext=0x0) at /home2/parjong/projects/dotnet/coreclr/src/vm/siginfo.cpp:1496
...
```
Unfortunately, this issue is non-deterministic and thus it is not easy to reproduce or validate.

**Comment by ruben-ayrapetyan** [comment]
See also: https://github.com/dotnet/coreclr/pull/11867/files/891c3d5e4269c42f67f6094ed0c815e3098d3529#diff-57b4d690ef230ae53997986a1a746962 (analysis of failure cause).
