### ISSUE TITLE
[RyuJIT/armel] CodeGenBringUpTests Assertion failed '(allRegs(theInterval->registerType) & mask) != 0'

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#11928]
A sub-issue for #11822 

Some tests fail with below assert failure.

```
               Assert failure(PID 13122 [0x00003342], Thread: 13122 [0x3342]): Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'System.Collections.Hashtable:.ctor():this' (IL size 15)

                   File: /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp Line: 892
```

List of the tests fail with above message in `JIT/CodeGenBringUpTests`

```
FAILED   - [  23]JIT/CodeGenBringUpTests/DblAdd/DblAdd.sh
FAILED   - [  24]JIT/CodeGenBringUpTests/DblAddConst/DblAddConst.sh
FAILED   - [  26]JIT/CodeGenBringUpTests/DblArray/DblArray.sh
FAILED   - [  27]JIT/CodeGenBringUpTests/DblAvg2/DblAvg2.sh
FAILED   - [  29]JIT/CodeGenBringUpTests/DblCall1/DblCall1.sh
FAILED   - [  32]JIT/CodeGenBringUpTests/DblDiv/DblDiv.sh
FAILED   - [  33]JIT/CodeGenBringUpTests/DblDivConst/DblDivConst.sh
FAILED   - [  35]JIT/CodeGenBringUpTests/DblMul/DblMul.sh
FAILED   - [  36]JIT/CodeGenBringUpTests/DblMulConst/DblMulConst.sh
FAILED   - [  37]JIT/CodeGenBringUpTests/DblNeg/DblNeg.sh
FAILED   - [  38]JIT/CodeGenBringUpTests/DblRem/DblRem.sh
FAILED   - [  40]JIT/CodeGenBringUpTests/DblSub/DblSub.sh
FAILED   - [  41]JIT/CodeGenBringUpTests/DblSubConst/DblSubConst.sh
FAILED   - [  42]JIT/CodeGenBringUpTests/DblVar/DblVar.sh
FAILED   - [  43]JIT/CodeGenBringUpTests/DivConst/DivConst.sh
FAILED   - [  45]JIT/CodeGenBringUpTests/FPAdd/FPAdd.sh
FAILED   - [  46]JIT/CodeGenBringUpTests/FPAddConst/FPAddConst.sh
FAILED   - [  47]JIT/CodeGenBringUpTests/FPArea/FPArea.sh
FAILED   - [  48]JIT/CodeGenBringUpTests/FPArray/FPArray.sh
FAILED   - [  49]JIT/CodeGenBringUpTests/FPAvg2/FPAvg2.sh
FAILED   - [  50]JIT/CodeGenBringUpTests/FPAvg6/FPAvg6.sh
FAILED   - [  51]JIT/CodeGenBringUpTests/FPCall1/FPCall1.sh
FAILED   - [  52]JIT/CodeGenBringUpTests/FPCall2/FPCall2.sh
FAILED   - [  53]JIT/CodeGenBringUpTests/FPConvDbl2Lng/FPConvDbl2Lng.sh
FAILED   - [  54]JIT/CodeGenBringUpTests/FPConvF2F/FPConvF2F.sh
FAILED   - [  55]JIT/CodeGenBringUpTests/FPConvF2I/FPConvF2I.sh
FAILED   - [  56]JIT/CodeGenBringUpTests/FPConvF2Lng/FPConvF2Lng.sh
FAILED   - [  57]JIT/CodeGenBringUpTests/FPConvI2F/FPConvI2F.sh
FAILED   - [  58]JIT/CodeGenBringUpTests/FPDist/FPDist.sh
FAILED   - [  59]JIT/CodeGenBringUpTests/FPDiv/FPDiv.sh
FAILED   - [  60]JIT/CodeGenBringUpTests/FPDivConst/FPDivConst.sh
FAILED   - [  61]JIT/CodeGenBringUpTests/FPError/FPError.sh
FAILED   - [  62]JIT/CodeGenBringUpTests/FPFillArray/FPFillArray.sh
FAILED   - [  63]JIT/CodeGenBringUpTests/FPMath/FPMath.sh
FAILED   - [  64]JIT/CodeGenBringUpTests/FPMul/FPMul.sh
FAILED   - [  65]JIT/CodeGenBringUpTests/FPMulConst/FPMulConst.sh
FAILED   - [  66]JIT/CodeGenBringUpTests/FPNeg/FPNeg.sh
FAILED   - [  67]JIT/CodeGenBringUpTests/FPRem/FPRem.sh
FAILED   - [  68]JIT/CodeGenBringUpTests/FPRoots/FPRoots.sh
FAILED   - [  69]JIT/CodeGenBringUpTests/FPSmall/FPSmall.sh
FAILED   - [  70]JIT/CodeGenBringUpTests/FPSub/FPSub.sh
FAILED   - [  71]JIT/CodeGenBringUpTests/FPSubConst/FPSubConst.sh
FAILED   - [  72]JIT/CodeGenBringUpTests/FPVar/FPVar.sh
FAILED   - [  85]JIT/CodeGenBringUpTests/JTrueEqDbl/JTrueEqDbl.sh
FAILED   - [  86]JIT/CodeGenBringUpTests/JTrueEqFP/JTrueEqFP.sh
FAILED   - [  88]JIT/CodeGenBringUpTests/JTrueGeDbl/JTrueGeDbl.sh
FAILED   - [  89]JIT/CodeGenBringUpTests/JTrueGeFP/JTrueGeFP.sh
FAILED   - [  91]JIT/CodeGenBringUpTests/JTrueGtDbl/JTrueGtDbl.sh
FAILED   - [  92]JIT/CodeGenBringUpTests/JTrueGtFP/JTrueGtFP.sh
FAILED   - [  94]JIT/CodeGenBringUpTests/JTrueLeDbl/JTrueLeDbl.sh
FAILED   - [  95]JIT/CodeGenBringUpTests/JTrueLeFP/JTrueLeFP.sh
FAILED   - [  97]JIT/CodeGenBringUpTests/JTrueLtDbl/JTrueLtDbl.sh
FAILED   - [  98]JIT/CodeGenBringUpTests/JTrueLtFP/JTrueLtFP.sh
FAILED   - [ 100]JIT/CodeGenBringUpTests/JTrueNeDbl/JTrueNeDbl.sh
FAILED   - [ 101]JIT/CodeGenBringUpTests/JTrueNeFP/JTrueNeFP.sh
FAILED   - [ 121]JIT/CodeGenBringUpTests/ModConst/ModConst.sh
FAILED   - [ 143]JIT/CodeGenBringUpTests/UDivConst/UDivConst.sh
FAILED   - [ 144]JIT/CodeGenBringUpTests/UModConst/UModConst.sh
FAILED   - [ 150]JIT/CodeGenBringUpTests/div2/div2.sh
```

**Comment by wateret** [comment]
Backtrace (JIT/CodeGenBringUpTests/DblAdd/DblAdd.exe)

```
#0  0xb6ca8094 in raise () from /lib/libc.so.6
#1  0xb6ca93f0 in abort () from /lib/libc.so.6
#2  0xb699f2fe in PROCAbort () at /opt/code/github/hqueue/coreclr/src/pal/src/thread/process.cpp:3023
#3  0xb699c0c0 in PROCEndProcess (hProcess=0xffffff01, uExitCode=123456789, bTerminateUnconditionally=1)
    at /opt/code/github/hqueue/coreclr/src/pal/src/thread/process.cpp:1391
#4  0xb699c1fe in TerminateProcess (hProcess=0xffffff01, uExitCode=123456789)
    at /opt/code/github/hqueue/coreclr/src/pal/src/thread/process.cpp:1307
#5  0xb62fe2a2 in TerminateOnAssert () at /opt/code/github/hqueue/coreclr/src/utilcode/debug.cpp:183
#6  0xb62feada in _DbgBreakCheck (szFile=0xb0f2ed9f "/opt/code/github/hqueue/coreclr/src/jit/lsra.cpp", iLine=892,
    szExpr=0xbeffa138 "Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'BringUpTest:Main():int' (IL size 62)\n",
    fConstrained=0) at /opt/code/github/hqueue/coreclr/src/utilcode/debug.cpp:436
#7  0xb6370f7c in CEEInfo::doAssert (this=0xbeffd840, szFile=0xb0f2ed9f "/opt/code/github/hqueue/coreclr/src/jit/lsra.cpp", iLine=892,
    szExpr=0xbeffa138 "Assertion failed '(allRegs(theInterval->registerType) & mask) != 0' in 'BringUpTest:Main():int' (IL size 62)\n")
    at /opt/code/github/hqueue/coreclr/src/vm/jitinterface.cpp:10400
#8  0xb0c80814 in assertAbort (why=0xb0f2f074 "(allRegs(theInterval->registerType) & mask) != 0",
    file=0xb0f2ed9f "/opt/code/github/hqueue/coreclr/src/jit/lsra.cpp", line=892) at /opt/code/github/hqueue/coreclr/src/jit/error.cpp:287
#9  0xb0d3fcb4 in LinearScan::newRefPosition (this=0x888f0, theInterval=0x899c4, theLocation=8, theRefType=RefType::RefTypeDef,
    theTreeNode=0x89330, mask=1, multiRegIdx=0, minRegCandidateCount=2) at /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp:892
#10 0xb0d491ce in LinearScan::buildRefPositionsForNode (this=0x888f0, tree=0x89330, block=0x8362c, listNodePool=...,
    operandToLocationInfoMap=..., currentLoc=7) at /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp:4114
#11 0xb0d41e36 in LinearScan::buildIntervals (this=0x888f0) at /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp:4680
#12 0xb0d4140c in LinearScan::doLinearScan (this=0x888f0) at /opt/code/github/hqueue/coreclr/src/jit/lsra.cpp:1765
#13 0xb0c5f6bc in Compiler::compCompile (this=0x80198, methodCodePtr=0xbeffd274, methodCodeSize=0xbeffd718, compileFlags=0xbeffd288)
    at /opt/code/github/hqueue/coreclr/src/jit/compiler.cpp:4825
#14 0xb0c619f0 in Compiler::compCompileHelper (this=0x80198, classPtr=0xb598bb3c, compHnd=0xbeffd840, methodInfo=0xbeffd79c,
    methodCodePtr=0xbeffd274, methodCodeSize=0xbeffd718, compileFlags=0xbeffd288, instVerInfo=INSTVER_GENERIC_PASSED_VERIFICATION)
    at /opt/code/github/hqueue/coreclr/src/jit/compiler.cpp:5968
#15 0xb0c609c8 in Compiler::compCompile(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, void**, unsigned
int*, JitFlags*)::$_0::operator()(Compiler::compCompile(CORINFO_METHOD_STRUCT_*, CORINFO_MODULE_STRUCT_*, ICorJitInfo*, CORINFO_METHOD_INFO*, v
oid**, unsigned int*, JitFlags*)::__JITParam*) const (this=0xbeffcf6c, __JITpParam=0xbeffcf70)
    at /opt/code/github/hqueue/coreclr/src/jit/compiler.cpp:5320
#16 0xb0c60634 in Compiler::compCompile (this=0x80198, methodHnd=0xb598ca80, classPtr=0xb598bb3c, compHnd=0xbeffd840, methodInfo=0xbeffd79c,
    methodCodePtr=0xbeffd274, methodCodeSize=0xbeffd718, compileFlags=0xbeffd288) at /opt/code/github/hqueue/coreclr/src/jit/compiler.cpp:5340
```
