### ISSUE TITLE
[RyuJIT/arm32] emitter::emitInsLoadStoreOp segmentation fault

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#11958]
When running with with `COMPlus_AltJit=* COMPlus_AltJitAssertOnNYI=0` options,
`JIT/Regression/JitBlue/DevDiv_283795/DevDiv_283795` faces segementation fault.

```
Thread 1 "corerun" received signal SIGSEGV, Segmentation fault.
emitter::emitInsLoadStoreOp (this=<optimized out>, ins=<optimized out>, attr=<optimized out>, dataReg=_regNumber_enum::REG_R0,
    indir=0x9292c) at /opt/code/github/hqueue/coreclr/src/jit/emitarm.cpp:7584
warning: Source file is more recent than executable.
7584                            emitIns_R_R_R_I(INS_add, EA_PTRSIZE, tmpReg, memBase->gtRegNum, index->gtRegNum, lsl,
(gdb) bt
#0  emitter::emitInsLoadStoreOp (this=<optimized out>, ins=<optimized out>, attr=<optimized out>, dataReg=_regNumber_enum::REG_R0,
    indir=0x9292c) at /opt/code/github/hqueue/coreclr/src/jit/emitarm.cpp:7584
#1  0x71161e18 in CodeGen::genCodeForIndir (this=0x90834, tree=0x9292c)
    at /opt/code/github/hqueue/coreclr/src/jit/codegenarmarch.cpp:1342
#2  0x7100c334 in CodeGen::genCodeForBBlist (this=<optimized out>) at /opt/code/github/hqueue/coreclr/src/jit/codegenlinear.cpp:385
#3  0x710003ca in CodeGen::genGenerateCode (this=0x90834, codePtr=0x7effd70c, nativeSizeOfCode=0x7effd860)
    at /opt/code/github/hqueue/coreclr/src/jit/codegencommon.cpp:3118
#4  0x71014e78 in Compiler::compCompile (this=<optimized out>, methodCodePtr=<optimized out>, methodCodeSize=<optimized out>,
    compileFlags=<optimized out>) at /opt/code/github/hqueue/coreclr/src/jit/compiler.cpp:4846
```

Previously it was considered to be #11779.

**Comment by hqueue** [comment]
Fixed by #11205
