### ISSUE TITLE
CLR unittest build is broken

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#12129]
I got the following error message:
```
10:57:10 Running: D:\workspace\CLR\x86_Rel_TC\code\Tools\dotnetcli\dotnet.exe D:\workspace\CLR\x86_Rel_TC\code\Tools\run.exe D:\workspace\CLR\x86_Rel_TC\code\config.json build -Project=D:\workspace\CLR\x86_Rel_TC\code\build.proj -generateHeaderWindows -NativeVersionHeaderFile="D:\workspace\CLR\x86_Rel_TC\code\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Release -BuildArch=x86
10:57:12 
10:57:12 Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 지정된 파일을 찾을 수 없습니다.
10:57:13    at Newtonsoft.Json.JsonConvert.DeserializeObject
10:57:13    at Newtonsoft.Json.JsonConvert.DeserializeObject[T]
10:57:13    at Microsoft.DotNet.Execute.Executor.OpenFile()
10:57:13    at Microsoft.DotNet.Execute.Executor.Main(String[] args)
```

Is there any issue on build tools?

**Comment by parjong** [comment]
It is interesting that this does not happen when I run build.cmd inside powershell.
