### ISSUE TITLE
build.cmd failed on 82af80d

### ISSUE THREAD

**Issue by sillyousu** [dotnet/coreclr#12271]
Do I miss something?

82af80d61310e55cce4cf96b0cb199bcfe50e497

```
PS E:\project\coreclr> .\build.cmd
Starting Build at 22:27:34.30
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat"
Installing dotnet cli...
Restoring BuildTools version 2.0.0-prerelease-01702-02...
Initializing BuildTools...
Done initializing tools.
Running: E:\project\coreclr\Tools\dotnetcli\dotnet.exe E:\project\coreclr\Tools\run.exe E:\project\coreclr\config.json b
uild -Project=E:\project\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="E:\project\coreclr\bin\obj\
_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。
   at Newtonsoft.Json.JsonConvert.DeserializeObject
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T]
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
BUILD: Restoring the OptimizationData Package
Tools are already initialized.
Running: E:\project\coreclr\Tools\dotnetcli\dotnet.exe E:\project\coreclr\Tools\run.exe E:\project\coreclr\config.json sync -optdata

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Serialization.Prim
itives, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. 系统找不到指定的文件。
   at Newtonsoft.Json.JsonConvert.DeserializeObject
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T]
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
BUILD: Error: Failed to restore the optimization data package.
```

**Comment by sillyousu** [comment]
dup of https://github.com/dotnet/coreclr/issues/12176 and https://github.com/dotnet/coreclr/issues/12268
