### ISSUE TITLE
"Length cannot be less than zero. " thrown on nectoreapp2.0 when trying to invoke Action<dynamic> that accesses a property on the input class - works for anonymous types

### ISSUE THREAD

**Issue by maumar** [dotnet/coreclr#12529]
repro:

```cs
        public class MyEntity
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }

        [Fact]
        public virtual void Netcoreapp_bug()
        {
            Action<dynamic> workingElementAsserter = e => Console.WriteLine("works");
            Action<dynamic> failingElementAsserter = e => Console.WriteLine(e.Id);
            var dto = new MyEntity { Id = 1, Name = "Foo" };
            var anonymous = new { Id = 1, Name = "Foo" };

            workingElementAsserter(dto); //works
            failingElementAsserter(anonymous); //works

            failingElementAsserter.Invoke(dto); //fails
        }
```

exception:

```
 System.ArgumentOutOfRangeException : Length cannot be less than zero.
Parameter name: length
Stack Trace:
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameTable.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.Syntax.NameManager.Add(String key, Int32 length)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.GetName(Type type)
   at Microsoft.CSharp.RuntimeBinder.SymbolTable.LoadSymbolsFromType(Type originalType)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.GetArgumentType(ICSharpBinder p, CSharpArgumentInfo argInfo, Expression param, DynamicMetaObject arg, Int32 index)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.CreateArgumentArray(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.BindCore(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(DynamicMetaObjectBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
   at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(DynamicMetaObjectBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
   at Microsoft.CSharp.RuntimeBinder.CSharpGetMemberBinder.FallbackGetMember(DynamicMetaObject target, DynamicMetaObject errorSuggestion)
   at System.Dynamic.DynamicMetaObject.BindGetMember(GetMemberBinder binder)
   at System.Dynamic.GetMemberBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
   at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
   at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.EntityFrameworkCore.Query.ComplexNavigationsQueryTestBase`2.<>c.<Netcoreapp_bug>b__247_1(Object e)
   at Microsoft.EntityFrameworkCore.Query.ComplexNavigationsQueryTestBase`2.Netcoreapp_bug()
```

I am unable to reproduce this in standalone app, this only happens in our test infrastructure (Entity Framework Core). Using xunit and we have generic and polymorphic test classes and tests are in multiple assemblies - maybe this has something to do with it, but so far we were unable to figure out the root cause. Let me know if you need any more info.

dotnet --version: 2.0.0-preview3-006607

**Comment by maumar** [comment]
In order to actually reproduce the issue:

clone https://github.com/aspnet/EntityFramework/tree/netcoreapp_bug
run `dotnet restore` on the solution
navigate to `\test\EFCore.InMemory.FunctionalTests`
run `dotnet test --framework netcoreapp2.0 --filter FullyQualifiedName~Netcoreapp_bug`

**Comment by jkotas** [comment]
This issue was moved to dotnet/corefx#21689
