### ISSUE TITLE
[RyuJIT/ARM32] Unhandled Exception: System.DataMisalignedException

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#12661]
With COMPlus_AltJit=* COMPlus_AltJitAssertOnNYI=0 options, following assertion is observed.
```
FAILED   - [6246][  15s]JIT/Regression/Dev11/External/Dev11_90434/UseUnalignedDouble/UseUnalignedDouble.sh
               BEGIN EXECUTION
               /home/dotnet_jenkins/workspace/hqueue/Run_coreclr_tests_Checked_ryujit_nyi_all/runtime/tests/Tests/coreoverlay/corerun UseUnalignedDouble.exe

               Unhandled Exception: System.DataMisalignedException: A datatype misalignment was detected in a load or store instruction.
                  at UnalignedDouble1.PtrAccess.StoreUnalignedDouble(Double* unalignedPtr, Double newValue)
                  at UnalignedDouble1.UnalignedDoubleHolder.GetDefaultInstance()
                  at UnalignedDouble1.App.UseUnalignedDouble()
                  at UnalignedDouble1.App.Main()
               ./UseUnalignedDouble.sh: line 240: 23834 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

## Related test
```
JIT/Regression/Dev11/External/Dev11_90434/UseUnalignedDouble/UseUnalignedDouble.sh
```

/cc: @dotnet/arm32-contrib

**Comment by mskvortsov** [comment]
I'll look into this. #11284 is related.
