### ISSUE TITLE
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libproc'

### ISSUE THREAD

**Issue by tarurar** [dotnet/coreclr#12672]
Getting the error while trying to run `dotnet run`:
```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libproc': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.libproc.proc_pidpath(Int32 pid, Byte* buffer, UInt32 bufferSize)
   at Interop.libproc.proc_pidpath(Int32 pid)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.ForwardingApp.Execute()
   at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp.Execute()
   at Microsoft.DotNet.Tools.Run.RunCommand.EnsureProjectIsBuilt()
   at Microsoft.DotNet.Tools.Run.RunCommand.Start()
   at Microsoft.DotNet.Tools.Run.RunCommand.<>c__DisplayClass0_0.<Run>b__0()
   at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
   at Microsoft.DotNet.Tools.Run.RunCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)
```
The same error I got when I was trying to run `dotnet restore`.

Environment info:
```
Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/1.0.4
```

The following file `/usr/lib/libproc.dylib` exists.

And here is the dump `otool -L /usr/lib/libproc.dylib`:
```
/usr/lib/libproc.dylib:

/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
/usr/lib/system/libcache.dylib (compatibility version 1.0.0, current version 79.0.0)
/usr/lib/system/libcommonCrypto.dylib (compatibility version 1.0.0, current version 60092.50.5)
/usr/lib/system/libcompiler_rt.dylib (compatibility version 1.0.0, current version 62.0.0)
/usr/lib/system/libcopyfile.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/lib/system/libcorecrypto.dylib (compatibility version 1.0.0, current version 442.50.19)
/usr/lib/system/libdispatch.dylib (compatibility version 1.0.0, current version 703.50.37)
/usr/lib/system/libdyld.dylib (compatibility version 1.0.0, current version 433.5.0)
/usr/lib/system/libkeymgr.dylib (compatibility version 1.0.0, current version 28.0.0)
/usr/lib/system/liblaunch.dylib (compatibility version 1.0.0, current version 972.60.2)
/usr/lib/system/libmacho.dylib (compatibility version 1.0.0, current version 898.0.0)
/usr/lib/system/libquarantine.dylib (compatibility version 1.0.0, current version 85.50.1)
/usr/lib/system/libremovefile.dylib (compatibility version 1.0.0, current version 45.0.0)
/usr/lib/system/libsystem_asl.dylib (compatibility version 1.0.0, current version 349.50.5)
/usr/lib/system/libsystem_blocks.dylib (compatibility version 1.0.0, current version 67.0.0)
/usr/lib/system/libsystem_c.dylib (compatibility version 1.0.0, current version 1158.50.2)
/usr/lib/system/libsystem_configuration.dylib (compatibility version 1.0.0, current version 888.60.2)
/usr/lib/system/libsystem_coreservices.dylib (compatibility version 1.0.0, current version 41.4.0)
/usr/lib/system/libsystem_coretls.dylib (compatibility version 1.0.0, current version 121.50.4)
/usr/lib/system/libsystem_dnssd.dylib (compatibility version 1.0.0, current version 765.50.9)
/usr/lib/system/libsystem_info.dylib (compatibility version 1.0.0, current version 503.50.4)
/usr/lib/system/libsystem_kernel.dylib (compatibility version 1.0.0, current version 3789.60.24)
/usr/lib/system/libsystem_m.dylib (compatibility version 1.0.0, current version 3121.6.0)
/usr/lib/system/libsystem_malloc.dylib (compatibility version 1.0.0, current version 116.50.8)
/usr/lib/system/libsystem_network.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/lib/system/libsystem_networkextension.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/lib/system/libsystem_notify.dylib (compatibility version 1.0.0, current version 165.20.1)
/usr/lib/system/libsystem_platform.dylib (compatibility version 1.0.0, current version 126.50.8)
/usr/lib/system/libsystem_pthread.dylib (compatibility version 1.0.0, current version 218.60.3)
/usr/lib/system/libsystem_sandbox.dylib (compatibility version 1.0.0, current version 592.60.1)
/usr/lib/system/libsystem_secinit.dylib (compatibility version 1.0.0, current version 24.50.4)
/usr/lib/system/libsystem_symptoms.dylib (compatibility version 1.0.0, current version 1.0.0)
/usr/lib/system/libsystem_trace.dylib (compatibility version 1.0.0, current version 518.60.2)
/usr/lib/system/libunwind.dylib (compatibility version 1.0.0, current version 35.3.0)
/usr/lib/system/libxpc.dylib (compatibility version 1.0.0, current version 972.60.2)
```

**Comment by adityamandaleeka** [comment]
Can you run `printenv | grep DYLD` in the shell where you're running dotnet and see if it prints anything?

**Comment by tarurar** [comment]
It prints nothing.

**Comment by adityamandaleeka** [comment]
OK, with that ruled out, I'd suggest trying another approach before we reach for a debugger. Can you run the `fs_usage` tool to see where dotnet is looking for libproc from?

You can open a second shell and run `sudo fs_usage -w -f filesys dotnet | grep libproc` and then run your `dotnet run` command in the other shell. This should print a list of file system operations along with paths. For your purposes, you don't need to understand every operation, but the paths should give you some clues as to what's going on.

**Comment by tarurar** [comment]
Well .., here is the log:
```
23:43:30.256550  stat64                 [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/libproc                                                                                                         0.000007   dotnet.3148391
23:43:30.256576  getattrlist            [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/libproc                                                                                                         0.000002   dotnet.3148391
23:43:30.256577  stat64                 [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/libproc                                                                                                         0.000001   dotnet.3148391
23:43:30.256605  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc                                                                                                    0.000004   dotnet.3148391
23:43:30.256621  getattrlist            [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc                                                                                                    0.000001   dotnet.3148391
23:43:30.256622  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc                                                                                                    0.000001   dotnet.3148391
23:43:30.256644  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc                                                                                                    0.000002   dotnet.3148391
23:43:30.256659  getattrlist            [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc                                                                                                    0.000001   dotnet.3148391
23:43:30.256660  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc                                                                                                    0.000001   dotnet.3148391
23:43:30.256676  stat64                 [  2]           libproc                                                                                                                                                               0.000002   dotnet.3148391
23:43:30.256682  stat64                 [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/libproc                                                             0.000006   dotnet.3148391
23:43:30.256705  getattrlist            [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/libproc                                                             0.000002   dotnet.3148391
23:43:30.256706  stat64                 [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/libproc                                                             0.000002   dotnet.3148391
23:43:30.256707  stat64                 [  2]           /libproc                                                                                                                                                              0.000001   dotnet.3148391
23:43:30.256708  getattrlist            [  2]           /libproc                                                                                                                                                              0.000001   dotnet.3148391
23:43:30.256709  stat64                 [  2]           /libproc                                                                                                                                                              0.000001   dotnet.3148391
23:43:30.256727  getattrlist            [  2]           /Users/atarutin/netcoreprojects/FirstCore/libproc                                                                                                                     0.000001   dotnet.3148391
23:43:30.256728  stat64                 [  2]           /Users/atarutin/netcoreprojects/FirstCore/libproc                                                                                                                     0.000001   dotnet.3148391
23:43:30.256752  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc.dylib                                                                                           0.000003   dotnet.3148391
23:43:30.256768  getattrlist            [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc.dylib                                                                                           0.000001   dotnet.3148391
23:43:30.256769  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc.dylib                                                                                           0.000001   dotnet.3148391
23:43:30.256786  stat64                 [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/liblibproc.dylib                                                                                                0.000003   dotnet.3148391
23:43:30.256806  getattrlist            [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/liblibproc.dylib                                                                                                0.000001   dotnet.3148391
23:43:30.256807  stat64                 [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/liblibproc.dylib                                                                                                0.000001   dotnet.3148391
23:43:30.256823  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc.dylib                                                                                           0.000002   dotnet.3148391
23:43:30.256838  getattrlist            [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc.dylib                                                                                           0.000001   dotnet.3148391
23:43:30.256839  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc.dylib                                                                                           0.000001   dotnet.3148391
23:43:30.256854  stat64                 [  2]           liblibproc.dylib                                                                                                                                                      0.000002   dotnet.3148391
23:43:30.256856  stat64                 [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/liblibproc.dylib                                                    0.000003   dotnet.3148391
23:43:30.256877  getattrlist            [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/liblibproc.dylib                                                    0.000002   dotnet.3148391
23:43:30.256878  stat64                 [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/liblibproc.dylib                                                    0.000002   dotnet.3148391
23:43:30.256879  stat64                 [  2]           /liblibproc.dylib                                                                                                                                                     0.000001   dotnet.3148391
23:43:30.256880  getattrlist            [  2]           /liblibproc.dylib                                                                                                                                                     0.000001   dotnet.3148391
23:43:30.256881  stat64                 [  2]           /liblibproc.dylib                                                                                                                                                     0.000001   dotnet.3148391
23:43:30.256891  getattrlist            [  2]           /Users/atarutin/netcoreprojects/FirstCore/liblibproc.dylib                                                                                                            0.000001   dotnet.3148391
23:43:30.256892  stat64                 [  2]           /Users/atarutin/netcoreprojects/FirstCore/liblibproc.dylib                                                                                                            0.000001   dotnet.3148391
23:43:30.256913  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc.dylib                                                                                              0.000003   dotnet.3148391
23:43:30.256929  getattrlist            [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc.dylib                                                                                              0.000001   dotnet.3148391
23:43:30.256930  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc.dylib                                                                                              0.000001   dotnet.3148391
23:43:30.256947  stat64                 [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/libproc.dylib                                                                                                   0.000003   dotnet.3148391
23:43:30.256966  getattrlist            [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/libproc.dylib                                                                                                   0.000001   dotnet.3148391
23:43:30.256967  stat64                 [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/libproc.dylib                                                                                                   0.000001   dotnet.3148391
23:43:30.256983  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc.dylib                                                                                              0.000002   dotnet.3148391
23:43:30.256998  getattrlist            [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc.dylib                                                                                              0.000001   dotnet.3148391
23:43:30.256999  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/libproc.dylib                                                                                              0.000001   dotnet.3148391
23:43:30.257014  stat64                 [  2]           libproc.dylib                                                                                                                                                         0.000002   dotnet.3148391
23:43:30.257016  stat64                 [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/libproc.dylib                                                       0.000002   dotnet.3148391
23:43:30.257036  getattrlist            [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/libproc.dylib                                                       0.000002   dotnet.3148391
23:43:30.257037  stat64                 [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/libproc.dylib                                                       0.000002   dotnet.3148391
23:43:30.257038  stat64                 [  2]           /libproc.dylib                                                                                                                                                        0.000001   dotnet.3148391
23:43:30.257039  getattrlist            [  2]           /libproc.dylib                                                                                                                                                        0.000001   dotnet.3148391
23:43:30.257040  stat64                 [  2]           /libproc.dylib                                                                                                                                                        0.000001   dotnet.3148391
23:43:30.257050  getattrlist            [  2]           /Users/atarutin/netcoreprojects/FirstCore/libproc.dylib                                                                                                               0.000001   dotnet.3148391
23:43:30.257051  stat64                 [  2]           /Users/atarutin/netcoreprojects/FirstCore/libproc.dylib                                                                                                               0.000001   dotnet.3148391
23:43:30.257071  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc                                                                                                 0.000003   dotnet.3148391
23:43:30.257086  getattrlist            [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc                                                                                                 0.000001   dotnet.3148391
23:43:30.257087  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc                                                                                                 0.000001   dotnet.3148391
23:43:30.257122  stat64                 [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/liblibproc                                                                                                      0.000013   dotnet.3148391
23:43:30.257150  getattrlist            [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/liblibproc                                                                                                      0.000001   dotnet.3148391
23:43:30.257151  stat64                 [  2]           /usr/local/share/dotnet/sdk/1.0.4/runtimes/any/native/liblibproc                                                                                                      0.000001   dotnet.3148391
23:43:30.257168  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc                                                                                                 0.000002   dotnet.3148391
23:43:30.257193  getattrlist            [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc                                                                                                 0.000001   dotnet.3148391
23:43:30.257204  stat64                 [  2]           /usr/local/share/dotnet/shared/Microsoft.NETCore.App/1.1.2/liblibproc                                                                                                 0.000011   dotnet.3148391
23:43:30.257219  stat64                 [  2]           liblibproc                                                                                                                                                            0.000002   dotnet.3148391
23:43:30.257222  stat64                 [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/liblibproc                                                          0.000003   dotnet.3148391
23:43:30.257242  getattrlist            [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/liblibproc                                                          0.000002   dotnet.3148391
23:43:30.257254  stat64                 [  2]           /Users/atarutin/.dnx/packages/Microsoft.AspNet.Server.Kestrel/1.0.0-rc1-final/runtimes/osx/native/liblibproc                                                          0.000012   dotnet.3148391
23:43:30.257255  stat64                 [  2]           /liblibproc                                                                                                                                                           0.000001   dotnet.3148391
23:43:30.257256  getattrlist            [  2]           /liblibproc                                                                                                                                                           0.000001   dotnet.3148391
23:43:30.257256  stat64                 [  2]           /liblibproc                                                                                                                                                           0.000001   dotnet.3148391
23:43:30.257267  getattrlist            [  2]           /Users/atarutin/netcoreprojects/FirstCore/liblibproc                                                                                                                  0.000001   dotnet.3148391
23:43:30.257268  stat64                 [  2]           /Users/atarutin/netcoreprojects/FirstCore/liblibproc                                                                                                                  0.000001   dotnet.3148391
```

**Comment by adityamandaleeka** [comment]
Well, that explains why it didn't find the one you have in /usr/lib... 😄

I'm downloading the 1.0.4 CLI tools now on my Mac to try this, and then we can compare the paths it searched.

**Comment by tarurar** [comment]
@adityamandaleeka, thank you for helping me.

**Comment by adityamandaleeka** [comment]
@tarurar You're welcome, happy to help.

I downloaded the 1.0.4 CLI binaries and ran a couple of checks. It looks like in every case, the /usr/lib one is being probed, while in your fs_usage output, we never see `/usr/lib/*libproc*`.

I assume you used the installer to install the dotnet tools? If so, can you please try downloading [this tar.gz](https://download.microsoft.com/download/E/7/8/E782433E-7737-4E6C-BFBF-290A0A81C3D7/dotnet-dev-osx-x64.1.0.4.tar.gz), extracting it, then running new/restore using the dotnet in there? This will help us understand whether the weirdness has anything to do with the installer workflow.

**Comment by jkotas** [comment]
https://github.com/dotnet/core-setup/issues/3279 tracks the specific issue of missing libproc.

https://github.com/dotnet/coreclr/issues/10520 tracks improving general diagnostic errors for native .dll loading errors.
