### ISSUE TITLE
[RyuJIT/ARM32] Unhandled Exception: System.MissingMethodException: Method not found: 'System.ReadOnlySpan`1<Char> System.SpanExtensions.AsSpan(System.String)'

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#12671]
With `COMPlus_AltJit=* COMPlus_AltJitAssertOnNYI=0` options, following assertion is observed.

```
               Unhandled Exception: System.MissingMethodException: Method not found: 'System.ReadOnlySpan`1<Char> System.SpanExtensions.AsSpan(System.String)'.
                  at Span.SpanBench.TestSpanAsSpanStringChar(String s, Int32 iterationCount, Boolean untrue)
                  at Span.SpanBench.<>c__DisplayClass92_0.<TestSpanAsSpanStringCharWrapper>b__0(Int32 innerIterationCount)
                  at Span.SpanBench.Invoke(Action`1 innerLoop, String nameFormat, Object[] nameArgs)
                  at Span.SpanBench.TestSpanAsSpanStringCharWrapper(Int32 length)
                  at Span.SpanBench.Main(String[] args)

```

## Related test
```
JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
```

/cc: @dotnet/arm32-contrib

**Comment by jkotas** [comment]
This was fixed by https://github.com/dotnet/coreclr/pull/12414
