### ISSUE TITLE
[RyuJIT/armel] Assert Failure `genIsValidDoubleReg(regRec->regNum)`

### ISSUE THREAD

**Issue by wateret** [dotnet/coreclr#12992]
Failed Tests
- JIT/Methodical/fp/exgen/10w5d_cs_do/10w5d_cs_do.exe
- JIT/Methodical/fp/exgen/10w5d_cs_ro/10w5d_cs_ro.exe
- JIT/Regression/CLR-x86-JIT/V1-M12-Beta2/b59782/b59782/b59782.exe

Backtrace (10w5d_cs_do.exe)

```
 98.#98  f9   Kill   Keep  f9   |    |    |    |    |----|----|----|----|----|----|----|----|    |----|    |----|    |    |    |    |    |    |    |    |    |    |C33i|C33i|    |    |    |    |V7 i|
 98.#99  f10  Kill   Restr f10  |    |    |    |    |----|----|----|----|----|----|----|----|    |----|    |----|    |    |    |    |    |    |    |    |    |    |V1 i|V1 i|    |    |    |    |V7 i|
                     Keep  f10  |    |    |    |    |----|----|----|----|----|----|----|----|    |----|    |----|    |    |    |    |    |    |    |    |    |    |V1 i|V1 i|    |    |    |    |V7 i|

Assert failure(PID 25594 [0x000063fa], Thread: 25594 [0x63fa]): Assertion failed 'genIsValidDoubleReg(regRec->regNum)' in 'testout1:Func_0_2_3_
2_5():double' (IL size 234)

    File: /opt/code/work/src/jit/lsra.cpp Line: 6346
    Image: /opt/usr/home/owner/dotnet/tto/corerun

 98.#100 f11  Kill
Program received signal SIGABRT, Aborted.
0xb6caa094 in raise () from /lib/libc.so.6
(gdb) bt
#8  0xb1272cec in assertAbort (
    why=0xb152f40c "genIsValidDoubleReg(regRec->regNum)",
---Type <return> to continue, or q <return> to quit---
    file=0xb152d68f "/opt/code/work/src/jit/lsra.cpp", line=6346)
    at /opt/code/work/src/jit/error.cpp:287
#9  0xb1340df6 in LinearScan::unassignPhysReg (this=0xbe050, regRec=0xbe544,
    spillRefPosition=0xc20d4) at /opt/code/work/src/jit/lsra.cpp:6346
#10 0xb1338c9a in LinearScan::allocateRegisters (this=0xbe050)
    at /opt/code/work/src/jit/lsra.cpp:7542
#11 0xb1336138 in LinearScan::doLinearScan (this=0xbe050)
    at /opt/code/work/src/jit/lsra.cpp:1776
#12 0xb1251e1e in Compiler::compCompile (this=0x802c0,
    methodCodePtr=0xbeffd14c, methodCodeSize=0xbeffd5f0,
    compileFlags=0xbeffd160) at /opt/code/work/src/jit/compiler.cpp:4829
```

**Comment by YongseopKim** [comment]
@BruceForstall please assign this to me.

**Comment by YongseopKim** [comment]
It may be solved by https://github.com/dotnet/coreclr/pull/13100. After https://github.com/dotnet/coreclr/pull/13100 is merged, I'll investigate it.

**Comment by alpencolt** [comment]
Tests passed on ARM32.
@wateret @YongseopKim  could you check on armel?

**Comment by YongseopKim** [comment]
@alpencolt Yes it passed on the latest corclr. Thank you for your checking ;)
@wateret Could you close this issue please?
