### ISSUE TITLE
[Arm32][Legacy Backend][GCStress 0xC] Unhandled Exception: System.ArgumentException: String contains invalid Unicode code points.

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#13201]
Test Failures:

```
437044.cmd_10304
openmutexpos4.cmd_5707
```

Example Output:

```

14:32:57 TestID: 437044.cmd_10304
14:32:57 Path  : baseservices/threading/regressions/beta2/437044/437044.cmd
14:32:57 
14:32:57 Started: Wed Aug 02 14:20:59 2017
14:32:57 Started: Wed Aug 02 14:21:13 2017
14:32:57 Output: TEST_CMD_LINE: baseservices\threading\regressions\beta2\437044> C:\Users\DDJOIN\arm64_ci\tests\tests\baseservices\threading\regressions\beta2\437044\437044.cmd 
14:32:57 BEGIN EXECUTION
14:32:57  "C:\Users\DDJOIN\arm64_ci\tests\tests\Tests\Core_Root\corerun.exe" 437044.exe 
14:32:57 Unhandled Exception: System.ArgumentException: String contains invalid Unicode code points.
14:32:57    at System.Text.OSEncoding.WideCharToMultiByte(Int32 codePage, Char* pChars, Int32 count, Byte* pBytes, Int32 byteCount)
14:32:57    at System.Text.OSEncoder.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, Boolean flush)
14:32:57    at System.Text.OSEncoder.GetBytes(Char[] chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex, Boolean flush)
14:32:57    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
14:32:57    at System.IO.StreamWriter.Write(String value)
14:32:57    at System.IO.SyncTextWriter.Write(String value)
14:32:57    at System.Console.Write(String value)
14:32:57    at Test.Thread2()
14:32:57    at System.Threading.Thread.ThreadMain_ThreadStart()
14:32:57    at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
14:32:57    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
14:32:57    at System.Threading.ThreadHelper.ThreadStart()
14:32:57 Expected: 100
14:32:57 Actual: -532462766
14:32:57 END EXECUTION - FAILED
14:32:57 FAILED
```

**Comment by RussKeldorph** [comment]
Lower priority unless repros on RyuJIT.  Keeping open unless/until we know we won't need.

**Comment by RussKeldorph** [comment]
Closing assuming not fixing legacy backend.
