### ISSUE TITLE
[RyuJIT/ARM32] Unhandled Exception: System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'US-ASCII' fallback 'System.Text.EncoderReplacementFallback'

### ISSUE THREAD

**Issue by hqueue** [dotnet/coreclr#13311]
With `COMPlus_AltJit=*`, following exception is observed from `Release` build of CoreCLR.

```
FAILED   - [6333][  54s]JIT/Performance/CodeQuality/BenchmarksGame/fasta/fasta/fasta.sh
               BEGIN EXECUTION
               /var/jenkins59/workspace/hqueue/Run_coreclr_tests_Checked_ryujit_nyi_all_pri2/runtime/tests/Tests/coreoverlay/corerun fasta.exe

               Unhandled Exception: System.ArgumentException: The output byte buffer is too small to contain the encoded data, encoding 'US-ASCII' fallback 'System.Text.EncoderReplacementFallback'.
               Parameter name: bytes
                  at System.Text.Encoding.ThrowBytesOverflow()
                  at System.Text.Encoding.ThrowBytesOverflow(EncoderNLS encoder, Boolean nothingEncoded)
                  at System.Text.ASCIIEncoding.GetBytes(Char* chars, Int32 charCount, Byte* bytes, Int32 byteCount, EncoderNLS encoder)
                  at System.Text.ASCIIEncoding.GetBytes(String chars, Int32 charIndex, Int32 charCount, Byte[] bytes, Int32 byteIndex)
                  at System.Text.Encoding.GetBytes(String s)
                  at BenchmarksGame.Fasta.MakeRepeatFasta(String id, String desc, Byte[] alu, Int32 n, Stream s)
                  at BenchmarksGame.Fasta.Main(String[] args)
               ./fasta.sh: line 243: 31482 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED

```

Related tests:
```
FAILED   - [6333][  54s]JIT/Performance/CodeQuality/BenchmarksGame/fasta/fasta/fasta.sh
FAILED   - [6334][  31s]JIT/Performance/CodeQuality/BenchmarksGame/fastaredux/fastaredux/fastaredux.sh
FAILED   - [6335][  31s]JIT/Performance/CodeQuality/BenchmarksGame/k-nucleotide/k-nucleotide/k-nucleotide.sh
```

**Comment by hqueue** [comment]
@BruceForstall Please assign this to me.

**Comment by hqueue** [comment]
With recent commit (fix bugs and regression), all three test passed.
