### ISSUE TITLE
[Arm64][Windows] Regressions

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#13796]
Tests:

```
JIT\Regression\JitBlue\GitHub_11408\GitHub_11408\GitHub_11408.cmd
JIT/Regression/JitBlue/GitHub_13404/GitHub_13404/GitHub_13404.cmd
baseservices/threading/generics/threadstart/GThread07/GThread07.cmd
Regressions/coreclr/0416/hello/hello.cmd
Regressions/coreclr/0433/test/test.cmd
Regressions/coreclr/0487/test/test.cmd
```

Test Output

```
14:15:49 Path  : JIT/Regression/JitBlue/GitHub_11408/GitHub_11408/GitHub_11408.cmd
14:15:49 
14:15:49 Started: Tue Sep 05 14:12:42 2017
14:15:49 Started: Tue Sep 05 14:12:44 2017
14:15:49 Output: TEST_CMD_LINE: JIT\Regression\JitBlue\GitHub_11408\GitHub_11408> C:\Users\DDJOIN\arm64_ci\tests\tests\JIT\Regression\JitBlue\GitHub_11408\GitHub_11408\GitHub_11408.cmd 
14:15:49 BEGIN EXECUTION
14:15:49  "C:\Users\DDJOIN\arm64_ci\tests\tests\Tests\Core_Root\corerun.exe" GitHub_11408.exe 
14:15:49 211
14:15:49 Fail
14:15:49 Expected: 100
14:15:49 Actual: -1
14:15:49 END EXECUTION - FAILED
14:15:49 FAILED

14:15:49 TestID: GitHub_13404.cmd_11677
14:15:49 Path  : JIT/Regression/JitBlue/GitHub_13404/GitHub_13404/GitHub_13404.cmd
14:15:49 
14:15:49 Started: Tue Sep 05 14:12:43 2017
14:15:49 Started: Tue Sep 05 14:12:45 2017
14:15:49 Output: TEST_CMD_LINE: JIT\Regression\JitBlue\GitHub_13404\GitHub_13404> C:\Users\DDJOIN\arm64_ci\tests\tests\JIT\Regression\JitBlue\GitHub_13404\GitHub_13404\GitHub_13404.cmd 
14:15:49 BEGIN EXECUTION
14:15:49  "C:\Users\DDJOIN\arm64_ci\tests\tests\Tests\Core_Root\corerun.exe" GitHub_13404.exe 
14:15:49 FAIL
14:15:49 Expected: 100
14:15:49 Actual: 1
14:15:49 END EXECUTION - FAILED
14:15:49 FAILED

14:15:49 TestID: GThread07.cmd_226
14:15:49 Path  : baseservices/threading/generics/threadstart/GThread07/GThread07.cmd
14:15:49 
14:15:49 Started: Tue Sep 05 13:26:40 2017
14:15:49 Started: Tue Sep 05 13:26:46 2017
14:15:49 Output: TEST_CMD_LINE: baseservices\threading\generics\threadstart\GThread07> C:\Users\DDJOIN\arm64_ci\tests\tests\baseservices\threading\generics\threadstart\GThread07\GThread07.cmd 
14:15:49 BEGIN EXECUTION
14:15:49  "C:\Users\DDJOIN\arm64_ci\tests\tests\Tests\Core_Root\corerun.exe" GThread07.exe 
14:15:49 Unhandled Exception: System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.
14:15:49    at System.Threading.Thread.StartupSetApartmentStateInternal()
14:15:49    at System.Threading.Thread.Start(StackCrawlMark& stackMark)
14:15:49    at System.Threading.Thread.Start()
14:15:49    at Internal.Runtime.Augments.RuntimeThread.Start()
14:15:49    at Gen`1.ThreadPoolTest()
14:15:49    at Test.Main()
14:15:49 Expected: 100
14:15:49 Actual: 255
14:15:49 END EXECUTION - FAILED
14:15:49 FAILED

14:15:49 Path  : Regressions/coreclr/0416/hello/hello.cmd
14:15:49 
14:15:49 Started: Tue Sep 05 14:04:08 2017
14:15:49 Started: Tue Sep 05 14:04:08 2017
14:15:49 Output: TEST_CMD_LINE: Regressions\coreclr\0416\hello> C:\Users\DDJOIN\arm64_ci\tests\tests\Regressions\coreclr\0416\hello\hello.cmd 
14:15:49 BEGIN EXECUTION
14:15:49  "C:\Users\DDJOIN\arm64_ci\tests\tests\Tests\Core_Root\corerun.exe" hello.exe 
14:15:49 Expected: 100
14:15:49 Actual: -1
14:15:49 END EXECUTION - FAILED
14:15:49 FAILED

```

**Comment by sdmaclea** [comment]
Related #13629
