### ISSUE TITLE
Can not connect to remote Raspberry PI running Windows IoT over SSH by Visual Studio 2017

### ISSUE THREAD

**Issue by xuliujian** [dotnet/coreclr#14077]
When connecting to remote Raspberry PI running Windows IoT over SSH by Visual Studio 2017 (version 15.3.4), there is an error so that can not connect successfully.  The exception information such as:

`liblinux.ExceptionBase: Could not retrieve the system properties. Please see the inner exception for more details. ---> liblinux.Shell.CommandingException: Timed out executing command 'cat /etc/*-release', waited for 15137.9066ms. ---> liblinux.Ssh.Common.SshOperationTimeoutException: Command 'cat /etc/*-release' has timed out.
   at liblinux.Ssh.SshCommand.WaitOnHandle(WaitHandle waitHandle)
   at liblinux.Ssh.SshCommand.EndExecute(IAsyncResult asyncResult)
   at liblinux.Shell.NonHostedCommand.OnRun()
   --- End of inner exception stack trace ---
   at liblinux.Shell.NonHostedCommand.OnRun()
   at liblinux.Shell.CommonCommandBase.Run()
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText, TimeSpan timeout)
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText, Int32 timeout)
   at liblinux.Shell.CommandHost.ExecuteCommand(String commandText)
   at liblinux.DistributionId.GetSystemId(IRemoteSystem remoteSystem)
   at liblinux.DistributionId.GetDistributionId(IRemoteSystem remoteSystem)
   at liblinux.SystemProperties.Populate()
   --- End of inner exception stack trace ---
   at liblinux.SystemProperties.Populate()
   at liblinux.SystemProperties..ctor(IRemoteSystem remoteSystem)
   at liblinux.UnixSystem.get_Properties()
   at SSHConnectionUI.MainWindow.login_Click(Object sender, RoutedEventArgs e)
`

But when using Putty or SecureCRT tool to connect, it is ok. Additionally, visual studio 2017 can connect to remote Raspberry PI running with Linux.

**Comment by RussKeldorph** [comment]
This issue doesn't appear related to dotnet/coreclr.  Did you open it in the wrong repo?
