### ISSUE TITLE
Enum.GetValues change of behavior 

### ISSUE THREAD

**Issue by pmcgrath** [dotnet/coreclr#14355]
I am seeing a change of behavior with Enum.GetValues and Enum.GetNames on dotnet core

On full .NET it will tolerate and work with enums that have duplicate values
I will use [HttpStatusCode](https://github.com/dotnet/corefx/blob/bffef76f6af208e2042a2f27bc081ee908bb390b/src/System.Net.Primitives/src/System/Net/HttpStatusCode.cs)  to illustrate this, note the MultipleChoices = 300 and Ambiguous = 300 members have the same value

# My dotnet core env
```
dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\utilities\dotnet-core-sdks\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

# Demo app
```
using System;
using System.Net;

namespace test_dn {
    class Program {
        static void Main(string[] args) {
            Console.WriteLine(Enum.GetValues(typeof(HttpStatusCode)).Length);
        }
    }
}
```

When I use .NET framework via csc I get no runtime exception and a correct count = 47
When I use dotnet core I get the following error 

```
of type 'System.ArgumentException' occurred in System.Private.CoreLib.dll: 'An item with the same key has already been added. Key: 300'
   at System.ThrowHelper.ThrowAddingDuplicateWithKeyArgumentException(Object key)
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](TSource[] source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at test_dn.Program.Main(String[] args) in C:\tmp\test-dn\Program.cs:line 11
```

Could not find any mention of this change in behavior via google and the method signatures indicate Array and string[] as return types, exception indicates a dictionary is being used internally hence the failure I'm guessing

Is this a documented change ?

Thanks
Pat

**Comment by mattwarren** [comment]
That's weird, if I run your code it works fine, here's my environment info (same `dotnet` version, different OS)

```
λ dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.1.7601
 OS Platform: Windows
 RID:         win7-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

and here's the output

```
λ dotnet run
47
```

Is the code sample above enough to reproduce the issue? It's just that the stack trace starts:

```
at test_dn.Program.Main(String[] args) in C:\tmp\test-dn\Program.cs:line 11
```

And there aren't 11 lines in the code?

**Comment by mattwarren** [comment]
Just to add, I update the sample code to the following (to test `GetValues` and `GetNames`) and it still works?

``` csharp
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Enum.GetValues: Length = " + Enum.GetValues(typeof(HttpStatusCode)).Length);
            Console.WriteLine("Enum.GetNames:  Length = " + Enum.GetNames(typeof(HttpStatusCode)).Length);

**Comment by pmcgrath** [comment]
My bad, issue was due to how I was using the enums

Re code - I extracted it as a simpler example, thought I had run it

Turns out I was trying to populate a dictionary keyed of the HttpStatusCode, guessing the dictionary key is based on a hash of the HttpStatusCode enum which is the numeric value

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;

namespace test_dn {
    class Program {
        static void Main(string[] args) {
            // I need to get distinct before I create a dictionary - guessing the dictionary key is the enum's numeric value
            var httpStatusCodeStringMap = Enum.GetValues(typeof(HttpStatusCode)).Cast<HttpStatusCode>().OrderBy(h => h).Distinct().ToDictionary(code => code, code => ((int)code).ToString());

            foreach(var code in new [] { HttpStatusCode.Ambiguous, HttpStatusCode.MultipleChoices }) {
                Console.WriteLine($"{code} -> {httpStatusCodeStringMap[code]}");
            }

            Console.WriteLine(httpStatusCodeStringMap[HttpStatusCode.Ambiguous]);
            Console.WriteLine(httpStatusCodeStringMap[HttpStatusCode.MultipleChoices]);

            Console.WriteLine($"Http status code count : {Enum.GetValues(typeof(HttpStatusCode)).Length}");
            Console.WriteLine($"Distinct numeric http status codes : {Enum.GetValues(typeof(HttpStatusCode)).Cast<HttpStatusCode>().OrderBy(h => h).Distinct().Count()}");
        }
    }
}
```

Apologies for wasting your time, I'm going to close this issue
Pat

**Comment by mattwarren** [comment]
no problem, glad that it's working for you
