### ISSUE TITLE
Failing test crashes dotnet process

### ISSUE THREAD

**Issue by arekpalinski** [dotnet/coreclr#14354]
I have a consistency failing test case (xunit) for a given seed of `new Random())`. It's here:
https://github.com/arekpalinski/ravendb/blob/RavenDB-8903/test/FastTests/Blittable/PeepingTomTest.cs#L30

Running this single test from the command line results in the following exception:
```
C:\workspace\ravendb-4.0 [RavenDB-8903]> cd .\test\FastTests
C:\workspace\ravendb-4.0\test\FastTests [RavenDB-8903]> dotnet xunit -method FastTests.Blittable.PeepingTomTest.PeepingTomStreamShouldPeepCorrectlyWithRandomValues
Detecting target frameworks in FastTests.csproj...
Building for framework netcoreapp2.0...
[....]
Running .NET Core tests for framework netcoreapp2.0...
xUnit.net Console Runner (64-bit .NET Core 4.6.00001.0)
  Discovering: FastTests
  Discovered:  FastTests
  Starting:    FastTests
    FastTests.Blittable.PeepingTomTest.PeepingTomStreamShouldPeepCorrectlyWithRandomValues(seed: 1291481720) [FAIL]
      System.ArgumentOutOfRangeException : The length cannot be greater than the capacity.
      Parameter name: valueCount
      Stack Trace:
           at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
           at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
        C:\workspace\ravendb-4.0\test\FastTests\Blittable\PeepingTomTest.cs(61,0): at FastTests.Blittable.PeepingTomTest.PeepingTomStreamTest(Int32 originalSize, Int32 chunkSizeToRead, Int32 offset, JsonOperationContext context)
        C:\workspace\ravendb-4.0\test\FastTests\Blittable\PeepingTomTest.cs(43,0): at FastTests.Blittable.PeepingTomTest.PeepingTomStreamShouldPeepCorrectlyWithRandomValues(Int32 seed)
  Finished:    FastTests
=== TEST EXECUTION SUMMARY ===
   FastTests  Total: 2, Errors: 0, Failed: 1, Skipped: 0, Time: 0.213s
```

The problem is that running all tests of `FastTests` project makes `dotnet` process crash.

In order to reproduce:

1) clone my repository: `git clone git@github.com:arekpalinski/ravendb.git`
2) checkout `RavenDB-8903` branch: `git checkout RavenDB-8903` (failing test case is just there)
3) `> cd .\test\FastTests`
4) `> dotnet xunit`
then I'm getting `dotnet has stopped working` window:

```
[Window Title]
dotnet

[Main Instruction]
dotnet has stopped working

[Content]
A problem caused the program to stop working correctly. Windows will close the program and notify you if a solution is available.

[Debug] [Close program]	
```
5) `> dotnet test` results in `the active test run was aborted. Reason:`

```
C:\workspace\ravendb-4.0\test\FastTests [RavenDB-8903]> dotnet test
Build started, please wait...
Build completed.

Test run for C:\workspace\ravendb-4.0\test\FastTests\bin\Debug\netcoreapp2.0\FastTests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.0106157]   Discovering: FastTests
[xUnit.net 00:00:01.5553485]   Discovered:  FastTests
[xUnit.net 00:00:01.5615060]   Starting:    FastTests
[xUnit.net 00:00:04.1890521]     FastTests.Voron.Backups.BackupToOneZipFile.FullBackupToOneZipFile [SKIP]
[xUnit.net 00:00:04.1894934]       Should add database record to backup and restore
[xUnit.net 00:00:04.1926077]     FastTests.Voron.Backups.BackupToOneZipFile.IncrementalBackupToOneZipFile [SKIP]
[xUnit.net 00:00:04.1929328]       Should add database record to backup and restore
Skipped  FastTests.Voron.Backups.BackupToOneZipFile.FullBackupToOneZipFile
Standard Output Messages:
 Should add database record to backup and restore
Skipped  FastTests.Voron.Backups.BackupToOneZipFile.IncrementalBackupToOneZipFile
Standard Output Messages:
 Should add database record to backup and restore
The active test run was aborted. Reason:

Total tests: 491. Passed: 489. Failed: 0. Skipped: 2.
Test Run Failed.
Test execution time: 16.9560 Seconds
```

If  steps 4. or 5. don't error then repeat that command (I have checked it on two machines, it typically errors on 1-2 run)

In the event viewer I see:
1) Error:
```
Faulting application name: dotnet.exe, version: 2.0.25521.1, time stamp: 0x597139df
Faulting module name: coreclr.dll, version: 4.6.25519.2, time stamp: 0x596f8abf
Exception code: 0xc0000005
Fault offset: 0x000000000017543d
Faulting process id: 0x445c
Faulting application start time: 0x01d33e7bc7f4e93a
Faulting application path: C:\Program Files\dotnet\dotnet.exe
Faulting module path: C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0\coreclr.dll
Report Id: 0aa9cb7b-3192-4663-a977-f89f83393918
Faulting package full name: 
Faulting package-relative application ID: 
```

2) Information:
```Fault bucket 120844845049, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: dotnet.exe
P2: 2.0.25521.1
P3: 597139df
P4: coreclr.dll
P5: 4.6.25519.2
P6: 596f8abf
P7: c0000005
P8: 000000000017543d
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A19.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1DD3.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1DE2.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1E31.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_dotnet.exe_a2f014eb8768a54acfd6ef4ac57aab80254f1d94_7fa847c7_4c5d4788

Analysis symbol: 
Rechecking for solution: 0
Report Id: 0aa9cb7b-3192-4663-a977-f89f83393918
Report Status: 268435456
Hashed bucket: 31ebdac9f30a6f76d8a7a312202c287d
```

The above errors has been exported. 

In `C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_dotnet.exe_a2f014eb8768a54acfd6ef4ac57aab80254f1d94_7fa847c7_4c5d4788` I found `Report.wer` file  (there were no more files there). 

Also caught Process Monitor results during `> dotnet xunit` 

Everyting can be found here: https://1drv.ms/f/s!AqoX7tk71dAv6W38PLbkgFDXIRJB

Dotnet info:
```
> dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by ayende** [comment]
This is caused by heap corruption in our code, not an issue the the CLR
