### ISSUE TITLE
[legacy x86 ryujit][Windows] Perf harness fails to download the JitBench repo.

### ISSUE THREAD

**Issue by jorive** [dotnet/coreclr#14477]
Repro steps:
```cmd
set "__TestIntermediateDir=int"
.\build.cmd release x86
.\tests\runtest.cmd release x86 GenerateLayoutOnly
.\tests\scripts\run-xunit-perf.cmd -arch x86 -configuration Release -runtype local -testEnv "C:\github\dotnet\coreclr\tests\legacyjit_x86_testenv.cmd" -optLevel full_opt -jitName legacy_backend -scenarioTest -testBinLoc bin\tests\Windows_NT.x86.Release\performance\Scenario\JitBench -group CoreCLR-Scenarios
```

This is the exception:
```
Unhandled Exception: System.AggregateException: One or more errors occurred. (An error occurred while sending the request.) ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.WinHttpException: The URL is invalid
   at System.Net.Http.WinHttpHandler.ThrowOnInvalidHandle(SafeWinHttpHandle handle) in E:\A\_work\1317\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 1318
   at System.Net.Http.WinHttpHandler.<StartRequest>d__105.MoveNext() in E:\A\_work\1317\s\corefx\src\System.Net.Http.WinHttpHandler\src\System\Net\Http\WinHttpHandler.cs:line 791
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext() in E:\A\_work\1317\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 489
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishGetStreamAsync>d__33.MoveNext() in E:\A\_work\1317\s\corefx\src\System.Net.Http\src\System\Net\Http\HttpClient.cs:line 252
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at JitBenchRepro.Program.Main(String[] args) in B:\TEMP\JitBenchRepro\Program.cs:line 23
```

This is a smaller repro:
```csharp
using System;
using System.IO;
using System.IO.Compression;
using System.Net.Http;

namespace JitBenchRepro
{
    class Program
    {
        static void Main(string[] args)
        {
            var archiveName = @"b7e7b786c60daa255aacaea85006afe4d4ec8306.zip";
            var url = $"https://github.com/aspnet/JitBench/archive/{archiveName}";
            var zipFile = Path.Combine(Directory.GetCurrentDirectory(), archiveName);

            if (File.Exists(zipFile))
                File.Delete(zipFile);

            using (var client = new HttpClient())
            {
                using (FileStream tmpzip = File.Create(zipFile))
                {
                    using (Stream stream = client.GetStreamAsync(url).Result) // ERROR: Fail here.
                        stream.CopyTo(tmpzip);
                    tmpzip.Flush();
                }
            }

            Console.WriteLine("Finished downloading...");

            if (File.Exists(zipFile))
                File.Delete(zipFile);
        }
    }
}
```

**Comment by BruceForstall** [comment]
@jorive Does this same code work when not using legacy x86 backend? Why would this code, which looks like harness code, ever be run by legacy backend? the "testEnv" environment should only apply to running the test, not any harness code.

**Comment by BruceForstall** [comment]
@RussKeldorph I'm inclined not to fix this.

**Comment by jorive** [comment]
@BruceForstall Yes, this work on non-legacy x64 and x86.

**Comment by RussKeldorph** [comment]
@BruceForstall Not terribly surprising.  We do need to resolve the failure one way or another, however.

**Comment by jorive** [comment]
@BruceForstall @RussKeldorph I have disabled the perf scenario runs on legacy due to this bug (There is no reason to use machine time at this point).

**Comment by BruceForstall** [comment]
Closing all x86 legacy backend bugs
