### ISSUE TITLE
CI Failures: OSX (fatal: unable to write new index file)

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#14688]
```
02:13:26 GitHub pull request #14655 of commit 8eb92370085b19192839f93b72a337072bb943de, no merge conflicts.
02:13:26 Notifying endpoint with credentials id 'helix-int-notification-url'
02:13:26 Notifying endpoint with credentials id 'helix-prod-notification-url'
02:13:27 Setting status of 8eb92370085b19192839f93b72a337072bb943de to PENDING with url https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_flow_prtest/8500/ and message: 'Started.'
02:13:27 Using context: OSX10.12 x64 Checked Innerloop Build and Test
02:13:27 Building remotely on dci-mac-build-086 (dtap osx-10.12 osx-10.12-elevated) in workspace /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_flow_prtest
02:13:27 [WS-CLEANUP] Deleting project workspace...
02:13:27 [WS-CLEANUP] Done
02:13:27 Selected Git installation does not exist. Using Default
02:13:27 Cloning the remote Git repository
02:13:27 Cloning repository https://github.com/dotnet/coreclr
02:13:27  > git init /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx10.12_flow_prtest # timeout=10
02:13:27 Fetching upstream changes from https://github.com/dotnet/coreclr
02:13:27  > git --version # timeout=10
02:13:27  > git fetch --tags --progress https://github.com/dotnet/coreclr +refs/heads/*:refs/remotes/origin/* # timeout=90
02:13:39  > git config remote.origin.url https://github.com/dotnet/coreclr # timeout=10
02:13:39  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
02:13:39  > git config remote.origin.url https://github.com/dotnet/coreclr # timeout=10
02:13:39 Fetching upstream changes from https://github.com/dotnet/coreclr
02:13:39  > git fetch --tags --progress https://github.com/dotnet/coreclr +refs/pull/14655/*:refs/remotes/origin/pr/14655/* # timeout=90
02:13:40  > git rev-parse refs/remotes/origin/pr/14655/merge^{commit} # timeout=10
02:13:40  > git rev-parse refs/remotes/origin/origin/pr/14655/merge^{commit} # timeout=10
02:13:40 JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
02:13:40 Checking out Revision 27019068c395250c8d4c6f44f6288d497fc23892 (refs/remotes/origin/pr/14655/merge)
02:13:40 Commit message: "Merge 8eb92370085b19192839f93b72a337072bb943de into 980def6282c9c64d38a218c3f37093d130222458"
02:13:40  > git config core.sparsecheckout # timeout=10
02:13:40  > git checkout -f 27019068c395250c8d4c6f44f6288d497fc23892
02:13:50 FATAL: Could not checkout 27019068c395250c8d4c6f44f6288d497fc23892
02:13:50 hudson.plugins.git.GitException: Command "git checkout -f 27019068c395250c8d4c6f44f6288d497fc23892" returned status code 128:
02:13:50 stdout: 
02:13:50 stderr: fatal: unable to write new index file
02:13:50 
02:13:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
02:13:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:71)
02:13:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2214)
02:13:50 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
02:13:50 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
02:13:50 	at hudson.remoting.UserRequest.perform(UserRequest.java:181)
02:13:50 	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
02:13:50 	at hudson.remoting.Request$2.run(Request.java:336)
02:13:50 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
02:13:50 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:13:50 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
02:13:50 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
02:13:50 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
02:13:50 	at java.lang.Thread.run(Thread.java:745)
02:13:50 Caused: hudson.plugins.git.GitException: Could not checkout 27019068c395250c8d4c6f44f6288d497fc23892
02:13:50 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2237)
02:13:50 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
02:13:50 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
02:13:50 	at hudson.remoting.UserRequest.perform(UserRequest.java:181)
02:13:50 	at hudson.remoting.UserRequest.perform(UserRequest.java:52)
02:13:50 	at hudson.remoting.Request$2.run(Request.java:336)
02:13:50 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
02:13:50 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02:13:50 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
02:13:50 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
02:13:50 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
02:13:50 	at java.lang.Thread.run(Thread.java:745)
02:13:50 	at ......remote call to JNLP4-connect connection from 131.107.19.175/131.107.19.175:59741(Native Method)
02:13:50 	at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1654)
02:13:50 	at hudson.remoting.UserResponse.retrieve(UserRequest.java:311)
02:13:50 	at hudson.remoting.Channel.call(Channel.java:905)
02:13:50 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
02:13:50 	at sun.reflect.GeneratedMethodAccessor308.invoke(Unknown Source)
02:13:50 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
02:13:50 	at java.lang.reflect.Method.invoke(Method.java:498)
02:13:50 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
02:13:50 	at com.sun.proxy.$Proxy179.execute(Unknown Source)
02:13:50 	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
02:13:50 	at hudson.scm.SCM.checkout(SCM.java:495)
02:13:50 	at hudson.model.AbstractProject.checkout(AbstractProject.java:1212)
02:13:50 	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:566)
02:13:50 	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
02:13:50 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:491)
02:13:50 	at hudson.model.Run.execute(Run.java:1737)
02:13:50 	at com.cloudbees.plugins.flow.FlowRun.run(FlowRun.java:153)
02:13:50 	at hudson.model.ResourceController.execute(ResourceController.java:97)
02:13:50 	at hudson.model.Executor.run(Executor.java:421)
02:13:50 [BFA] Scanning build for known causes...
02:13:50 [BFA] No failure causes found
02:13:50 [BFA] Done. 0s
02:13:50 Notifying endpoint with credentials id 'helix-int-notification-url'
02:13:50 Notifying endpoint with credentials id 'helix-prod-notification-url'
02:13:51 Setting status of 8eb92370085b19192839f93b72a337072bb943de to FAILURE with url https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx10.12_flow_prtest/8500/ and message: 'Build finished. '
02:13:51 Using context: OSX10.12 x64 Checked Innerloop Build and Test
02:13:51 [WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
02:13:56 [WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
02:13:56 Finished: FAILURE
```

**Comment by benaadams** [comment]
Error in https://github.com/dotnet/coreclr/pull/14684
Error in https://github.com/dotnet/coreclr/pull/14655

**Comment by jkotas** [comment]
@dotnet/dnceng We are seeing a lot of `stderr: fatal: unable to write new index file` failures in CI

**Comment by ravimeda** [comment]
`dci-mac-build-086` that is low on disk space. Clearing up now...

**Comment by ravimeda** [comment]
Started OSX job on https://github.com/dotnet/coreclr/pull/14684 and https://github.com/dotnet/coreclr/pull/14655

**Comment by ravimeda** [comment]
Both OSX jobs succeeded.

**Comment by ravimeda** [comment]
@benaadams thanks for reporting the issue. Fix https://github.com/dotnet/dotnet-ci/commit/9c6484a632e29755e15a32feda81abae12f42d75 ensures CI jobs on OSX machines will cleanup correctly so that sufficient disk space is available.

**Comment by benaadams** [comment]
Thank you!
