### ISSUE TITLE
corefx XsltCompiler.Tests fails under altjit

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#14810]
e.g., "Windows_NT x86_arm_altjit Checked corefx_baseline"

```
=== TEST EXECUTION SUMMARY ===
   XsltCompiler.Tests  Total: 36, Errors: 0, Failed: 34, Skipped: 0, Time: 55.474s
```

Output:
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: XsltCompiler.Tests
Discovered:  XsltCompiler.Tests
Starting:    XsltCompiler.Tests
   System.Xml.Tests.XsltcTestPlatform.Var3(param0: \"pft19.xsl\", param1: \"pft19.dll\", param2: \"yes\", param3: \"\", param4: \"pft19.pdb\", param5: \"no\", param6: \"pft19.txt\", param7: \"no\") [STARTING]
   System.Xml.Tests.XsltcTestPlatform.Var3(param0: \"pft19.xsl\", param1: \"pft19.dll\", param2: \"yes\", param3: \"\", param4: \"pft19.pdb\", param5: \"no\", param6: \"pft19.txt\", param7: \"no\") [FAIL]
      OLEDB.Test.ModuleCore.CTestFailedException : Failed to create assembly: 
      Stack Trace:
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(290,0): at System.Xml.Tests.XsltcTestCaseBase.TryCreatePersistedTransformAssembly(String commandLine, Boolean createFromInputFile, Boolean expectedToSucceed, String targetDirectory)
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(152,0): at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile)
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestPlatform.cs(93,0): at System.Xml.Tests.XsltcTestPlatform.Var3(Object param0, Object param1, Object param2, Object param3, Object param4, Object param5, Object param6, Object param7)
   System.Xml.Tests.XsltcTestPlatform.Var3(param0: \"pft19.xsl\", param1: \"pft19.dll\", param2: \"yes\", param3: \"\", param4: \"pft19.pdb\", param5: \"no\", param6: \"pft19.txt\", param7: \"no\") [FINISHED] Time: 1.9476365s
   System.Xml.Tests.XsltcTestPlatform.Var2(param0: \"/platform: pft2.xsl\", param1: \"pft2.txt\") [STARTING]
   System.Xml.Tests.XsltcTestPlatform.Var2(param0: \"/platform: pft2.xsl\", param1: \"pft2.txt\") [FAIL]
      OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.
      Stack Trace:
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(102,0): at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count)
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(186,0): at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile)
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestPlatform.cs(54,0): at System.Xml.Tests.XsltcTestPlatform.Var2(Object param0, Object param1)
   System.Xml.Tests.XsltcTestPlatform.Var2(param0: \"/platform: pft2.xsl\", param1: \"pft2.txt\") [FINISHED] Time: 1.7939921s
   System.Xml.Tests.XsltcTestPlatform.Var2(param0: \"/platform:foo pft4.xsl\", param1: \"pft4.txt\") [STARTING]
   System.Xml.Tests.XsltcTestPlatform.Var2(param0: \"/platform:foo pft4.xsl\", param1: \"pft4.txt\") [FAIL]
      OLEDB.Test.ModuleCore.CTestFailedException : Output was not as expected.
      Stack Trace:
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(102,0): at System.Xml.Tests.XsltcTestCaseBase.CompareOutput(Stream expectedStream, Stream actualStream, Int32 count)
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestCaseBase.cs(186,0): at System.Xml.Tests.XsltcTestCaseBase.VerifyTest(String cmdLine, String asmName, Boolean asmCreated, String typeName, String pdbName, Boolean pdbCreated, String baselineFile, Boolean runAssemblyVerification, Boolean loadFromFile)
         E:\gh\corefx\src\System.Private.Xml\tests\Xslt\XsltCompiler\CommonScenarios\XsltcTestPlatform.cs(54,0): at System.Xml.Tests.XsltcTestPlatform.Var2(Object param0, Object param1)
   System.Xml.Tests.XsltcTestPlatform.Var2(param0: \"/platform:foo pft4.xsl\", param1: \"pft4.txt\") [FINISHED] Time: 1.3562016s
   System.Xml.Tests.XsltcTestPlatform.Var2(param0: \"/platform: pft12.xsl\", param1: \"pft12.txt\") [STARTING]
   System.Xml.Tests.XsltcTestPlatform.Var2(param0: \"/platform: pft12.xsl\", param1: \"pft12.txt\") [FAIL]

... more ...
```

Altjit shouldn't affect x86 runtime behavior.

**Comment by BruceForstall** [comment]
The problem is these tests invoke the .NET xslt compiler:
```
C:\program Files (x86)\Microsoft SDKs\Windows\v8.1A\bin\NETFX 4.5.1 Tools\xsltc.exe
```
Which loads this CLR:
```
C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
```
and that CLR sees the `COMPlus_AltJit=*` / `COMPlus_AltJitName=protononjit.dll` variables, but fails to find and load a protononjit.dll, so it fails fast.

We need a way to not run these tests for altjit, e.g., pass some `-notrait category=noaltjit` option.

**Comment by krwq** [comment]
You should be able to disable those with
```
msbuild /t:BuildAndTest /p:WithoutCategories="IgnoreForCI;XsltcExeRequired"
```

once the above PR is merged (name may change as part of the feedback)

**Comment by BruceForstall** [comment]
Fixed with https://github.com/dotnet/coreclr/pull/14873
