### ISSUE TITLE
Failed Debug.Assert prints the stacktrace twice to the console

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#14867]
Repro: Run the following as debug build:

```C#
using System.Diagnostics;

class Program
{
    static void Main(string[] args)
    {
        Debug.Assert(false);
    }
}
```

Result:

```
FailFast:

   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at Program.Main(String[] args) in C:\repro\Program.cs:line 7

   at System.Environment.FailFast(System.String, System.Exception)
   at Program.Main(System.String[])
```

Problems:

- Stacktrace is printed twice
- `System.Diagnostics.Debug.Assert` should not be included in the stacktrace
- Title should say `Assertion failed` instead of `FailFast`

**Comment by jkotas** [comment]
Also, make sure that contract failures like `Contract.Assume(false);` produce a good error message as well.

**Comment by ViktorHofer** [comment]
@jkotas currently the title "FailFast:" is hard-coded. I did this here: https://github.com/dotnet/coreclr/commit/0c4a490#diff-4c8371796156e86a3c2d34c8794f6582R1184. Should we always use the fail fast message instead of the hard-coded string?

I will tackle this and other issues and keep track of them in this issue: https://github.com/dotnet/coreclr/issues/15203

**Comment by jkotas** [comment]
I think we need an extra argument to be passed to the fail fast FCall that will differentiate the message:

When the program fails with FailFast, the error should have fail fast title.
When the program fails with Debug.Fail, the error should have assertion failed title.

**Comment by ViktorHofer** [comment]
Sounds good!

**Comment by lt72** [comment]
@sywhang: PTAL

**Comment by sywhang** [comment]
Hey @jkotas, what would be a good error message for ```Contract.Assume(false);```? Currently a program like this:
```
    class Program
    {
        static void Main(string[] args)
        {
            Contract.Assert(false);
        }
    }
```
produces this error message:
```
Assertion failed.
Description: Assertion failed.
Stack Trace:
   at debug3.Program.Main(String[] args) in E:\test\issue14867\debug3\Program.cs:line 9
```
Do you have any suggestions on how this error message should be changed?

**Comment by jkotas** [comment]
Yes, message like that would fine for `Contract.Assume`. I do not see message like that in the current master - the current master prints the following message because. We have started using the `Debug.Assert` path for contracts due to various CoreLib refactorings and cleanups, and so it suffers from the same problems as `Debug.Assert` now.

```
FailFast: Assumption failed.

   at System.Diagnostics.Debug.Assert(Boolean condition, String message, String detailMessage)
   at Program.Main(String[] args) in C:\repro\Test\Program.cs:line 7

   at System.Environment.FailFast(System.String, System.Exception)
   at Program.Main(System.String[])
```

**Comment by sywhang** [comment]
This should be fixed with #15895.

**Comment by danmosemsft** [comment]
Now dumps just
```

Assertion Failed


   at Program.Main(String[] args)

```

**Comment by danmosemsft** [comment]
@sywhang the output now has excess newlines as you see above. Are you planning to fix that? I see you put up https://github.com/dotnet/coreclr/pull/16265 but canceled it.

**Comment by sywhang** [comment]
@danmosemsft I noticed some issues with this, along with ```Contract.Assume()```. I'm currently working on a fix. Thanks for the heads up.

**Comment by danmosemsft** [comment]
Thanks @sywhang .

**Comment by danmosemsft** [comment]
@sywhang I guess you can close this now? That only leaves the important one, #15203.
