### ISSUE TITLE
DllImport on raspbian stretch failing

### ISSUE THREAD

**Issue by MaitreDede** [dotnet/coreclr#14923]
Hi,
I am trying to run an application on raspbian stretch (latest current version).
I have a simple program that tries to load `libbrcmEGL.so` :
```
    class Program
    {
        public const string LIB_EGL = "libbrcmEGL";

        [DllImport(LIB_EGL, EntryPoint = "eglGetDisplay", CallingConvention = CallingConvention.Cdecl)]
        public static extern IntPtr eglGetDisplay(int display);

        [DllImport(LIB_EGL, EntryPoint = "eglGetError", CallingConvention = CallingConvention.Cdecl)]
        public static extern int eglGetError();

        [DllImport(LIB_EGL, EntryPoint = "eglInitialize", CallingConvention = CallingConvention.Cdecl)]
        public static extern bool eglInitialize(IntPtr display, out int major, out int minor);

        [DllImport(LIB_EGL, EntryPoint = "eglTerminate", CallingConvention = CallingConvention.Cdecl)]
        public static extern bool eglTerminate(IntPtr display);

        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            IntPtr display = eglGetDisplay(0);

            Console.WriteLine("Display ptr {0}", display);
        }
    }
```

The library is `ln -s /opt/vc/lib/libbrcmEGL.so`

```
pi@raspberrypi:~/test $ ldd libbrcmEGL.so
        linux-vdso.so.1 (0x7e8b7000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f0a000)
        libbcm_host.so => /opt/vc/lib/libbcm_host.so (0x76ee1000)
        libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76e62000)
        libvchiq_arm.so => /opt/vc/lib/libvchiq_arm.so (0x76e4c000)
        libvcos.so => /opt/vc/lib/libvcos.so (0x76e32000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76e09000)
        libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0x76df6000)
        librt.so.1 => /lib/arm-linux-gnueabihf/librt.so.1 (0x76ddf000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76ca0000)
        /lib/ld-linux-armhf.so.3 (0x76f59000)
```

Result is :
```
pi@raspberrypi:~/test $ ./EglLoad
Hello World!

Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libbrcmEGL': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at EglLoad.Program.eglGetDisplay(Int32 display)
   at EglLoad.Program.Main(String[] args) in I:\RaspberryPi.Libs\EglLoad\Program.cs:line 26
Aborted
```

I have native apps that uses `libbrcmEGL` and works fine, but my app does not.

How can I diagnose the problem ?

Thanks.

**Comment by jkotas** [comment]
You can use `ldd -r` to find out why the .dll is not loading.

More context https://github.com/dotnet/coreclr/issues/10520#issuecomment-290684429

We should add more actionable error message here. This is frequently hit problem / frequently asked question.

cc @russellhadley

**Comment by MaitreDede** [comment]
Hi,
I have found why it does not load : the lib tries to map a symbol that does not exists.
The anwser that gave me the solution is [here](https://stackoverflow.com/a/14623998/1199210).

I have made a simple C program to help me find the right libraries I need, and I found that I have to load `libbrcmGLESv2`before `libbrcmEGL`, so I don't get the error.

**Comment by jkotas** [comment]
Let's use #10520 to track improving the error message here.
