### ISSUE TITLE
[x64] System.NullReferenceException in _opt_relrotarg_valref

### ISSUE THREAD

**Issue by CarolEidt** [dotnet/coreclr#15027]
This test:
JIT\Methodical\explicit\rotate\_opt_relrotarg_valref\_opt_relrotarg_valref.cmd
fails with this error:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Rotate.App.Node.growTree(Int32 maxHeight, String indent)
   at Rotate.App.Node.growTree(Int32 maxHeight, String indent)
   at Rotate.App.Node.growTree(Int32 maxHeight, String indent)
   at Rotate.App.Node.growTree(Int32 maxHeight, String indent)
   at Rotate.App.Main()
```
on both x64/ux and x64/windows with either `COMPlus_JitStress=1` or `COMPlus_JitStress=2`

**Comment by sandreenko** [comment]
It is a duplicate of #14455.

**Comment by CarolEidt** [comment]
> It is a duplicate of #14455.

Oops - should have seen that - especially since I opened that one. Thanks!
