### ISSUE TITLE
[ARM64/Win] CoreCLR raises System.InvalidOperationException with asp.net benchmark

### ISSUE THREAD

**Issue by pgodeq** [dotnet/coreclr#15224]
While I was executing asp.net bechmark plaintext on Windows-ARM64 with the latest coreclr, an exception is raised.  Following is the failure log. 

```
c:\DATA\aspnet_benchmark\publish_24nov_rel_newasp>CoreRun.exe Benchmarks.dll --scenarios="Plaintext" --threadCount=12

ASP.NET Core Benchmarks
-----------------------
Current directory: c:\DATA\aspnet_benchmark\publish_24nov_rel_newasp
WebHostBuilder loading from: c:\DATA\aspnet_benchmark\publish_24nov_rel_newasp\microsoft.aspnetcore.hosting.dll
Scenario configuration found in scenarios.json and/or command line args

The following scenarios were enabled:
  Plaintext -> /plaintext

Database: None
Using server Kestrel
Server GC is currently DISABLED
Press 'C' to force GC or any other key to display GC stats

Hosting environment: Production
Content root path: c:\DATA\aspnet_benchmark\publish_24nov_rel_newasp
Now listening on: http://10.131.5.101:5000
Application started. Press Ctrl+C to shut down.

Unhandled Exception: System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.<ProcessRequestsAsync>d__47`1.MoveNext()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) in c:\DATA\ci\2017-23-11\coreclr\src\mscorlib\shared\System\Threading\ExecutionContext.cs:line 151
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in c:\DATA\ci\2017-23-11\coreclr\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs:line 556
   at System.Threading.ThreadPoolWorkQueue.Dispatch() in c:\DATA\ci\2017-23-11\coreclr\src\mscorlib\src\System\Threading\ThreadPool.cs:line 586


```
Load generator 'wrk' (set up on a different machine) is used to generate workload, with below arguments: 
`./wrk -c 16  -t 16 -d 60 http://10.131.5.101:5000/plaintext -s ./scripts/pipeline.lua -- 16`

I created a setup to host this asp.net benchmark on Windows-ARM64 by 
1. copying all Core_Root (coreclr\bin\tests\Windows_NT.arm64.Release\Tests\Core_Root) contents 
2. copying System.Memory from CoreFx build (bin\Windows_NT.AnyCPU.Release\System.Memory\netcoreapp), along with asp.net benchmark compiled Benchmarks.dll ( [](https://github.com/aspnet/benchmarks))
3. copying asp.net benchmark dll from (benchmarks\src\Benchmarks\bin\Release\netcoreapp2.0\publish)
4. setting gcServer
`set COMPlus_gcServer=1 `

5. Executing below command
`c:\DATA\aspnet_benchmark\publish_24nov_rel_newasp>CoreRun.exe Benchmarks.dll --scenarios="Plaintext" --threadCount=6`

I do not observe this exception when I do the same run on Windows-x64, Linux-x64 or Linux-ARM64.
Is there any setting I have missed or is it a genuine failure ? 

I tried debugging with Windbg.exe for ARM64 and I could collect following information when exception occurs:
```
0:043> sxe clr
0:043> sxd av
0:043> .loadby sos coreclr
0:043> !pe
*** WARNING: Unable to verify checksum for C:\DATA\aspnet_benchmark\publish_24nov_rel_newasp\CoreCLR.dll
Exception object: 0000025ac7d52508
Exception type:   System.InvalidOperationException
Message:          An attempt was made to transition a task to a final state when it had already completed.
InnerException:   <none>
StackTrace (generated):
    SP               IP               Function
    00000083E3ABF1A0 00007FFB35CDE298 System_Private_CoreLib!System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource)+0x38
    00000083E3ABF250 00007FFAD706AE84 microsoft_aspnetcore_server_kestrel_core!Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+<ProcessRequestsAsync>d__47`1[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]].MoveNext()+0x7ec
    00000083E3ABF2A0 00007FFB35D37438 System_Private_CoreLib!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x128
    00000083E3ABF2C0 00007FFAD707F534 System_Private_CoreLib!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+<ProcessRequestsAsync>d__47`1[[Microsoft.AspNetCo+0x54
    00000083E3ABF330 00007FFB35E4072C System_Private_CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()+0x19c

StackTraceString: <none>
HResult: 80131509
There are nested exceptions on this thread. Run with -nested for details

0:043> !dso
OS Thread Id: 0x884 (43)
SP/REG           Object           Name
x13              0000025ac7c1b448 System.Threading.ExecutionContext
x14              0000025ac7ce7ac8 System.Threading.ContextCallback
x16              0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABD438 0000025ac7ce7ac8 System.Threading.ContextCallback
00000083E3ABD448 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABD4C8 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABD4D0 0000025ac7ce7ac8 System.Threading.ContextCallback
00000083E3ABD4E0 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABD5A0 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABD5C8 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABD5D0 0000025ac7ce7ac8 System.Threading.ContextCallback
00000083E3ABD898 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABD988 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABD998 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABDAC0 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABDAC8 0000025ac7ce7ac8 System.Threading.ContextCallback
00000083E3ABDAD8 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABDD18 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABDD28 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABDDB0 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABDDB8 0000025ac7ce7ac8 System.Threading.ContextCallback
00000083E3ABDDC8 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABDF68 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABDF78 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABE388 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABE5B8 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABE5C8 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABE8A0 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABE8A8 0000025ac7ce7ac8 System.Threading.ContextCallback
00000083E3ABE8B8 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABEE78 0000025ac7cea498 System.Char[]
00000083E3ABEEE8 0000025ac7cea298 System.Collections.Generic.Dictionary`2[[System.String, System.Private.CoreLib],[System.Resources.ResourceLocator, System.Private.CoreLib]]
00000083E3ABEF58 0000025ac7cea2e8 System.Resources.ResourceReader
00000083E3ABEF78 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABF000 0000025ac7c04110 System.Globalization.CultureInfo
00000083E3ABF0A0 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABF1B0 0000025ac816f820 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.LibuvOutputConsumer+<WriteOutputAsync>d__6, Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv]]
00000083E3ABF200 0000025ac7c28960 System.Threading.Tasks.Task
00000083E3ABF230 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABF238 0000025ac7ce7ac8 System.Threading.ContextCallback
00000083E3ABF248 0000025ac7cea638 System.Threading.ThreadPoolWorkQueueThreadLocals
00000083E3ABF268 0000025ac7cea7b0 System.Threading.Thread
00000083E3ABF288 0000025ac7d44d50 System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+<ProcessRequestsAsync>d__47`1[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel.Core]]
00000083E3ABF290 0000025ac7c1b448 System.Threading.ExecutionContext
00000083E3ABF2D8 0000025ac7ceebd8 System.Threading.Tasks.CompletionActionInvoker
00000083E3ABF2E0 0000025ac7c28ee0 System.Threading.ThreadPoolWorkQueue


!dumpheap -type Exception

Statistics:
              MT    Count    TotalSize Class Name
00007ffb361ccc30        1           24 System.Text.EncoderExceptionFallback
00007ffb361cc900        1           24 System.Text.DecoderExceptionFallback
00007ffad70a69f0        1           64 System.Action`5[[Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions],[System.String, System.Private.CoreLib],[System.String, System.Private.CoreLib],[System.Double, System.Private.CoreLib],[System.Exception, System.Private.CoreLib]]
00007ffad70a6780        1           64 System.Action`4[[Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions],[System.TimeSpan, System.Private.CoreLib],[System.DateTimeOffset, System.Private.CoreLib],[System.Exception, System.Private.CoreLib]]
00007ffad70a65b8        1           64 System.Action`4[[Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions],[System.String, System.Private.CoreLib],[System.Int64, System.Private.CoreLib],[System.Exception, System.Private.CoreLib]]
00007ffad7048040        1           64 System.Action`4[[Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvConnectRequest, Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv],[System.Int32, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException, Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv],[System.Object, System.Private.CoreLib]]
00007ffad6c9da78        1           64 System.Func`3[[System.Object, System.Private.CoreLib],[System.Exception, System.Private.CoreLib],[System.String, System.Private.CoreLib]]
00007ffad70a6c58        2          128 System.Action`4[[Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions],[System.String, System.Private.CoreLib],[System.Int32, System.Private.CoreLib],[System.Exception, System.Private.CoreLib]]
00007ffad70a6388        2          128 System.Action`2[[Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions],[System.Exception, System.Private.CoreLib]]
00007ffad70495a8        2          128 System.Action`4[[Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvWriteReq, Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv],[System.Int32, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException, Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv],[System.Object, System.Private.CoreLib]]
00007ffad7044210        2          128 System.Action`4[[Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvStreamHandle, Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv],[System.Int32, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv.Internal.Networking.UvException, Microsoft.AspNetCore.Server.Kestrel.Transport.Libuv],[System.Object, System.Private.CoreLib]]
00007ffb361c39a0        1          144 System.StackOverflowException
00007ffb361c2e38        1          144 System.ExecutionEngineException
00007ffb361ade28        1          144 System.OutOfMemoryException
00007ffb361adae8        1          144 System.InvalidOperationException
00007ffb361c7d10        2          288 System.Threading.ThreadAbortException
00007ffb361ad7a8        2          288 System.Exception
00007ffad70a6240        5          320 System.Action`4[[Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions],[System.String, System.Private.CoreLib],[System.String, System.Private.CoreLib],[System.Exception, System.Private.CoreLib]]
00007ffad70a5cf0       17         1088 System.Action`3[[Microsoft.Extensions.Logging.ILogger, Microsoft.Extensions.Logging.Abstractions],[System.String, System.Private.CoreLib],[System.Exception, System.Private.CoreLib]]
00007ffb35786ab8       77         2464 System.Collections.ObjectModel.ReadOnlyCollection`1[[System.Exception, System.Private.CoreLib]]
00007ffb3618eb50       78         2488 System.Exception[]
00007ffb3619ee68       99         3168 System.Runtime.ExceptionServices.ExceptionDispatchInfo[]
00007ffb35778b98       99         3960 System.Collections.Generic.List`1[[System.Runtime.ExceptionServices.ExceptionDispatchInfo, System.Private.CoreLib]]
00007ffb361b6f30       99         4752 System.Threading.Tasks.TaskExceptionHolder
00007ffb361b99c0       99         6336 System.Runtime.ExceptionServices.ExceptionDispatchInfo
00007ffad6c9dbb8      116         7424 System.Action`2[[System.Exception, System.Private.CoreLib],[System.Object, System.Private.CoreLib]]
00007ffb361addb8       77        11704 System.AggregateException
00007ffb361b4048       79        13272 System.TypeLoadException
00007ffad70a2248      102        15504 Microsoft.AspNetCore.Protocols.ConnectionAbortedException
Total 970 objects


0:043> !clrstack
OS Thread Id: 0x884 (43)
        Child SP               IP Call Site
00000083e3abd498 00007ffb50bc76a0 [HelperMethodFrame: 00000083e3abd498] 
00000083e3abd5b0 00007ffb35d3743c SOS Error: Unable to CoCreateInstance class=CLSID_CorSymBinder_SxS, interface=IID_ISymUnmanagedBinder3, hr=0x80040154
This usually means the installation of .Net Framework on your machine is missing or needs repair
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [c:\DATA\clr\ci\2017-23-11\coreclr\src\mscorlib\shared\System\Threading\ExecutionContext.cs @ 133]
00000083e3abf058 00007ffb363a18a8 [HelperMethodFrame: 00000083e3abf058] 
00000083e3abf180 00007ffb35cde29c SOS Error: Unable to CoCreateInstance class=CLSID_CorSymBinder_SxS, interface=IID_ISymUnmanagedBinder3, hr=0x80040154
This usually means the installation of .Net Framework on your machine is missing or needs repair
System.ThrowHelper.ThrowInvalidOperationException(System.ExceptionResource) [c:\DATA\clr\ci\2017-23-11\coreclr\src\mscorlib\src\System\ThrowHelper.cs @ 175]
00000083e3abf1a0 00007ffad706ae88 SOS Error: Unable to CoCreateInstance class=CLSID_CorSymBinder_SxS, interface=IID_ISymUnmanagedBinder3, hr=0x80040154
This usually means the installation of .Net Framework on your machine is missing or needs repair
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+d__47`1[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]].MoveNext()
00000083e3abf250 00007ffb35d3738c SOS Error: Unable to CoCreateInstance class=CLSID_CorSymBinder_SxS, interface=IID_ISymUnmanagedBinder3, hr=0x80040154
This usually means the installation of .Net Framework on your machine is missing or needs repair
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) [c:\DATA\clr\ci\2017-23-11\coreclr\src\mscorlib\shared\System\Threading\ExecutionContext.cs @ 153]
00000083e3abf2a0 00007ffad707f538 SOS Error: Unable to CoCreateInstance class=CLSID_CorSymBinder_SxS, interface=IID_ISymUnmanagedBinder3, hr=0x80040154
This usually means the installation of .Net Framework on your machine is missing or needs repair
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib],[Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection+d__47`1[[Microsoft.AspNetCore.Hosting.Internal.HostingApplication+Context, Microsoft.AspNetCore.Hosting]], Microsoft.AspNetCore.Server.Kestrel.Core]].MoveNext() [c:\DATA\clr\ci\2017-23-11\coreclr\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 566]
00000083e3abf2c0 00007ffb35e40730 SOS Error: Unable to CoCreateInstance class=CLSID_CorSymBinder_SxS, interface=IID_ISymUnmanagedBinder3, hr=0x80040154
This usually means the installation of .Net Framework on your machine is missing or needs repair
System.Threading.ThreadPoolWorkQueue.Dispatch() [c:\DATA\clr\ci\2017-23-11\coreclr\src\mscorlib\src\System\Threading\ThreadPool.cs @ 588]
00000083e3abf7d0 00007ffb363a2100 [DebuggerU2MCatchHandlerFrame: 00000083e3abf7d0] 


0:043> !threads
ThreadCount:      43
UnstartedThread:  0
BackgroundThread: 42
PendingThread:    0
DeadThread:       0
Hosted Runtime:   no
                                                                                                        Lock  
       ID OSID ThreadOBJ           State GC Mode     GC Alloc Context                  Domain           Count Apt Exception
   0    1  7b0 0000025ac623d660  202a020 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA 
  12    2 16cc 0000025ac6243f00    2b220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Finalizer) 
  16    3  6ac 0000025ae144f150  1029220 Preemptive  0000025AC80DE8F8:0000025AC80DEA30 0000025ac6223540 0     MTA (Threadpool Worker) 
  18    4 12ac 0000025ae1453710  1029220 Preemptive  0000025AC7F3BC38:0000025AC7F3BCB0 0000025ac6223540 0     MTA (Threadpool Worker) 
  19    5 1aac 0000025ae1455d90  8029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Completion Port) 
  21    7  d24 0000025ae1460180    2b220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 1     MTA 
  22    8 1b94 0000025ae146f8a0  102a220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  23    9  d20 0000025ae14b3630    2b220 Preemptive  0000025AC839C500:0000025AC839E230 0000025ac6223540 0     MTA 
  24   10 1ac0 0000025ae14b42c0    2b220 Preemptive  0000025AC837F090:0000025AC8380130 0000025ac6223540 0     MTA 
  25   11  d1c 0000025ae14b4f50    2b220 Preemptive  0000025AC838DB90:0000025AC838E1B0 0000025ac6223540 0     MTA 
  26   12 11d8 0000025ae14b59b0    2b220 Preemptive  0000025AC839B190:0000025AC839C230 0000025ac6223540 0     MTA 
  27   13 1574 0000025ae14b6050    2b220 Preemptive  0000025AC83AB2A0:0000025AC83AC2B0 0000025ac6223540 0     MTA 
  28   14  4d4 0000025ae14b66f0    2b220 Preemptive  0000025AC83629B8:0000025AC8364030 0000025ac6223540 0     MTA 
  29   15  d08 0000025ae14e62a0  1029220 Preemptive  0000025AC81C9908:0000025AC81CB230 0000025ac6223540 0     MTA (Threadpool Worker) 
  30   16  ca0 0000025ae14e6940  1029220 Preemptive  0000025AC82DC000:0000025AC82DDBB0 0000025ac6223540 0     MTA (Threadpool Worker) System.TypeLoadException 0000025ac82dbda8
  31   17  6ec 0000025ae14fe200  1029220 Preemptive  0000025AC7FC3F28:0000025AC7FC40B0 0000025ac6223540 0     MTA (Threadpool Worker) 
  32   18 1588 0000025ae14ff640  1029220 Preemptive  0000025AC83551F0:0000025AC8355FB0 0000025ac6223540 0     MTA (Threadpool Worker) 
  33   19  4d0 0000025ae14fc040  1029220 Preemptive  0000025AC8294118:0000025AC8295930 0000025ac6223540 0     MTA (Threadpool Worker) 
  36   20 1a38 0000025ae14fef80  1029220 Preemptive  0000025AC7F4DB58:0000025AC7F4DD30 0000025ac6223540 0     MTA (Threadpool Worker) 
  34   21  990 0000025ae14fe8c0  1029220 Preemptive  0000025AC7F6F5D8:0000025AC7F6FE30 0000025ac6223540 0     MTA (Threadpool Worker) 
  49   22 1668 0000025ae14fdb40  1029220 Preemptive  0000025AC81BA4D8:0000025AC81BB1B0 0000025ac6223540 0     MTA (Threadpool Worker) 
  47   23  c48 0000025ae14fc700  1029220 Preemptive  0000025AC82FE0E8:0000025AC82FFCB0 0000025ac6223540 0     MTA (Threadpool Worker) 
  45   24 1164 0000025ae14fcdc0  1029220 Preemptive  0000025AC7F333A8:0000025AC7F33CB0 0000025ac6223540 0     MTA (Threadpool Worker) 
  46   25  9c8 0000025ae14fd480  1029220 Preemptive  0000025AC7FD4088:0000025AC7FD4130 0000025ac6223540 0     MTA (Threadpool Worker) 
  41   26  458 0000025ae232e050  1029220 Preemptive  0000025AC8006288:0000025AC80062B0 0000025ac6223540 0     MTA (Threadpool Worker) 
  43   27  884 0000025ae232f490  1029220 Preemptive  0000025AC83ADFA0:0000025AC83AE2B0 0000025ac6223540 0     MTA (Threadpool Worker) System.InvalidOperationException 0000025ac7d52508 (nested exceptions)
  38   28  540 0000025ae232fb50  1029220 Preemptive  0000025AC824C488:0000025AC824D6B0 0000025ac6223540 0     MTA (Threadpool Worker) 
  40   29 1ad0 0000025ae2331d10  1029220 Preemptive  0000025AC7F5F448:0000025AC7F5FDB0 0000025ac6223540 0     MTA (Threadpool Worker) 
  39   30 11b8 0000025ae2330210  1029220 Preemptive  0000025AC7F39AE8:0000025AC7F39CB0 0000025ac6223540 0     MTA (Threadpool Worker) 
  37   31 1b70 0000025ae23308d0  1029220 Preemptive  0000025AC803EF18:0000025AC80404B0 0000025ac6223540 0     MTA (Threadpool Worker) 
  35   32  224 0000025ae232edd0  1029220 Preemptive  0000025AC7F934A8:0000025AC7F93F30 0000025ac6223540 0     MTA (Threadpool Worker) 
  42   33  b10 0000025ae2330f90  1029220 Preemptive  0000025AC810B7A8:0000025AC810CBB0 0000025ac6223540 0     MTA (Threadpool Worker) 
  44   34  764 0000025ae2331650  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  48   35  744 0000025ae232e710  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  50   36 154c 0000025ae23323d0  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  51   37  7a0 0000025ae2334c50  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  52   38  264 0000025ae2332a90  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  53   39  250 0000025ae2333150  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  54   40  254 0000025ae2335310  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  55   41  260 0000025ae2333810  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  65   46  4b4 0000025ae234bb50  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  60   47  54c 0000025ae234cf90  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
  64   49 1614 0000025ae234c8d0  1029220 Preemptive  0000000000000000:0000000000000000 0000025ac6223540 0     MTA (Threadpool Worker) 
```

**Comment by pgodeq** [comment]
I created a debug build, to capture LOG statements by setting following variables (suggested on other issue comment): 
set COMPLUS_LogEnable=1
set COMPLUS_LOGLEVEL=6
set COMPLUS_LogToFile=1
set COMPLUS_LogFile=clr_log.txt

This generates log for all threads activity, which seems to be too much information to analyze. 
I tried bifurcating the log for each thread, which still doesn't help much. 

@dotnet/arm64-contrib @jkotas Please suggest.

**Comment by jkotas** [comment]
Since the same code works everywhere else, you are probably looking at ARM64-specific low-level race condition (e.g. there can be memory barrier missing somewhere), or memory corruption (e.g. GC hole).

You need to analyze the crash dump to make progress on it.

If you share the crash dump (w/ symbols), others can help you with it.

Also, how long does it take to hit the crash? How deterministic is the crash?

**Comment by pgodeq** [comment]
I have collected the crash dump and I will share it across.
The crash is deterministic and happens when wrk is executed with 16 threads and 16 connections.
We execute 'wrk' for total 60 seconds, and the crash is observed after 6 seconds or so.

**Comment by BruceForstall** [comment]
This bug is old and has not been investigated. I'm going to close it, and assume if the problem still occurs, the bug will come back.
