### ISSUE TITLE
CentOS 7.1 x64 SpanBench test failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15251]
This test has been failing in every PR in dotnet/coreclr for a while:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_centos7.1_tst_prtest/

```
07:37:55 FAILED   - JIT/Performance/CodeQuality/Span/SpanBench/SpanBench.sh
07:37:55                BEGIN EXECUTION
07:37:55                /mnt/resource/j/workspace/dotnet_coreclr/master/checked_centos7.1_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun SpanBench.exe
07:37:55                TestSpanClear<Byte>(100): 0.585ms
07:37:55                TestSpanClear<String>(100): 0.0081ms
07:37:55                TestArrayClear<Byte>(100): 0.0092ms
07:37:55                TestArrayClear<String>(100): 0.0097ms
07:37:55                
07:37:55                Unhandled Exception: System.TypeLoadException: Could not load type 'System.MemoryExtensions' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
07:37:55                   at Span.SpanBench.TestSpanAsBytes[T](T[] array, Int32 iterationCount, Boolean untrue)
07:37:55                   at Span.SpanBench.Invoke(Action`1 innerLoop, String nameFormat, Object[] nameArgs)
07:37:55                   at Span.SpanBench.Main(String[] args)
07:37:55                ./SpanBench.sh: line 243: 12297 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
07:37:55                Expected: 100
07:37:55                Actual: 134
07:37:55                END EXECUTION - FAILED
```

**Comment by BruceForstall** [comment]
@AndyAyersMS @stephentoub @jkotas ideas?

**Comment by AndyAyersMS** [comment]
See #15096.

**Comment by BruceForstall** [comment]
Closing, since #15096 covers it.
