### ISSUE TITLE
[RyuJIT/arm32] Make altjit corefx runs clean

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#15304]
The x86_arm_altjit corefx runs have errors that are not asserts. Fix any issues that prevent these runs from being clean.

For example, we already needed to disable XSLT tests when running the altjit: https://github.com/dotnet/coreclr/pull/14873.

**Comment by BruceForstall** [comment]
Current set of corefx jobs with failures:
```
Windows_NT x86_arm_altjit Checked corefx_jitstress1
Windows_NT x86_arm_altjit Checked corefx_jitstress2
Windows_NT x86_arm_altjit Checked corefx_jitstressregs0x80
Windows_NT x86_arm_altjit Checked corefx_minopts
```

**Comment by BruceForstall** [comment]
Example failures:
```
  Using D:\j\workspace\x86_arm_altji---7030128c\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x86\ as the test runtime folder.
  Executing in D:\j\workspace\x86_arm_altji---7030128c\_\fx\bin\tests\System.Data.SqlClient.Tests\netcoreapp-Windows_NT-Release-x86\ 
  Running tests... Start time: 13:20:07.99
  xUnit.net console test runner (32-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
     System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: null, lineNumber: -1, columnNumber: 0) [FAIL]
  Discovered:  System.Collections.Specialized.Tests
        Assert.Equal() Failure
  Discovering: System.Data.SqlClient.Tests
        Expected: 0
        Actual:   8
        Stack Trace:
           D:\j\workspace\x86_arm_altji---7030128c\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(168,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           D:\j\workspace\x86_arm_altji---7030128c\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(109,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
     System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"\", lineNumber: 0, columnNumber: -1) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   8
        Stack Trace:
           D:\j\workspace\x86_arm_altji---7030128c\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(168,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           D:\j\workspace\x86_arm_altji---7030128c\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(109,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
     System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"FileName\", lineNumber: 1, columnNumber: 2) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   8
        Stack Trace:
           D:\j\workspace\x86_arm_altji---7030128c\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(168,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           D:\j\workspace\x86_arm_altji---7030128c\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(109,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
  Finished:    System.Diagnostics.StackTrace.Tests
```

```
Using D:\j\workspace\x86_arm_altji---7030128c\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x86\ as the test runtime folder.
  Executing in D:\j\workspace\x86_arm_altji---7030128c\_\fx\bin\tests\System.Runtime.Numerics.Tests\netcoreapp-Windows_NT-Release-x86\ 
  Running tests... Start time: 14:57:08.13
  xUnit.net console test runner (32-bit .NET Core)
  Copyright (C) 2014 Outercurve Foundation.
  
  Discovering: System.Runtime.Numerics.Tests
  Discovered:  System.Runtime.Numerics.Tests
  Starting:    System.Runtime.Numerics.Tests
  
  Assert failure(PID 8108 [0x00001fac], Thread: 8416 [0x20e0]): !hasPartialArgInfo || isZero(argHigh) || (argHigh == CONSTRUCT_ptrArgTP(1, (argCnt-1)))
  
  CORECLR! scanArgRegTableI + 0x5F3 (0x720a79a3)
  CORECLR! EECodeManager::EnumGcRefs + 0x322 (0x720a1342)
  CORECLR! GcStackCrawlCallBack + 0x170 (0x722748a0)
  CORECLR! Thread::MakeStackwalkerCallback + 0x45 (0x71efaad4)
  CORECLR! Thread::StackWalkFramesEx + 0x177 (0x71efc16b)
  CORECLR! Thread::StackWalkFrames + 0x15E (0x71efbf71)
  CORECLR! ScanStackRoots + 0x18C (0x72372dda)
  CORECLR! GCToEEInterface::GcScanRoots + 0x10F (0x7237249f)
  CORECLR! WKS::gc_heap::mark_phase + 0x1B1 (0x7233da3e)
  CORECLR! WKS::gc_heap::gc1 + 0x155 (0x72338442)
      File: d:\j\workspace\x86_arm_altji---7030128c\src\vm\eetwain.cpp Line: 2639
      Image: D:\j\workspace\x86_arm_altji---7030128c\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-x86\dotnet.exe
  
  Finished running tests.  End time=14:57:43.77, Exit code = 123456789
```
