### ISSUE TITLE
[Local GC] CoreFX test failure: System.Tests.GCTests.LatencyRoundtrips_LowLatency

### ISSUE THREAD

**Issue by swgillespie** [dotnet/coreclr#15589]
This is the one (!) CoreFX test failure that arises when using a standalone GC:

```
     System.Tests.GCTests.LatencyRoundtrips_LowLatency(value: LowLatency) [FAIL]
        Assert.Equal() Failure
        Expected: LowLatency
        Actual:   Interactive
        Stack Trace:
           E:\GitHub\corefx\src\System.Runtime\tests\System\GCTests.cs(407,0): at System.Tests.GCTests.LatencyRoundtrips(GCLatencyMode value)
           E:\GitHub\corefx\src\System.Runtime\tests\System\GCTests.cs(420,0): at System.Tests.GCTests.LatencyRoundtrips_LowLatency(GCLatencyMode value)
```

Will need to be fixed before shipping. cc @Maoni0 @sergiy-k

**Comment by Maoni0** [comment]
@davmason would you please check if this is still failing?

**Comment by davmason** [comment]
This test is no longer failing, but two new ones are. I haven't had time to investigate yet, I will do that after the two other issues

System.IO.Tests.FileStream_Dispose.FinalizeFlushesWriteBuffer
```
<test name="System.Drawing.Tests.BitmapTests.MakeTransparent_GrayscalePixelFormat_ThrowsArgumentException" type="System.Drawing.Tests.BitmapTests" method="MakeTransparent_GrayscalePixelFormat_ThrowsArgumentException" time="0.0208556" result="Fail">
  <traits>
    <trait name="category" value="nonnetfxtests" />
    <trait name="activeissue" value="21886" />
  </traits>
  <failure exception-type="Xunit.Sdk.ThrowsException">
    <message><![CDATA[Assert.Throws() Failure\r\nExpected: typeof(System.Runtime.InteropServices.ExternalException)\r\nActual:   (No exception was thrown)]]></message>
    <stack-trace><![CDATA[   at System.Drawing.Tests.BitmapTests.MakeTransparent_GrayscalePixelFormat_ThrowsArgumentException() in D:\corefx_main\src\System.Drawing.Common\tests\BitmapTests.cs:line 964]]></stack-trace>
  </failure>
</test>
```

System.Dynamic.Tests.InvokeMemberBindingTests.OperationOnTwoObjectsDifferentTypesOfSameName
```
<test name="System.Dynamic.Tests.InvokeMemberBindingTests.OperationOnTwoObjectsDifferentTypesOfSameName" type="System.Dynamic.Tests.InvokeMemberBindingTests" method="OperationOnTwoObjectsDifferentTypesOfSameName" time="0" result="Fail">
  <failure exception-type="System.ArgumentNullException">
    <message><![CDATA[System.ArgumentNullException : Value cannot be null.\r\nParameter name: type]]></message>
    <stack-trace><![CDATA[   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type) in D:\coreclr\src\mscorlib\shared\System\Reflection\IntrospectionExtensions.cs:line 14
at NewReflectionExtensions.IsAssignableFrom(Type type, Type otherType) in C:\BuildAgent\work\cb37e9acf085d108\src\common\NewReflectionExtensions.cs:line 109]]></stack-trace>
  </failure>
</test>
```

**Comment by davmason** [comment]
This issue is no longer reproing. I found a finalizer issue running the tests that I'll open a new issue for
