### ISSUE TITLE
[Arm64/Linux] New regression on tip

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#15931]
Several tests are failing with
```
FailFast: Infinite recursion during resource lookup within System.Private.CoreLib.  
This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points
such as assembly resolve events or CultureInfo names.  
Resource name: Arg_NullReferenceException
```
List of affected tests
```
CoreMangLib/cti/system/double/DoubleToString2/DoubleToString2.sh
Interop/MarshalAPI/String/StringMarshalingTest/StringMarshalingTest.sh
JIT/Regression/CLR-x86-JIT/V1-M09/b15307/b15307/b15307.sh
JIT/Regression/CLR-x86-JIT/V1-M10/b04914/b04914/b04914.sh
Regressions/common/ThreadCulture/ThreadCulture.sh
Regressions/coreclr/0202/ThreadCulture/ThreadCulture.sh
Regressions/coreclr/0570/Test570/Test570.sh
Regressions/coreclr/0576/Test0576/Test0576.sh
Regressions/coreclr/1402/Test1402/Test1402.sh
```
`git bisect bad f1c732878`
`git bisect good 84efbc8`

**Comment by sdmaclea** [comment]
@dotnet/arm64-contrib @jkotas FYI

**Comment by jkotas** [comment]
Do you happen to have callstack that leads to this? Thanks!

**Comment by sdmaclea** [comment]
Here is the callstack for CoreMangLib.cti.system.double.DoubleToString2.DoubleToString2
```
   at System.Environment.FailFast(System.String)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.NullReferenceException..ctor()
   at System.String.IndexOf(System.String, Int32, Int32, System.StringComparison)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureInfoHelper(Int32, System.String, System.String)
   at System.Globalization.CultureInfo.GetCultureInfo(System.String)
   at System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(System.Reflection.Assembly, System.Resources.UltimateResourceFallbackLocation ByRef)
   at System.Resources.ResourceManager.CommonAssemblyInit()
   at System.Resources.ResourceManager..ctor(System.Type)
   at System.SR.InternalGetResourceString(System.String)
   at System.SR.GetResourceString(System.String, System.String)
   at System.NullReferenceException..ctor()
   at System.String.IndexOf(System.String, Int32, Int32, System.StringComparison)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
   at System.Globalization.CultureInfo.GetCultureByName(System.String, Boolean)
   at System.Globalization.CultureInfo.GetUserDefaultCulture()
   at System.Globalization.CultureInfo.Init()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at System.Globalization.CompareInfo..cctor()
   at System.String.IndexOf(System.String, Int32, Int32, System.StringComparison)
   at System.Globalization.CultureData.InitCultureData()
   at System.Globalization.CultureData.CreateCultureData(System.String, Boolean)
   at System.Globalization.CultureData.GetCultureData(System.String, Boolean)
   at System.Globalization.CultureInfo.InitializeFromName(System.String, Boolean)
   at DoubleToString1.InitializeIFormatProvider()
   at DoubleToString1.Main()
```

**Comment by sdmaclea** [comment]
I doubt this is Arm64 specific.  I just found it on Arm64 linux

**Comment by jkotas** [comment]
cc @ViktorHofer Make sure that you do not regress this with the other work you are doing.

**Comment by ViktorHofer** [comment]
👍

**Comment by jkotas** [comment]
Regression introduced by #15902
