### ISSUE TITLE
ARM corefx test failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#16001]
A baseline (no stress mode) run of the corefx tests on Windows ARM32 shows failures in the following tests:

```
System.Data.SqlClient.Tests  Total: 110, Errors: 0, Failed: 19, Skipped: 2, Time: 7.337s
System.Diagnostics.Process.Tests  Total: 206, Errors: 0, Failed: 1, Skipped: 1, Time: 75.217s
System.Drawing.Common.Tests  Total: 4496, Errors: 0, Failed: 15, Skipped: 0, Time: 43.753s
System.IO.FileSystem.Tests  Total: 5066, Errors: 0, Failed: 7, Skipped: 26, Time: 1281.986s
System.IO.Ports.Tests  Total: 939, Errors: 0, Failed: 1, Skipped: 816, Time: 7.774s
System.Management.Tests  Total: 25, Errors: 0, Failed: 19, Skipped: 4, Time: 5.054s
```

This is when building corefx like this:
```
build.cmd -Release -os:Windows_NT -buildArch:arm -- /p:CoreCLROverridePath=E:\gh\coreclr2\bin\Product\Windows_NT.arm.Checked
build-tests.cmd -SkipTests -Release -os:Windows_NT -buildArch:arm -- /p:WithoutCategories=\"IgnoreForCI;XsltcExeRequired\"
```

There are no asserts.

The System.Data.SqlClient.Tests failures appears to be (at least partially) due to:
```
Unable to load DLL 'sni.dll'
```

The System.Diagnostics.Process.Tests failure appears due to:
```
System.InvalidOperationException : Couldn't connect to remote machine.
```

The System.Drawing.Common.Tests failures appear due to slight floating-point accuracy difference, e.g.:
```
System.Drawing.Drawing2D.Tests.GraphicsPathTests.AddClosedCurve_Points_Success [FAIL]
   Assert.Equal() Failure
   Expected: {X=0.8333333,Y=0.8333333,Width=2.333333,Height=2.333333}
   Actual:   {X=0.8333334,Y=0.8333334,Width=2.333333,Height=2.333333}
```

The System.IO.FileSystem.Tests failures are due to:
```
Assert.Throws() Failure
Expected: typeof(System.UnauthorizedAccessException)
Actual:   typeof(System.IO.IOException): The process cannot access the file 'Z:\gh\corefx\bin\tests\System.IO.FileSystem.Tests\netcoreapp-Windows_NT-Release-arm' because it is being used by another process.
```
perhaps due to the way the tests were being run, across a network?

The System.IO.Ports.Tests failures are due to:
```
Installed ports : COM2,COM8
Exception opening port COM2: System.IO.IOException: A device attached to the system is not functioning
...
Exception opening port COM8: System.IO.IOException: Incorrect function
...
System.IO.Ports.Tests.GetPortNames.AllHelperPortsAreInGetPortNames [FAIL]
   COM2 is not present in SerialPort.GetPortNames result
   PortHelper Ports: COM2,COM8
   SerialPort Ports:

   Expected: True
   Actual:   False
```
Seems likely this test depends on hardware characteristics that don't apply to these ARM machines.

The System.Management.Tests failures are due to:
```
System.PlatformNotSupportedException : Could not find an installation of .NET Framework v4.0.30319. System.Management requires native modules from the .NET Framework to operate.
```
odd -- the test depends on a desktop .NET install! (Which ARM32 does not have.)

===============

Summary: only the System.Drawing.Common.Tests floating-point variation failures seem vaguely worth investigating.

category:correctness
theme:testing
skill-level:intermediate
cost:small

**Comment by RussKeldorph** [comment]
I recall looking into this or something similar earlier and determining it's effectively by design.  Mostly likely the only action to take is hardening the test.

**Comment by sandreenko** [comment]
System.Runtime.Tests was excluded from the ci testing by #17803, because of the stress mode failure #17585, but as I see from previous ci and my local runs it does not pass without stress mode as well, for [example](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst/13/consoleText):
```
Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests

Assert failure(PID 1708 [0x000006ac], Thread: 3612 [0x0e1c]): !"You cannot use this function for arbitrary value types. You must preallocate a box object and copy the value in yourself."

<no module>! <no symbol> + 0x0 (0x00000000)
    File: d:\j\workspace\arm_cross_che---99792267\src\vm\invokeutil.cpp Line: 693
    Image: C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe
```

In my local runs it usually fails with
```
 System.Tests.TypedReferenceTests.NegativeMakeTypedReference [FAIL]
      Assert.Equal() Failure
      Expected: (null)
      Actual:   flds
      Stack Trace:
         F:\git\corefx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(48,0): at System.AssertExtensions.Throws[T](String paramName, Action action)
         F:\git\corefx\src\System.Runtime\tests\System\TypedReferenceTests.cs(60,0): at System.Tests.TypedReferenceTests.NegativeMakeTypedReference()
* ExceptionTests - reported call stack:
   at System.Tests.ExceptionTests.ThrowAndRethrowSameMethod(ValueTuple`3& rethrownExceptionStackFrame) in F:\git\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 84
   at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineSameMethod() in F:\git\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 70
* ExceptionTests - reported call stack:
   at System.Tests.ExceptionTests.ThrowException() in F:\git\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 128
   at System.Tests.ExceptionTests.ThrowAndRethrowOtherMethod(ValueTuple`3& rethrownExceptionStackFrame) in F:\git\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 115
   at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod() in F:\git\corefx\src\System.Runtime\tests\System\ExceptionTests.cs:line 101
```

I have not found an open issue for that, do we have it?

**Comment by BruceForstall** [comment]
> "You cannot use this function for arbitrary value types. You must preallocate a box object and copy the value in yourself."

This should be fixed.

If you haven't found a GitHub issue, please open one.

**Comment by sandreenko** [comment]
The issue is outdated, create a new one for particular test failures when we get CoreFX testing in AzDO.
