### ISSUE TITLE
GCStress failures: tracing\tracevalidation tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#16374]
x86 checked with `COMPlus_GCStress=4`, two test failures:

tracing\tracevalidation\inducedgc\inducedgc
tracing\tracevalidation\jittingstarted\JittingStarted

The output:

```
e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\tracing\tracevalidation\inducedgc\inducedgc>inducedgc.cmd -coreroot e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
BEGIN EXECUTION
 "e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" inducedgc.exe
        Start: Enable tracing.
        End: Enable tracing.

        Start: Generate some events.
        End: Generate some events.

        Start: Disable tracing.
        End: Disable tracing.

        Start: Process the trace file.
        End: Processing events from file.


Unhandled Exception: System.Exception: Values for 'nonMatchingEventCount' are not equal! Left='11' Right='0'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in e:\gh\coreclr3\tests\src\tracing\common\Assert.cs:line 21
   at Tracing.Tests.TraceValidationInducedGC.Main(String[] args) in e:\gh\coreclr3\tests\src\tracing\tracevalidation\inducedgc\InducedGC.cs:line 76
Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED
```

```
e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\tracing\tracevalidation\jittingstarted\JittingStarted>JittingStarted.cmd -coreroot e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
BEGIN EXECUTION
 "e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" JittingStarted.exe
        Start: Enable tracing.
        End: Enable tracing.

        Start: Generate some events.

Assert failure(PID 16624 [0x000040f0], Thread: 22616 [0x5858]): CONTRACT VIOLATION by ExecutionManager::ReaderLockHolder::ReaderLockHolder at "e:\gh\coreclr3\src\vm\codeman.cpp" @ 673

HOST_CALLS  encountered in a HOST_NOCALLS scope

                        CONTRACT in ExecutionManager::ReaderLockHolder::ReaderLockHolder at "e:\gh\coreclr3\src\vm\codeman.cpp" @ 673
                        CONTRACT in ExecutionManager::FindCodeRangeWithLock at "e:\gh\coreclr3\src\vm\codeman.cpp" @ 4153
                        CONTRACT in ExecutionManager::FindCodeRange at "e:\gh\coreclr3\src\vm\codeman.cpp" @ 4132
                        CONTRACT in ExecutionManager::FindModuleForGCRefMap at "e:\gh\coreclr3\src\vm\codeman.cpp" @ 4577
                        CONTRACT in StubDispatchFrame::GetGCRefMap at "e:\gh\coreclr3\src\vm\frames.cpp" @ 674
VIOLATED-->  CONTRACT in StubDispatchFrame::UpdateRegDisplay at "e:\gh\coreclr3\src\vm\i386\cgenx86.cpp" @ 565
                        CONTRACT in EventPipe::WalkManagedStackForThread at "e:\gh\coreclr3\src\vm\eventpipe.cpp" @ 709
                        CONTRACT in EventPipe::WalkManagedStackForCurrentThread at "e:\gh\coreclr3\src\vm\eventpipe.cpp" @ 689
                        CONTRACT in EventPipeEventInstance::EventPipeEventInstance at "e:\gh\coreclr3\src\vm\eventpipeeventinstance.cpp" @ 29
                        CONTRACT in EventPipeBuffer::WriteEvent at "e:\gh\coreclr3\src\vm\eventpipebuffer.cpp" @ 59
                        CONTRACT in EventPipeBufferManager::WriteEvent at "e:\gh\coreclr3\src\vm\eventpipebuffermanager.cpp" @ 302
                        CONTRACT in EventPipe::WriteEventInternal at "e:\gh\coreclr3\src\vm\eventpipe.cpp" @ 529
                        CONTRACT in EventPipe::WriteEvent at "e:\gh\coreclr3\src\vm\eventpipe.cpp" @ 500
                        CONTRACT in VSD_ResolveWorker at "e:\gh\coreclr3\src\vm\virtualcallstub.cpp" @ 1519
                        CONTRACT in MethodDescCallSite::CallTargetWorker at "e:\gh\coreclr3\src\vm\callhelpers.cpp" @ 361
                        GCX_COOP in Assembly::ExecuteMainMethod at "e:\gh\coreclr3\src\vm\assembly.cpp" @ 1790
                        CONTRACT in Assembly::ExecuteMainMethod at "e:\gh\coreclr3\src\vm\assembly.cpp" @ 1774
                        GCX_COOP in CorHost2::ExecuteAssembly at "e:\gh\coreclr3\src\vm\corhost.cpp" @ 467
                        CONTRACT in CorHost2::ExecuteAssembly at "e:\gh\coreclr3\src\vm\corhost.cpp" @ 411



CORECLR! CONTRACT_ASSERT + 0x317 (0x0f7e7fdd)
CORECLR! EEContract::DoChecks + 0x292 (0x0f8858dc)
CORECLR! ExecutionManager::ReaderLockHolder::ReaderLockHolder + 0x85 (0x0f837617)
CORECLR! ExecutionManager::FindCodeRangeWithLock + 0x79 (0x0f83a0c9)
CORECLR! ExecutionManager::FindCodeRange + 0x83 (0x0f83a031)
CORECLR! ExecutionManager::FindModuleForGCRefMap + 0x7E (0x0f83a2eb)
CORECLR! StubDispatchFrame::GetGCRefMap + 0x8A (0x0fa3f3d4)
CORECLR! StubDispatchFrame::UpdateRegDisplay + 0xCA (0x0f888c1a)
CORECLR! StackFrameIterator::NextRaw + 0x8C6 (0x0f947a88)
CORECLR! StackFrameIterator::Next + 0x46 (0x0f94717e)
    File: e:\gh\coreclr3\src\vm\codeman.cpp Line: 673
    Image: e:\gh\coreclr3\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe

Expected: 100
Actual: 123456789
END EXECUTION - FAILED
FAILED
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_checked_windows_nt_gcstress0xc/67/#showFailuresLink

at least inducegc also fails for x64:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc/73/#showFailuresLink

If these tests should not run for GCStress, you can prevent that by adding:
1. 
```
<GCStressIncompatible>true</GCStressIncompatible>
```
to the `*.csproj` file,
2. adding `GCSTRESS_EXCLUDE` to the `Categories` of the tests in tests\arm\tests.lst and tests\arm64\tests.lst
3. There might not be a mechanism for Linux test runs.

**Comment by BruceForstall** [comment]
cc @nategraf

**Comment by brianrob** [comment]
The contract violation is interesting - I will investigate.  The induced GC test likely just shouldn't run on GCStress.  Do I need do both steps 1 and 2 to disable the tests or just one?  Also, we will need a way to disable the tests on Linux - these need to run on all platforms.

**Comment by BruceForstall** [comment]
Looks like these new tests have never been added to the arm/arm64 tests.lst files (so they are not running for arm or arm64 Windows), so step 2 isn't necessary. (If you wish to add them for those platforms, that's another story.)

It looks like the `inducegc` test is failing in Ubuntu GCStress:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_tst/61/#showFailuresLink

I don't *think* there is currently a way to disable tests on Linux only for a specific stress mode: that's a severe limitation of our current runtests.sh script.

**Comment by brianrob** [comment]
Ok, thanks.  Just confirming - if I set them as GCStress incompatible, then they are disabled for all configurations right?  If the limitation is just that you can't control per OS, then I that should be fine for these tests.

**Comment by BruceForstall** [comment]
I think what you're asking is if you add
```
<GCStressIncompatible>true</GCStressIncompatible>
```
to the csproj file, are you good?

I'm not sure: presumably the generated `<test>.sh` wrapper script will include appropriate logic to skip them for GCStress modes; you should check that.

So maybe it's only Windows arm/arm64 that are oddballs for GCStress disabling.

**Comment by brianrob** [comment]
Yes, that's what I'm asking.  I will try it.

**Comment by brianrob** [comment]
To confirm, if I specify ```<GCStressIncompatible>true</GCStressIncompatible>``` then the script files will bail early if COMPlus_GCStress is set.

The induced GC tests should be disabled for GCStress since it counts GCs.  The JittingStarted test doesn't fail on x64 which is the build that I have around so I'm doing an x86 build and will report back.

**Comment by BruceForstall** [comment]
@brianrob I'm still seeing this fail:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_gcstress0xc/74/#showFailuresLink

**Comment by brianrob** [comment]
Yup, I'm still working on these.  Will report back with a PR hopefully soon.
