### ISSUE TITLE
Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll'

### ISSUE THREAD

**Issue by miguellira** [dotnet/coreclr#1649]
Running the most basic web application:
```c#
using Microsoft.AspNet.Builder;
using Microsoft.AspNet.Http;

namespace EmptyApplication
{
    public class Startup
    {
        public void Configure(IApplicationBuilder app)
        {
            app.Run(async (context) =>
            {
                await context.Response.WriteAsync("Hello World!");
            });
        }
    }
}
```
with the following `project.json`:
```json
{
  "webroot": "wwwroot",
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-*"
  },

  "commands": {
    "kestrel": "Microsoft.AspNet.Hosting --server Microsoft.AspNet.Server.Kestrel --config server.urls=http://localhost:5000"
  },

  "frameworks": {
    "dnxcore50": {}
  }
}
```
on a Mac running the latest CoreCLR:
```console
Miguels-MBP:EmptyApplication miguellira$ dnvm list

Active Version              Runtime Architecture OperatingSystem Alias
------ -------              ------- ------------ --------------- -----
       1.0.0-beta7          coreclr x64          darwin          
       1.0.0-beta7          mono                 linux/osx       
  *    1.0.0-beta8-15736    coreclr x64          darwin          default
       1.0.0-beta8-15736    mono                 linux/osx 
```
results in the following error:
```console
Miguels-MBP:EmptyApplication miguellira$ dnx kestrel
System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-localization-l1-2-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.FormatMessage(Int32 dwFlags, IntPtr lpSource_mustBeNull, UInt32 dwMessageId, Int32 dwLanguageId, StringBuilder lpBuffer, Int32 nSize, IntPtr[] arguments)
   at Interop.mincore.TryGetErrorMessage(Int32 errorCode, StringBuilder sb, String& errorMsg)
   at Interop.mincore.GetMessage(Int32 errorCode)
   at System.Net.IPAddressParser.IPv4AddressToString(Byte[] numbers)
   at System.Net.IPAddress.ToString()
   at Microsoft.AspNet.Server.Kestrel.Networking.UvTcpHandle.Bind(String host, Int32 port)
   at Microsoft.AspNet.Server.Kestrel.Http.TcpListener.CreateListenSocket(String host, Int32 port)
   at Microsoft.AspNet.Server.Kestrel.Http.Listener.<>c__DisplayClass5_0.<StartAsync>b__0(Object _)
```
NOTE: No issues when running under Mono:
```console
Miguels-MBP:EmptyApplication miguellira$ dnx kestrel
Hosting environment: Development
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.

Miguels-MBP:EmptyApplication miguellira$ mono --version
Mono JIT compiler version 4.2.0 (Stable 4.2.0.179/a224653 Tue Sep  8 15:36:22 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            seen
```

**Comment by davidfowl** [comment]
Can you open this ok AspNet/home

**Comment by tzwlai** [comment]
Closing this since it should be on aspnet/Home instead.

**Comment by miguellira** [comment]
My bad. I've seen plenty of issues logged in aspnet/home asked to be moved to a specific repo, since the exception only occurred while running on the coreclr and not Mono I figured I'd save a step. From now on I'll be sure to log things in aspnet/home first.
