### ISSUE TITLE
LinkedList_Generic_Tests_int.RemoveLast_Tests failed on Windows in CI

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#16892]
_From @stephentoub on March 7, 2018 14:54_

https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/35efdbdc1e25f83f216064482479e555425ce3a0/workItem/System.Collections.Tests/analysis/xunit/System.Collections.Tests.LinkedList_Generic_Tests_int~2FRemoveLast_Tests
```
Windows.81.Amd64.Open-Debug-x64
Unhandled Exception of Type Xunit.Sdk.EqualException
Message :
Assert.Equal() Failure
Expected: LinkedListNode`1 { List = [718949278, 815265269, 911581260, 1007897251, 1104213242, ...], Next = LinkedListNode`1 { List = [...], Next = null, Previous = LinkedListNode`1 { ... }, Value = 1296845224 }, Previous = LinkedListNode`1 { List = [...], Next = LinkedListNode`1 { ... }, Previous = LinkedListNode`1 { ... }, Value = 1104213242 }, Value = 1200529233 }
Actual:   LinkedListNode`1 { List = [718949278, 815265269, 911581260, 1007897251, 1104213242, ...], Next = LinkedListNode`1 { List = [...], Next = null, Previous = LinkedListNode`1 { ... }, Value = 1296845224 }, Previous = LinkedListNode`1 { List = [...], Next = LinkedListNode`1 { ... }, Previous = LinkedListNode`1 { ... }, Value = 1104213242 }, Value = 1200529233 }
Stack Trace :
   at System.Collections.Tests.LinkedList_Generic_Tests`1.VerifyLinkedListNode(LinkedListNode`1 node, T expectedValue, LinkedList`1 expectedList, LinkedListNode`1 expectedPrevious, LinkedListNode`1 expectedNext) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 141
   at System.Collections.Tests.LinkedList_Generic_Tests`1.VerifyState(LinkedList`1 linkedList, T[] expectedItems) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 83
   at System.Collections.Tests.LinkedList_Generic_Tests`1.InitialItems_Tests(LinkedList`1 collection, T[] expectedItems) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 38
   at System.Collections.Tests.LinkedList_Generic_Tests`1.RemoveLast_Tests() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.RemoveLast.cs:line 89
```

_Copied from original issue: dotnet/corefx#27817_

**Comment by jkotas** [comment]
_From @danmosemsft on March 7, 2018 16:27_

That's a little worrying. The implementation and tests have not changed in some time, and there should be no concurrency involved.

Next steps might be more asserts in the test, and a better visualization of LinkedListNode in the failure case. See https://github.com/xunit/assert.xunit/blob/master/Sdk/ArgumentFormatter.cs#L148

**Comment by jkotas** [comment]
_From @danmosemsft on March 7, 2018 18:43_

@jkotas would it be a reach to suspect a runtime issue? any other theory?

**Comment by jkotas** [comment]
Memory corruption or GC hole. Running the tests on checked runtime, with GCStress enabled, may be useful.

**Comment by jkotas** [comment]
_From @stephentoub on March 10, 2018 16:22_

Another linked list test failure on Windows... different test, similar symptom:
https://mc.dot.net/#/user/stephentoub/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/83f3502519d25134909e6fbbb9b2c91d9ea902ba/workItem/System.Collections.Tests/analysis/xunit/System.Collections.Tests.LinkedList_Generic_Tests_string~2FAddBefore_LLNode_LLNode
```
Assert.Equal() Failure
Expected: LinkedListNode`1 { List = [\"F189GTPC8wg=\", \"wNm+8m1+\", \"aVI+zKY69dpM+j3EWf4=\", \"Esy/pd/29kN9Kgni\", \"u0U/fxiz96yvWQ==\", ...], Next = LinkedListNode`1 { List = [...], Next = LinkedListNode`1 { ... }, Previous = LinkedListNode`1 { ... }, Value = \"kIIAbDSR+OHI\" }, Previous = LinkedListNode`1 { List = [...], Next = LinkedListNode`1 { ... }, Previous = LinkedListNode`1 { ... }, Value = \"4nUBH6c=\" }, Value = \"OfuARW1N+Q==\" }
Actual:   LinkedListNode`1 { List = [\"F189GTPC8wg=\", \"wNm+8m1+\", \"aVI+zKY69dpM+j3EWf4=\", \"Esy/pd/29kN9Kgni\", \"u0U/fxiz96yvWQ==\", ...], Next = LinkedListNode`1 { List = [...], Next = LinkedListNode`1 { ... }, Previous = LinkedListNode`1 { ... }, Value = \"kIIAbDSR+OHI\" }, Previous = LinkedListNode`1 { List = [...], Next = LinkedListNode`1 { ... }, Previous = LinkedListNode`1 { ... }, Value = \"4nUBH6c=\" }, Value = \"OfuARW1N+Q==\" }
Stack Trace :
   at System.Collections.Tests.LinkedList_Generic_Tests`1.VerifyLinkedListNode(LinkedListNode`1 node, T expectedValue, LinkedList`1 expectedList, LinkedListNode`1 expectedPrevious, LinkedListNode`1 expectedNext) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 140
   at System.Collections.Tests.LinkedList_Generic_Tests`1.VerifyState(LinkedList`1 linkedList, T[] expectedItems) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 83
   at System.Collections.Tests.LinkedList_Generic_Tests`1.InitialItems_Tests(LinkedList`1 collection, T[] expectedItems) in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.cs:line 38
   at System.Collections.Tests.LinkedList_Generic_Tests`1.AddBefore_LLNode_LLNode() in D:\j\workspace\windows-TGrou---74aa877a\src\System.Collections\tests\Generic\LinkedList\LinkedList.Generic.Tests.AddBefore.cs:line 379
```

**Comment by jkotas** [comment]
This is JIT bug. Bad GCInfo in VerifyState method. The complete dump of GCInfo for this method is at: https://gist.github.com/jkotas/5e4097a81e96ca5aedb17b076f7b5ee

The bad GCInfo is in this fragment. `-sp+28` and `-sp+20` at 000002b7 is wrong. The arguments living at these location had to be protected till the call at 000002cb.

```
0000029b +sp+20
00007ffc`dada8dcb 4c8b45c0        mov     r8,qword ptr [rbp-40h]
00007ffc`dada8dcf 4c89442428      mov     qword ptr [rsp+28h],r8
000002a4 +sp+28
00007ffc`dada8dd4 448b45dc        mov     r8d,dword ptr [rbp-24h]
000002a8 -r8
00007ffc`dada8dd8 488b4d20        mov     rcx,qword ptr [rbp+20h]
000002ac +rcx
00007ffc`dada8ddc 4c3b4108        cmp     r8,qword ptr [rcx+8]
00007ffc`dada8de0 7205            jb      System_Collections_Tests!System.Collections.Tests.LinkedList_Generic_Tests`1[[System.Int32, System.Private.CoreLib]].VerifyState(System.Collections.Generic.LinkedList`1<Int32>, Int32[])+0x2dd357 (00007ffc`dada8de7)
00007ffc`dada8de2 e82916205e      call    coreclr!JIT_RngChkFail (00007ffd`38faa410)
000002b7 -sp+28 -sp+20 -rax
>>> 00007ffc`dada8de7 4a8d4cc110      lea     rcx,[rcx+r8*8+10h]
000002bc -rcx +rcx(interior)
00007ffc`dada8dec 4c8b01          mov     r8,qword ptr [rcx]
000002bf +r8
00007ffc`dada8def 488b4d10        mov     rcx,qword ptr [rbp+10h]
000002c3 -rcx(interior)
00007ffc`dada8df3 488b55d0        mov     rdx,qword ptr [rbp-30h]
000002c7 +rdx
00007ffc`dada8df7 4c8b4d18        mov     r9,qword ptr [rbp+18h]
000002cb +r9
00007ffc`dada8dfb e8607de8fe      call    System.Collections.Tests.LinkedList_Generic_Tests`1[[System.__Canon, System.Private.CoreLib]].VerifyLinkedListNode(System.Collections.Generic.LinkedListNode`1<System.__Canon>, System.__Canon, System.Collections.Generic.LinkedList`1<System.__Canon>, System.Collections.Generic.LinkedListNode`1<System.__Canon>, System.Collections.Generic.LinkedListNode`1<System.__Canon>) (00007ffc`d9c30b60)
000002d0 -r9 -r8 -rdx
```

**Comment by jkotas** [comment]
cc @dotnet/jit-contrib JIT is generating bad GCInfo that is causing intermittent test failures in CoreFX CI.

**Comment by briansull** [comment]
Is there a link to the source code or binary of the test case anywhere?

**Comment by jkotas** [comment]
@briansull https://github.com/dotnet/corefx/blob/master/src/System.Collections/tests/Generic/LinkedList/LinkedList.Generic.Tests.cs#L83
