### ISSUE TITLE
[Arm64/Linux] gcServer + forcerelocs --> JIT/jit64/regress/vsw/373472/test fails

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17130]
`JIT/jit64/regress/vsw/373472/test/test.sh` fails with configuration gcServer + forcerelocs
Similarly `JIT/jit64/regress/vsw/373472/test_il/test_il.sh`
```
corerun test.exe
test1 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at StrideTest.Test1()
Test1 failed
test2 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at StrideTest.Test2()
Test2 failed
Expected: 100
Actual: 1
```

@dotnet/arm64-contrib @Maoni0 @swgillespie @sywhang FYI

**Comment by Maoni0** [comment]
do you get OOM with just gcServer? or only if you have both gcServer and forcerelocs?

**Comment by sdmaclea** [comment]
Only if both are enabled.

**Comment by fiigii** [comment]
This also failed with Windows/x86 (32-bit)
```
D:\workspace\coreclr\bin\tests\Windows_NT.x86.Debug\TestWrappers\JIT.jit64\JIT.jit64.XUnitWrapper.cs(6127): error : JIT
_jit64._regress_vsw_373472_test_test_._regress_vsw_373472_test_test_cmd [FAIL] [D:\workspace\coreclr\tests\runtest.proj
]


  Return code:      1
  Raw output file:      D:\workspace\coreclr\bin\tests\Windows_NT.x86.Debug\Reports\JIT.jit64\regress\vsw\373472\test\t
  est.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\workspace\coreclr\tests\..\bin\tests\Windows_NT.x86.Debug\Tests\Core_Root\corerun.exe" test.exe
        test1 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
           at StrideTest.Test1() in D:\workspace\coreclr\tests\src\JIT\jit64\regress\vsw\373472\test.cs:line 28
        Test1 failed
        test2 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
           at StrideTest.Test2() in D:\workspace\coreclr\tests\src\JIT\jit64\regress\vsw\373472\test.cs:line 51
        Test2 failed
        test3 exception: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
           at StrideTest.Test3() in D:\workspace\coreclr\tests\src\JIT\jit64\regress\vsw\373472\test.cs:line 74
        Test3 failed
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1

  To run the test:
  > set CORE_ROOT=D:\workspace\coreclr\bin\tests\Windows_NT.x86.Debug\Tests\Core_Root
  > D:\workspace\coreclr\bin\tests\Windows_NT.x86.Debug\JIT\jit64\regress\vsw\373472\test\test.cmd

        Expected: True
        Actual:   False
          D:\workspace\coreclr\bin\tests\Windows_NT.x86.Debug\TestWrappers\JIT.jit64\JIT.jit64.XUnitWrapper.cs(6127,0):
   at JIT_jit64._regress_vsw_373472_test_test_._regress_vsw_373472_test_test_cmd()
```

cc @AndyAyersMS @CarolEidt
