### ISSUE TITLE
[Arm64] System.Tests.MathFTests.Pow(x: 0, y: -3, expectedResult: -∞, allowedVariance: 0) [FAIL]

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17175]
```
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Extensions.Tests
Discovered:  System.Runtime.Extensions.Tests
Starting:    System.Runtime.Extensions.Tests
   System.Tests.EnvironmentTests.GetFolderPath_UapExistAndAccessible [SKIP]
      Condition(s) not met: \"IsWindows10Version1709OrGreater\", \"IsInAppContainer\"
   System.Tests.MathFTests.Ceiling(value: -0.3183099, expectedResult: 0, allowedVariance: 0) [SKIP]
      https://github.com/dotnet/coreclr/issues/10287
   System.Tests.MathFTests.Ceiling(value: -0.4342945, expectedResult: 0, allowedVariance: 0) [SKIP]
      https://github.com/dotnet/coreclr/issues/10287
   System.Tests.MathFTests.Ceiling(value: -0.6366197, expectedResult: 0, allowedVariance: 0) [SKIP]
      https://github.com/dotnet/coreclr/issues/10287
   System.Tests.MathFTests.Ceiling(value: -0.6931472, expectedResult: 0, allowedVariance: 0) [SKIP]
      https://github.com/dotnet/coreclr/issues/10287
   System.Tests.MathFTests.Ceiling(value: -0.7071068, expectedResult: 0, allowedVariance: 0) [SKIP]
      https://github.com/dotnet/coreclr/issues/10287
   System.Tests.MathFTests.Ceiling(value: -0.7853982, expectedResult: 0, allowedVariance: 0) [SKIP]
      https://github.com/dotnet/coreclr/issues/10287
   System.Tests.MathTests.Floor_Double(value: 0, expectedResult: 0, allowedVariance: 0) [SKIP]
      https://github.com/dotnet/coreclr/issues/10288
   System.Tests.MathTests.Pow(x: 0, y: -3, expectedResult: -∞, allowedVariance: 0) [FAIL]
      Assert.Equal() Failure
      Expected:                   -∞
      Actual:                     +∞
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Runtime.Extensions/tests/System/Math.cs(69,0): at System.Tests.MathTests.AssertEqual(Double expected, Double actual, Double variance)
   System.Tests.MathFTests.Pow(x: 0, y: -3, expectedResult: -∞, allowedVariance: 0) [FAIL]
      Assert.Equal() Failure
      Expected:         -∞
      Actual:           +∞
      Stack Trace:
         /home/vmjenkins/workspace/Dotnet/build_corefx/src/System.Runtime.Extensions/tests/System/MathF.netcoreapp.cs(54,0): at System.Tests.MathFTests.AssertEqual(Single expected, Single actual, Single variance)
```

**Comment by sdmaclea** [comment]
@janvorli : @debayang looked into this.  He was finding the issue was in the PAL pow() emulation library.  The pow(-0.0, -1.0) returns the wrong answer.

I took a look at the settings in cross/arm64/tryrun.cmake and found `set(HAVE_COMPATIBLE_POW_EXITCODE  1 ...)`

This does not match what I see in `grep _EXITCODE ./bin/obj/Linux.arm64.Checked/CMakeCache.txt` when building on target.

I will create a PR to update cross/arm64/tryrun.cmake.  There is another setting which is not matching too.

**Comment by sdmaclea** [comment]
Someone can take the arm64 label off this

**Comment by tannergooding** [comment]
For reference, the test is validating section `9.2.1 Special Values` of the IEEE spec:
> pow (±0, y) is ±∞ and signals the divideByZero exception for y an odd integer < 0

This IEEE compliant behavior also matches the behavior documented in `Annex F (normative) IEC 60559 floating-point arithmetic` of the C Language Specification (see `F.10.4.4 The pow functions`):
> pow(±0, y) returns ±∞ and raises the ‘‘divide-by-zero’’ floating-point exception
for y an odd integer < 0.
