### ISSUE TITLE
[Arm64/arm32] GCStress failure in tracing/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#17188]
`tracing/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh` fails often in `gcStress0x4`

```
corerun eventsourcetrace.exe
Start: Enable tracing.
End: Enable tracing.

Start: Messaging.
End: Messaging.

Start: Disable tracing.
FailFast:
A callback was made on a garbage collected delegate of type 'System.Private.CoreLib!Microsoft.Win32.UnsafeNativeMethods+ManifestEtw+EtwEnableCallback::Invoke'.

   at System.Diagnostics.Tracing.EventPipeInternal.Disable()
   at System.Diagnostics.Tracing.EventPipeInternal.Disable()
   at System.Diagnostics.Tracing.EventPipe.Disable()
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at Tracing.Tests.EventSourceTrace.Main(System.String[])
```

**Comment by sdmaclea** [comment]
Also fails like like
```
corerun eventsourcetrace.exe
Start: Enable tracing.
End: Enable tracing.

Start: Messaging.
End: Messaging.

Start: Disable tracing.

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Diagnostics.Tracing.EventPipeInternal.Disable()
   at System.Diagnostics.Tracing.EventPipe.Disable()
```

**Comment by sdmaclea** [comment]
gcStress0x2 sometime too

**Comment by BruceForstall** [comment]
@brianrob @nategraf

**Comment by brianrob** [comment]
What’s the best way to get a repro of this?

**Comment by sdmaclea** [comment]
It fails most runs.  
I just run the test using the `tracing/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh` script.

@dotnet/arm64-contrib can help you find an appropriate arm64 machine

**Comment by brianrob** [comment]
Ok, thanks @sdmaclea.  @dotnet/arm64-contrib it would be great if you can help me get access to an arm64 machine where I can repro this.

**Comment by sdmaclea** [comment]
@brianrob 

After #18217, I am seeing this fail consistently like this on linux-arm64 in gcStress=2

```
corerun eventsourcetrace.exe
Start: Enable tracing.
End: Enable tracing.

Start: Messaging.

Assert failure(PID 24319 [0x00005eff], Thread: 24319 [0x5eff]): 
    CORProfilerStackSnapshotEnabled() || !IsStackWalkerThread()
    File: src/vm/stackwalk.cpp Line: 932
```

**Comment by BruceForstall** [comment]
@brianrob @sdmaclea Can we mark this test `<GCStressIncompatible>true</GCStressIncompatible>` for now?

**Comment by brianrob** [comment]
I think that marking this as incompatible for now is fine, we should just keep this bug around so that it can be investigated further.

**Comment by jorive** [comment]
Keep this open to reenable disabled test.

**Comment by vancem** [comment]
Yes.  I see no reason why this test should fail under GCStress.  @jorive  has disabled it for now, but we should definitely understand why it is failing.

Note that so far we only know that it fails on ARM systems.  We should confirm that it succeeds on X64 systems.  If so, that does tend to make it a JIT/Runtime issue.   

The fact it fails in GCStress 4 (which is about testing that the JIT emitted the proper GC tracking information for methods), suggests that a JIT dev should look at it.

Do we have a JIT Dev who can take a look?

**Comment by AndyAyersMS** [comment]
Sure, I'll take a look.

**Comment by AndyAyersMS** [comment]
I don't see this failing in recent CI history (though we don't have much), at least for arm64.

Trying to repro on Linux arm64 with
```
COMPlus_TieredCompilation=0
COMPlus_GCStress=0x4
```
and stress-loading the machine via
```
stress -c 50 -m 25 -i 25
```
No luck so far.

@jorive did you manage to get this test to fail under stress before your recent PR to disable it?

**Comment by jorive** [comment]
@AndyAyersMS No, sorry, I did not managed to repro this before my recent PR. There is not much history in CI neither, and I noticed it failed the last two runs too.

**Comment by AndyAyersMS** [comment]
> and I noticed it failed the last two runs too

Did you mean to say you noticed it did **not** fail?

**Comment by jorive** [comment]
Yes, from the limited history available in Jenkins, I did not see the arm legs fail before I disabled the test. On the other hand, the stress legs failed last two runs after disabling the test:
[arm_cross_checked_ubuntu_gcstress0xc_tst](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_tst/)
```log
    Discovering: GC.API.XUnitWrapper
    Discovered:  GC.API.XUnitWrapper
    Starting:    GC.API.XUnitWrapper
      GC_API._GC_Collect_Collect_._GC_Collect_Collect_sh [FAIL]
        /n/nReturn code:      1/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.arm.Checked/GC/API/Reports/GC.API/GC/Collect/Collect.output.txt/nRaw output:/nBEGIN EXECUTION
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun Collect.exe ''
        Array is in generation: 0
        Array is in generation: 0
        Test for GC.Collect() failed!
        Expected: 100
        Actual: 1
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.arm.Checked/GC/API/GC/Collect/Collect.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/bin/tests/Linux.arm.Checked/TestWrappers/GC.API/GC.API.XUnitWrapper.cs(319,0): at GC_API._GC_Collect_Collect_._GC_Collect_Collect_sh()
    Finished:    GC.API.XUnitWrapper
```
[arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/)
```log
    Discovering: JIT.Regression.XUnitWrapper
    Discovered:  JIT.Regression.XUnitWrapper
    Starting:    JIT.Regression.XUnitWrapper
      JIT_Regression._CLR_x86_JIT_V2_0_Beta2_b268908_b268908_b268908_._CLR_x86_JIT_V2_0_Beta2_b268908_b268908_b268908_sh [FAIL]
        
        Assert failure(PID 28592 [0x00006fb0], Thread: 28592 [0x6fb0]): SUCCEEDED(res)
            File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/unwinder/arm/unwinder_arm.cpp Line: 1540
            Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
        
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b268908/b268908/b268908.sh: line 244: 28592 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
        /n/nReturn code:      1/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/Reports/JIT.Regression/CLR-x86-JIT/V2.0-Beta2/b268908/b268908/b268908.output.txt/nRaw output:/nBEGIN EXECUTION
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun b268908.exe
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b268908/b268908/b268908.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/bin/tests/Linux.arm.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs(59049,0): at JIT_Regression._CLR_x86_JIT_V2_0_Beta2_b268908_b268908_b268908_._CLR_x86_JIT_V2_0_Beta2_b268908_b268908_b268908_sh()
      JIT_Regression._CLR_x86_JIT_V2_0_Beta2_b399444_b399444b_b399444b_._CLR_x86_JIT_V2_0_Beta2_b399444_b399444b_b399444b_sh [FAIL]
        
        Assert failure(PID 29289 [0x00007269], Thread: 29289 [0x7269]): SUCCEEDED(res)
            File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/unwinder/arm/unwinder_arm.cpp Line: 1540
            Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
        
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.sh: line 244: 29289 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
        /n/nReturn code:      1/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/Reports/JIT.Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.output.txt/nRaw output:/nBEGIN EXECUTION
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun b399444b.exe
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/CLR-x86-JIT/V2.0-Beta2/b399444/b399444b/b399444b.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/bin/tests/Linux.arm.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs(59819,0): at JIT_Regression._CLR_x86_JIT_V2_0_Beta2_b399444_b399444b_b399444b_._CLR_x86_JIT_V2_0_Beta2_b399444_b399444b_b399444b_sh()
      JIT_Regression._VS_ia64_JIT_V2_0_Beta2_b311420_b311420_b311420_._VS_ia64_JIT_V2_0_Beta2_b311420_b311420_b311420_sh [FAIL]
        
        Assert failure(PID 5036 [0x000013ac], Thread: 5036 [0x13ac]): SUCCEEDED(res)
            File: /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/src/unwinder/arm/unwinder_arm.cpp Line: 1540
            Image: /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun
        
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.sh: line 244:  5036 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
        /n/nReturn code:      1/nRaw output file:      /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/Reports/JIT.Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.output.txt/nRaw output:/nBEGIN EXECUTION
        /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/corerun b311420.exe
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/Tests/Core_Root/n> /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_gcstress0xc_jitstress2_tst/bin/tests/Linux.arm.Checked/JIT/Regression/VS-ia64-JIT/V2.0-Beta2/b311420/b311420/b311420.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm_cross_checked_ubuntu/bin/tests/Linux.arm.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs(94749,0): at JIT_Regression._VS_ia64_JIT_V2_0_Beta2_b311420_b311420_b311420_._VS_ia64_JIT_V2_0_Beta2_b311420_b311420_b311420_sh()
    Finished:    JIT.Regression.XUnitWrapper
```

**Comment by AndyAyersMS** [comment]
Last two rolling runs of arm64 0xC gc stress are clean (59 and 60).

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_windows_nt_gcstress0xc_tst/

(not sure how much was disabled to get us to this state, but what we're running now is passing).

Let me put up a PR re-enabling this test and see if we can get it to fail via CI.
