### ISSUE TITLE
Failure: StringBuilder.set_Length: The new chunk should be larger than the one it is replacing.

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#17205]
For `Windows_NT x64 Checked corefx_baseline` and `Ubuntu x64 Checked corefx_baseline` https://github.com/dotnet/coreclr/pull/17204 also https://github.com/dotnet/coreclr/pull/17196#issuecomment-375945569

Ubuntu x64 Checked Build and Test (Jit - CoreFx) failure:
```
Discovering: System.Security.SecureString.Tests
Discovered:  System.Security.SecureString.Tests
Starting:    System.Security.SecureString.Tests
Assertion Failed
The new chunk should be larger than the one it is replacing.

   at System.Text.StringBuilder.set_Length(Int32 value)
   at System.Text.StringBuilder.Remove(Int32 startIndex, Int32 length)
   at System.Security.Tests.SecureStringTests.GrowAndContract_Small() in /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.Security.SecureString/tests/SecureStringTests.cs:line 426
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at ...
```

Perhaps related to https://github.com/dotnet/coreclr/pull/16926?

/cc @maryamariyan @danmosemsft @jkotas

**Comment by maryamariyan** [comment]
... Looking at it
