### ISSUE TITLE
[arm32/Ubuntu] Enable GCStress CI jobs

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17241]

**Comment by BruceForstall** [comment]
@janvorli I've started working on this, and my first attempts to run GCStress=4 show very early failures.

Do you know if anyone has tried Linux arm32 GCStress before? Do you think it should "just work", or are there known issues that need to be addressed first?

E.g.,
```
ubuntu@tegra-ubuntu-131:/ssd/brucefo/debug/coreclr/bin/tests/Linux.arm.Debug/JIT/CodeGenBringUpTests/Add1$ ./r.sh
++ export COMPlus_GCStress=4
++ COMPlus_GCStress=4
++ /ssd/brucefo/debug/coreclr/bin/tests/Linux.arm.Debug/Tests/Core_Root/corerun ./Add1.exe

Assert failure(PID 13427 [0x00003473], Thread: 13427 [0x3473]): !CREATE_CHECK_STRING(pMT && pMT->Validate())
    File: /mnt/coreclr/src/vm/object.cpp Line: 733
    Image: /ssd/brucefo/debug/coreclr/bin/tests/Linux.arm.Debug/Tests/Core_Root/corerun
```
under gdb:
```
(gdb) bt
#0  0xb0ea50b0 in ?? ()
#1  0xb66b612e in CallDescrWorkerInternal () at /mnt/coreclr/src/vm/arm/asmhelpers.S:79
#2  0xb656af4c in CallDescrWorker (pCallDescrData=0xbeffe820) at /mnt/coreclr/src/vm/callhelpers.cpp:135
#3  0xb656ade6 in CallDescrWorkerWithHandler (pCallDescrData=0xbeffe820, fCriticalCall=0) at /mnt/coreclr/src/vm/callhelpers.cpp:78
#4  0xb656bd38 in MethodDescCallSite::CallTargetWorker (this=0xbeffe9ac, pArguments=0xbeffea20, pReturnValue=0x0, cbReturnValue=0)
    at /mnt/coreclr/src/vm/callhelpers.cpp:620
#5  0xb64535f8 in MethodDescCallSite::Call (this=0xbeffe9ac, pArguments=0xbeffea20) at /mnt/coreclr/src/vm/callhelpers.h:433
#6  0xb66bcae8 in AppDomain::InitializeDomainContext (this=0x637b8, allowRedirects=1, pwszPath=0x0, pwszConfig=0x0)
    at /mnt/coreclr/src/vm/appdomain.cpp:7628
#7  0xb66bc532 in SystemDomain::InitializeDefaultDomain (allowRedirects=1, pBinder=0x0) at /mnt/coreclr/src/vm/appdomain.cpp:3198
#8  0xb66bbf6a in SystemDomain::SetupDefaultDomain () at /mnt/coreclr/src/vm/appdomain.cpp:3134
#9  0xb66bc63c in SystemDomain::SetupDefaultDomainNoThrow () at /mnt/coreclr/src/vm/appdomain.cpp:3157
#10 0xb656c55a in EEStartup (fFlags=COINITEE_DEFAULT) at /mnt/coreclr/src/vm/ceemain.cpp:1237
#11 0xb656c2a0 in EnsureEEStarted (flags=COINITEE_DEFAULT) at /mnt/coreclr/src/vm/ceemain.cpp:365
#12 0xb656c1d6 in InitializeEE (flags=COINITEE_DEFAULT) at /mnt/coreclr/src/vm/ceemain.cpp:303
#13 0xb644ccf6 in CorRuntimeHostBase::Start (this=0x17bec) at /mnt/coreclr/src/vm/corhost.cpp:224
#14 0xb644cc50 in CorHost2::Start (this=0x17be8) at /mnt/coreclr/src/vm/corhost.cpp:182
#15 0xb6409c38 in coreclr_initialize (exePath=0x17014 "/ssd/brucefo/debug/coreclr/bin/tests/Linux.arm.Debug/Tests/Core_Root/corerun",
    appDomainFriendlyName=0xcffe "unixcorerun", propertyCount=6, propertyKeys=0xbefff1fc, propertyValues=0xbefff1e4, hostHandle=0xbefff1c8,
    domainId=0xbefff1c4) at /mnt/coreclr/src/dlls/mscoree/unixinterface.cpp:216
#16 0x0000bb0e in ExecuteManagedAssembly (
    currentExeAbsolutePath=0x17014 "/ssd/brucefo/debug/coreclr/bin/tests/Linux.arm.Debug/Tests/Core_Root/corerun",
    clrFilesAbsolutePath=0x170d4 "/ssd/brucefo/debug/coreclr/bin/tests/Linux.arm.Debug/Tests/Core_Root",
    managedAssemblyAbsolutePath=0x1712c "/ssd/brucefo/debug/coreclr/bin/tests/Linux.arm.Debug/JIT/CodeGenBringUpTests/Add1/Add1.exe",
    managedAssemblyArgc=0, managedAssemblyArgv=0x0) at /mnt/coreclr/src/coreclr/hosts/unixcoreruncommon/coreruncommon.cpp:413
#17 0x0000b1c0 in corerun (argc=2, argv=0xbefff4a4) at /mnt/coreclr/src/coreclr/hosts/unixcorerun/corerun.cpp:149
#18 0x0000b264 in main (argc=2, argv=0xbefff4a4) at /mnt/coreclr/src/coreclr/hosts/unixcorerun/corerun.cpp:161
```

I haven't gotten any farther, e.g., trying to run under LLDB + SOS, or getting JitDump with GC info dump, or using CLR logging.

**Comment by janvorli** [comment]
I don't know if anyone has tried Linux arm32 GCStress before. I would guess that the answer is "no". 
As for LLDB, I couldn't make it work on my Raspbian for some reason yet. It can load and run processes, but setting breakpoints doesn't work and while I can break into the running process, it doesn't show any stack trace, the "target modules list" shows nothing, etc.

**Comment by BruceForstall** [comment]
Current status: GCStress for Ubuntu ARM currently runs. The GCStress jobs are available for triggering in the CI.

However, no triggered job has ever successfully completed, due to timeouts or other issues. I'm keeping this issue open until that happens.

**Comment by BruceForstall** [comment]
These jobs are all running now, and we've seen results.
