### ISSUE TITLE
Building from medium-long path fails in package restore

### ISSUE THREAD

**Issue by poizan42** [dotnet/coreclr#1731]
```
C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx>build.cmd
  Restoring all packages...
C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx\build.proj(24,5): error MSB3073: The command ""C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta7/\bin\dnu.cmd" res
tore --packages "C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx\packages" --source https://www.myget.org/F/dotnet-core/ --source https://www.myget.org/F/dotnet-coreclr/ --source https://www.myget.org/F/dotnet-corefxtes
tdata/ --source https://www.myget.org/F/dotnet-buildtools/ --source https://www.nuget.org/api/v2/ "C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx\src" "C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx\p
ackages/Microsoft.DotNet.BuildTools.1.0.25-prerelease-00104/lib/"" exited with code 1.

    0 Warning(s)
    1 Error(s)
Time Elapsed 00:01:34.70
Build Exit Code = 1
```

Running the command manually:

```
C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx>"C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx\packages//dnx-coreclr-win-x86.1.0.0-beta7/\bin\dnu.cmd" restore --packages "C:\Users\kb\Documents\Visual Studio 2015\Projects\netcore\corefx\packages" --source https://www.myget.org/F/dotnet-core/ --source https://www.myget.org/F/dotnet-coreclr/ --source https://www.myget.org/F/dotnet-corefxtestdata/ --source https://www.myget.org/F/dotnet-buildtools/ --source https://www.nuget.org/api/v2/
Microsoft .NET Development Utility CoreCLR-x86-1.0.0-beta7-15532

... (snip) ...

----------
System.ArgumentException: The name can be no more than 260 characters in length.
   at System.Threading.Semaphore.ValidateNewName(String name)
   at System.Threading.Semaphore..ctor(Int32 initialCount, Int32 maximumCount, String name, Boolean& createdNew)
   at Microsoft.Dnx.Runtime.Internal.ConcurrencyUtilities.SemaphoreWrapper.Create(Int32 initialCount, Int32 maximumCount, String name, Boolean& createdNew)
   at Microsoft.Dnx.Runtime.Internal.ConcurrencyUtilities.<ExecuteWithFileLocked>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.NuGetPackageUtils.<InstallFromStream>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<InstallPackageCore>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<InstallPackages>d__66.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass60_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__60.MoveNext()
----------
Restore failed
The name can be no more than 260 characters in length.

NuGet Config files used:
    C:\Users\kb\AppData\Roaming\NuGet\NuGet.Config

Feeds used:
    https://www.myget.org/F/dotnet-core/
    https://www.myget.org/F/dotnet-coreclr/
    https://www.myget.org/F/dotnet-corefxtestdata/
    https://www.myget.org/F/dotnet-buildtools/
    https://www.nuget.org/api/v2/
```

**Comment by poizan42** [comment]
This can be fixed by lifting the path length restriction on semaphores (dotnet/corefx#3740) or by changing how the semaphore name is generated from the filename (aspnet/dnx#2943)

**Comment by ericstj** [comment]
I just noticed this bug here in the coreclr repo.

As @poizan42 mentioned, the code to which this issue is referring was part of DNX, not coreclr.  This code now lives in NuGet.  If you still see the issue you should file an issue in https://github.com/nuget/home.
