### ISSUE TITLE
[Linux] [CoreClr] SecureString, an exception during instantiation

### ISSUE THREAD

**Issue by mviorno** [dotnet/coreclr#1732]
During execution of the following code

```csharp
SecureString str = new SecureString();
```

got an exception:

```
      System.DllNotFoundException : Unable to load DLL 'oleaut32.dll': The specified module could not be found.
       (Exception from HRESULT: 0x8007007E)
      Stack Trace:
           at Interop.OleAut32.SysAllocStringLen(String src, UInt32 len)
           at System.Security.SafeBSTRHandle.Allocate(String src, UInt32 lenInChars)
           at System.Security.SecureString.InitializeSecureString(Char* value, Int32 length)
           at DevExpress.Compatibility.System.Security.SecureStringTest()
```

The runtime is looking for OLE automation on my linux machine, have no chance ^)

Environment:

```
uname -a

Linux debianDNX 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux
```

```
dnvm list

Active Version              Runtime Arch OperatingSystem Alias
------ -------              ------- ---- --------------- -----
       1.0.0-beta6          mono         linux/darwin
  *    1.0.0-rc1-15838      coreclr x64  linux           default
       1.0.0-beta8-15618    mono         linux/darwin
       1.0.0-beta8-15530    mono         linux/darwin
       1.0.0-rc1-15838      mono         linux/darwin
       1.0.0-beta8-15618    coreclr x64  linux
       1.0.0-beta7          mono         linux/darwin
```

**Comment by stephentoub** [comment]
SecureString is being removed from coreclr/corefx.  As a result the existing package for it does not contain a Linux implementation.

cc: @weshaggard

**Comment by mviorno** [comment]
Ok, thanks for information.
