### ISSUE TITLE
Exception when using Normalize method in Linux

### ISSUE THREAD

**Issue by kichalla** [dotnet/coreclr#1752]
When I execute the following piece of code (as part of a Dnx console app) in my linux machine, I get the following error...any ideas?

```
var name = "John";
Console.WriteLine(name.Normalize().ToUpperInvariant());
```

Exception
```
System.DllNotFoundException: Unable to load DLL 'api-ms-win-core-errorhandling-l1-1-0.dll': The specified module could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Interop.mincore.SetLastError(UInt32 dwErrCode)
   at System.StringNormalizationExtensions.Normalize(String value, NormalizationForm normalizationForm)
   at DnxConsoleApp.Program.Main(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.ApplicationHost.Program.ExecuteMain(DefaultHost host, String applicationName, String[] args)
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
```

My dnx project dependencies:
```
"frameworks": {
    "dnx451": { },
    "dnxcore50": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-*",
        "System.Collections": "4.0.11-beta-*",
        "System.Console": "4.0.0-beta-*",
        "System.Linq": "4.0.1-beta-*",
        "System.Threading": "4.0.11-beta-*",
        "System.Globalization.Extensions": "4.0.1-beta-*"
      }
    }
  }

```

@haok

**Comment by kichalla** [comment]
cc @dougbu @davidfowl

**Comment by kichalla** [comment]
cc @anurse

**Comment by dougbu** [comment]
FYI this is likely a DNX issue that @anurse has just fixed. Will close once we're able to confirm the problem goes away with the latest DNX bits.

**Comment by anurse** [comment]
This should be fixed now. I'm not sure why I was assigned a bug on the dotnet/coreclr repo, but I'm going to close it and it can be re-opened if it's still reproing.

**Comment by dougbu** [comment]
My fault I guess @anurse. I should have closed this bug when I realized the issue was in DNX and not Core CLR or Core Fx.

Separately I've confirmed the problem no longer reproduces.
