### ISSUE TITLE
Failures in x64_checked_windows_nt_corefx_jitstress1 jobs

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#17557]
We get the following failures in  x64_checked_windows_nt_corefx_jitstress1 jobs (e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/Windows_NT/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress1/lastBuild/consoleText)

```
     System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: null, lineNumber: -1, columnNumber: 0) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   8
        Stack Trace:
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(112,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
     System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"\", lineNumber: 0, columnNumber: -1) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   8
        Stack Trace:
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(112,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
     System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(fileName: \"FileName\", lineNumber: 1, columnNumber: 2) [FAIL]
        Assert.Equal() Failure
        Expected: 0
        Actual:   8
        Stack Trace:
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(170,0): at System.Diagnostics.Tests.StackFrameTests.VerifyStackFrameSkipFrames(StackFrame stackFrame, Boolean isFileConstructor, Int32 skipFrames, MethodInfo expectedMethod, Boolean isCurrentFrame)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Diagnostics.StackTrace\tests\StackFrameTests.cs(112,0): at System.Diagnostics.Tests.StackFrameTests.Ctor_Filename_LineNumber_ColNumber(String fileName, Int32 lineNumber, Int32 columnNumber)
  Finished:    System.Diagnostics.StackTrace.Tests
```
```
DataContractSerializerTests.DCS_ResolveDatacontractBaseType [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
  Finished:    System.Security.Cryptography.Cng.Tests
  
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Runtime.Serialization.Xml\tests\SerializationTestTypes\DataContractResolverLibrary.cs(84,0): at SerializationTestTypes.ProxyDataContractResolver.ResolveName(String typeName, String typeNamespace, Type declaredType, DataContractResolver knownTypeResolver)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerContext.cs(276,0): at System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes(String typeName, String typeNs, DataContract memberTypeContract)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\KnownTypeDataContractResolver.cs(26,0): at System.Runtime.Serialization.KnownTypeDataContractResolver.TryResolveType(Type type, Type declaredType, DataContractResolver knownTypeResolver, XmlDictionaryString& typeName, XmlDictionaryString& typeNamespace)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(673,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType(Type objectType, Type declaredType, XmlDictionaryString& typeName, XmlDictionaryString& typeNamespace)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(665,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteResolvedTypeInfo(XmlWriterDelegator writer, Type objectType, Type declaredType)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(710,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo(XmlWriterDelegator writer, DataContract contract, DataContract declaredContract)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(178,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs(376,0): at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs(237,0): at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(71,0): at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(57,0): at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
```
```
DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Runtime.Serialization.Xml\tests\SerializationTestTypes\DataContractResolverLibrary.cs(75,0): at SerializationTestTypes.EmptyNamespaceResolver.ResolveName(String typeName, String typeNamespace, Type declaredType, DataContractResolver knownTypeResolver)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerContext.cs(276,0): at System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes(String typeName, String typeNs, DataContract memberTypeContract)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\KnownTypeDataContractResolver.cs(26,0): at System.Runtime.Serialization.KnownTypeDataContractResolver.TryResolveType(Type type, Type declaredType, DataContractResolver knownTypeResolver, XmlDictionaryString& typeName, XmlDictionaryString& typeNamespace)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(673,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType(Type objectType, Type declaredType, XmlDictionaryString& typeName, XmlDictionaryString& typeNamespace)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(665,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteResolvedTypeInfo(XmlWriterDelegator writer, Type objectType, Type declaredType)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(710,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo(XmlWriterDelegator writer, DataContract contract, DataContract declaredContract)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(230,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiType(XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle objectTypeHandle, Type objectType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle, Type declaredType)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(143,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.InternalSerialize(XmlWriterDelegator xmlWriter, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Int32 declaredTypeID, RuntimeTypeHandle declaredTypeHandle)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ReflectionClassWriter.cs(158,0): at System.Runtime.Serialization.ReflectionClassWriter.ReflectionInternalSerialize(XmlWriterDelegator xmlWriter, XmlObjectSerializerWriteContext context, Object obj, Boolean isDeclaredType, Boolean writeXsiType, Type memberType, Boolean isNullableOfT)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ReflectionClassWriter.cs(95,0): at System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteValue(XmlWriterDelegator xmlWriter, XmlObjectSerializerWriteContext context, Type type, Object value, Boolean writeXsiType, PrimitiveDataContract primitiveContractForParamType)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ReflectionXmlFormatWriter.cs(187,0): at System.Runtime.Serialization.ReflectionXmlClassWriter.ReflectionWriteMembers(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract classContract, ClassDataContract derivedMostClassContract, Int32 childElementIndex, XmlDictionaryString[] emptyStringArray)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ReflectionClassWriter.cs(35,0): at System.Runtime.Serialization.ReflectionClassWriter.ReflectionWriteClass(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract classContract, XmlDictionaryString[] memberNames)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ReflectionXmlFormatWriter.cs(20,0): at System.Runtime.Serialization.ReflectionXmlFormatWriter.ReflectionWriteClass(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context, ClassDataContract classContract)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\ClassDataContract.cs(507,0): at System.Runtime.Serialization.ClassDataContract.WriteXmlValue(XmlWriterDelegator xmlWriter, Object obj, XmlObjectSerializerWriteContext context)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(654,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteDataContractValue(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(155,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithoutXsiType(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle declaredTypeHandle)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs(354,0): at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs(237,0): at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(71,0): at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(57,0): at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(27,0): at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\Common\tests\System\Runtime\Serialization\DataContractSerializerHelper.cs(29,0): at System.Runtime.Serialization.Tests.DataContractSerializerHelper.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
           D:\j\workspace\x64_checked_w---b16ed97b\_\fx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs(2784,0): at DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace()
```

**Comment by RussKeldorph** [comment]
@erozenfeld Do you know if these fail in the same way with a Debug runtime?  I assume they don't fail with Release or else we'd see it in dotnet/corefx.

**Comment by RussKeldorph** [comment]
Oops, nevermind....I missed that this is jitstress

**Comment by erozenfeld** [comment]
The last 2 failures also happen in x64_checked_windows_nt_corefx_jitstress2 jobs, e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/Windows_NT/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress2/484/consoleText

**Comment by briansull** [comment]
I need repro instructions

**Comment by erozenfeld** [comment]
You can replicate the build and test steps from a failing log: https://ci.dot.net/job/dotnet_coreclr/job/master/view/Windows_NT/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress1/lastBuild/consoleText

**Comment by briansull** [comment]
In the source code for this test on line 170 (where we hit the Assert.Equal issue)
We have the following code:

```
#if !DEBUG
            else if ((!PlatformDetection.IsFullFramework && isFileConstructor) || (PlatformDetection.IsFullFramework && !isFileConstructor && !isCurrentFrame && skipFrames == 0))
            {
                Assert.Equal(0, stackFrame.GetILOffset());
            }
#endif
```

**Comment by briansull** [comment]
This is a test issue.

**Comment by BruceForstall** [comment]
System.Diagnostics.StackTrace.Tests failures also exist on ARM:

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_jitstress1_tst_prtest/1/consoleText

**Comment by briansull** [comment]
Resolving as Won't Fix

Delete tests that depend on JIT optimization behavior #30444
