### ISSUE TITLE
[arm64] Assertion failed '(candidates & allRegs(srcInterval->registerType)) != 0'

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17573]
x64_arm64_altjit job failures:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitstress1/
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitstress2/

```
D:\j\workspace\x64_arm64_alt---733f8d21\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(247): error : JIT_HardwareIntrinsics._Arm64_Simd_Simd_._Arm64_Simd_Simd_cmd [FAIL] [D:\j\workspace\x64_arm64_alt---733f8d21\tests\runtest.proj]
07:29:17         
07:29:17 
        Assert failure(PID 6328 [0x000018b8], Thread: 1960 [0x07a8]): Assertion failed '(candidates & allRegs(srcInterval->registerType)) != 0' in '<>c:<TestAdd>b__21_40(struct,struct):struct:this' (IL size 8)
07:29:17         
07:29:17             File: d:\j\workspace\x64_arm64_alt---733f8d21\src\jit\lsrabuild.cpp Line: 1577
07:29:17             Image: D:\j\workspace\x64_arm64_alt---733f8d21\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
07:29:17         
07:29:17         
07:29:17   
07:29:17   Return code:      1
07:29:17   Raw output file:      D:\j\workspace\x64_arm64_alt---733f8d21\bin\tests\Windows_NT.x64.Checked\Reports\JIT.HardwareIntrinsics\Arm64\Simd\Simd.output.txt
07:29:17   Raw output:
07:29:17   BEGIN EXECUTION
07:29:17          "D:\j\workspace\x64_arm64_alt---733f8d21\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" Simd.exe 
07:29:17         System.Runtime.Intrinsics.Arm.Arm64.Simd.IsSupported = False
07:29:17         Using default data set
07:29:17         TestAbs passed
07:29:17         Expected: 100
07:29:17         Actual: 123456789
07:29:17         END EXECUTION - FAILED
07:29:17         FAILED
07:29:17         Test Harness Exitcode is : 1
07:29:17         
07:29:17   To run the test:
07:29:17   > set CORE_ROOT=D:\j\workspace\x64_arm64_alt---733f8d21\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
07:29:17   > D:\j\workspace\x64_arm64_alt---733f8d21\bin\tests\Windows_NT.x64.Checked\JIT\HardwareIntrinsics\Arm64\Simd\Simd.cmd
07:29:17   
07:29:17         Expected: True
07:29:17         Actual:   False
07:29:17           D:\j\workspace\x64_arm64_alt---733f8d21\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(247,0): at JIT_HardwareIntrinsics._Arm64_Simd_Simd_._Arm64_Simd_Simd_cmd()
```

**Comment by BruceForstall** [comment]
@sdmaclea @dotnet/arm64-contrib

**Comment by BruceForstall** [comment]
In minopts, it fails with a different assert:

Assertion failed '(consume > 1) || (regType(store->gtOp1->TypeGet()) == regType(store->TypeGet()))'

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_minopts/157/consoleFull#159614762933fe3402-0c0f-45a7-a707-47164965bab5

```
D:\j\workspace\x64_arm64_alt---85bca9a1\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(247): error : JIT_HardwareIntrinsics._Arm64_Simd_Simd_._Arm64_Simd_Simd_cmd [FAIL] [D:\j\workspace\x64_arm64_alt---85bca9a1\tests\runtest.proj]
18:14:18         
18:14:19 
        Assert failure(PID 9408 [0x000024c0], Thread: 9708 [0x25ec]): Assertion failed '(consume > 1) || (regType(store->gtOp1->TypeGet()) == regType(store->TypeGet()))' in 'Arm64intrisicsTest.Program:testThrowsPlatformNotSupported(ref,ref)' (IL size 73)
18:14:19         
18:14:19             File: d:\j\workspace\x64_arm64_alt---85bca9a1\src\jit\lsrabuild.cpp Line: 1383
18:14:19             Image: D:\j\workspace\x64_arm64_alt---85bca9a1\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\CoreRun.exe
18:14:19         
18:14:19         
18:14:19   
18:14:19   Return code:      1
18:14:19   Raw output file:      D:\j\workspace\x64_arm64_alt---85bca9a1\bin\tests\Windows_NT.x64.Checked\Reports\JIT.HardwareIntrinsics\Arm64\Simd\Simd.output.txt
18:14:19   Raw output:
18:14:19   BEGIN EXECUTION
18:14:19          "D:\j\workspace\x64_arm64_alt---85bca9a1\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" Simd.exe 
18:14:19         System.Runtime.Intrinsics.Arm.Arm64.Simd.IsSupported = False
18:14:19         Using default data set
18:14:19         Expected: 100
18:14:19         Actual: 123456789
18:14:19         END EXECUTION - FAILED
18:14:19         FAILED
18:14:19         Test Harness Exitcode is : 1
18:14:19         
18:14:19   To run the test:
18:14:19   > set CORE_ROOT=D:\j\workspace\x64_arm64_alt---85bca9a1\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
18:14:19   > D:\j\workspace\x64_arm64_alt---85bca9a1\bin\tests\Windows_NT.x64.Checked\JIT\HardwareIntrinsics\Arm64\Simd\Simd.cmd
18:14:19   
18:14:19         Expected: True
18:14:19         Actual:   False
18:14:19           D:\j\workspace\x64_arm64_alt---85bca9a1\bin\tests\Windows_NT.x64.Checked\TestWrappers\JIT.HardwareIntrinsics\JIT.HardwareIntrinsics.XUnitWrapper.cs(247,0): at JIT_HardwareIntrinsics._Arm64_Simd_Simd_._Arm64_Simd_Simd_cmd()
```

**Comment by sdmaclea** [comment]
The minopts jitStress ones are duplicates of #17111 

@debayang started looking at some of these last week.

**Comment by BruceForstall** [comment]
Closing as dup
