### ISSUE TITLE
[arm32/Windows] Test Failed: Failure in corefx System.Net.HttpListener.Tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17584]
Consistent failure in Windows arm32 corefx System.Net.HttpListener.Tests with COMPlus_JitStress=2:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_jitstress2_tst/10/consoleText

```
Running: C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Net.HttpListener.Tests\netcoreapp-Windows_NT-Release-arm\RunTests.cmd C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm
Using C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm as the test runtime folder.
Executing in C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Net.HttpListener.Tests\netcoreapp-Windows_NT-Release-arm\ 
----- start 23:44:22.99 ===============  To repro directly: ===================================================== 
pushd C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Net.HttpListener.Tests\netcoreapp-Windows_NT-Release-arm\
set COMPlus_JitStress=2
call C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe System.Net.HttpListener.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Net.HttpListener.Tests\netcoreapp-Windows_NT-Release-arm>set COMPlus_JitStress=2 

C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\tests\System.Net.HttpListener.Tests\netcoreapp-Windows_NT-Release-arm>call C:\Users\robox\j\workspace\arm_cross_che---6fedd1e9\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe System.Net.HttpListener.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.HttpListener.Tests
Discovered:  System.Net.HttpListener.Tests
Starting:    System.Net.HttpListener.Tests
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(274,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutNoStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   10485760
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(296,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetNoStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(285,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.IdleConnection_SetTimeoutAfterStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   10485760
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(308,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(229,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutNoStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.RequestQueue_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStop_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   10485760
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(330,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStop_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.RequestQueue_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(264,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.RequestQueue_SetTimeoutAfterStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.DrainEntityBody_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(190,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.DrainEntityBody_SetTimeoutNoStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(211,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutNoStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(222,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.EntityBody_SetTimeoutAfterStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.DrainEntityBody_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(201,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.DrainEntityBody_SetTimeoutAfterStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   300
      Stack Trace:
         D:\j\workspace\arm_cross_che---b006c545\_\fx\src\System.Net.HttpListener\tests\HttpListenerTimeoutManagerTests.cs(243,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.HeaderWait_SetTimeoutAfterStart_GetReturnsNewValue()
   System.Net.Tests.HttpListenerTimeoutManagerUnixTests.IdleConnection_Roundtrips [SKIP]
      Condition(s) not met: \"IsManagedImplementation\"
   System.Net.Tests.HttpListenerTimeoutManagerUnixTests.UnsupportedProperties_Throw [SKIP]
      Condition(s) not met: \"IsManagedImplementation\"
   System.Net.Tests.HttpListenerTimeoutManagerUnixTests.Properties_DefaultValues [SKIP]
      Condition(s) not met: \"IsManagedImplementation\"
   System.Net.Tests.HttpListenerTimeoutManagerUnixTests.DrainEntityBody_Roundtrips [SKIP]
      Condition(s) not met: \"IsManagedImplementation\"
Finished:    System.Net.HttpListener.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.HttpListener.Tests  Total: 661, Errors: 0, Failed: 13, Skipped: 4, Time: 52.882s
----- end 23:45:23.83 ----- exit code 1 ----------------------------------------------------------
COREFX TEST FAILED
```

**Comment by echesakovMSFT** [comment]
This issue is duplicate of #11408 and due to the following:

1. In [`System.Net.HttpListener:SetServerTimeout`](https://github.com/dotnet/corefx/blob/b399fe53343295ccf475262552b6d36beafb2b4e/src/System.Net.HttpListener/src/System/Net/Windows/HttpListener.Windows.cs#L123) under `COMPlus_JitStress=2` call to `System.Net.HttpListener.SetUrlGroupProperty` treated as "explicit" tail call;  
2. `System.Net.HttpListener.SetUrlGroupProperty` takes as an argument address of local variable `timeoutinfo` .

@RussKeldorph @BruceForstall What should be appropriate "fix" here? Disable System.Net.HttpListener.Tests for all JitStress modes?

/cc @dotnet/jit-contrib

**Comment by RussKeldorph** [comment]
@echesakovMSFT The right thing to do is to fix #11408 so that TailCallStress isn't creating illegal conditions.  Plumbing a way to disable the *corefx* test under JitStress/TailCallStress might be too much of a hack.  For now, it's probably best to disable it as best we can via mechanisms available in coreclr, such as disabling the entire test assembly, under only JitStress if possible.

I have moved #11408 into 2.2 in the hope of a proper fix.

**Comment by echesakovMSFT** [comment]
@BruceForstall has already disabled the test assembly in d3714249669

**Comment by sandreenko** [comment]
These tests fail on windows x86 as well ([example ](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstress2/670/testReport/junit/System.Net.Tests/)).

**Comment by VincentBu** [comment]
There are some issues due to same assertion:
https://mc.dot.net/#/user/coreclr-corefx-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190627.1/workItem/System.Net.HttpListener.Tests/analysis/xunit/System.Net.Tests.HttpListenerTimeoutManagerWindowsTests~2FDrainEntityBody_SetTimeoutAfterStart_GetReturnsNewValue

**Comment by VincentBu** [comment]
**Job:**
[coreclr-corefx-jitstress2-jitstressregs #20190915.1 Run Test Pri1 CoreFX Windows_NT x86 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=355675)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/5b1c2e88-53cf-4597-b5db-c55091dc81ad/workitems/System.Net.HttpListener.Tests/console

**OS & Arch:**
windows x86

**Mode:**
COMPlus_JitStress=2
COMPlus_JitStressRegs=1
COMPlus_TieredCompilation=0

**Log:**
```
System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStop_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 3
      Actual:   10485760
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(332,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStop_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetNoStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 3
      Actual:   10485760
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(298,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetNoStart_GetReturnsNewValue()
    System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStart_GetReturnsNewValue [FAIL]
      Assert.Equal() Failure
      Expected: 3
      Actual:   10485760
      Stack Trace:
        /_/src/System.Net.HttpListener/tests/HttpListenerTimeoutManagerTests.cs(308,0): at System.Net.Tests.HttpListenerTimeoutManagerWindowsTests.MinSendBytesPerSecond_SetAfterStart_GetReturnsNewValue()
```

**Comment by BruceForstall** [comment]
I'm going to close this. Please create a new bug if System.Net tests fail again.
