### ISSUE TITLE
 [x64/Ubuntu] Failures in tailcallstress job

### ISSUE THREAD

**Issue by erozenfeld** [dotnet/coreclr#17629]
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_tailcallstress_tst/323/consoleText

FAILED   - tracing/tracevalidation/tracelogging/tracelogging/tracelogging.sh
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_tailcallstress_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun tracelogging.exe
               
               Unhandled Exception: System.TypeLoadException: Could not find type Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses+ILToNativeMap
                  at FastSerialization.Deserializer.GetFactory(String fullName)
                  at FastSerialization.SerializationType.FastSerialization.IFastSerializable.FromStream(Deserializer deserializer)
                  at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
                  at FastSerialization.Deserializer.ReadObject()
                  at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
                  at FastSerialization.Deserializer.ReadObject()
                  at Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses.<>c__DisplayClass42_0.<FastSerialization.IFastSerializable.FromStream>b__0()
                  at FastSerialization.DeferedRegion.FinishReadHelper(Boolean preserveStreamPosition)
                  at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
                  at FastSerialization.Deserializer.ReadObject()
                  at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.FastSerialization.IFastSerializable.FromStream(Deserializer deserializer)
                  at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
                  at FastSerialization.Deserializer.GetEntryObject()
                  at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.InitializeFromFile(String etlxFilePath)
                  at Tracing.Tests.Common.EventSourceTestSuite.RunTests()
                  at Tracing.Tests.TraceLogging.Main(String[] args)
               ./tracelogging.sh: line 244: 64297 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED

FAILED   - tracing/eventsourcetrace/eventsourcetrace/eventsourcetrace.sh
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_tailcallstress_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun eventsourcetrace.exe
               	Start: Enable tracing.
               	End: Enable tracing.
               
               	Start: Messaging.
               	End: Messaging.
               
               	Start: Disable tracing.
               	End: Disable tracing.
               
               	Start: Processing events from file.
               
               Unhandled Exception: System.TypeLoadException: Could not find type Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses+ILToNativeMap
                  at FastSerialization.Deserializer.GetFactory(String fullName)
                  at FastSerialization.SerializationType.FastSerialization.IFastSerializable.FromStream(Deserializer deserializer)
                  at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
                  at FastSerialization.Deserializer.ReadObject()
                  at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
                  at FastSerialization.Deserializer.ReadObject()
                  at Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses.<>c__DisplayClass42_0.<FastSerialization.IFastSerializable.FromStream>b__0()
                  at FastSerialization.DeferedRegion.FinishReadHelper(Boolean preserveStreamPosition)
                  at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
                  at FastSerialization.Deserializer.ReadObject()
                  at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.FastSerialization.IFastSerializable.FromStream(Deserializer deserializer)
                  at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
                  at FastSerialization.Deserializer.GetEntryObject()
                  at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.InitializeFromFile(String etlxFilePath)
                  at Tracing.Tests.EventSourceTrace.Main(String[] args)
               ./eventsourcetrace.sh: line 244: 64063 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED

**Comment by RussKeldorph** [comment]
@brianrob I don't have the complete history, but I suspect these tests were failing in this scenario since they were added.  Are these tests perhaps sensitive to precise results from stack walks?  Tailcallstress might invalidate assumptions like that, among other things.

**Comment by brianrob** [comment]
These tests don't look at stacks, just at the event payloads themselves.  The exception above is a managed TypeLoadException, so I expect this is a functional issue unrelated to the contents of the trace.

The exception implies that the type ```Microsoft.Diagnostics.Tracing.Etlx.TraceCodeAddresses+ILToNativeMap``` can't be found.

**Comment by erozenfeld** [comment]
I investigated tracelogging. This test fails both on Windows and Ubuntu under tailcallstress with the same stack trace. For some reason we are not running it in Windows ci jobs.

I isolated a bad method. Setting tailcallstress just on this method makes the test fail.

.method assembly hidebysig instance class [System.Runtime]System.Type 
            '<InitializeFromFile>b__112_0'(string typeName) cil managed
    {
      // Code size       7 (0x7)
      .maxstack  8
      IL_0000:  ldarg.1
      IL_0001:  call       class [System.Runtime]System.Type [System.Runtime]System.Type::GetType(string)
      IL_0006:  ret
    } // end of method '<>c'::'<InitializeFromFile>b__112_0'

; Assembly listing for method <>c:<InitializeFromFile>b__112_0(ref):ref:this
; Emitting BLENDED_CODE for X64 CPU with AVX
; optimized code
; rsp based frame
; fully interruptible
; Final local variable assignments
;
;* V00 this         [V00    ] (  0,  0   )     ref  ->  zero-ref    this class-hnd
;  V01 arg1         [V01,T00] (  3,  3   )     ref  ->  rsi         class-hnd
;# V02 OutArgs      [V02    ] (  1,  1   )  lclBlk ( 0) [rsp+0x00]  
;
; Lcl frame size = 0

G_M38745_IG01:

G_M38745_IG02:
       488BFE               mov      rdi, rsi
       48B8A0F333B6FD7E0000 mov      rax, 0x7EFDB633F3A0

G_M38745_IG03:
       48FFE0               rex.jmp  rax

; Total bytes of code 16, prolog size 0 for method <>c:<InitializeFromFile>b__112_0(ref):ref:this
; ============================================================

I suspect the reason the test fails is because we are forcing a tail call on Type::GetType(string) that's marked with [System.Security.DynamicSecurityMethod] because of StackCrawlMark. Normally such methods are not inlined or tail-called. tailcallstress logic relies on verCheckTailCallConstraint to check the legality of turning a normal call into a tail-prefixed call, which doesn't call canTailCall on Jit-EE interface (which would return false in this case):

```
        // Methods with StackCrawlMark depend on finding their caller on the stack.
        // If we tail call one of these guys, they get confused.  For lack of
        // a better way of identifying them, we use DynamicSecurity attribute to identify
        // them. We have an assert in canInline that ensures all StackCrawlMark
        // methods are appropriately marked.
        //
        if ((pExactCallee != NULL) && IsMdRequireSecObject(pExactCallee->GetAttrs()))
        {
            result = false;
            szFailReason = "Callee might have a StackCrawlMark.LookForMyCaller";
            goto exit;
        }
```

**Comment by erozenfeld** [comment]
A later call to canTailCall returns true because the check for DynamicSecurityMethods in canTailCall above is only done when there is no explicit tail prefix. It's under
```
if (!fIsTailPrefix) 
```

**Comment by erozenfeld** [comment]
So the possible solutions here are:
1. Don't add tail prefix under TailCallStress if canTailCall() returns false. This will make the testing more robust but will reduce the number of tail calls.
2. Exclude this test from running under TailCallStress. We will likely have other cases like this in the future.

My preference is to go with option 1.
