### ISSUE TITLE
[arm32] corefx System.Net.NameResolution.Pal.Tests fails

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17740]
https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/3/consoleText

```
Running tests in /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Pal.Tests/netcoreapp-Linux-Release-arm
./RunTests.sh /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm

----- start 04:53:57 =============== To repro directly: =====================================================
pushd .
#!/usr/bin/env bash
chmod +x /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet xunit.console.netcore.exe System.Net.NameResolution.Pal.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Pal.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Pal.Tests/netcoreapp-Linux-Release-arm
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.NameResolution.Pal.Tests
Discovered:  System.Net.NameResolution.Pal.Tests
Starting:    System.Net.NameResolution.Pal.Tests
   System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetNameInfo_LocalHost_IPv6_TryGetAddrInfo [FAIL]
      Assert.Equal() Failure
      Expected: Success
      Actual:   HostNotFound
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs(161,0): at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetNameInfo_LocalHost_IPv6_TryGetAddrInfo()
   System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetNameInfo_LocalHost_IPv6 [FAIL]
      Assert.Equal() Failure
      Expected: Success
      Actual:   HostNotFound
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_prtest/_/fx/src/System.Net.NameResolution/tests/PalTests/NameResolutionPalTests.cs(77,0): at System.Net.NameResolution.PalTests.NameResolutionPalTests.TryGetNameInfo_LocalHost_IPv6()
Finished:    System.Net.NameResolution.Pal.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.NameResolution.Pal.Tests  Total: 10, Errors: 0, Failed: 2, Skipped: 0, Time: 4.381s
/ssd/j/workspace/dotnet_coreclr/dev_unix_test_workflow/jitstress/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Pal.Tests/netcoreapp-Linux-Release-arm
----- end 04:54:07 ----- exit code 1 ----------------------------------------------------------
```

**Comment by RussKeldorph** [comment]
This issue was moved to dotnet/corefx#29293
