### ISSUE TITLE
[arm32/Ubuntu][JitStressRegs] corefx System.Net.NameResolution.Functional.Tests failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17756]
With JitStressRegs=0x10,

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/1/consoleText

```
Running tests in /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm
timeout --kill-after=30s 10m ./RunTests.sh /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm

----- start 03:14:14 =============== To repro directly: =====================================================
pushd .
#!/usr/bin/env bash
export COMPlus_JitStressRegs=0x10
chmod +x /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet
/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm/dotnet xunit.console.netcore.exe System.Net.NameResolution.Functional.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================
/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.NameResolution.Functional.Tests
Discovered:  System.Net.NameResolution.Functional.Tests
Starting:    System.Net.NameResolution.Functional.Tests
   System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName [FAIL]
      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(32,0): at System.Net.Dns.GetHostByName(String hostName)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs(108,0): at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName()
   System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName [FAIL]
      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(208,0): at System.Net.Dns.ResolveCallback(Object context)
         --- End of stack trace from previous location where exception was thrown ---
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(358,0): at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(383,0): at System.Net.Dns.EndGetHostByName(IAsyncResult asyncResult)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs(117,0): at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName()
   System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_HostString_Ok(hostName: \"\") [FAIL]
      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(404,0): at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs(26,0): at System.Net.NameResolution.Tests.GetHostEntryTest.<>c__DisplayClass1_0.<Dns_GetHostEntry_HostString_Ok>b__0()
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs(38,0): at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc)
         --- End of stack trace from previous location where exception was thrown ---
   System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_HostString_Ok(hostName: \"\") [FAIL]
      System.AggregateException : One or more errors occurred. (One or more errors occurred. (No such device or address)) (One or more errors occurred. (No such device or address))
      ---- System.AggregateException : One or more errors occurred. (No such device or address)
      -------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
      ---- System.AggregateException : One or more errors occurred. (No such device or address)
      -------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : No such device or address
      Stack Trace:
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(90,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(52,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs(41,0): at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc)
         --- End of stack trace from previous location where exception was thrown ---
         ----- Inner Stack Trace #1 (System.AggregateException) -----
         
         ----- Inner Stack Trace -----
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(208,0): at System.Net.Dns.ResolveCallback(Object context)
         --- End of stack trace from previous location where exception was thrown ---
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(358,0): at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(500,0): at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(590,0): at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult)
            at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
         --- End of stack trace from previous location where exception was thrown ---
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(64,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
         ----- Inner Stack Trace #2 (System.AggregateException) -----
         
         ----- Inner Stack Trace -----
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(208,0): at System.Net.Dns.ResolveCallback(Object context)
         --- End of stack trace from previous location where exception was thrown ---
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(358,0): at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(500,0): at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_prtest/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(590,0): at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult)
            at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
Finished:    System.Net.NameResolution.Functional.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.NameResolution.Functional.Tests  Total: 57, Errors: 0, Failed: 4, Skipped: 0, Time: 8.016s
/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm
----- end 03:14:27 ----- exit code 1 ----------------------------------------------------------
Looking around for any Linux dump...
... found no dump in /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs0x10_tst_prtest/_/fx/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm
error: One or more tests failed while running tests from ''.  Exit code 1.
```

**Comment by BruceForstall** [comment]
When fixing this, update tests\arm\corefx_linux_test_exclusions.txt

**Comment by CarolEidt** [comment]
I was unable to repro this, and rerunning JitStressRegs=0x10 with the test re-enabled now passes.

**Comment by echesakovMSFT** [comment]
@BruceForstall @CarolEidt I saw this issue recently in https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_minopts_tst_prtest/10/consoleText
