### ISSUE TITLE
[arm/corefx] System.Tests.TypedReferenceTests.NegativeMakeTypedReference fails

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#17835]
[ci run](https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst/13/consoleText) shows:
```
Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests

Assert failure(PID 1708 [0x000006ac], Thread: 3612 [0x0e1c]): !"You cannot use this function for arbitrary value types. You must preallocate a box object and copy the value in yourself."

<no module>! <no symbol> + 0x0 (0x00000000)
    File: d:\j\workspace\arm_cross_che---99792267\src\vm\invokeutil.cpp Line: 693
    Image: C:\Users\robox\j\workspace\arm_cross_che---eb7b805d\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe
```

local runs fail with:
```
Z:\bin\tests\System.Runtime.Tests\netcoreapp-Windows_NT-Release-arm>call Z:\bin\testhost\netcoreapp-Windows_NT-Release-arm\dotnet.exe xunit.console.netcore.exe System.Runtime.Tests.dll -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -method System.Tests.TypedReferenceTests.NegativeMakeTypedReference
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests
   System.Tests.TypedReferenceTests.NegativeMakeTypedReference [FAIL]
      Assert.Equal() Failure
      Expected: (null)
      Actual:   flds
      Stack Trace:
         F:\git\corefx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(48,0): at System.AssertExtensions.Throws[T](String paramName, Action action)
         F:\git\corefx\src\System.Runtime\tests\System\TypedReferenceTests.cs(60,0): at System.Tests.TypedReferenceTests.NegativeMakeTypedReference()
Finished:    System.Runtime.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Tests  Total: 1, Errors: 0, Failed: 1, Skipped: 0, Time: 4.239s
```

link  https://github.com/dotnet/coreclr/issues/16001#issuecomment-385319873.

Probably it will fix #17585.

**Comment by sandreenko** [comment]
Yes, thanks Jan.
