### ISSUE TITLE
corefx test failures: assertion failed in System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Return

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#17862]
Several corefx tests are failing with:
```
  Assertion Failed
  
     at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Return(T[] array, Boolean clearArray)
     at System.Buffers.ArrayPool.Tests.ArrayPoolUnitTests.Renting0LengthArrayReturnsSingleton(ArrayPool`1 pool) in D:\j\workspace\x64_checked_w---d7295605\_\fx\src\System.Buffers\tests\ArrayPool\UnitTests.cs:line 107
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

also:
```
  Assertion Failed
  
     at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Return(T[] array, Boolean clearArray)
     at System.IO.Stream.Read(Span`1 buffer)
     at System.IO.Pipes.PipeStream.Read(Span`1 buffer) in D:\j\workspace\x64_checked_w---d7295605\_\fx\src\System.IO.Pipes\src\System\IO\Pipes\PipeStream.cs:line 140
     at System.IO.Pipes.Tests.PipeTest_Read.ReadWithZeroLengthBuffer_Span_Nop() in D:\j\workspace\x64_checked_w---d7295605\_\fx\src\System.IO.Pipes\tests\PipeTest.Read.netcoreapp.cs:line 41
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
     at System.IO.Pipes.Tests.PipeTest_Read.ReadWithZeroLengthBuffer_Span_Nop()
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

also:
```
  Assertion Failed
  
     at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Return(T[] array, Boolean clearArray)
     at System.IO.Stream.Read(Span`1 buffer)
     at System.Net.Http.Functional.Tests.HttpClientHandlerTest.<>c__DisplayClass84_0.<<ReadAsStreamAsync_HandlerProducesWellBehavedResponseStream>b__0>d.MoveNext() in D:\j\workspace\x64_checked_w---d7295605\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.cs:line 2009
```

there are more, all architecture, all platform.

(btw, the interleaved output in the Windows x64 run is really annoying...)

Example jobs:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_baseline_prtest/356/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_baseline_prtest/301/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm_cross_checked_ubuntu_corefx_baseline_tst_prtest/13/consoleText

This appears to be a regression.

@jkotas @stephentoub ideas?

**Comment by stephentoub** [comment]
There are no line numbers, but I expect it's due to this change that just got merged:
https://github.com/dotnet/coreclr/commit/d8f028d7a47e6e2872d733346509e3be1e64ceb4#diff-6ae774662dc637ecc68fd009d821ec8fR15
That assert should not be there, or it should be changed from `bufferSize > 0` to `bufferSize >= 0`, as a bufferSize of 0 is valid.
