### ISSUE TITLE
Reflection.Emit: ParameterBuilder.SetConstant throws ArgumentException for nullable enum parameters

### ISSUE THREAD

**Issue by stakx** [dotnet/coreclr#17893]
Say we want to emit the following type declaration using Reflection.Emit:

```
interface Type
{
```

The following program fails with an `ArgumentException`:

```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

class Program
{
    static void Main()
    {
        var parameterType = typeof(AttributeTargets?);
        var parameterDefaultValue = default(AttributeTargets);

        var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Assembly"), AssemblyBuilderAccess.Run);
        var moduleBuilder = assemblyBuilder.DefineDynamicModule("Module");
        var typeBuilder = moduleBuilder.DefineType("Type", TypeAttributes.Interface | TypeAttributes.Abstract);
        var methodBuilder = typeBuilder.DefineMethod("Method", MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.Abstract, typeof(void), new[] { parameterType });
        var parameterBuilder = methodBuilder.DefineParameter(1, ParameterAttributes.Optional, "arg");
        parameterBuilder.SetConstant(parameterDefaultValue);
    }
}
``` 

```
Unhandled Exception: System.ArgumentException: System.AttributeTargets is not a supported constant type.
   at System.Reflection.Emit.TypeBuilder.SetConstantValue(ModuleBuilder module, Int32 tk, Type destType, Object value)
   at Program.Main()
```

If the value of `parameterType` is changed from `typeof(AttributeTargets?)` to `typeof(AttributeTargets)`, the error does not occur. Given

**Comment by stakx** [comment]
The cause of this bug is in this method: https://github.com/dotnet/coreclr/blob/0ba6924dbc8477e4ecfbb8fd7793c2788bd48cd9/src/mscorlib/src/System/Reflection/Emit/TypeBuilder.cs#L291

And it could be fixed as follows:

```diff
             if (value != null)
             {
                 Type type = value.GetType();


                 // We should allow setting a constant value on a ByRef parameter
                 if (destType.IsByRef)
                     destType = destType.GetElementType();

+                if (destType.IsGenericType
+                    && destType.GetGenericTypeDefinition() == typeof(Nullable<>))
+                {
+                    destType = destType.GetGenericArguments()[0];
+                }

                 if (destType.IsEnum)
                 {
```

May I submit a PR for this?

**Comment by jkotas** [comment]
cc @AtsushiKan

**Comment by AtsushiKan** [comment]
Seems worth a PR. BTW, `Nullable.GetUnderlyingType()` will do both the "is this a `Nullable<T>` and if so, what's the `T`" check.
