### ISSUE TITLE
Reflection.Emit: Assertion failure in SignatureHelper.AddOneArgTypeHelper. Missing argument validation in public API?

### ISSUE THREAD

**Issue by stakx** [dotnet/coreclr#17986]
I've come across a failing `Debug.Assert` in System.Reflection.Emit, using an up-to-date debug build of System.Private.CoreLib. It's probably a fairly benign case, but since I don't know how much value you place on fixing something like this, I thought I'd report it. Suggestions on how to fix it at the end of this post.

We're talking about the second `Debug.Assert` here: https://github.com/dotnet/coreclr/blob/4c716dc92ccc3c22e175576af426a8a972401f07/src/System.Private.CoreLib/src/System/Reflection/Emit/SignatureHelper.cs#L286-L292

This code makes it fail:

```csharp
using System;
using System.Reflection;
using System.Reflection.Emit;

public interface IType
{
    T Method<T>();
}

class Program
{
    static void Main()
    {
        // The following code creates an implementation `class Type : IType`:
        var assemblyBuilder = AssemblyBuilder.DefineDynamicAssembly(new AssemblyName("Assembly"), AssemblyBuilderAccess.Run);
        var moduleBuilder = assemblyBuilder.DefineDynamicModule("Module");
        var typeBuilder = moduleBuilder.DefineType("Type", TypeAttributes.Class, typeof(object), new[] { typeof(IType) });
        var methodBuilder = typeBuilder.DefineMethod("Method", MethodAttributes.Public | MethodAttributes.Final | MethodAttributes.Virtual);
        var genericParamBuilder = methodBuilder.DefineGenericParameters("T")[0];

        methodBuilder.SetSignature(genericParamBuilder, Type.EmptyTypes, Type.EmptyTypes, null, null, null);
        //                         ^^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^
        //                  This combination of arguments is what will make the assertion fail.
        //                  Note that user code ought to pass `null` instead of empty arrays!

        // Generate method body corresponding to `return default(T)`:
        var il = methodBuilder.GetILGenerator();
        il.DeclareLocal(genericParamBuilder);
        il.Emit(OpCodes.Ldloca_S, 0);
        il.Emit(OpCodes.Initobj, genericParamBuilder);
        il.Emit(OpCodes.Ldloc_0);
        il.Emit(OpCodes.Ret);

        typeBuilder.DefineMethodOverride(methodBuilder, typeof(IType).GetMethod("Method")); // BOOM!

        var type = typeBuilder.CreateType();
    }
}
```

```
Assertion Failed

   at System.Reflection.Emit.SignatureHelper.AddOneArgTypeHelper(Type clsArgument, Type[] requiredCustomModifiers, Type[] optionalCustomModifiers) in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\SignatureHelper.cs:line 292
   at System.Reflection.Emit.SignatureHelper..ctor(Module mod, MdSigCallingConvention callingConvention, Int32 cGenericParameters, Type returnType, Type[] requiredCustomModifiers, Type[] optionalCustomModifiers) in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\SignatureHelper.cs:line 221
   at System.Reflection.Emit.SignatureHelper.GetMethodSigHelper(Module scope, CallingConventions callingConvention, Int32 cGenericParam, Type returnType, Type[] requiredReturnTypeCustomModifiers, Type[] optionalReturnTypeCustomModifiers, Type[] parameterTypes, Type[][] requiredParameterTypeCustomModifiers, Type[][] optionalParameterTypeCustomModifiers) in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\SignatureHelper.cs:line 83
   at System.Reflection.Emit.MethodBuilder.GetMethodSignature() in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\MethodBuilder.cs:line 378
   at System.Reflection.Emit.MethodBuilder.GetTokenNoLock() in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\MethodBuilder.cs:line 758
   at System.Reflection.Emit.MethodBuilder.GetToken() in ...\src\mscorlib\src\System\Reflection\Emit\MethodBuilder.cs:line 738
   at System.Reflection.Emit.MethodBuilder.get_MetadataTokenInternal() in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\MethodBuilder.cs:line 517
   at System.Reflection.Emit.ModuleBuilder.GetMethodTokenNoLock(MethodInfo method, Boolean getGenericTypeDefinition) in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\ModuleBuilder.cs:line 1215
   at System.Reflection.Emit.ModuleBuilder.GetMethodTokenInternal(MethodInfo method) in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\ModuleBuilder.cs:line 1192
   at System.Reflection.Emit.TypeBuilder.DefineMethodOverrideNoLock(MethodInfo methodInfoBody, MethodInfo methodInfoDeclaration) in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\TypeBuilder.cs:line 1322
   at System.Reflection.Emit.TypeBuilder.DefineMethodOverride(MethodInfo methodInfoBody, MethodInfo methodInfoDeclaration) in ...\coreclr\src\mscorlib\src\System\Reflection\Emit\TypeBuilder.cs:line 1301
   at Program.Main() in ...\Program.cs:line 34
```

The assertion failure happens in `AddOneArgTypeHelper` which is being called for the return type. It is triggered by the user code passing in empty arrays (`Type.EmptyTypes`) for the return type's modreqs and modopts instead of `null` (as it should according to the [documentation for `MethodBuilder.SetSignature`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.emit.methodbuilder.setsignature)).

It seems to me that instead of trusting user code to pass in `null` instead of empty arrays, `MethodBuilder.SetSignature` should actively check for empty arrays, and correct them.

**Comment by AtsushiKan** [comment]
I ran that code on NETFX (retail) and it seems to work - is the only issue the false assert? Or do we end up corrupting something downstream once we ignore the assert.

If user code can trigger an assert, that's a bug and we should fix it. It sounds like the assert is incorrectly written here.

**Comment by AtsushiKan** [comment]
Actually, I don't understand why it's even a problem to have custom modifiers for open-typed parameters...

**Comment by stakx** [comment]
> If user code can trigger an assert, that's a bug and we should fix it.

Agreed, that makes sense.

> Actually, I don't understand why it's even a problem to have custom modifiers for open-typed parameters...

That's the main reason why I've decided to raise this issue although it seems fairly benign in this particular case. Ive repeatedly stumbled upon code that separates out generics when dealing with signatures, as if generics and custom modifiers aren't allowed to go together. I'm not knowledgeable enough at this point to understand why that is.

Since the assertion in question is again trying to separate generics and custom modifiers, I thought someone should take a look that knows more about why it's required in the first place.

**Comment by AtsushiKan** [comment]
I don't know of any reason why generics and custom modifiers shouldn't combine. I do a deeper dive to see why that assert is there but right now, it looks really bogus.

**Comment by AtsushiKan** [comment]
This assert's been around since 2010 (can't find history before that) but I can't see any reason for it. I can add custom modifiers and it works fine. I'd say delete the assert.
