### ISSUE TITLE
[Arm64/Linux] Stabilize 2.2 SDK

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#18026]
#17933 will be fixed by #17991 

Using a variant of the patch in #17991, I was able to bootstrap build a linux-arm64 cli/sdk based on 2.1.300-rtm-008820.  To check stability, I tried to use it to build coreclr natively.

```
export COMPlus_ZapDisable=1
cd git/coreclr
git clean -x -d -f
export DotNetBootstrapCliTarPath=/home/sdmaclea/dotnetcli-2.1.300-rtm-008820-linux-arm64-qdt.tgz
./init-tools.sh
./build.sh -msbuildonunsupportedplatform -nopgooptimize
```

It is not clear to me why ZapDisable=1 is needed.  This could be due to a bug in the buildbootstrap script, my bootstrap build process, or in the usage of init-tools.sh with arm64.  I am assuming this is a side effect of the build bootstrap process.  

The build sequence above more often than not fails.  The typical failure looks a lot like the thread pool memory ordering race conditions fixed by #17567.  FYI @kouvel @stephentoub 

For instance
```
No antecedent was set for the ContinuationTaskFromTask.

   at System.Threading.Tasks.ContinuationTaskFromTask.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe()
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Object' to type 'System.Collections.Generic.List`1[System.Object]'.
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.Finish(Boolean userDelegateExecute)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe()
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```
```
Assertion Failed
Null action in InnerInvoke()

   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe()
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by kouvel** [comment]
CC @tarekgh

Not sure if `Task.FinishContinuations` can run concurrently, it looks like there is no check for the sentinel object in `RunContinuations`:
https://github.com/dotnet/coreclr/blob/f17770dd0318aa80fcd2a70288f097f2e05ba3bd/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs#L3241-L3242

Maybe that is covered in some other way using state changes, etc.

**Comment by stephentoub** [comment]
> Maybe that is covered in some other way using state changes

Right.  It should never be the case that FinishContinuations is called multiple times on the same task; only the code that transitions the task to completed invokes that.

**Comment by sdmaclea** [comment]
2.2 SDK is now being built.  I'll take a look at it.

**Comment by BruceForstall** [comment]
@sdmaclea Have you had a chance to look? Is this issue still needed?

**Comment by sdmaclea** [comment]
Last I checked, this issue was still needed.  Sounds like 2.2 will be based off 2.1 branch, so maybe 3.0 is more likely to get this fixed.

**Comment by sdmaclea** [comment]
@richlander We briefly discussed this last week when I was in Redmond.  This was the issue which is making the arm64 CLI unstable on multicore targets.  When I set the thread affinity so that it ran only on one core, the CLI seemed reasonably stable.
