### ISSUE TITLE
[InvalidCastException] within System.Private.CoreLib causing slow load times 

### ISSUE THREAD

**Issue by saluton-mundo** [dotnet/coreclr#18197]
Hi, 

Not sure what is going on with this, however, cranking up the verbosity of output in VS 2017 we noticed slow page load times across the board because of this:

![image](https://user-images.githubusercontent.com/7760994/40733034-a8d8eb18-642c-11e8-8aac-de7f69050990.png)

Project is targeting .NET Core 2.0 and has the following referenced: 

![image](https://user-images.githubusercontent.com/7760994/40733146-e4bb379e-642c-11e8-9c15-175dc4cfa6ce.png)

**Comment by 0xd4d** [comment]
Break on InvalidCastException (see the exception window) and check the call stack. You can also right click anywhere in the call stack window and enable 'show parameter values'

**Comment by saluton-mundo** [comment]
System.FormatException: Unrecognized Guid format.
   at System.Guid.GuidResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument, String failureArgumentName, Exception innerException)
   at System.Guid.TryParseGuid(String g, GuidStyles flags, GuidResult& result)
   at System.Guid..ctor(String g)
   at System.ComponentModel.GuidConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)

**Comment by saluton-mundo** [comment]
I've found that it is a data problem with a Guid coming out in the wrong format from the MySQL database. The InvalidCastException came later on and masked the real problem. Thanks for the advice @0xd4d
