### ISSUE TITLE
Number.FormatFixed throws IndexOutOfRangeException if NumberGroupSizes is empty

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#18218]
The following code crashes on .NET Core (2.1-300) but works on .NET4.x and Mono
(we have it as a test in mono)
```
var nfi = NumberFormatInfo.InvariantInfo.Clone() as NumberFormatInfo;
nfi.NumberGroupSizes = new int[] { };
var str = Int32.MinValue.ToString("N1", nfi);
```
Stacktrace:
```
Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Number.FormatFixed(ValueStringBuilder& sb, NumberBuffer& number, Int32 nMinDigits, Int32 nMaxDigits, NumberFormatInfo info, Int32[] groupDigits, String sDecimal, String sGroup)
   at System.Number.FormatNumber(ValueStringBuilder& sb, NumberBuffer& number, Int32 nMinDigits, Int32 nMaxDigits, NumberFormatInfo info)
   at System.Number.FormatInt32(Int32 value, ReadOnlySpan`1 format, IFormatProvider provider)
   at System.Int32.ToString(String format, IFormatProvider provider)
   at ConsoleApp2.Program.Main(String[] args) in Program.cs:line 12
```

**Comment by stephentoub** [comment]
This looks like a regression from .NET Core 2.0 to 2.1.  I'll take a look...
