### ISSUE TITLE
Exception when trying to GCHandle.Alloc(new ValueTuple[1], GCHandleType.Pinned)

### ISSUE THREAD

**Issue by voinokin** [dotnet/coreclr#18244]
I'm getting exception when I try to pin array of `ValueTuple`s using this statement with .NET Core 2.1 release:

> GCHandle.Alloc(new ValueTuple<ulong, ulong>[1], GCHandleType.Pinned)

The exception tells:
> System.ArgumentException
>   HResult=0x80070057
>   Message=Object contains non-primitive or non-blittable data.
>   Source=System.Private.CoreLib
>   StackTrace:
>    at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
>    at System.Runtime.InteropServices.GCHandle.Alloc(Object value, GCHandleType type) in E:\A\_work\31\s\src\mscorlib\src\System\Runtime\InteropServices\GcHandle.cs:line 94

**Comment by 0xd4d** [comment]
It's because it has StructLayout = LayoutKind.Auto.

```
// Summary:
//     The runtime automatically chooses an appropriate layout for the members of an
//     object in unmanaged memory. Objects defined with this enumeration member cannot
//     be exposed outside of managed code. Attempting to do so generates an exception.
Auto = 3
```

**Comment by voinokin** [comment]
Although the workaround is obvious (just create own struct type instead of using the `ValueTuple<>`), I believe the message could state the reason that is easier to understand :-)
Anyway, thanks for explanation!
