### ISSUE TITLE
SUSE dotnet 2.0.3 Description: Infinite recursion during resource lookup within System.Private.CoreLib.

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/coreclr#18446]
@iga1976 commented on [Tue Jun 12 2018](https://github.com/dotnet/core/issues/1687)

SUSE dotnet 2.0.3 Description: Infinite recursion during resource lookup within System.Private.CoreLib. This may be a bug in System.Private.CoreLib, or potentially in certain extensibility points such as assembly resolve events or CultureInfo names. Resource name: ArgumentNull_Generic 
https://github.com/dotnet/corefx/issues/30208

**Comment by Petermarcu** [comment]
We're probably going to need a repro code snippet or something so we can reproduce this and get to the bottom of it.

**Comment by tarekgh** [comment]
@kouvel Kount Veluri FTE @jeffschwMSFT Jeff Schwartz FTE @tommcdon Tom McDonald FTE

could you please help with this issue? this is the issue that @kouvel Kount Veluri FTE fixed dotnet/coreclr#12668 for 2.0.3 but people running into it. Although they have installed dotnet 2.0.3, maybe they are not targeting this version which has the fix? would be nice if you can help narrow down the problem.

   at System.SR.InternalGetResourceString(String key)
   at System.SR.GetResourceString(String resourceKey, String defaultString)
   at System.ArgumentNullException..ctor(String paramName)
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Assembly assembly)
   at System.Reflection.Assembly.LoadFromResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalGetSatelliteAssembly(String name, CultureInfo culture, Version version, Boolean throwOnFileNotFound, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(CultureInfo lookForCulture, StackCrawlMark& stackMark)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at System.SR.InternalGetResourceString(String key)

**Comment by jeffschwMSFT** [comment]
@iga1976 do you have a small repro?

**Comment by tarekgh** [comment]
@jeffschwMSFT a sample repro is here https://github.com/dotnet/coreclr/issues/12668#issuecomment-317055454 

I want to point at @kouvel already fixed this issue and the fix supposes to be in 2.0.3 so my guess the problem here is @iga1976 has 2.0.3 but his app is targetting the previous version which not have the fix. it will be nice if @iga1976 run the following command and get the output and share his repro too.

```
dotnet --info
```
