### ISSUE TITLE
Setting up CoreCLR and CoreFX on Ubuntu 14.04

### ISSUE THREAD

**Issue by IanFoote** [dotnet/coreclr#1847]
I'm trying to get CoreCLR and CoreFX up and running on an Ubuntu 14.04 machine.

Everything seems to have built correctly, but when I try to run a program with it, I get the following error:

> ./corerun HelloWorld.exe
> 
> Assert failure(PID 6093 [0x000017cd], Thread: 6093 [0x17cd]): !"Recursion in >CLRException::GetThrowable"
>    File: /home/ubuntu/git/coreclr/src/vm/clrex.cpp Line: 150
>    Image: /home/ubuntu/coreclr-demo/runtime/corerun
> 
> ***\* MessageBox invoked, title 'corerun - Assert Failure (PID 6093, Thread 6093/0x17cd)' ****
>  !"Recursion in CLRException::GetThrowable"
> 
> /home/ubuntu/git/coreclr/src/vm/clrex.cpp, Line: 150

These are the steps I used to set everything up:

1) Set up toolchain:

```
echo "deb http://llvm.org/apt/trusty/ llvm-toolchain-trusty-3.6 main" | sudo tee /etc/apt/sources.list.d/llvm.list
wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install cmake llvm-3.5 clang-3.5 lldb-3.6 lldb-3.6-dev libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev uuid-dev
```

2) Set up repos:

```
sudo apt-get install git
mkdir ~/git
mkdir ~/git/coreclr
mkdir ~/git/corefx
cd ~/git
git clone https://github.com/dotnet/coreclr.git
git clone https://github.com/dotnet/corefx.git
```

3) Install Mono:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo apt-get update
sudo apt-get install mono-devel
```

4) Build CoreCLR:

```
cd ~/git/coreclr
./build.sh
```

5) Set up directory for runtime and copy files

```
mkdir -p ~/coreclr-demo/runtime
cp ~/git/coreclr/bin/Product/Linux.x64.Debug/corerun ~/coreclr-demo/runtime
cp ~/git/coreclr/bin/Product/Linux.x64.Debug/libcoreclr.so ~/coreclr-demo/runtime
cp ~/git/coreclr/bin/Product/Linux.x64.Debug/mscorlib.dll ~/coreclr-demo/runtime
```

6) Build Framework

```
echo "deb http://jenkins.mono-project.com/repo/debian sid main" | sudo tee /etc/apt/sources.list.d/mono-jenkins.list
sudo apt-get update
sudo apt-get install mono-snapshot-latest referenceassemblies-pcl
sudo apt-get install libcurl4-openssl-dev
mozroots --import --sync
cd ~/git/corefx
./build.sh

cp ~/git/corefx/bin/Linux.x64.Debug/Native/*.so ~/coreclr-demo/runtime
cp ~/git/corefx/bin/Linux.AnyCPU.Debug/System.Console/System.Console.dll ~/coreclr-demo/runtime
cp ~/git/corefx/bin/Linux.AnyCPU.Debug/System.Diagnostics.Debug/System.Diagnostics.Debug.dll ~/coreclr-demo/runtime
```

7) Download Dependencies:

```
mkdir ~/coreclr-demo/packages
cd ~/coreclr-demo/packages
curl -L -O https://nuget.org/nuget.exe

nano packages.config
```

PASTE THE FOLLOWING INTO THE NEW PACKAGES.CONFIG FILE:

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="System.Console" version="4.0.0-beta-22703" />
  <package id="System.Diagnostics.Contracts" version="4.0.0-beta-22703" />
  <package id="System.Diagnostics.Debug" version="4.0.10-beta-22703" />
  <package id="System.Diagnostics.Tools" version="4.0.0-beta-22703" />
  <package id="System.Globalization" version="4.0.10-beta-22703" />
  <package id="System.IO" version="4.0.10-beta-22703" />
  <package id="System.IO.FileSystem.Primitives" version="4.0.0-beta-22703"/>
  <package id="System.Reflection" version="4.0.10-beta-22703" />
  <package id="System.Resources.ResourceManager" version="4.0.0-beta-22703"/>
  <package id="System.Runtime" version="4.0.20-beta-22703" />
  <package id="System.Runtime.Extensions" version="4.0.10-beta-22703" />
  <package id="System.Runtime.Handles" version="4.0.0-beta-22703" />
  <package id="System.Runtime.InteropServices" version="4.0.20-beta-22703"/>
  <package id="System.Text.Encoding" version="4.0.10-beta-22703" />
  <package id="System.Text.Encoding.Extensions" version="4.0.10-beta-22703"/>
  <package id="System.Threading" version="4.0.10-beta-22703" />
  <package id="System.Threading.Tasks" version="4.0.10-beta-22703" />
</packages>

mono nuget.exe restore -Source https://www.myget.org/F/dotnet-corefx/ -PackagesDirectory .
find . -wholename '*/aspnetcore50/*.dll' -exec cp -n {} ~/coreclr-demo/runtime \;
```

8) Compile a test app:

```
cd ~/coreclr-demo/runtime
curl -O https://raw.githubusercontent.com/dotnet/corefxlab/master/demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs
mcs /nostdlib /noconfig /r:../packages/System.Console.4.0.0-beta-22703/lib/contract/System.Console.dll /r:../packages/System.Runtime.4.0.20-beta-22703/lib/contract/System.Runtime.dll HelloWorld.cs
```

9) Run the app:

```
./corerun HelloWorld.exe
```

What should I be doing differently to get this working?

**Comment by rambocoder** [comment]
Try ``./corerun HelloWorld.exe linux``

**Comment by IanFoote** [comment]
I tried that... no change whatsoever.

**Comment by janvorli** [comment]
You are missing System.Globalization.Native.so in the folder where you have managed assemblies, libcoreclr.so, etc.

**Comment by IanFoote** [comment]
Thank you.  I am now seeing the "Hello, Linux..." output as expected, although the demo application is still crashing with the following error:

./corerun HelloWorld.exe linux
Hello, Linux...

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. The system cannot find the file specified.

   at System.Console.get_IsOutputRedirected()
   at System.ConsolePal.ResetColor()
   at System.Console.ResetColor()
   at Program.DrawLinux()
   at Program.Main(String[] args)
Aborted (core dumped)

**Comment by ellismg** [comment]
Sadly that document is pretty out of date (it uses our old packages which which were not cross platform, have not been updated in a while, etc).  I am going to try to update it to take into account the new packages, but it will probably not happen for a few days.

**Comment by danmosemsft** [comment]
I think this is not needed anymore.
