### ISSUE TITLE
Possible JIT \ cross-gen bug in xplat in 2.2.0-preview1-26614-02 of shared runtime

### ISSUE THREAD

**Issue by pranavkm** [dotnet/coreclr#18525]
We started seeing errors during runtime Razor view compilation once we upgraded to build `2.2.0-preview1-26614-02` of Microsoft.NETCore.App. Downgrading to `2.2.0-preview1-26612-04` resolves this error. We're targeting the RTM (2.8.0) version of Roslyn that hasn't changed for a while now.

Builds with failures:: 
https://ci3.dot.net/job/aspnet_Mvc/job/dev/job/osx-Configuration_Release_prtest/319/console
https://ci3.dot.net/job/aspnet_Mvc/job/dev/job/linux-Configuration_Release_prtest/323/console

The error stack trace:

```
08:59:23    System.IndexOutOfRangeException : Index was outside the bounds of the array.
08:59:23   Stack Trace:
08:59:23      at Microsoft.CodeAnalysis.CodeGen.SwitchIntegralJumpTableEmitter.SwitchBucket.MergeIsAdvantageous(SwitchBucket bucket1, SwitchBucket bucket2) in /_/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.SwitchBucket.cs:line 282
08:59:23      at Microsoft.CodeAnalysis.CodeGen.SwitchIntegralJumpTableEmitter.GenerateSwitchBuckets(Int32 startLabelIndex, Int32 endLabelIndex) in /_/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs:line 200
08:59:23      at Microsoft.CodeAnalysis.CodeGen.SwitchIntegralJumpTableEmitter.EmitJumpTable() in /_/src/Compilers/Core/Portable/CodeGen/SwitchIntegralJumpTableEmitter.cs:line 125
08:59:23      at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSwitchHeader(BoundSwitchStatement switchStatement, BoundExpression expression, KeyValuePair`2[] switchCaseLabels, LabelSymbol fallThroughLabel) in /_/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 1174
08:59:23      at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitSwitchStatement(BoundSwitchStatement switchStatement) in /_/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 1113
08:59:23      at Microsoft.CodeAnalysis.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement statement) in /_/src/Compilers/CSharp/Portable/CodeGen/EmitStatement.cs:line 73
```

We've usually seen these sort of errors on account due to bugs in cross-gen \ JIT.

**Comment by jkotas** [comment]
We had a bad regressions in the JIT last week (#18483) that is likely causing this. @pranavkm Could you please check whether this still repros with newer builds that include this fix?

**Comment by ajaybhargavb** [comment]
I just upgraded to `2.2.0-preview1-26618-02` and this issue seems to be fixed. This issue can be closed.
