### ISSUE TITLE
System.Security.Principal.Tests Failure

### ISSUE THREAD

**Issue by A-And** [dotnet/coreclr#18701]
The following error is hit when running System.Security.Principal.Tests - this also crashes the .NET Core Host running the XUnit runner. 
There is a substantial number of tests, which fail with `ObjectDisposedException`
```

Test:
Error:
    System.ObjectDisposedException: Safe handle has been closed
       at System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
       at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
       at Interop.Advapi32.ImpersonateLoggedOnUser(SafeAccessTokenHandle userToken)
       at System.Security.Principal.WindowsIdentity.CurrentImpersonatedTokenChanged(AsyncLocalValueChangedArgs`1 args)
       at System.Threading.AsyncLocal`1.System.Threading.IAsyncLocal.OnValueChanged(Object previousValueObj, Object currentValueObj, Boolean contextChanged)
       at System.Threading.ExecutionContext.OnValuesChanged(ExecutionContext previousExecutionCtx, ExecutionContext nextExecutionCtx)
```

### To reproduce failing 

1. `build x64 [release/debug] skiptests`
2. `.\build-test.cmd x64 [release/debug] buildtesthostonly`
3. Navigate to `<repo-root>\bin\tests\<Configuration>\CoreFX\tests_downloaded\System.Security.Principal.Tests`
4. Run `<repo-root>\bin\tests\<Configuration>\testhost\dotnet.exe .\xunit.console.netcore.exe .\System.Security.Principal.Tests.dll `

**Comment by A-And** [comment]
Fixed with #18760
