### ISSUE TITLE
[Windows/arm64] corefx System.Runtime.Tests test failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#18914]
Happens in baseline and all JIT stress runs.

```
----- start 17:45:13.31 ===============  To repro directly: ===================================================== 
pushd C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\tests\System.Runtime.Tests\netcoreapp-Windows_NT-Release-arm64\
set COMPlus_TieredCompilation=0
call C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm64\dotnet.exe xunit.console.netcore.exe System.Runtime.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================

C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\tests\System.Runtime.Tests\netcoreapp-Windows_NT-Release-arm64>set COMPlus_TieredCompilation=0 

C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\tests\System.Runtime.Tests\netcoreapp-Windows_NT-Release-arm64>call C:\Users\robox\j\workspace\arm64_cross_c---c55e6c4b\_\fx\bin\testhost\netcoreapp-Windows_NT-Release-arm64\dotnet.exe xunit.console.netcore.exe System.Runtime.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapptests -notrait category=nonwindowstests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing 
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Tests
Discovered:  System.Runtime.Tests
Starting:    System.Runtime.Tests
   System.Tests.EnumTests.GetName(enumType: typeof(System.UInt32Enum), value: 4294967295, expected: \"Max\") [FAIL]
      Assert.Equal() Failure
      Expected: Max
      Actual:   (null)
      Stack Trace:
         D:\j\workspace\arm64_cross_c---999e2d10\_\fx\src\System.Runtime\tests\System\EnumTests.cs(315,0): at System.Tests.EnumTests.GetName(Type enumType, Object value, String expected)
   System.Tests.EnumTests.GetName(enumType: typeof(System.UInt32Enum), value: 4294967295, expected: \"Max\") [FAIL]
      Assert.Equal() Failure
      Expected: Max
      Actual:   (null)
      Stack Trace:
         D:\j\workspace\arm64_cross_c---999e2d10\_\fx\src\System.Runtime\tests\System\EnumTests.cs(315,0): at System.Tests.EnumTests.GetName(Type enumType, Object value, String expected)
   System.Tests.EnumTests.ToString_Format(e: 4294967295, format: \"F\", expected: \"Max\") [FAIL]
      Assert.Equal() Failure
                ↓ (pos 0)
      Expected: Max
      Actual:   4294967295
                ↑ (pos 0)
      Stack Trace:
         D:\j\workspace\arm64_cross_c---999e2d10\_\fx\src\System.Runtime\tests\System\EnumTests.cs(1471,0): at System.Tests.EnumTests.ToString_Format(Enum e, String format, String expected)
   System.Tests.EnumTests.ToString_Format(e: 4294967295, format: \"G\", expected: \"Max\") [FAIL]
      Assert.Equal() Failure
                ↓ (pos 0)
      Expected: Max
      Actual:   4294967295
                ↑ (pos 0)
      Stack Trace:
         D:\j\workspace\arm64_cross_c---999e2d10\_\fx\src\System.Runtime\tests\System\EnumTests.cs(1463,0): at System.Tests.EnumTests.ToString_Format(Enum e, String format, String expected)
WARNING: System.Tests.DecimalTests+BigIntegerMod.Test is running for 333s.
Finished:    System.Runtime.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Tests  Total: 16388, Errors: 0, Failed: 4, Skipped: 0, Time: 366.937s
----- end 17:53:31.00 ----- exit code 1 ----------------------------------------------------------
```

e.g., https://ci.dot.net/job/dotnet_coreclr/job/dev_unix_test_workflow/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_baseline_tst_prtest/3/consoleText

**Comment by sandreenko** [comment]
Now it fails with #23444.
