### ISSUE TITLE
Interop\COM\NETClients\Primitives\NETClientPrimitives fails on r2r and some jitstress jobs

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#19164]
- See PR https://github.com/dotnet/coreclr/pull/19122
- Example: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_windows_nt_r2r_prtest/70/

```
10:12:11          "D:\j\workspace\x64_checked_w---962da9ce\tests\..\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" NETClientPrimitives.exe 
10:12:11         Numeric RNG seed: 37
10:12:11         Test Failure: System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {53169A33-E85D-4E3C-B668-24E438D0929B} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
10:12:11 
      Interop_COM._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd [FAIL]
10:12:11            at NetClient.NumericTests..ctor(Int32 seed) in D:\j\workspace\x64_checked_w---962da9ce\tests\src\Interop\COM\NETClients\Primitives\NumericTests.cs:line 22
10:12:11            at NetClient.Program.Main(String[] doNotUse) in D:\j\workspace\x64_checked_w---962da9ce\tests\src\Interop\COM\NETClients\Primitives\Program.cs:line 15
10:12:11         Expected: 100
10:12:11         Actual: 101
10:12:11         END EXECUTION - FAILED
10:12:11         FAILED
10:12:11         Test Harness Exitcode is : 1
10:12:11         
10:12:11   To run the test:
10:12:11   > set CORE_ROOT=D:\j\workspace\x64_checked_w---962da9ce\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
10:12:11   > D:\j\workspace\x64_checked_w---962da9ce\bin\tests\Windows_NT.x64.Checked\Interop\COM\NETClients\Primitives\NETClientPrimitives\NETClientPrimitives.cmd
10:12:11   
10:12:11         Expected: True
10:12:11         Actual:   False
10:12:11         Stack Trace:
10:12:11           D:\j\workspace\x64_checked_w---962da9ce\bin\tests\Windows_NT.x64.Checked\TestWrappers\Interop.COM\Interop.COM.XUnitWrapper.cs(109,0): at Interop_COM._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd()
```

Failed in the following jobs:
```
Windows_NT x64 Checked R2R Build & Test
Windows_NT x64 Checked R2R jitstress1 Build & Test
Windows_NT x64 Checked R2R jitstress1_tiered Build & Test
Windows_NT x64 Checked R2R jitstress2 Build & Test
Windows_NT x64 Checked R2R jitstress2_tiered Build & Test
Windows_NT x64 Checked R2R no_tiered_compilation Build & Test
Windows_NT x64_arm64_altjit Checked jitstress1
Windows_NT x64_arm64_altjit Checked jitstress1_tiered
Windows_NT x64_arm64_altjit Checked jitstress2
Windows_NT x64_arm64_altjit Checked jitstress2_tiered
Windows_NT x64_arm64_altjit Checked r2r
Windows_NT x64_arm64_altjit Checked r2r_jitstress1
Windows_NT x64_arm64_altjit Checked r2r_jitstress1_tiered
Windows_NT x64_arm64_altjit Checked r2r_jitstress2
Windows_NT x64_arm64_altjit Checked r2r_jitstress2_tiered
Windows_NT x64_arm64_altjit Checked r2r_no_tiered_compilation
Windows_NT x86 Checked R2R Build & Test
Windows_NT x86 Checked R2R jitstress1 Build & Test
Windows_NT x86 Checked R2R jitstress1_tiered Build & Test
Windows_NT x86 Checked R2R jitstress2 Build & Test
Windows_NT x86 Checked R2R jitstress2_tiered Build & Test
Windows_NT x86 Checked R2R no_tiered_compilation Build & Test
Windows_NT x86_arm_altjit Checked r2r
Windows_NT x86_arm_altjit Checked r2r_jitstress1
Windows_NT x86_arm_altjit Checked r2r_jitstress1_tiered
Windows_NT x86_arm_altjit Checked r2r_jitstress2
```

@AaronRobinsonMSFT, this test did not seem to get disabled in these jobs by https://github.com/dotnet/coreclr/pull/19047, though I'm not sure if it's related.

@BruceForstall, is there something special about the r2r and jitstress jobs, do they run in a particular mode? Is there a way to disable a test from those jobs?

**Comment by BruceForstall** [comment]
The R2R jobs first crossgen all the framework assemblies, then for each test run "crossgen" on the test before running it. For the tests, this is determined by the `RunCrossGen` variable in the test wrapper (e.g., TryCatch.cmd).

I don't think we have a way to exclude a test from just the R2R jobs.

**Comment by kouvel** [comment]
Oh ok, just for my curiosity, which script that does the crossgen'ning?

Otherwise I'm not sure why the test would fail based on the r2r mode, as considering its history it's only known to fail on Windows Nano.

**Comment by kouvel** [comment]
I see, missed that, thanks!

**Comment by AaronRobinsonMSFT** [comment]
@jashook Did I add this to the `issues.targets` correctly? I thought this was supposed to disable this everywhere in Helix?

**Comment by BruceForstall** [comment]
Note: this test was disabled by https://github.com/dotnet/coreclr/pull/19294 (for basically all scenarios). Please re-enable as appropriate, when fixed for these and other scenarios.

**Comment by AaronRobinsonMSFT** [comment]
I am re-enabling these tests with #20621. If we continue to see failures I will investigate.
