### ISSUE TITLE
r2rdump test failure: FileNotFoundException HelloWorld.xml

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#19285]
Looks like the x64 release build has been failing with this problem for a while.

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/release_windows_nt/

```
      readytorun_r2rdump._R2RDumpTest_R2RDumpTest_._R2RDumpTest_R2RDumpTest_cmd [FAIL]
15:43:51         
15:43:51   Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'D:\j\workspace\release_windo---dfb17e42\bin\tests\Windows_NT.x64.Release\readytorun\r2rdump\R2RDumpTest\HelloWorld.xml'.
15:43:51            at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
15:43:51            at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
15:43:51            at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
15:43:51            at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy) in E:\A\_work\5\s\corefx\src\System.Private.Xml\src\System\Xml\XmlDownloadManager.cs:line 27
15:43:51            at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn) in E:\A\_work\5\s\corefx\src\System.Private.Xml\src\System\Xml\XmlUrlResolver.cs:line 66
15:43:51            at System.Xml.XmlTextReaderImpl.OpenUrl() in E:\A\_work\5\s\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs:line 3087
15:43:51            at System.Xml.XmlTextReaderImpl.Read() in E:\A\_work\5\s\corefx\src\System.Private.Xml\src\System\Xml\Core\XmlTextReaderImpl.cs:line 1206
15:43:51            at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace) in E:\A\_work\5\s\corefx\src\System.Private.Xml\src\System\Xml\Dom\XmlLoader.cs:line 50
15:43:51            at System.Xml.XmlDocument.Load(XmlReader reader) in E:\A\_work\5\s\corefx\src\System.Private.Xml\src\System\Xml\Dom\XmlDocument.cs:line 1336
15:43:51            at System.Xml.XmlDocument.Load(String filename) in E:\A\_work\5\s\corefx\src\System.Private.Xml\src\System\Xml\Dom\XmlDocument.cs:line 1288
15:43:51            at R2RDumpTest.TestHelpers.RunTest(String name) in D:\j\workspace\release_windo---dfb17e42\tests\src\readytorun\r2rdump\TestHelpers.cs:line 20
15:43:51            at R2RDumpTest.BasicTests.Main(String[] args) in D:\j\workspace\release_windo---dfb17e42\tests\src\readytorun\r2rdump\BasicTests.cs:line 16
15:43:51   
15:43:51   
15:43:51   Return code:      1
15:43:51   Raw output file:      D:\j\workspace\release_windo---dfb17e42\bin\tests\Windows_NT.x64.Release\Reports\readytorun.r2rdump\R2RDumpTest\R2RDumpTest.output.txt
15:43:51   Raw output:
15:43:51   BEGIN EXECUTION
15:43:51         The system cannot find the path specified.
15:43:51         Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
15:43:51         Copyright (c) Microsoft Corporation.  All rights reserved.
15:43:51         
15:43:51         Native image HelloWorld.ni.dll generated successfully.
15:43:51         Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
15:43:51         Copyright (c) Microsoft Corporation.  All rights reserved.
15:43:51         
15:43:51         Native image GcInfoTransitions.ni.dll generated successfully.
15:43:51         Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
15:43:51         Copyright (c) Microsoft Corporation.  All rights reserved.
15:43:51         
15:43:51         Native image GenericFunctions.ni.dll generated successfully.
15:43:51         Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
15:43:51         Copyright (c) Microsoft Corporation.  All rights reserved.
15:43:51         
15:43:51         Native image MultipleRuntimeFunctions.ni.dll generated successfully.
15:43:51          "D:\j\workspace\release_windo---dfb17e42\tests\..\bin\tests\Windows_NT.x64.Release\Tests\Core_Root\corerun.exe" R2RDumpTest.exe 
15:43:51         Starting the test
15:43:51         Expected: 100
15:43:51         Actual: -532462766
15:43:51         END EXECUTION - FAILED
15:43:51         FAILED
15:43:51         Test Harness Exitcode is : 1
15:43:51         
15:43:51   To run the test:
15:43:51   > set CORE_ROOT=D:\j\workspace\release_windo---dfb17e42\bin\tests\Windows_NT.x64.Release\Tests\Core_Root
15:43:51   > D:\j\workspace\release_windo---dfb17e42\bin\tests\Windows_NT.x64.Release\readytorun\r2rdump\R2RDumpTest\R2RDumpTest.cmd
15:43:51   
15:43:51         Expected: True
15:43:51         Actual:   False
```

@acmyu @nattress

**Comment by BruceForstall** [comment]
Dup of https://github.com/dotnet/coreclr/issues/19277
