### ISSUE TITLE
[Linux/arm64] System.Collections.Tests Generic.Dictionary.DictionaryConcurrentAccessDetectionTests Failure

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#20208]
**COMPlus_JitStress=2 COMPlus_TieredCompilation=1**

```
/home/robox/echesako/git/coreclr/_/fx/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet xunit.console.dll System.Collections.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -parallel none -class Generic.Dictionary.DictionaryConcurrentAccessDetectionTests
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.26927.0)
  Discovering: System.Collections.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Collections.Tests (found 2 of 6944 test cases)
  Starting:    System.Collections.Tests (parallel test collections = off, max threads = 46)
    Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection_ReferenceTypeKey(comparerType: null) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /opt/code/_/fx/src/System.Collections/tests/Generic/Dictionary/Dictionary.Generic.Tests.ConcurrentAccessDetection.netcoreapp.cs(38,0): at Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection[TKey,TValue](Dictionary`2 dictionary, Boolean isValueType, Object comparer, Action`1 add, Action`1 get, Action`1 remove, Action`1 removeOutParam)
        /opt/code/_/fx/src/System.Collections/tests/Generic/Dictionary/Dictionary.Generic.Tests.ConcurrentAccessDetection.netcoreapp.cs(78,0): at Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection_ReferenceTypeKey(Type comparerType)
        --- End of stack trace from previous location where exception was thrown ---
    Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection_ReferenceTypeKey(comparerType: typeof(Generic.Dictionary.CustomEqualityComparerDummyRefType)) [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        /opt/code/_/fx/src/System.Collections/tests/Generic/Dictionary/Dictionary.Generic.Tests.ConcurrentAccessDetection.netcoreapp.cs(38,0): at Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection[TKey,TValue](Dictionary`2 dictionary, Boolean isValueType, Object comparer, Action`1 add, Action`1 get, Action`1 remove, Action`1 removeOutParam)
        /opt/code/_/fx/src/System.Collections/tests/Generic/Dictionary/Dictionary.Generic.Tests.ConcurrentAccessDetection.netcoreapp.cs(78,0): at Generic.Dictionary.DictionaryConcurrentAccessDetectionTests.DictionaryConcurrentAccessDetection_ReferenceTypeKey(Type comparerType)
        --- End of stack trace from previous location where exception was thrown ---
  Finished:    System.Collections.Tests
=== TEST EXECUTION SUMMARY ===
   System.Collections.Tests  Total: 4, Errors: 0, Failed: 2, Skipped: 0, Time: 1.813s

```

**Comment by VSadov** [comment]
I tried reproducing the failure both with `COMPlus_JitStress=2 COMPlus_TieredCompilation=1` and without while re-executing a sample containing the testcase code in a loop.
Even after many thouthands iterations there were no failures.

I tried a debug build of corerun as well.
