### ISSUE TITLE
[Linux/arm64] System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide Failure

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#20215]
```
/home/robox/echesako/git/coreclr/_/fx/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet xunit.console.dll System.Threading.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
===========================================================================================================
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.26927.0)
  Discovering: System.Threading.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Threading.Tests (found 178 of 206 test cases)
  Starting:    System.Threading.Tests (parallel test collections = on, max threads = 46)
    System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999999
  Finished:    System.Threading.Tests
=== TEST EXECUTION SUMMARY ===
   System.Threading.Tests  Total: 396, Errors: 0, Failed: 1, Skipped: 0, Time: 44.019s
```

This took me a while to reproduce - but I got at least five exact failures.

**Comment by jkotas** [comment]
This is most likely caused by `FlushProcessWriteBuffers` in PAL not being reliable. We may want to try to fix this by implementing https://github.com/dotnet/coreclr/issues/1563.

**Comment by danmosemsft** [comment]
@kouvel (?) do you expect to have time to work on this relatively soon? If not can you please disable the test in CoreFX for ARM...

https://mc.dot.net/#/user/danmosemsft/pr~2Fjenkins~2Fdotnet~2Fcorefx~2Fmaster~2F/test~2Ffunctional~2Fcli~2F/5651b5c2b7134c8ab662c5594b10f86db7f3cb9c/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.InterlockedTests~2FMemoryBarrierProcessWide

**Comment by sandreenko** [comment]
The issue was marked as fixed in https://github.com/dotnet/coreclr/pull/20949.

**Comment by AriNuer** [comment]
Same test `System.Threading.Tests.InterlockedTests/MemoryBarrierProcessWide ` has failed.

Message :
```
Assert.Equal() Failure
Expected: 1000000
Actual:   999999
``` 
Stack Trace :
```
 at System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide() in /_/src/System.Threading/tests/InterlockedTests.netcoreapp.cs:line 122
```

Details:
https://mc.dot.net/#/user/dotnet-bot/pr~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcli~2Finnerloop~2F/20190609.21/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.InterlockedTests~2FMemoryBarrierProcessWide

**Comment by danmosemsft** [comment]
When fixed please un-disable test in linked https://github.com/dotnet/corefx/issues/38400

**Comment by sergiy-k** [comment]
This requires Linux kernel 4.14 or later to run.

**Comment by sergiy-k** [comment]
Our lab machines need to be updated to have this version of Linux kernel before we can enable this test.

**Comment by VSadov** [comment]
Just to mention - the test is actually enabled. It is only disabled for the Linux/ARM64 config.

**Comment by VincentBu** [comment]
Test System.Threading.Tests.InterlockedTests/MemoryBarrierProcessWide failed again in:
https://mc.dot.net/#/user/coreclr-corefx/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190723.1/workItem/System.Threading.Tests/analysis/xunit/System.Threading.Tests.InterlockedTests~2FMemoryBarrierProcessWide

message:
```
Assert.Equal() Failure
Expected: 1000000
Actual:   999999
```

Stack Trace:
```
at System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide() in /_/src/System.Threading/tests/InterlockedTests.netcoreapp.cs:line 122
```

**Comment by VincentBu** [comment]
Same test failed in pipeline **coreclr-corefx-jitstressregs**

**Log:**
```
System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide [FAIL]
      Assert.Equal() Failure
      Expected: 1000000
      Actual:   999999
      Stack Trace:
        /_/src/System.Threading/tests/InterlockedTests.netcoreapp.cs(122,0): at System.Threading.Tests.InterlockedTests.MemoryBarrierProcessWide()
```

Details:
https://helix.dot.net/api/2019-06-17/jobs/ee569cda-26bb-44b1-b0f0-0df5bd9942e0/workitems/System.Threading.Tests/console

**Comment by gkarabin** [comment]
Apologies for the hijack, but can anyone on this thread help me to identify the kernel patches in 4.14 that are required for resolving at least this issue? I am developing a .NET core 3.0 app on ARM64 kernel 4.9. It will be a while before my device can update to 4.14; but backports of specific patch sets may be an option for me.  After reviewing the 4.14 changelog I don’t see any obvious ARM64 patches that point to this issue. I would appreciate any advice that can be offered.

**Comment by janvorli** [comment]
@gkarabin the change was not ARM64 specific. See the related commit here: https://github.com/torvalds/linux/commit/22e4ebb975822833b083533035233d128b30e98f

**Comment by gkarabin** [comment]
Thanks! I appreciate the pointer.
