### ISSUE TITLE
[Linux/arm64] System.Security.Cryptography.Algorithms.Tests.AesCcmTests Failure

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#20212]
```
/home/robox/echesako/git/coreclr/_/fx/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet xunit.console.dll System.Security.Cryptography.Algorithms.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing -parallel none -class System.Security.Cryptography.Algorithms.Tests.AesCcmTests
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.26927.0)
  Discovering: System.Security.Cryptography.Algorithms.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.Algorithms.Tests (found 18 of 1049 test cases)
  Starting:    System.Security.Cryptography.Algorithms.Tests (parallel test collections = off, max threads = 46)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - DVPT128.rsp - 60 (128/56/192/32/0)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [246, 8, 27, 47, 68, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - DVPT192.rsp - 60 (192/56/192/32/0)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [86, 104, 123, 143, 164, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - DVPT256.rsp - 60 (256/56/192/32/0)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [182, 200, 219, 239, 4, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT128.rsp - 0 (128/56/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [22, 40, 59, 79, 100, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT128.rsp - 50 (128/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [118, 144, 171, 199, 228, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT128.rsp - 51 (128/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [6, 32, 59, 87, 116, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT128.rsp - 52 (128/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [150, 176, 203, 231, 4, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT128.rsp - 60 (128/104/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [38, 64, 91, 119, 148, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT192.rsp - 0 (192/56/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [182, 200, 219, 239, 4, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT192.rsp - 50 (192/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [22, 48, 75, 103, 132, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT192.rsp - 51 (192/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [166, 184, 203, 223, 244, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT192.rsp - 52 (192/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [6, 32, 59, 87, 116, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT192.rsp - 60 (192/104/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [150, 168, 187, 207, 228, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT256.rsp - 0 (256/56/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [246, 8, 27, 47, 68, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT256.rsp - 50 (256/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [86, 104, 123, 143, 164, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT256.rsp - 51 (256/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [182, 208, 235, 7, 36, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT256.rsp - 52 (256/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [70, 96, 123, 151, 180, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(testCase: NIST CCM Test Vectors - VNT256.rsp - 60 (256/104/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [214, 240, 11, 39, 68, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(381,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperCiphertext(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.InplaceEncryptTamperTagDecrypt [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [62, 88, 115, 143, 172, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(319,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.InplaceEncryptTamperTagDecrypt()
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - DVPT128.rsp - 60 (128/56/192/32/0)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [133, 151, 170, 190, 211, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - DVPT192.rsp - 60 (192/56/192/32/0)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [133, 159, 186, 214, 243, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - DVPT256.rsp - 60 (256/56/192/32/0)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [181, 207, 234, 6, 35, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT128.rsp - 0 (128/56/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [149, 175, 202, 230, 3, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT128.rsp - 50 (128/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [37, 63, 90, 118, 147, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT128.rsp - 51 (128/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [181, 207, 234, 6, 35, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT128.rsp - 52 (128/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [69, 95, 122, 150, 179, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT128.rsp - 60 (128/104/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [213, 239, 10, 38, 67, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT192.rsp - 0 (192/56/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [101, 119, 138, 158, 179, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT192.rsp - 50 (192/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [197, 223, 250, 22, 51, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT192.rsp - 51 (192/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [85, 103, 122, 142, 163, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT192.rsp - 52 (192/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [181, 199, 218, 238, 3, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT192.rsp - 60 (192/104/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [21, 47, 74, 102, 131, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT256.rsp - 0 (256/56/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [165, 191, 218, 246, 19, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT256.rsp - 50 (256/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [53, 71, 90, 110, 131, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT256.rsp - 51 (256/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [149, 167, 186, 206, 227, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT256.rsp - 52 (256/96/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [245, 7, 26, 46, 67, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
    System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(testCase: NIST CCM Test Vectors - VNT256.rsp - 60 (256/104/192/128/256)) [FAIL]
      Assert.Equal() Failure
      Expected: Byte[] [0, 0, 0, 0, 0, ...]
      Actual:   Byte[] [85, 103, 122, 142, 163, ...]
      Stack Trace:
        /opt/code/_/fx/src/System.Security.Cryptography.Algorithms/tests/AesCcmTests.cs(359,0): at System.Security.Cryptography.Algorithms.Tests.AesCcmTests.AesCcmNistTestsTamperTag(AEADTest testCase)
  Finished:    System.Security.Cryptography.Algorithms.Tests
=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.Algorithms.Tests  Total: 133, Errors: 0, Failed: 37, Skipped: 0, Time: 2.476s
```

**Comment by wfurt** [comment]
This seems like old issue. I cannot reproduce it:

```
../../../testhost/netcoreapp-Linux-Debug-arm64/dotnet xunit.console.dll System.Security.Cryptography.Algorithms.Tests.dll -xml testResults.xml -nologo -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=failing -notrait category=Outerloop -verbose -nocolor -parallel none  -class System.Security.Cryptography.Algorithms.Tests.AesCcmTests
=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.Algorithms.Tests  Total: 90, Errors: 0, Failed: 0, Skipped: 0, Time: 0.218s
```
I can also run whole crypto suite without any problems:
```
  Discovering: System.Security.Cryptography.Algorithms.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Security.Cryptography.Algorithms.Tests (found 1046 of 1052 test cases)
  Starting:    System.Security.Cryptography.Algorithms.Tests (parallel test collections = on, max threads = 46)
  Finished:    System.Security.Cryptography.Algorithms.Tests
=== TEST EXECUTION SUMMARY ===
   System.Security.Cryptography.Algorithms.Tests  Total: 1747, Errors: 0, Failed: 0, Skipped: 0, Time: 3.090s
~/github/wfurt-corefx-arm/artifacts/bin/tests/System.Security.Cryptography.Algorithms.Tests/netcoreapp-Linux-Debug-arm64
```

also note that this probably depends on underlying crypto in OpenSSL. cc: @bartonjs 

I suggest to close this unless we can reproduce it with current master builds.

**Comment by bartonjs** [comment]
> I suggest to close this unless we can reproduce it with current master builds.

Makes sense to me.
