### ISSUE TITLE
[Linux/arm64] System.Buffers.ArrayPool.Tests.CollectionTests.PollingEventFire Failures

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#20226]
CI failures in varieties of JitStress modes and also in TieredCompilation. For example, https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress1_tst_prtest/1/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_tst_prtest/1/consoleText
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst_prtest/1/consoleText
```
----- start 19:22:04 =============== To repro directly: =====================================================
pushd .
#!/usr/bin/env bash export COMPlus_TieredCompilation=1
chmod +x /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet
/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst_prtest/_/fx/bin/testhost/netcoreapp-Linux-Release-arm64/dotnet xunit.console.dll System.Buffers.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
popd
===========================================================================================================
~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst_prtest/_/fx/bin/tests/System.Buffers.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst_prtest/_/fx/bin/tests/System.Buffers.Tests/netcoreapp-Linux-Release-arm64
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27002.0)
  Discovering: System.Buffers.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Buffers.Tests (found 39 of 40 test cases)
  Starting:    System.Buffers.Tests (parallel test collections = on, max threads = 46)
    System.Buffers.ArrayPool.Tests.CollectionTests.ThreadLocalIsCollectedUnderHighPressure [SKIP]
      Condition(s) not met: "IsStressModeEnabled"
    System.Buffers.ArrayPool.Tests.CollectionTests.PollingEventFires(trim: True) [FAIL]
      Timed out after 60000ms waiting for remote process 870
      Expected: True
      Actual:   False
      Stack Trace:
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_prtest/_/fx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(359,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose(Boolean disposing)
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_prtest/_/fx/src/CoreFx.Private.TestUtilities/src/System/Diagnostics/RemoteExecutorTestBase.cs(346,0): at System.Diagnostics.RemoteExecutorTestBase.RemoteInvokeHandle.Dispose()
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_prtest/_/fx/src/System.Buffers/tests/ArrayPool/ArrayPoolTest.cs(57,0): at System.Buffers.ArrayPool.Tests.ArrayPoolTest.RemoteInvokeWithTrimming(Func`2 method, Boolean trim, Int32 timeout)
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_prtest/_/fx/src/System.Buffers/tests/ArrayPool/CollectionTests.cs(153,0): at System.Buffers.ArrayPool.Tests.CollectionTests.PollingEventFires(Boolean trim)
  Finished:    System.Buffers.Tests
=== TEST EXECUTION SUMMARY ===
   System.Buffers.Tests  Total: 80, Errors: 0, Failed: 1, Skipped: 1, Time: 65.151s
~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst_prtest/_/fx/bin/tests/System.Buffers.Tests/netcoreapp-Linux-Release-arm64
----- end 19:23:20 ----- exit code 1 ----------------------------------------------------------
```

I couldn't reproduce it locally though.

**Comment by AndyAyersMS** [comment]
Current runs don't show these failures. So likely this is no repro. But we'll see....

**Comment by BruceForstall** [comment]
@AndyAyersMS Can we close this bug, and let it come back if the failures return?

**Comment by AndyAyersMS** [comment]
Sure. I am suspicious of all CoreFX failures, especially old ones.
