### ISSUE TITLE
Building coreclr failes on laying out ETW event logging interfaces

### ISSUE THREAD

**Issue by simonz130** [dotnet/coreclr#20312]
I'm trying to build coreclr repo on Windows 10, version 1709 (OS Build 16299.665)
This consistently fails (both when I do it in elevated CMD and regular) with the following output:
```batch
C:\dev\coreclr>build
BUILD: Starting Build at 15:49:06.87
BUILD: Searching for Visual Studio 2017 or 2015 installation
BUILD: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\Tools\VsDevCmd.bat"
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.7.6
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
BUILD: Commencing CoreCLR product build
BUILD: Checking prerequisites
BUILD: Number of processor cores 2
Installing dotnet cli...
Restoring BuildTools version 3.0.0-preview1-03307-03...
Initializing BuildTools...
Done initializing tools.
Running: C:\dev\coreclr\Tools\dotnetcli\dotnet.exe C:\dev\coreclr\Tools\run.exe C:\dev\coreclr\config.json build -Project=C:\dev\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="C:\dev\coreclr\bin\obj\_version.h" -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64
Running: C:\dev\coreclr\Tools\msbuild.cmd /nologo /verbosity:minimal /clp:Summary /nodeReuse:false  /l:BinClashLogger,Tools/net46/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log  C:\dev\coreclr\build.proj /p:__BuildType=Debug /p:__BuildArch=x64 /p:__BuildOS=Windows_NT  /t:GenerateVersionHeader /p:GenerateVersionHeader=true  /maxcpucount /p:NativeVersionHeaderFile=C:\dev\coreclr\bin\obj\_version.h /p:RestoreDefaultOptimizationDataPackage=false /p:UsePartialNGENOptimization=false /p:PortableBuild=true

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.37
Command execution succeeded.
BUILD: Laying out dynamically generated files consumed by the native build system
BUILD: Laying out dynamically generated Event test files and etmdummy stub functions
 Generating Dummy Event Headers
 Generating Event Headers
BUILD: Laying out dynamically generated EventPipe Implementation
BUILD: Laying out ETW event logging interface
Traceback (most recent call last):
  File "C:\dev\coreclr\src\scripts\genEtwProvider.py", line 320, in <module>
    return_code = main(sys.argv[1:])
  File "C:\dev\coreclr\src\scripts\genEtwProvider.py", line 308, in main
    genFiles(manifest, intermediate, exclusion_filename)
  File "C:\dev\coreclr\src\scripts\genEtwProvider.py", line 282, in genFiles
    genProviderInterface(manifest, intermediate)
  File "C:\dev\coreclr\src\scripts\genEtwProvider.py", line 58, in genProviderInterface
    subprocess.check_call(cmd)
  File "C:\Python37\lib\subprocess.py", line 323, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python37\lib\subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

Any ideas what's going on?

**Comment by simonz130** [comment]
Apparently, the problem was that Windows SDK installation on my machine didn't have all the components installed. I had to re-install Windows SDK and it started to work.
