### ISSUE TITLE
[Linux/arm32] Pri-1 test runs are all failing

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#20328]
It appears that all Linux arm32 test runs in the CI are failing.

E.g., look at the Ubuntu jobs in the ARM view: https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/

The basic Checked job is: https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_flow/

The issue seems to be xunit running out of memory while running tests, e.g. many of these:
```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
```

also:
```
23:32:01   Unhandled Exception: System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
23:32:01      at System.Threading.Thread.StartInternal()
23:32:01      at System.Threading.Thread.Start()
23:32:01      at System.Threading.Thread.Start(Object parameter)
23:32:01      at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
23:32:01      at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
23:32:01      at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
23:32:01      --- End of inner exception stack trace ---
23:32:01      at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
23:32:01      at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions)
23:32:01      at System.Threading.Tasks.TaskFactory.StartNew(Action`1 action, Object state, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
23:32:01      at Xunit.Sdk.XunitWorkerThread.QueueUserWorkItem(Action backgroundTask, EventWaitHandle finished) in C:\projects\xunit\src\common\XunitWorkerThread.cs:line 31
23:32:01      at Xunit.Sdk.XunitWorkerThread..ctor(Action threadProc) in C:\projects\xunit\src\common\XunitWorkerThread.cs:line 16
23:32:01      at Xunit.Sdk.MaxConcurrencySyncContext.<.ctor>b__5_0(Int32 _) in C:\projects\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 29
23:32:01      at System.Linq.Enumerable.SelectIPartitionIterator`2.ToList() in /root/corefx-2082958/src/System.Linq/src/System/Linq/Select.SpeedOpt.cs:line 503
23:32:01      at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) in /root/corefx-2082958/src/System.Linq/src/System/Linq/ToCollection.cs:line 27
23:32:01      at Xunit.Sdk.MaxConcurrencySyncContext..ctor(Int32 maximumConcurrencyLevel) in C:\projects\xunit\src\xunit.execution\Sdk\MaxConcurrencySyncContext.cs:line 28
23:32:01      at Xunit.Sdk.XunitTestAssemblyRunner.SetupSyncContext(Int32 maxParallelThreads) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs:line 72
23:32:01      at Xunit.Sdk.XunitTestAssemblyRunner.RunTestCollectionsAsync(IMessageBus messageBus, CancellationTokenSource cancellationTokenSource) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\XunitTestAssemblyRunner.cs:line 167
23:32:01      at Xunit.Sdk.TestAssemblyRunner`1.RunAsync() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestAssemblyRunner.cs:line 196
23:32:01      at Xunit.Sdk.XunitTestFrameworkExecutor.RunTestCases(IEnumerable`1 testCases, IMessageSink executionMessageSink, ITestFrameworkExecutionOptions executionOptions) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 95
23:32:01      at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
23:32:01      at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
23:32:01      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
23:32:01   --- End of stack trace from previous location where exception was thrown ---
23:32:01      at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
23:32:01      at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
23:32:01      at System.Threading.ThreadPoolWorkQueue.Dispatch()
23:32:01      at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
23:32:01   Aborted
```

**Comment by BruceForstall** [comment]
@dotnet/arm32-contrib
