### ISSUE TITLE
[Perf][Release/2.1] Investigate Perf benchmark failures on Ubuntu 16.04

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#20352]
The following perf benchmarks are failing in Release/2.1 Ubuntu 16.04:

```
14:28:18 [./tests/scripts/run-xunit-perf.py]: --------
14:28:18 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off PacketTracer
14:28:18 [./tests/scripts/run-xunit-perf.py]: --------
14:28:18 [./tests/scripts/run-xunit-perf.py]: 
14:28:18 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/PacketTracer.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/PacketTracer --perf:runid Perf-Off --perf:collect stopwatch
14:28:18 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:28:18 [10/6/18 2:26:40 PM][ERR] Could not find constructor for 'Xunit.Sdk.CollectionPerClassTestCollectionFactory' with arguments type(s): Xunit.Sdk.TestAssembly
14:28:18 
[ERROR] Benchmark execution failed.
14:28:18   System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Intrinsics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
14:28:18 
14:28:18 File name: 'System.Runtime.Intrinsics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
14:28:18    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
14:28:18    at System.Reflection.RuntimeAssembly.GetExportedTypes()
14:28:18    at Xunit.Sdk.ReflectionAssemblyInfo.GetTypes(Boolean includePrivateTypes)
14:28:18    at Xunit.Sdk.TestCollectionFactoryHelper.GetTestCollectionDefinitions(IAssemblyInfo assemblyInfo, IMessageSink diagnosticMessageSink)
14:28:18    at Xunit.Sdk.CollectionPerClassTestCollectionFactory..ctor(ITestAssembly testAssembly, IMessageSink diagnosticMessageSink)
14:28:18    at Xunit.Sdk.ExtensibilityPointFactory.GetXunitTestCollectionFactory(IMessageSink diagnosticMessageSink, IAttributeInfo collectionBehaviorAttribute, ITestAssembly testAssembly)
14:28:18    at Xunit.Sdk.XunitTestFrameworkDiscoverer..ctor(IAssemblyInfo assemblyInfo, ISourceInformationProvider sourceProvider, IMessageSink diagnosticMessageSink, IXunitTestCollectionFactory collectionFactory)
14:28:18    at Xunit.Sdk.XunitTestFramework.CreateDiscoverer(IAssemblyInfo assemblyInfo)
14:28:18    at Xunit.Sdk.TestFramework.GetDiscoverer(IAssemblyInfo assemblyInfo)
14:28:18    at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk)
14:28:18    at Xunit.Xunit2..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyTestAssemblyExists)
14:28:18    at Xunit.XunitFrontController.CreateInnerController()
14:28:18    at Xunit.XunitFrontController.get_InnerController()
14:28:18    at Microsoft.Xunit.Performance.Api.XunitBenchmark.GetMetadata(String assemblyFileName, IEnumerable`1 performanceMetricInfos, Boolean collectDefaultMetrics)
14:28:18    at Microsoft.Xunit.Performance.Api.XunitPerformanceHarness.RunBenchmarks(String assemblyFileName)
14:28:18    at PerfHarness.Main(String[] args) in /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/tests/src/Common/PerfHarness/PerfHarness.cs:line 11
```

```
14:43:13 [./tests/scripts/run-xunit-perf.py]: --------
14:43:13 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off k-nucleotide-1
14:43:13 [./tests/scripts/run-xunit-perf.py]: --------
14:43:13 [./tests/scripts/run-xunit-perf.py]: 
14:43:13 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/k-nucleotide-1.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/k-nucleotide-1 --perf:runid Perf-Off --perf:collect stopwatch
14:43:13 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:43:13 [10/6/18 2:42:42 PM][INF] Running 1 [Benchmark]s
14:43:13 [10/6/18 2:42:42 PM][INF]   BenchmarksGame.KNucleotide_1.RunBench
14:43:13 [10/6/18 2:42:42 PM][ERR] BenchmarksGame.KNucleotide_1.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.0.4010, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:43:13 [10/6/18 2:42:42 PM][INF] Finished 1 tests in 0.105s (1 failed, 0 skipped)
```

```
14:43:13 [./tests/scripts/run-xunit-perf.py]: --------
14:43:13 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off k-nucleotide-9
14:43:13 [./tests/scripts/run-xunit-perf.py]: --------
14:43:13 [./tests/scripts/run-xunit-perf.py]: 
14:43:13 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/k-nucleotide-9.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/k-nucleotide-9 --perf:runid Perf-Off --perf:collect stopwatch
14:43:13 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:43:13 [10/6/18 2:42:42 PM][INF] Running 1 [Benchmark]s
14:43:13 [10/6/18 2:42:42 PM][INF]   BenchmarksGame.KNucleotide_9.RunBench
14:43:13 [10/6/18 2:42:43 PM][ERR] BenchmarksGame.KNucleotide_9.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.0.4010, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:43:13 [10/6/18 2:42:43 PM][INF] Finished 1 tests in 0.104s (1 failed, 0 skipped)
```

```
14:43:13 [./tests/scripts/run-xunit-perf.py]: --------
14:43:13 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off regex-redux-1
14:43:13 [./tests/scripts/run-xunit-perf.py]: --------
14:43:13 [./tests/scripts/run-xunit-perf.py]: 
14:43:13 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/regex-redux-1.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/regex-redux-1 --perf:runid Perf-Off --perf:collect stopwatch
14:43:13 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:43:13 [10/6/18 2:42:43 PM][INF] Running 1 [Benchmark]s
14:43:13 [10/6/18 2:42:43 PM][INF]   BenchmarksGame.RegexRedux_1.RunBench
14:43:13 Using input file regexdna-input25000.txt
14:43:13 [10/6/18 2:42:43 PM][ERR] BenchmarksGame.RegexRedux_1.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.0.4010, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:43:13 [10/6/18 2:42:43 PM][ERR]    at BenchmarksGame.RegexRedux_1.<>c__DisplayClass1_0.<RunBench>b__0()
14:43:13    at Microsoft.Xunit.Performance.Benchmark.Iterate(Action measuredOperation)
14:43:13 [10/6/18 2:42:43 PM][INF] Finished 1 tests in 0.144s (1 failed, 0 skipped)
```

```
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off regex-redux-5
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: 
14:43:16 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/regex-redux-5.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/regex-redux-5 --perf:runid Perf-Off --perf:collect stopwatch
14:43:16 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:43:16 [10/6/18 2:42:44 PM][INF] Running 1 [Benchmark]s
14:43:16 [10/6/18 2:42:44 PM][INF]   BenchmarksGame.RegexRedux_5.RunBench
14:43:16 Using input file regexdna-input25000.txt
14:43:16 [10/6/18 2:42:44 PM][ERR] BenchmarksGame.RegexRedux_5.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.0.4010, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:43:16 [10/6/18 2:42:44 PM][ERR]    at BenchmarksGame.RegexRedux_5.<>c__DisplayClass3_0.<RunBench>b__0()
14:43:16    at Microsoft.Xunit.Performance.Benchmark.Iterate(Action measuredOperation)
14:43:16 [10/6/18 2:42:44 PM][INF] Finished 1 tests in 0.143s (1 failed, 0 skipped)
```

```
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off spectralnorm-3
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: 
14:43:16 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/spectralnorm-3.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/spectralnorm-3 --perf:runid Perf-Off --perf:collect stopwatch
14:43:16 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:43:16 [10/6/18 2:42:44 PM][INF] Running 1 [Benchmark]s
14:43:16 [10/6/18 2:42:44 PM][INF]   BenchmarksGame.SpectralNorm_3.RunBench
14:43:16 [10/6/18 2:42:44 PM][ERR] BenchmarksGame.SpectralNorm_3.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.0.4010, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:43:16 [10/6/18 2:42:44 PM][INF] Finished 1 tests in 0.106s (1 failed, 0 skipped)
```

```
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off spectralnorm-1
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: 
14:43:16 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/spectralnorm-1.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/spectralnorm-1 --perf:runid Perf-Off --perf:collect stopwatch
14:43:16 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:43:16 [10/6/18 2:42:45 PM][INF] Running 1 [Benchmark]s
14:43:16 [10/6/18 2:42:45 PM][INF]   BenchmarksGame.SpectralNorm_1.RunBench
14:43:16 [10/6/18 2:42:45 PM][ERR] BenchmarksGame.SpectralNorm_1.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.0.4010, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:43:16 [10/6/18 2:42:45 PM][INF] Finished 1 tests in 0.105s (1 failed, 0 skipped)
```
```
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off reverse-complement-1
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: 
14:43:16 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/reverse-complement-1.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/reverse-complement-1 --perf:runid Perf-Off --perf:collect stopwatch
14:43:16 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:43:16 [10/6/18 2:42:46 PM][INF] Running 1 [Benchmark]s
14:43:16 [10/6/18 2:42:46 PM][INF]   BenchmarksGame.ReverseComplement_1.RunBench
14:43:16 [10/6/18 2:42:46 PM][ERR] BenchmarksGame.ReverseComplement_1.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.0.4010, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:43:16 [10/6/18 2:42:46 PM][INF] Finished 1 tests in 0.104s (1 failed, 0 skipped)
```

```
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off reverse-complement-6
14:43:16 [./tests/scripts/run-xunit-perf.py]: --------
14:43:16 [./tests/scripts/run-xunit-perf.py]: 
14:43:16 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox/reverse-complement-6.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.1/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/reverse-complement-6 --perf:runid Perf-Off --perf:collect stopwatch
14:43:16 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:43:16 [10/6/18 2:42:46 PM][INF] Running 1 [Benchmark]s
14:43:16 [10/6/18 2:42:46 PM][INF]   BenchmarksGame.ReverseComplement_6.RunBench
14:43:16 [10/6/18 2:42:46 PM][ERR] BenchmarksGame.ReverseComplement_6.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.0.4010, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
14:43:16 [10/6/18 2:42:46 PM][INF] Finished 1 tests in 0.104s (1 failed, 0 skipped)
```

**Comment by adiaaida** [comment]
@billwert @brianrob @RussKeldorph

**Comment by RussKeldorph** [comment]
Assume this is no longer interesting in light of https://github.com/dotnet/performance.
