### ISSUE TITLE
[Perf][Release/2.1][Release/2.2] Investigate Perf Scenario benchmark failures

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#20353]
The scenario benchmarks are failing in release/2.1 and release/2.2. See: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.2/job/perf_scenarios_Windows_NT_x64_full_opt_ryujit/14/console

Looking at the logs in the build artifacts, JitBench is failing with the following error:

```
Unhandled Exception: System.AggregateException: One or more errors occurred. (Could not find 'publish' directory) ---> System.IO.DirectoryNotFoundException: Could not find 'publish' directory
   at JitBench.MLBenchmark.Publish(DotNetInstallation dotNetInstall, String outputDir, ITestOutputHelper output)
   at JitBench.MLBenchmark.Setup(DotNetInstallation dotNetInstall, String outputDir, Boolean useExistingSetup, ITestOutputHelper output)
   at JitBench.TestRun.SetupBenchmarks(ITestOutputHelper output)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at JitBench.TestRun.Run(ITestOutputHelper output)
   at JitBench.Program.Main(String[] args)
```

**Comment by adiaaida** [comment]
@billwert @brianrob @RussKeldorph

**Comment by RussKeldorph** [comment]
Assume this is no longer interesting in light of https://github.com/dotnet/performance.
