### ISSUE TITLE
.NET Core crash on ARM (RaspberryPi 3) inside INJECT_ACTIVATION_SIGNAL handler

### ISSUE THREAD

**Issue by sherlock1982** [dotnet/coreclr#20413]
Hello!
I'm getting random crashes inside .NET Core on ARM (RaspberryPi 3). 
I have dumps but don't know how to reproduce it yet.
Does anyone knows what it can be?

.NET Core 2.1.5

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
0000001  0x76bd9824 in __GI_abort () at abort.c:89
#2  0x76865096 in PROCAbort () at /root/coreclr/src/pal/src/thread/process.cpp:3068
#3  0x768642b4 in PROCEndProcess (hProcess=<optimized out>, uExitCode=2, bTerminateUnconditionally=1993248888) at /root/coreclr/src/pal/src/thread/process.cpp:1394
#4  0x765b85c8 in CrawlFrame::CheckGSCookies (this=<optimized out>) at /root/coreclr/src/vm/stackwalk.cpp:416
#5  CrawlFrame::SetCurGSCookie (this=0x67d6b850, pGSCookie=<optimized out>) at /root/coreclr/src/vm/stackwalk.cpp:433
#6  StackFrameIterator::PreProcessingForManagedFrames (this=0x67d6b850) at /root/coreclr/src/vm/stackwalk.cpp:3156
0000007  StackFrameIterator::ProcessCurrentFrame (this=0x67d6b850) at /root/coreclr/src/vm/stackwalk.cpp:2990
0000008  0x765b818e in StackFrameIterator::Init (this=0x67d6b850, pThread=0x491a20, pFrame=<optimized out>, pRegDisp=0x67d6bb90, flags=392) at /root/coreclr/src/vm/stackwalk.cpp:1266
0000009  0x765b7fc8 in Thread::StackWalkFramesEx (this=0x491a20, pRD=0x67d6bb90, pCallback=0x7665a081 <SWCB_GetExecutionState(CrawlFrame*, void*)>, pData=0x67d6bb48, flags=392, pStartFrame=<optimized out>)
    at /root/coreclr/src/vm/stackwalk.cpp:954
#10 0x7665b11a in HandleGCSuspensionForInterruptedThread (interruptedContext=0x67d6bfc0) at /root/coreclr/src/vm/threadsuspend.cpp:7479
#11 0x7683f3bc in inject_activation_handler (code=34, siginfo=<optimized out>, context=0x67d6c200) at /root/coreclr/src/pal/src/exception/signal.cpp:701
#12 <signal handler called>
#13 0x70686980 in ?? ()
0000014 0x706828be in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)

```

**Comment by janvorli** [comment]
This is already fixed and the fix will be part of 2.1.6 release.
