### ISSUE TITLE
Exception during deserialization of ConcurrentDictionary between .NET 4.5, and .NET 4.5.1 or higher

### ISSUE THREAD

**Issue by samshteinman** [dotnet/coreclr#20492]
**Reproduction Steps:**
Send a ConcurrentDictionary using serialization + BinaryFormatter(FormatterAssemblyType.Simple, FormatterTypeStyle.TypesWhenNeeded) -- from a machine with .NET 4.5 to a machine with .NET 4.5.1 or higher

**Where in the code:**

Specifically the **m_KeyRehashCount member**, but because we are using **Simple formatter assembly type, we never throw the specific exception of missing member**, and also **_it never gets added to outMemberTypes_**

System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo:

```
internal  Type[] GetMemberTypes(String[] inMemberNames, Type objectType)
{

..
                    if (!isFound)
                    {
                        // A field on the type isnt found. See if the field has OptionallySerializable and the type has the deserialization constructor
                        Object [] attrs = cache.memberInfos[i].GetCustomAttributes(typeof(OptionalFieldAttribute), false);
                        if ((attrs == null || attrs.Length == 0) && !bSimpleAssembly){
                            // the member isnt optionally serializable
                            throw new SerializationException(Environment.GetResourceString("Serialization_MissingMember", cache.memberNames[i], objectType, typeof(OptionalFieldAttribute).FullName));
                        }
                    }
}
```

So then **later we have a null ref exception when try to get parser binary type info**

Then later in the System.Runtime.Serialization.Formatters.Binary.ObjectMap
```
internal ObjectMap(String objectName, Type objectType, String[] memberNames, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo)
{
..

 for (int i=0; i<memberTypes.Length; i++)
            {
                Object typeInformation = null;
                BinaryTypeEnum binaryTypeEnum = BinaryConverter.GetParserBinaryTypeInfo(memberTypes[i], out typeInformation);
                binaryTypeEnumA[i] = binaryTypeEnum;
                typeInformationA[i] = typeInformation;
            }
}
```

The **type being passed is null,** because **it never got filled** in the **GetMemberTypes** method.
```
internal static BinaryTypeEnum GetParserBinaryTypeInfo(Type type, out Object typeInformation)
{
..
case InternalPrimitiveTypeE.Invalid:
                        if (Assembly.GetAssembly(type) == Converter.urtAssembly)
                            binaryTypeEnum = BinaryTypeEnum.ObjectUrt;
                        else
                            binaryTypeEnum = BinaryTypeEnum.ObjectUser;
}
```

Stack trace:
System.ArgumentNullException: Value cannot be null.

Parameter name: type
at System.Reflection.Assembly.GetAssembly(Type type)
at System.Runtime.Serialization.Formatters.Binary.BinaryConverter.GetParserBinaryTypeInfo(Type type, Object& typeInformation)
at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, Type objectType, String[] memberNames, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo)
at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(BinaryObjectWithMap record)
at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(BinaryHeaderEnum binaryHeaderEnum)
at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)

**Comment by jkotas** [comment]
This was a known issue that was fixed in .NET Framework 4.7.

cc @AlexGhiondea

**Comment by samshteinman** [comment]
> This was a known issue that was fixed in .NET Framework 4.7.
> 
> cc @AlexGhiondea

I can reproduce this with a .NET 4.5 ConcurrentDictionary sent to a machine running .NET 4.7.2

**Comment by jkotas** [comment]
It was not possible to repair this issue for every every possible combination of from/to versions unfortunately.

https://stackoverflow.com/questions/19585791/net-4-5-1-wcf-serialization-exception has a few more details.

@AlexGhiondea Do you have anything to add? This was tracked internally as TFS bug 899074 that you have fixed.
