### ISSUE TITLE
System.IO.Tests.File_Delete.Unix_NonExistentPath_Nop [FAIL]

### ISSUE THREAD

**Issue by benaadams** [dotnet/coreclr#20507]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_corefx_innerloop_prtest/3406/consoleFull#3758903192d31e50d-1517-49fc-92b3-2ca637122019
```
Discovering: System.IO.FileSystem.Tests
Discovered:  System.IO.FileSystem.Tests
Starting:    System.IO.FileSystem.Tests

System.IO.Tests.File_Delete.Unix_NonExistentPath_Nop [FAIL]
      System.IO.DirectoryNotFoundException : Could not find a part of the path '/tmp/File_Delete_0oc4eg5j.54a/Unix_NonExistentPath_Nop_118_ac051064/C'.
      Stack Trace:
            at System.IO.FileSystem.DeleteFile(String fullPath)
            at System.IO.File.Delete(String path)
         /root/corefx-1949935/src/System.IO.FileSystem/tests/File/Delete.cs(15,0): at System.IO.Tests.File_Delete.Delete(String path)
         /root/corefx-1949935/src/System.IO.FileSystem/tests/File/Delete.cs(119,0): at System.IO.Tests.File_Delete.Unix_NonExistentPath_Nop()
```

Seen in https://github.com/dotnet/coreclr/pull/20503

**Comment by mikedn** [comment]
Looks like that test was already deleted in https://github.com/dotnet/corefx/pull/32660

I guess coreclr still uses an older version of corefx

**Comment by MarcoRossignoli** [comment]
Yes we fixed to have consistent behaviour between unix and win
