### ISSUE TITLE
Several tests failed with System.TimeoutException : VirtualNetwork: Timeout reading the next frame

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/coreclr#20542]
**Job:**
jitstress » x86_checked_windows_nt_corefx_jitstressregs3
[https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs3/621/](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs3/621/)

**Affected tests:**
System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_Async_TestOverloadProtectionLevel.NegotiateStream_StreamToStream_Successive_ClientWrite_Async_Success
System.Net.Security.Tests.SslStreamAlpnTests.SslStream_StreamToStream_Alpn_Success(clientProtocols: null, serverProtocols: null, expected: )
System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok
System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_Async.NegotiateStream_StreamToStream_Authentication_TargetName_Success
System.Net.Security.Tests.NegotiateStreamStreamToStreamTest_Async_TestOverloadAllParameters.NegotiateStream_ReadWriteLongMsgSync_Success

**Log:**
```
Discovering: System.Numerics.Vectors.Tests (method display = ClassAndMethod, method display options = None)
      System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok [FAIL]
    Discovered:  System.Numerics.Vectors.Tests (found 1150 of 1153 test cases)
        System.TimeoutException : VirtualNetwork: Timeout reading the next frame.
        Stack Trace:
    Starting:    System.Numerics.Vectors.Tests (parallel test collections = on, max threads = 4)
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetwork.cs(52,0): at System.Net.Test.Common.VirtualNetwork.ReadFrame(Boolean server, Byte[]& buffer)
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs(118,0): at System.Net.Test.Common.VirtualNetworkStream.Read(Byte[] buffer, Int32 offset, Int32 count)
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\Common\tests\System\Net\VirtualNetwork\VirtualNetworkStream.cs(138,0): at System.Net.Test.Common.VirtualNetworkStream.<>c__DisplayClass27_0.<ReadAsync>b__0()
             at System.Threading.Tasks.Task`1.InnerInvoke()
             at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
             at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
          --- End of stack trace from previous location where exception was thrown ---
             at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
             at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
          --- End of stack trace from previous location where exception was thrown ---
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\System.Net.Security\src\System\Net\FixedSizeReader.cs(56,0): at System.Net.FixedSizeReader.ReadPacketAsync(Stream transport, AsyncProtocolRequest request)
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\System.Net.Security\src\System\Net\Security\SslState.cs(96,0): at System.Net.Security.SslState.ThrowIfExceptional()
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\System.Net.Security\src\System\Net\Security\SslState.cs(735,0): at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\System.Net.Security\src\System\Net\Security\SslState.cs(705,0): at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(221,0): at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\System.Net.Security\src\System\Net\Security\SslStream.cs(368,0): at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__44_1(IAsyncResult iar)
             at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
          --- End of stack trace from previous location where exception was thrown ---
          D:\j\workspace\x86_checked_w---932410df\_\fx\src\System.Net.Security\tests\FunctionalTests\SslStreamAlertsTest.cs(37,0): at System.Net.Security.Tests.SslStreamAlertsTest.SslStream_StreamToStream_HandshakeAlert_Ok()
```

**Comment by BruceForstall** [comment]
I'm going to ignore the System.Net failures, and close this issue.
