### ISSUE TITLE
Some tests failed with System.NullReferenceException in x64_checked_ubuntu_corefx_jitstress2

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/coreclr#20564]
**Job:**
x64_checked_ubuntu_corefx_jitstress2
[https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_jitstress2/742](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_jitstress2/742)

**Affected tests:**
```
System.Diagnostics.Tests.DebugTests.WriteLineIf
System.Diagnostics.Tests.DebugTests.Asserts
System.Diagnostics.Tests.DebugTests.Write
System.Diagnostics.Tests.DebugTests.IndentLevel_Set_GetReturnsExpected(indentLevel: -1, expectedIndentLevel: 0)
System.Diagnostics.Tests.DebugTests.IndentLevel_Set_GetReturnsExpected(indentLevel: 0, expectedIndentLevel: 0)
System.Diagnostics.Tests.DebugTests.IndentLevel_Set_GetReturnsExpected(indentLevel: 1, expectedIndentLevel: 1)
System.Diagnostics.Tests.DebugTests.WriteLine
System.Diagnostics.Tests.DebugTests.Fail
System.Diagnostics.Tests.DebugTests.WriteIf
System.Diagnostics.Tests.DebugTests.Print
System.Diagnostics.Tests.DebugTests.IndentSize_Set_GetReturnsExpected(indentSize: -1, expectedIndentSize: 0)
System.Diagnostics.Tests.DebugTests.IndentSize_Set_GetReturnsExpected(indentSize: 0, expectedIndentSize: 0)
System.Diagnostics.Tests.DebugTests.IndentSize_Set_GetReturnsExpected(indentSize: 1, expectedIndentSize: 1)
System.Diagnostics.Tests.DebugTests.IndentSize_Set_GetReturnsExpected(indentSize: 2, expectedIndentSize: 2)
System.Diagnostics.Tests.DebugTests.IndentSize_Set_GetReturnsExpected(indentSize: 3, expectedIndentSize: 3)
System.Diagnostics.Tests.DebugTests.IndentSize_Set_GetReturnsExpected(indentSize: 4, expectedIndentSize: 4)
```

**Log:**
```
System.Diagnostics.Tests.DebugTests.IndentSize_Set_GetReturnsExpected(indentSize: 2, expectedIndentSize: 2) [FAIL]
  [m[31;1m[m[37m      System.NullReferenceException : Object reference not set to an instance of an object.
  [m[30;1m      Stack Trace:
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress2/_/fx/src/System.Diagnostics.Debug/tests/DebugTests.cs(172,0): at System.Diagnostics.Tests.DebugTests.VerifyLogged(Action test, String expectedOutput)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress2/_/fx/src/System.Diagnostics.Debug/tests/DebugTests.cs(117,0): at System.Diagnostics.Tests.DebugTests.IndentSize_Set_GetReturnsExpected(Int32 indentSize, Int32 expectedIndentSize)

```

**Comment by BruceForstall** [comment]
The only failure I see in that job now is:
```
System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod
```
which looks like https://github.com/dotnet/coreclr/issues/21644. So closing.
