### ISSUE TITLE
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown  in  arm_cross_checked_ubuntu_gcstress0xc_zapdisable

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20566]
**job**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_tst/31/

**Log:**
```
Unhandled Exception: 
  Unhandled Exception: System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
     at System.Threading.Thread.StartInternal()
     at System.Threading.Thread.Start()
     at System.Threading.Thread.Start(Object parameter)
     at System.Threading.Tasks.ThreadPoolTaskScheduler.QueueTask(Task task)
     at System.Threading.Tasks.TaskScheduler.InternalQueueTask(Task task)
     at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
     --- End of inner exception stack trace ---
     at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
     at System.Threading.Tasks.Task.InternalStartNew(Task creatingTask, Delegate action, Object state, CancellationToken cancellationToken, TaskScheduler scheduler, TaskCreationOptions options, InternalTaskOptions internalOptions)
     at System.Threading.Tasks.TaskFactory.StartNew(Action`1 action, Object state, CancellationToken cancellationToken, TaskCreationOptions creationOptions, TaskScheduler scheduler)
     at Xunit.Sdk.XunitWorkerThread.QueueUserWorkItem(Action backgroundTask, EventWaitHandle finished) in C:\projects\xunit\src\common\XunitWorkerThread.cs:line 31
     at Xunit.Sdk.XunitWorkerThread..ctor(Action threadProc) in C:\projects\xunit\src\common\XunitWorkerThread.cs:line 16
     at Xunit.Sdk.MessageBus..ctor(IMessageSink messageSink, Boolean stopOnFail) in C:\projects\xunit\src\xunit.execution\Sdk\MessageBus.cs:line 28
     at Xunit.Sdk.TestAssemblyRunner`1.CreateMessageBus() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestAssemblyRunner.cs:line 139
     at Xunit.Sdk.TestAssemblyRunner`1.RunAsync() in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestAssemblyRunner.cs:line 183
     at Xunit.Sdk.XunitTestFrameworkExecutor.RunTestCases(IEnumerable`1 testCases, IMessageSink executionMessageSink, ITestFrameworkExecutionOptions executionOptions) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkExecutor.cs:line 95
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_1(Object state)
     at System.Threading.QueueUserWorkItemCallbackDefaultContext.<>c.<.cctor>b__5_0(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
  --- End of stack trace from previous location where exception was thrown ---
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.QueueUserWorkItemCallbackDefaultContext.ExecuteWorkItem()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
     at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
  Aborted

```

**Comment by echesakovMSFT** [comment]
I believe that this was fixed in https://github.com/dotnet/coreclr/pull/20349

Will verify in https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_zapdisable_flow/34/

**Comment by echesakovMSFT** [comment]
Verified that there is no OutOfMemory
