### ISSUE TITLE
NullPointerException in CI job arm64_cross_checked_windows_nt_r2r_no_tiered_compilation_tst

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20598]
the failing job https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_r2r_no_tiered_compilation_tst/15

failed log:
Build step 'Copy artifacts from another project' marked build as failure
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing xUnit.Net-v2 (default)
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performTests(XUnitProcessor.java:145)
	at org.jenkinsci.plugins.xunit.XUnitProcessor.performXUnit(XUnitProcessor.java:88)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:142)
	at org.jenkinsci.plugins.xunit.XUnitPublisher.perform(XUnitPublisher.java:134)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Publish xUnit test result report' marked build as failure
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] Build step... marked build as failure from category Build
[BFA] Done. 0s
ERROR: Step �Delete workspace when build is done� failed: no workspace for dotnet_coreclr/master/jitstress/arm64_cross_checked_windows_nt_r2r_no_tiered_compilation_tst #15
Finished: FAILURE

**Comment by RussKeldorph** [comment]
Looks like Jenkins flakiness.
