### ISSUE TITLE
Loader_classloader._DefaultInterfaceMethods_diamondshape_diamondshape_d_diamondshape_d_._DefaultInterfaceMethods_diamondshape_diamondshape_d_diamondshape_d_cmd Failed with access violation

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20602]
**job**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_gcstress0xc_zapdisable/104/#showFailuresLink

**affected test**
```
Loader_classloader._DefaultInterfaceMethods_diamondshape_diamondshape_d_diamondshape_d_._DefaultInterfaceMethods_diamondshape_diamondshape_d_diamondshape_d_cmd 
```

**log:**
```
Return code:      1
  Raw output file:      D:\j\workspace\x64_checked_w---2b0573da\bin\tests\Windows_NT.x64.Checked\Reports\Loader.classloader\DefaultInterfaceMethods\diamondshape\diamondshape_d\diamondshape_d.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x64_checked_w---2b0573da\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" diamondshape_d.exe 
        Calling IFoo.Foo on Foo - expecting exception.
        Exception caught: System.NotSupportedException: Could not call method 'IFoo.Foo(Int32)' on interface 'IFoo' with type 'FooClass' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
           at IFoo.Foo(Int32 a)
           at Program.Negative()
        Calling I1.Func on I47Class - expecting exception
        Exception caught: System.NotSupportedException: Could not call method 'I1.Func(Int32)' on interface 'I1' with type 'I47Class' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
           at I1.Func(Int32 a)
           at Program.Negative()
        Calling GI1<T>.Func on GI23Class<S> - expecting exception
        Exception caught: System.NotSupportedException: Could not call method 'GI1`1[S].Func(System.Type[] ByRef)' on interface 'GI1`1[System.Object]' with type 'GI23Class`1[System.Object]' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
           at Program.Negative()
        Calling I1.Func on I4Class - expecting I4.Func
        At I4.Func
        PASS
        Calling I1.Func on I8Class - expecting I8.Func
        At I8.Func
        PASS
        Calling GI1.Func on GI4Class<object> - expecting GI4.Func<S>
        System.Object, System.String, GI4
        PASS
        PASS
        PASS
        Expected: 100
        Actual: -1073741819
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
```

**Comment by AndyAyersMS** [comment]
This test hasn't failed recently.

**Comment by AndyAyersMS** [comment]
Will see if I can get a local repro.

**Comment by AndyAyersMS** [comment]
No repro after 1000x runs with additional CPU stress loading. Closing.
