### ISSUE TITLE
System.Text.Tests.StringBuilderTests.Equals(sb1: , sb2: , expected: False) [FAIL] in CI job x64_arm64_altjit_checked_windows_nt_corefx_baseline

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20624]
the failing job https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_baseline/335

failed log:
```
xUnit.net Console Runner v2.4.1-pre.build.4059 (64-bit .NET Core 4.6.27025.0)
    Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Runtime.Tests (found 4714 of 4757 test cases)
    Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 4)
      System.Tests.ActivatorNetcoreTests.TestingCreateInstanceObjectHandleFullSignatureWinRT [SKIP]
        Condition(s) not met: "IsNotWindows8x"
        Assert.Equal() Failure
        Expected: False
        Actual:   True
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\src\System.Runtime\tests\System\Text\StringBuilderTests.cs(1127,0): at System.Text.Tests.StringBuilderTests.Equals(StringBuilder sb1, StringBuilder sb2, Boolean expected)
      System.Text.Tests.StringBuilderTests.Equals(sb1: , sb2: , expected: False) [FAIL]
        Assert.Equal() Failure
        Expected: False
        Actual:   True
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---734a66f6\_\fx\src\System.Runtime\tests\System\Text\StringBuilderTests.cs(1127,0): at System.Text.Tests.StringBuilderTests.Equals(StringBuilder sb1, StringBuilder sb2, Boolean expected)
      System.Text.Tests.StringBuilderTests.Equals(sb1: , sb2: , expected: False) [FAIL]
    Finished:    System.Runtime.Tests
```

**Comment by echesakovMSFT** [comment]
Those tests were removed as invalid in https://github.com/dotnet/corefx/pull/33086.
Confirmed that these failures don't reproduce as of aef0bc27daebb70ccc4bdb9bd46960b7e8b5eb0e
