### ISSUE TITLE
Lower fast tail call doesn't patch control expression

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#20625]
the failing job: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstress1/339

failed tests:

- DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace
- DataContractSerializerTests.DCS_ResolveDatacontractBaseType

failed log:
```
System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Runtime.Serialization.Xml\tests\SerializationTestTypes\DataContractResolverLibrary.cs(84,0): at SerializationTestTypes.ProxyDataContractResolver.ResolveName(String typeName, String typeNamespace, Type declaredType, DataContractResolver knownTypeResolver)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerContext.cs(276,0): at System.Runtime.Serialization.XmlObjectSerializerContext.ResolveDataContractFromKnownTypes(String typeName, String typeNs, DataContract memberTypeContract)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\KnownTypeDataContractResolver.cs(26,0): at System.Runtime.Serialization.KnownTypeDataContractResolver.TryResolveType(Type type, Type declaredType, DataContractResolver knownTypeResolver, XmlDictionaryString& typeName, XmlDictionaryString& typeNamespace)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(673,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.ResolveType(Type objectType, Type declaredType, XmlDictionaryString& typeName, XmlDictionaryString& typeNamespace)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(665,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteResolvedTypeInfo(XmlWriterDelegator writer, Type objectType, Type declaredType)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(710,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.WriteTypeInfo(XmlWriterDelegator writer, DataContract contract, DataContract declaredContract)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializerWriteContext.cs(178,0): at System.Runtime.Serialization.XmlObjectSerializerWriteContext.SerializeWithXsiTypeAtTopLevel(DataContract dataContract, XmlWriterDelegator xmlWriter, Object obj, RuntimeTypeHandle originalDeclaredTypeHandle, Type graphType)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs(387,0): at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\DataContractSerializer.cs(248,0): at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(71,0): at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(57,0): at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Private.DataContractSerialization\src\System\Runtime\Serialization\XmlObjectSerializer.cs(27,0): at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\Common\tests\System\Runtime\Serialization\DataContractSerializerHelper.cs(29,0): at System.Runtime.Serialization.Tests.DataContractSerializerHelper.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Runtime.Serialization.Xml\tests\DataContractSerializer.cs(2800,0): at DataContractSerializerTests.DCS_ResolveDatacontractBaseType()
    Finished:    System.Runtime.Serialization.Xml.ReflectionOnly.Tests
```

**Comment by shimingsg** [comment]
similar failing job https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs4/325

failed tests:

- DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace
- DataContractSerializerTests.DCS_ResolveDatacontractBaseType
- DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace
- DataContractSerializerTests.DCS_ResolveDatacontractBaseType

**Comment by echesakovMSFT** [comment]
Also in https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress1/675/

**Comment by echesakovMSFT** [comment]
Reproduces as of aef0bc27daebb70ccc4bdb9bd46960b7e8b5eb0e

**Comment by echesakovMSFT** [comment]
**DataContractSerializerTests.DCS_ResolveNameReturnsEmptyNamespace** is reproducible with **both** stress modes enabled

```
COMPlus_JitStressModeNames=STRESS_TAILCALL STRESS_MIN_OPTS
COMPlus_JitStressModeNamesOnly=1
COMPlus_JitStressRange=3468051885
COMPlus_TieredCompilation=0
```
for the method

SerializationTestTypes.EmptyNamespaceResolver:ResolveName(ref,ref,ref,ref):ref:this (MethodHash=ceb645ad)

**Comment by echesakovMSFT** [comment]
The same issue (System.NullReferenceException) reproduces under

```
COMPlus_JitStressModeNames=STRESS_TAILCALL STRESS_MIN_OPTS
COMPlus_JitStressModeNamesOnly=1
COMPlus_TieredCompilation=0
```

for the following program

```c#
using System;

namespace GitHub_20625
{
    abstract class Base 
    {
        public abstract void M(int arg1, int arg2, int arg3, Base arg4);
    }

    class Der1 : Base
    {
        public override void M(int arg1, int arg2, int arg3, Base arg4)
        {
            arg4.M(arg1, arg2, arg3, null);
        }
    }

    class Der2 : Base
    {
        public override void M(int arg1, int arg2, int arg3, Base arg4)
        {         
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var der1 = new Der1();
            var der2 = new Der2();

            der1.M(20, 62, 5, der2);
            Console.WriteLine("PASS");
        }
    }
}
```

**Comment by echesakovMSFT** [comment]
The issue is understood. During **Lowering::LowerCall**
1. **LowerFastTailCall** spills V04 arg4 to V06 tmp1 (see [000035]) **and** replaces all LCL_VAR   ref    V04 arg4 with LCL_VAR   ref    V06 tmp1 (see [000001]) consumed by PUTARG_REG
2. However, **Lowering::LowerCall** doesn't know about this spilling and continues using V04 arg4 in control expression (see [000026])

```
lowering call (before):
N005 (  1,  1) [000005] ------------         t5 =    CNS_INT   ref    null
N010 (  3,  2) [000001] ------------         t1 =    LCL_VAR   ref    V04 arg4         
N011 (  3,  2) [000002] ------------         t2 =    LCL_VAR   int    V01 arg1         
N012 (  3,  2) [000003] ------------         t3 =    LCL_VAR   int    V02 arg2         
N013 (  3,  2) [000004] ------------         t4 =    LCL_VAR   int    V03 arg3         
                                                 /--*  t5     ref    arg4 out+20
                                                 +--*  t1     ref    this in rcx
                                                 +--*  t2     int    arg1 in rdx
                                                 +--*  t3     int    arg2 in r8
                                                 +--*  t4     int    arg3 in r9
N018 ( 36, 21) [000006] --CXG-------              *  CALLV ind void   Base.M

objp:
======
lowering arg : N001 (  0,  0) [000013] ----------L-              *  ARGPLACE  ref   

args:
======
lowering arg : N002 (  0,  0) [000015] ----------L-              *  ARGPLACE  int   
lowering arg : N003 (  0,  0) [000017] ----------L-              *  ARGPLACE  int   
lowering arg : N004 (  0,  0) [000019] ----------L-              *  ARGPLACE  int   
lowering arg : N005 (  1,  1) [000005] ------------              *  CNS_INT   ref    null
new node is :                [000021] ------------              *  PUTARG_STK [+0x20] void  


late:
======
lowering arg : N010 (  3,  2) [000001] ------------              *  LCL_VAR   ref    V04 arg4         
new node is :                [000022] ------------              *  PUTARG_REG ref    REG rcx

lowering arg : N011 (  3,  2) [000002] ------------              *  LCL_VAR   int    V01 arg1         
new node is :                [000023] ------------              *  PUTARG_REG int    REG rdx

lowering arg : N012 (  3,  2) [000003] ------------              *  LCL_VAR   int    V02 arg2         
new node is :                [000024] ------------              *  PUTARG_REG int    REG r8

lowering arg : N013 (  3,  2) [000004] ------------              *  LCL_VAR   int    V03 arg3         
new node is :                [000025] ------------              *  PUTARG_REG int    REG r9


lvaGrabTemp returning 6 (V06 tmp1) called for Fast tail call lowering is creating a new local variable.
rewriting asg(LCL_VAR, X) to STORE_LCL_VAR(X)
               [000035] DA----------              *  STORE_LCL_VAR ref    V06 tmp1         

results of lowering call:
N001 (  3,  2) [000026] ------------        t26 =    LCL_VAR   ref    V04 arg4         
                                                 /--*  t26    ref    
N002 (  4,  3) [000027] ------------        t27 = *  LEA(b+0)  byref 
                                                 /--*  t27    byref  
N003 (  7,  5) [000028] ------------        t28 = *  IND       long  
                                                 /--*  t28    long   
N004 (  8,  6) [000029] ------------        t29 = *  LEA(b+72) long  
                                                 /--*  t29    long   
N005 ( 11,  8) [000030] ------------        t30 = *  IND       long  
                                                 /--*  t30    long   
N006 ( 12,  9) [000031] ------------        t31 = *  LEA(b+32) long  
                                                 /--*  t31    long   
N007 ( 15, 11) [000032] ------------        t32 = *  IND       long  
lowering call (after):
N005 (  1,  1) [000005] ------------         t5 =    CNS_INT   ref    null
N001 (  3,  2) [000033] ------------        t33 =    LCL_VAR   ref    V04 arg4         
                                                 /--*  t33    ref    
N002 (  4,  3) [000035] DA----------              *  STORE_LCL_VAR ref    V06 tmp1         
               [000037] ------------                 NO_OP     void  
               [000036] ------------                 START_NONGC void  
                                                 /--*  t5     ref    
               [000021] ------------              *  PUTARG_STK [+0x20] void  
N010 (  3,  2) [000001] ------------         t1 =    LCL_VAR   ref    V06 tmp1         
                                                 /--*  t1     ref    
               [000022] ------------        t22 = *  PUTARG_REG ref    REG rcx
N011 (  3,  2) [000002] ------------         t2 =    LCL_VAR   int    V01 arg1         
                                                 /--*  t2     int    
               [000023] ------------        t23 = *  PUTARG_REG int    REG rdx
N012 (  3,  2) [000003] ------------         t3 =    LCL_VAR   int    V02 arg2         
                                                 /--*  t3     int    
               [000024] ------------        t24 = *  PUTARG_REG int    REG r8
N013 (  3,  2) [000004] ------------         t4 =    LCL_VAR   int    V03 arg3         
                                                 /--*  t4     int    
               [000025] ------------        t25 = *  PUTARG_REG int    REG r9
N001 (  3,  2) [000026] ------------        t26 =    LCL_VAR   ref    V04 arg4         
                                                 /--*  t26    ref    
N002 (  4,  3) [000027] -c----------        t27 = *  LEA(b+0)  byref 
                                                 /--*  t27    byref  
N003 (  7,  5) [000028] ------------        t28 = *  IND       long  
                                                 /--*  t28    long   
N004 (  8,  6) [000029] -c----------        t29 = *  LEA(b+72) long  
                                                 /--*  t29    long   
N005 ( 11,  8) [000030] ------------        t30 = *  IND       long  
                                                 /--*  t30    long   
N006 ( 12,  9) [000031] -c----------        t31 = *  LEA(b+32) long  
                                                 /--*  t31    long   
N007 ( 15, 11) [000032] ------------        t32 = *  IND       long  
                                                 /--*  t22    ref    this in rcx
                                                 +--*  t23    int    arg1 in rdx
                                                 +--*  t24    int    arg2 in r8
                                                 +--*  t25    int    arg3 in r9
                                                 +--*  t32    long   control expr
N018 ( 36, 21) [000006] --CXG-------              *  CALLV ind void   Base.M
```

Adding regression test in https://github.com/dotnet/coreclr/pull/20740

/cc @dotnet/jit-contrib

**Comment by jashook** [comment]
This should also repro on unix and arm64 this logic for shuffling outgoing stack args is not os specific.

**Comment by jashook** [comment]
The only difference, is the unix and arm64 case will need more variables. Can you modify to have 6 args instead of 4?

**Comment by echesakovMSFT** [comment]
@jashook Just modified the test in #20740, thanks for pointing this out!
