### ISSUE TITLE
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly test failed in jitstress job x86_arm_altjit_checked_windows_nt_corefx_jitstressregs0x80

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/coreclr#20630]
**Job:**
[https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstressregs0x80/335/](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstressregs0x80/335/)

**Affected tests:**
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly(chunkedTransfer: True, connectionClose: True, mode: Token)

**Log:**
```
System.Net.Http.Functional.Tests.PlatformHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly(chunkedTransfer: True, connectionClose: True, mode: Token) [FAIL]
        Elapsed time 00:01:41.5695978 should be less than 60 seconds, was 101.5695978
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_arm_altji---1cc90e64\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Cancellation.cs(368,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.ValidateClientCancellationAsync(Func`1 clientBodyAsync)
          D:\j\workspace\x86_arm_altji---1cc90e64\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Cancellation.cs(129,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass2_2.<<GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly>b__0>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
          D:\j\workspace\x86_arm_altji---1cc90e64\_\fx\src\Common\tests\System\Net\Http\LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
          D:\j\workspace\x86_arm_altji---1cc90e64\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Cancellation.cs(111,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly(Boolean chunkedTransfer, Boolean connectionClose, CancellationMode mode)
          --- End of stack trace from previous location where exception was thrown ---
```

**Comment by BruceForstall** [comment]
Ignoring System.Net failure; closing.
