### ISSUE TITLE
Perf-Off JitBench not producing data

### ISSUE THREAD

**Issue by maririos** [dotnet/coreclr#20642]
Jobs CoreCLR Master:

- [perf_scenarios_Windows_NT_x64_full_opt_ryujit](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x64_full_opt_ryujit/)
- [perf_scenarios_Windows_NT_x64_min_opt_ryujit](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x64_min_opt_ryujit/)
- [perf_scenarios_Windows_NT_x64_tiered_ryujit](https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x64_tiered_ryujit)

```
14:51:24 [tests\scripts\run-xunit-perf.py]: 
14:51:24 [tests\scripts\run-xunit-perf.py]: --------
14:51:24 [tests\scripts\run-xunit-perf.py]: Running Perf-Off JitBench
14:51:24 [tests\scripts\run-xunit-perf.py]: --------
14:51:24 [tests\scripts\run-xunit-perf.py]: 
14:51:24 [tests\scripts\run-xunit-perf.py]: cmd.exe /c START "CORECLR_PERF_RUN" /B /WAIT /HIGH C:\j\w\perf_scenario---5b001a46\bin\sandbox\corerun.exe C:\j\w\perf_scenario---5b001a46\bin\sandbox\JitBench.exe --perf:outputdir C:\j\w\perf_scenario---5b001a46\bin\sandbox_logs\Scenarios\Off\JitBench --perf:runid Perf-Off --target-architecture x64 --perf:collect stopwatch
14:51:24 Traceback (most recent call last):
14:51:24   File "tests\scripts\run-xunit-perf.py", line 531, in <module>
14:51:24     sys.exit(main(Args))
14:51:24   File "tests\scripts\run-xunit-perf.py", line 522, in main
14:51:24     upload_to_benchview(python, coreclrRepo, benchviewPath, uploadToBenchview, benchviewGroup, runType, configuration, operatingSystem, etwCollection, optLevel, jitName, pgoOptimized, arch)
14:51:24   File "tests\scripts\run-xunit-perf.py", line 285, in upload_to_benchview
14:51:24     raise Exception('%s does not exist. There is no data to be uploaded.' % jsonFile)
14:51:24 Exception: C:\j\w\perf_scenario---5b001a46\bin\sandbox\measurement.json does not exist. There is no data to be uploaded.
```

FYI @adiaaida @brianrob @billwert @RussKeldorph

**Comment by adiaaida** [comment]
This seems to be a duplicate of https://github.com/dotnet/coreclr/issues/20571

**Comment by maririos** [comment]
Closing as a dup
