### ISSUE TITLE
NETClientPrimitives test fails on Windows/arm

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#20682]
The following tests were disabled in https://github.com/dotnet/coreclr/pull/20675

* Interop/COM/NETClients/Primitives/NETClientPrimitives
* Interop/COM/NativeClients/Primitives
* Interop/COM/NETClients/IDispatch/NETClientIDispatch
* Interop/COM/NETClients/Aggregation/NETClientAggregation

**Comment by janvorli** [comment]
These tests now work fine on my local Windows ARM64 device. I just had to patch registry as follows:
Under `HKEY_LOCAL_MACHINE\SOFTWARE\WowAA32Node\Microsoft\Windows NT\CurrentVersion`, add `REG_SZ` `InstallationType` with value `client`. It was missing it in the wow node while it was present in the `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion`. I've found it by stepping through the code in Windows.

**Comment by BruceForstall** [comment]
@AaronRobinsonMSFT Is it correct that this "Future", not "3.0"?

**Comment by AaronRobinsonMSFT** [comment]
@BruceForstall Unclear. I am not sure how important this scenario is for 3.0. cc @jeffschwMSFT.

**Comment by RussKeldorph** [comment]
This is now blocking the official build.

https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190521.72/workItem/Interop/analysis/xunit/Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_~2F_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

```
Unhandled Exception: System.Exception: Invalid RegGetValueW result: 0x2 type: RegNone
   at TestLibrary.Utilities.GetRegistryValueString(String key, String value) in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 247
   at TestLibrary.Utilities.GetInstallationTypeForWindows() in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 193
   at TestLibrary.Utilities.GetInstallationType() in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 181
   at TestLibrary.Utilities.get_IsWindowsNanoServer() in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 71
   at TestLibrary.Utilities.get_IsWinRTSupported() in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 70
   at NetClient.Program.Main(String[] args) in F:\\workspace\\_work\\1\\s\\tests\\src\\Interop\\WinRT\\NETClients\\Primitives\\Program.cs:line 13
```


@jkoritzinsky @AaronRobinsonMSFT

**Comment by jkoritzinsky** [comment]
The official build break has been fixed, moving back to Future.
