### ISSUE TITLE
[arm64/Linux] System.Threading.Tasks.Tests.Status.TaskStatusTests test failures

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20706]
**Job**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10_tst/33/

**failed test**
System.Threading.Tasks.Tests.Status.TaskStatusTests.TaskStatus10

**Log:**
```
[37m  Discovering: System.Threading.Tasks.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Threading.Tasks.Tests (found 518 of 694 test cases)
[m[37m  Starting:    System.Threading.Tasks.Tests (parallel test collections = on, max threads = 46)
[m[33;1m    System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_DebuggerAttached_ReturnsAllSchedulers [SKIP]
[m[37m      Condition(s) not met: "DebuggerIsAttached"
[m[33;1m    System.Threading.Tasks.Tests.TaskSchedulerTests.GetScheduledTasksForDebugger_DebuggerAttached_ReturnsTasksFromCustomSchedulers [SKIP]
[m[37m      Condition(s) not met: "DebuggerIsAttached"
[m[31;1m    System.Threading.Tasks.Tests.Status.TaskStatusTests.TaskStatus10 [FAIL]
[m[37m      Expecting Child Task final Status to be Canceled, while getting RanToCompletion
[m[37m      Expected: True
[m[37m      Actual:   False
[m[30;1m      Stack Trace:
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10/_/fx/src/System.Threading.Tasks/tests/Task/TaskStatusTest.cs(255,0): at System.Threading.Tasks.Tests.Status.TaskStatusTest.RealRun()
[m[37m  Finished:    System.Threading.Tasks.Tests
[m[37m=== TEST EXECUTION SUMMARY ===
[m[37m   System.Threading.Tasks.Tests  Total: 619, Errors: 0, Failed: 1, Skipped: 2, Time: 40.697s
[m[m~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10_tst/_/fx/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64
----- end 23:35:29 ----- exit code 1 ----------------------------------------------------------
Looking around for any Linux dump...
... found no dump in /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10_tst/_/fx/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64
error: One or more tests failed while running tests from ''.  Exit code 1.
```

**Comment by BruceForstall** [comment]
Current runs (https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10_tst/) don't show this failure.

**Comment by BruceForstall** [comment]
I saw 2 different TaskStatusTests failures today:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress1_tst/114/consoleFull
```
01:53:36 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64
01:53:36 [37m  Discovering: System.Threading.Tasks.Tests (method display = ClassAndMethod, method display options = None)
01:53:36 [m[37m  Discovered:  System.Threading.Tasks.Tests (found 537 of 713 test cases)
01:53:36 [m[37m  Starting:    System.Threading.Tasks.Tests (parallel test collections = on, max threads = 46)
01:53:36 
[m[31;1m    System.Threading.Tasks.Tests.Status.TaskStatusTests.TaskStatus17 [FAIL]
01:53:36 [m[37m      Expecting Child Task final Status to be Canceled, while getting RanToCompletion
01:53:36 [m[37m      Expected: True
01:53:36 [m[37m      Actual:   False
01:53:36 [m[30;1m      Stack Trace:
01:53:36 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1/_/fx/src/System.Threading.Tasks/tests/Task/TaskStatusTest.cs(255,0): at System.Threading.Tasks.Tests.Status.TaskStatusTest.RealRun()
01:53:36 [m[33;1m    System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_DebuggerAttached_ReturnsAllSchedulers [SKIP]
01:53:36 [m[37m      Condition(s) not met: "DebuggerIsAttached"
01:53:36 [m[33;1m    System.Threading.Tasks.Tests.TaskSchedulerTests.GetScheduledTasksForDebugger_DebuggerAttached_ReturnsTasksFromCustomSchedulers [SKIP]
01:53:36 [m[37m      Condition(s) not met: "DebuggerIsAttached"
01:53:36 [m[37m  Finished:    System.Threading.Tasks.Tests
01:53:36 [m[37m=== TEST EXECUTION SUMMARY ===
01:53:36 [m[37m   System.Threading.Tasks.Tests  Total: 648, Errors: 0, Failed: 1, Skipped: 2, Time: 42.325s
01:53:36 [m[m~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64
01:53:36 ----- end 01:53:36 ----- exit code 1 ---------------------------------------------------------
```

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10_tst/113/consoleFull
```
23:35:55 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64
23:35:55 [37m  Discovering: System.Threading.Tasks.Tests (method display = ClassAndMethod, method display options = None)
23:35:55 [m[37m  Discovered:  System.Threading.Tasks.Tests (found 537 of 713 test cases)
23:35:55 [m[37m  Starting:    System.Threading.Tasks.Tests (parallel test collections = on, max threads = 46)
23:35:55 
[m[31;1m    System.Threading.Tasks.Tests.Status.TaskStatusTests.TaskStatus10 [FAIL]
23:35:55 [m[37m      Expecting Child Task final Status to be Canceled, while getting RanToCompletion
23:35:55 [m[37m      Expected: True
23:35:55 [m[37m      Actual:   False
23:35:55 [m[30;1m      Stack Trace:
23:35:55 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10/_/fx/src/System.Threading.Tasks/tests/Task/TaskStatusTest.cs(255,0): at System.Threading.Tasks.Tests.Status.TaskStatusTest.RealRun()
23:35:55 [m[33;1m    System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_DebuggerAttached_ReturnsAllSchedulers [SKIP]
23:35:55 [m[37m      Condition(s) not met: "DebuggerIsAttached"
23:35:55 [m[33;1m    System.Threading.Tasks.Tests.TaskSchedulerTests.GetScheduledTasksForDebugger_DebuggerAttached_ReturnsTasksFromCustomSchedulers [SKIP]
23:35:55 [m[37m      Condition(s) not met: "DebuggerIsAttached"
23:35:55 [m[37m  Finished:    System.Threading.Tasks.Tests
23:35:55 [m[37m=== TEST EXECUTION SUMMARY ===
23:35:55 [m[37m   System.Threading.Tasks.Tests  Total: 648, Errors: 0, Failed: 1, Skipped: 2, Time: 39.936s
23:35:55 [m[m~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs0x10_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64
23:35:55 ----- end 23:35:55 ----- exit code 1 ---------------------------------------------------------
```

@danmosemsft @wfurt Can the robustness of these be improved? (Or is there a real bug here?)

**Comment by wfurt** [comment]
we will probably need to reproduce this before making any real progress. This could be just timing or it could be real bug either in test logic or in product.

**Comment by sandreenko** [comment]
The test was excluded in #22697.

**Comment by VSadov** [comment]
The test says:
```cs
                        //
                        // if cancel action, start the child task after calling Cancel()
                        //
```

but later has:
```cs
switch (_testAction)
                {
                    case TestAction.CancelTask:
                        if (_createChildTask)
                        {
                            _childTask.Start();
                        }
                        _taskCts.Cancel();

                        break;
                    case TestAction.CancelTaskAndAcknowledge:
                        if (_createChildTask)
                        {
                            _childTask.Start();
                        }
                        _taskCts.Cancel();
                        if (_taskCts.Token.IsCancellationRequested)
                        {
                            throw new OperationCanceledException(_taskCts.Token);
                        }
                        break;
                    case TestAction.FailedTask:
                        throw new StatusTestException();
                }
```

Cancel goes after Start. 
Does it create an opportunity for a task to complete before observing cancellation?  (assuming that under stress anything can be slow, including ` _taskCts.Cancel();`)

**Comment by VSadov** [comment]
if the code is changed to the following (extra Sleeps), there is a consistent repro:

```cs
switch (_testAction)
                {
                    case TestAction.CancelTask:
                        if (_createChildTask)
                        {
                            _childTask.Start();
                        }
                        Thread.Sleep(100);
                        _taskCts.Cancel();

                        break;
                    case TestAction.CancelTaskAndAcknowledge:
                        if (_createChildTask)
                        {
                            _childTask.Start();
                        }
                        Thread.Sleep(100);
                        _taskCts.Cancel();
                        if (_taskCts.Token.IsCancellationRequested)
                        {
                            throw new OperationCanceledException(_taskCts.Token);
                        }
                        break;
                    case TestAction.FailedTask:
                        throw new StatusTestException();
                }
```

**Comment by VSadov** [comment]
I will make a fix in CoreFX, but being a test issue, this is not a blocker.

**Comment by VSadov** [comment]
The CoreFX fix was merged. Need to update the exclusion list to point o the PR https://github.com/dotnet/corefx/pull/36645

**Comment by VSadov** [comment]
Updating the exclusion list is in https://github.com/dotnet/coreclr/pull/23818
