### ISSUE TITLE
IllegalStateException in arm64_cross_checked_windows_nt_jitstress1_tiered_tst

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20714]
**job**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstress1_tiered_tst/13/

**log:**
```
Started by upstream project "dotnet_coreclr/master/jitstress/arm64_cross_checked_windows_nt_jitstress1_tiered_flow" build number 18
originally caused by:
 Started by an SCM change
FATAL: no longer a configured node for windows.10.arm64.open-1029164131722-0
java.lang.IllegalStateException: no longer a configured node for windows.10.arm64.open-1029164131722-0
	at hudson.model.AbstractBuild$AbstractBuildExecution.getCurrentNode(AbstractBuild.java:415)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:455)
	at hudson.model.Run.execute(Run.java:1724)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing xUnit.Net-v2 (default)
ERROR: Build step failed with exception
java.lang.NullPointerException
Build step 'Publish xUnit test result report' marked build as failure
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] Build step... marked build as failure from category Build
[BFA] Done. 0s
ERROR: Step �Delete workspace when build is done� failed: no workspace for dotnet_coreclr/master/jitstress/arm64_cross_checked_windows_nt_jitstress1_tiered_tst #13
Finished: FAILURE
```

**Comment by BruceForstall** [comment]
@dotnet/dnceng I've never seen this Jenkins failure mode before...
cc @jashook

**Comment by MattGal** [comment]
@BruceForstall taking a peek...

**Comment by mmitche** [comment]
Never seen that one before

**Comment by MattGal** [comment]
I couldn't find anything interesting, but it correlates fairly to when I rebooted yesterday.

**Comment by BruceForstall** [comment]
Closing as obsolete infrastructure issue
