### ISSUE TITLE
XmlWriterTraceListenerTests failed in x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x80

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20761]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x80/343/

**Failed tests:**
```
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceData_NullDataParams
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceTransferTest
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceEvent_WithStackTrace
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceData_MultipleXPathNavigators
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceData_NullObjectArray
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceEventFormat(format: \"This is a format without args\", args: null)
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceEventFormat(format: \"This is my {0} to {1} a trace with {0} {2} format \"..., args: [\"test\", \"try\", \"\", 3])
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceEvent_WithLogicalOperationStack
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceData_OneObject(data: \"My string data\", eventType: -1)
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceData_OneObject(data: Exception thrownFailed when trying to connect to server, eventType: Error)
```

**One of the failed log:**
```
System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceData_NullDataParams [FAIL]
        Assert.Equal() Failure
                    (pos 1)
        Expected: 11-DD-YY
        Actual:   10-DD-YY
                    (pos 1)
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---29fc8c6b\_\fx\src\System.Diagnostics.TextWriterTraceListener\tests\XmlWriterTraceListenerTests.cs(489,0): at System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.ValidateSystemInfo(XmlDocument document, String eventId, TraceEventType eventType, DateTime date, TraceEventCache eventCache)
          D:\j\workspace\x64_arm64_alt---29fc8c6b\_\fx\src\System.Diagnostics.TextWriterTraceListener\tests\XmlWriterTraceListenerTests.cs(298,0): at System.Diagnostics.TextWriterTraceListenerTests.XmlWriterTraceListenerTests.TraceData_NullDataParams()
```

**Comment by sandreenko** [comment]
@BruceForstall [ci log](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x80/354/) doesn't show failed tests in [`Test Result`](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x80/354/testReport/), is it a known issue?

**Comment by BruceForstall** [comment]
Current runs (e.g., https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x80/375) don't show this failure
