### ISSUE TITLE
[JitStress] System.Tests.Int16Tests.Equals(i1: -789, obj: -789, expected: True)

### ISSUE THREAD

**Issue by jiangzeng** [dotnet/coreclr#20799]
**Jobs:**
[https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress2/677/](https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress2/677/)

**Affected tests:**
System.Reflection.Tests.AssemblyNameTests.Constructor_String_LoadVersionTest
System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod
System.Tests.Int16Tests.Equals(i1: -789, obj: -789, expected: True)

**Log:**
System.Reflection.Tests.AssemblyNameTests.Constructor_String_LoadVersionTest
```
Starting:    System.IO.Tests (parallel test collections = on, max threads = 4)
    Starting:    System.Reflection.Tests (parallel test collections = on, max threads = 4)
        Assert.Throws() Failure
        Expected: typeof(System.IO.FileNotFoundException)
        Actual:   (No exception was thrown)
        Stack Trace:
          D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Reflection\tests\AssemblyNameTests.cs(559,0): at System.Reflection.Tests.AssemblyNameTests.Constructor_String_LoadVersionTest()
      System.Reflection.Tests.AssemblyNameTests.Constructor_String_LoadVersionTest [FAIL]
```

System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod
```
Starting:    System.Xml.RW.RwFactory.Tests (parallel test collections = on, max threads = 4)
  * ExceptionTests - reported call stack:
     at System.Tests.ExceptionTests.ThrowAndRethrowOtherMethod(ValueTuple`3& rethrownExceptionStackFrame) in D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\ExceptionTests.cs:line 156
     at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod() in D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\ExceptionTests.cs:line 142
      System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod [FAIL]
        Assert.Equal() Failure
                        (pos 5)
        Expected: ThrowAndRethrowOtherMethod
        Actual:   ThrowStatementDoesNotResetExceptionStackLineOt���
                        (pos 5)
        Stack Trace:
          D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\ExceptionTests.cs(189,0): at System.Tests.ExceptionTests.VerifyCallStack(ValueTuple`3 expectedStackFrame, String reportedCallStack, Int32 skipFrames)
          D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\ExceptionTests.cs(144,0): at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod()

```

System.Tests.Int16Tests.Equals(i1: -789, obj: -789, expected: True)
```
Starting:    System.Xml.RW.XmlWriterApi.Tests (parallel test collections = on, max threads = 4)
      System.Tests.Int16Tests.Equals(i1: -789, obj: -789, expected: True) [FAIL]
     System.Runtime.Serialization.Formatters.Tests: [Long Running Test] 'System.Runtime.Serialization.Formatters.Tests.BinaryFormatterTests.SerializeHugeObjectGraphs', Elapsed: 00:26:09
        Assert.Equal() Failure
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\Int16Tests.cs(87,0): at System.Tests.Int16Tests.Equals(Int16 i1, Object obj, Boolean expected)
    Finished:    System.Xml.RW.XmlWriterApi.Tests
```

**Comment by echesakovMSFT** [comment]
An issue with **System.Tests.Int16Tests.Equals(i1: -789, obj: -789, expected: True) [FAIL]** reproduces under the following environment
```
COMPlus_JitStressModeNames=STRESS_UNSAFE_BUFFER_CHECKS
COMPlus_JitStressModeNamesOnly=1
COMPlus_JitStressRange=3500251927
COMPlus_TieredCompilation=0
```
The hash corresponds to the test method itself System.Tests.Int16Tests:Equals(short,ref,bool)

**Comment by echesakovMSFT** [comment]
An issue with **System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod [FAIL]** reproduces under the following environment
```
COMPlus_JitInlinePolicyRandom=2
COMPlus_JitStressModeNames=STRESS_RANDOM_INLINE
COMPlus_JitStressModeNamesOnly=1
COMPlus_JitStressRange=2880818700
COMPlus_TieredCompilation=0
```
The hash corresponds to the test method itself System.Tests.ExceptionTests:ThrowAndRethrowOtherMethod(byref)

**Comment by echesakovMSFT** [comment]
An issue with **System.Reflection.Tests.AssemblyNameTests.Constructor_String_LoadVersionTest [FAIL]** is tracked by https://github.com/dotnet/corefx/issues/33249. The test was disabled in https://github.com/dotnet/corefx/pull/33224

**Comment by BruceForstall** [comment]
@echesakovMSFT Can you split this into separate issues, and only keep open the issues that are still unresolved?

**Comment by echesakovMSFT** [comment]
@BruceForstall Sure

**Comment by echesakovMSFT** [comment]
Closed via https://github.com/dotnet/coreclr/pull/20900
