### ISSUE TITLE
run-corefx-tests.py does not work after corefx update

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#20826]
After dotnet/corefx#33208 update corefx has bin folder under `corefx\artifacts\bin` and we need to update `run-corefx-tests.py ` accordingly.  Now it fails with 
```
Updating CoreCLR: F:\git\coreclr\bin\Product\Windows_NT.x86.Checked => F:\git\corefx\bin\testhost\netcoreapp-Windows_NT-Release-x86\shared\Microsoft.NETCore.App\9.9.9
Traceback (most recent call last):
  File "F:\git\coreclr\tests\scripts\run-corefx-tests.py", line 384, in <module>
    main(Args)
  File "F:\git\coreclr\tests\scripts\run-corefx-tests.py", line 316, in main
    copy_files(core_root, fx_runtime)
  File "F:\git\coreclr\tests\scripts\run-corefx-tests.py", line 199, in copy_files
    assert os.path.isdir(target_dir)
AssertionError
```

PTAL @jashook @sbomer @dotnet/jit-contrib

**Comment by AriNuer** [comment]
wait for next job to verify
**bug:**
https://github.com/dotnet/coreclr/issues/20826
