### ISSUE TITLE
Some adjustment rules are ambiguous in TimeZoneInfo.GetSystemTimeZones on unix

### ISSUE THREAD

**Issue by EgorBo** [dotnet/coreclr#20837]
Run the following code snippet on macOS:
```csharp
foreach (var tmz in TimeZoneInfo.GetSystemTimeZones())
    var tmzClone = TimeZoneInfo.FromSerializedString(tmz.ToSerializedString ());
```
**Expected:**
no exceptions (just like on Windows).

**Actual:**
```
Unhandled Exception: System.Runtime.Serialization.SerializationException: An error occurred while deserializing the object.  The serialized data is corrupt. ---> System.InvalidTimeZoneException: The elements of the AdjustmentRule array must be in chronological order and must not overlap.
   at System.TimeZoneInfo.ValidateTimeZoneInfo(String id, TimeSpan baseUtcOffset, AdjustmentRule[] adjustmentRules, Boolean& adjustmentRulesSupportDst)
   at System.TimeZoneInfo..ctor(String id, TimeSpan baseUtcOffset, String displayName, String standardDisplayName, String daylightDisplayName, AdjustmentRule[] adjustmentRules, Boolean disableDaylightSavingTime)
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
   --- End of inner exception stack trace ---
   at System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo(String source)
```

The problem is - some adjustment rules are ambiguous, run this to find out which ones:
```csharp
var rules = tmz.GetAdjustmentRules();
var prev = rules.First();
foreach (var current in rules.Skip(1))
    if (current.DateStart <= prev.DateEnd)	
        Console.WriteLine($"ERR: {tmz.Id}, CurrentStart={current.DateStart}, PrevEnd={prev.DateEnd}");
```
so the first snippet is crashed here: https://github.com/dotnet/coreclr/blob/030a3ea9b8dbeae89c90d34441d4d9a1cf4a7de6/src/System.Private.CoreLib/shared/System/TimeZoneInfo.cs#L1974-L1978

**Comment by RussKeldorph** [comment]
@tarekgh

**Comment by tarekgh** [comment]
@EgorBo yes we are aware of some limitation of the serialization functionality/Adjustment rules on Linux. I am wondering in what scenario you are trying to serialize and de-serialize the time zones? I would say the best practice is to serialize the time zone Id only and use this Id to reconstruct the time zone object again.
