### ISSUE TITLE
Seg fault in ICU on Ubuntu 15.10 with IC 55

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#2083]
It's possible something is set up incorrectly in my environment, but I just tried setting up an Ubuntu 15.10 VM (including rebuilding coreclr and the corefx native binaries), which has ICU v55.  A very simple program:
```C#
using System;

public class Program
{
    public static void Main(string[] args)
    {
        "a".StartsWith("b");
    }
}
```
ends up crashing 90% of the time, in the following place:
```
#0  0x00007f1a7fd19267 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007f1a7fd1aeca in __GI_abort () at abort.c:89
#2  0x00007f1a8065cb7d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007f1a8065a9c6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007f1a8065aa11 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007f1a8065ac29 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007f1a7f8e4556 in SEHProcessException (pointers=<optimized out>)
    at /home/stoub/Source/coreclr/src/pal/src/exception/seh.cpp:166
#7  0x00007f1a7f8e5943 in common_signal_handler (pointers=<error reading variable: Cannot access memory at address 0x2931>, code=11, 
    ucontext=0x7ffcb000c000) at /home/stoub/Source/coreclr/src/pal/src/exception/signal.cpp:562
#8  sigsegv_handler (code=11, siginfo=0x7ffcb000c130, context=0x7ffcb000c000)
    at /home/stoub/Source/coreclr/src/pal/src/exception/signal.cpp:296
#9  <signal handler called>
#10 0x00007f1a76312c01 in utext_setNativeIndex_55 () from /usr/lib/x86_64-linux-gnu/libicuuc.so.55
#11 0x00007f1a7634f42c in icu_55::RuleBasedBreakIterator::first() () from /usr/lib/x86_64-linux-gnu/libicuuc.so.55
#12 0x00007f1a7634a5eb in ubrk_setText_55 () from /usr/lib/x86_64-linux-gnu/libicuuc.so.55
#13 0x00007f1a7634a745 in ubrk_open_55 () from /usr/lib/x86_64-linux-gnu/libicuuc.so.55
#14 0x00007f1a75f5aae4 in usearch_openFromCollator_55 () from /usr/lib/x86_64-linux-gnu/libicui18n.so.55
#15 0x00007f1a765f8fca in StartsWith () from /home/stoub/netcore/System.Globalization.Native.so
```
I can't get this to repro at all while running under gdb or lldb, but it repros almost all the time when just run from the prompt.

**Comment by stephentoub** [comment]
I'm going to close this for now.  I just resynced to the latest coreclr and corefx, rebuilt everything, and I'm no longer reproing this.  So for the moment I'm going to consider it operator error.  We can reopen if I or anyone else sees this again.
