### ISSUE TITLE
[Perf] [release/2.2] [release/2.1] [Linux] PacketTracer failing with `System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Intrinsics`

### ISSUE THREAD

**Issue by adiaaida** [dotnet/coreclr#20850]
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/release_2.2/job/perf_Ubuntu16.04/32/

Full error message:
```
14:36:43 [./tests/scripts/run-xunit-perf.py]: Running Perf-Off PacketTracer
14:36:43 [./tests/scripts/run-xunit-perf.py]: --------
14:36:43 [./tests/scripts/run-xunit-perf.py]: 
14:36:43 [./tests/scripts/run-xunit-perf.py]: taskset 0x00000002 nice --adjustment=-10 /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.2/perf_Ubuntu16.04/bin/sandbox/corerun PerfHarness.dll /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.2/perf_Ubuntu16.04/bin/sandbox/PacketTracer.exe --perf:outputdir /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.2/perf_Ubuntu16.04/bin/sandbox_logs/Microbenchmarks/Off/PacketTracer --perf:runid Perf-Off --perf:collect stopwatch
14:36:43 [./tests/scripts/run-xunit-perf.py]: CoreRun.exe exited with 1 code
14:36:43 
[ERROR] Benchmark execution failed.
14:36:43   System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Intrinsics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
14:36:43 
14:36:43 File name: 'System.Runtime.Intrinsics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
14:36:43    at System.Reflection.RuntimeAssembly.GetExportedTypes(RuntimeAssembly assembly, ObjectHandleOnStack retTypes)
14:36:43    at System.Reflection.RuntimeAssembly.GetExportedTypes()
14:36:43    at Xunit.Sdk.ReflectionAssemblyInfo.GetTypes(Boolean includePrivateTypes) in C:\projects\xunit\src\xunit.execution\Sdk\Reflection\ReflectionAssemblyInfo.cs:line 80
14:36:43    at Xunit.Sdk.TestCollectionFactoryHelper.GetTestCollectionDefinitions(IAssemblyInfo assemblyInfo, IMessageSink diagnosticMessageSink) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestCollectionFactoryHelper.cs:line 22
14:36:43    at Xunit.Sdk.CollectionPerClassTestCollectionFactory..ctor(ITestAssembly testAssembly, IMessageSink diagnosticMessageSink) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\CollectionPerClassTestCollectionFactory.cs:line 27
14:36:43    at Xunit.Sdk.ExtensibilityPointFactory.GetXunitTestCollectionFactory(IMessageSink diagnosticMessageSink, IAttributeInfo collectionBehaviorAttribute, ITestAssembly testAssembly) in C:\projects\xunit\src\xunit.execution\Sdk\ExtensibilityPointFactory.cs:line 239
14:36:43    at Xunit.Sdk.XunitTestFrameworkDiscoverer..ctor(IAssemblyInfo assemblyInfo, ISourceInformationProvider sourceProvider, IMessageSink diagnosticMessageSink, IXunitTestCollectionFactory collectionFactory) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFrameworkDiscoverer.cs:line 45
14:36:43    at Xunit.Sdk.XunitTestFramework.CreateDiscoverer(IAssemblyInfo assemblyInfo) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\XunitTestFramework.cs:line 21
14:36:43    at Xunit.Sdk.TestFramework.GetDiscoverer(IAssemblyInfo assemblyInfo) in C:\projects\xunit\src\xunit.execution\Sdk\Frameworks\TestFramework.cs:line 71
14:36:43    at Xunit.Xunit2Discoverer..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, IAssemblyInfo assemblyInfo, String assemblyFileName, String xunitExecutionAssemblyPath, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyAssembliesOnDisk)
14:36:43    at Xunit.Xunit2..ctor(AppDomainSupport appDomainSupport, ISourceInformationProvider sourceInformationProvider, String assemblyFileName, String configFileName, Boolean shadowCopy, String shadowCopyFolder, IMessageSink diagnosticMessageSink, Boolean verifyTestAssemblyExists)
14:36:43    at Xunit.XunitFrontController.CreateInnerController()
14:36:43    at Xunit.XunitFrontController.get_InnerController()
14:36:43    at Microsoft.Xunit.Performance.Api.XunitBenchmark.GetMetadata(String assemblyFileName, IEnumerable`1 performanceMetricInfos, Boolean collectDefaultMetrics)
14:36:43    at Microsoft.Xunit.Performance.Api.XunitPerformanceHarness.RunBenchmarks(String assemblyFileName)
14:36:43    at PerfHarness.Main(String[] args) in /home/administrator/jenkins/w/dotnet_coreclr/perf/release_2.2/perf_Ubuntu16.04/tests/src/Common/PerfHarness/PerfHarness.
```

**Comment by adiaaida** [comment]
@brianrob @billwert @RussKeldorph FYI

**Comment by RussKeldorph** [comment]
@adiaaida Are you looking into this, or are you asking for help?

**Comment by adiaaida** [comment]
We identified this as a product/test failure, rather than an infra failure, so someone on coreclr needs to take a look at it and track down why the test is failing.

**Comment by adiaaida** [comment]
This is also failing in release/2.1 now along with the following tests:

Perf-Off regex-redux-5
Perf-Off regex-redux-1
Perf-Off spectralnorm-3
Perf-Off spectralnorm-1
Perf-Off reverse-complement-6
Perf-Off reverse-complement-1
Perf-Off k-nucleotide-9
Perf-Off k-nucleotide-1

which are failing with the following error:

```
BenchmarksGame.SpectralNorm_3.RunBench: Could not load file or assembly 'xunit.assert, Version=2.4.1.4059, Culture=neutral, PublicKeyToken=8d05b1bb7a6fdb6c'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

**Comment by DrewScoggins** [comment]
I think that the issue here is in perf-prep.sh. We download the tests from the last good build from ci, but we pull it from master. We should have that script take a parameter so that we can pull the test build from the release branches.

**Comment by maririos** [comment]
@DrewScoggins where does `perf-prep.sh` lives? Is this infra related?

**Comment by maririos** [comment]
> I would call this infrastructure.

Yeah. Sounds like it. 
Could you move it to core-eng with the proper labels for FR Perf?

**Comment by DrewScoggins** [comment]
Issue moved to [dotnet/core-eng #4738](https://github.com/dotnet/core-eng/issues/4738) via [**ZenHub**](https://www.zenhub.com/)
