### ISSUE TITLE
[x64/Windows] Tests failed in x64_checked_windows_nt_corefx_jitstressregs0x10

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#20966]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_jitstressregs0x10/698/

**Failed tests:**
```
System.Tests.MathFTests.Min
System.Tests.MathFTests.Max
System.Tests.MathTests.Max_Double
System.Tests.MathTests.Min_Single
System.Tests.MathTests.Min_Double
System.Tests.MathTests.Max_Single
```

**Log:**
```
System.Tests.MathFTests.Min [FAIL]
        Assert.Equal() Failure
        Expected: NaN
        Actual:   -Infinity
        Stack Trace:
          D:\j\workspace\x64_checked_w---1d068d3b\_\fx\src\System.Runtime.Extensions\tests\System\MathF.netcoreapp.cs(930,0): at System.Tests.MathFTests.Min()
      System.Tests.MathFTests.Max [FAIL]
        Assert.Equal() Failure
        Expected: NaN
        Actual:   Infinity
        Stack Trace:
          D:\j\workspace\x64_checked_w---1d068d3b\_\fx\src\System.Runtime.Extensions\tests\System\MathF.netcoreapp.cs(920,0): at System.Tests.MathFTests.Max()
      System.Tests.MathTests.Max_Double [FAIL]
        Assert.Equal() Failure
        Expected: NaN
        Actual:   Infinity
        Stack Trace:
          D:\j\workspace\x64_checked_w---1d068d3b\_\fx\src\System.Runtime.Extensions\tests\System\Math.cs(1068,0): at System.Tests.MathTests.Max_Double()
    Finished:    System.Numerics.Vectors.Tests
      System.Tests.MathTests.Min_Single [FAIL]
  === TEST EXECUTION SUMMARY ===
        Assert.Equal() Failure
        Expected: NaN
        Actual:   -Infinity
        Stack Trace:
          D:\j\workspace\x64_checked_w---1d068d3b\_\fx\src\System.Runtime.Extensions\tests\System\Math.cs(1189,0): at System.Tests.MathTests.Min_Single()
     System.Numerics.Vectors.Tests  Total: 1150, Errors: 0, Failed: 0, Skipped: 0, Time: 26.799s
      System.Tests.MathTests.Min_Double [FAIL]
  ----- end 11:54:50.22 ----- exit code 0 ----------------------------------------------------------
        Assert.Equal() Failure
      System.Tests.MathTests.Max_Single [FAIL]
        Expected: NaN
        Actual:   -Infinity
        Stack Trace:
          D:\j\workspace\x64_checked_w---1d068d3b\_\fx\src\System.Runtime.Extensions\tests\System\Math.cs(1151,0): at System.Tests.MathTests.Min_Double()
        Assert.Equal() Failure
        Expected: NaN
        Actual:   Infinity
        Stack Trace:
          D:\j\workspace\x64_checked_w---1d068d3b\_\fx\src\System.Runtime.Extensions\tests\System\Math.cs(1106,0): at System.Tests.MathTests.Max_Single()
```

**Comment by BruceForstall** [comment]
@tannergooding That file is only used for the corefx "innerloop" test runner currently. All the "corefx_X" jobs use the old mechanism (run-corefx-tests.py) and those currently have NO exclusion mechanism for x86/x64 -- which is one of their biggest problems.

**Comment by tannergooding** [comment]
Ah, then it should be resolved after the CoreFX side changes finish going through (assuming they aren't using a stale copy: https://github.com/dotnet/coreclr/pull/20920#issuecomment-437535193).

**Comment by BruceForstall** [comment]
run-corefx-tests.py always clones and uses the latest corefx master branch for testing.

**Comment by tannergooding** [comment]
This should be resolved now.
