### ISSUE TITLE
delete_existing_wrappers() function in tests\runtest.py does not support Unicode file names

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21049]
**Jobs:**

- https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitstress2_tiered/119/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitstressregs1/355/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_jitx86hwintrinsicnosimd/292/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstress2_jitstressregs0x10/357/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstressregs2/359/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_jitstressregs4/357/
- https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/x86_arm_altjit_checked_windows_nt/2572/

**One of the log:**
```
Traceback (most recent call last):
  File "D:\j\workspace\x64_arm64_alt---49bb15a9\tests\runtest.py", line 2099, in <module>
    sys.exit(main(args))
  File "D:\j\workspace\x64_arm64_alt---49bb15a9\tests\runtest.py", line 2069, in main
    args.test_env)
  File "D:\j\workspace\x64_arm64_alt---49bb15a9\tests\runtest.py", line 2027, in do_setup
    build_test_wrappers(host_os, arch, build_type, coreclr_repo_location, test_location, args.altjit_arch)
  File "D:\j\workspace\x64_arm64_alt---49bb15a9\tests\runtest.py", line 1514, in build_test_wrappers
    delete_existing_wrappers(test_location)
  File "D:\j\workspace\x64_arm64_alt---49bb15a9\tests\runtest.py", line 1483, in delete_existing_wrappers
    delete_existing_wrappers(os.path.join(test_location, item))
  File "D:\j\workspace\x64_arm64_alt---49bb15a9\tests\runtest.py", line 1483, in delete_existing_wrappers
    delete_existing_wrappers(os.path.join(test_location, item))
  File "D:\j\workspace\x64_arm64_alt---49bb15a9\tests\runtest.py", line 1477, in delete_existing_wrappers
    assert os.path.isdir(test_location) or os.path.isfile(test_location)
AssertionError
```

**Comment by AriNuer** [comment]
Similar path issue with #20826

**Comment by echesakovMSFT** [comment]
The problem with this is that **tests\runtest.py** does not support Unicode file names such as in https://github.com/dotnet/coreclr/pull/19270

> Similar path issue with #20826

This is a completely different issue related to corefx repo switching to arcade
