### ISSUE TITLE
Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by shimingsg** [dotnet/coreclr#21050]
failed in job: https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_scenarios_Windows_NT_x64_min_opt_ryujit/1071

failed log:

```
/jenkins/jobs/dotnet_coreclr/jobs/perf/jobs/master/jobs/perf_throughput_linux_arm_build/builds/669/archive/bin/Product/Linux.arm.Release/bin/libDllImportPath_U?n?i?c?o?d?e.so to /home/ubuntu/jenkins/w/dotnet_coreclr/perf/master/perf_throughput_Ubuntu14.04_full_opt_arm/bin/Product/Linux.arm.Release/bin/libDllImportPath_U?n?i?c?o?d?e.so
21:12:18 java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/ubuntu/jenkins/w/dotnet_coreclr/perf/master/perf_throughput_Ubuntu14.04_full_opt_arm/bin/Product/Linux.arm.Release/bin/libDllImportPath_U?n?i?c?o?d?e.so
21:12:18 	at sun.nio.fs.UnixPath.encode(UnixPath.java:147)
21:12:18 	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
21:12:18 	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
21:12:18 	at java.io.File.toPath(File.java:2234)
21:12:18 	at hudson.FilePath$36.invoke(FilePath.java:1900)
21:12:18 Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 167.220.2.11/167.220.2.11:7357
21:12:18 		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
21:12:18 		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
21:12:18 		at hudson.remoting.Channel.call(Channel.java:908)
21:12:18 		at hudson.FilePath.act(FilePath.java:986)
21:12:18 		at hudson.FilePath.act(FilePath.java:975)
21:12:18 		at hudson.FilePath.write(FilePath.java:1894)
21:12:18 		at hudson.plugins.copyartifact.FingerprintingCopyMethod.copyOne(FingerprintingCopyMethod.java:82)
21:12:18 		at hudson.plugins.copyartifact.FingerprintingCopyMethod.copyAll(FingerprintingCopyMethod.java:67)
21:12:18 		at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:526)
21:12:18 		at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:460)
21:12:18 		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
21:12:18 		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
21:12:18 		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
21:12:18 		at hudson.model.Build$BuildExecution.build(Build.java:206)
21:12:18 		at hudson.model.Build$BuildExecution.doRun(Build.java:163)
21:12:18 		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
21:12:18 		at hudson.model.Run.execute(Run.java:1724)
21:12:18 		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
21:12:18 		at hudson.model.ResourceController.execute(ResourceController.java:97)
21:12:18 		at hudson.model.Executor.run(Executor.java:429)
21:12:18 Caused: java.io.IOException
21:12:18 	at hudson.FilePath$36.invoke(FilePath.java:1903)
21:12:18 	at hudson.FilePath$36.invoke(FilePath.java:1894)
21:12:18 	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2760)
21:12:18 	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
21:12:18 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
21:12:18 	at hudson.remoting.Request$2.run(Request.java:358)
21:12:18 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
21:12:18 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
21:12:18 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
21:12:18 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
21:12:18 	at hudson.remoting.Engine$1$1.run(Engine.java:98)
21:12:18 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by maririos** [comment]
Job seems to be passing now

**Comment by maririos** [comment]
Another job passed, so closing this issue

**Comment by v-haren** [comment]
failed again:
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_Ubuntu14.04_full_opt_arm/661/
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_Ubuntu14.04_min_opt_arm/662/

**Comment by adiaaida** [comment]
@jashook I'm not sure who's working on arm right now, but we are starting to see an error in the arm throughput legs where there is a library that seems to have a malformed name. It started failing on Nov 15. The file that is causing problems is libDllImportPath_U�n�i�c�o�d�e.so. Do you, or whoever is working on arm, know if the name of this file is correct/where it came from? We could work around it, but if shouldn't be named like that, then we should get the real fix, rather than do a work around.

**Comment by jashook** [comment]
This seems similar to https://github.com/dotnet/coreclr/pull/21056.

**Comment by jashook** [comment]
See https://github.com/dotnet/coreclr/issues/21049. For that issue runtest.py was reading in the file location as ascii and adding the question marks of the unicode path.

**Comment by adiaaida** [comment]
Issue moved to [dotnet/core-eng #4694](https://github.com/dotnet/core-eng/issues/4694) via [**ZenHub**](https://www.zenhub.com/)
