### ISSUE TITLE
[x64/Linux] Method not found: 'System.Runtime.Intrinsics.Vector128`1<Single>

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21078]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_jitstress2/767/

**Failed tests:**
```
System.Numerics.Tests.Matrix4x4Tests.Matrix4x4UnaryNegationTest
System.Numerics.Tests.Matrix4x4Tests.Matrix4x4NegateTest
System.Numerics.Tests.Matrix4x4Tests.Matrix4x4MultiplyTest5
System.Numerics.Tests.Matrix4x4Tests.Matrix4x4LerpTest
System.Numerics.Tests.Matrix4x4Tests.Matrix4x4MultiplyTest6
```

**Log:**
```
System.Numerics.Tests.Matrix4x4Tests.Matrix4x4UnaryNegationTest [FAIL]
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Runtime.Intrinsics.Vector128`1<Single> System.Runtime.Intrinsics.X86.Sse.SetZeroVector128()'.
  [m[30;1m      Stack Trace:
  [m[37m           at System.Numerics.Matrix4x4.op_UnaryNegation(Matrix4x4 value)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress2/_/fx/src/System.Numerics.Vectors/tests/Matrix4x4Tests.cs(1200,0): at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4UnaryNegationTest()
      System.Numerics.Tests.Matrix4x4Tests.Matrix4x4NegateTest [FAIL]
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Runtime.Intrinsics.Vector128`1<Single> System.Runtime.Intrinsics.X86.Sse.SetZeroVector128()'.
  [m[30;1m      Stack Trace:
  [m[37m           at System.Numerics.Matrix4x4.op_UnaryNegation(Matrix4x4 value)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress2/_/fx/src/System.Numerics.Vectors/tests/Matrix4x4Tests.cs(1676,0): at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4NegateTest()
      System.Numerics.Tests.Matrix4x4Tests.Matrix4x4MultiplyTest5 [FAIL]
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Runtime.Intrinsics.Vector128`1<Single> System.Runtime.Intrinsics.X86.Sse.SetAllVector128(Single)'.
  [m[30;1m      Stack Trace:
  [m[37m           at System.Numerics.Matrix4x4.op_Multiply(Matrix4x4 value1, Single value2)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress2/_/fx/src/System.Numerics.Vectors/tests/Matrix4x4Tests.cs(1636,0): at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4MultiplyTest5()
      System.Numerics.Tests.Matrix4x4Tests.Matrix4x4LerpTest [FAIL]
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Runtime.Intrinsics.Vector128`1<Single> System.Runtime.Intrinsics.X86.Sse.SetAllVector128(Single)'.
  [m[30;1m      Stack Trace:
  [m[37m           at System.Numerics.Matrix4x4.Lerp(Matrix4x4 matrix1, Matrix4x4 matrix2, Single amount)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress2/_/fx/src/System.Numerics.Vectors/tests/Matrix4x4Tests.cs(1172,0): at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4LerpTest()
      System.Numerics.Tests.Matrix4x4Tests.Matrix4x4MultiplyTest6 [FAIL]
  [m[31;1m[m[37m      System.MissingMethodException : Method not found: 'System.Runtime.Intrinsics.Vector128`1<Single> System.Runtime.Intrinsics.X86.Sse.SetAllVector128(Single)'.
  [m[30;1m      Stack Trace:
  [m[37m           at System.Numerics.Matrix4x4.op_Multiply(Matrix4x4 value1, Single value2)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstress2/_/fx/src/System.Numerics.Vectors/tests/Matrix4x4Tests.cs(1647,0): at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4MultiplyTest6()
  [m[37m  Finished:    System.Numerics.Vectors.Tests
```

**Comment by tannergooding** [comment]
This should be resolved now, we merged the fix for this yesterday as part of normal codeflow.
