### ISSUE TITLE
Tests failure: Dev10_630880_cmd: NullReferenceException

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21173]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_jitstressregs4/681/
**Failed test:**
reflection_regression._dev10bugs_Dev10_630880_Dev10_630880_._dev10bugs_Dev10_630880_Dev10_630880_cmd

**Failed log:**
```
reflection_regression._dev10bugs_Dev10_630880_Dev10_630880_._dev10bugs_Dev10_630880_Dev10_630880_cmd [FAIL]
        
  Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
           at Dev10_630880.Main() in D:\j\workspace\x86_checked_w---b7304e59\tests\src\reflection\regression\dev10bugs\dev10_630880.cs:line 20
  
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_checked_w---b7304e59\bin\tests\Windows_NT.x86.Checked\Reports\reflection.regression\dev10bugs\Dev10_630880\Dev10_630880.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---b7304e59\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" Dev10_630880.exe 
        Getting type of System.AppDomainManager.
        Getting type handle of System.AppDomainManager type.
        Expected: 100
        Actual: -1073741819
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x86_checked_w---b7304e59\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
  > D:\j\workspace\x86_checked_w---b7304e59\bin\tests\Windows_NT.x86.Checked\reflection\regression\dev10bugs\Dev10_630880\Dev10_630880.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_checked_w---b7304e59\bin\tests\Windows_NT.x86.Checked\TestWrappers\reflection.regression\reflection.regression.XUnitWrapper.cs(179,0): at reflection_regression._dev10bugs_Dev10_630880_Dev10_630880_._dev10bugs_Dev10_630880_Dev10_630880_cmd()
```

**Comment by BruceForstall** [comment]
I also see this for Linux/arm32:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_forcerelocs_tst/32/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_gcstress0xc_tst/36/consoleFull

**Comment by BruceForstall** [comment]
https://ci.dot.net/job/dotnet_coreclr/job/master/job/arm_cross_checked_ubuntu_tst/210/consoleFull

**Comment by BruceForstall** [comment]
Also, x64: https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/checked_windows_nt/10787/

Looks like it's due to https://github.com/dotnet/coreclr/pull/21157

**Comment by BruceForstall** [comment]
This has been fixed
