### ISSUE TITLE
[Linux/arm32] Test Failed: corefx System.Net.NameResolution.Functional.Tests failure

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#21224]
JitStressRegs=1

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/33/consoleFull

```
13:37:04 >>>>> /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Net.NameResolution.Functional.Tests
13:37:04 
13:37:04 Running tests in /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm
13:37:04 timeout --kill-after=30s 20m ./RunTests.sh /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm
13:37:04 
13:37:04 ----- start 21:36:33 =============== To repro directly: =====================================================
13:37:04 pushd .
13:37:04 #!/usr/bin/env bash export COMPlus_TieredCompilation=0 export COMPlus_JitStressRegs=1
13:37:04 chmod +x /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm/dotnet
13:37:04 /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/testhost/netcoreapp-Linux-Release-arm/dotnet xunit.console.dll System.Net.NameResolution.Functional.Tests.dll  -xml testResults.xml -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests  -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
13:37:04 popd
13:37:04 ===========================================================================================================
13:37:04 /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm
13:37:04 xUnit.net Console Runner v2.4.1-pre.build.4059 (32-bit .NET Core 4.6.27124.0)
13:37:04 [37m  Discovering: System.Net.NameResolution.Functional.Tests (method display = ClassAndMethod, method display options = None)
13:37:04 [m[37m  Discovered:  System.Net.NameResolution.Functional.Tests (found 53 test cases)
13:37:04 [m[37m  Starting:    System.Net.NameResolution.Functional.Tests (parallel test collections = on, max threads = 4)
13:37:04 
[m[31;1m    System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName [FAIL]
13:37:04 [m[37m      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
13:37:04 [m[30;1m      Stack Trace:
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(208,0): at System.Net.Dns.ResolveCallback(Object context)
13:37:04 [m[37m        --- End of stack trace from previous location where exception was thrown ---
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(358,0): at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(383,0): at System.Net.Dns.EndGetHostByName(IAsyncResult asyncResult)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs(117,0): at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName()
13:37:04 [m[31;1m    System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName [FAIL]
13:37:04 [m[37m      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
13:37:04 [m[30;1m      Stack Trace:
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(32,0): at System.Net.Dns.GetHostByName(String hostName)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs(108,0): at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteGetHostByName_EmptyString_ReturnsHostName()
13:37:04 [m[31;1m    System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntry_HostString_Ok(hostName: "") [FAIL]
13:37:04 [m[37m      System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
13:37:04 [m[30;1m      Stack Trace:
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(404,0): at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs(26,0): at System.Net.NameResolution.Tests.GetHostEntryTest.<>c__DisplayClass1_0.<Dns_GetHostEntry_HostString_Ok>b__0()
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs(38,0): at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc)
13:37:04 [m[37m        --- End of stack trace from previous location where exception was thrown ---
13:37:04 [m[31;1m    System.Net.NameResolution.Tests.GetHostEntryTest.Dns_GetHostEntryAsync_HostString_Ok(hostName: "") [FAIL]
13:37:04 [m[37m      System.AggregateException : One or more errors occurred. (One or more errors occurred. (Name or service not known)) (One or more errors occurred. (Name or service not known))
13:37:04 [m[37m      ---- System.AggregateException : One or more errors occurred. (Name or service not known)
13:37:04 [m[37m      -------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
13:37:04 [m[37m      ---- System.AggregateException : One or more errors occurred. (Name or service not known)
13:37:04 [m[37m      -------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known
13:37:04 [m[30;1m      Stack Trace:
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(103,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(65,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/tests/FunctionalTests/GetHostEntryTest.cs(41,0): at System.Net.NameResolution.Tests.GetHostEntryTest.TestGetHostEntryAsync(Func`1 getHostEntryFunc)
13:37:04 [m[37m        --- End of stack trace from previous location where exception was thrown ---
13:37:04 [m[37m        ----- Inner Stack Trace #1 (System.AggregateException) -----
13:37:04 [m[37m        
13:37:04 [m[37m        ----- Inner Stack Trace -----
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(208,0): at System.Net.Dns.ResolveCallback(Object context)
13:37:04 [m[37m        --- End of stack trace from previous location where exception was thrown ---
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(358,0): at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(500,0): at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(590,0): at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult)
13:37:04 [m[37m           at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
13:37:04 [m[37m        ----- Inner Stack Trace #2 (System.AggregateException) -----
13:37:04 [m[37m        
13:37:04 [m[37m        ----- Inner Stack Trace -----
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(65,0): at System.Net.Dns.InternalGetHostByName(String hostName)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(208,0): at System.Net.Dns.ResolveCallback(Object context)
13:37:04 [m[37m        --- End of stack trace from previous location where exception was thrown ---
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(358,0): at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(500,0): at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult)
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/System.Net.NameResolution/src/System/Net/DNS.cs(590,0): at System.Net.Dns.<>c.<GetHostEntryAsync>b__27_1(IAsyncResult asyncResult)
13:37:04 [m[37m           at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
13:37:04 [m[37m        --- End of stack trace from previous location where exception was thrown ---
13:37:04 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(77,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
13:37:04 [m[37m  Finished:    System.Net.NameResolution.Functional.Tests
13:37:04 [m[37m=== TEST EXECUTION SUMMARY ===
13:37:04 [m[37m   System.Net.NameResolution.Functional.Tests  Total: 57, Errors: 0, Failed: 4, Skipped: 0, Time: 7.203s
13:37:04 [m[m/ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm
13:37:04 ----- end 21:37:04 ----- exit code 1 ----------------------------------------------------------
13:37:04 Looking around for any Linux dump...
13:37:04 ... found no dump in /ssd/j/workspace/dotnet_coreclr/master/jitstress/arm_cross_checked_ubuntu_corefx_jitstressregs1_tst/_/fx/artifacts/bin/tests/System.Net.NameResolution.Functional.Tests/netcoreapp-Linux-Release-arm
13:37:04 
error: One or more tests failed while running tests from ''.  Exit code 1.
13:37:04 <<<<<
```

**Comment by GrabYourPitchforks** [comment]
@BruceForstall Is the title of this issue correct? I don't see anything encoding-related in the stack trace.

**Comment by danmosemsft** [comment]
May be just flaky test. Similar failure: https://github.com/dotnet/corefx/issues/24355

**Comment by BruceForstall** [comment]
@danmosemsft If so, can someone figure out which are "flaky" and mark them so `/p:WithoutCategories=IgnoreForCI` skips them?

**Comment by stephentoub** [comment]
Is this a consistent repro?  I think it's more likely that the machine just isn't configured as we'd expect, e.g. that there are missing entries in the /etc/hosts file.
cc: @wfurt

**Comment by BruceForstall** [comment]
I believe it was consistent, with `COMPlus_JitStressRegs=1`, when I opened the issue. Of course, that indicates a JIT bug, if it requires that variable. It's been disabled from running since then (https://github.com/dotnet/coreclr/blob/master/tests/arm/corefx_linux_test_exclusions.txt), and nobody has tried to reproduce it, so it's not clear how consistent the repro is, or what configuration is required.

**Comment by VincentBu** [comment]
[System.Net.NameResolution.Tests.GetHostByNameTest/DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName](https://mc.dot.net/#/user/coreclr-corefx/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190618.1/workItem/System.Net.NameResolution.Functional.Tests/analysis/xunit/System.Net.NameResolution.Tests.GetHostByNameTest~2FDnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName) failed with this message:
```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : Name or service not known

at System.Net.Dns.InternalGetHostByName(String hostName) in /_/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 65
   at System.Net.Dns.ResolveCallback(Object context) in /_/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 208
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) in /_/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 358
   at System.Net.Dns.EndGetHostByName(IAsyncResult asyncResult) in /_/src/System.Net.NameResolution/src/System/Net/DNS.cs:line 383
   at System.Net.NameResolution.Tests.GetHostByNameTest.DnsObsoleteBeginEndGetHostByName_EmptyString_ReturnsHostName() in /_/src/System.Net.NameResolution/tests/FunctionalTests/GetHostByNameTest.cs:line 119
```

**Comment by stephentoub** [comment]
Dup of https://github.com/dotnet/corefx/issues/24355.  Something appears to have changed recently in CI that's causing this to occur much more frequently.

**Comment by wfurt** [comment]
I think we use Azure hosted machines now instead of old CI pool.

cc: @safern @ViktorHofer

**Comment by BruceForstall** [comment]
Also note that we just started running corefx tests in coreclr repo much more frequently (we were barely running them after Jenkins shut down), including with many JIT stress modes.

**Comment by safern** [comment]
> I think we use Azure hosted machines now instead of old CI pool.

That doesn't affect the tests, the Azure Hosted Machines are for build purposes not for test execution. The test pools are the same.

What probably changed is either that we're no running arm tests to run inside a docker container or that we disabled the helix retry feature?

**Comment by BruceForstall** [comment]
Too old; closing
