### ISSUE TITLE
Thousands of tests failed with System.NullReferenceException in x86_arm_altjit_checked_windows_nt_corefx_jitstress2

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21295]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress2/361/

**One of failed log:**
```
System.Numerics.Tests.GenericVectorTests.DivisionInt64 [FAIL]
        System.NullReferenceException : Object reference not set to an instance of an object.
        Stack Trace:
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\Microsoft.CSharp\src\Microsoft\CSharp\RuntimeBinder\SymbolTable.cs(280,0): at Microsoft.CSharp.RuntimeBinder.SymbolTable.CreateInheritanceHierarchyList(Type type)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\Microsoft.CSharp\src\Microsoft\CSharp\RuntimeBinder\SymbolTable.cs(75,0): at Microsoft.CSharp.RuntimeBinder.SymbolTable.PopulateSymbolTableWithName(String name, IEnumerable`1 typeArguments, Type callingType)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\Microsoft.CSharp\src\Microsoft\CSharp\RuntimeBinder\CSharpBinaryOperationBinder.cs(41,0): at Microsoft.CSharp.RuntimeBinder.CSharpBinaryOperationBinder.PopulateSymbolTableWithName(Type callingType, ArgumentObject[] arguments)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\Microsoft.CSharp\src\Microsoft\CSharp\RuntimeBinder\RuntimeBinder.cs(64,0): at Microsoft.CSharp.RuntimeBinder.RuntimeBinder.Bind(ICSharpBinder payload, Expression[] parameters, DynamicMetaObject[] args, DynamicMetaObject& deferredBinding)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\Microsoft.CSharp\src\Microsoft\CSharp\RuntimeBinder\BinderHelper.cs(93,0): at Microsoft.CSharp.RuntimeBinder.BinderHelper.Bind(ICSharpBinder action, RuntimeBinder binder, DynamicMetaObject[] args, IEnumerable`1 arginfos, DynamicMetaObject onBindingError)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\Microsoft.CSharp\src\Microsoft\CSharp\RuntimeBinder\CSharpBinaryOperationBinder.cs(130,0): at Microsoft.CSharp.RuntimeBinder.CSharpBinaryOperationBinder.FallbackBinaryOperation(DynamicMetaObject target, DynamicMetaObject arg, DynamicMetaObject errorSuggestion)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Linq.Expressions\src\System\Dynamic\DynamicMetaObject.cs(241,0): at System.Dynamic.DynamicMetaObject.BindBinaryOperation(BinaryOperationBinder binder, DynamicMetaObject arg)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Linq.Expressions\src\System\Dynamic\BinaryOperationBinder.cs(70,0): at System.Dynamic.BinaryOperationBinder.Bind(DynamicMetaObject target, DynamicMetaObject[] args)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Linq.Expressions\src\System\Dynamic\DynamicMetaObjectBinder.cs(90,0): at System.Dynamic.DynamicMetaObjectBinder.Bind(Object[] args, ReadOnlyCollection`1 parameters, LabelTarget returnLabel)
     System.IO.FileSystem.Tests: [Long Running Test] 'System.IO.Tests.File_Copy_str_str.CopyFileWithData_MemberData', Elapsed: 00:45:28
  [Long Running Test] 'System.IO.Tests.FileInfo_CopyTo_str_b.CopyFileWithData_MemberData', Elapsed: 00:37:32
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Linq.Expressions\src\System\Runtime\CompilerServices\CallSiteBinder.cs(129,0): at System.Runtime.CompilerServices.CallSiteBinder.BindCore[T](CallSite`1 site, Object[] args)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Linq.Expressions\src\System\Dynamic\UpdateDelegates.Generated.cs(262,0): at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Numerics.Vectors\tests\Util.cs(121,0): at System.Numerics.Tests.Util.Divide[T](T left, T right)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(807,0): at System.Numerics.Tests.GenericVectorTests.<>c__DisplayClass248_0`1.<TestDivision>b__2(Int32 index, T val)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(2696,0): at System.Numerics.Tests.GenericVectorTests.ValidateVector[T](Vector`1 vector, Action`2 indexValidationFunc)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(804,0): at System.Numerics.Tests.GenericVectorTests.TestDivision[T]()
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Numerics.Vectors\tests\GenericVectorTests.cs(788,0): at System.Numerics.Tests.GenericVectorTests.DivisionInt64()
```

**Comment by sandreenko** [comment]
It is a new regression from one of 16 commits in this PR, cc @AndyAyersMS, @dotnet/jit-contrib .

**Comment by AndyAyersMS** [comment]
Single def propagation is too aggressive updating return spill temps. For instance if a callee has two return points and returns a base class from one and a derived from another we may mistakenly update the return spill temp type to the derived type.

Working on fix now.
