### ISSUE TITLE
[x64/windows] System.Runtime.InteropServices.Tests failed in x64_checked_windows_nt_corefx_baseline

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21398]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/709/#showFailuresLink
**Failed tests:**
System.Runtime.InteropServices.Tests.GetComInterfaceForObjectTests.GetComInterfaceForObject_ObjectNotCollectible_ThrowsNotSupportedException
System.Runtime.InteropServices.Tests.ChangeWrapperHandleStrengthTests.ChangeWrapperHandleStrength_ObjectNotCollectible_ThrowsNotSupportedException
System.Runtime.InteropServices.Tests.CreateAggregatedObjectTests.CreateAggregatedObject_ObjectNotCollectible_ReturnsExpected
System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariantForObject_ObjectNotCollectible_ThrowsNotSupportedException
System.Runtime.InteropServices.Tests.GetIUnknownForObjectTests.GetIUnknownForObject_ObjectNotCollectible_ThrowsNotSupportedException
**Failed log:**
```
Discovering: System.Runtime.InteropServices.Tests (method display = ClassAndMethod, method display options = None)
    Discovered:  System.Runtime.InteropServices.Tests (found 563 of 616 test cases)
    Starting:    System.Runtime.InteropServices.Tests (parallel test collections = on, max threads = 4)
      System.Runtime.InteropServices.Tests.ChangeWrapperHandleStrengthTests.ChangeWrapperHandleStrength_ObjectNotCollectible_ThrowsNotSupportedException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.NotSupportedException)
        Actual:   (No exception was thrown)
        Stack Trace:
          D:\j\workspace\x64_checked_w---a7bd363e\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\ChangeWrapperHandleStrengthTests.cs(66,0): at System.Runtime.InteropServices.Tests.ChangeWrapperHandleStrengthTests.ChangeWrapperHandleStrength_ObjectNotCollectible_ThrowsNotSupportedException()
      System.Runtime.InteropServices.Tests.GetComInterfaceForObjectTests.GetComInterfaceForObject_ObjectNotCollectible_ThrowsNotSupportedException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.NotSupportedException)
        Actual:   typeof(System.InvalidCastException): Specified cast is not valid.
        ---- System.InvalidCastException : Specified cast is not valid.
        Stack Trace:
             at System.Runtime.InteropServices.Marshal.GetComInterfaceForObjectNative(Object o, Type t, Boolean onlyInContext, Boolean fEnalbeCustomizedQueryInterface)
          D:\j\workspace\x64_checked_w---a7bd363e\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\GetComInterfaceForObjectTests.cs(220,0): at System.Runtime.InteropServices.Tests.GetComInterfaceForObjectTests.<>c__DisplayClass15_0.<GetComInterfaceForObject_ObjectNotCollectible_ThrowsNotSupportedException>b__0()
          ----- Inner Stack Trace -----
             at System.Runtime.InteropServices.Marshal.GetComInterfaceForObjectNative(Object o, Type t, Boolean onlyInContext, Boolean fEnalbeCustomizedQueryInterface)
          D:\j\workspace\x64_checked_w---a7bd363e\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\GetComInterfaceForObjectTests.cs(220,0): at System.Runtime.InteropServices.Tests.GetComInterfaceForObjectTests.<>c__DisplayClass15_0.<GetComInterfaceForObject_ObjectNotCollectible_ThrowsNotSupportedException>b__0()
      System.Runtime.InteropServices.Tests.CreateAggregatedObjectTests.CreateAggregatedObject_ObjectNotCollectible_ReturnsExpected [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.NotSupportedException)
        Actual:   (No exception was thrown)
        Stack Trace:
          D:\j\workspace\x64_checked_w---a7bd363e\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\CreateAggregatedObjectTests.cs(134,0): at System.Runtime.InteropServices.Tests.CreateAggregatedObjectTests.CreateAggregatedObject_ObjectNotCollectible_ReturnsExpected()
      System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariantForObject_ObjectNotCollectible_ThrowsNotSupportedException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.NotSupportedException)
        Actual:   (No exception was thrown)
        Stack Trace:
             at System.Runtime.InteropServices.Tests.GetNativeVariantForObjectTests.GetNativeVariantForObject_ObjectNotCollectible_ThrowsNotSupportedException()
      System.Runtime.InteropServices.Tests.GetIUnknownForObjectTests.GetIUnknownForObject_ObjectNotCollectible_ThrowsNotSupportedException [FAIL]
        Assert.Throws() Failure
        Expected: typeof(System.NotSupportedException)
        Actual:   (No exception was thrown)
        Stack Trace:
          D:\j\workspace\x64_checked_w---a7bd363e\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\Marshal\GetIUnknownForObjectTests.cs(39,0): at System.Runtime.InteropServices.Tests.GetIUnknownForObjectTests.GetIUnknownForObject_ObjectNotCollectible_ThrowsNotSupportedException()
    Finished:    System.Runtime.InteropServices.Tests
```

**Comment by AaronRobinsonMSFT** [comment]
@janvorli Looks like this is related to your collectable classes work. Anything I can do to help here?

**Comment by BruceForstall** [comment]
These also fail on x86

**Comment by BruceForstall** [comment]
Looks like https://github.com/dotnet/coreclr/pull/20919 probably introduced the failures.

**Comment by janvorli** [comment]
These tests are not valid anymore (they were testing that attempt to use COM interop for collectible classes would fail). They just need to be disabled using the tests\CoreFX\CoreFX.issues.json file. I'll send out a PR soon.

**Comment by BruceForstall** [comment]
@janvorli Can you disable them in CoreFX? The problem is that we run 2 types of corefx testing in coreclr: the "innerloop" (new) style, disabled by the file you reference, and the "old" style, with various files for disabling in tests\arm and tests\arm64, but no way to disable for x86/x64

**Comment by janvorli** [comment]
They were already deleted in corefx. The issue is that the corefx tests version we use in coreclr is old and still contains tests that were deleted from the corefx repo. That's why we have the tests\CoreFX\CoreFX.issues.json file so that we can disable them without updating the version. At least that's my understanding.

**Comment by BruceForstall** [comment]
When were they deleted? Our non-innerloop corefx tests (`corefx_baseline` and other `corefx_*` tests) always clone corefx master branch and build/run it. You're right about the corefx "innerloop" job using cached tests.

**Comment by janvorli** [comment]
They were deleted yesterday: https://github.com/dotnet/corefx/pull/33842
