### ISSUE TITLE
Microsoft.Azure.NotificationHubs throws error when sending notification to a tag with special characters (on linux-arm)

### ISSUE THREAD

**Issue by actionRadius** [dotnet/coreclr#21489]
Im using Microsoft.NETCore.App v2.0.0 and Microsoft.Azure.NotificationHubs v2.0.2.
The code is compiled with cmd: dotnet publish --self-contained -r linux-arm -c Release
Running on Raspberry PI 3 Model B.

the error is thrown at: 
`await hub.SendWindowsNativeNotificationAsync("<anyValidXml>", new List<string>{"Café"});`

StackTrace: 

> at Microsoft.Azure.NotificationHubs.NotificationHubClient.<SendRequestAsync>d__117.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.Azure.NotificationHubs.NotificationHubClient.<SendNotificationImplAsync>d__106.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
>    at CoreApp.Program.<doJob>d__5.MoveNext() in 

Message:

> An invalid tag(s) 'CafÃ©' was supplied. Valid tag characters are alphanumeric, _, @, -, ., : and #.TrackingId:

The above error comes up only from the linux environment. Works well on my Windows PC.
Could you please investigate, or advise if im doing something worng?
thank you in advance

**Comment by RussKeldorph** [comment]
@actionRadius Does this repro with v2.1 or v2.2?  If so, please share something, e.g. source code, we can use to reproduce it.
