### ISSUE TITLE
Assertion failed 'op1->gtIntConCommon.ImmedValCanBeFolded(this, tree->OperGet())'

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21483]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_centos7.1_r2r_tst/2767/#showFailuresLink
**Failed tests:**
JIT_Regression._CLR_x86_JIT_V1_2_M01_b18049_b18049_b18049_._CLR_x86_JIT_V1_2_M01_b18049_b18049_b18049_sh
JIT_Regression._CLR_x86_JIT_V1_QFE_b147816_b147816_b147816_._CLR_x86_JIT_V1_QFE_b147816_b147816_b147816_sh
**Failed log:**
JIT_Regression._CLR_x86_JIT_V1_2_M01_b18049_b18049_b18049_._CLR_x86_JIT_V1_2_M01_b18049_b18049_b18049_sh
```
JIT_Regression._CLR_x86_JIT_V1_2_M01_b18049_b18049_b18049_._CLR_x86_JIT_V1_2_M01_b18049_b18049_b18049_sh [FAIL]
        
        Assert failure(PID 117227 [0x0001c9eb], Thread: 117227 [0x1c9eb]): Assertion failed 'op1->gtIntConCommon.ImmedValCanBeFolded(this, tree->OperGet())' in '<Module>:main():int' (IL size 39)
        
            File: /mnt/resource/j/workspace/dotnet_coreclr/master/checked_centos7.1/src/jit/gentree.cpp Line: 13883
            Image: /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/crossgen
        
        /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/CLR-x86-JIT/V1.2-M01/b18049/b18049/b18049.sh: line 156: 117227 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/crossgen" /Platform_Assemblies_Paths $CORE_ROOT:$PWD/IL:$PWD /in b18049.org /out b18049.exe
        /n/nReturn code:      1/nRaw output file:      /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/Reports/JIT.Regression/CLR-x86-JIT/V1.2-M01/b18049/b18049/b18049.output.txt/nRaw output:/nBEGIN EXECUTION
        in takeLock
        /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root:/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/CLR-x86-JIT/V1.2-M01/b18049/b18049/IL:/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/CLR-x86-JIT/V1.2-M01/b18049/b18049 /in b18049.org /out b18049.exe
        Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
        Copyright (c) Microsoft Corporation.  All rights reserved.
        
        Crossgen failed with exitcode: 134
        in ReleaseLock
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/n> /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/CLR-x86-JIT/V1.2-M01/b18049/b18049/b18049.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/resource/j/workspace/dotnet_coreclr/master/checked_centos7.1/bin/tests/Linux.x64.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs(57999,0): at JIT_Regression._CLR_x86_JIT_V1_2_M01_b18049_b18049_b18049_._CLR_x86_JIT_V1_2_M01_b18049_b18049_b18049_sh()
```
JIT_Regression._CLR_x86_JIT_V1_QFE_b147816_b147816_b147816_._CLR_x86_JIT_V1_QFE_b147816_b147816_b147816_sh
```
JIT_Regression._CLR_x86_JIT_V1_QFE_b147816_b147816_b147816_._CLR_x86_JIT_V1_QFE_b147816_b147816_b147816_sh [FAIL]
        
        Assert failure(PID 19229 [0x00004b1d], Thread: 19229 [0x4b1d]): Assertion failed 'op1->gtIntConCommon.ImmedValCanBeFolded(this, tree->OperGet())' in '<Module>:main():int' (IL size 39)
        
            File: /mnt/resource/j/workspace/dotnet_coreclr/master/checked_centos7.1/src/jit/gentree.cpp Line: 13883
            Image: /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/crossgen
        
        /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/CLR-x86-JIT/V1-QFE/b147816/b147816/b147816.sh: line 156: 19229 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/crossgen" /Platform_Assemblies_Paths $CORE_ROOT:$PWD/IL:$PWD /in b147816.org /out b147816.exe
        /n/nReturn code:      1/nRaw output file:      /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/Reports/JIT.Regression/CLR-x86-JIT/V1-QFE/b147816/b147816/b147816.output.txt/nRaw output:/nBEGIN EXECUTION
        in takeLock
        /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/crossgen /Platform_Assemblies_Paths /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root:/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/CLR-x86-JIT/V1-QFE/b147816/b147816/IL:/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/CLR-x86-JIT/V1-QFE/b147816/b147816 /in b147816.org /out b147816.exe
        Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
        Copyright (c) Microsoft Corporation.  All rights reserved.
        
        Crossgen failed with exitcode: 134
        in ReleaseLock
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/n> /mnt/resource/j/workspace/dotnet_coreclr/master/x64_checked_centos7.1_r2r_tst/bin/tests/Linux.x64.Checked/JIT/Regression/CLR-x86-JIT/V1-QFE/b147816/b147816/b147816.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/resource/j/workspace/dotnet_coreclr/master/checked_centos7.1/bin/tests/Linux.x64.Checked/TestWrappers/JIT.Regression/JIT.Regression.XUnitWrapper.cs(53939,0): at JIT_Regression._CLR_x86_JIT_V1_QFE_b147816_b147816_b147816_._CLR_x86_JIT_V1_QFE_b147816_b147816_b147816_sh()
```

**Comment by BruceForstall** [comment]
@dotnet/jit-contrib

**Comment by BruceForstall** [comment]
Also x64 Ubuntu R2R job: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_ubuntu_r2r_tst/2646/

**Comment by BruceForstall** [comment]
Looks like this is due to https://github.com/dotnet/coreclr/pull/21463

**Comment by BruceForstall** [comment]
@jkotas Looks like your change #21463 causes a couple test failures due to assertions in the JIT. I could disable the tests temporarily if you think that's the right thing to do.

**Comment by jkotas** [comment]
These failures should be fixed by https://github.com/dotnet/coreclr/pull/21477

**Comment by jkotas** [comment]
Dup of #21466

**Comment by AndyAyersMS** [comment]
This assert happens upstream of the encoder assert that #21477 is fixing, and still repros with that fix.

Let me dig in a bit.

**Comment by AndyAyersMS** [comment]
`gtFoldExprConst` is unhappy with folding:
```
[000006] -----+------              /--*  CNS_INT(h) long   0x1f05c912920 static Fseq[a]
[000007] N------N-U--              *  GE        int
[000031] -----+------              \--*  CNS_INT(h) long   0x1f05c912920 static
```
I  think the assert is too aggressive? 

For relational folds we shouldn't care about foldable immediates. But we might still run into this for an add perhaps.

**Comment by AndyAyersMS** [comment]
Fix for relational seems simple enough, just broaden the cases allowed in `GenTreeIntConCommon::ImmedValCanBeFolded` to allow all comparison ops.

**Comment by BruceForstall** [comment]
How do we get to this point? (of trying to fold these handle constants)

**Comment by AndyAyersMS** [comment]
These are IL tests...
```
.data D_a = bytearray (30 31 32 33)

.field public static int32 a at D_a

.method static public int32 main() cil managed
{ .entrypoint
  .maxstack  3
  .locals (int32* V_0)
  ldsflda    int32 a
  stloc.0                  // p = &a

  ldloc.0
  ldsflda    int32 a
  bge.un.s   Label_Exit    // Compare p and &a if they are equal (of course they should be equal, so following should be dead code)
```
I suppose we could rewrite them to check equality.

We start with this input IL and morph propagates the local constant down and tries to fold the compare:
```
    [ 0]   0 (0x000) ldsflda 04000001
    [ 1]   5 (0x005) stloc.0

               [000004] ------------              *  STMT      void  (IL 0x000...  ???)
               [000001] ------------              |  /--*  CNS_INT(h) long   0x26947d62920 static Fseq[a]
               [000003] -A----------              \--*  ASG       long  
               [000002] D------N----                 \--*  LCL_VAR   long   V00 loc0         

    [ 0]   6 (0x006) ldloc.0
    [ 1]   7 (0x007) ldsflda 04000001
    [ 2]  12 (0x00c) bge.un.s

               [000009] ------------              *  STMT      void  (IL 0x006...  ???)
               [000008] ------------              \--*  JTRUE     void  
               [000006] ------------                 |  /--*  CNS_INT(h) long   0x26947d62920 static Fseq[a]
               [000007] N--------U--                 \--*  GE        int   
               [000005] ------------                    \--*  LCL_VAR   long   V00 loc0         
```

Previously RVA statics would probably cause the method to drop out of R2R so we'd never see this, and fragile NGEN likely does something different (non-relocs? haven't looked) and and jit time we'll have the actual addresses.
