### ISSUE TITLE
[arm64/linux] System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.AsyncMethodsDropsStateMachineAndExecutionContextUponCompletion failed with System.TimeoutException

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21577]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs8_tst/66/
**Failed test:**
System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.AsyncMethodsDropsStateMachineAndExecutionContextUponCompletion

**Failed log:**
```
~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs8_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs8_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64
[37m  Discovering: System.Threading.Tasks.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Threading.Tasks.Tests (found 530 of 706 test cases)
[m[37m  Starting:    System.Threading.Tasks.Tests (parallel test collections = on, max threads = 46)
[m[33;1m    System.Threading.Tasks.Tests.TaskSchedulerTests.GetTaskSchedulersForDebugger_DebuggerAttached_ReturnsAllSchedulers [SKIP]
[m[37m      Condition(s) not met: "DebuggerIsAttached"
[m[33;1m    System.Threading.Tasks.Tests.TaskSchedulerTests.GetScheduledTasksForDebugger_DebuggerAttached_ReturnsTasksFromCustomSchedulers [SKIP]
[m[37m      Condition(s) not met: "DebuggerIsAttached"
[m[31;1m    System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.AsyncMethodsDropsStateMachineAndExecutionContextUponCompletion [FAIL]
[m[37m      System.TimeoutException : Task timed out after 60000ms
[m[30;1m      Stack Trace:
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs8/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(54,0): at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter[TResult](Task`1 task, Int32 millisecondsTimeout)
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs8/_/fx/src/System.Threading.Tasks/tests/System.Runtime.CompilerServices/AsyncTaskMethodBuilderTests.cs(564,0): at System.Threading.Tasks.Tests.AsyncTaskMethodBuilderTests.AsyncMethodsDropsStateMachineAndExecutionContextUponCompletion()
[m[37m        --- End of stack trace from previous location where exception was thrown ---
[m[37m  Finished:    System.Threading.Tasks.Tests
[m[37m=== TEST EXECUTION SUMMARY ===
[m[37m   System.Threading.Tasks.Tests  Total: 635, Errors: 0, Failed: 1, Skipped: 2, Time: 87.805s
[m[m~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs8_tst/_/fx/artifacts/bin/tests/System.Threading.Tasks.Tests/netcoreapp-Linux-Release-arm64
----- end 15:21:35 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment]
The next run succeeded. I'm closing this as "random failure".

**Comment by BruceForstall** [comment]
I saw this fail again:
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_tst_prtest/35/consoleFull

@danmosemsft @wfurt Is there some improvement in robustness that can be made to this test?

**Comment by danmosemsft** [comment]
I am not sure who has context on this test - perhaps @stephentoub..

**Comment by stephentoub** [comment]
This is a dup of https://github.com/dotnet/corefx/issues/34852.

**Comment by danmosemsft** [comment]
In many of these timeout cases it would be nice if in the test we used a common wait such that X seconds was a failure but it waited eg 2X or 3X seconds before actually failing. In the failure it could log how long it took (if it did complete in 3X). That would help us tell from the log whether the test was just slow, or hung. If it is slow (eg because of this hardware) we can speed  up the test, or increase the timeout. If hung, we have to analyze the code, etc

**Comment by danmosemsft** [comment]
Ah yes thanks.
