### ISSUE TITLE
[Linux/arm64] System.Net.Sockets.Tests.SendReceive.ReceiveIovMaxUdp_SuccessOrMessageSize failures

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21576]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4_tst/64/testReport/
**Failed test:**
 System.Net.Sockets.Tests.SendReceive.ReceiveIovMaxUdp_SuccessOrMessageSize

**Failed log:**
```
~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4_tst/_/fx/artifacts/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4_tst/_/fx/artifacts/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Release-arm64
[37m  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
[m[37m  Discovered:  System.Net.Sockets.Tests (found 688 of 1052 test cases)
[m[37m  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 46)
[m[33;1m    System.Net.Sockets.Tests.KeepAliveTest.Socket_KeepAlive_RetryCount_Failure [SKIP]
[m[37m      Condition(s) not met: "IsWindowsBelow1703"
[m[33;1m    System.Net.Sockets.Tests.UnixDomainSocketTest.Socket_CreateUnixDomainSocket_Throws_OnWindows [SKIP]
[m[37m      Condition(s) not met: "IsSubWindows10"
[m[31;1m    System.Net.Sockets.Tests.SendReceive.ReceiveIovMaxUdp_SuccessOrMessageSize [FAIL]
[m[37m      Assert.True() Failure
[m[37m      Expected: True
[m[37m      Actual:   False
[m[30;1m      Stack Trace:
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4/_/fx/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(1104,0): at System.Net.Sockets.Tests.SendReceive.ReceiveIovMaxUdp_SuccessOrMessageSize()
[m[37m        --- End of stack trace from previous location where exception was thrown ---
[m[33;1m    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Success [SKIP]
[m[37m      Condition(s) not met: "SupportsRawSockets"
[m[33;1m   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.NetworkStreamTest.ReadWrite_Memory_LargeWrite_Success', Elapsed: 00:02:07
[m[37m  Finished:    System.Net.Sockets.Tests
[m[37m=== TEST EXECUTION SUMMARY ===
[m[37m   System.Net.Sockets.Tests  Total: 877, Errors: 0, Failed: 1, Skipped: 3, Time: 244.718s
[m[m~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4_tst/_/fx/artifacts/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Release-arm64
----- end 16:20:30 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment]
The next run succeeded. I'm closing this as "random failure".

**Comment by BruceForstall** [comment]
I also saw it here:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/67/consoleFull

**Comment by BruceForstall** [comment]
It appears this test fails fairly regularly, e.g.:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/67/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/63/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/53/consoleFull

**Comment by wfurt** [comment]
I could not reproduce it locally:
```
  Finished:    System.Net.Sockets.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Sockets.Tests  Total: 1408, Errors: 0, Failed: 0, Skipped: 3, Time: 40.715s
toweinfu@ubunddarm64s-016:~/github/wfurt-corefx-arm/artifacts/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Debug-arm64$ ../../../testhost/netcoreapp-Linux-Debug-arm64/dotnet xunit.console.dll System.Net.Socke
```
so it definitely seems like flaky test. This may be timing or it may be UDP loss under load. One option would be to disable this on ARM to reduce noise if rest of socket is passing.

**Comment by BruceForstall** [comment]
@danmosemsft suggested we simply disable any System.Net test or test assembly that exhibits flakiness. We don't currently have a retry mechanism, which apparently we do have for corefx repo CI System.Net tests run in Helix.

**Comment by wfurt** [comment]
ok. I'll do that. I don't really like the retry strategy but I think noisy tests are worse.

**Comment by BruceForstall** [comment]
@wfurt I saw this fail again last night (Linux/arm64):
https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst_prtest/38/consoleFull

```
00:28:21 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst_prtest/_/fx/artifacts/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst_prtest/_/fx/artifacts/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Release-arm64
00:28:21 [37m  Discovering: System.Net.Sockets.Tests (method display = ClassAndMethod, method display options = None)
00:28:21 [m[37m  Discovered:  System.Net.Sockets.Tests (found 689 of 1053 test cases)
00:28:21 [m[37m  Starting:    System.Net.Sockets.Tests (parallel test collections = on, max threads = 46)
00:28:21 [m[33;1m    System.Net.Sockets.Tests.KeepAliveTest.Socket_KeepAlive_RetryCount_Failure [SKIP]
00:28:21 [m[37m      Condition(s) not met: "IsWindowsBelow1703"
00:28:21 [m[33;1m    System.Net.Sockets.Tests.UnixDomainSocketTest.Socket_CreateUnixDomainSocket_Throws_OnWindows [SKIP]
00:28:21 [m[37m      Condition(s) not met: "IsSubWindows10"
00:28:21 
[m[31;1m    System.Net.Sockets.Tests.SendReceive.ReceiveIovMaxUdp_SuccessOrMessageSize [FAIL]
00:28:21 [m[37m      Assert.True() Failure
00:28:21 [m[37m      Expected: True
00:28:21 [m[37m      Actual:   False
00:28:21 [m[30;1m      Stack Trace:
00:28:21 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_prtest/_/fx/src/System.Net.Sockets/tests/FunctionalTests/SendReceive.cs(1126,0): at System.Net.Sockets.Tests.SendReceive.ReceiveIovMaxUdp_SuccessOrMessageSize()
00:28:21 [m[37m        --- End of stack trace from previous location where exception was thrown ---
00:28:21 [m[33;1m    System.Net.Sockets.Tests.CreateSocket.Ctor_Raw_Success [SKIP]
00:28:21 [m[37m      Condition(s) not met: "SupportsRawSockets"
00:28:21 [m[33;1m   System.Net.Sockets.Tests: [Long Running Test] 'System.Net.Sockets.Tests.NetworkStreamTest.ReadWrite_Memory_LargeWrite_Success', Elapsed: 00:02:07
00:28:21 [m[37m  Finished:    System.Net.Sockets.Tests
00:28:21 [m[37m=== TEST EXECUTION SUMMARY ===
00:28:21 [m[37m   System.Net.Sockets.Tests  Total: 879, Errors: 0, Failed: 1, Skipped: 3, Time: 241.893s
00:28:21 [m[m~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst_prtest/_/fx/artifacts/bin/tests/System.Net.Sockets.Tests/netcoreapp-Linux-Release-arm64
00:28:21 ----- end 00:28:21 ----- exit code 1 ----------------------------------------------------------
```

**Comment by wfurt** [comment]
do you know if this is running in the 2core container @BruceForstall ? It is maybe interesting that ReadWrite_Memory_LargeWrite_Success is still running in background.

**Comment by BruceForstall** [comment]
I don't think so; I think we're still using the many-core raw hardware configuration.
