### ISSUE TITLE
ERROR: Failed to archive artifacts: bin-Product-Linux.arm.Release.tgz

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21595]
**Job:**
https://ci2.dot.net/job/dotnet_coreclr/job/perf/job/master/job/perf_throughput_linux_arm_build/918/
**Failed log:**
```
Product binaries are available at /mnt/j/w/dotnet_coreclr/perf/master/perf_throughput_linux_arm_build/bin/Product/Linux.arm.Release
[perf_throughput_linux_arm_build] $ /bin/sh -xe /tmp/jenkins3436873242099032768.sh
+ tar -czf bin-Product-Linux.arm.Release.tgz bin/Product/Linux.arm.Release
[Current build status] check if current [SUCCESS] is worse or equals then [SUCCESS] and better or equals then [SUCCESS]
Run condition [Current build status] enabling perform for step [[Archive the artifacts]]
Archiving artifacts
ERROR: Failed to archive artifacts: bin-Product-Linux.arm.Release.tgz
Command close created at
	at hudson.remoting.Command.<init>(Command.java:60)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1219)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1217)
	at hudson.remoting.Channel.close(Channel.java:1391)
	at hudson.remoting.Channel.close(Channel.java:1358)
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1224)
Caused: hudson.remoting.Channel$OrderlyShutdown
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1225)
	at hudson.remoting.Channel$1.handle(Channel.java:560)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:87)
Caused: java.io.IOException
	at hudson.remoting.FastPipedInputStream.read(FastPipedInputStream.java:169)
	at hudson.util.HeadBufferingStream.read(HeadBufferingStream.java:61)
	at com.jcraft.jzlib.InflaterInputStream.fill(InflaterInputStream.java:175)
	at com.jcraft.jzlib.InflaterInputStream.read(InflaterInputStream.java:106)
	at org.apache.commons.compress.archivers.tar.TarArchiveInputStream.read(TarArchiveInputStream.java:614)
	at java.io.InputStream.read(InputStream.java:101)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
	at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
	at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
	at hudson.util.IOUtils.copy(IOUtils.java:40)
	at hudson.FilePath.readFromTar(FilePath.java:2307)
Also:   <cycle to hudson.remoting.Channel$OrderlyShutdown>
	Caused: hudson.remoting.RequestAbortedException
		at hudson.remoting.Request.abort(Request.java:329)
		at hudson.remoting.Channel.terminate(Channel.java:992)
		at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1225)
		at hudson.remoting.Channel$1.handle(Channel.java:560)
		at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:87)
	Caused: java.util.concurrent.ExecutionException
		at hudson.remoting.Request$1.get(Request.java:308)
		at hudson.remoting.Request$1.get(Request.java:229)
		at hudson.remoting.FutureAdapter.get(FutureAdapter.java:59)
		at hudson.FilePath.copyRecursiveTo(FilePath.java:2224)
Caused: java.io.IOException: Failed to extract /mnt/j/w/dotnet_coreclr/perf/master/perf_throughput_linux_arm_build/transfer of 1 files
	at hudson.FilePath.readFromTar(FilePath.java:2317)
	at hudson.FilePath.copyRecursiveTo(FilePath.java:2221)
	at jenkins.model.StandardArtifactManager.archive(StandardArtifactManager.java:61)
	at hudson.tasks.ArtifactArchiver.perform(ArtifactArchiver.java:245)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at org.jenkins_ci.plugins.flexible_publish.builder.FailFastBuilder.perform(FailFastBuilder.java:102)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$2.run(BuildStepRunner.java:110)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner$Fail.conditionalRun(BuildStepRunner.java:154)
	at org.jenkins_ci.plugins.run_condition.BuildStepRunner.perform(BuildStepRunner.java:105)
	at org.jenkins_ci.plugins.flexible_publish.strategy.FailFastExecutionStrategy.perform(FailFastExecutionStrategy.java:63)
	at org.jenkins_ci.plugins.flexible_publish.ConditionalPublisher.perform(ConditionalPublisher.java:206)
	at org.jenkins_ci.plugins.flexible_publish.FlexiblePublisher.perform(FlexiblePublisher.java:124)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1749)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Flexible publish' changed build result to FAILURE
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 2s
ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for dotnet_coreclr/perf/master/perf_throughput_linux_arm_build #918
Finished: FAILURE
```

**Comment by BruceForstall** [comment]
I don't see the problem in more recent builds
