### ISSUE TITLE
[JitStress] System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#21644]
```
Starting:    System.Xml.RW.RwFactory.Tests (parallel test collections = on, max threads = 4)
  * ExceptionTests - reported call stack:
     at System.Tests.ExceptionTests.ThrowAndRethrowOtherMethod(ValueTuple`3& rethrownExceptionStackFrame) in D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\ExceptionTests.cs:line 156
     at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod() in D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\ExceptionTests.cs:line 142
      System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod [FAIL]
        Assert.Equal() Failure
                        (pos 5)
        Expected: ThrowAndRethrowOtherMethod
        Actual:   ThrowStatementDoesNotResetExceptionStackLineOt���
                        (pos 5)
        Stack Trace:
          D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\ExceptionTests.cs(189,0): at System.Tests.ExceptionTests.VerifyCallStack(ValueTuple`3 expectedStackFrame, String reportedCallStack, Int32 skipFrames)
          D:\j\workspace\x64_checked_w---3eccb510\_\fx\src\System.Runtime\tests\System\ExceptionTests.cs(144,0): at System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod()

```

An issue with **System.Tests.ExceptionTests.ThrowStatementDoesNotResetExceptionStackLineOtherMethod [FAIL]** reproduces under the following environment
```
COMPlus_JitInlinePolicyRandom=2
COMPlus_JitStressModeNames=STRESS_RANDOM_INLINE
COMPlus_JitStressModeNamesOnly=1
COMPlus_JitStressRange=2880818700
COMPlus_TieredCompilation=0
```
The hash corresponds to the test method itself System.Tests.ExceptionTests:ThrowAndRethrowOtherMethod(byref)

**Comment by echesakovMSFT** [comment]
@erozenfeld https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_ubuntu_corefx_jitstress2/823/

**Comment by erozenfeld** [comment]
Windows ci link: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x64_checked_windows_nt_corefx_jitstress2/743/

**Comment by erozenfeld** [comment]
https://github.com/dotnet/corefx/pull/34653 fixed this issue.
