### ISSUE TITLE
NullReferenceException invoking System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)

### ISSUE THREAD

**Issue by tmm360** [dotnet/coreclr#21651]
I'm using netcoreapp2.2, .Net Core SDK 2.2.100 (x64) for an Asp.Net Core application.
The exception is not raised every time.

    System.NullReferenceException
      HResult=0x80004003
      Message=Object reference not set to an instance of an object.
      Source=System.Private.CoreLib
      StackTrace:
       at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
       at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
       at (... my project info ...)

**Comment by svick** [comment]
Can you reproduce the exception in a short console application?

If not, what is the key type in question and how are its `GetHashCode` and `Equals` implemented? Are you doing something unusual with the dictionary, like accessing it from multiple threads?

**Comment by tmm360** [comment]
Now I've updated the SDK to 2.2.101, I've tried another time and have received a different exception on the same dictionary, but into another line of code:

    System.InvalidOperationException
      HResult=0x80131509
      Message=Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
      Source=System.Private.CoreLib
      StackTrace:
       at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported()
       at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
       at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
       at (... my project info ...)

So definitely yes! I'm doing something of odd with threading... My fault.

**Comment by benaadams** [comment]
For info https://github.com/dotnet/corefx/issues/31186
