### ISSUE TITLE
Tests failed in x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x80

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21664]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstressregs0x80/388/#showFailuresLink
**Failed tests:**
System.Collections.Tests.Hashtable_SyncRootTests.SyncRoot
System.Collections.Tests.DictionaryBaseTests.SyncRoot
System.Collections.Specialized.Tests.StringDictionarySyncRootTests.SyncRoot(count: 0)
System.Collections.Specialized.Tests.StringDictionarySyncRootTests.SyncRoot(count: 5)

**Failed log:**
```
System.Collections.Tests.Hashtable_SyncRootTests.SyncRoot [FAIL]
        Assert.NotEqual() Failure
        Expected: Not []
        Actual:   []
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---29fc8c6b\_\fx\src\System.Collections.NonGeneric\tests\HashtableTests.cs(1212,0): at System.Collections.Tests.Hashtable_SyncRootTests.SyncRoot()
        Assert.NotEqual() Failure
        Expected: Not []
        Actual:   []
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---29fc8c6b\_\fx\src\System.Collections.NonGeneric\tests\DictionaryBaseTests.cs(298,0): at System.Collections.Tests.DictionaryBaseTests.SyncRoot()
      System.Collections.Tests.DictionaryBaseTests.SyncRoot [FAIL]
```
```
Discovered:  System.Collections.Specialized.Tests (found 620 test cases)
    Starting:    System.Collections.Specialized.Tests (parallel test collections = on, max threads = 4)
      System.Collections.Specialized.Tests.StringDictionarySyncRootTests.SyncRoot(count: 0) [FAIL]
        Assert.IsType() Failure
        Expected: System.Object
        Actual:   System.Collections.Hashtable
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---29fc8c6b\_\fx\src\System.Collections.Specialized\tests\StringDictionary\StringDictionary.SyncRootTests.cs(22,0): at System.Collections.Specialized.Tests.StringDictionarySyncRootTests.SyncRoot(Int32 count)
      System.Collections.Specialized.Tests.StringDictionarySyncRootTests.SyncRoot(count: 5) [FAIL]
        Assert.IsType() Failure
        Expected: System.Object
        Actual:   System.Collections.Hashtable
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---29fc8c6b\_\fx\src\System.Collections.Specialized\tests\StringDictionary\StringDictionary.SyncRootTests.cs(22,0): at System.Collections.Specialized.Tests.StringDictionarySyncRootTests.SyncRoot(Int32 count)
    Finished:    System.Collections.Specialized.Tests
  === TEST EXECUTION SUMMARY ===
     System.Collections.Specialized.Tests  Total: 2122, Errors: 0, Failed: 2, Skipped: 0, Time: 12.986s
  ----- end 18:07:17.50 ----- exit code 1 ----------------------------------------------------------
```

**Comment by CarolEidt** [comment]
This is failing even without JitStressRegs. Investigating.

**Comment by CarolEidt** [comment]
@BruceForstall - I can't repro this, and now that we've eliminated the altjit jobs, should I just close this?

**Comment by BruceForstall** [comment]
Make sense. Closed.
