### ISSUE TITLE
Tests failed in x64_arm64_altjit_checked_windows_nt_corefx_jitstress1

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21684]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64_arm64_altjit/job/jitstress/job/x64_arm64_altjit_checked_windows_nt_corefx_jitstress1/395/
**Failed tests:**
System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryAsyncErrorTest
System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_Points
System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_Points
**Failed log:**
System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryAsyncErrorTest
```
System.Data.SqlClient.Tests.DiagnosticTest.ExecuteNonQueryAsyncErrorTest [FAIL]
        System.Diagnostics.RemoteExecutorTestBase+RemoteInvokeHandle+RemoteExecutionException : Remote process failed with an unhandled exception.
        Stack Trace:
          
          Child exception:
            System.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed during the post-login phase.  The connection could have timed out while waiting for server to complete the login process and respond; Or it could have timed out while attempting to create multiple active connections.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=321; handshake=2722; [Login] initialization=95; authentication=117; [Post-Login] complete=1851;  ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlInternalConnectionTds.cs(400,0): at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnectionFactory.cs(135,0): at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\Common\src\System\Data\ProviderBase\DbConnectionFactory.cs(109,0): at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs(677,0): at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs(1622,0): at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs(1082,0): at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionPool.cs(1049,0): at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\ProviderBase\DbConnectionFactory.cs(151,0): at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\Common\src\System\Data\ProviderBase\DbConnectionInternal.cs(325,0): at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs(1222,0): at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\src\System\Data\SqlClient\SqlConnection.cs(757,0): at System.Data.SqlClient.SqlConnection.Open()
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs(337,0): at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<<ExecuteNonQueryAsyncErrorTest>b__15_1>d.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs(898,0): at System.Data.SqlClient.Tests.DiagnosticTest.CollectStatisticsDiagnosticsAsync(Func`2 sqlOperation, String methodName)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Data.SqlClient\tests\FunctionalTests\DiagnosticTest.cs(342,0): at System.Data.SqlClient.Tests.DiagnosticTest.<>c.<ExecuteNonQueryAsyncErrorTest>b__15_0()
          ClientConnectionId:c94a8498-7002-4b39-a97c-8ddc54e4fade
          Error Number:-2,State:0,Class:11
          
          Child process:
            System.Data.SqlClient.Tests, Version=4.6.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Data.SqlClient.Tests.DiagnosticTest+<>c Int32 <ExecuteNonQueryAsyncErrorTest>b__15_0()
          
          
  Test: ConnectionOpenTest Enabled Listeners
    Finished:    System.Drawing.Common.Tests
  === TEST EXECUTION SUMMARY ===
     System.Drawing.Common.Tests  Total: 4507, Errors: 0, Failed: 2, Skipped: 0, Time: 106.021s
  TDSServerEndPoint ConnectionOpenTest Is Server Socket Bound: True Testing connectivity to the endpoint created for the server.
  ----- end 13:35:48.12 ----- exit code 1 ----------------------------------------------------------
```
System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_Points
```
System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_Points [FAIL]
        Assert.Equal() Failure
        Expected: Byte[] [142, 194, 251, 180, 222, ...]
  Test: ExecuteScalarAsyncErrorTest Listeners Disposed Successfully
        Actual:   Byte[] [212, 29, 140, 217, 143, ...]
        Stack Trace:
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Drawing.Common\tests\DrawingTest.cs(21,0): at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash)
  Test: ExecuteXmlReaderErrorTest Enabled Listeners
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Drawing.Common\tests\Graphics_DrawLineTests.cs(18,0): at System.Drawing.Tests.Graphics_DrawLineTests.DrawLines_Points()
```
System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_Points
```
System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_Points [FAIL]
        Assert.Equal() Failure
        Expected: Byte[] [208, 0, 8, 33, 6, ...]
  Test: ExecuteScalarAsyncErrorTest SqlOperation Successful
        Actual:   Byte[] [122, 252, 178, 214, 123, ...]
  Test: ExecuteScalarAsyncErrorTest Listeners Disabled
  TDSServerEndPoint ExecuteScalarAsyncErrorTest Connection Closed
        Stack Trace:
  Test: ExecuteScalarAsyncErrorTest Server Disposed
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Drawing.Common\tests\DrawingTest.cs(21,0): at System.Drawing.Tests.DrawingTest.ValidateImageContent(Image image, Byte[] expectedHash)
          D:\j\workspace\x64_arm64_alt---d32d0525\_\fx\src\System.Drawing.Common\tests\Graphics_DrawBezierTests.cs(28,0): at System.Drawing.Tests.Graphics_DrawBezierTests.DrawBezier_Points()
```

**Comment by AndyAyersMS** [comment]
I'll investigate.

**Comment by AndyAyersMS** [comment]
We don't seem to run the altjit jobs anymore -- we just run these natively. So the new link would be

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstress1_tst

The last two runs of this have timed out. Am going to trigger a new one.

**Comment by AndyAyersMS** [comment]
Seems odd that an altjitrun would run into non-assert failures that don't appear in  normal runs. After all we don't run the altjit-generated code, we throw it away.

Could be a timing issue, I suppose, as altjit runs take quite a bit longer to run (since every method is jitted 2x).

**Comment by AndyAyersMS** [comment]
Triggered run https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstress1_tst/25/ says it passed. Howver I am skeptical; it looks like it did not run any tests:
```
20:38:17 Using architecture: arm64
20:38:18 COREFX TEST PASS: 0, FAIL: 0, SKIPPED: 0, TOTAL: 0
```

**Comment by AndyAyersMS** [comment]
Possibly more relevant: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress1/

These seem to be hitting an infrastructure issue:
```
bash : error : setlocale: LC_ALL: cannot change locale (en_US.UTF-8) 
[/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1/_/fx/tempHome/.nuget/packages/microsoft.dotnet.arcade.sdk/1.0.0-beta.19121.4/tools/Tools.proj]
```
Seems like any failure here is likely covered by #18886 too.

**Comment by AndyAyersMS** [comment]
Infra issue tracked by #22823.

**Comment by AndyAyersMS** [comment]
Infrastructure issue now fixed, and the natively hosted jitstress1 job claims it passed, but also didn't actually run any tests:
```
00:49:22 Run condition [Current build status] enabling perform for step [[Archive the artifacts]]
00:49:22 Archiving artifacts
00:49:23 [WS-CLEANUP] Deleting project workspace...Cannot delete workspace :remote file operation failed: /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1 at hudson.remoting.Channel@6eeda6e0:ubuntu1604-20170925-1-8c1150: java.io.IOException: Unable to delete '/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1/.dotnet/LICENSE.txt'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
00:49:30 ERROR: Step ‘Delete workspace when build is done’ failed: Cannot delete workspace: remote file operation failed: /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1 at hudson.remoting.Channel@6eeda6e0:ubuntu1604-20170925-1-8c1150: java.io.IOException: Unable to delete '/mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress1/.dotnet/LICENSE.txt'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts.
00:49:30 Finished: SUCCESS
```

**Comment by AndyAyersMS** [comment]
Bruce pointed me at the right CI link (test leg, not build leg):

https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstress1_tst/130/

These are still not running properly.

**Comment by AndyAyersMS** [comment]
Will close and we can reopen if this recurs once we are on a better footing with CoreFx testing.
