### ISSUE TITLE
[arm] init-tools.cmd failed in arm_cross_checked_windows_nt_jitstress2_jitstressregs8_tst

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21740]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_jitstress2_jitstressregs8_tst/55/

**Failed tests:**
init-tools.cmd

**Failed log:**
```
C:\j\workspace\arm_cross_che---1418a2f7\init-tools.cmd
Traceback (most recent call last):
  File "C:\j\workspace\arm_cross_che---1418a2f7\tests\runtest.py", line 2324, in <module>
    sys.exit(main(args))
  File "C:\j\workspace\arm_cross_che---1418a2f7\tests\runtest.py", line 2298, in main
    lambda path: do_setup(host_os,
  File "C:\j\workspace\arm_cross_che---1418a2f7\tests\runtest.py", line 494, in create_and_use_test_env
    return func(test_env.name)
  File "C:\j\workspace\arm_cross_che---1418a2f7\tests\runtest.py", line 2307, in <lambda>
    path))
  File "C:\j\workspace\arm_cross_che---1418a2f7\tests\runtest.py", line 2193, in do_setup
    setup_tools(host_os, coreclr_repo_location)
  File "C:\j\workspace\arm_cross_che---1418a2f7\tests\runtest.py", line 1271, in setup_tools
    subprocess.check_output(command)
  File "c:\python\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\j\\workspace\\arm_cross_che---1418a2f7\\init-tools.cmd']' returned non-zero exit status 1
```

**Comment by BruceForstall** [comment]
Maybe this is the real issue?
```
02:02:15 C:\j\workspace\arm_cross_che---1418a2f7>C:\j\workspace\arm_cross_che---1418a2f7\tests\runtest.cmd arm Checked skipgeneratelayout 
02:02:15 RUNTEST: Searching for Visual Studio 2017 or 2015 installation
02:02:15 VS2017 not found, using VS2015
02:02:15 RUNTEST: Error: Visual Studio 2015 or 2017 required.
02:02:15        Please see https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md for build instructions.
02:02:15 python "C:\j\workspace\arm_cross_che---1418a2f7\tests\runtest.py" -arch arm -build_type Checked
02:06:04 Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to the remote server"
02:06:04 At line:1 char:249
02:06:04 + ... dentials; } $wc.DownloadFile('https://dotnetcli.azureedge.net/dotnet/ ...
02:06:04 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
02:06:04     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
02:06:04     + FullyQualifiedErrorId : WebException
02:06:04  
02:06:04 ERROR: Could not install dotnet cli correctly. 
02:06:04 Please check the detailed log that follows. 
```

Not sure what is supposed to happen here, but this is a Windows arm64 box running Windows arm32 tests, so it shouldn't be trying to check for VS. I don't know if it should try to install the CLI or not.
