### ISSUE TITLE
[x64] _interlocked_compareexchange_compareexchangedouble_compareexchangedouble_sh failed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21775]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_gcstress0xc_tst/101/
**Failed tests:**
GC_API._GC_Collect_Collect_._GC_Collect_Collect_sh
JIT_jit64._gc_misc_structret5_3_structret5_3_._gc_misc_structret5_3_structret5_3_sh
JIT_Methodical._eh_deadcode_deadnonlocalexit_d_deadnonlocalexit_d_._eh_deadcode_deadnonlocalexit_d_deadnonlocalexit_d_sh
JIT_Regression._CLR_x86_JIT_V1_M10_b04914_b04914_b04914_._CLR_x86_JIT_V1_M10_b04914_b04914_b04914_sh
JIT_Regression._JitBlue_GitHub_16892_GitHub_16892_GitHub_16892_._JitBlue_GitHub_16892_GitHub_16892_GitHub_16892_sh
JIT_Regression._CLR_x86_JIT_V1_M09_5_PDC_b12624_b12624_b12624_._CLR_x86_JIT_V1_M09_5_PDC_b12624_b12624_b12624_sh
Loader_classloader._TypeGeneratorTests_TypeGeneratorTest1188_Generated1188_Generated1188_._TypeGeneratorTests_TypeGeneratorTest1188_Generated1188_Generated1188_sh
**Logs:**
```
baseservices_threading._interlocked_compareexchange_compareexchangedouble_compareexchangedouble_._interlocked_compareexchange_compareexchangedouble_compareexchangedouble_sh [FAIL]
        Assertion Failed
        
           at System.Number.BigInteger.Multiply(BigInteger& lhs, BigInteger& rhs, BigInteger& result)
           at System.Number.BigInteger.Pow10(UInt32 exponent, BigInteger& result)
           at System.Number.AccumulateDecimalDigitsIntoBigInteger(NumberBuffer& number, UInt32 firstIndex, UInt32 lastIndex, BigInteger& result)
           at System.Number.NumberToFloatingPointBitsSlow(NumberBuffer& number, FloatingPointInfo& info, UInt32 positiveExponent, UInt32 integerDigitsPresent, UInt32 fractionalDigitsPresent)
           at System.Number.NumberToFloatingPointBits(NumberBuffer& number, FloatingPointInfo& info)
           at System.Number.NumberToDouble(NumberBuffer& number)
           at System.Number.TryParseDouble(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info, Double& result)
           at CompareExchangeDouble.CompareExchangeDouble.Main(String[] args) in /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/tests/src/baseservices/threading/interlocked/compareexchange/compareexchangedouble.cs:line 16
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/baseservices/threading/interlocked/compareexchange/compareexchangedouble/compareexchangedouble.sh: line 244: 104086 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" $ExePath $CLRTestExecutionArguments
        /n/nReturn code:      1/nRaw output file:      /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/baseservices/threading/Reports/baseservices.threading/interlocked/compareexchange/compareexchangedouble/compareexchangedouble.output.txt/nRaw output:/nBEGIN EXECUTION
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/corerun compareexchangedouble.exe /loops:100 /addVal:1.79769313486232E+304
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        /nTo run the test:/n> set CORE_ROOT=/mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/Tests/Core_Root/n> /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_gcstress0xc_tst/bin/tests/Linux.x64.Checked/baseservices/threading/interlocked/compareexchange/compareexchangedouble/compareexchangedouble.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu/bin/tests/Linux.x64.Checked/TestWrappers/baseservices.threading/baseservices.threading.XUnitWrapper.cs(13479,0): at baseservices_threading._interlocked_compareexchange_compareexchangedouble_compareexchangedouble_._interlocked_compareexchange_compareexchangedouble_compareexchangedouble_sh()
    Finished:    tracing.tracevalidation.XUnitWrapper
        /n/nReturn code:      1
```

**Comment by AndyAyersMS** [comment]
There was a missing pin in `BigInteger.Multiply` that is the likely culprit here. See notes #20538 and fix in #22334.

So, will close.
