### ISSUE TITLE
[x86] Tests failed to create a file with non-zero nanoseconds

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21798]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_jitstressregs1/687

**Failed tests:**
System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent

**Failed log:**
```
System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent [FAIL]
        Tests failed to create a file with non-zero nanoseconds.
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x86_checked_w---4c3d1b62\_\fx\src\System.IO.FileSystem\tests\FileInfo\GetSetTimes.cs(59,0): at System.IO.Tests.FileInfo_GetSetTimes.GetNonZeroNanoseconds()
          D:\j\workspace\x86_checked_w---4c3d1b62\_\fx\src\System.IO.FileSystem\tests\FileInfo\GetSetTimes.cs(129,0): at System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent()
```

**Comment by BruceForstall** [comment]
Subsequent runs don't show this failure, so closing.

cc @danmosemsft
