### ISSUE TITLE
[x86_arm_altjit] System.Diagnostics.Tests.ProcessTests.Process_StartWithArgumentsTest failed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21865]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86_arm_altjit/job/jitstress/job/x86_arm_altjit_checked_windows_nt_corefx_jitstress2/395/

**Failed test:**
System.Diagnostics.Tests.ProcessTests.Process_StartWithArgumentsTest

**Log:**
```
System.Diagnostics.Tests.ProcessTests.Process_StartWithArgumentsTest [FAIL]
        System.InvalidOperationException : Cannot process request because the process (4152) has exited.
        Stack Trace:
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(765,0): at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(800,0): at System.Diagnostics.Process.GetProcessHandle(Int32 access)
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs(91,0): at System.Diagnostics.Process.Kill()
          D:\j\workspace\x86_arm_altji---cebbbab6\_\fx\src\System.Diagnostics.Process\tests\ProcessTests.cs(1771,0): at System.Diagnostics.Tests.ProcessTests.Process_StartWithArgumentsTest()
```

**Comment by BruceForstall** [comment]
This failure doesn't exist in subsequent runs, so closing.

cc @danmosemsft
