### ISSUE TITLE
[profiler api] definemethod generic method problem

### ISSUE THREAD

**Issue by caozhiyuan** [dotnet/coreclr#21906]
i use IMetaDataImport2 find a generic method (ExecuteAsyncImpl) of type ，and use this method props define a renamed method, and copy il to new method, but C# code reflect this generic method returntype info get

```
Unhandled Exception: System.BadImageFormatException: Trying to load incorrect format programs 。 (Exception from HRESULT: 0x8007000B)
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Signature..ctor(IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.get_Signature()
   at System.Reflection.RuntimeMethodInfo.get_ReturnType()
```

C++ profiler sample code like this 

```
       const LPCWSTR typeNameToProb = L"StackExchange.Redis.ConnectionMultiplexer";
            mdTypeDef typeToProb;
            hr = metadata_import->FindTypeDefByName(
                typeNameToProb,
                mdTokenNil,
                &typeToProb);
            RETURN_OK_IF_FAILED(hr);

            LPCWSTR mdProbeNames[] = { L"ExecuteAsyncImpl",L"ExecuteSyncImpl", L"Configure" };
            for (LPCWSTR smdProbeName : mdProbeNames)
            {
                mdMethodDef mdProb;
                hr = metadata_import->FindMember(
                    typeToProb,
                    smdProbeName,
                    sigFunctionProbe.data(),
                    (DWORD)sigFunctionProbe.size(),
                    &mdProb);
                RETURN_OK_IF_FAILED(hr);

                trace::Info("FindMember"_W);

                DWORD       pdwAttr;
                PCCOR_SIGNATURE ppvSigBlob;
                ULONG       pcbSigBlob;
                ULONG       pulCodeRVA;
                DWORD       pdwImplFlags;
                hr = metadata_import->GetMethodProps(
                    mdProb,
                    nullptr,	   // Put method's class here. 
                    nullptr,		   // Put method's name here.  
                    0,			       // Size of szMethod buffer in wide chars.   
                    nullptr,		   // Put actual size here 
                    &pdwAttr,		   // Put flags here.  
                    &ppvSigBlob,       // [OUT] point to the blob value of meta data   
                    &pcbSigBlob,	   // [OUT] actual size of signature blob  
                    &pulCodeRVA,
                    &pdwImplFlags);
                RETURN_OK_IF_FAILED(hr);

                Info(pulCodeRVA);

                const WSTRING prefixStr = "Trace_"_W;
                WSTRING mdProbeWrapperName = prefixStr + WSTRING(smdProbeName);
                mdMethodDef mdWrapperProb;
                hr = pEmit->DefineMethod(
                    typeToProb,
                    mdProbeWrapperName.data(),
                    pdwAttr,
                    ppvSigBlob,
                    pcbSigBlob,
                    pulCodeRVA,
                    pdwImplFlags,
                    &mdWrapperProb);
                RETURN_OK_IF_FAILED(hr);

                trace::Info("DefineWrapperMethod"_W);

                LPCBYTE pMethodBytes;
                ULONG pMethodSize;
                hr = corProfilerInfo->GetILFunctionBody(moduleId, mdProb, &pMethodBytes, &pMethodSize);
                RETURN_OK_IF_FAILED(hr);

                trace::Info("GetILFunctionBody"_W);

                IMethodMalloc* pIMethodMalloc;
                hr = corProfilerInfo->GetILFunctionBodyAllocator(moduleId, &pIMethodMalloc);
                RETURN_OK_IF_FAILED(hr);

                LPBYTE pNewMethodBytes = (LPBYTE)pIMethodMalloc->Alloc(pMethodSize);
                pIMethodMalloc->Release();
                memcpy(pNewMethodBytes, pMethodBytes, pMethodSize);
                hr = corProfilerInfo->SetILFunctionBody(moduleId, mdWrapperProb, pNewMethodBytes);
                RETURN_OK_IF_FAILED(hr);

                trace::Info("SetILFunctionBody"_W);
            }            
```
no generic method (Trace_Configure) can reflect to run success, can anybody explain it?

**Comment by RussKeldorph** [comment]
@dotnet/dotnet-diag Not sure this is you.  Please re-label if appropriate.

**Comment by noahfalk** [comment]
The MethodDef signature (ppvSigBlob) contains type signatures for the various method parameters and return values, some of which probably refer to the generic type argument(s) on your method. This is done via an MVAR signature encoding that identifies an entry in the GenericParam table. The entries in the GenericParam table have an owner field that designates which MethodDef defined the generic parameter. You probably have Trace_Configure's signature referring to MVAR 0, but you haven't added entries to the GenericParam table to indicate that Trace_Configure has generic type parameters.

ECMA CLI section II.22.20 for info about GenericParam and II.23.2.1 for all things signature.  
http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-335.pdf

Hope that helps,
 -Noah

**Comment by caozhiyuan** [comment]
ok thanks. i loss copy params、 genericparams、 custom attribute。

**Comment by caozhiyuan** [comment]
ok it success ,thks @noahfalk  DefineGenericParam reserved must 0
