### ISSUE TITLE
[x64] Test failed: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Authentication_Test.SocketsHttpHandler_Authentication_Succeeds 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#21903]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_jitstressregs0x80/820/

**Failed test:**
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Authentication_Test.SocketsHttpHandler_Authentication_Succeeds

**Log:**
```
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Authentication_Test.SocketsHttpHandler_Authentication_Succeeds(authenticateHeader: "Digest realm=\"testrealm\", algorithm=md5-Sess, no"..., result: True) [FAIL]
  [m[31;1m[m[37m      Assert.Equal() Failure
  [m[37m      Expected: OK
  [m[37m      Actual:   Unauthorized
  [m[30;1m      Stack Trace:
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs0x80/_/fx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Authentication.cs(31,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Authentication_Test.<>c.<<-cctor>b__19_0>d.MoveNext()
  [m[37m        --- End of stack trace from previous location where exception was thrown ---
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs0x80/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(77,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs0x80/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(105,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs0x80/_/fx/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs(65,0): at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks, Int32 millisecondsTimeout)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs0x80/_/fx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Authentication.cs(59,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Authentication_Test.<>c__DisplayClass6_0.<<HttpClientHandler_Authentication_Succeeds>b__0>d.MoveNext()
  [m[37m        --- End of stack trace from previous location where exception was thrown ---
```

**Comment by BruceForstall** [comment]
This is a System.Net failure that didn't fail in the subsequent run; closing.

cc @danmosemsft
