### ISSUE TITLE
Intermittent failure to install native OSX dependencies in official builds

### ISSUE THREAD

**Issue by sbomer** [dotnet/coreclr#21910]
See the failing OSX build in https://dnceng.visualstudio.com/internal/_build/results?buildId=68976.
The error is as follows, during a `brew install`:
```
2019-01-09T13:02:12.5324730Z /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `initialize': no implicit conversion of nil into String (TypeError)
2019-01-09T13:02:12.5325920Z 	from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `new'
2019-01-09T13:02:12.5326790Z 	from /usr/local/Homebrew/Library/Homebrew/config.rb:39:in `<top (required)>'
2019-01-09T13:02:12.5327660Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2019-01-09T13:02:12.5328500Z 	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2019-01-09T13:02:12.5329490Z 	from /usr/local/Homebrew/Library/Homebrew/global.rb:25:in `<top (required)>'
2019-01-09T13:02:12.5330250Z 	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `require_relative'
2019-01-09T13:02:12.5330940Z 	from /usr/local/Homebrew/Library/Homebrew/brew.rb:13:in `<main>'
```

**Comment by chcosta** [comment]
@dotnet/dnceng is this a known issue?

**Comment by sbomer** [comment]
I have some experimental evidence that running `brew update` separately before `brew install` (as opposed to letting `brew install` do the auto-update) works around the issue.

**Comment by sbomer** [comment]
Apparently other teams are hitting this as well, and it was caused by https://github.com/Homebrew/brew/commit/9156d6def4b55acf6e9796f144f7af7551edecad. See https://github.com/Homebrew/brew/issues/5513 for more info. Workarounds include setting `HOMEBREW_LOGS` and running `brew update`. It sounds like the mac images will eventually be updated to a homebrew with the fix.

**Comment by RussKeldorph** [comment]
Tracks reverting #21913.
