### ISSUE TITLE
[x64\windows] AssemblyDependencyResolverTests failed in x64_checked_windows_nt_r2r_gcstress15

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#21975]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_r2r_gcstress15/129/testReport/
**Failed test:**
Loader_AssemblyDependencyResolverTests._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_cmd

**Failed log:**
```
Loader_AssemblyDependencyResolverTests._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_cmd [FAIL]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\Reports\Loader.AssemblyDependencyResolverTests\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests.output.txt
  Raw output:
  BEGIN EXECUTION
                1 file(s) copied.
        " D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\crossgen.exe" /Platform_Assemblies_Paths D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root;D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\Loader\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests\IL;D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\Loader\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests /in AssemblyDependencyResolverTests.org /out AssemblyDependencyResolverTests.exe
        Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
        Copyright (c) Microsoft Corporation.  All rights reserved.
        
        Native image AssemblyDependencyResolverTests.exe generated successfully.
         "D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" AssemblyDependencyResolverTests.exe 
        TestMissingHostPolicy Start
        TestMissingHostPolicy PASSED.
        TestComponentLoadFailure Start
        TestComponentLoadFailure FAILED:
        System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Xunit.Sdk.ThrowsException: Assert.Throws() Failure
        Expected: typeof(System.InvalidOperationException)
        Actual:   typeof(System.NullReferenceException): Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
           at AssemblyDependencyResolverTests.AssemblyDependencyResolver..ctor(String componentAssemblyPath) in D:\j\workspace\x64_checked_w---18f655dc\tests\src\Loader\AssemblyDependencyResolverTests\AssemblyDependencyResolver.cs:line 31
           at AssemblyDependencyResolverTests.AssemblyDependencyResolverTests.<TestComponentLoadFailure>b__4_1() in D:\j\workspace\x64_checked_w---18f655dc\tests\src\Loader\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests.cs:line 60
           at Xunit.Assert.RecordException(Action testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\Record.cs:line 28
           --- End of inner exception stack trace ---
           at Xunit.Assert.Throws(Type exceptionType, Exception exception) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 148
           at Xunit.Assert.Throws[T](Action testCode) in C:\Dev\xunit\xunit\src\xunit.assert\Asserts\ExceptionAsserts.cs:line 27
           at AssemblyDependencyResolverTests.AssemblyDependencyResolverTests.TestComponentLoadFailure() in D:\j\workspace\x64_checked_w---18f655dc\tests\src\Loader\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests.cs:line 56
           --- End of inner exception stack trace ---
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
           at AssemblyDependencyResolverTests.TestBase.<>c__DisplayClass18_1.<RunTestsForInstance>b__1() in D:\j\workspace\x64_checked_w---18f655dc\tests\src\Loader\AssemblyDependencyResolverTests\TestBase.cs:line 87
           at AssemblyDependencyResolverTests.TestBase.RunSingleTest(Action test, String testName) in D:\j\workspace\x64_checked_w---18f655dc\tests\src\Loader\AssemblyDependencyResolverTests\TestBase.cs:line 71
        TestComponentLoadFailureWithPreviousErrorWriter Start
        TestComponentLoadFailureWithPreviousErrorWriter PASSED.
        TestAssembly Start
        TestAssembly PASSED.
        TestAssemblyWithNoRecord Start
        TestAssemblyWithNoRecord PASSED.
        TestAssemblyWithMissingFile Start
        TestAssemblyWithMissingFile PASSED.
        TestSingleResource Start
        TestSingleResource PASSED.
        TestMutipleResourcesWithSameBasePath Start
        TestMutipleResourcesWithSameBasePath PASSED.
        TestMutipleResourcesWithDifferentBasePath Start
        TestMutipleResourcesWithDifferentBasePath PASSED.
        TestAssemblyWithNeutralCulture Start
        TestAssemblyWithNeutralCulture PASSED.
        TestSingleNativeDependency Start
        TestSingleNativeDependency PASSED.
        TestMultipleNativeDependencies Start
        TestMultipleNativeDependencies PASSED.
        TestSimpleNameAndNoPrefixAndNoSuffix Start
        TestSimpleNameAndNoPrefixAndNoSuffix PASSED.
        TestSimpleNameAndNoPrefixAndSuffix Start
        TestSimpleNameAndNoPrefixAndSuffix PASSED.
        TestSimpleNameAndLibPrefixAndNoSuffix Start
        TestSimpleNameAndLibPrefixAndNoSuffix PASSED.
        TestRelativeNameAndLibPrefixAndNoSuffix Start
        TestRelativeNameAndLibPrefixAndNoSuffix PASSED.
        TestSimpleNameAndLibPrefixAndSuffix Start
        TestSimpleNameAndLibPrefixAndSuffix PASSED.
        TestNameWithSuffixAndNoPrefixAndNoSuffix Start
        TestNameWithSuffixAndNoPrefixAndNoSuffix PASSED.
        TestNameWithSuffixAndNoPrefixAndSuffix Start
        TestNameWithSuffixAndNoPrefixAndSuffix PASSED.
        TestNameWithSuffixAndNoPrefixAndDoubleSuffix Start
        TestNameWithSuffixAndNoPrefixAndDoubleSuffix PASSED.
        TestNameWithSuffixAndPrefixAndNoSuffix Start
        TestNameWithSuffixAndPrefixAndNoSuffix PASSED.
        TestNameWithSuffixAndPrefixAndSuffix Start
        TestNameWithSuffixAndPrefixAndSuffix PASSED.
        TestRelativeNameWithSuffixAndPrefixAndSuffix Start
        TestRelativeNameWithSuffixAndPrefixAndSuffix PASSED.
        TestNameWithPrefixAndNoPrefixAndNoSuffix Start
        TestNameWithPrefixAndNoPrefixAndNoSuffix PASSED.
        TestNameWithPrefixAndPrefixAndNoSuffix Start
        TestNameWithPrefixAndPrefixAndNoSuffix PASSED.
        TestNameWithPrefixAndNoPrefixAndSuffix Start
        TestNameWithPrefixAndNoPrefixAndSuffix PASSED.
        TestNameWithPrefixAndPrefixAndSuffix Start
        TestNameWithPrefixAndPrefixAndSuffix PASSED.
        TestWindowsAddsSuffixEvenWithOnePresent Start
        TestWindowsAddsSuffixEvenWithOnePresent PASSED.
        TestWindowsDoesntAddSuffixWhenExectubaleIsPresent Start
        TestWindowsDoesntAddSuffixWhenExectubaleIsPresent PASSED.
        TestFullPathLookupWithMatchingFileName Start
        TestFullPathLookupWithMatchingFileName PASSED.
        TestFullPathLookupWithDifferentFileName Start
        TestFullPathLookupWithDifferentFileName PASSED.
        Expected: 100
        Actual: -1
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
  > D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\Loader\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests\AssemblyDependencyResolverTests.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---18f655dc\bin\tests\Windows_NT.x64.Checked\TestWrappers\Loader.AssemblyDependencyResolverTests\Loader.AssemblyDependencyResolverTests.XUnitWrapper.cs(109,0): at Loader_AssemblyDependencyResolverTests._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_._AssemblyDependencyResolverTests_AssemblyDependencyResolverTests_cmd()
```

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky Looks like `InnerException` is null.

https://github.com/dotnet/coreclr/blob/8b7d300c164971f573d8186e78204597a679c7d8/tests/src/Loader/AssemblyDependencyResolverTests/AssemblyDependencyResolver.cs#L31
