### ISSUE TITLE
[Linux/arm] JIT.Methodical/doublearray/dblarray3_cs Failure

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#22015]
The issue reproduces in AzDO on a Helix machine, but not locally. Also, doesn't happen in Jenkins CI (which I believe uses the same Helix queue).

```
+ export CORE_ROOT=/ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Payload
+ export __TestEnv=/ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Work/82284500-eaa8-4cdb-ba40-a5a0f06a2939/Unzip/SetStressModes_normal.sh
+ cat /ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Work/82284500-eaa8-4cdb-ba40-a5a0f06a2939/Unzip/SetStressModes_normal.sh
#!/usr/bin/env bash
+ /ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Payload/corerun /ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Payload/xunit.console.dll JIT.Methodical.XUnitWrapper.dll -parallel collections -nocolor -noshadow -xml testResults.xml -notrait category=outerloop -notrait category=failing
xUnit.net Console Runner v2.4.1 (32-bit .NET Core 4.6.27316.0)
  Discovering: JIT.Methodical.XUnitWrapper
  Discovered:  JIT.Methodical.XUnitWrapper
  Starting:    JIT.Methodical.XUnitWrapper
    JIT_Methodical._doublearray_dblarray3_cs_do_dblarray3_cs_do_._doublearray_dblarray3_cs_do_dblarray3_cs_do_sh [FAIL]
      /n/nReturn code:      1/nRaw output file:      /ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Work/82284500-eaa8-4cdb-ba40-a5a0f06a2939/Exec/Reports/JIT.Methodical/doublearray/dblarray3_cs_do/dblarray3_cs_do.output.txt/nRaw output:/nBEGIN EXECUTION
      /ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Payload/corerun dblarray3_cs_do.exe
      
      Generation 1
      Exception of type 'System.Exception' was thrown.
         at DblArray3.f2a() in /__w/1/s/tests/src/JIT/Methodical/doublearray/dblarray3.cs:line 83
         at DblArray3.Main() in /__w/1/s/tests/src/JIT/Methodical/doublearray/dblarray3.cs:line 143
      FAILED
      Expected: 100
      Actual: 255
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      /nTo run the test:/n> set CORE_ROOT=/ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Payload/n> /ssd/dotnetbuild/work/c54b1614-4a1c-4967-8a35-df73f23af1e0/Work/82284500-eaa8-4cdb-ba40-a5a0f06a2939/Exec/doublearray/dblarray3_cs_do/dblarray3_cs_do.sh/n
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/1/s/bin/tests/Linux.arm.Checked/TestWrappers/JIT.Methodical/JIT.Methodical.XUnitWrapper.cs(12009,0): at JIT_Methodical._doublearray_dblarray3_cs_do_dblarray3_cs_do_._doublearray_dblarray3_cs_do_dblarray3_cs_do_sh()
  Finished:    JIT.Methodical.XUnitWrapper
=== TEST EXECUTION SUMMARY ===
   JIT.Methodical.XUnitWrapper  Total: 749, Errors: 0, Failed: 1, Skipped: 0, Time: 209.057s
```

**Comment by AndyAyersMS** [comment]
This test allocates various objects and then checks the GC generation of the objects. The bit that failed above is:

https://github.com/dotnet/coreclr/blob/d466bdbd47ab7a861046b99340e16e037098fb2a/tests/src/JIT/Methodical/doublearray/dblarray3.cs#L78-L83

There is a chance GC happens between the allocation and the test. So seems likely this pattern is susceptible to random failures, perhaps especially so on a loaded machine.

**Comment by AndyAyersMS** [comment]
Though somewhat unexpectedly, this fails every time for me...
```
$ ./corerun ../../JIT/Methodical/doublearray/dblarray3_cs_do/dblarray3_cs_do.exe

Generation 1
Exception of type 'System.Exception' was thrown.
   at DblArray3.f2a() in /coreclr/tests/src/JIT/Methodical/doublearray/dblarray3.cs:line 83
   at DblArray3.Main() in /coreclr/tests/src/JIT/Methodical/doublearray/dblarray3.cs:line 143
FAILED
```

**Comment by AndyAyersMS** [comment]
Looks like the double array allocation triggers a gen0 GC... added a bit of instrumentation:
```C#
        double[][] arr = new double[1][];
        int gen = GC.GetGeneration(arr);
        Console.WriteLine($"f2a bef: gen {gen}, c0 {GC.CollectionCount(0)} c1 {GC.CollectionCount(1)}");
        var z = new double[1000];
        gen = GC.GetGeneration(arr);
        Console.WriteLine($"f2a mid: gen {gen}, c0 {GC.CollectionCount(0)} c1 {GC.CollectionCount(1)}");
        arr[0] = z;
        gen = GC.GetGeneration(arr);
        Console.WriteLine($"f2a aft: gen {gen}, c0 {GC.CollectionCount(0)} c1 {GC.CollectionCount(1)}");
```
and get
```
f2a bef: gen 0, c0 0 c1 0
f2a mid: gen 1, c0 1 c1 0
f2a aft: gen 1, c0 1 c1 0
Generation 1
Exception of type 'System.Exception' was thrown.
   at DblArray3.f2a()
   at DblArray3.Main()
FAILED
```
Wrapping the allocate / check sequence in a `TryStartNoGCRegion` is one option, if we want to fix this.

**Comment by AndyAyersMS** [comment]
In this test case we should not have allocated all that much that I can see.... let's measure:
```
;; bytes -> GC.GetAllocatedBytesForCurrentThread
;; total -> GC.GetTotalMemory(false)

AMD64
f2a bef: gen 0, c0 0 c1 0 bytes 121680 total 140456
f2a mid: gen 0, c0 0 c1 0 bytes 130480 total 148648
f2a aft: gen 0, c0 0 c1 0 bytes 131048 total 156776

ARM32
f2a bef: gen 0, c0 0 c1 0 bytes 163204 total 180676
f2a mid: gen 1, c0 1 c1 0 bytes 172008 total 155744
f2a aft: gen 1, c0 1 c1 0 bytes 172636 total 163936
```
So somewhat unexpectedly  at `bef` we have more allocated bytes on ARM32 than AMD64. Not sure yet if this is bug or there's some good explanation.

**Comment by AndyAyersMS** [comment]
FWIW this check in the test case should probably be modernized...looks like ~6 tests do something like this:
```C#
        Console.WriteLine(Environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE"));
        if (Environment.GetEnvironmentVariable("PROCESSOR_ARCHITECTURE") == "x86")
```
Opened #22694.

**Comment by AndyAyersMS** [comment]
Hmm, no pattern emerging. Need to drill in and look at the the heap.
```
Arm64 (Ubuntu 18.04)
f2a bef: gen 0, c0 0 c1 0 bytes 132752 total 151040
f2a mid: gen 0, c0 0 c1 0 bytes 141416 total 160872
f2a aft: gen 0, c0 0 c1 0 bytes 141728 total 160872

Amd64 (Ubuntu 18.04)
f2a bef: gen 0, c0 0 c1 0 bytes 229824 total 249864
f2a mid: gen 0, c0 0 c1 0 bytes 238240 total 258056
f2a after: gen 0, c0 0 c1 0 bytes 238552 total 258056
```

**Comment by AndyAyersMS** [comment]
Probably being too sloppy here and inadvertently mixing `dotnet` and `corerun` data; master, 3.0 preview, and 2.2, data, and data from release and checked builds. Need to measure the same kind of thing in all places. Will try and standardize on a release corerun from master.

**Comment by AndyAyersMS** [comment]
At any rate the test should not be sensitive to the amount of allocation done so far. Possible fixes:
* forbid gc between allocation and generation check
* force gc before each test

Might as well go the forbid GC route, then we can probably re-enable these for GC stress.

This allocate-test pattern is repeated a bunch of times in this test and in the other dblarray variants.

**Comment by AndyAyersMS** [comment]
Hmm, looks like GC stress doesn't respect the forbid GC regions. So won't try re-enabling stress after all.
```
Garbage collection was induced in NoGCRegion mode
   at System.GC.EndNoGCRegionWorker()
   at System.GC.EndNoGCRegion()
   at DblArray3.Run(Action f)
   at DblArray3.Main()
```
