### ISSUE TITLE
Unable to load shared library 'libproc' or one of its dependencies

### ISSUE THREAD

**Issue by tarurar** [dotnet/coreclr#22098]
Getting the error while trying to run `dotnet restore`:

> Unable to load shared library 'libproc' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(liblibproc, 1): image not found.
   at Interop.libproc.proc_pidpath(Int32 pid, Byte* buffer, UInt32 bufferSize)
   at Interop.libproc.proc_pidpath(Int32 pid)
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.ProcessStartInfoExtensions.Execute(ProcessStartInfo startInfo)
   at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp.Execute()
   at Microsoft.DotNet.Tools.Restore.RestoreCommand.Run(String[] args)
   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
   at Microsoft.DotNet.Cli.Program.Main(String[] args)

Environment:
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.103
 Commit:    8edbc2570a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.103/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.103 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
```

I definitely have the `libproc.dylib` library here `/usr/lib/libproc.dylib` but it looks like env doesn't know about it. The .net core installation was done from here: https://dotnet.microsoft.com/learn/dotnet/hello-world-tutorial.

**Comment by tarurar** [comment]
@adityamandaleeka , you was helping me before here https://github.com/dotnet/coreclr/issues/12672, but I had a long break since that time and the issue still exists.

**Comment by tarurar** [comment]
@AaronRobinsonMSFT that's correct. I've tried to remove net core completely from the syste, and install it again. No luck.

**Comment by jeffschwMSFT** [comment]
Closing in favor of dotnet/corefx#25157
