### ISSUE TITLE
[x86] Test failed: Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22109]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_gcstress0xc_zapdisable/114/

**Failed tests:**
Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_cmd

**Log:**
```
Interop_ICustomMarshaler._ConflictingNames_MultipleALCs_MultipleALCs_._ConflictingNames_MultipleALCs_MultipleALCs_cmd [FAIL]
        
  
  Return code:      1
  Raw output file:      D:\j\workspace\x86_checked_w---34329519\bin\tests\Windows_NT.x86.Checked\Reports\Interop.ICustomMarshaler\ConflictingNames\MultipleALCs\MultipleALCs.output.txt
  Raw output:
  BEGIN EXECUTION
         "D:\j\workspace\x86_checked_w---34329519\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" MultipleALCs.exe 
        System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
           at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDll(String unmanagedDllName, IntPtr gchManagedAssemblyLoadContext)
           at CustomMarshalers.CustomMarshalerTest.NativeParseInt(WrappedString str)
           at CustomMarshalers.CustomMarshalerTest.ParseInt(String str) in D:\j\workspace\x86_checked_w---34329519\tests\src\Interop\ICustomMarshaler\ConflictingNames\CustomMarshaler.cs:line 50
           --- End of inner exception stack trace ---
           at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
           at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
           at RunInALC.Run(AssemblyLoadContext context) in D:\j\workspace\x86_checked_w---34329519\tests\src\Interop\ICustomMarshaler\ConflictingNames\RunInALC.cs:line 48
           at RunInALC.ConflictingCustomMarshalerNamesInCollectibleLoadContexts_Succeeds() in D:\j\workspace\x86_checked_w---34329519\tests\src\Interop\ICustomMarshaler\ConflictingNames\RunInALC.cs:line 32
           at RunInALC.Main(String[] args) in D:\j\workspace\x86_checked_w---34329519\tests\src\Interop\ICustomMarshaler\ConflictingNames\RunInALC.cs:line 18
        Expected: 100
        Actual: 101
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
```

**Comment by jkoritzinsky** [comment]
Looks like somewhere in the runtime isn't keeping the custom ALC alive and the GC is collecting it. Adding a `GC.KeepAlive(context)` at the end of the `RunInALC.Run` method makes the test pass.
