### ISSUE TITLE
[x86] Index out of range exception in x86_checked_windows_nt_corefx

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22107]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_baseline/721/

**Failed jobs:**
System.Runtime.InteropServices.Tests.ArrayWithOffsetTests.Ctor_Array_Offset

**Log:**
```
System.Runtime.InteropServices.Tests.ArrayWithOffsetTests.Ctor_Array_Offset(array: [0, 0], offset: -1, expectedHashCode: 8) [FAIL]
        System.IndexOutOfRangeException : ArrayWithOffset: offset exceeds array size.
        Stack Trace:
             at System.Runtime.InteropServices.ArrayWithOffset..ctor(Object array, Int32 offset)
          D:\j\workspace\x86_checked_w---fbe14ed2\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\ArrayWithOffsetTests.cs(25,0): at System.Runtime.InteropServices.Tests.ArrayWithOffsetTests.Ctor_Array_Offset(Object array, Int32 offset, Int32 expectedHashCode)
    Finished:    System.Runtime.InteropServices.Tests
  === TEST EXECUTION SUMMARY ===
     System.Runtime.InteropServices.Tests  Total: 1650, Errors: 0, Failed: 1, Skipped: 0, Time: 11.631s
  ----- end 10:49:10.88 ----- exit code 1 ----------------------------------------------------------
```

**Comment by danmosemsft** [comment]
@AaronRobinsonMSFT

**Comment by jkotas** [comment]
Right, this is temporary coreclr/corefx mismatch.
