### ISSUE TITLE
CI aborts on x64_checked_osx10.12_innerloop_prtest

### ISSUE THREAD

**Issue by filipnavara** [dotnet/coreclr#22125]
This seems to happen very often now:

```
22:14:20 GitHub pull request #22122 of commit 51d44ce33ab82c23bbc3fbb9e1a28c9a35bc319a, no merge conflicts.
22:14:21 Setting status of 51d44ce33ab82c23bbc3fbb9e1a28c9a35bc319a to PENDING with url https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/12313/ and message: 'Started.'
22:14:21 Using context: OSX10.12 x64 Checked Innerloop Build and Test
22:14:21 Building remotely on OSX.1012.Amd64.Open-0121211312163-0 (dci-mac-build-082.local) (OSX.1012.Amd64.Open) in workspace /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/x64_checked_osx10.12_innerloop_flow_prtest@2
22:14:21 [WS-CLEANUP] Deleting project workspace...
22:14:21 [WS-CLEANUP] Done
22:14:21 Selected Git installation does not exist. Using Default
22:14:21 Cloning the remote Git repository
22:14:21 Cloning repository https://github.com/dotnet/coreclr
22:14:21  > git init /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/x64_checked_osx10.12_innerloop_flow_prtest@2 # timeout=10
22:14:21 Fetching upstream changes from https://github.com/dotnet/coreclr
22:14:21  > git --version # timeout=10
22:14:21  > git fetch --tags --progress https://github.com/dotnet/coreclr +refs/heads/*:refs/remotes/origin/* # timeout=90
22:16:12  > git config remote.origin.url https://github.com/dotnet/coreclr # timeout=10
22:16:12  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
22:16:12  > git config remote.origin.url https://github.com/dotnet/coreclr # timeout=10
22:16:12 Fetching upstream changes from https://github.com/dotnet/coreclr
22:16:12  > git fetch --tags --progress https://github.com/dotnet/coreclr +refs/pull/22122/*:refs/remotes/origin/pr/22122/* # timeout=90
22:16:14  > git rev-parse refs/remotes/origin/pr/22122/merge^{commit} # timeout=10
22:16:14  > git rev-parse refs/remotes/origin/origin/pr/22122/merge^{commit} # timeout=10
22:16:14 JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins-ci.org/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
22:16:14 Checking out Revision 36e9b0b7142f9909b228284240949cfffca09303 (refs/remotes/origin/pr/22122/merge)
22:16:14 Commit message: "Merge 51d44ce33ab82c23bbc3fbb9e1a28c9a35bc319a into 5c9febf6346f90c06e70b3cb9e002300e50fa54b"
22:16:14  > git config core.sparsecheckout # timeout=10
22:16:14  > git checkout -f 36e9b0b7142f9909b228284240949cfffca09303
22:16:50 First time build. Skipping changelog.
22:16:50 Schedule job dotnet_coreclr » master » x64_checked_osx10.12_innerloop_prtest
22:21:18 Build dotnet_coreclr » master » x64_checked_osx10.12_innerloop_prtest #11048 started
00:44:25 dotnet_coreclr » master » x64_checked_osx10.12_innerloop_prtest #11048 completed  : ABORTED
00:44:25 Setting status of 51d44ce33ab82c23bbc3fbb9e1a28c9a35bc319a to FAILURE with url https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/12313/ and message: 'Build finished. '
00:44:25 Using context: OSX10.12 x64 Checked Innerloop Build and Test
00:44:25 ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for dotnet_coreclr/master/x64_checked_osx10.12_innerloop_flow_prtest #12313
00:44:25 ERROR: Step ‘Delete workspace when build is done’ failed: no workspace for dotnet_coreclr/master/x64_checked_osx10.12_innerloop_flow_prtest #12313
00:44:25 Finished: ABORTED
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/12313/console
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/12320/console
https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/12321/console

**Comment by RussKeldorph** [comment]
I wonder if this could be due to additional pressure from the new CI systems.  @echesakovMSFT and @safern Could we disable the Jenkins submissions to the OSX queues in favor of the new CI like we did for ARM(64)?

@mattgal @mmitche

**Comment by MattGal** [comment]
The first two are "normal" failures simply indicating that a pattern of Xunit test results were expected to be found and weren't.  Perhaps the result file names got changed?

```
00:39:10 [xUnit] [INFO] - [xUnit.Net-v2 (default)] - No test report file(s) were found with the pattern '**/pal_tests.xml' relative to '/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/x64_checked_osx10.12_innerloop_prtest' for the testing framework 'xUnit.Net-v2 (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'xUnit.Net-v2 (default)'?
00:39:10 [xUnit] [ERROR] - No test reports found for the metric 'xUnit.Net' with the resolved pattern '**/pal_tests.xml'. Configuration error?.
```

The third does appear to be a network hangup issue, not with Helix machines but somewhere in Java code:
```
Jan 22, 2019 4:32:43 AM hudson.remoting.UserRequest perform
WARNING: LinkageError while performing UserRequest:UserRPCRequest(9,join)
java.lang.NoClassDefFoundError: hudson/util/ProcessTree$UnixReflection
	at hudson.util.ProcessTree$Unix.get(ProcessTree.java:578)
	at hudson.util.ProcessTree.killAll(ProcessTree.java:145)
	at hudson.Proc$LocalProc.destroy(Proc.java:384)
	at hudson.Proc$LocalProc.join(Proc.java:357)
	at hudson.Launcher$RemoteLaunchCallable$1.join(Launcher.java:1304)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.perform(RemoteInvocationHandler.java:922)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:896)
	at hudson.remoting.RemoteInvocationHandler$RPCRequest.call(RemoteInvocationHandler.java:853)
	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: hudson.util.ProcessTree$UnixReflection
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at hudson.remoting.RemoteClassLoader.findClass(RemoteClassLoader.java:159)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 21 more

Jan 22, 2019 4:32:43 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Terminated
Jan 22, 2019 4:32:43 AM hudson.remoting.Request$2 run
WARNING: Failed to send back a reply to the request hudson.remoting.Request$2@1a165cb9
hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:671)
	at hudson.remoting.Request$2.run(Request.java:370)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
	at java.lang.Thread.run(Thread.java:748)
Caused by: hudson.remoting.Channel$OrderlyShutdown
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1225)
	at hudson.remoting.Channel$1.handle(Channel.java:560)
	at hudson.remoting.AbstractByteBufferCommandTransport.processCommand(AbstractByteBufferCommandTransport.java:202)
	at hudson.remoting.AbstractByteBufferCommandTransport.receive(AbstractByteBufferCommandTransport.java:188)
	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onRead(ChannelApplicationLayer.java:186)
	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecv(ApplicationLayer.java:207)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processRead(SSLEngineFilterLayer.java:369)
	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecv(SSLEngineFilterLayer.java:117)
	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecv(ProtocolStack.java:669)
	at org.jenkinsci.remoting.protocol.NetworkLayer.onRead(NetworkLayer.java:136)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer.access$2200(BIONetworkLayer.java:48)
	at org.jenkinsci.remoting.protocol.impl.BIONetworkLayer$Reader.run(BIONetworkLayer.java:283)
	... 4 more
``` ... @mmitche may have more insight there, as noted elsewhere there's lots of reasons for random network hangups.

**Comment by filipnavara** [comment]
Still happens: https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_flow_prtest/12925/console

**Comment by MattGal** [comment]
Hi Filip.  I checked out the job you sent the link to and I believe if you sent the link you meant to that you might be mistaken.  

The actual run log from the link above is https://ci.dot.net/job/dotnet_coreclr/job/master/job/x64_checked_osx10.12_innerloop_prtest/11634/consoleFull, and from the logs it's failing because it's trying to find xml files that aren't there:

### Agent log:
```
INFO: Connected
Feb 04, 2019 5:51:42 AM org.jenkinsci.plugins.xunit.service.XUnitService infoSystemLogger
INFO: [xUnit] - [xUnit.Net-v2 (default)] - No test report file(s) were found with the pattern '**/pal_tests.xml' relative to '/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/x64_checked_osx10.12_innerloop_prtest' for the testing framework 'xUnit.Net-v2 (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'xUnit.Net-v2 (default)'?
Feb 04, 2019 5:51:42 AM org.jenkinsci.plugins.xunit.service.XUnitService errorSystemLogger
SEVERE: [xUnit] - No test reports found for the metric 'xUnit.Net' with the resolved pattern '**/pal_tests.xml'. Configuration error?.
Feb 04, 2019 5:57:42 AM hudson.remoting.jnlp.Main$CuiListener status
INFO: Terminated
```

**Comment by filipnavara** [comment]
@MattGal The log you linked to clearly says that the job is aborted due to timeout: `05:48:59 Build timed out (after 120 minutes). Marking the build as aborted.` Obviously that's way better information than I had before, so thanks for linking the log from the downstream job. Nevertheless it still is an issue if significant number of the jobs don't manage to finish in 2 hours.

**Comment by safern** [comment]
> Nevertheless it still is an issue if significant number of the jobs don't manage to finish in 2 hours.

I think it could be related to many jobs sending a lot of tests to Helix, because we're duplicating this payload on every PR in corefx and coreclr. However at least from corefx side, this should go away pretty soon once the pipelines triggers are resolved.

**Comment by echesakovMSFT** [comment]
coreclr doesn't use this queue in AzDO - we switched to OSX.1013.Amd64.Open

**Comment by MattGal** [comment]
(@echesakov  : this is the thread I thought I was replying to, the nearest log to this comment used 10.12)

**Comment by filipnavara** [comment]
I interpreted it as Azure Pipelines jobs running on different set (OSX.1013.Amd64.Open) than the Jenkins jobs (OSX.1012.something) thus spreading the load.
