### ISSUE TITLE
ComTypes.IConnectionPoint.Advise throws InvalidCastException

### ISSUE THREAD

**Issue by KexyBiscuit** [dotnet/coreclr#22250]
### Symptoms

The code was like...

```
SomeComObject.ExampleEvent += new SomeComType.SomeDelegate(SomeMethod);
```

### Exception details

```
System.InvalidCastException
  HResult=0x80004002
  Message=Specified cast is not valid.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.InteropServices.ComTypes.IConnectionPoint.Advise(Object pUnkSink, Int32& pdwCookie)
   at System.Runtime.InteropServices.ComEventsSink.Advise(Object rcw)
   at System.Runtime.InteropServices.ComEventsInfo.AddSink(Guid& iid)
   at System.Runtime.InteropServices.ComEventsHelper.Combine(Object rcw, Guid iid, Int32 dispid, Delegate d)
   at System.Runtime.InteropServices.ComAwareEventInfo.AddEventHandler(Object target, Delegate handler)
   (further StackTrace is omitted)
```

### Environment

```
C:\Users\KexyBiscuit> dotnet --version
3.0.100-preview-009812
```

```
<TargetFramework>netcoreapp3.0</TargetFramework>
```

**Comment by AaronRobinsonMSFT** [comment]
cc @jeffschwMSFT @onovotny
