### ISSUE TITLE
[arm64] Test failed: JIT_Performance._CodeQuality_Benchstones_BenchI_AddArray_AddArray_AddArray_._CodeQuality_Benchstones_BenchI_AddArray_AddArray_AddArray_sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22286]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/22/

**Failed tests:**
JIT_Performance._CodeQuality_Benchstones_BenchI_AddArray_AddArray_AddArray_._CodeQuality_Benchstones_BenchI_AddArray_AddArray_AddArray_sh
JIT_Performance._CodeQuality_Benchstones_BenchF_NewtR_NewtR_NewtR_._CodeQuality_Benchstones_BenchF_NewtR_NewtR_NewtR_sh
JIT_Performance._CodeQuality_Benchstones_BenchI_AddArray2_AddArray2_AddArray2_._CodeQuality_Benchstones_BenchI_AddArray2_AddArray2_AddArray2_sh

**Log:**
```
      JIT_Performance._CodeQuality_Benchstones_BenchI_AddArray_AddArray_AddArray_._CodeQuality_Benchstones_BenchI_AddArray_AddArray_AddArray_sh [FAIL]
        /n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/JIT/Performance/Reports/JIT.Performance/CodeQuality/Benchstones/BenchI/AddArray/AddArray/AddArray.output.txt/nRaw output:/nTest Harness Exitcode is : 137
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/JIT/Performance/CodeQuality/Benchstones/BenchI/AddArray/AddArray/AddArray.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.Performance/JIT.Performance.XUnitWrapper.cs(2909,0): at JIT_Performance._CodeQuality_Benchstones_BenchI_AddArray_AddArray_AddArray_._CodeQuality_Benchstones_BenchI_AddArray_AddArray_AddArray_sh()
      JIT_Performance._CodeQuality_Benchstones_BenchF_NewtR_NewtR_NewtR_._CodeQuality_Benchstones_BenchF_NewtR_NewtR_NewtR_sh [FAIL]
        /n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/JIT/Performance/Reports/JIT.Performance/CodeQuality/Benchstones/BenchF/NewtR/NewtR/NewtR.output.txt/nRaw output:/nTest Harness Exitcode is : 137
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/JIT/Performance/CodeQuality/Benchstones/BenchF/NewtR/NewtR/NewtR.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.Performance/JIT.Performance.XUnitWrapper.cs(2209,0): at JIT_Performance._CodeQuality_Benchstones_BenchF_NewtR_NewtR_NewtR_._CodeQuality_Benchstones_BenchF_NewtR_NewtR_NewtR_sh()
      JIT_Performance._CodeQuality_Benchstones_BenchI_AddArray2_AddArray2_AddArray2_._CodeQuality_Benchstones_BenchI_AddArray2_AddArray2_AddArray2_sh [FAIL]
        /n/nReturn code:      137/nRaw output file:      /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/JIT/Performance/Reports/JIT.Performance/CodeQuality/Benchstones/BenchI/AddArray2/AddArray2/AddArray2.output.txt/nRaw output:/nTest Harness Exitcode is : 137
        /nTo run the test:/n> set CORE_ROOT=/home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/Tests/Core_Root/n> /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_r2r_jitminopts_tst/bin/tests/Linux.arm64.Checked/JIT/Performance/CodeQuality/Benchstones/BenchI/AddArray2/AddArray2/AddArray2.sh/n
        Expected: True
        Actual:   False
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/arm64_cross_checked_ubuntu16.04/bin/tests/Linux.arm64.Checked/TestWrappers/JIT.Performance/JIT.Performance.XUnitWrapper.cs(2979,0): at JIT_Performance._CodeQuality_Benchstones_BenchI_AddArray2_AddArray2_AddArray2_._CodeQuality_Benchstones_BenchI_AddArray2_AddArray2_AddArray2_sh()
```

**Comment by AndyAyersMS** [comment]
Exit code 137 looks like it is probably an OOM kill. This test suite seems to have a few different random failures each time it runs. Based on our limited history these particular tests haven't failed before or since.

Suspect there is nothing actionable here as far as these tests go.

We should investigate what is leading to test processes getting killed like this. Perhaps we're overloading the test machines with too many concurrent test runs, or we're using more memory when testing than we should. At the very least we could grep the relevant log and confirm it is the OOM killer at work.

@RussKeldorph do you know of any relevant issue or ongoing work?

**Comment by AndyAyersMS** [comment]
See also #22287, #22368

**Comment by sandreenko** [comment]
The test stopped failing in ci after #22421
