### ISSUE TITLE
ArgumentOutOfRangeException When Tracing on Linux

### ISSUE THREAD

**Issue by brianrob** [dotnet/coreclr#2233]
When tracing on Linux, an ArgumentOutOfRangeException is thrown by the XplatEventLogger serialization code:

System.Threading.Tasks.TaskSchedulerException: An exception was thrown by a TaskScheduler. ---> System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at System.Diagnostics.Tracing.XplatEventLogger.Serialize(ReadOnlyCollection`1 payloadName, ReadOnlyCollection`1 payload, String sep)
   at System.Diagnostics.Tracing.XplatEventLogger.LogOnEventWritten(EventWrittenEventArgs eventData)
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
   --- End of inner exception stack trace ---
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* childActivityID, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
   at System.Threading.Tasks.TplEtwProvider.TaskScheduled(Int32 OriginatingTaskSchedulerID, Int32 OriginatingTaskID, Int32 TaskID, Int32 CreatingTaskID, Int32 TaskCreationOptions, Int32 appDomain)
   at System.Threading.Tasks.Task.ScheduleAndStart(Boolean needsProtection)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Dnx.ApplicationHost.Program.Main(String[] args)

**Comment by brianrob** [comment]
@ramarag can you please take a look at this?
