### ISSUE TITLE
[arm] Test failed: System.Runtime.Tests.MemoryFailPointTests.Ctor_LargeSizeInMegabytes_ThrowsInsufficientMemoryException

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22379]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_baseline_tst/54/

**Failed tests:**
System.Runtime.Tests.MemoryFailPointTests.Ctor_LargeSizeInMegabytes_ThrowsInsufficientMemoryException

**Log:**
```
System.Runtime.Tests.MemoryFailPointTests.Ctor_LargeSizeInMegabytes_ThrowsInsufficientMemoryException [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.InsufficientMemoryException)
      Actual:   typeof(System.IO.IOException): The parameter is incorrect.
      ---- System.IO.IOException : The parameter is incorrect.
      Stack Trace:
           at System.Runtime.MemoryFailPoint.MemFreeAfterAddress(Void* address, UInt64 size)
           at System.Runtime.MemoryFailPoint.CheckForFreeAddressSpace(UInt64 size, Boolean shouldThrow)
           at System.Runtime.MemoryFailPoint..ctor(Int32 sizeInMegabytes)
        D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Runtime\tests\System\Runtime\MemoryFailPointTests.cs(33,0): at System.Runtime.Tests.MemoryFailPointTests.<>c.<Ctor_LargeSizeInMegabytes_ThrowsInsufficientMemoryException>b__2_0()
        ----- Inner Stack Trace -----
           at System.Runtime.MemoryFailPoint.MemFreeAfterAddress(Void* address, UInt64 size)
           at System.Runtime.MemoryFailPoint.CheckForFreeAddressSpace(UInt64 size, Boolean shouldThrow)
           at System.Runtime.MemoryFailPoint..ctor(Int32 sizeInMegabytes)
        D:\j\workspace\arm_cross_che---99792267\_\fx\src\System.Runtime\tests\System\Runtime\MemoryFailPointTests.cs(33,0): at System.Runtime.Tests.MemoryFailPointTests.<>c.<Ctor_LargeSizeInMegabytes_ThrowsInsufficientMemoryException>b__2_0()
```

**Comment by BruceForstall** [comment]
@danmosemsft Just the name of this test makes me suspicious. Can you get someone who owns this to look at it?

**Comment by danmosemsft** [comment]
@BruceForstall Can you please check htat you have symbols for CoreFX bits, not just for the tests? It would be helpful to get line numbers in these traces.

**Comment by danmosemsft** [comment]
Probably ::VirtualQuery produced ERROR_INVALID_PARAMETER (if this is consistent, possibly due to some lower limit on ARM ?)

If that's the case, perhaps we should still throw InsufficientMemoryException...

**Comment by sandreenko** [comment]
The test was excluded in https://github.com/dotnet/coreclr/pull/22695.
