### ISSUE TITLE
[Linux/arm64] failure in corefx System.Diagnostics.Process.Tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#22430]
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/112/consoleFull

```
04:26:27 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Diagnostics.Process.Tests/netcoreapp-Linux-Release-arm64 ~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Diagnostics.Process.Tests/netcoreapp-Linux-Release-arm64
04:26:27 [37m  Discovering: System.Diagnostics.Process.Tests (method display = ClassAndMethod, method display options = None)
04:26:27 [m[37m  Discovered:  System.Diagnostics.Process.Tests (found 208 of 268 test cases)
04:26:27 [m[37m  Starting:    System.Diagnostics.Process.Tests (parallel test collections = on, max threads = 46)
04:26:27 [m[33;1m    System.Diagnostics.Tests.ProcessStartInfoTests.ShellExecute_Nano_Fails_Start [SKIP]
04:26:27 [m[37m      Condition(s) not met: "IsWindowsNanoServer"
04:26:27 [mLinux
04:26:27 Linux
04:26:27 Linux
04:26:27 Linux
04:26:27 None of the following programs were installed on this machine: xdg-open,gnome-open,kfmclient.
04:26:27 
04:26:27 Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
04:26:27    at System.IO.Pipes.PipeStream.WaitForPipeDrain() in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.IO.Pipes/src/System/IO/Pipes/PipeStream.Unix.cs:line 298
04:26:27    at System.Diagnostics.Tests.ProcessTests.<CreateProcessTree>g__SendMessage|202_4(String message, String handleAsString) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Diagnostics.Process/tests/ProcessTests.netcoreapp.cs:line 365
04:26:27    at System.Diagnostics.Tests.ProcessTests.<CreateProcessTree>b__202_8(String c1hs) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Diagnostics.Process/tests/ProcessTests.netcoreapp.cs:line 319
04:26:27 --- End of stack trace from previous location where exception was thrown ---
04:26:27    at RemoteExecutorConsoleApp.Program.Main(String[] args) in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/Common/tests/System/Diagnostics/RemoteExecutorConsoleApp/RemoteExecutorConsoleApp.cs:line 92
04:26:27 
[31;1m    System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated [FAIL]
04:26:27 [m[37m      System.AggregateException : Not all processes in process tree could be terminated. (No such process)
04:26:27 [m[37m      ---- System.ComponentModel.Win32Exception : No such process
04:26:27 [m[30;1m      Stack Trace:
04:26:27 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Diagnostics.Process/src/System/Diagnostics/Process.NonUap.cs(29,0): at System.Diagnostics.Process.Kill(Boolean entireProcessTree)
04:26:27 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Diagnostics.Process/tests/ProcessTests.netcoreapp.cs(282,0): at System.Diagnostics.Tests.ProcessTests.Kill_EntireProcessTree_True_EntireTreeTerminated()
04:26:27 [m[37m        --- End of stack trace from previous location where exception was thrown ---
04:26:27 [m[37m        ----- Inner Stack Trace -----
04:26:27 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(63,0): at System.Diagnostics.Process.Kill()
04:26:27 [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs(106,0): at System.Diagnostics.Process.KillTree()
04:26:27 [m[33;1m    System.Diagnostics.Tests.ProcessTests.TestProcessRecycledPid [SKIP]
04:26:27 [m[37m      Condition(s) not met: "IsStressModeEnabled"
04:26:27 [m[37m  Finished:    System.Diagnostics.Process.Tests
04:26:27 [m[37m=== TEST EXECUTION SUMMARY ===
04:26:27 [m[37m   System.Diagnostics.Process.Tests  Total: 259, Errors: 0, Failed: 1, Skipped: 2, Time: 106.765s
04:26:27 [m[m~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Diagnostics.Process.Tests/netcoreapp-Linux-Release-arm64
04:26:27 ----- end 04:26:16 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment]
@danmosemsft

**Comment by danmosemsft** [comment]
Cc @bgribaudo

**Comment by BruceForstall** [comment]
BTW, this happens consistently in every Linux/arm64 corefx test run.

**Comment by sandreenko** [comment]
Is not it a dup of #22413?

**Comment by BruceForstall** [comment]
Looks like it. I didn't see that one in my bug search before opening this.
