### ISSUE TITLE
Test failure: tracing_runtimeeventsource._runtimeeventsource_runtimeeventsource_._runtimeeventsource_runtimeeventsource_cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#22441]
This test is consistently failing in the x64 Checked Windows test run with
```
COMPlus_ZapDisable=1
COMPlus_ReadyToRun=0
COMPlus_TieredCompilation=0
```

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_zapdisable/758/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_zapdisable/757/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_zapdisable/756/consoleFull
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_zapdisable/755/consoleFull

I can't repro it locally when run by itself (not in a full test harness run).

Looks like the same issue as https://github.com/dotnet/coreclr/issues/18907, but for a different platform.

Failure:
```
tracing_runtimeeventsource._runtimeeventsource_runtimeeventsource_._runtimeeventsource_runtimeeventsource_cmd [FAIL]
07:09:56         
07:09:56   Unhandled Exception: System.Exception: Condition 'listener.EventCount > 0' is not true
07:09:56            at Tracing.Tests.Common.Assert.True(String name, Boolean condition) in D:\j\workspace\x64_checked_w---fa5d14d7\tests\src\tracing\common\Assert.cs:line 15
07:09:56            at Tracing.Tests.RuntimeEventSourceTest.Main(String[] args) in D:\j\workspace\x64_checked_w---fa5d14d7\tests\src\tracing\runtimeeventsource\RuntimeEventSourceTest.cs:line 35
07:09:56   
07:09:56   
07:09:56   Return code:      1
07:09:56   Raw output file:      D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\Reports\tracing.runtimeeventsource\runtimeeventsource\runtimeeventsource.output.txt
07:09:56   Raw output:
07:09:56   BEGIN EXECUTION
07:09:56          "D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" runtimeeventsource.exe 
07:09:56         [Simple] ThreadID = 8036 ID = 200 Name = IncreaseMemoryPressure
07:09:56         TimeStamp: 2/5/2019 7:08:38 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:03.4330247
07:09:56         	Name = "BytesAllocated" Value = "3816"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 8036 ID = 70 Name = ThreadCreating
07:09:56         TimeStamp: 2/5/2019 7:08:38 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:03.6098274
07:09:56         	Name = "ID" Value = "110079818128"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 7196 ID = 85 Name = ThreadCreated
07:09:56         TimeStamp: 2/5/2019 7:08:38 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:03.2515891
07:09:56         	Name = "ManagedThreadID" Value = "110079818128"
07:09:56         	Name = "AppDomainID" Value = "109631519376"
07:09:56         	Name = "Flags" Value = "0"
07:09:56         	Name = "ManagedThreadIndex" Value = "5"
07:09:56         	Name = "OSThreadID" Value = "7196"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 7196 ID = 71 Name = ThreadRunning
07:09:56         TimeStamp: 2/5/2019 7:08:38 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:03.2552762
07:09:56         	Name = "ID" Value = "110079818128"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 7196 ID = 145 Name = MethodJittingStarted_V1
07:09:56         TimeStamp: 2/5/2019 7:08:38 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:03.3397157
07:09:56         	Name = "MethodID" Value = "140719860519720"
07:09:56         	Name = "ModuleID" Value = "140719855919136"
07:09:56         	Name = "MethodToken" Value = "100682957"
07:09:56         	Name = "MethodILSize" Value = "133"
07:09:56         	Name = "MethodNamespace" Value = "System.Diagnostics.Tracing.EventPipeEventDispatcher"
07:09:56         	Name = "MethodName" Value = "TimeStampToDateTime"
07:09:56         	Name = "MethodSignature" Value = "instance value class System.DateTime  (int64)"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 7196 ID = 143 Name = MethodLoadVerbose_V2
07:09:56         TimeStamp: 2/5/2019 7:08:38 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:03.3350550
07:09:56         	Name = "MethodID" Value = "140719860519720"
07:09:56         	Name = "ModuleID" Value = "140719855919136"
07:09:56         	Name = "MethodStartAddress" Value = "140719862058224"
07:09:56         	Name = "MethodSize" Value = "300"
07:09:56         	Name = "MethodToken" Value = "100682957"
07:09:56         	Name = "MethodFlags" Value = "8"
07:09:56         	Name = "MethodNamespace" Value = "System.Diagnostics.Tracing.EventPipeEventDispatcher"
07:09:56         	Name = "MethodName" Value = "TimeStampToDateTime"
07:09:56         	Name = "MethodSignature" Value = "instance value class System.DateTime  (int64)"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         	Name = "ReJITID" Value = ""
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 7196 ID = 190 Name = MethodILToNativeMap
07:09:56         TimeStamp: 2/5/2019 7:08:38 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:03.3351065
07:09:56         	Name = "MethodID" Value = "140719860519720"
07:09:56         	Name = "ReJITID" Value = "0"
07:09:56         	Name = "MethodExtent" Value = "0"
07:09:56         	Name = "CountOfMapEntries" Value = "16"
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 7196 ID = 145 Name = MethodJittingStarted_V1
07:09:56         TimeStamp: 2/5/2019 7:08:38 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:03.3391564
07:09:56         	Name = "MethodID" Value = "140719862901056"
07:09:56         	Name = "ModuleID" Value = "140719855919136"
07:09:56         	Name = "MethodToken" Value = "100682985"
07:09:56         	Name = "MethodILSize" Value = "903"
07:09:56         	Name = "MethodNamespace" Value = "System.Diagnostics.Tracing.EventPipePayloadDecoder"
07:09:56         	Name = "MethodName" Value = "DecodePayload"
07:09:56         	Name = "MethodSignature" Value = "class System.Object[]  (value class EventMetadata&,value class System.ReadOnlySpan`1<unsigned int8>)"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 8036 ID = 145 Name = MethodJittingStarted_V1
07:09:56         TimeStamp: 2/5/2019 7:08:39 AM
07:09:56         LocalTime: 2/5/2019 7:08:42 AM
07:09:56         Difference: 00:00:02.9785988
07:09:56         	Name = "MethodID" Value = "140719860111216"
07:09:56         	Name = "ModuleID" Value = "140719855919136"
07:09:56         	Name = "MethodToken" Value = "100671615"
07:09:56         	Name = "MethodILSize" Value = "25"
07:09:56         	Name = "MethodNamespace" Value = "System.Threading.Tasks.Task"
07:09:56         	Name = "MethodName" Value = "Run"
07:09:56         	Name = "MethodSignature" Value = "class System.Threading.Tasks.Task  (class System.Action)"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         
07:09:56   
07:09:56         [Simple] ThreadID = 8036 ID = 143 Name = MethodLoadVerbose_V2
07:09:56         TimeStamp: 2/5/2019 7:08:39 AM
07:09:56         LocalTime: 2/5/2019 7:09:55 AM
07:09:56         Difference: 00:01:15.6907758
07:09:56         	Name = "MethodID" Value = "140719860111216"
07:09:56         	Name = "ModuleID" Value = "140719855919136"
07:09:56         	Name = "MethodStartAddress" Value = "140719862059616"
07:09:56         	Name = "MethodSize" Value = "61"
07:09:56         	Name = "MethodToken" Value = "100671615"
07:09:56         	Name = "MethodFlags" Value = "8"
07:09:56         	Name = "MethodNamespace" Value = "System.Threading.Tasks.Task"
07:09:56         	Name = "MethodName" Value = "Run"
07:09:56         	Name = "MethodSignature" Value = "class System.Threading.Tasks.Task  (class System.Action)"
07:09:56         	Name = "ClrInstanceID" Value = "0"
07:09:56         	Name = "ReJITID" Value = ""
07:09:57         
07:09:57   
07:09:57         Expected: 100
07:09:57         Actual: -532462766
07:09:57         END EXECUTION - FAILED
07:09:57         FAILED
07:09:57         Test Harness Exitcode is : 1
07:09:57         
07:09:57   To run the test:
07:09:57   > set CORE_ROOT=D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
07:09:57   > D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\tracing\runtimeeventsource\runtimeeventsource\runtimeeventsource.cmd
07:09:57   
07:09:57         Expected: True
07:09:57         Actual:   False
07:09:57         Stack Trace:
07:09:57           D:\j\workspace\x64_checked_w---fa5d14d7\bin\tests\Windows_NT.x64.Checked\TestWrappers\tracing.runtimeeventsource\tracing.runtimeeventsource.XUnitWrapper.cs(109,0): at tracing_runtimeeventsource._runtimeeventsource_runtimeeventsource_._runtimeeventsource_runtimeeventsource_cmd()
```

**Comment by BruceForstall** [comment]
@jorive @brianrob @vancem

**Comment by jorive** [comment]
Test disabled with https://github.com/dotnet/coreclr/pull/22899
