### ISSUE TITLE
[arm64][Ubuntu][jitstress2] System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#22449]
There are unstable failures of this test with:

```
m[31;1m System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds [FAIL]
00:40:05  [m  [37m   Assert.Equal() Failure
00:40:05   [m  [37m   Expected: OK
00:40:05   [m  [37m   Actual:   Unauthorized
00:40:05   [m  [30;1m   Stack Trace:
00:40:05   [m  [37m     /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_prtest/_/fx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Proxy.cs(277,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Proxy_Test.<>c__DisplayClass8_0.<<ProxyAuth_Digest_Succeeds>b__0>d.MoveNext()
00:40:05   [m  [37m     --- End of stack trace from previous location where exception was thrown ---
00:40:05   [m  [37m     /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_prtest/_/fx/src/Common/tests/System/Net/Http/LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
00:40:05   [m  [37m     /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstress2_prtest/_/fx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Proxy.cs(256,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Proxy_Test.ProxyAuth_Digest_Succeeds()
00:40:05   [m  [37m     --- End of stack trace from previous location where exception was thrown ---
```

**Comment by BruceForstall** [comment]
@sandreenko Can we close this issue? If it's not a known JIT bug, the guidance is to ignore (and disable) any unstable System.Net tests in coreclr CI.

**Comment by sandreenko** [comment]
> @sandreenko Can we close this issue? If it's not a known JIT bug, the guidance is to ignore (and disable) any unstable System.Net tests in coreclr CI.

It is disabled now (in tests\arm64\corefx_linux_test_exclusions.txt), can we just change the milestone for it? I do not want to have an exclusion that points to a closed issue without resolution.

**Comment by BruceForstall** [comment]
I don't see us ever investigating any System.Net failures. But minimally yes, please change the milestone.
