### ISSUE TITLE
[x64] Error in x64_checked_ubuntu_illink_flow

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22508]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/illink/job/x64_checked_ubuntu_illink/648/

**Log:**
```
ERROR: An error occurred in /mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink/Tools/dotnetcli/dotnet msbuild /nologo /verbosity:minimal /clp:Summary /p:RestoreDefaultOptimizationDataPackage=false /p:PortableBuild=true /p:UsePartialNGENOptimization=false /maxcpucount /mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink/tests/build.proj /flp:Verbosity=normal;LogFile=/mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink/bin/Logs/Tests_Managed.Linux.x64.Checked.log;Append=true /flp1:WarningsOnly;LogFile=/mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink/bin/Logs/Tests_Managed.Linux.x64.Checked.wrn;Append=true /flp2:ErrorsOnly;LogFile=/mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink/bin/Logs/Tests_Managed.Linux.x64.Checked.err;Append=true /l:BinClashLogger,Tools/Microsoft.DotNet.Build.Tasks.dll;LogFile=binclash.log /p:__BuildArch=x64 /p:__BuildType=Checked /p:__BuildOS=Linux /p:CLRTestPriorityToBuild=1. Check logs under /mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink.
Failed to build Managed tests build (build tests). See the build logs:
    /mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink/bin/Logs/Tests_Managed.Linux.x64.Checked.log
    /mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink/bin/Logs/Tests_Managed.Linux.x64.Checked.wrn
    /mnt/j/workspace/dotnet_coreclr/master/illink/x64_checked_ubuntu_illink/bin/Logs/Tests_Managed.Linux.x64.Checked.err
```

**Comment by shimingsg** [comment]
MSBUILD Failure log: 

```UNHANDLED EXCEPTIONS FROM PROCESS 127264:
=====================
2/10/19 6:53:02 AM
System.IO.IOException: Broken pipe ---> System.Net.Sockets.SocketException: Broken pipe
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================```

**Comment by sandreenko** [comment]
Saw it again on OSX in #24984 (https://dev.azure.com/dnceng/public/_build/results?buildId=213700&view=logs):
```
UNHANDLED EXCEPTIONS FROM PROCESS 14290:
=====================
6/5/2019 10:36:44 PM
System.IO.IOException: Broken pipe ---> System.Net.Sockets.SocketException: Broken pipe
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.IO.Pipes.PipeStream.WriteAsyncCore(ReadOnlyMemory`1 source, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
===================
```
