### ISSUE TITLE
[x64] Test Infrastructure Failure: System.ComponentModel.Win32Exception (1455): The paging file is too small for this operation to complete

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22512]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_jitx86hwintrinsicnoavx2/374/

**Failed tests:**
hosting_stress._testset1_csgen_1_csgen_1_._testset1_csgen_1_csgen_1_cmd

**Log:**
```
hosting_stress._testset1_csgen_1_csgen_1_._testset1_csgen_1_csgen_1_cmd [FAIL]
        Test Infrastructure Failure: System.ComponentModel.Win32Exception (1455): The paging file is too small for this operation to complete.
           at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo) in F:\vsagent\1\s\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Windows.cs:line 598
           at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo) in F:\vsagent\1\s\src\System.Diagnostics.Process\src\System\Diagnostics\Process.Win32.cs:line 26
           at System.Diagnostics.Process.Start() in F:\vsagent\1\s\src\System.Diagnostics.Process\src\System\Diagnostics\Process.cs:line 1215
           at CoreclrTestLib.CoreclrTestWrapperLib.RunTest(String executable, String outputFile, String errorFile) in D:\j\workspace\x64_checked_w---c3e1a93c\tests\src\Common\Coreclr.TestWrapper\CoreclrTestWrapperLib.cs:line 199
           at hosting_stress._testset1_csgen_1_csgen_1_._testset1_csgen_1_csgen_1_cmd() in D:\j\workspace\x64_checked_w---c3e1a93c\bin\tests\Windows_NT.x64.Checked\TestWrappers\hosting.stress\hosting.stress.XUnitWrapper.cs:line 69
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\x64_checked_w---c3e1a93c\bin\tests\Windows_NT.x64.Checked\TestWrappers\hosting.stress\hosting.stress.XUnitWrapper.cs(109,0): at hosting_stress._testset1_csgen_1_csgen_1_._testset1_csgen_1_csgen_1_cmd()
```

**Comment by RussKeldorph** [comment]
No repro
