### ISSUE TITLE
[arm] Test failed: System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22562]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm/job/jitstress/job/arm_cross_checked_windows_nt_corefx_jitstressregs3_tst/50/

**Failed tests:**
System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException

**Log:**
```
System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException(value: System.Runtime.InteropServices.Tests.GCHandleTests+NonBlittable) [FAIL]
      Assert.Equal() Failure
      Expected: (null)
      Actual:   value
      Stack Trace:
        D:\j\workspace\arm_cross_che---470eb69d\_\fx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(86,0): at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode)
        D:\j\workspace\arm_cross_che---470eb69d\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\GCHandleTests.cs(78,0): at System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException(Object value)
    System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException(value: []) [FAIL]
      Assert.Equal() Failure
      Expected: (null)
      Actual:   value
      Stack Trace:
        D:\j\workspace\arm_cross_che---470eb69d\_\fx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(86,0): at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode)
        D:\j\workspace\arm_cross_che---470eb69d\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\GCHandleTests.cs(78,0): at System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException(Object value)
    System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException(value: []) [FAIL]
      Assert.Equal() Failure
      Expected: (null)
      Actual:   value
      Stack Trace:
        D:\j\workspace\arm_cross_che---470eb69d\_\fx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(86,0): at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode)
        D:\j\workspace\arm_cross_che---470eb69d\_\fx\src\System.Runtime.InteropServices\tests\System\Runtime\InteropServices\GCHandleTests.cs(78,0): at System.Runtime.InteropServices.Tests.GCHandleTests.Alloc_InvalidPinnedObject_ThrowsArgumentException(Object value)
```

**Comment by jkotas** [comment]
CoreCLR/CoreFX out of sync.
