### ISSUE TITLE
[x64] Test failed:  System.Tests.DecimalTests.Round_InvalidMidpointRounding_ThrowsArgumentException(mode: ToZero)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22588]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_baseline/839/

**Failed tests:**
System.Tests.DecimalTests.Round_InvalidMidpointRounding_ThrowsArgumentException(mode: ToZero)
System.Drawing.Tests.FontTests.ToLogFont_DisposedGraphics_ThrowsArgumentException

**Log:**
```
System.Tests.DecimalTests.Round_InvalidMidpointRounding_ThrowsArgumentException(mode: ToZero) [FAIL]
  [m[31;1m[m[37m      Assert.Throws() Failure
  [m[37m      Expected: typeof(System.ArgumentException)
  [m[37m      Actual:   (No exception was thrown)
  [m[30;1m      Stack Trace:
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs(83,0): at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/System.Runtime/tests/System/DecimalTests.cs(931,0): at System.Tests.DecimalTests.Round_InvalidMidpointRounding_ThrowsArgumentException(MidpointRounding mode)
```

**Comment by stephentoub** [comment]
This test is out of date in coreclr and should be disabled.  It's been fixed in corefx.
