### ISSUE TITLE
[arm64] Sending request failed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22615]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation_tst/122/

**Failed tests:**
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http2.GetAsync_SetCookieContainer_CookieSent

**Log:**
```
System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies_Http2.GetAsync_SetCookieContainer_CookieSent(cookieName: "foo", cookieValue: "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"..., useCookies: True) [FAIL]
[m[37m      System.Net.Http.HttpRequestException : An error occurred while sending the request.
[m[30;1m      Stack Trace:
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation/_/fx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/Http2Connection.cs(1177,0): at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation/_/fx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/HttpConnectionPool.cs(500,0): at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation/_/fx/src/System.Net.Http/src/System/Net/Http/SocketsHttpHandler/RedirectHandler.cs(33,0): at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation/_/fx/src/System.Net.Http/src/System/Net/Http/HttpClient.cs(475,0): at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
[m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_tieredcompilation/_/fx/src/System.Net.Http/tests/FunctionalTests/HttpClientHandlerTest.Cookies.cs(70,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.<>c__DisplayClass9_0.<<GetAsync_SetCookieContainer_CookieSent>b__0>d.MoveNext()
```

**Comment by RussKeldorph** [comment]
@karelz Could you take a look?

**Comment by karelz** [comment]
@wfurt to help

**Comment by sandreenko** [comment]
The test was disabled in #22697.
