### ISSUE TITLE
An invocation of a "non-virtual" delegate to a default interface implementation calls the method virtually

### ISSUE THREAD

**Issue by AlekseyTs** [dotnet/coreclr#22728]
Compile and run the following code:
```
class A : B
{
    char B.F1(int pA) => 'A';
    char D.F1(int pA) => 'A';

    void Test()
    {
        System.Console.WriteLine(new System.Func<int, char>(base(B).F1)(1));
        System.Console.WriteLine(new System.Func<int, char>(base(C).F1)(1));
        System.Console.WriteLine(new System.Func<int, char>(base(D).F1)(1));
    }

    static void Main()
    {
        new A().Test();
    }
}

interface B : C
{
    new virtual char F1(int pB) => 'B';
}

interface C : D
{
}

interface D
{
    virtual char F1(int pD) => 'D';
}
```

Observed output:
```
A
A
A
```

Expected output:
```
B
D
D
```

IL looks like this:
```

//  Microsoft (R) .NET Framework IL Disassembler.  Version 4.6.1055.0
//  Copyright (c) Microsoft Corporation.  All rights reserved.



// Metadata version: v4.0.30319
.assembly extern System.Runtime
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:2:1:0
}
.assembly extern System.Console
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A )                         // .?_....:
  .ver 4:1:1:0
}
.assembly debug15
{
  .custom instance void [System.Runtime]System.Runtime.CompilerServices.CompilationRelaxationsAttribute::.ctor(int32) = ( 01 00 08 00 00 00 00 00 ) 
  .custom instance void [System.Runtime]System.Runtime.CompilerServices.RuntimeCompatibilityAttribute::.ctor() = ( 01 00 01 00 54 02 16 57 72 61 70 4E 6F 6E 45 78   // ....T..WrapNonEx
                                                                                                                   63 65 70 74 69 6F 6E 54 68 72 6F 77 73 01 )       // ceptionThrows.

  // --- The following custom attribute is added automatically, do not uncomment -------
  //  .custom instance void [System.Runtime]System.Diagnostics.DebuggableAttribute::.ctor(valuetype [System.Runtime]System.Diagnostics.DebuggableAttribute/DebuggingModes) = ( 01 00 07 01 00 00 00 00 ) 

  .hash algorithm 0x00008004
  .ver 0:0:0:0
}
.module debug15.exe
// MVID: {119E194D-1CB2-4667-A56F-897CD0B68F60}
.imagebase 0x00400000
.file alignment 0x00000200
.stackreserve 0x00100000
.subsystem 0x0003       // WINDOWS_CUI
.corflags 0x00000001    //  ILONLY
// Image base: 0x00870000


// =============== CLASS MEMBERS DECLARATION ===================

.class private auto ansi beforefieldinit A
       extends [System.Runtime]System.Object
       implements B,
                  C,
                  D
{
  .method private hidebysig newslot virtual final 
          instance char  B.F1(int32 pA) cil managed
  {
    .override B::F1
    // Code size       3 (0x3)
    .maxstack  8
    IL_0000:  ldc.i4.s   65
    IL_0002:  ret
  } // end of method A::B.F1

  .method private hidebysig newslot virtual final 
          instance char  D.F1(int32 pA) cil managed
  {
    .override D::F1
    // Code size       3 (0x3)
    .maxstack  8
    IL_0000:  ldc.i4.s   65
    IL_0002:  ret
  } // end of method A::D.F1

  .method private hidebysig instance void 
          Test() cil managed
  {
    // Code size       74 (0x4a)
    .maxstack  2
    IL_0000:  nop
    IL_0001:  ldarg.0
    IL_0002:  ldftn      instance char B::F1(int32)
    IL_0008:  newobj     instance void class [System.Runtime]System.Func`2<int32,char>::.ctor(object,
                                                                                              native int)
    IL_000d:  ldc.i4.1
    IL_000e:  callvirt   instance !1 class [System.Runtime]System.Func`2<int32,char>::Invoke(!0)
    IL_0013:  call       void [System.Console]System.Console::WriteLine(char)
    IL_0018:  nop
    IL_0019:  ldarg.0
    IL_001a:  ldftn      instance char D::F1(int32)
    IL_0020:  newobj     instance void class [System.Runtime]System.Func`2<int32,char>::.ctor(object,
                                                                                              native int)
    IL_0025:  ldc.i4.1
    IL_0026:  callvirt   instance !1 class [System.Runtime]System.Func`2<int32,char>::Invoke(!0)
    IL_002b:  call       void [System.Console]System.Console::WriteLine(char)
    IL_0030:  nop
    IL_0031:  ldarg.0
    IL_0032:  ldftn      instance char D::F1(int32)
    IL_0038:  newobj     instance void class [System.Runtime]System.Func`2<int32,char>::.ctor(object,
                                                                                              native int)
    IL_003d:  ldc.i4.1
    IL_003e:  callvirt   instance !1 class [System.Runtime]System.Func`2<int32,char>::Invoke(!0)
    IL_0043:  call       void [System.Console]System.Console::WriteLine(char)
    IL_0048:  nop
    IL_0049:  ret
  } // end of method A::Test

  .method private hidebysig static void  Main() cil managed
  {
    .entrypoint
    // Code size       13 (0xd)
    .maxstack  8
    IL_0000:  nop
    IL_0001:  newobj     instance void A::.ctor()
    IL_0006:  call       instance void A::Test()
    IL_000b:  nop
    IL_000c:  ret
  } // end of method A::Main

  .method public hidebysig specialname rtspecialname 
          instance void  .ctor() cil managed
  {
    // Code size       8 (0x8)
    .maxstack  8
    IL_0000:  ldarg.0
    IL_0001:  call       instance void [System.Runtime]System.Object::.ctor()
    IL_0006:  nop
    IL_0007:  ret
  } // end of method A::.ctor

} // end of class A

.class interface private abstract auto ansi B
       implements C,
                  D
{
  .method public hidebysig newslot virtual 
          instance char  F1(int32 pB) cil managed
  {
    // Code size       3 (0x3)
    .maxstack  8
    IL_0000:  ldc.i4.s   66
    IL_0002:  ret
  } // end of method B::F1

} // end of class B

.class interface private abstract auto ansi C
       implements D
{
} // end of class C

.class interface private abstract auto ansi D
{
  .method public hidebysig newslot virtual 
          instance char  F1(int32 pD) cil managed
  {
    // Code size       3 (0x3)
    .maxstack  8
    IL_0000:  ldc.i4.s   68
    IL_0002:  ret
  } // end of method D::F1

} // end of class D


// =============================================================

// *********** DISASSEMBLY COMPLETE ***********************
// WARNING: Created Win32 resource file debug15.res
```

**Comment by AlekseyTs** [comment]
Here is another scenario:
```
class A : B
{
    char D.F1() => 'A';

    void Test()
    {
        System.Console.WriteLine(new System.Func<char>(base(B).F1)());
        System.Console.WriteLine(new System.Func<char>(base(C).F1)());
        System.Console.WriteLine(new System.Func<char>(base(D).F1)());
    }

    static void Main()
    {
        new A().Test();
        new F().Test();
        ((E)new G()).Test();
    }
}

struct F : B
{
    char D.F1() => 'F';

    public void Test()
    {
        System.Console.WriteLine(new System.Func<char>(base(B).F1)());
        System.Console.WriteLine(new System.Func<char>(base(C).F1)());
        System.Console.WriteLine(new System.Func<char>(base(D).F1)());
    }
}

interface E : B
{
    sealed void Test()
    {
        System.Console.WriteLine(new System.Func<char>(base(B).F1)());
        System.Console.WriteLine(new System.Func<char>(base(C).F1)());
        System.Console.WriteLine(new System.Func<char>(base(D).F1)());
    }
}

class G : E
{
    char D.F1() => 'G';
}

interface B : C
{
    char D.F1() => 'B';
}

interface C : D
{
}

interface D
{
    virtual char F1() => 'D';
}
```

      Expected: 
```
      B
      D
      D
      B
      D
      D
      B
      D
      D
```
      
      Actual:
```
      B
      A
      A
      B
      F
      F
      B
      G
      G
```

**Comment by AlekseyTs** [comment]
@MichalStrehovsky The issue is closed, but I still see Roslyn test scenarios failing with Microsoft.NETCore.App 3.0.0-preview4-27525-12, SDK version 3.0.100-preview4-010963. Is this expected?

```
    Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.ExplicitBase_107_Delegate [FAIL]
      Roslyn.Test.Utilities.ExecutionException : 
      Execution failed for assembly 'da280268-7e16-4a65-beb5-f331238d4773, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
      Expected: 
      B
      D
      B
      D
      B
      D
      
      Actual:   A
      A
      F
      F
      G
      G
      
      
      Stack Trace:
        F:\GitHub\roslyn\src\Test\Utilities\Portable\Platform\CoreClr\CoreCLRRuntimeEnvironment.cs(86,0): at Roslyn.Test.Utilities.CoreClr.CoreCLRRuntimeEnvironment.Execute(String moduleName, String[] args, String expectedOutput)
        F:\GitHub\roslyn\src\Test\Utilities\Portable\CompilationVerifier.cs(201,0): at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit(String expectedOutput, Nullable`1 expectedReturnCode, String[] args, IEnumerable`1 manifestResources, EmitOptions emitOptions, Verification peVerify, SignatureDescription[] expectedSignatures)
        F:\GitHub\roslyn\src\Test\Utilities\Portable\CommonTestBase.cs(154,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify)
        F:\GitHub\roslyn\src\Test\Utilities\Portable\CommonTestBase.cs(68,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify)
        F:\GitHub\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs(679,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify)
        F:\GitHub\roslyn\src\Compilers\CSharp\Test\Symbol\Symbols\DefaultInterfaceImplementationTests.cs(49379,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.ExplicitBase_107_Delegate()
    Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.ExplicitBase_150_Delegate [FAIL]
      Roslyn.Test.Utilities.ExecutionException : 
      Execution failed for assembly 'adb15845-a279-4037-a249-28aae5f17266, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
      Expected: 
      B
      D
      B
      D
      B
      D
      
      Actual:   B
      A
      B
      F
      B
      G
      
      
      Stack Trace:
        F:\GitHub\roslyn\src\Test\Utilities\Portable\Platform\CoreClr\CoreCLRRuntimeEnvironment.cs(86,0): at Roslyn.Test.Utilities.CoreClr.CoreCLRRuntimeEnvironment.Execute(String moduleName, String[] args, String expectedOutput)
        F:\GitHub\roslyn\src\Test\Utilities\Portable\CompilationVerifier.cs(201,0): at Microsoft.CodeAnalysis.Test.Utilities.CompilationVerifier.Emit(String expectedOutput, Nullable`1 expectedReturnCode, String[] args, IEnumerable`1 manifestResources, EmitOptions emitOptions, Verification peVerify, SignatureDescription[] expectedSignatures)
        F:\GitHub\roslyn\src\Test\Utilities\Portable\CommonTestBase.cs(154,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.Emit(Compilation compilation, IEnumerable`1 dependencies, IEnumerable`1 manifestResources, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, Action`1 assemblyValidator, Action`1 symbolValidator, EmitOptions emitOptions, Verification verify)
        F:\GitHub\roslyn\src\Test\Utilities\Portable\CommonTestBase.cs(68,0): at Microsoft.CodeAnalysis.Test.Utilities.CommonTestBase.CompileAndVerifyCommon(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 assemblyValidator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify)
        F:\GitHub\roslyn\src\Compilers\Test\Utilities\CSharp\CSharpTestBase.cs(679,0): at Microsoft.CodeAnalysis.CSharp.Test.Utilities.CSharpTestBase.CompileAndVerify(Compilation compilation, IEnumerable`1 manifestResources, IEnumerable`1 dependencies, Action`1 sourceSymbolValidator, Action`1 validator, Action`1 symbolValidator, SignatureDescription[] expectedSignatures, String expectedOutput, Nullable`1 expectedReturnCode, String[] args, EmitOptions emitOptions, Verification verify)
        F:\GitHub\roslyn\src\Compilers\CSharp\Test\Symbol\Symbols\DefaultInterfaceImplementationTests.cs(55758,0): at Microsoft.CodeAnalysis.CSharp.UnitTests.Symbols.DefaultInterfaceImplementationTests.ExplicitBase_150_Delegate()
  Finished:    Microsoft.CodeAnalysis.CSharp.Symbol.UnitTests
```

**Comment by MichalStrehovsky** [comment]
@AlekseyTs Yeah, it got rolled back because it found a ReadyToRun bug (#23317). I then started tracking re-enabling this in #23262. It's a mess. I agree it's better to track it in this bug. I'll close the other one.
