### ISSUE TITLE
Test failed: System.Globalization.Tests.GregorianCalendarMiddleEastFrenchTests.CalendarType_SetInvalidValue_ThrowsArgumentOutOfRangeException(type: 0)

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22777]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_baseline/847/

**Failed tests:**
System.Globalization.Tests.GregorianCalendarMiddleEastFrenchTests.CalendarType_SetInvalidValue_ThrowsArgumentOutOfRangeException

**Log:**
```
System.Globalization.Tests.GregorianCalendarMiddleEastFrenchTests.CalendarType_SetInvalidValue_ThrowsArgumentOutOfRangeException(type: 0) [FAIL]
  [m[31;1m[m[37m      Assert.Equal() Failure
  [m[37m                ↓ (pos 0)
  [m[37m      Expected: m_type
  [m[37m      Actual:   value
  [m[37m                ↑ (pos 0)
  [m[30;1m      Stack Trace:
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/CoreFx.Private.TestUtilities/src/System/AssertExtensions.cs(88,0): at System.AssertExtensions.Throws[T](String paramName, Func`1 testCode)
  [m[37m        /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_baseline/_/fx/src/System.Globalization.Calendars/tests/System/Globalization/GregorianCalendarTests.cs(54,0): at System.Globalization.Tests.GregorianCalendarTestBase.CalendarType_SetInvalidValue_ThrowsArgumentOutOfRangeException(GregorianCalendarTypes type)
```

**Comment by BruceForstall** [comment]
I don't see this failure in current runs
