### ISSUE TITLE
[arm64] Test failed: tracing_eventsource._eventpipeandetw_eventpipeandetw_eventpipeandetw_._eventpipeandetw_eventpipeandetw_eventpipeandetw_cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#22826]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_gcstress0xc_minopts_heapverify1_tst/53/

**Failed tests:**
tracing_eventsource._eventpipeandetw_eventpipeandetw_eventpipeandetw_._eventpipeandetw_eventpipeandetw_eventpipeandetw_cmd

**Log:**
```
tracing_eventsource._eventpipeandetw_eventpipeandetw_eventpipeandetw_._eventpipeandetw_eventpipeandetw_eventpipeandetw_cmd [FAIL]
        
  Unhandled Exception: System.InvalidOperationException: Bad PE Header.
           at PEFile.PEHeader..ctor(Void* startOfPEFile)
           at PEFile.PEFile..ctor(String filePath)
           at Microsoft.Diagnostics.Tracing.Session.TraceEventProviderOptions.get_FilteringSupported()
           at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableProvider(Guid providerGuid, TraceEventLevel providerLevel, UInt64 matchAnyKeywords, TraceEventProviderOptions options)
           at Microsoft.Diagnostics.Tracing.Session.TraceEventSession.EnableProvider(String providerName, TraceEventLevel providerLevel, UInt64 matchAnyKeywords, TraceEventProviderOptions options)
           at Tracing.Tests.EventPipeAndEtw.EnableETW(EventSource eventSource, EventKeywords keywords, String outputFile) in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\tracing\eventsource\eventpipeandetw\EventPipeAndEtw.cs:line 116
           at Tracing.Tests.EventPipeAndEtw.RoundOne(String[] args) in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\tracing\eventsource\eventpipeandetw\EventPipeAndEtw.cs:line 148
           at Tracing.Tests.EventPipeAndEtw.Main(String[] args) in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\tracing\eventsource\eventpipeandetw\EventPipeAndEtw.cs:line 290
  
  Return code:      1
```

**Comment by jorive** [comment]
Closed by https://github.com/dotnet/coreclr/pull/22870
