### ISSUE TITLE
container fails on kubernetes when CPU limits are not set

### ISSUE THREAD

**Issue by mgumowsk** [dotnet/coreclr#22957]
The following code fails:

```
using System.Collections.Generic;
using System.Threading.Tasks;

namespace bugrepro
{
    class Program
    {
        static void Main(string[] args)
        {
            List<int> list = new List<int>(100);
            while (true)
            {
                Parallel.For(0, 100, i =>
                {
                    var c = list[i];
                });
            }
        }
    }
}
```

with the exception
```
Parameter name: index) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at bugrepro.Program.<>c__DisplayClass0_0.<Main>b__0(Int32 i) in /app/bugrepro/Program.cs:line 15
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at bugrepro.Program.Main(String[] args) in /app/bugrepro/Program.cs:line 13
```

when run as an image on kubernetes without limits set.
Example docker container build :
```
FROM microsoft/dotnet:sdk AS build-env
WORKDIR /app
COPY bugrepro/*.csproj ./bugrepro/
WORKDIR /app/bugrepro
COPY bugrepro /app/bugrepro
WORKDIR /app/bugrepro
RUN dotnet publish -c Release -o out
FROM microsoft/dotnet:runtime
WORKDIR /app
COPY --from=build-env /app/bugrepro/out .
ENTRYPOINT ["dotnet", "bugrepro.dll"]
```

Example kubernetes deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bugrepro-deployment
  labels:
    app: bugrepro
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bugrepro
  template:
    metadata:
      labels:
        app: bugrepro
    spec:
      containers:
      - name: bugrepro
        image: 127.0.0.1:32001/bugrepro
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Gi"
            cpu: "2"
```

When CPU limits are set on kubernetes deployment there aren't any issues.

**Comment by RussKeldorph** [comment]
@janvorli @kouvel

**Comment by mgumowsk** [comment]
The provided example code to reproduce is wrong. The issue still occurs in my main code, but I have to take out the valid example to reproduce. Will open again if I have good example.
