### ISSUE TITLE
[Linux|x64] Regressions/coreclr/1514/interlockexchange/ fails randomly

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#22975]
This test was not being run for a bit. It fails intermittently. Example output below:

```
System.Runtime.InteropServices.SEHException: External component has thrown an exception.System.Runtime.InteropServices.SEHException: External component has thrown an exception.

System.Runtime.InteropServices.SEHException: External component has thrown an exception.System.Runtime.InteropServices.SEHException: External component has thrown an exception.System.Runtime.InteropServices.SEHException: External component has thrown an exception.


 at System.Threading.Interlocked.Add(Int64 ByRef, Int64)
 at System.Threading.Interlocked.Add(Int64 ByRef, Int64) at System.Threading.Interlocked.Add(Int64 ByRef, Int64) at Program.DoWork()


 at System.Threading.Interlocked.Add(Int64 ByRef, Int64)
 at Program.DoWork()
 at Program.DoWork()
 at System.Threading.Thread.ThreadMain_ThreadStart() at System.Threading.Thread.ThreadMain_ThreadStart()

 at System.Threading.Interlocked.Add(Int64 ByRef, Int64) at Program.DoWork() at System.Threading.Thread.ThreadMain_ThreadStart()
 at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
 at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
 at System.Threading.ThreadHelper.ThreadStart_Context(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

 at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)

 at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 at System.Threading.Thread.ThreadMain_ThreadStart()

 at System.Threading.ThreadHelper.ThreadStart() at Program.DoWork()
 at System.Threading.ThreadHelper.ThreadStart()

 at System.Threading.Thread.ThreadMain_ThreadStart()
 at System.Threading.ThreadHelper.ThreadStart() at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)

 at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
 at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
 at System.Threading.ThreadHelper.ThreadStart()
 at System.Threading.ThreadHelper.ThreadStart()
/home/helixbot/dotnetbuild/work/26c5993a-dbfe-45cc-a3a3-b2f309444ed6/Work/4ad2340d-a861-465d-8c62-65a6518c469d/Exec/1514/InterlockExchange/InterlockExchange.sh: line 252: 11134 Aborted (core dumped) $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"
/n/nReturn code: 1/nRaw output file: /home/helixbot/dotnetbuild/work/26c5993a-dbfe-45cc-a3a3-b2f309444ed6/Work/4ad2340d-a861-465d-8c62-65a6518c469d/Exec/Reports/Regressions.coreclr/1514/InterlockExchange/InterlockExchange.output.txt/nRaw output:/nBEGIN EXECUTION
/home/helixbot/dotnetbuild/work/26c5993a-dbfe-45cc-a3a3-b2f309444ed6/Payload/corerun InterlockExchange.exe ''
Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
/nTo run the test:/n> set CORE_ROOT=/home/helixbot/dotnetbuild/work/26c5993a-dbfe-45cc-a3a3-b2f309444ed6/Payload/n> /home/helixbot/dotnetbuild/work/26c5993a-dbfe-45cc-a3a3-b2f309444ed6/Work/4ad2340d-a861-465d-8c62-65a6518c469d/Exec/1514/InterlockExchange/InterlockExchange.sh/n
Expected: True
Actual: False

```

**Comment by RussKeldorph** [comment]
This looks like a platform issue or a bug in the runtime or codegen around thread synch.  We probably need a crash dump to even begin to investigate.

**Comment by janvorli** [comment]
I was trying to repro it on my local x64 Linux box (Ubuntu 16.10) last week running that test in a loop and running `stress` side by side with it. Thousands of iterations completed just fine. 
I've tried a checked build of coreclr.

**Comment by janvorli** [comment]
I wonder - were the failures by any chance in release build?

**Comment by jashook** [comment]
Correct the failure was in a release build.

**Comment by janvorli** [comment]
Ok, I'll retry with the release build.

**Comment by VSadov** [comment]
we have not seen this failure on Linux/x64 for ~ 4 months.
