### ISSUE TITLE
Test failure: tracing/tracevalidation/inducedgc/inducedgc 

### ISSUE THREAD

**Issue by sywhang** [dotnet/coreclr#23124]
On ARM64 Linux, tracing/tracevalidation/inducedgc/inducedgc is keep failing with the following error:
```

Unhandled Exception: System.Exception: Values for 'matchingEventCount' are not equal! Left='10' Right='1'
   at Tracing.Tests.Common.Assert.Equal[T](String name, T left, T right) in /__w/1/s/tests/src/tracing/common/Assert.cs:line 34
   at Tracing.Tests.TraceValidationInducedGC.Main(String[] args) in /__w/1/s/tests/src/tracing/tracevalidation/inducedgc/InducedGC.cs:line 64
/home/helixbot/dotnetbuild/work/2659a935-d8bb-42fc-9d92-98d375ab32de/Work/ccb456a9-b2f3-459f-8b9a-b46e7360a656/Exec/inducedgc/inducedgc/inducedgc.sh: line 266:  5653 Aborted                 $LAUNCHER $ExePath \"${CLRTestExecutionArguments[@]}\"
/n/nReturn code:      1/nRaw output file:      /home/helixbot/dotnetbuild/work/2659a935-d8bb-42fc-9d92-98d375ab32de/Work/ccb456a9-b2f3-459f-8b9a-b46e7360a656/Exec/Reports/tracing.tracevalidation/inducedgc/inducedgc/inducedgc.output.txt/nRaw output:/nBEGIN EXECUTION
/home/helixbot/dotnetbuild/work/2659a935-d8bb-42fc-9d92-98d375ab32de/Payload/corerun inducedgc.exe ''
\tStart: Enable tracing.
\tEnd: Enable tracing.

\tStart: Generate some events.
\tEnd: Generate some events.

\tStart: Disable tracing.
\tEnd: Disable tracing.

\tStart: Process the trace file.
\tEnd: Processing events from file.

Expected: 100
Actual: 134
END EXECUTION - FAILED
Test Harness Exitcode is : 1
/nTo run the test:/n> set CORE_ROOT=/home/helixbot/dotnetbuild/work/2659a935-d8bb-42fc-9d92-98d375ab32de/Payload/n> /home/helixbot/dotnetbuild/work/2659a935-d8bb-42fc-9d92-98d375ab32de/Work/ccb456a9-b2f3-459f-8b9a-b46e7360a656/Exec/inducedgc/inducedgc/inducedgc.sh/n
Expected: True
Actual:   False
```
It seems like an actual failure but I don't have an ARM64 machine lying around to repro this locally. I will come back to investigate it later and will disable the test for now.

**Comment by RussKeldorph** [comment]
@sywhang `inducedgc` is also failing on Alpine.  Could you fix it or disable it for that case as well?

https://dnceng.visualstudio.com/internal/_build/results?buildId=122003&view=ms.vss-test-web.build-test-results-tab

**Comment by sywhang** [comment]
@RussKeldorph #23240 should disable it for Alpine.

**Comment by tommcdon** [comment]
This is now tracked on #22898
