### ISSUE TITLE
[x64] Test failed: System.Net.Sockets.Tests.SocketOptionNameTest.BindDuringTcpWait_Succeeds

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23274]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_ubuntu_corefx_jitstressregs3/837/

**Failed tests:**
System.Net.Sockets.Tests.SocketOptionNameTest.BindDuringTcpWait_Succeeds

**Log:**
```
System.Net.Sockets.Tests.SocketOptionNameTest.BindDuringTcpWait_Succeeds [FAIL]
        System.Net.Sockets.SocketException : Address already in use
        Stack Trace:
          /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs3/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(5170,0): at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
          /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs3/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(762,0): at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
          /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs3/_/fx/src/System.Net.Sockets/src/System/Net/Sockets/Socket.cs(705,0): at System.Net.Sockets.Socket.Bind(EndPoint localEP)
          /mnt/j/workspace/dotnet_coreclr/master/jitstress/x64_checked_ubuntu_corefx_jitstressregs3/_/fx/src/System.Net.Sockets/tests/FunctionalTests/SocketOptionNameTest.cs(467,0): at System.Net.Sockets.Tests.SocketOptionNameTest.BindDuringTcpWait_Succeeds()
```

**Comment by BruceForstall** [comment]
@danmosemsft Something anyone would want to look at?

**Comment by danmosemsft** [comment]
@wfurt

**Comment by wfurt** [comment]
I'll try to reproduce it. Unfortunately coreclr runs leave almost no evidence so it may be difficult to investigate.

**Comment by RussKeldorph** [comment]
@wfurt Any luck?

**Comment by wfurt** [comment]
no, I did not get to it recently.

**Comment by jeffschwMSFT** [comment]
I ran this test in a loop against a Dbg build of master tip with JitStress enabled and did not see a failure.  A possibility is that this test was running concurrently with another and contending on the address.  I am going to close for now and we can keep an eye on if this fails again.
