### ISSUE TITLE
[arm64] Test failed: System.Net.Security.Tests.SslStreamStreamToStreamTest_Sync.SslStream_StreamToStream_Dispose_Throws

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23310]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4_tst/137/

**Failed tests:**
System.Net.Security.Tests.SslStreamStreamToStreamTest_Sync.SslStream_StreamToStream_Dispose_Throws

**Log:**
```
System.Net.Security.Tests.SslStreamStreamToStreamTest_Sync.SslStream_StreamToStream_Dispose_Throws [FAIL]
      Assert.Throws() Failure
      Expected: typeof(System.IO.IOException)
      Actual:   typeof(System.ObjectDisposedException): Cannot access a disposed object.
      Object name: 'SslStream'.
      ---- System.ObjectDisposedException : Cannot access a disposed object.
      Object name: 'SslStream'.
      Stack Trace:
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4/_/fx/src/System.Net.Security/src/System/Net/Security/Sslstream.Implementation.cs(78,0): at System.Net.Security.SslStream.ThrowIfExceptional()
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4/_/fx/src/System.Net.Security/src/System/Net/Security/Sslstream.Implementation.cs(168,0): at System.Net.Security.SslStream.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4/_/fx/src/System.Net.Security/src/System/Net/Security/SslStream.cs(740,0): at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
           at System.Threading.Tasks.Task`1.InnerInvoke()
           at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
           at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location where exception was thrown ---
        ----- Inner Stack Trace -----
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4/_/fx/src/System.Net.Security/src/System/Net/Security/Sslstream.Implementation.cs(78,0): at System.Net.Security.SslStream.ThrowIfExceptional()
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4/_/fx/src/System.Net.Security/src/System/Net/Security/Sslstream.Implementation.cs(168,0): at System.Net.Security.SslStream.CheckThrow(Boolean authSuccessCheck, Boolean shutdownCheck)
        /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4/_/fx/src/System.Net.Security/src/System/Net/Security/SslStream.cs(740,0): at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
           at System.Threading.Tasks.Task`1.InnerInvoke()
           at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
           at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
        --- End of stack trace from previous location where exception was thrown ---
           at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
        --- End of stack trace from previous location where exception was thrown ---
  Finished:    System.Net.Security.Tests
=== TEST EXECUTION SUMMARY ===
   System.Net.Security.Tests  Total: 4237, Errors: 0, Failed: 1, Skipped: 5, Time: 23.537s
~/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4_tst/_/fx/artifacts/bin/tests/System.Net.Security.Tests/netcoreapp-Linux-Release-arm64
```

**Comment by stephentoub** [comment]
@jkotas, this coreclr leg picks up live corefx src and tests?

**Comment by jkotas** [comment]
Correct, the JIT stress legs pick up live corefx src and tests.

**Comment by stephentoub** [comment]
> the JIT stress legs pick up live corefx src and tests

Thanks.  What environment variables or the like do I need to set to achieve the same JIT configuration locally as this leg does?

**Comment by jkotas** [comment]
From https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_jitstressregs4_tst/137/ :

`export COMPlus_TieredCompilation=0 export COMPlus_JitStressRegs=4`

In case you see behavior that does not match the source code, the failure may be a manifestation of a JIT codegen bug.

**Comment by stephentoub** [comment]
Thanks.

**Comment by stephentoub** [comment]
I see how this could have happened.  The test was queueing a work item that called SslStream.Read, and if that were delayed long enough, it could have run after a later call to Dispose, triggering Read to throw an ObjectDisposedException.  That test code, however, only lived for about a day, at which point it was changed in a way where that interleaving can no longer happen (the Read call is now made synchronously rather than asynchronously).  Given that, I think this is fixed.
