### ISSUE TITLE
[x86] System.Tests.ArraySegment_Tests.CopyTo_Invalid

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23376]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_corefx_minopts/754/

**Failed tests:**
System.Tests.ArraySegment_Tests.CopyTo_Invalid

**Log:**
```
System.Tests.ArraySegment_Tests.CopyTo_Invalid(arraySegment: [4, 5, 6]) [FAIL]
        Assert.Equal() Failure
        Expected: (null)
        Actual:   destination
        Stack Trace:
          D:\j\workspace\x86_checked_w---91802095\_\fx\src\CoreFx.Private.TestUtilities\src\System\AssertExtensions.cs(68,0): at System.AssertExtensions.Throws[T](String paramName, Action action)
          D:\j\workspace\x86_checked_w---91802095\_\fx\src\System.Runtime\tests\System\ArraySegmentTests.netcoreapp.cs(233,0): at System.Tests.ArraySegment_Tests.CopyTo_Invalid(ArraySegment`1 arraySegment)
```

**Comment by stephentoub** [comment]
Corelib added a name to an exception parameter, and the corefx test was validating that it was null. The discrepancy was fixed this morning when the updated corelib was pulled into corefx.
