### ISSUE TITLE
[arm64] Test failed: System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23447]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_tieredcompilation_tst/26/

**Failed tests:**
System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read

**Log:**
```
System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read [FAIL]
      System.IO.IOException : The service has not been started. : 'C:\Users\HelixAdmin\AppData\Local\Temp\tmp5C97.tmp'
      Stack Trace:
        D:\j\workspace\arm64_cross_c---aca7f1c3\_\fx\src\System.IO.FileSystem\src\System\IO\FileSystem.Win32.cs(60,0): at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath)
        D:\j\workspace\arm64_cross_c---aca7f1c3\_\fx\src\System.IO.FileSystem\src\System\IO\FileSystem.Win32.cs(24,0): at System.IO.FileSystem.Encrypt(String path)
        D:\j\workspace\arm64_cross_c---aca7f1c3\_\fx\src\System.IO.FileSystem\src\System\IO\File.cs(650,0): at System.IO.File.Encrypt(String path)
        D:\j\workspace\arm64_cross_c---aca7f1c3\_\fx\src\System.IO.FileSystem\tests\File\EncryptDecrypt.cs(45,0): at System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read()
```

**Comment by BruceForstall** [comment]
@karelz Someone want to investigate this corefx test failure?

**Comment by karelz** [comment]
@wfurt can you please help?

**Comment by wfurt** [comment]
That seems like environmental issue. 
cc: @bartonjs

**Comment by VincentBu** [comment]
Test failed again:
**Job:**
[coreclr-corefx-jitstressregs #20190909.1](https://dev.azure.com/dnceng/public/_build/results?buildId=345102)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/3d1b85ee-d1c3-4c77-bf48-d57c7e45cc08/workitems/System.IO.FileSystem.Tests/console

**OS & Arch:**
Windows x86

**Mode:**
set COMPlus_TieredCompilation=0
set COMPlus_JitStressRegs=8

**Log:**
```
System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read [FAIL]
      System.IO.IOException : The service has not been started. : 'C:\Users\runner\AppData\Local\Temp\tmp329.tmp'
      Stack Trace:
        /_/src/System.IO.FileSystem/src/System/IO/FileSystem.Win32.cs(60,0): at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath)
        /_/src/System.IO.FileSystem/src/System/IO/FileSystem.Win32.cs(24,0): at System.IO.FileSystem.Encrypt(String path)
        /_/src/System.IO.FileSystem/src/System/IO/File.cs(650,0): at System.IO.File.Encrypt(String path)
        /_/src/System.IO.FileSystem/tests/File/EncryptDecrypt.cs(44,0): at System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read()
    System.IO.Tests.Directory_CreateDirectory.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.DirectoryInfo_Create.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.File_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
  Finished:    System.IO.FileSystem.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Tests  Total: 5931, Errors: 0, Failed: 1, Skipped: 9, Time: 221.258s
 exit code 1 
```

**Comment by AriNuer** [comment]
Test failed again:
**Job:**
coreclr-corefx:[20190929.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=370045)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/de6e2465-2c94-4985-a762-e49b7d489c1f/workitems/System.IO.FileSystem.Tests/console

**OS & Arch:**
Wndows x86

**Mode:**
set COMPlus_TieredCompilation=0

**Log:**
```
C:\dotnetbuild\work\de6e2465-2c94-4985-a762-e49b7d489c1f\Work\4f7c4a21-0741-402c-bc72-44b317cb7429\Exec>"C:\dotnetbuild\work\de6e2465-2c94-4985-a762-e49b7d489c1f\Payload\dotnet.exe" exec --runtimeconfig System.IO.FileSystem.Tests.runtimeconfig.json xunit.console.dll System.IO.FileSystem.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\de6e2465-2c94-4985-a762-e49b7d489c1f\Payload\CoreFX.issues.rsp 
  Discovering: System.IO.FileSystem.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Tests (found 2938 of 3278 test cases)
  Starting:    System.IO.FileSystem.Tests (parallel test collections = on, max threads = 2)
    System.IO.Tests.FileInfo_GetSetTimes.MoveToMillisecondPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToMillisecondPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read [FAIL]
      System.IO.IOException : The service has not been started. : 'C:\Users\runner\AppData\Local\Temp\tmp3D6E.tmp'
      Stack Trace:
           at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath)
           at System.IO.FileSystem.Encrypt(String path)
           at System.IO.File.Encrypt(String path)
        /_/src/System.IO.FileSystem/tests/File/EncryptDecrypt.cs(44,0): at System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read()
    System.IO.Tests.File_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.Directory_CreateDirectory.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.DirectoryInfo_Create.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.DirectoryInfo_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.Directory_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
  Finished:    System.IO.FileSystem.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Tests  Total: 5932, Errors: 0, Failed: 1, Skipped: 9, Time: 173.478s
----- end Sun 09/29/2019 11:12:44.02 ----- exit code 1 ----------------------------------------------------------
```

**Comment by VincentBu** [comment]
**Job:**
[coreclr-corefx-jitstressregs #20191028.1 Run Test Pri1 CoreFX Windows_NT x64 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=404253)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/15aba9cc-89fc-4074-8d7b-0f1c0e66df25/workitems/System.IO.FileSystem.Tests/console

**OS & Arch:**
windows x64

**Mode:**
COMPlus_JitStressRegs=3
COMPlus_TieredCompilation=0

**Note:**
This failure **doesn't repro** on our windows x64 machine

**Log:**
```
C:\dotnetbuild\work\15aba9cc-89fc-4074-8d7b-0f1c0e66df25\Work\8652b25f-f875-425c-b9cd-f3d9042d65e0\Exec>"C:\dotnetbuild\work\15aba9cc-89fc-4074-8d7b-0f1c0e66df25\Payload\dotnet.exe" exec --runtimeconfig System.IO.FileSystem.Tests.runtimeconfig.json xunit.console.dll System.IO.FileSystem.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\15aba9cc-89fc-4074-8d7b-0f1c0e66df25\Payload\CoreFX.issues.rsp 
  Discovering: System.IO.FileSystem.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Tests (found 2940 of 3280 test cases)
  Starting:    System.IO.FileSystem.Tests (parallel test collections = on, max threads = 2)
    System.IO.Tests.FileInfo_GetSetTimes.MoveToMillisecondPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToMillisecondPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.File_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.Directory_CreateDirectory.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.Directory_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.DirectoryInfo_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.DirectoryInfo_Create.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read [FAIL]
      System.IO.IOException : The service has not been started. : 'C:\Users\runner\AppData\Local\Temp\tmpF519.tmp'
      Stack Trace:
           at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath)
        /_/src/System.IO.FileSystem/tests/File/EncryptDecrypt.cs(44,0): at System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read()
    System.IO.Tests.DirectoryInfo_ToString.ParentToString_Framework [SKIP]
      Condition(s) not met: "IsFullFramework"
  Finished:    System.IO.FileSystem.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Tests  Total: 5934, Errors: 0, Failed: 1, Skipped: 10, Time: 176.328s
exit code 1
```

**Comment by AriNuer** [comment]
**Job:**
[coreclr-corefx-jitstressregs:20191118.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=430563)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/4903276a-dc2c-4e20-9182-3d1d1fab844a/workitems/System.IO.FileSystem.Tests/console

**OS & Arch:**
Windows x86

**Mode:**
set COMPlus_TieredCompilation=0
set COMPlus_JitStressRegs=1

**Note:**
This failure **doesn't repro** on our windows x86 machine

**Log:**
```
C:\dotnetbuild\work\4903276a-dc2c-4e20-9182-3d1d1fab844a\Work\d010ed65-d034-4f2b-986c-d2693b1f8dcf\Exec>"C:\dotnetbuild\work\4903276a-dc2c-4e20-9182-3d1d1fab844a\Payload\dotnet.exe" exec --runtimeconfig System.IO.FileSystem.Tests.runtimeconfig.json xunit.console.dll System.IO.FileSystem.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\4903276a-dc2c-4e20-9182-3d1d1fab844a\Payload\CoreFX.issues.rsp 
  Discovering: System.IO.FileSystem.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.IO.FileSystem.Tests (found 2962 of 3308 test cases)
  Starting:    System.IO.FileSystem.Tests (parallel test collections = on, max threads = 2)
    System.IO.Tests.DirectoryInfo_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.Directory_CreateDirectory.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.Directory_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read [FAIL]
      System.IO.IOException : The service has not been started. : 'C:\Users\runner\AppData\Local\Temp\tmpF841.tmp'
      Stack Trace:
           at System.IO.FileSystem.ThrowExceptionEncryptDecryptFail(String fullPath)
           at System.IO.FileSystem.Encrypt(String path)
           at System.IO.File.Encrypt(String path)
        /_/src/System.IO.FileSystem/tests/File/EncryptDecrypt.cs(44,0): at System.IO.Tests.EncryptDecrypt.EncryptDecrypt_Read()
    System.IO.Tests.DirectoryInfo_Create.RootPath_AppContainer [SKIP]
      Condition(s) not met: "IsInAppContainer"
    System.IO.Tests.FileInfo_GetSetTimes.MoveToMillisecondPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToNanosecondsPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.CopyToMillisecondPresent_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.FileInfo_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.File_GetSetTimes.TimesIncludeMillisecondPart_HFS [SKIP]
      Condition(s) not met: "isHFS"
    System.IO.Tests.DirectoryInfo_ToString.ParentToString_Framework [SKIP]
      Condition(s) not met: "IsFullFramework"
  Finished:    System.IO.FileSystem.Tests
=== TEST EXECUTION SUMMARY ===
   System.IO.FileSystem.Tests  Total: 5956, Errors: 0, Failed: 1, Skipped: 10, Time: 193.452s
----- end Mon 11/18/2019 13:28:33.62 ----- exit code 1 ----------------------------------------------------------
```
