### ISSUE TITLE
Test failure: JIT.HardwareIntrinsics.X86.ScalarTernOpBinResTest__MultiplyNoFlagsUInt32.RunBasicScenario_UnsafeRead

### ISSUE THREAD

**Issue by jkotas** [dotnet/coreclr#23546]
```
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at JIT.HardwareIntrinsics.X86.ScalarTernOpBinResTest__MultiplyNoFlagsUInt32.RunBasicScenario_UnsafeRead()
   at JIT.HardwareIntrinsics.X86.Program.MultiplyNoFlagsUInt32BinRes()
   at JIT.HardwareIntrinsics.X86.Program.Main(System.String[])


Return code:      1
Raw output file:      C:\\dotnetbuild\\work\\9c2346ee-a8c9-488f-bc5f-9cf2ab13fd35\\Work\\4cd95052-0f4e-4bba-837b-b9aa42b944e9\\Exec\\Reports\\JIT.HardwareIntrinsics\\X86\\Bmi2\\Bmi2_r\\Bmi2_r.output.txt
Raw output:
BEGIN EXECUTION
 \"C:\\dotnetbuild\\work\\9c2346ee-a8c9-488f-bc5f-9cf2ab13fd35\\Payload\\corerun.exe\" Bmi2_r.exe 
Supported ISAs:
  AES:       True
  AVX:       True
  AVX2:      True
  BMI1:      True
  BMI2:      True
  FMA:       True
  LZCNT:     True
  PCLMULQDQ: True
  POPCNT:    True
  SSE:       True
  SSE2:      True
  SSE3:      True
  SSE4.1:    True
  SSE4.2:    True
  SSSE3:     True

Beginning test case ParallelBitDeposit.UInt32 at 3/28/2019 10:56:01 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 3/28/2019 10:56:01 PM
Beginning test case ParallelBitExtract.UInt32 at 3/28/2019 10:56:01 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 3/28/2019 10:56:01 PM
Beginning test case ZeroHighBits.UInt32 at 3/28/2019 10:56:01 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 3/28/2019 10:56:01 PM
Beginning test case MultiplyNoFlags.UInt32 at 3/28/2019 10:56:01 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Beginning scenario: RunBasicScenario_UnsafeRead
Beginning scenario: RunReflectionScenario_UnsafeRead
Beginning scenario: RunClsVarScenario
Beginning scenario: RunLclVarScenario_UnsafeRead
Beginning scenario: RunClassLclFldScenario
Beginning scenario: RunClassFldScenario
Beginning scenario: RunStructLclFldScenario
Beginning scenario: RunStructFldScenario

Ending test case at 3/28/2019 10:56:01 PM
Beginning test case MultiplyNoFlags.UInt32.BinRes at 3/28/2019 10:56:01 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

Expected: 100
Actual: -1073741819
END EXECUTION - FAILED
FAILED
Test Harness Exitcode is : 1
```

**Comment by jkotas** [comment]
Failed in: https://github.com/dotnet/coreclr/pull/23532

**Comment by jkotas** [comment]
Duplicate of https://github.com/dotnet/coreclr/issues/23534
