### ISSUE TITLE
System.Runtime.Serialization.SerializationException occurs on deserialize Calendar

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/coreclr#23567]
@SlavaB commented on [Wed Mar 20 2019](https://github.com/dotnet/winforms/issues/616)

* .NET Core 3.0 Preview 4
* Have you experienced this same bug with .NET Framework?: No

**Problem description:**

System.Runtime.Serialization.SerializationException with Message=Type 'System.Globalization.GregorianCalendar' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.
ocurrs. Please find the attached sample to reproduce.
[DotNetCore3Calendar.zip](https://github.com/dotnet/winforms/files/2986949/DotNetCore3Calendar.zip)

**Actual behavior:** 

System.Runtime.Serialization.SerializationException
  HResult=0x8013150C
  Message=Type 'System.Globalization.GregorianCalendar' in Assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not marked as serializable.
  Source=System.Runtime.Serialization.Formatters
  StackTrace:
   at System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(Type type)
   at System.Runtime.Serialization.FormatterServices.<>c.<GetSerializableMembers>b__5_0(MemberHolder mh)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Runtime.Serialization.FormatterServices.GetSerializableMembers(Type type, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitMemberInfo()
   at System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitReadConstructor(Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap.Create(String name, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryHeaderEnum binaryHeaderEnum)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at System.Resources.ResourceReader.<>c__DisplayClass44_0`1.<CreateUntypedDelegate>b__0(Object obj, Stream stream)
   at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.ResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.ResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at System.Resources.ResourceManager.GetObject(String name)
   at WindowsFormsAppCalendar.Form1.InitializeComponent() in \.Net Core 3\Apps\DotNetCore3Calendar\WindowsFormsAppCalendar\Form1.Designer.cs:line 38
   at WindowsFormsAppCalendar.Form1..ctor() in \.Net Core 3\Apps\DotNetCore3Calendar\WindowsFormsAppCalendar\Form1.cs:line 16
   at DotNetCore3Calendar.Program.Main() in \.Net Core 3\Apps\DotNetCore3Calendar\DotNetCore3Calendar\Program.cs:line 19

**Expected behavior:**

Run sample without exception.

**Minimal repro:**

* Unpack the attached sample. 
* Open the DotNetCore3Cal.sln solution in Visual Studio 2019
* Build and run the DotNetCore3Calendar.csproj project - exception raised

Note the WindowsFormsAppCalendar.csproj (.NET Framework 4.0 WinForms project) runs without exception.

---

@merriemcgaw commented on [Fri Mar 22 2019](https://github.com/dotnet/winforms/issues/616#issuecomment-475732175)

@dreddy-work can you take a look at this one? This relates to the resource serialization stuff you're working on. It may be that we need to consider WinForms controls like this one in our design.

---

@OliaG commented on [Wed Mar 27 2019](https://github.com/dotnet/winforms/issues/616#issuecomment-477402782)

@dreddy-work , any updates on this one?

---

@dreddy-work commented on [Thu Mar 28 2019](https://github.com/dotnet/winforms/issues/616#issuecomment-477868073)

Type System.Globalization.GregorianCalendar is coming from CoreLib.  Serializable tag is removed. It would be best addressed if we move this issue to coreclr repo and get the owner's attention.

---

@dreddy-work commented on [Thu Mar 28 2019](https://github.com/dotnet/winforms/issues/616#issuecomment-477871009)

@OliaG Can you please help move this issue to coreclr repo?

**Comment by RussKeldorph** [comment]
@tarekgh @danmosemsft

**Comment by jkotas** [comment]
.NET Core supports binary serialization for limited set of types only. The set is documented in: https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#serializable-types

Is it feasible to update your Windows Form application to avoid binary serialization of unsupported types?

**Comment by tarekgh** [comment]
I am not sure if this occurred in a real application. Looks the attachment to this issue is just a sample which has 

```C#
    public partial class UserControl1 : UserControl
    {
        [Editor(typeof(CalendarEditor), typeof(UITypeEditor))]
        public Calendar Calendar { get; set; }
    }
```

and include in the resources

```Xml
  <data name="userControl11.Calendar" mimetype="application/x-microsoft.net.object.binary.base64">
    <value>
        AAEAAAD/////AQAAAAAAAAAEAQAAACZTeXN0ZW0uR2xvYmFsaXphdGlvbi5HcmVnb3JpYW5DYWxlbmRh
        cgYAAAAGbV90eXBlEW1fY3VycmVudEVyYVZhbHVlD3R3b0RpZ2l0WWVhck1heBpDYWxlbmRhcittX2N1
        cnJlbnRFcmFWYWx1ZRVDYWxlbmRhcittX2lzUmVhZE9ubHkYQ2FsZW5kYXIrdHdvRGlnaXRZZWFyTWF4
        AwAAAAAAK1N5c3RlbS5HbG9iYWxpemF0aW9uLkdyZWdvcmlhbkNhbGVuZGFyVHlwZXMICAgBCAT+////
        K1N5c3RlbS5HbG9iYWxpemF0aW9uLkdyZWdvcmlhbkNhbGVuZGFyVHlwZXMBAAAAB3ZhbHVlX18ACAEA
        AAD///////////////8A/////ws=
</value>
  </data>
```

So, we just want to decide what to do in general here? this is not specific to Calendar type but can happen with any other type that used to be serialize on the full framework and not serialize anymore on .NET Core.

Should WinForm just document it support only the types listed in https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#serializable-types? 

CC @ViktorHofer

**Comment by dreddy-work** [comment]
@ericstj  as an FYI as we were talking about it this morning.

**Comment by ericstj** [comment]
I believe this one showed up in the data we gathered from real world apps by analyzing what they had in their resources.  @dreddy-work can you let us know where this was in the data?  Lots of hits, just a few?

I took a look at this type and it seems like it would be reasonable to support serialization for (though we may have to undo some field renames).

**Comment by tarekgh** [comment]
Just to mention, the calendar class has many calendar sub-classes. I hope we can avoid serializing such type because it is not really interesting for serialization and apps can still create such object without real need of serialization. Anyway, more data can help deciding what to do here.

**Comment by merriemcgaw** [comment]
It would be great if @SlavaB could help us with the user scenario here. Perhaps there are other ways to accomplish what he's looking to do. We didn't notice this at the top of our lists of types, so we can't comment on how important this class is.

**Comment by SlavaB** [comment]
@tarekgh, This sample has, surely, taken from real life. We have a component that persists its data by this way. @merriemcgaw, we'll discuss with team about importance of this issue.

**Comment by SlavaB** [comment]
We discussed this issue and agreed that we have a workaround for our control letting to avoid the Calendar serialization. Therefore this ticket can be closed if there are no people it is disturbed.

**Comment by tarekgh** [comment]
Thanks @SlavaB, closing this issue per your comment.

@merriemcgaw  please let's know if you get any other data suggest the otherwise.
