### ISSUE TITLE
AssemblyLoadContext.GetLoadContext(Assembly) throwing

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#23583]
With the following modification the corefx test is failing on Windows runs (except uapaot which skips the test)
```diff
diff --git a/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs b/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs
index 16e4c38..13aae6f 100644
--- a/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs
+++ b/src/System.Runtime.Loader/tests/DefaultContext/DefaultLoadContextTest.cs
@@ -96,12 +96,15 @@ namespace System.Runtime.Loader.Tests
             // Create a secondary load context and wireup its resolving event
             SecondaryLoadContext slc = new SecondaryLoadContext();
             slc.Resolving += ResolveAssembly;
 
+            Assert.Contains(slc, AssemblyLoadContext.All);
+
             // Attempt to load the assembly in secondary load context
             var slcLoadedAssembly = slc.LoadFromAssemblyName(assemblyName);
  
             // We should have successfully loaded the assembly in secondary load context.
             Assert.NotNull(slcLoadedAssembly);
+            Assert.Contains(slcLoadedAssembly, slc.Assemblies);
 
             // And make sure the simple name matches
             Assert.Equal(TestAssemblyName, slcLoadedAssembly.GetName().Name);
@@ -118,12 +121,13 @@ namespace System.Runtime.Loader.Tests
             AssemblyLoadContext.Default.Resolving += ResolveNullAssembly;
             AssemblyLoadContext.Default.Resolving += ResolveAssembly;
             AssemblyLoadContext.Default.Resolving += ResolveAssemblyAgain;
 
             // This will invoke the resolution via VM requiring to bind using the TPA binder
             var assemblyExpectedFromLoad = Assembly.Load(assemblyName);
 
             // We should have successfully loaded the assembly in default context.
             Assert.NotNull(assemblyExpectedFromLoad);
+            Assert.Contains(assemblyExpectedFromLoad, AssemblyLoadContext.Default.Assemblies);
 
             // We should have only invoked non-Null returning handler once
             Assert.Equal(1, _numNonNullResolutions);
```
Failure looks like this
```
C:\dotnetbuild\work\879f0c69-d11e-4b0a-a47c-f5358d852978\Work\a31874fc-8e7f-4c85-9315-92955288f871\Exec>"C:\dotnetbuild\work\879f0c69-d11e-4b0a-a47c-f5358d852978\Payload\dotnet.exe" xunit.console.dll System.Runtime.Loader.DefaultContext.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=failing -notrait category=OuterLoop 

  Discovering: System.Runtime.Loader.DefaultContext.Tests (method display = ClassAndMethod, method display options = None)

  Discovered:  System.Runtime.Loader.DefaultContext.Tests (found 2 test cases)

  Starting:    System.Runtime.Loader.DefaultContext.Tests (parallel test collections = on, max threads = 4)

0xC0000005
   at System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(System.Reflection.Assembly)
   at System.Runtime.Loader.AssemblyLoadContext+<get_Assemblies>d__46.MoveNext()
   at System.Linq.Enumerable.Contains[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.__Canon, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at Xunit.Assert.Contains[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Collections.Generic.IEqualityComparer`1<System.__Canon>)
   at Xunit.Assert.Contains[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon, System.Collections.Generic.IEnumerable`1<System.__Canon>)
   at System.Runtime.Loader.Tests.DefaultLoadContextTests.LoadInDefaultContext()
```

The failure occurs when the following code tries to get the ALC for an Assembly.
```C#
         public IEnumerable<Assembly> Assemblies
         {
             get
             {
                 foreach (Assembly a in GetLoadedAssemblies())
                 {
                     AssemblyLoadContext alc = GetLoadContext(a);
 
                     if (alc == this)
                     {
                         yield return a;
                     }
                 }
             }
         }
```

`AssemblyLoadContext.GetLoadContext(Assembly)` should not throw.
This also looks like it could be an unloadability issue.

**Comment by sdmaclea** [comment]
See dotnet/corefx#36465

**Comment by janvorli** [comment]
I am looking into it. I can confirm that I can repro it.

**Comment by janvorli** [comment]
So, the crash has nothing to do with unloadability. It happens when we are trying to get ALC for `C:\WINDOWS\system32\WinMetadata\Windows.Foundation.winmd`. In the `AssemblyNative::GetLoadContextForAssembly`, the `pOpaqueBinder` we get is an instance of `CLRPrivBinderWinRT`. But we assume it must be `CLRPrivBinderAssemblyLoadContext` and cast the pointer to that one. And then we call `GetManagedAssemblyLoadContext()` on it, which obviously returns a garbage `ptrManagedAssemblyLoadContext`.
This needs to be fixed by handling the case when `pOpaqueBinder` is `CLRPrivBinderWinRT` correctly.
