### ISSUE TITLE
[arm64] Test falied: System.Text.Json.Serialization.Tests.StringTests.Write

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#23645]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_minopts_tst/152/

**Failed tests:**
System.Text.Json.Serialization.Tests.StringTests.Write

**Log:**
```
System.Text.Json.Serialization.Tests.StringTests.Write(testObj: SimpleTestClassWithNulls { MyBooleanFalse = null, MyBooleanTrue = null, MyByte = null, MyChar = null, MyDateTime = null, ... }) [FAIL]
      System.ArgumentException : Destination array was not long enough. Check the destination index, length, and the array's lower bounds.
      Parameter name: destinationArray
      Stack Trace:
           at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
           at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
           at System.Collections.Generic.List`1.set_Capacity(Int32 value)
           at System.Collections.Generic.List`1.EnsureCapacity(Int32 min)
           at System.Collections.Generic.List`1.AddWithResize(T item)
           at System.Collections.Generic.List`1.Add(T item)
```

**Comment by BruceForstall** [comment]
@danmosemsft random failure? The next run didn't have any errors.

**Comment by danmosemsft** [comment]
@steveharter was this a known fix made? If not - there may be a bug here.

**Comment by danmosemsft** [comment]
Actually, this is fishy. How can this code fail this way? `value` is greater than or equal to `_size`. We make a new array with `value` elements and try to copy `_size` elements into it starting at offset `0`. How that that fail. @stephentoub any idea?

```c#
            set
            {
                if (value < _size)
                {
                    ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.value, ExceptionResource.ArgumentOutOfRange_SmallCapacity);
                }

                if (value != _items.Length)
                {
                    if (value > 0)
                    {
                        T[] newItems = new T[value];
                        if (_size > 0)
                        {
                            Array.Copy(_items, 0, newItems, 0, _size);
                        }
                        _items = newItems;
```

**Comment by steveharter** [comment]
The serialization code hasn't changed here recently. I suspect that it's a multi-threaded bug on cache warm-up. I created https://github.com/dotnet/corefx/issues/36547 to track.
