### ISSUE TITLE
[arm64/windows] ERROR: Timeout after 10 minutes

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#23644]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_jitstress2_jitstressregs1_tst/63/

**Failed log:**
```
ERROR: Timeout after 10 minutes
FATAL: Could not checkout 808e048c8535f9fd704acb75f1fa4aecdf36b72e
hudson.plugins.git.GitException: Command "git checkout -f 808e048c8535f9fd704acb75f1fa4aecdf36b72e" returned status code -1:
stdout: 
stderr: 
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1924)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$800(CliGitAPIImpl.java:71)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2214)
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to JNLP4-connect connection from 131.107.160.88/131.107.160.88:10022
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1693)
		at hudson.remoting.UserResponse.retrieve(UserRequest.java:310)
		at hudson.remoting.Channel.call(Channel.java:908)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.execute(RemoteGitImpl.java:146)
		at sun.reflect.GeneratedMethodAccessor259.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler.invoke(RemoteGitImpl.java:132)
		at com.sun.proxy.$Proxy181.execute(Unknown Source)
		at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1167)
		at hudson.scm.SCM.checkout(SCM.java:495)
		at hudson.model.AbstractProject.checkout(AbstractProject.java:1202)
		at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:574)
		at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
		at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
		at hudson.model.Run.execute(Run.java:1724)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
Caused: hudson.plugins.git.GitException: Could not checkout 808e048c8535f9fd704acb75f1fa4aecdf36b72e
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$9.execute(CliGitAPIImpl.java:2237)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
	at hudson.remoting.UserRequest.perform(UserRequest.java:207)
	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
	at hudson.remoting.Request$2.run(Request.java:358)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at hudson.remoting.Engine$1$1.run(Engine.java:98)
	at java.lang.Thread.run(Unknown Source)
[Current build status] check if current [FAILURE] is worse or equals then [FAILURE] and better or equals then [SUCCESS]
Run condition [Current build status] enabling perform for step [[Archive the artifacts]]
Archiving artifacts
[xUnit] [INFO] - Starting to record.
[xUnit] [INFO] - Processing xUnit.Net-v2 (default)
[xUnit] [INFO] - [xUnit.Net-v2 (default)] - No test report file(s) were found with the pattern 'bin/**/TestRun*.xml' relative to 'C:\j\workspace\arm64_cross_c---a3dd5b4e' for the testing framework 'xUnit.Net-v2 (default)'.  Did you enter a pattern relative to the correct directory?  Did you generate the result report(s) for 'xUnit.Net-v2 (default)'?
[xUnit] [WARNING] - No test reports found for the metric 'xUnit.Net' with the resolved pattern 'bin/**/TestRun*.xml'.
[xUnit] [INFO] - Skipping the metric tool processing.
[xUnit] [INFO] - There are errors when processing test results.
[xUnit] [INFO] - Skipping tests recording.
[BFA] Scanning build for known causes...
[BFA] Found failure cause(s):
[BFA] GitHub Timeout from category Infrastructure
[BFA] Done. 0s
[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Finished: FAILURE
```

**Comment by RussKeldorph** [comment]
Assuming network issue
