### ISSUE TITLE
CallbackTests.cmd and ResolveEventTests.cmd time out on Windows_NT x86 in PRs

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/coreclr#23941]
For example,
https://mc.dot.net/#/user/coreclr-ci/pr~2Fdotnet~2Fcoreclr~2Frefs~2Fpull~2F23916~2Fmerge/test~2Ffunctional~2Fr2r~2Fcli~2F/20190412.713/workItem/Interop/wilogs

```
  Discovering: Interop.NativeLibraryResolveCallback.XUnitWrapper

  Discovered:  Interop.NativeLibraryResolveCallback.XUnitWrapper

  Starting:    Interop.NativeLibraryResolveCallback.XUnitWrapper

    Interop\NativeLibraryResolveCallback\CallbackTests\CallbackTests.cmd [FAIL]

      
cmdLine:C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests\CallbackTests.cmd Timed Out

      

Return code:      -100
Raw output file:      C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\Reports\Interop.NativeLibraryResolveCallback\CallbackTests\CallbackTests.output.txt
Raw output:
BEGIN EXECUTION

              1 file(s) copied.

      " C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload\crossgen.exe"  /Platform_Assemblies_Paths C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload;C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests\IL;C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests /in CallbackTests.org /out CallbackTests.exe

      Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0

      Copyright (c) Microsoft Corporation.  All rights reserved.

      

      Native image CallbackTests.exe generated successfully.

       "C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload\corerun.exe" CallbackTests.exe 

      
cmdLine:C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests\CallbackTests.cmd Timed Out

      Test Harness Exitcode is : -100

      
To run the test:
> set CORE_ROOT=C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload
> C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveCallback\CallbackTests\CallbackTests.cmd


      Expected: True

      Actual:   False

      Stack Trace:

        F:\workspace\_work\1\s\bin\tests\Windows_NT.x86.Checked\TestWrappers\Interop.NativeLibraryResolveCallback\Interop.NativeLibraryResolveCallback.XUnitWrapper.cs(112,0): at Interop_NativeLibraryResolveCallback._CallbackTests_CallbackTests_._CallbackTests_CallbackTests_cmd()

  Finished:    Interop.NativeLibraryResolveCallback.XUnitWrapper

  Discovering: Interop.NativeLibraryResolveEvent.XUnitWrapper

  Discovered:  Interop.NativeLibraryResolveEvent.XUnitWrapper

  Starting:    Interop.NativeLibraryResolveEvent.XUnitWrapper

    Interop\NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.cmd [FAIL]

      
cmdLine:C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.cmd Timed Out

      

Return code:      -100
Raw output file:      C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\Reports\Interop.NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.output.txt
Raw output:
BEGIN EXECUTION

              1 file(s) copied.

      " C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload\crossgen.exe"  /Platform_Assemblies_Paths C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload;C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests\IL;C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests /in ResolveEventTests.org /out ResolveEventTests.exe

      Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0

      Copyright (c) Microsoft Corporation.  All rights reserved.

      

      Native image ResolveEventTests.exe generated successfully.

       "C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload\corerun.exe" ResolveEventTests.exe 

      
cmdLine:C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.cmd Timed Out

      Test Harness Exitcode is : -100

      
To run the test:
> set CORE_ROOT=C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Payload
> C:\dotnetbuild\work\4e090433-57c6-49bb-9125-aec3d3edac31\Work\85b7d86f-1623-4ea4-867f-3640b46ef123\Exec\Interop\NativeLibraryResolveEvent\ResolveEventTests\ResolveEventTests.cmd


      Expected: True

      Actual:   False

      Stack Trace:

        F:\workspace\_work\1\s\bin\tests\Windows_NT.x86.Checked\TestWrappers\Interop.NativeLibraryResolveEvent\Interop.NativeLibraryResolveEvent.XUnitWrapper.cs(112,0): at Interop_NativeLibraryResolveEvent._ResolveEventTests_ResolveEventTests_._ResolveEventTests_ResolveEventTests_cmd()
```

**Comment by sergiy-k** [comment]
@fadimounir, could you please take a look at these tests failing in the R2R mode?

**Comment by RussKeldorph** [comment]
@fadimounir Could we get these tests disabled or fixed ASAP?  We need to keep at least the official build testing green.

**Comment by RussKeldorph** [comment]
I should clarify that ResolveEventTests has also timed out on ARM64. https://mc.dot.net/#/user/dotnet-mc-bot-2/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fr2r~2Fcli~2F/20190417.71/workItem/Interop, not just x86

**Comment by RussKeldorph** [comment]
Similar situation for `Interop\PInvoke\SafeHandles\ReleaseHandle\ReleaseHandleTest\ReleaseHandleTest`

**Comment by fadimounir** [comment]
@RussKeldorph Taking a look

**Comment by fadimounir** [comment]
Hmm... I couldn't repro this using a Debug build. Let me try with CHK

**Comment by RussKeldorph** [comment]
@fadimounir Only ResolveEventTests ARM64 timed out on the latest run this morning: https://dev.azure.com/dnceng/internal/_build/results?buildId=160090&view=ms.vss-test-web.build-test-results-tab

**Comment by fadimounir** [comment]
I was able to repro the callback one locally. I'm currently debugging it

**Comment by fadimounir** [comment]
@RussKeldorph I'm pretty close to figuring out what the issue is, but not done yet. I still need a bit of debugging to be able to fix this issue. I'll disable the tests for the time being

**Comment by fadimounir** [comment]
Note to self: undo changes from #24121 when fixing bug
