### ISSUE TITLE
[JitStressRegs=0x80] System.Net.Requests.Tests fails with System.ArgumentNullException : Value cannot be null.\nParameter name: SafeHandle cannot be null.

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2398]
**Configuration**
 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release
 Ubuntu Linux 14.04 LTS on Hyper-V

Run run-test.sh **with sudo** to avoid corefx hang 

**Failures**

Pass without JitStressRegs=0x80
Fail with JitStressRegs=0x80 with exit code 2

System.Net.Requests.Tests  Total: 112, Errors: 0, Failed: 2, Skipped: 0, Time: 24.446s

Test names:

System.Net.Tests.HttpWebRequestTest.Headers_GetResponseHeaders_ContainsExpectedValue(remoteServer: http://corefx-networking.azurewebsites.net/Echo.ashx
System.Net.Tests.HttpWebRequestTest.Headers_GetResponseHeaders_ContainsExpectedValue(remoteServer: https://corefx-networking.azurewebsites.net/Echo.ashx

Stack trace:

   at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
   at Interop.GlobalizationInterop.CompareString(SafeSortHandle sortHandle, Char* lpStr1, Int32 cwStr1Len, Char* lpStr2, Int32 cwStr2Len, CompareOptions options)
   at System.Globalization.CompareInfo.CompareString(String string1, Int32 offset1, Int32 length1, String string2, Int32 offset2, Int32 length2, CompareOptions options)
   at System.__DTString.MatchSpecifiedWord(String target, Int32 endIndex)
   at System.DateTimeParse.MatchAbbreviatedDayName(__DTString& str, DateTimeFormatInfo dtfi, Int32& result)
   at System.DateTimeParse.ParseByFormat(__DTString& str, __DTString& format, ParsingInfo& parseInfo, DateTimeFormatInfo dtfi, DateTimeResult& result)
   at System.DateTimeParse.DoStrictParse(String s, String formatParam, DateTimeStyles styles, DateTimeFormatInfo dtfi, DateTimeResult& result)
   at System.DateTimeParse.TryParseExactMultiple(String s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, DateTimeResult& result)
   at System.DateTimeParse.TryParseExactMultiple(String s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, DateTime& result, TimeSpan& offset)
   at System.DateTimeOffset.TryParseExact(String input, String[] formats, IFormatProvider formatProvider, DateTimeStyles styles, DateTimeOffset& result)
   at System.Net.Http.HttpRuleParser.TryStringToDate(String input, DateTimeOffset& result)
   at System.Net.Http.Headers.DateHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
   at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(String name, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
   at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(String name, HeaderStoreItemInfo info)
   at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(String name, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
   at System.Net.Http.Headers.HttpHeaders.<GetEnumerator>d__20.MoveNext()
   at System.Net.HttpWebResponse.get_Headers()
   at System.Net.Tests.HttpWebRequestTest.<Headers_GetResponseHeaders_ContainsExpectedValue>d__46.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

**Comment by hoyMS** [comment]
Not repro with latest builds.
