### ISSUE TITLE
[arm64/windows] Test "Loader_ContextualReflection._ContextualReflection_ContextualReflection" failed with TestLibrary.AssertTestException: Assert.IsNotNull

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#24023]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_r2r_gcstress15_tst/47/

**Failed test:**
Loader_ContextualReflection._ContextualReflection_ContextualReflection_.Loader\\ContextualReflection\\ContextualReflection\\ContextualReflection.cmd

**Failed log:**
```
Loader\ContextualReflection\ContextualReflection\ContextualReflection.cmd [FAIL]
        
  Unhandled Exception: TestLibrary.AssertTestException: Assert.IsNotNull: 
           at TestLibrary.Assert.HandleFail(String assertionName, String message) in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\Common\CoreCLRTestLibrary\Assertion.cs:line 725
           at ContextualReflectionTest.Program.TestTypeGetType(Boolean isolated, Func`2 typeGetType) in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\Loader\ContextualReflection\ContextualReflection.cs:line 410
           at ContextualReflectionTest.Program.TestTypeGetType(Boolean isolated) in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\Loader\ContextualReflection\ContextualReflection.cs:line 359
           at ContextualReflectionTest.Program.RunTests(Boolean isolated) in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\Loader\ContextualReflection\ContextualReflection.cs:line 735
           at ContextualReflectionTest.Program.RunTests() in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\Loader\ContextualReflection\ContextualReflection.cs:line 728
           at ContextualReflectionTest.Program.Main() in D:\j\workspace\arm64_cross_c---0aaef436\tests\src\Loader\ContextualReflection\ContextualReflection.cs:line 32
  
  
  Return code:      1
  Raw output file:      C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Reports\Loader.ContextualReflection\ContextualReflection\ContextualReflection.output.txt
  Raw output:
  BEGIN EXECUTION
        
        C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Loader\ContextualReflection\ContextualReflection>set COMPLUS_NOGUIONASSERT=1 
        
        C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Loader\ContextualReflection\ContextualReflection>set COMPLUS_CONTINUEONASSERT=0 
        
        C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Loader\ContextualReflection\ContextualReflection>set COMPLUS_GCSTRESS=0xF 
        
        C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Loader\ContextualReflection\ContextualReflection>set COMPLUS_TIEREDCOMPILATION=0 
                1 file(s) copied.
        " C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\crossgen.exe"  /Platform_Assemblies_Paths C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root;C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Loader\ContextualReflection\ContextualReflection\IL;C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Loader\ContextualReflection\ContextualReflection /in ContextualReflection.org /out ContextualReflection.exe
        Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
        Copyright (c) Microsoft Corporation.  All rights reserved.
        
        Native image ContextualReflection.exe generated successfully.
         "C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root\corerun.exe" ContextualReflection.exe 
        Expected: 100
        Actual: -532462766
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        
  To run the test:
  > set CORE_ROOT=C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root
  > C:\j\workspace\arm64_cross_c---c8d6d889\bin\tests\Windows_NT.arm64.Checked\Loader\ContextualReflection\ContextualReflection\ContextualReflection.cmd
  
        Expected: True
        Actual:   False
        Stack Trace:
          D:\j\workspace\arm64_cross_c---0aaef436\bin\tests\Windows_NT.arm64.Checked\TestWrappers\Loader.ContextualReflection\Loader.ContextualReflection.XUnitWrapper.cs(112,0): at Loader_ContextualReflection._ContextualReflection_ContextualReflection_._ContextualReflection_ContextualReflection_cmd()
```

**Comment by danmosemsft** [comment]
@steveharter @GrabYourPitchforks this one is in you guys' area. Can this be safely deferred to Future?

**Comment by steveharter** [comment]
This only occurred once AFAIK, and around the same time the test \ feature was [added](https://github.com/dotnet/corefx/pull/37052).

@sdmaclea any thoughts?

Moving to future; likely can be closed unless we get another git.

**Comment by sdmaclea** [comment]
It seems to have happened once and only on arm64. I guess I would close this.
