### ISSUE TITLE
[arm64] System.Security.Cryptography.Xml.Tests.Reference_ArbitraryElements.Transforms_ExtraData_XmlProcessingInstruction

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24025]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x10_tst/28/

**Failed tests:**
System.Security.Cryptography.Xml.Tests.Reference_ArbitraryElements.Transforms_ExtraData_XmlProcessingInstruction

**Log:**
```
System.Security.Cryptography.Xml.Tests.Reference_ArbitraryElements.Transforms_ExtraData_XmlProcessingInstruction [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        D:\j\workspace\arm64_cross_c---16b68231\_\fx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\SignedXml.cs(1116,0): at System.Security.Cryptography.Xml.SignedXml.IsKeyTheCorrectAlgorithm(AsymmetricAlgorithm key, Type expectedType)
        D:\j\workspace\arm64_cross_c---16b68231\_\fx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\SignedXml.cs(1020,0): at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
        D:\j\workspace\arm64_cross_c---16b68231\_\fx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\SignedXml.cs(290,0): at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
        D:\j\workspace\arm64_cross_c---16b68231\_\fx\src\System.Security.Cryptography.Xml\src\System\Security\Cryptography\Xml\SignedXml.cs(272,0): at System.Security.Cryptography.Xml.SignedXml.CheckSignatureReturningKey(AsymmetricAlgorithm& signingKey)
        D:\j\workspace\arm64_cross_c---16b68231\_\fx\src\System.Security.Cryptography.Xml\tests\SignedXml_Helpers.cs(28,0): at System.Security.Cryptography.Xml.Tests.Helpers.VerifyCryptoExceptionOnLoad(String xml, Boolean loadXmlThrows)
        D:\j\workspace\arm64_cross_c---16b68231\_\fx\src\System.Security.Cryptography.Xml\tests\Reference_ArbitraryElements.cs(68,0): at System.Security.Cryptography.Xml.Tests.Reference_ArbitraryElements.Transforms_ExtraData_XmlProcessingInstruction()
```

**Comment by BruceForstall** [comment]
Kicked off https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x10_flow/38/ to see if it repros

**Comment by BruceForstall** [comment]
kicked off https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x10_flow/39/

**Comment by RussKeldorph** [comment]
Multiple instances of 
```
Assert failure(PID 10732 [0x000029ec], Thread: 4312 [0x10d8]): bSuccess

CORECLR! CreateCLRProfiling + 0x105210 (0x00007ffb`227d2f90)
CORECLR! CreateCLRProfiling + 0xFE024 (0x00007ffb`227cbda4)
CORECLR! CreateCLRProfiling + 0x43578 (0x00007ffb`227112f8)
<no module>! <no symbol> + 0x0 (0x00007ffa`c758f748)
    File: d:\j\workspace\arm64_cross_c---16b68231\src\md\compiler\regmeta_emit.cpp Line: 1014
    Image: C:\j\workspace\arm64_cross_c---81129547\_\fx\artifacts\bin\testhost\netcoreapp-Windows_NT-Release-arm64\dotnet.exe
```
as well as
#24108

**Comment by RussKeldorph** [comment]
@dotnet/dotnet-diag Is above Assert failure yours?

**Comment by davmason** [comment]
It looks like there are no symbols available, those offsets look bogus. It could be any assert and CreateCLRProfiling is the closest public symbol available.

There are two instances of  `_ASSERTE(bSuccess)` in regmeta_emit.cpp in `RegMeta::_DefineTypeRef` and `RegMeta::_DefineTypeDef`, without seeing a callstack I don't think it has anything to do with diagnostics work.

**Comment by BruceForstall** [comment]
Didn't fail in the latest:

https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_jitstressregs0x10_tst/31
