### ISSUE TITLE
[JitStressRegs=4] System.Xml.XmlSerializer.Tests fails with System.NullReferenceException : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2403]
**Configuration**
 Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreCLR tests: release
 Ubuntu Linux 14.04 LTS on Hyper-V

 Run run-test.sh **with sudo** to avoid corefx hang 

**Failure**
Pass without JitStressRegs=4
Fail with JitStressRegs=4 with exit code 9

Test names:
XmlSerializerTests.Xml_JaggedArrayAsRoot
XmlSerializerTests.Xml_TestTypeWithListPropertiesWithoutPublicSetters
XmlSerializerTests.Xml_EnumerableRoot
XmlSerializerTests.Xml_ListRoot
XmlSerializerTests.Xml_XmlAttributesTest
XmlSerializerTests.Xml_CollectionRoot
XmlSerializerTests.XML_TypeWithXmlTextAttributeOnArray
XmlSerializerTests.Xml_TypeWithXmlElementProperty
XmlSerializerTests.Xml_ConstructorWithXmlAttributeOverrides      

Stack trace:
```
System.NullReferenceException : Object reference not set to an instance of an object
  at System.Xml.Serialization.XmlSerializationWriterILGen.WriteArray(SourceInfo source, String choiceSource, ElementAccessor[] elements, TextAccessor text, ChoiceIdentifierAccessor choice, TypeDesc arrayTypeDesc)
   at System.Xml.Serialization.XmlSerializationWriterILGen.WriteEnumAndArrayTypes()
   at System.Xml.Serialization.XmlSerializationWriterILGen.WriteStructMethod(StructMapping mapping)
   at System.Xml.Serialization.XmlSerializationILGen.GenerateReferencedMethods()
   at System.Xml.Serialization.XmlSerializationWriterILGen.GenerateEnd()
   at System.Xml.Serialization.TempAssembly.GenerateRefEmitAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Object evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at XmlSerializerTests.SerializeAndDeserialize[T](T value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns)
   at XmlSerializerTests.Xml_JaggedArrayAsRoot()
```

Search for result="Fail"
[testResults.xml.txt](https://github.com/dotnet/coreclr/files/67299/testResults.xml.txt)

**Comment by hoyMS** [comment]
Not repro
