### ISSUE TITLE
[JitStressRegs=4] System.Reflection.Emit.Tests fails with exit code 3

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2404]
**Configuration**
Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release
 Ubuntu Linux 14.04 LTS on Hyper-V

 Run run-test.sh **with sudo** to avoid corefx hang 

**Failures**

Pass without COMPlus_JitStressRegs=4
Fail with COMPlus_JitStressRegs=4 with exit code 3.

Test names:
System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestWithMultipleGlobalMethods
System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestWithSingleGlobalMethod
System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestThrowsExceptionOnMultipleCallsToCreateGlobalFunctions

Stack trace:
```
System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestThrowsExceptionOnMultipleCallsToCreateGlobalFunctions [FAIL]
      System.TypeLoadException : Non-Static Global Method.
      Stack Trace:
            at System.Reflection.Emit.TypeBuilder.TermCreateClass(RuntimeModule module, Int32 tk, ObjectHandleOnStack type)
            at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
            at System.Reflection.Emit.TypeBuilder.CreateType()
            at System.Reflection.Emit.ModuleBuilder.CreateGlobalFunctionsNoLock()
            at System.Reflection.Emit.ModuleBuilder.CreateGlobalFunctions()
            at System.Reflection.Emit.Tests.ModuleBuilderCreateGlobalFunctions.TestThrowsExceptionOnMultipleCallsToCreateGlobalFunctions()
```

The details are attached and search for result="Fail"
[testResults.xml.txt](https://github.com/dotnet/coreclr/files/67300/testResults.xml.txt)

**Comment by hoyMS** [comment]
Not repro
