### ISSUE TITLE
runtest.py crash parsing failures

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#24183]
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x86/job/jitstress/job/x86_checked_windows_nt_jitx86hwintrinsicnoavx2/431/consoleFull

Test run had one failure:
```
05:31:33                                                       GRAND TOTAL: 10450          0          1           0        5552.797s (5628.209s)
```

Python stack:
```
05:31:44 Parsing test results from (D:\j\workspace\x86_checked_w---fa86ae90\bin\Logs\TestRunResults_Windows_NT_x86_Checked)
05:31:44 Traceback (most recent call last):
05:31:44   File "D:\j\workspace\x86_checked_w---fa86ae90\tests\runtest.py", line 2431, in <module>
05:31:44     sys.exit(main(args))
05:31:44   File "D:\j\workspace\x86_checked_w---fa86ae90\tests\runtest.py", line 2417, in main
05:31:44     tests = parse_test_results(host_os, arch, build_type, coreclr_repo_location, test_location)
05:31:44   File "D:\j\workspace\x86_checked_w---fa86ae90\tests\runtest.py", line 2092, in parse_test_results
05:31:44     test_output = failure_info[0].text
05:31:44   File "C:\Python27\lib\xml\etree\ElementTree.py", line 266, in __getitem__
05:31:44     return self._children[index]
05:31:44 IndexError: list index out of range
```

**Comment by BruceForstall** [comment]
cc @jashook

**Comment by BruceForstall** [comment]
cc @RussKeldorph @dotnet/jit-contrib
