### ISSUE TITLE
[arm64] Test failed: System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24180]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_minopts_tst/30/

**Failed tests:**
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly

**Log:**
```
System.Net.Http.Functional.Tests.SocketsHttpHandler_HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly(chunkedTransfer: True, connectionClose: True, mode: CancelPendingRequests) [FAIL]
      System.TypeLoadException : Could not load type 'System.IO.Stream+<FinishWriteAsync>d__60' from assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'.
      Stack Trace:
           at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
           at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
           at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1& derivedAttributes)
           at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
           at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeMethodInfo method, RuntimeType caType, Boolean inherit)
           at System.Reflection.RuntimeMethodInfo.GetCustomAttributes(Type attributeType, Boolean inherit)
           at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
           at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
           at System.Diagnostics.StackTrace.TryResolveStateMachineMethod(MethodBase& method, Type& declaringType)
           at System.Diagnostics.StackTrace.ToString(TraceFormat traceFormat)
           at System.Exception.GetStackTrace(Boolean needFileInfo)
           at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
           at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
           at System.Exception.ToString()
           at System.String.Concat(Object arg0, Object arg1, Object arg2)
        D:\j\workspace\arm64_cross_c---d6aee07b\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Cancellation.cs(406,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.ValidateClientCancellationAsync(Func`1 clientBodyAsync)
        D:\j\workspace\arm64_cross_c---d6aee07b\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Cancellation.cs(132,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.<>c__DisplayClass3_2.<<GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly>b__0>d.MoveNext()
        --- End of stack trace from previous location where exception was thrown ---
        D:\j\workspace\arm64_cross_c---d6aee07b\_\fx\src\Common\tests\System\Net\Http\LoopbackServer.cs(66,0): at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options)
        D:\j\workspace\arm64_cross_c---d6aee07b\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Cancellation.cs(114,0): at System.Net.Http.Functional.Tests.HttpClientHandler_Cancellation_Test.GetAsync_CancelDuringResponseBodyReceived_Buffered_TaskCanceledQuickly(Boolean chunkedTransfer, Boolean connectionClose, CancellationMode mode)
```

**Comment by BruceForstall** [comment]
@wfurt

**Comment by tommcdon** [comment]
@mikem8361 @sywhang

**Comment by wfurt** [comment]
looking at this again, this seems like some mismatch for assemblies. With all evidence gone I don't see this actionable unless we get repro.

**Comment by sywhang** [comment]
@jeffschwMSFT As far as I can tell this isn't a Diagnostics issue. Would be happy to investigate further if this is repro-able but from the callstack it just looks like a TypeLoad exception thrown from a mismatched assembly. 

I'll close this issue as no repro for now but if the failure happens again please feel free to open it again.
