### ISSUE TITLE
CoreFX test failure: System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#24184]
Looks like a timeout

https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_corefx_baseline/840/consoleFull

```
22:45:50      System.Net.Http.Functional.Tests.SocketsHttpHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent [FAIL]
22:45:50         System.TimeoutException : Task timed out after 00:00:30
22:45:50         Stack Trace:
22:45:50              at System.Threading.Tasks.TaskTimeoutExtensions.TimeoutAfter(Task task, TimeSpan timeout)
22:45:50           D:\j\workspace\x64_checked_w---a7bd363e\_\fx\src\System.Net.Http\tests\FunctionalTests\HttpClientHandlerTest.Cookies.cs(153,0): at System.Net.Http.Functional.Tests.HttpClientHandlerTest_Cookies.GetAsync_AddMultipleCookieHeaders_CookiesSent()
22:45:50           --- End of stack trace from previous location where exception was thrown ---
```

**Comment by BruceForstall** [comment]
@wfurt

**Comment by wfurt** [comment]
I look at the log and it seems like there are other long-running and aborted tests. I'm not sure if that is caused by checked build or if that is some kind of environmental issue. Nothing obvious pops for this particular test.

**Comment by wfurt** [comment]
https://mc.dot.net/#/product/netcore/30/source/official~2Fdotnet~2Fcorefx~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190423.5

seems like most tests are bombing out as well for Windows/ARM64. So this is either regression or environmental problem as the runs are normally stable.
