### ISSUE TITLE
[x64] Test failed: tracing\tracevalidation\inducedgc\inducedgc\inducedgc.cmd

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24399]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/x64/job/jitstress/job/x64_checked_windows_nt_minopts/841/

**Failed tests:**
tracing\tracevalidation\inducedgc\inducedgc\inducedgc.cmd

**Log:**
```
tracing\eventsource\eventsourcetrace\eventsourcetrace\eventsourcetrace.cmd [FAIL]
        
        Unhandled Exception: System.ArgumentException: String cannot have zero length.
           at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
           at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
           at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
           at System.Type.GetType(String typeName)
           at FastSerialization.Deserializer.GetFactory(String fullName)
           at FastSerialization.SerializationType.FastSerialization.IFastSerializable.FromStream(Deserializer deserializer)
           at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
           at FastSerialization.Deserializer.ReadObject()
           at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
           at FastSerialization.Deserializer.ReadObject()
           at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
           at FastSerialization.Deserializer.ReadObject()
           at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
           at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CopyRawEvents(TraceEventDispatcher rawEvents, IStreamWriter writer)
           at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.<>c__DisplayClass118_0.<FastSerialization.IFastSerializable.ToStream>b__0()
           at FastSerialization.DeferedRegion.Write(Serializer serializer, Action toStream)
           at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.FastSerialization.IFastSerializable.ToStream(Serializer serializer)
           at FastSerialization.Serializer.WriteObjectData(IFastSerializable obj, Tags beginTag)
           at FastSerialization.Serializer.WriteObjectRef(IFastSerializable obj, Boolean defered)
           at FastSerialization.Serializer..ctor(IStreamWriter writer, IFastSerializable entryObject)
           at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventPipeEventSources(TraceEventDispatcher source, String etlxFilePath, TraceLogOptions options)
           at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventPipeDataFile(String filePath, String etlxFilePath, TraceLogOptions options)
           at Tracing.Tests.EventSourceTrace.Main(String[] args) in D:\j\workspace\x64_checked_w---f9691bc8\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs:line 84
```

**Comment by RussKeldorph** [comment]
tracing\tracevalidation\inducedgc\inducedgc\inducedgc.cmd [FAIL]
        
        Unhandled Exception: System.Exception: Read past end of stream.
           at FastSerialization.IOStreamStreamReader.Fill(Int32 minimum)
           at FastSerialization.PinnedStreamReader.GetPointer(Int32 length)
           at Microsoft.Diagnostics.Tracing.EventPipeEventSource.ReadEvent(PinnedStreamReader reader)
           at Microsoft.Diagnostics.Tracing.EventPipeEventBlock.FromStream(Deserializer deserializer)
           at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
           at FastSerialization.Deserializer.ReadObject()
           at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
           at Tracing.Tests.TraceValidationInducedGC.Main(String[] args) in D:\j\workspace\x64_checked_w---a16971a7\tests\src\tracing\tracevalidation\inducedgc\InducedGC.cs:line 60
        
        Return code:      1
        Raw output file:      D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\Reports\tracing.tracevalidation\inducedgc\inducedgc\inducedgc.output.txt
        Raw output:
        BEGIN EXECUTION
         "D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root\corerun.exe" inducedgc.exe 
        	Start: Enable tracing.
        	End: Enable tracing.
        
        	Start: Generate some events.
        	End: Generate some events.
        
        	Start: Disable tracing.
        	End: Disable tracing.
        
        	Start: Process the trace file.
        Expected: 100
        Actual: -532462766
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\Tests\Core_Root
        > D:\j\workspace\x64_checked_w---a16971a7\bin\tests\Windows_NT.x64.Checked\tracing\tracevalidation\inducedgc\inducedgc\inducedgc.cmd
        Expected: True
        Actual:   False

**Comment by RussKeldorph** [comment]
Note that this is failed under COMPlus_JITMinOps=1.  That may be related, or it may just be an unstable test since it doesn't repro consistently.
