### ISSUE TITLE
[arm64] IOError: getaddrinfo failed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24408]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_r2r_jitstress1_tst/53/

**Log:**
```
Running tests R2R
Setting RunCrossGen=true
Setting __TestTimeout=900000
Setting CORE_ROOT=C:\j\workspace\arm64_cross_c---9f0d91aa\bin\tests\Windows_NT.arm64.Checked\Tests\Core_Root
Setting __TestEnv=c:\users\helixa~1\appdata\local\temp\tmpbexshz.bat
Download and overwrite xunit.console.dll in Core_Root
Traceback (most recent call last):
  File "C:\j\workspace\arm64_cross_c---9f0d91aa\tests\runtest.py", line 2431, in <module>
    sys.exit(main(args))
  File "C:\j\workspace\arm64_cross_c---9f0d91aa\tests\runtest.py", line 2405, in main
    lambda path: do_setup(host_os,
  File "C:\j\workspace\arm64_cross_c---9f0d91aa\tests\runtest.py", line 538, in create_and_use_test_env
    ret_code = func(test_env.name)
  File "C:\j\workspace\arm64_cross_c---9f0d91aa\tests\runtest.py", line 2414, in <lambda>
    path))
  File "C:\j\workspace\arm64_cross_c---9f0d91aa\tests\runtest.py", line 2363, in do_setup
    run_in_context=unprocessed_args.run_in_context)
  File "C:\j\workspace\arm64_cross_c---9f0d91aa\tests\runtest.py", line 1124, in run_tests
    urlretrieve(url, zipfilename)
  File "c:\python\lib\urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "c:\python\lib\urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "c:\python\lib\urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "c:\python\lib\urllib.py", line 443, in open_https
    h.endheaders(data)
  File "c:\python\lib\httplib.py", line 1049, in endheaders
    self._send_output(message_body)
  File "c:\python\lib\httplib.py", line 893, in _send_output
    self.send(msg)
  File "c:\python\lib\httplib.py", line 855, in send
    self.connect()
  File "c:\python\lib\httplib.py", line 1266, in connect
    HTTPConnection.connect(self)
  File "c:\python\lib\httplib.py", line 832, in connect
    self.timeout, self.source_address)
  File "c:\python\lib\socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno 11001] getaddrinfo failed
```

**Comment by RussKeldorph** [comment]
Assuming no longer relevant since we don't use runtest.py in CI
