### ISSUE TITLE
Test Failure: System.Runtime.Tests: Unhandled Exception: Xunit.Sdk.InRangeException: Assert.InRange() Failure

### ISSUE THREAD

**Issue by sandreenko** [dotnet/coreclr#24414]
Output:
```
04:18:47 /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Runtime.Tests/netcoreapp-Linux-Release-arm64 /home/robox/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/_/fx/artifacts/bin/tests/System.Runtime.Tests/netcoreapp-Linux-Release-arm64
04:18:47   Discovering: System.Runtime.Tests (method display = ClassAndMethod, method display options = None)
04:18:47   Discovered:  System.Runtime.Tests (found 5347 of 5402 test cases)
04:18:47   Starting:    System.Runtime.Tests (parallel test collections = on, max threads = 46)
04:18:47 
04:18:47 Unhandled Exception: Xunit.Sdk.InRangeException: Assert.InRange() Failure
04:18:47 Range:  (18216268922 - 9223372036854775807)
04:18:47 Actual: 17204253982
04:18:47    at Xunit.Assert.InRange[T](T actual, T low, T high, IComparer`1 comparer) in C:\projects\xunit\src\xunit.assert\Asserts\RangeAsserts.cs:line 41
04:18:47    at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 56
04:18:47 --- End of stack trace from previous location where exception was thrown ---
04:18:47    at Microsoft.DotNet.RemoteExecutorHost.Program.Main(String[] args) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutorHost/Program.cs:line 92
04:18:47     System.Tests.ArgIteratorTests.ArgIterator_GetNextArgType [SKIP]
04:18:47       Condition(s) not met: "IsArgIteratorSupported"
04:18:47     System.Tests.ArgIteratorTests.ArgIterator_GetRemainingCount_GetNextArg [SKIP]
04:18:47       Condition(s) not met: "IsArgIteratorSupported"
04:18:47 
    System.Tests.GCTests.GetGCMemoryInfo [FAIL]
04:18:47       Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.
04:18:47       Stack Trace:
04:18:47         
04:18:47         Child exception:
04:18:47           Xunit.Sdk.InRangeException: Assert.InRange() Failure
04:18:47         Range:  (18216268922 - 9223372036854775807)
04:18:47         Actual: 17204253982
04:18:47         /mnt/j/workspace/dotnet_coreclr/master/jitstress/arm64_cross_checked_ubuntu16.04_corefx_baseline/_/fx/src/System.Runtime/tests/System/GCTests.netcoreapp.cs(56,0): at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0()
04:18:47         
04:18:47         Child process:
04:18:47           System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()
04:18:47         
04:18:47         
04:18:47   Finished:    System.Runtime.Tests
04:18:47 === TEST EXECUTION SUMMARY ===
```

Started to fail in https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/arm64_cross_checked_ubuntu16.04_corefx_baseline_tst/192/

**Comment by danmosemsft** [comment]
same one ARM32 as ARM64 .. Ubuntu 1604
```
{ "HelixJobId": "b9ab4cca-558a-4603-a446-2a0c4b2239cd", "HelixWorkItemName": "System.Runtime.Tests" }


Error message
Microsoft.DotNet.RemoteExecutor.RemoteExecutionException : Remote process failed with an unhandled exception.

Stack trace

Child exception:
  Xunit.Sdk.InRangeException: Assert.InRange() Failure
Range:  (1 - 9223372036854775807)
Actual: -1844674407689672704
   at System.Tests.GCTests.<>c.<GetGCMemoryInfo>b__29_0() in /_/src/System.Runtime/tests/System/GCTests.netcoreapp.cs:line 35

Child process:
  System.Runtime.Tests, Version=4.2.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 System.Tests.GCTests+<>c Void <GetGCMemoryInfo>b__29_0()

```

**Comment by jeffschwMSFT** [comment]
Closing in favor of https://github.com/dotnet/coreclr/issues/25810
