### ISSUE TITLE
[arm64] System.Buffers.Text.Tests.Base64EncoderUnitTests failed

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#24436]
**Job:**
https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_minopts_tst/34/

**Failed tests:**
System.Buffers.Text.Tests.Base64EncoderUnitTests.BasicEncoding
System.Buffers.Text.Tests.Base64EncoderUnitTests.BasicEncodingWithFinalBlockFalse
System.Buffers.Text.Tests.Base64DecoderUnitTests.BasicDecoding

**Log:**
```
System.Buffers.Text.Tests.Base64EncoderUnitTests.BasicEncoding [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        D:\j\workspace\arm64_cross_c---d6aee07b\_\fx\src\System.Memory\tests\Base64\Base64EncoderUnitTests.cs(59,0): at System.Buffers.Text.Tests.Base64EncoderUnitTests.BasicEncoding()
    System.Buffers.Text.Tests.Base64EncoderUnitTests.BasicEncodingWithFinalBlockFalse [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        D:\j\workspace\arm64_cross_c---d6aee07b\_\fx\src\System.Memory\tests\Base64\Base64EncoderUnitTests.cs(136,0): at System.Buffers.Text.Tests.Base64EncoderUnitTests.BasicEncodingWithFinalBlockFalse()
    System.Buffers.Text.Tests.Base64DecoderUnitTests.BasicDecoding [FAIL]
      Assert.True() Failure
      Expected: True
      Actual:   False
      Stack Trace:
        D:\j\workspace\arm64_cross_c---d6aee07b\_\fx\src\System.Memory\tests\Base64\Base64DecoderUnitTests.cs(31,0): at System.Buffers.Text.Tests.Base64DecoderUnitTests.BasicDecoding()
```

**Comment by BruceForstall** [comment]
kicked off https://ci.dot.net/job/dotnet_coreclr/job/master/view/arm64/job/jitstress/job/arm64_cross_checked_windows_nt_corefx_minopts_flow/44/ to see if it repros

**Comment by jeffschwMSFT** [comment]
Closing this is old issue as the links are no longer available.  If it repro again we can file a new issue.
