### ISSUE TITLE
[EventPipe] Null passed as an event argument causes crash

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/coreclr#24469]
Test: 
coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs
Line 23: 
this.WriteEvent(1, x, y, z, **null**);
 
```
F:\TempRepo\coreclr>bin\tests\Windows_NT.x64.Debug\tracing\eventsource\eventsourcetrace\eventsourcetrace\eventsourcetrace.cmd
BEGIN EXECUTION
 "F:\TempRepo\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe" eventsourcetrace.exe
        Start: Enable tracing.
        End: Enable tracing.

        Start: Messaging.

Unhandled Exception: System.Diagnostics.Tracing.EventSourceException: Null passed as a event argument.
   at System.Diagnostics.Tracing.EventSource.ThrowEventSourceException(String eventName, Exception innerEx)
   at System.Diagnostics.Tracing.EventSource.WriteEventVarargs(Int32 eventId, Guid* childActivityID, Object[] args)
   at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, Object[] args)
   at Tracing.Tests.SimpleEventSource.MathResult(Int32 x, Int32 y, Int32 z, String formula) in F:\TempRepo\coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs:line 23
   at Tracing.Tests.EventSourceTrace.Main(String[] args) in F:\TempRepo\coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs:line 75
Expected: 100
Actual: 255
END EXECUTION - FAILED
FAILED
```

**Comment by sywhang** [comment]
@brianrob Is this an expected behavior that's working as design? I tried something similar on Framework and it doesn't seem to be throwing there. Just wanted to know what the correct behavior should be here before I put out a "fix" :-)

**Comment by brianrob** [comment]
@sywhang, I would expect a null argument passed for ```formula``` in ```Tracing.Tests.SimpleEventSource.MathResult(Int32 x, Int32 y, Int32 z, String formula)``` should result in that null being written into the trace file.  Said another way, null is a legal value for reference types.

**Comment by jorive** [comment]
I think the function being called here is `WriteEvent(Int32, param object[])`

**Comment by brianrob** [comment]
Right - every manifest based event is implemented as something that looks like this:

```
[Event(1)]
public void MathResult(Int32 x, Int32 y, Int32 z, String formula)
{
    WriteEvent(1, x, y, z, formula);
}
```

There are various overloads of WriteEvent to avoid the array allocation and subsequent boxing associated with param object[], but if there isn't a specialized overload for the set of arguments to the event then the compiler will bind to ```WriteEvent(Int32, param object[])```.

So even though you see the exception inside fo ```WriteEvent```, the work being done is on-behalf-of the event method.
