### ISSUE TITLE
[JitStressRegs=4] System.Threading.Tasks.Parallel.Tests fails with  System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest33 [FAIL]

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2458]
**Configuration**
Debug CoreCLR runtime: coreclr.dll, corerun.exe and mscorlib.dll
 CoreFX assemblies and CoreFX tests: release

**Command line and stack trace**

corefx/bin/tests/Linux.AnyCPU.Release/System.Threading.Tasks.Parallel.Tests/dnxcore50$ ./corerun xunit.console.netcore.exe System.Threading.Tasks.Parallel.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Threading.Tasks.Parallel.Tests
Discovered:  System.Threading.Tasks.Parallel.Tests
Starting:    System.Threading.Tasks.Parallel.Tests
   System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest33 [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
            at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEach[TSource,TLocal](IEnumerable`1 source, Func`1 localInit, Func`5 body, Action`1 localFinally)
            at System.Threading.Tasks.Tests.ParallelForTest.ParallelForeachWithLocalAndIndex()
            at System.Threading.Tasks.Tests.ParallelForTest.RealRun()
            at System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest33()
         ----- Inner Stack Trace #1 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #2 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest35 [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
            at System.Threading.Tasks.Tests.ParallelForTest.ParallelForEach()
            at System.Threading.Tasks.Tests.ParallelForTest.RealRun()
            at System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest35()
   System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest25 [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
            at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEach[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Func`1 localInit, Func`5 body, Action`1 localFinally)
            at System.Threading.Tasks.Tests.ParallelForTest.ParallelForEachWithOptionsAndLocalAndIndex()
            at System.Threading.Tasks.Tests.ParallelForTest.RealRun()
            at System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest25()
         ----- Inner Stack Trace #1 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #2 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest31 [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
            at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEach[TSource,TLocal](IEnumerable`1 source, Func`1 localInit, Func`5 body, Action`1 localFinally)
            at System.Threading.Tasks.Tests.ParallelForTest.ParallelForeachWithLocalAndIndex()
            at System.Threading.Tasks.Tests.ParallelForTest.RealRun()
            at System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest31()
         ----- Inner Stack Trace -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest46 [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      Stack Trace:
            at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEach[TSource,TLocal](IEnumerable`1 source, Func`1 localInit, Func`4 body, Action`1 localFinally)
            at System.Threading.Tasks.Tests.ParallelForTest.ParallelForeachWithLocal()
            at System.Threading.Tasks.Tests.ParallelForTest.RealRun()
            at System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest46()
         ----- Inner Stack Trace #1 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #2 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #3 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #4 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #5 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #6 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #7 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #8 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #9 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest22 [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      ---- System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
            at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEach[TSource,TLocal](IEnumerable`1 source, Func`1 localInit, Func`5 body, Action`1 localFinally)
            at System.Threading.Tasks.Tests.ParallelForTest.ParallelForeachWithLocalAndIndex()
            at System.Threading.Tasks.Tests.ParallelForTest.RealRun()
            at System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest22()
         ----- Inner Stack Trace #1 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #2 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #3 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #4 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #5 (System.NullReferenceException) -----
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest43 [FAIL]
      System.AggregateException : One or more errors occurred.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      ---- System.IndexOutOfRangeException : Index was outside the bounds of the array.
      Stack Trace:
            at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
            at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
            at System.Threading.Tasks.Parallel.ForEach[TSource,TLocal](IEnumerable`1 source, Func`1 localInit, Func`4 body, Action`1 localFinally)
            at System.Threading.Tasks.Tests.ParallelForTest.ParallelForeachWithLocal()
            at System.Threading.Tasks.Tests.ParallelForTest.RealRun()
            at System.Threading.Tasks.Tests.ParallelForUnitTests.ParallelForTest43()
         ----- Inner Stack Trace #1 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
         ----- Inner Stack Trace #2 (System.IndexOutOfRangeException) -----
            at System.Threading.Tasks.Tests.ParallelForTest.InvokeZetaWorkload(Int32 i)
            at System.Threading.Tasks.Tests.ParallelForTest.WorkWithLocal(Int32 i, ParallelLoopState state, List`1 threadLocalValue)
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
            at System.Threading.Tasks.TaskReplicator.Replica.Execute()
Segmentation fault (core dumped)

**Comment by hoyMS** [comment]
Not repro.

**Comment by sejongoh** [comment]
I can reproduce this with the following commits. 

Coreclr: 761fa46 (Wed Jan 13 18:15:58 2016 -0500)
Corefx: 0824d9745687271503f7538d16f44f17f5ef5f18 (Tue Jan 12 14:49:52 2016 -0800)

I sometimes see different errors:

```

corefx/bin/tests/Linux.AnyCPU.Release/System.Threading.Tasks.Parallel.Tests/dnxcore50$ 
COMPlus_JitStressRegs=4 ./corerun xunit.console.netcore.exe System.Threading.Tasks.Parallel.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true

xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Threading.Tasks.Parallel.Tests
Bus error (core dumped)
```
```
COMPlus_JitStressRegs=4 ./corerun xunit.console.netcore.exe System.Threading.Tasks.Parallel.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Threading.Tasks.Parallel.Tests
Discovered:  System.Threading.Tasks.Parallel.Tests
Starting:    System.Threading.Tasks.Parallel.Tests
   System.Threading.Tasks.Tests.ParallelForTests.TestParallelForEachConversions [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   45
      Stack Trace:
            at System.Threading.Tasks.Tests.ParallelForTests.TestParallelForEachConversions()
Finished:    System.Threading.Tasks.Parallel.Tests
```

**Comment by sejongoh** [comment]
This issue looks a duplicate of #2380.
