### ISSUE TITLE
Environment.GetEnvironmentVariables throws ArgumentException due to internal error

### ISSUE THREAD

**Issue by AArnott** [dotnet/coreclr#24648]
We saw [a test failure](https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=2686250&_a=summary&view=ms.vss-test-web.unified-test-results-tab&runId=6183152&resultId=100094&paneView=attachments) in an Azure Pipelines test run of our own product that failed after switching from msbuild to `dotnet build`. It appears that `Environment.GetEnvironmentVariables()` may have encountered an unfamiliar environment. 

```
script stdout: VERBOSE: dotnet build ServiceHub.Sample.NugetClientApp.csproj /p:Configuration=Release /v:m /nr:false
script stderr: System.ArgumentException: Item has already been added. Key in dictionary: 'CODE_COVERAGE_SESSION_NAME'  Key being added: 'CODE_COVERAGE_SESSION_NAME'
script stderr:    at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
script stderr:    at System.Environment.ToHashtable(IEnumerable`1 pairs)
script stderr:    at System.Environment.GetEnvironmentVariables()
script stderr:    at System.Diagnostics.ProcessStartInfo.get_Environment()
script stderr:    at Microsoft.DotNet.Cli.Utils.ForwardingAppImplementation.GetProcessStartInfo()
script stderr:    at Microsoft.DotNet.Cli.Utils.MSBuildForwardingAppWithoutLogging.GetProcessStartInfo()
script stderr:    at Microsoft.DotNet.Tools.MSBuild.MSBuildForwardingApp.GetProcessStartInfo()
script stderr:    at Microsoft.DotNet.Tools.RestoringCommand.Execute()
script stderr:    at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args)
script stderr:    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
script stderr:    at Microsoft.DotNet.Cli.Program.Main(String[] args)
script stderr: dotnet build failure. Exit code: 1
```

.NET SDK version: 2.2.105

**Comment by kevingosse** [comment]
It looks like another occurrence of https://github.com/dotnet/corefx/issues/34263 and https://github.com/dotnet/corefx/issues/30341

**Comment by AArnott** [comment]
Agreed. Thanks.
