### ISSUE TITLE
Test failure: Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_/_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#24661]
The test `Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_/_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd` has failed.

Failure Message:
```
\r
Return code:      1\r
Raw output file:      C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Work\\5ff48737-f514-4c3e-a14e-6fea1160135f\\Exec\\Interop\\WinRT\\Reports\\Interop.WinRT\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.output.txt\r
Raw output:\r
BEGIN EXECUTION\r
 \"C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Payload\\corerun.exe\" NETClientPrimitives.exe \r
System.Runtime.InteropServices.COMException (0x80040154): Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))\r
   at System.StubHelpers.UriMarshaler.CreateNativeUriInstanceHelper(Char* rawUri, Int32 strLen)\r
   at System.StubHelpers.UriMarshaler.CreateNativeUriInstance(String rawUri)\r
   at Component.Contracts.IUriTesting.GetFromUri(Uri uri)\r
   at NetClient.UriTests.RunTest() in F:\\workspace\\_work\\1\\s\\tests\\src\\Interop\\WinRT\\NETClients\\Primitives\\UriTests.cs:line 15\r
   at NetClient.Program.Main(String[] args) in F:\\workspace\\_work\\1\\s\\tests\\src\\Interop\\WinRT\\NETClients\\Primitives\\Program.cs:line 28\r
Expected: 100\r
Actual: 101\r
END EXECUTION - FAILED\r
FAILED\r
Test Harness Exitcode is : 1\r
To run the test:\r
> set CORE_ROOT=C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Payload\r
> C:\\work\\a41b0e25-9123-49be-81b6-6d0e4c6a89b9\\Work\\5ff48737-f514-4c3e-a14e-6fea1160135f\\Exec\\Interop\\WinRT\\NETClients\\Primitives\\NETClientPrimitives\\NETClientPrimitives.cmd\r
Expected: True\r
Actual:   False
```

Stack Trace:
```
   at Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd() in F:\workspace\_work\1\s\bin\tests\Windows_NT.x64.Release\TestWrappers\Interop.WinRT\Interop.WinRT.XUnitWrapper.cs:line 218
```

Build : Master - 20190519.72 (Core Tests)
Failing configurations:
- Windows.10.Nano.Amd64-x64
  - 
  - 

Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190519.72/workItem/Interop/analysis/xunit/Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_~2F_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

**Comment by AriNuer** [comment]
Same test failed again with Unhandled Exception: System.Exception: Invalid RegGetValueW result: 0x2 type: RegNone
Details:
https://mc.dot.net/#/product/netcore/master/source/official~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/type/test~2Ffunctional~2Fcli~2F/build/20190521.72/workItem/Interop/analysis/xunit/Interop_WinRT._NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_~2F_NETClients_Primitives_NETClientPrimitives_NETClientPrimitives_cmd

**Comment by AaronRobinsonMSFT** [comment]
@jkoritzinsky This is a different issue. The here issue here addressed Nano, but it looks like the failure is on Arm64, not a Nano.Amd64 server run.

**Comment by AaronRobinsonMSFT** [comment]
Bah. Looks like the very act of trying to determine if this is a Windows.Nano scenario is the issue.

```
Unhandled Exception: System.Exception: Invalid RegGetValueW result: 0x2 type: RegNone
   at TestLibrary.Utilities.GetRegistryValueString(String key, String value) in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 247
   at TestLibrary.Utilities.GetInstallationTypeForWindows() in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 193
   at TestLibrary.Utilities.GetInstallationType() in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 181
   at TestLibrary.Utilities.get_IsWindowsNanoServer() in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 71
   at TestLibrary.Utilities.get_IsWinRTSupported() in F:\\workspace\\_work\\1\\s\\tests\\src\\Common\\CoreCLRTestLibrary\\Utilities.cs:line 70
   at NetClient.Program.Main(String[] args) in F:\\workspace\\_work\\1\\s\\tests\\src\\Interop\\WinRT\\NETClients\\Primitives\\Program.cs:line 13
```

**Comment by AaronRobinsonMSFT** [comment]
Got it. This is an issue with how we detect Windows Nano. When the code was ported from CoreFX, the `where` clause was kept, but shouldn't be because we are P/Invoking into the registry APIs instead of calling the `Registry` library.

The change is to remove the `where` clause which will capture all exceptions which is basically what we want.

https://github.com/dotnet/coreclr/blob/aa66f12b58dc11857db5796ff49bd46dd242dd82/tests/src/Common/CoreCLRTestLibrary/Utilities.cs#L195
