### ISSUE TITLE
Crash happen when there is not enough space on the disk for the netperf file

### ISSUE THREAD

**Issue by jiangzeng01** [dotnet/coreclr#24691]
Test:
coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs

Repro steps:
1. Create a VHD with 10MB fixed size.
2. Change netperf file path in the file "coreclr\tests\src\tracing\common\NetPerfFile.cs" to point to the VHD
3. Build & run the test.
4. Crash happen with following exception.

Exception:
```
BEGIN EXECUTION
 "F:\TempRepo\coreclr\bin\tests\Windows_NT.x64.Debug\Tests\Core_Root\corerun.exe" eventsourcetrace.exe
        Start: Enable tracing.
        End: Enable tracing.

        Start: Messaging.
        End: Messaging.

        Start: Disable tracing.
        End: Disable tracing.

        Start: Processing events from file.

Unhandled Exception: System.IO.IOException: There is not enough space on the disk. : 'E:\becf7070-0f27-4604-8e96-4b79a32ec6bf.netperf.etlx.new'
   at System.IO.FileStream.WriteCore(ReadOnlySpan`1 source)
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at FastSerialization.IOStreamStreamWriter.MakeSpace()
   at FastSerialization.MemoryStreamWriter.Write(Int32 value)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.WriteBlob(IntPtr source, IStreamWriter writer, Int32 byteCount)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.<>c__DisplayClass83_0.<CopyRawEvents>b__1(TraceEvent data)
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.DoDispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.Dispatch(TraceEvent anEvent)
   at Microsoft.Diagnostics.Tracing.EventPipeEventBlock.FromStream(Deserializer deserializer)
   at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
   at FastSerialization.Deserializer.ReadObject()
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CopyRawEvents(TraceEventDispatcher rawEvents, IStreamWriter writer)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.<>c__DisplayClass118_0.<FastSerialization.IFastSerializable.ToStream>b__0()
   at FastSerialization.DeferedRegion.Write(Serializer serializer, Action toStream)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.FastSerialization.IFastSerializable.ToStream(Serializer serializer)
   at FastSerialization.Serializer.WriteObjectData(IFastSerializable obj, Tags beginTag)
   at FastSerialization.Serializer.WriteObjectRef(IFastSerializable obj, Boolean defered)
   at FastSerialization.Serializer..ctor(IStreamWriter writer, IFastSerializable entryObject)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventPipeEventSources(TraceEventDispatcher source, String etlxFilePath, TraceLogOptions options)
   at Microsoft.Diagnostics.Tracing.Etlx.TraceLog.CreateFromEventPipeDataFile(String filePath, String etlxFilePath, TraceLogOptions options)
   at Tracing.Tests.EventSourceTrace.Main(String[] args) in F:\TempRepo\coreclr\tests\src\tracing\eventsource\eventsourcetrace\EventSourceTrace.cs:line 85
Expected: 100
Actual: 255
END EXECUTION - FAILED
```

**Comment by sywhang** [comment]
Looks like this crash is not in the runtime, but in TraceEvent library.. I don't think this is a product issue.

**Comment by jiangzeng01** [comment]
@sywhang thanks, I will close it.
