### ISSUE TITLE
Run crashes without output. Internal CLR error 0x80131506 after clean.

### ISSUE THREAD

**Issue by arcooke** [dotnet/coreclr#24727]
Hi.  I am running core 3 preview on two linux systems.  Same versions, same projects, both installed with snaps.  The runtime crashes on Solus, but not on KDE Neon (Ubuntu 18.04) 

**DOES** crash:
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     solus
 OS Version:  4.0
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/37/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  3.0.100-preview5-011568 [/snap/dotnet-sdk/37/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/snap/dotnet-sdk/37/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/snap/dotnet-sdk/37/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Does **NOT** crash:
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.0.100-preview5-011568
 Commit:    b487ff10aa

Runtime Environment:
 OS Name:     neon
 OS Version:  18.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /snap/dotnet-sdk/37/sdk/3.0.100-preview5-011568/

Host (useful for support):
  Version: 3.0.0-preview5-27626-15
  Commit:  61f30f5a23

.NET Core SDKs installed:
  3.0.100-preview5-011568 [/snap/dotnet-sdk/37/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.0.0-preview5-19227-01 [/snap/dotnet-sdk/37/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0-preview5-27626-15 [/snap/dotnet-sdk/37/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

---

(the rest of this is related only to the Solus system)

The first issue I encountered is `dotnet run` was crashing without any output.  See a screen recording here: 

https://i.imgur.com/T0cbkZY.gifv

After a bit of testing, I got an internal CLR error at the end of a `dotnet clean`.. but this only happened once.  I can't get that error to come back.  I'm not certain if this is related.

```
$ dotnet clean
Microsoft (R) Build Engine version 16.0.462+g62fb89029d for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/22/2019 12:29:45 PM.
     1>Project "/home/adam/Source/cura/cura-api/cura-api.csproj" on node 1 (Clean target(s)).
     1>_CheckForNETCoreSdkIsPreview:
       /snap/dotnet-sdk/current/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/home/adam/Source/cura/cura-api/cura-api.csproj]
       CoreClean:
         Deleting file ... blah blah ...
         Deleting file ... blah blah ...
         ...
         ...
         ...
         Deleting file ... blah blah ...
         Deleting file ... blah blah ...         
     1>Done Building Project "/home/adam/Source/cura/cura-api/cura-api.csproj" (Clean target(s)).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.64
Internal CLR error. (0x80131506)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at Interop+Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback, IPv6AddressDiscoveredCallback, LinkLayerAddressDiscoveredCallback)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetIsNetworkAvailable()
   at System.Net.NetworkInformation.NetworkInterface.GetIsNetworkAvailable()
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.Send(Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.StorageTransmission, System.TimeSpan ByRef)
   at Microsoft.DotNet.Cli.Telemetry.PersistenceChannel.Sender.SendLoop()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task+<>c.<.cctor>b__274_0(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(System.Threading.Thread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler+<>c.<.cctor>b__10_0(System.Object)
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
```

If there is a log file somewhere that might help, just let me know where to find it and I will provide that.  Thanks

**Comment by janvorli** [comment]
@arcooke could you please try that with a simple hello world app (unless that's what you were using)? Just run `dotnet new console`. I would then run `dotnet restore` and `dotnet build` separately, the `dotnet run` combines those and it seems likely that one of these was actually crashing.

**Comment by janvorli** [comment]
Seems to be a dup of https://github.com/dotnet/cli/issues/11403

**Comment by arcooke** [comment]
> @arcooke could you please try that with a simple hello world app (unless that's what you were using)? Just run `dotnet new console`. I would then run `dotnet restore` and `dotnet build` separately, the `dotnet run` combines those and it seems likely that one of these was actually crashing.

Thanks

I just tried this with a simple hello world app, and it still crashes in the same way.  I don't have any issues with `dotnet restore` or `dotnet build` separately, but it still crashes with no output on `dotnet run`

```
$ dotnet new console
The template "Console Application" was created successfully.

Processing post-creation actions...
Running 'dotnet restore' on /home/adam/Source/hello/hello.csproj...
  Restore completed in 59.32 ms for /home/adam/Source/hello/hello.csproj.

Restore succeeded.

adam@adam-solus ~/Source/hello $ dotnet restore
  Restore completed in 14.83 ms for /home/adam/Source/hello/hello.csproj.
adam@adam-solus ~/Source/hello $ dotnet build
Microsoft (R) Build Engine version 16.0.462+g62fb89029d for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 14.95 ms for /home/adam/Source/hello/hello.csproj.
/snap/dotnet-sdk/current/sdk/3.0.100-preview5-011568/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.RuntimeIdentifierInference.targets(157,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview [/home/adam/Source/hello/hello.csproj]
  hello -> /home/adam/Source/hello/bin/Debug/netcoreapp3.0/hello.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.14
adam@adam-solus ~/Source/hello $ dotnet run
adam@adam-solus ~/Source/hello $ dotnet run
adam@adam-solus ~/Source/hello $ 
```
