### ISSUE TITLE
dotnet restore NullReferenceException

### ISSUE THREAD

**Issue by mafshin** [dotnet/coreclr#2499]
Following [Getting Started](https://dotnet.github.io/getting-started) Console app with .NET Core just after `dotnet new` I get a `NullReferenceException` for `dotnet restore`:

```
D:\Test>dotnet restore
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dnx.Tooling.Program.Main(String[] args)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Dnx.Runtime.Common.EntryPointExecutor.Execute(Assembly assembly, String[] args, IServiceProvider serviceProvider)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)
```

**Comment by joshfree** [comment]
Hi @mafshin I've moved this bug to the CLI repo: https://github.com/dotnet/cli/issues/750
