### ISSUE TITLE
[RyuJIT/Linux/x86] Tail-call optimization leads to assert on Linux/x86 

### ISSUE THREAD

**Issue by kbaladurin** [dotnet/coreclr#25020]
Following example crashes due to assert in `morph.cpp` on Linux/x86:
```cs
using System;
using System.Reflection;
using System.Reflection.Emit;

namespace jitx86
{
    class Program
    {    
        static void Main(string[] args)
        {
            DynamicMethod dm = new DynamicMethod("MyMethod", typeof(string), new Type[] { typeof(string), typeof(string) });
            
            ILGenerator generator = dm.GetILGenerator();
            generator.Emit(OpCodes.Ldarg_0);
            generator.Emit(OpCodes.Ldarg_1);
            generator.Emit(OpCodes.Tailcall);
            generator.EmitCall(OpCodes.Call, typeof(String).GetMethod("Concat", new Type[] { typeof(string), typeof(string) }), null);
            generator.Emit(OpCodes.Ret);

            string a = "1234";
            string b = "abcd";
            
            Console.WriteLine(dm.Invoke(null, BindingFlags.Default, null, new object[] {a, b}, null));
        }
    }
}
```
```
$ ./corerun jitx86.dll
...
Morphing BB01 of 'DynamicClass:MyMethod(ref,ref):ref'

fgMorphTree BB01, stmt 1 (before)
               [000006] --C-G-------              *  RETURN    ref   
               [000003] --C-G-------              \--*  CALL      ref    System.String.Concat
               [000001] ------------ arg0            +--*  LCL_VAR   ref    V00 arg0         
               [000002] ------------ arg1            \--*  LCL_VAR   ref    V01 arg1         
fgMorphTailCall (before):
               [000003] --CXG-------              *  CALL      ref    System.String.Concat
               [000001] ------------ arg0         +--*  LCL_VAR   ref    V00 arg0         
               [000002] ------------ arg1         \--*  LCL_VAR   ref    V01 arg1         
fgMorphTailCall (after):
               [000003] --CXG-------              *  CALL      ref    System.String.Concat
               [000001] ------------ arg0         +--*  LCL_VAR   ref    V00 arg0         
               [000002] ------------ arg1         +--*  LCL_VAR   ref    V01 arg1         
               [000008] ------------ arg2         +--*  CNS_INT   int    0
               [000010] ------------ arg3         +--*  CNS_INT   int    9
               [000012] ------------ arg4         +--*  CNS_INT   int    8
               [000014] ------------ arg5         \--*  CNS_INT   int    7

GTF_CALL_M_TAILCALL bit set for call [000003]
New Basic Block BB02 [0002] created.
New Basic Block BB03 [0003] created.

Removing statement [000007] in BB01 as useless:
               [000007] ------------              *  STMT      void  (IL 0x000...0x004)
               [000003] --CXG-------              \--*  CALL      void   System.String.Concat
               [000001] ------------ arg0            +--*  LCL_VAR   ref    V00 arg0         
               [000002] ------------ arg1            +--*  LCL_VAR   ref    V01 arg1         
               [000008] ------------ arg2            +--*  CNS_INT   int    0
               [000010] ------------ arg3            +--*  CNS_INT   int    9
               [000012] ------------ arg4            +--*  CNS_INT   int    8
               [000014] ------------ arg5            \--*  CNS_INT   int    7

BB01 becomes empty
*** creating inlined GC Poll in top block BB01
               [000023] ------------              *  STMT      void  (IL   ???...  ???)
               [000022] ------------              \--*  JTRUE     void  
               [000020] ------------                 |  /--*  CNS_INT   int    0
               [000021] J------N----                 \--*  EQ        int   
               [000019] V-----------                    \--*  IND       int   
               [000018] ------------                       \--*  CNS_INT(h) int    0xF7AE7098 ptr

 poll block is BB02
               [000017] ------------              *  STMT      void  (IL   ???...  ???)
               [000016] --C-G-------              \--*  CALL help void   HELPER.CORINFO_HELP_POLL_GC

 bottom block is BB03
               [000007] ------------              *  STMT      void  (IL 0x000...0x004)
               [000003] --CXG-------              \--*  CALL      void   System.String.Concat
               [000001] ------------ arg0            +--*  LCL_VAR   ref    V00 arg0         
               [000002] ------------ arg1            +--*  LCL_VAR   ref    V01 arg1         
               [000008] ------------ arg2            +--*  CNS_INT   int    0
               [000010] ------------ arg3            +--*  CNS_INT   int    9
               [000012] ------------ arg4            +--*  CNS_INT   int    8
               [000014] ------------ arg5            \--*  CNS_INT   int    7


fgMorphTree BB01, stmt 1 (after)
               [000003] --CXG-------              *  CALL      void   System.String.Concat
               [000001] ------------ arg0         +--*  LCL_VAR   ref    V00 arg0         
               [000002] ------------ arg1         +--*  LCL_VAR   ref    V01 arg1         
               [000008] ------------ arg2         +--*  CNS_INT   int    0
               [000010] ------------ arg3         +--*  CNS_INT   int    9
               [000012] ------------ arg4         +--*  CNS_INT   int    8
               [000014] ------------ arg5         \--*  CNS_INT   int    7

Morphing BB02 of 'DynamicClass:MyMethod(ref,ref):ref'

fgMorphTree BB02, stmt 2 (before)
               [000016] --C-G-------              *  CALL help void   HELPER.CORINFO_HELP_POLL_GC
Initializing arg info for 16.CALL:

Morphing args for 16.CALL:


Morphing BB03 of 'DynamicClass:MyMethod(ref,ref):ref'

fgMorphTree BB03, stmt 3 (before)
               [000003] --CXG-------              *  CALL      void   System.String.Concat
               [000001] ------------ arg0         +--*  LCL_VAR   ref    V00 arg0         
               [000002] ------------ arg1         +--*  LCL_VAR   ref    V01 arg1         
               [000008] ------------ arg2         +--*  CNS_INT   int    0
               [000010] ------------ arg3         +--*  CNS_INT   int    9
               [000012] ------------ arg4         +--*  CNS_INT   int    8
               [000014] ------------ arg5         \--*  CNS_INT   int    7
Initializing arg info for 3.CALL:

Assert failure(PID 20524 [0x0000502c], Thread: 20524 [0x502c]): Assertion failed 'NYI: Morphing Vararg call not yet implemented on non Windows targets.' in 'DynamicClass:MyMethod(ref,ref):ref' (IL size 10)

    File: /media/kbaladurin/data/dotnet/forked/coreclr-sec/src/jit/morph.cpp Line: 2629
    Image: /media/kbaladurin/data/dotnet/clr_overlay_x86/corerun

Aborted (core dumped)
```

`fgMorphTailCall` marks `3.CALL` as varargs on x86 and amd64 and compilation fails due to NYI in `fgInitArgInfo` (on amd64 `fgMorphTailCall` isn't called as fast tail-call optimization is used). I think we can temporary disable tail-call optimization for Linux/x86:
```diff
diff --git a/src/jit/morph.cpp b/src/jit/morph.cpp
index 5f675dd76b..ddd5288ca6 100644
--- a/src/jit/morph.cpp
+++ b/src/jit/morph.cpp
@@ -8227,6 +8227,11 @@ GenTree* Compiler::fgMorphCall(GenTreeCall* call)
                 }
             }
         }
+#elif defined(_TARGET_UNIX_)
+        if (!canFastTailCall && szFailReason == nullptr)
+        {
+            szFailReason = "Morphing Vararg call that needed for tailcall optimization on non Windows targets is not yet implemented.";
+        }
 #endif // !_TARGET_X86_
 
         if (szFailReason != nullptr)
```

Thank you!

**Comment by kbaladurin** [comment]
@janvorli @jkotas @BruceForstall PTAL
cc @alpencolt

**Comment by janvorli** [comment]
cc: @dotnet/jit-contrib

**Comment by jashook** [comment]
We do not support fast tail calls on windows x86. It should be disabled for Linux x86 as well.

**Comment by BruceForstall** [comment]
@jashook Fast tailcall is already disabled for Linux/x86.

@kbaladurin Even if you disable (all) tailcalls, don't you still have a varargs call that needs to get morphed? Which would cause the same NYI? Why doesn't the NYI get hit with your change?

**Comment by jashook** [comment]
@BruceForstall this from the repro that is above, this looks like an explicit tail call. More interestingly it looks like morphTailCall is morphing the call to varargs. See: https://github.com/dotnet/coreclr/blob/master/src/jit/morph.cpp#L7501.

**Comment by jashook** [comment]
I am checking to see if this is reproducible on x64, and if not why x86 only catches this. It seems like a corner case, but it could affect arm64 as well.

**Comment by jashook** [comment]
This does not affect x64 because we do not support explicit tail calls on x64 unix. That being said, it has surfaced problems in fgMorphTailCall. In the future we will need to:

1. Understand why we are treating explicit tail calls as vararg methods
2. Permitted we do not break backcompat, hopefully stop doing number 1.

I have a change which should fix this for unix x86, seeing that it has been already investigated why not.

**Comment by jkotas** [comment]
> don't you still have a varargs call that needs to get morphed? 

varargs are not supported on Unix.

> Understand why we are treating explicit tail calls as vararg methods

It is because of `JIT_TailCall` helper is vararg method.

One way to fix this is to implement the portable slow tailcall design described in https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/tailcalls-with-helpers.md

**Comment by kbaladurin** [comment]
@BruceForstall varargs methods cause `System.InvalidProgramException` on Unix platform:
```
Unhandled Exception: System.InvalidProgramException: Vararg calling convention not supported.
   at vararg.Program.Run()
   at vararg.Program.Main(String[] args) in /home/kbaladurin/dotnet/examples/vararg/Program.cs:line 18
```
