### ISSUE TITLE
[x64] System.InvalidOperationException : Cannot process request because the process has exited.

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25191]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190615.1/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FTestProcessorAffinity

**Failed tests:**
 System.Diagnostics.Tests.ProcessTests/TestProcessorAffinity 

**Log:**
```
System.InvalidOperationException : Cannot process request because the process (10611) has exited.
   at System.Diagnostics.Process.ThrowIfExited(Boolean refresh) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 343
   at System.Diagnostics.Process.EnsureState(State state) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 940
   at System.Diagnostics.Process.set_ProcessorAffinity(IntPtr value) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 536
   at System.Diagnostics.Tests.ProcessTests.TestProcessorAffinity() in /_/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 865
```

**Comment by CarolEidt** [comment]
I've been unable to reproduce this bug. It happens only in the debian9 run, and it doesn't always fail. It ran for 7 days June 12-18, but doesn't appear to have run since. It failed in the following configurations:
Checked-jitstress2_jitstressregs1 - 1 failure 6/15
Checked-jitstress2_jitstressregs2 - 1 failure 6/17
Checked-jitstress2_jitstressregs8 - 3 failures 6/14, 15, 17
Checked-jitstress2_jitstressregs0x10 - 2 failures 6/14 out of 14 runs (2 runs each day; not sure why)
Checked-jitstress2_jitstressregs0x80 - 1 failure 6/15
Checked-jitstress2_jitstressregs0x1000 - 1 failure 6/17

I've built and run in a debian container with multiple copies running without hitting the failure (more than about 20 concurrent runs seems to bring down the container).

Oddly, it doesn't seem to have run on debian-9 since the 18th. @BruceForstall do you know why that might be the case?

**Comment by CarolEidt** [comment]
I am wondering whether this is a fundamental weakness of this test. AFAICT it creates a process with a fixed sleep time, and then tries to set process affinity. In a stress run, it is reasonable to expect that things will execute more slowly, hence risk the process exiting before the test tries to set its affinity.
@ViktorHofer @krwq @stephentoub as people who've touched this file in the not-too-distant past, can you comment or direct me?

**Comment by BruceForstall** [comment]
> Oddly, it doesn't seem to have run on debian-9 since the 18th. @BruceForstall do you know why that might be the case?

It's because of https://github.com/dotnet/coreclr/pull/25235. We were running on far too many OS variations, which was leading to machine capacity issues. And it was believed (at least by me) that the additional OS variations were not providing additional value.

**Comment by CarolEidt** [comment]
ping @ViktorHofer @krwq @stephentoub
Can you comment on my interpretation of this test - i.e. that there's not a strong guarantee that the process will still exist at the time the test attempts to set its affinity?

**Comment by stephentoub** [comment]
@CarolEidt, you're correct, the test is flaky if it's possible that it takes more than 30s from the time the process is created until the time ProcessorAffinity is accessed.
https://github.com/dotnet/corefx/blob/30ca4113ed07fc78060a0c9d3f95eee4fe8f8ee3/src/System.Diagnostics.Process/tests/ProcessTests.cs#L865-L877
We really shouldn't be using a timeout in this situation at all; the Process should be allowed to stay up until it's killed by the test.  In practice, we need a timeout in case this parent process is killed, in which case we don't want the child process to live on forever.  But we could certainly make the timeout much longer (at least minutes) to account for stress scenarios.

**Comment by CarolEidt** [comment]
@stephentoub - thanks!
It's pretty hard to imagine that it would take more than 30s, but I've seen weirder things happen in CI - it seems that those systems are often pretty heavily loaded.
I'm going to move this bug to corefx, with notes that it's not readily reproducible.
