### ISSUE TITLE
Test failed: System.Net.WebSockets.Client.Tests.ConnectTest/ConnectAsync_NonStandardRequestHeaders_HeadersAddedWithoutValidation 

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25241]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190617.1/workItem/System.Net.WebSockets.Client.Tests/analysis/xunit/System.Net.WebSockets.Client.Tests.ConnectTest~2FConnectAsync_NonStandardRequestHeaders_HeadersAddedWithoutValidation

**Failed tests:**
System.Net.WebSockets.Client.Tests.ConnectTest/ConnectAsync_NonStandardRequestHeaders_HeadersAddedWithoutValidation

**Log:**
```
System.Threading.Tasks.TaskCanceledException : A task was canceled.

   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 83
   at System.Threading.Tasks.TaskTimeoutExtensions.WhenAllOrAnyFailed(Task[] tasks) in /_/src/Common/tests/System/Threading/Tasks/TaskTimeoutExtensions.cs:line 111
   at System.Net.Test.Common.LoopbackServer.<>c__DisplayClass11_0.<<CreateClientAndServerAsync>b__0>d.MoveNext() in /_/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Test.Common.LoopbackServer.CreateServerAsync(Func`2 funcAsync, Options options) in /_/src/Common/tests/System/Net/Http/LoopbackServer.cs:line 66
   at System.Net.WebSockets.Client.Tests.ConnectTest.ConnectAsync_NonStandardRequestHeaders_HeadersAddedWithoutValidation() in /_/src/System.Net.WebSockets.Client/tests/ConnectTest.cs:line 237
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by BruceForstall** [comment]
@wfurt

**Comment by jeffschwMSFT** [comment]
I just ran this test in a loop against Linux X64 with a Dbg build of master tip with COMPlus_JitStress=1 set and it did not repro.
