### ISSUE TITLE
Test Failure: Exit code was 127 but it should have been 42

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25467]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190626.1/workItem/System.Net.Http.Unit.Tests/analysis/xunit/System.Net.Http.Tests.HttpEnvironmentProxyTest~2FHttpProxy_EnvironmentProxy_Loaded

**Log:**
```
Exit code was 127 but it should have been 42
Expected: True
Actual:   False

at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose(Boolean disposing) in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 163
   at Microsoft.DotNet.RemoteExecutor.RemoteInvokeHandle.Dispose() in /_/src/Microsoft.DotNet.RemoteExecutor/src/Microsoft.DotNet.RemoteExecutor/RemoteInvokeHandle.cs:line 55
   at System.Net.Http.Tests.HttpEnvironmentProxyTest.HttpProxy_EnvironmentProxy_Loaded() in /_/src/System.Net.Http/tests/UnitTests/HttpEnvironmentProxyTest.cs:line 45
```

**Comment by BruceForstall** [comment]
This result is too old to be investigated. I'm closing this, in hopes it comes back in the new test infra if it's still a problem.
