### ISSUE TITLE
Test failed: System.Resources.Extensions.Tests.PreserializedResourceWriterTests

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25585]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190707.1/workItem/System.Resources.Extensions.Tests/analysis/xunit/System.Resources.Extensions.Tests.PreserializedResourceWriterTests~2FStreamResources

**Failed tests:**
System.Resources.Extensions.Tests.PreserializedResourceWriterTests

**Log:**
```
System.ArgumentException : Parameter is not valid.
   at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
   at System.Drawing.Bitmap..ctor(Image original, Int32 width, Int32 height)
   at System.Drawing.Icon.ToBitmap()
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.ResourceValueEquals(Object expected, Object actual) in /_/src/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 525
   at System.Resources.Extensions.Tests.PreserializedResourceWriterTests.StreamResources() in /_/src/System.Resources.Extensions/tests/BinaryResourceWriterUnitTest.cs:line 460
```

**Comment by BruceForstall** [comment]
JitStressRegs=0x80
