### ISSUE TITLE
System.InvalidOperationException : Cannot process request because the process has exited

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25689]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190712.1/workItem/System.Diagnostics.Process.Tests/analysis/xunit/System.Diagnostics.Tests.ProcessTests~2FTestProcessorAffinity

**Log:**
```
System.InvalidOperationException : Cannot process request because the process (491) has exited.
   at System.Diagnostics.Process.ThrowIfExited(Boolean refresh) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Unix.cs:line 343
   at System.Diagnostics.Process.EnsureState(State state) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 967
   at System.Diagnostics.Process.set_ProcessorAffinityCore(IntPtr value) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.Linux.cs:line 191
   at System.Diagnostics.Process.set_ProcessorAffinity(IntPtr value) in /_/src/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 533
   at System.Diagnostics.Tests.ProcessTests.TestProcessorAffinity() in /_/src/System.Diagnostics.Process/tests/ProcessTests.cs:line 875
```

**Comment by stephentoub** [comment]
Is this running with the latest code in corefx, or is this using a snapshot copy of the tests?

**Comment by BruceForstall** [comment]
@stephentoub It runs with the latest snapshot published by the corefx official build. In this case, it was parsing https://dotnetfeed.blob.core.windows.net/dotnet-core/corefx-tests/4.6.0-preview8.19360.10/Linux.arm/netcoreapp/corefx-test-assets.xml.

Subsequent runs succeeded, so I'll close this.
