### ISSUE TITLE
Test failed with System.AggregateException

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25714]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190714.1/workItem/System.Drawing.Primitives.Tests/analysis/xunit/System.Drawing.Primitives.Tests.ColorTests~2FUserPreferenceChangingEventTest

**Log:**
```
System.AggregateException : One or more errors occurred. (Assert.Equal() Failure
Expected: -10496
Actual:   -5526613) (Assert.Equal() Failure
Expected: -10496
Actual:   -5526613) (Assert.Equal() Failure
Expected: -10496
Actual:   -5526613) (Assert.Equal() Failure
Expected: -10496
Actual:   -5526613) (Assert.Equal() Failure
Expected: -10496
Actual:   -5526613)
---- Assert.Equal() Failure
Expected: -10496
Actual:   -5526613
---- Assert.Equal() Failure
Expected: -10496
Actual:   -5526613
---- Assert.Equal() Failure
Expected: -10496
Actual:   -5526613
---- Assert.Equal() Failure
Expected: -10496
Actual:   -5526613
---- Assert.Equal() Failure
Expected: -10496
Actual:   -5526613

   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 45
   at System.Drawing.Primitives.Tests.ColorTests.UserPreferenceChangingEventTest() in /_/src/System.Drawing.Primitives/tests/ColorTests.cs:line 516
----- Inner Stack Trace #1 (Xunit.Sdk.EqualException) -----
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #2 (Xunit.Sdk.EqualException) -----
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #3 (Xunit.Sdk.EqualException) -----
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #4 (Xunit.Sdk.EqualException) -----
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
----- Inner Stack Trace #5 (Xunit.Sdk.EqualException) -----
   at System.RetryHelper.Execute(Action test, Int32 maxAttempts, Func`2 backoffFunc) in /_/src/Common/tests/CoreFx.Private.TestUtilities/System/RetryHelper.cs:line 37
```

**Comment by BruceForstall** [comment]
Failed in JitStress=1 run.

Only one failure in Kusto.

**Comment by danmosemsft** [comment]
Does jitstress=1 cause a significant slowdown?

**Comment by BruceForstall** [comment]
Some slowdown; roughly 25% on this test assembly, by my unscientific measurements.

I ran more than a dozen times, and didn't see it fail. (Windows x64, both with and without JitStress=1, always with `COMPlus_TieredCompilation=0`)

@danmosemsft Do you want to investigate it more? If not, I'd probably close it and wait to see if it comes back.

**Comment by danmosemsft** [comment]
Let's do that
