### ISSUE TITLE
Debugger refuses to attach to 5.0 builds

### ISSUE THREAD

**Issue by sdmaclea** [dotnet/coreclr#25758]
Apparently rebranding to 5.0 has caused the debugger to assert
```
 Assertion Failed
 Unsupported version of mscorlib
    at Ilrun.DefaultHost.GetClrVersionFromSystemAssembly()
    at Ilrun.DefaultHost.get_ClrVersionImpl()
    at Ilrun.ClrVersionUtility.GetClrVersion(IHost host)
    at Ilrun.DefaultSlotFactory.get_ClrVersion()
    at Ilrun.DefaultSlotFactory.GetSlotForPrimitive(PrimitiveValue pv)
    at Ilrun.DefaultSlotFactory.GetSlotForHostObject(Object value)
    at Ilrun.Utility.GetSlotForObject(ISlotFactory factory, Object value)
    at Ilrun.Utility.GetSlotForInteger(ISlotFactory factory, Int32 value)
    at Ilrun.CommonSlotConst..ctor(IHost host)
    at Ilrun.DefaultHost.get_CommonConst()
    at Ilrun.VirtualMachine2..ctor(IHost host, Int32 maxStackDepth)
    at Ilrun.VirtualMachine2..ctor(IHost host)
    at Ilrun.DefaultHost.CreateVM()
    at Microsoft.VisualStudio.VIL.DebuggerHost.LocalContext.CreateVM()
    at Microsoft.VisualStudio.VIL.VisualStudioHost.LocalContextWrapper.CreateVM()
    at Microsoft.VisualStudio.VIL.DebuggerHost.LocalContext.get_VM()
    at Microsoft.VisualStudio.VIL.VisualStudioHost.VilEvaluationServices.InterpretInspectionQuery(DkmInspectionSession inspectionSession, DkmWorkList workList, DkmEvaluationFlags evalFlags, DkmFuncEvalFlags funcEvalFlags, UInt32 timeout, DkmStackWalkFrame frame, Assembly queryAssembly, String expression, String queryClassName, String queryMethodName, DkmClrCompilationResultFlags queryCompilationFlags, DkmEvaluationResultCategory resultCategory, DkmEvaluationResultAccessType accessType, DkmEvaluationResultStorageType storageType, DkmEvaluationResultTypeModifierFlags typeModifierFlags, VilEvaluationResult targetValue, Type targetType, InspectionQueryUserContext inspectionQueryUserContext, String& error, MethodInfo& queryMethod)
    at VSDebugEngine.ClrInspector.VilHelper.ExecuteQueryInternal(Assembly queryAssembly, String queryTypeName, String queryMethodName, DkmClrCompilationResultFlags queryCompilationFlags, DkmEvaluationResultCategory resultCategory, DkmEvaluationResultAccessType accessType, DkmEvaluationResultStorageType storageType, DkmEvaluationResultTypeModifierFlags typeModifierFlags, DkmClrCustomTypeInfo customTypeInfo, DkmInspectionContext inspectionContext, DkmStackWalkFrame frame, String resultName, String resultFullName, ReadOnlyCollection`1 additionalFormatSpecifiers, DkmWorkList workList, EvaluationResultContinuation continuation)
    at VSDebugEngine.ClrInspector.VilHelper.ExecuteInspectionQuery(DkmCompiledClrInspectionQuery query, DkmInspectionContext inspectionContext, DkmStackWalkFrame frame, String expressionName, DkmWorkList workList, EvaluationResultContinuation continuation)
    at VSDebugEngine.ClrInspector.EntryPoint.Microsoft.VisualStudio.Debugger.ComponentInterfaces.IDkmClrInspectionQueryProcessor.Execute(DkmCompiledClrInspectionQuery query, DkmWorkList workList, DkmInspectionContext inspectionContext, DkmILContext iLContext, String expressionName, DkmCompletionRoutine`1 completionRoutine)
    at Microsoft.VisualStudio.Debugger.EntryPoint.IDkmClrInspectionQueryProcessor_Execute(IntPtr pvClassInfo, IntPtr CompiledClrInspectionQuery, IntPtr WorkList, IntPtr InspectionContext, IntPtr ILContext, IntPtr ExpressionName, IntPtr CompletionRoutine)
```

**Comment by sdmaclea** [comment]
@gregg-miskelly Do we need new vsdb builds for 5.0?

**Comment by gregg-miskelly** [comment]
This is the first I have seen of this issue. I can fix it fairly easily.

Are you asking for a particular drop of something? (ex: glass, vsdbg, VS, etc)

**Comment by sdmaclea** [comment]
I am seeing when testing vsdbg on arm64.  (the only place I am testing at the moment)

**Comment by gregg-miskelly** [comment]
Got it. We can put in a fix and Andrew can give you a new vsdbg with that fix.

CC @WardenGnaw

**Comment by gregg-miskelly** [comment]
Are there installable builds yet that with this change? Pulling the latest from the master channel using the dotnet install script comes back with a 4.7 version number.

**Comment by sdmaclea** [comment]
I'm not sure if there are official 5.9 builds yet.  Rebranding may have broken official builds.  This patch made the version change 0cc81b60eb18

**Comment by jkoritzinsky** [comment]
There are official builds for the runtime in dotnet/core-setup's master channel. The rest of the product hasn't snapped yet so there aren't 5.0 builds of the SDK.

**Comment by sdmaclea** [comment]
@WardenGnaw Thanks for the fixed build.
