### ISSUE TITLE
Out Of Memory Exception in .NET Core 3.0 preview 5

### ISSUE THREAD

**Issue by SilentCC** [dotnet/coreclr#25767]
Since I update my application to .NET Core 3.0 preview 5 in container scenario, the OutOfMemory exceptions come out sometimes.

Production Environments:

*   **production cluster**:  docker swarm
*   **docker container cpu limit** :1.5
*   **docker container memory limit**: 2G
*   **docker container duplicates** : 2
*   **PV** : about  60000 per day
*   **Application** : .NET Core MVC Web
*   **GC type** : Server GC
*   **.Net version** : .NET Core 3.0 preview 5

Previous version is .NET Core 2.2 , and it worked fine all the time until it was updated to .NET Core 3.0 a few days ago.

Last night, It threw lots of OutOfMemory exceptions and restarted by docker finally.I think its memory exceeded docker memory limit. 

Here is error logs, note that OutOfMemory exception may occurs on many different places .

```
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
```

```
 "Message": "Exception of type 'System.OutOfMemoryException' was thrown.",
  "Source": "System.Private.CoreLib",
  "StackTraceString": "   
     at System.Collections.Generic.Dictionary`2.Initialize(Int32 capacity)\n   at System.Collections.Generic.Dictionary`2..ctor(Int32 capacity, IEqualityComparer`1 comparer)\n 
     at System.Linq.Expressions.Compiler.CompilerScope..ctor(Object node, Boolean isMethod)\n   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)\n   
     at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)\n   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)\n  
```

```
 "Message": "Exception of type 'System.OutOfMemoryException' was thrown.",
  "Source": "System.Private.CoreLib",
  "StackTraceString": "   
       at System.GC.AllocateNewArray(IntPtr typeHandle, Int32 length, Boolean zeroingOptional)\n   at System.GC.AllocateUninitializedArray[T](Int32 length)\n   
       at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int3  2 minimumLength)\n  
       at Microsoft.AspNetCore.Http.Extensions.StreamCopyOperation.CopyToAsync(Stream source, Stream destination, Nullable`1 count, Int32 bufferSize, CancellationToken cancel)\n   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.SendAsync()\n   
       at Microsoft.AspNetCore.StaticFiles.StaticFileContext.ServeStaticFile(HttpContext context, RequestDelegate next)\n   
       at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)",
```

```
Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.Linq.Expressions.Compiler.CompilerScope.SetParent(LambdaCompiler lc, CompilerScope parent)
   at System.Linq.Expressions.Compiler.CompilerScope.Enter(LambdaCompiler lc, CompilerScope parent)
   at System.Linq.Expressions.Compiler.LambdaCompiler.EmitLambdaBody(CompilerScope parent, Boolean inlined, CompilationFlags flags)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateFactory(Type instanceType, Type[] argumentTypes)
   at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
   at Microsoft.Extensions.Http.DefaultTypedHttpClientFactory`1.CreateClient(HttpClient httpClient)
   at Microsoft.Extensions.DependencyInjection.HttpClientBuilderExtensions.<>c__DisplayClass10_0`2.<AddTypedClient>b__0(IServiceProvider s)
   at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method(Closure , IServiceProvider , Object[] )
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware 
```

I suppose that  GC may be affected by GCHeapHardLimit in .NET Core 3.0.
Any one can help me? Thank you very much!

**Comment by SilentCC** [comment]
@Maoni0

**Comment by Maoni0** [comment]
@andy-ms could you take a look please? 

I still don't understand the issue description. did you get OOM in 2.2 or not? it's unclear from this
>Previous version is .NET Core 2.2 , and it worked fine all the time.
>It threw lots of OutOfMemory exceptions and restarted by docker finally last night.I think its memory exceeded docker memory limit.

**Comment by SilentCC** [comment]
@Maoni0 Sorry,I don't explain it clearly. I didn't get OOM in 2.2. I have fixed my description.

**Comment by Maoni0** [comment]
there is a change that went in with the hardlimit work which was we take 75% of the container memory limit so it could be that you were using more than 75%. the way to verify this is if you set COMPlus_GCHeapLimit to the container's memory limit, and you no longer get OOMs, you could do this. if you still get OOMs, it means most likely 3.0 is simply using more memory. 3.0 has tons of changes other than what's in the GC.

**Comment by SilentCC** [comment]
@Maoni0 Thanks! But  I don't know  where and how to set COMPlus_GCHeapLimit.I never used COMPlus_GCHeapLimit before.

**Comment by stephentoub** [comment]
cc: @richlander

**Comment by andy-ms** [comment]
@SilentCC That's an the name of an environment variable. The value would be bytes in hexadecimal without the `0x`. For a 2GB limit that would be `80000000`. Also, the name is `COMPlus_GCHeapHardLimit`.

In cmd you could write `set COMPlus_GCHeapHardLimit=80000000`, in powershell it would be `$env:COMPlus_GCHeapHardLimit=80000000`.

**Comment by SilentCC** [comment]
@andy-ms Thanks a lot!

**Comment by SilentCC** [comment]
I think this issue should be closed.I met this problem seldom since set COMPlus_GCHeapHardLimit=8000000
