### ISSUE TITLE
[EventListener] Include thread ID

### ISSUE THREAD

**Issue by kouvel** [dotnet/coreclr#25824]
`EventWrittenEventArgs` doesn't appear to provide information about which thread fired the event. It would be useful to have that information to be able to associate paired events such as `Start`/`Stop` that may be fired from multiple threads concurrently.

**Comment by stephentoub** [comment]
Isn't the event fired synchronously, in which case you can just look at Environment.CurrentManagedThreadId?

**Comment by kouvel** [comment]
The callback is happening on a thread pool thread and it's a different thread from the thread that fired the event (main thread in this case).

```
   at System.Environment.get_StackTrace()
   at TieringInProcEventListener.ClrEventListener.OnEventWritten(EventWrittenEventArgs eventData) in D:\Test\source\test\Program.cs:line 65
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, Guid* childActivityID, EventWrittenEventArgs eventCallbackArgs)
   at System.Diagnostics.Tracing.EventPipeEventDispatcher.DispatchEventsToEventListeners()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.<>c.<.cctor>b__10_0(Object s)
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by stephentoub** [comment]
Ah, EventPipe is doing the offloading.

**Comment by kouvel** [comment]
Updated description to specify the kind of thread ID
