### ISSUE TITLE
System.NullReferenceException : Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#25959]
**Job:**
https://mc.dot.net/#/user/coreclr-corefx-jitstress2-jitstressregs/ci~2Fdotnet~2Fcoreclr~2Frefs~2Fheads~2Fmaster/test~2Ffunctional~2Fcorefx~2F/20190731.1/workItem/System.Runtime.Loader.Tests/analysis/xunit/System.Runtime.Loader.Tests.ContextualReflectionTest~2FTypeGetTypeStringMultiLoadedAssemblyIsolated

**Log:**
```
System.NullReferenceException : Object reference not set to an instance of an object.
```

**Stack Trace:**
```
   at System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeTestCase(Func`1 func, Assembly nullExpected, Assembly defaultExpected, Assembly isolatedExpected) in /_/src/System.Runtime.Loader/tests/ContextualReflection.cs:line 661
   at System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeStringMultiLoadedAssemblyIsolated() in /_/src/System.Runtime.Loader/tests/ContextualReflection.cs:line 810
```

**Comment by BruceForstall** [comment]
Another case that fails in many stress modes. Another possible corefx/coreclr mismatch? @stephentoub @danmosemsft

**Comment by danmosemsft** [comment]
Git log says these tests are @sdmaclea

**Comment by sdmaclea** [comment]
If I remember correctly these tests were disabled in corefx when they were broken by an arcade infrastructure change which removed the ability to reference assemblies but not deploy them.  The tests assume certain assemblies are not in the root directory and therefore not in the TPA list.
