### ISSUE TITLE
Assert failure: Consistency check failed: hit privileged instruction!

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#26123]
**Job:**
https://helix.dot.net/api/2019-06-17/jobs/946121e7-6f9d-4fd0-bf95-30b2c5824424/workitems/Loader.classloader/console

** Failed tests:**
Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh
Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh
Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.sh

**Log:**
```
Assert failure(PID 1037 [0x0000040d], Thread: 1037 [0x040d]): Consistency check failed: hit privileged instruction!FAILED: !ExecutionManager::IsManagedCode(GetIP(pContext))
          File: /__w/5/s/src/vm/excep.cpp Line: 6615
          Image: /root/helix/work/correlation/corerun
      
      /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh: line 252:  1037 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun constrainedcall.exe ''
      Constrained calls that require runtime lookup are OK
      Runtime does not support lookups with runtime determined boxing
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/8/s/bin/tests/Linux.arm64.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs(166495,0): at Loader_classloader._DefaultInterfaceMethods_constrainedcall_constrainedcall_constrainedcall_._DefaultInterfaceMethods_constrainedcall_constrainedcall_constrainedcall_sh()
      Output:
        
        Assert failure(PID 1037 [0x0000040d], Thread: 1037 [0x040d]): Consistency check failed: hit privileged instruction!FAILED: !ExecutionManager::IsManagedCode(GetIP(pContext))
            File: /__w/5/s/src/vm/excep.cpp Line: 6615
            Image: /root/helix/work/correlation/corerun
        
        /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh: line 252:  1037 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun constrainedcall.exe ''
        Constrained calls that require runtime lookup are OK
        Runtime does not support lookups with runtime determined boxing
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh
      
      Assert failure(PID 1491 [0x000005d3], Thread: 1491 [0x05d3]): Consistency check failed: hit privileged instruction!FAILED: !ExecutionManager::IsManagedCode(GetIP(pContext))
          File: /__w/5/s/src/vm/excep.cpp Line: 6615
          Image: /root/helix/work/correlation/corerun
      
      /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh: line 252:  1491 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.output.txt
      Raw output:
      BEGIN EXECUTION
      /root/helix/work/correlation/corerun valuetypes.exe ''
      Calling IFoo.Foo on FooBarStruct
      Expected: 100
      Actual: 134
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/root/helix/work/correlation
      > /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/8/s/bin/tests/Linux.arm64.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs(167368,0): at Loader_classloader._DefaultInterfaceMethods_valuetypes_valuetypes_valuetypes_._DefaultInterfaceMethods_valuetypes_valuetypes_valuetypes_sh()
      Output:
        
        Assert failure(PID 1491 [0x000005d3], Thread: 1491 [0x05d3]): Consistency check failed: hit privileged instruction!FAILED: !ExecutionManager::IsManagedCode(GetIP(pContext))
            File: /__w/5/s/src/vm/excep.cpp Line: 6615
            Image: /root/helix/work/correlation/corerun
        
        /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh: line 252:  1491 Aborted                 $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /root/helix/work/workitem/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.output.txt
        Raw output:
        BEGIN EXECUTION
        /root/helix/work/correlation/corerun valuetypes.exe ''
        Calling IFoo.Foo on FooBarStruct
        Expected: 100
        Actual: 134
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/root/helix/work/correlation
        > /root/helix/work/workitem/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh
```

**Comment by BruceForstall** [comment]
```
export COMPlus_TieredCompilation=0
export COMPlus_GCStress=0xC
export COMPlus_ReadyToRun=0
export COMPlus_ZapDisable=1
```

**Comment by BruceForstall** [comment]
@MichalStrehovsky

**Comment by MichalStrehovsky** [comment]
Going with the theory that #25770 is going to fix this, as usual...

**Comment by kouvel** [comment]
https://github.com/dotnet/coreclr/pull/25770 is merged, let's see if it happens again
