### ISSUE TITLE
Exception caught when calling IFoo.Foo

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#26124]
**Job:**
https://helix.dot.net/api/2019-06-17/jobs/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/workitems/Loader.classloader/console

**Failed tests:**
Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh
Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.sh
Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh

**Log:**
```
Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh [FAIL]
      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh: line 252:  6617 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.output.txt
      Raw output:
      BEGIN EXECUTION
      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload/corerun valuetypes.exe ''
      Calling IFoo.Foo on FooBarStruct
      Expected: 100
      Actual: 139
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload
      > /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/10/s/bin/tests/Linux.x64.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs(167368,0): at Loader_classloader._DefaultInterfaceMethods_valuetypes_valuetypes_valuetypes_._DefaultInterfaceMethods_valuetypes_valuetypes_valuetypes_sh()
      Output:
        /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh: line 252:  6617 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.output.txt
        Raw output:
        BEGIN EXECUTION
        /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload/corerun valuetypes.exe ''
        Calling IFoo.Foo on FooBarStruct
        Expected: 100
        Actual: 139
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload
        > /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/valuetypes/valuetypes/valuetypes.sh
    Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.sh [FAIL]
      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.sh: line 252:  7285 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.output.txt
      Raw output:
      BEGIN EXECUTION
      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload/corerun diamondshape_d.exe ''
      Calling IFoo.Foo on Foo - expecting exception.
      Exception caught: System.Runtime.AmbiguousImplementationException: Could not call method 'IFoo.Foo(Int32)' on interface 'IFoo' with type 'FooClass' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
         at IFoo.Foo(Int32 a)
         at Program.Negative()
      Calling I1.Func on I47Class - expecting exception
      Exception caught: System.Runtime.AmbiguousImplementationException: Could not call method 'I1.Func(Int32)' on interface 'I1' with type 'I47Class' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
         at I1.Func(Int32 a)
         at Program.Negative()
      Calling GI1<T>.Func on GI23Class<S> - expecting exception
      Exception caught: System.Runtime.AmbiguousImplementationException: Could not call method 'GI1`1[S].Func(System.Type[] ByRef)' on interface 'GI1`1[System.Object]' with type 'GI23Class`1[System.Object]' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
         at Program.Negative()
      Calling I1.Func on I4Class - expecting I4.Func
      Expected: 100
      Actual: 139
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload
      > /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/10/s/bin/tests/Linux.x64.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs(166592,0): at Loader_classloader._DefaultInterfaceMethods_diamondape_diamondape_d_diamondape_d_._DefaultInterfaceMethods_diamondshape_diamondshape_d_diamondshape_d_sh()
      Output:
        /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.sh: line 252:  7285 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.output.txt
        Raw output:
        BEGIN EXECUTION
        /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload/corerun diamondshape_d.exe ''
        Calling IFoo.Foo on Foo - expecting exception.
        Exception caught: System.Runtime.AmbiguousImplementationException: Could not call method 'IFoo.Foo(Int32)' on interface 'IFoo' with type 'FooClass' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
           at IFoo.Foo(Int32 a)
           at Program.Negative()
        Calling I1.Func on I47Class - expecting exception
        Exception caught: System.Runtime.AmbiguousImplementationException: Could not call method 'I1.Func(Int32)' on interface 'I1' with type 'I47Class' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
           at I1.Func(Int32 a)
           at Program.Negative()
        Calling GI1<T>.Func on GI23Class<S> - expecting exception
        Exception caught: System.Runtime.AmbiguousImplementationException: Could not call method 'GI1`1[S].Func(System.Type[] ByRef)' on interface 'GI1`1[System.Object]' with type 'GI23Class`1[System.Object]' from assembly 'diamondshape, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' because there are multiple incompatible interface methods overriding this method.
           at Program.Negative()
        Calling I1.Func on I4Class - expecting I4.Func
        Expected: 100
        Actual: 139
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload
        > /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/diamondshape/diamondshape_d/diamondshape_d.sh
    Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh [FAIL]
      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh: line 252:  8246 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
      
      Return code:      1
      Raw output file:      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.output.txt
      Raw output:
      BEGIN EXECUTION
      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload/corerun constrainedcall.exe ''
      Constrained calls that require runtime lookup are OK
      Runtime does not support lookups with runtime determined boxing
      Expected: 100
      Actual: 139
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=/home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload
      > /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh
      Expected: True
      Actual:   False
      Stack Trace:
        /__w/10/s/bin/tests/Linux.x64.Checked/TestWrappers/Loader.classloader/Loader.classloader.XUnitWrapper.cs(166495,0): at Loader_classloader._DefaultInterfaceMethods_constrainedcall_constrainedcall_constrainedcall_._DefaultInterfaceMethods_constrainedcall_constrainedcall_constrainedcall_sh()
      Output:
        /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh: line 252:  8246 Segmentation fault      (core dumped) $LAUNCHER $ExePath "${CLRTestExecutionArguments[@]}"
        
        Return code:      1
        Raw output file:      /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/Reports/Loader.classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.output.txt
        Raw output:
        BEGIN EXECUTION
        /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload/corerun constrainedcall.exe ''
        Constrained calls that require runtime lookup are OK
        Runtime does not support lookups with runtime determined boxing
        Expected: 100
        Actual: 139
        END EXECUTION - FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=/home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Payload
        > /home/helixbot/work/a6a3eb5b-d050-46e6-8915-88f1019f8ea0/Work/4cfab324-f28a-4fb3-91ca-4d77b1e5ef5f/Exec/Loader/classloader/DefaultInterfaceMethods/constrainedcall/constrainedcall/constrainedcall.sh
  Finished:    Loader.classloader.XUnitWrapper
```

**Comment by MichalStrehovsky** [comment]
Quite likely the same issue as #25690 and #25813. Let's see if this reproes after #25770 is merged. Cc @kouvel

**Comment by kouvel** [comment]
https://github.com/dotnet/coreclr/pull/25770 is merged, let's see if it happens again
