### ISSUE TITLE
Test failed: System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeStringMultiLoadedAssemblyIsolated

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#26121]
**Job:**
https://helix.dot.net/api/2019-06-17/jobs/d3a57903-5087-4324-bd04-fc9254c3bda5/workitems/System.Runtime.Loader.Tests/console

**Failed tests:**
System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeStringMultiLoadedAssemblyIsolated

**Log:**
```
System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeStringMultiLoadedAssemblyIsolated [FAIL]
      System.NullReferenceException : Object reference not set to an instance of an object.
      Stack Trace:
        /_/src/System.Runtime.Loader/tests/ContextualReflection.cs(661,0): at System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeTestCase(Func`1 func, Assembly nullExpected, Assembly defaultExpected, Assembly isolatedExpected)
        /_/src/System.Runtime.Loader/tests/ContextualReflection.cs(810,0): at System.Runtime.Loader.Tests.ContextualReflectionTest.TypeGetTypeStringMultiLoadedAssemblyIsolated()
  Finished:    System.Runtime.Loader.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Loader.Tests  Total: 134, Errors: 0, Failed: 1, Skipped: 0, Time: 8.284s
----- end Sun 08/11/2019  6:39:49.18 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment]
`JitStress=1`

**Comment by jeffschwMSFT** [comment]
I ran this in a loop on a check build of masters tip with JitStress=1 and did not see any failures.
