### ISSUE TITLE
Unable to build coreclr

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#26213]
CI is failing to build coreclr, and I'm unable to build it locally either.  Errors like:
```C#
d:\repos\coreclr>build.cmd -release -skiptests
BUILD: Starting Build at 10:41:33.72
BUILD: Detected Visual Studio 16.0 developer command prompt environment
BUILD: Commencing CoreCLR product build
BUILD: Checking prerequisites
BUILD: Number of processor cores 6
Unable to connect to the remote server
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 104.214.64.238:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
   at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
```
cc: @AaronRobinsonMSFT, @ViktorHofer, @dotnet/dnceng

**Comment by mmitche** [comment]
@stephentoub The dot.net website appears to be down.  We are waiting for @rowanmiller to investigate.

**Comment by markwilkie** [comment]
Things are back now.  https://github.com/dotnet/core-eng/issues/7463

**Comment by jashook** [comment]
This should no longer be reproducible. Ci is running.
