### ISSUE TITLE
Test failed: System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_ColorMatrixDefaultFlagType_Success

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#26308]
**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/9f2533c8-5903-447b-b099-3c861eb02547/workitems/System.Drawing.Common.Tests/console

**Failed tests:**
System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_ColorMatrixDefaultFlagType_Success

**Log:**
```
System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_ColorMatrixDefaultFlagType_Success(type: Bitmap) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=0, G=0, B=0]
      Actual:   Color [A=255, R=0, G=255, B=0]
      Stack Trace:
        /_/src/System.Drawing.Common/tests/Imaging/ImageAttributesTests.cs(195,0): at System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrix_ColorMatrixDefaultFlagType_Success(ColorAdjustType type)
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=255, G=255, B=0]
      Stack Trace:
        /_/src/System.Drawing.Common/tests/Imaging/ImageAttributesTests.cs(434,0): at System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrices_ColorMatrixGrayMatrixFlagsTypes_Success(ColorMatrixFlag flag, ColorAdjustType type, Color grayShade, Color expecedGrayShade)
    System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrices_ColorMatrixGrayMatrixFlagsTypes_Success(flag: Default, type: Bitmap, grayShade: Color [A=255, R=100, G=100, B=100], expecedGrayShade: Color [A=255, R=100, G=0, B=100]) [FAIL]
    System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrices_ColorMatrixGrayMatrixFlagsTypes_Success(flag: SkipGrays, type: Bitmap, grayShade: Color [A=255, R=100, G=100, B=100], expecedGrayShade: Color [A=255, R=100, G=100, B=100]) [FAIL]
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=255, G=255, B=0]
      Stack Trace:
        /_/src/System.Drawing.Common/tests/Imaging/ImageAttributesTests.cs(434,0): at System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrices_ColorMatrixGrayMatrixFlagsTypes_Success(ColorMatrixFlag flag, ColorAdjustType type, Color grayShade, Color expecedGrayShade)
      Assert.Equal() Failure
      Expected: Color [A=255, R=255, G=0, B=0]
      Actual:   Color [A=255, R=255, G=255, B=0]
      Stack Trace:
        /_/src/System.Drawing.Common/tests/Imaging/ImageAttributesTests.cs(434,0): at System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrices_ColorMatrixGrayMatrixFlagsTypes_Success(ColorMatrixFlag flag, ColorAdjustType type, Color grayShade, Color expecedGrayShade)
    System.Drawing.Imaging.Tests.ImageAttributesTests.SetColorMatrices_ColorMatrixGrayMatrixFlagsTypes_Success(flag: AltGrays, type: Bitmap, grayShade: Color [A=255, R=100, G=100, B=100], expecedGrayShade: Color [A=255, R=100, G=200, B=255]) [FAIL]
    System.Drawing.Imaging.Tests.EncoderParameterTests.Ctor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues: -1) [SKIP]
      backwards compatibility on 32 bit platforms may not throw
    System.Drawing.Imaging.Tests.EncoderParameterTests.Ctor_Encoder_NegativeNumberOfValues_Type_Value_OutOfMemoryException(numberOfValues: -2147483648) [SKIP]
      backwards compatibility on 32 bit platforms may not throw
    MonoTests.System.Drawing.GraphicsTest.Rotate [SKIP]
      Precision on float numbers

Assert failure(PID 22 [0x00000016], Thread: 43 [0x002b]): object->HasEmptySyncBlockInfo()
    File: /__w/6/s/src/vm/jithelpers.cpp Line: 2690
    Image: /root/helix/work/correlation/dotnet

./RunTests.sh: line 161:    22 Aborted                 "$RUNTIME_PATH/dotnet" exec --runtimeconfig System.Drawing.Common.Tests.runtimeconfig.json xunit.console.dll System.Drawing.Common.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonlinuxtests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
/root/helix/work/workitem
 exit code 134 
```

**Comment by BruceForstall** [comment]
I don't see failures in the current runs. I'm going to close this. Please re-open if it happens again.
