### ISSUE TITLE
System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#26367]
**Detail:**
https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-coreclr-refs-heads-master-f45d24b93b8645baa1/JIT.Regression/console.8fff52b5.log?sv=2018-03-28&sr=c&sig=R2IOEeUvPW6PDIVtPVuQhRo66C0zYtIJckCIPgyFL0A%3D&se=2019-09-04T14%3A23%3A49Z&sp=rl

**Failed tests:**
JIT\\Regression\\JitBlue\\GitHub_25468\\GitHub_25468\\GitHub_25468.cmd

**Log:**
```
JIT\Regression\JitBlue\GitHub_25468\GitHub_25468\GitHub_25468.cmd [FAIL]
      
      Return code:      1
      Raw output file:      C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Work\051fe643-e9da-4146-97d0-833c5589d0f8\Exec\JIT\Regression\Reports\JIT.Regression\JitBlue\GitHub_25468\GitHub_25468\GitHub_25468.output.txt
      Raw output:
      BEGIN EXECUTION
      call C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Payload\runincontext.cmd C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Work\051fe643-e9da-4146-97d0-833c5589d0f8\Exec\JIT\Regression\JitBlue\GitHub_25468\GitHub_25468\ GitHub_25468.dll 
      Serializing System.Drawing.Bitmap
        {110,100,73744,96,96}
      Deserializing System.Drawing.Bitmap
      FAILURE: Unload failed
      
      RunInContext FAIL! Exiting with code 213
      RunInContext FAIL! Exiting due to unhandled exception in the test: System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Thread, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
      File name: 'System.Threading.Thread, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
       ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
         at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
         at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
         at TestAssemblyLoadContext.Load(AssemblyName name) in /_/src/tools/runincontext/runincontext.cs:line 179
         at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
         at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
         at System.Drawing.SafeNativeMethods.Gdip.ClearThreadData()
         at System.Drawing.SafeNativeMethods.Gdip.Shutdown()
         at System.Drawing.SafeNativeMethods.Gdip.OnProcessExit(Object sender, EventArgs e)
         at System.EventHandler.Invoke(Object sender, EventArgs e)
         at System.AppContext.OnProcessExit()
      
      
      Expected: 100
      Actual: 213
      END EXECUTION - FAILED
      FAILED
      Test Harness Exitcode is : 1
      To run the test:
      > set CORE_ROOT=C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Payload
      > C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Work\051fe643-e9da-4146-97d0-833c5589d0f8\Exec\JIT\Regression\JitBlue\GitHub_25468\GitHub_25468\GitHub_25468.cmd
      Expected: True
      Actual:   False
      Stack Trace:
        F:\workspace.8\_work\1\s\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT.Regression\JIT.Regression.XUnitWrapper.cs(122748,0): at JIT_Regression._JitBlue_GitHub_25468_GitHub_25468_GitHub_25468_._JitBlue_GitHub_25468_GitHub_25468_GitHub_25468_cmd()
      Output:
        
        Return code:      1
        Raw output file:      C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Work\051fe643-e9da-4146-97d0-833c5589d0f8\Exec\JIT\Regression\Reports\JIT.Regression\JitBlue\GitHub_25468\GitHub_25468\GitHub_25468.output.txt
        Raw output:
        BEGIN EXECUTION
        call C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Payload\runincontext.cmd C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Work\051fe643-e9da-4146-97d0-833c5589d0f8\Exec\JIT\Regression\JitBlue\GitHub_25468\GitHub_25468\ GitHub_25468.dll 
        Serializing System.Drawing.Bitmap
          {110,100,73744,96,96}
        Deserializing System.Drawing.Bitmap
        FAILURE: Unload failed
        
        RunInContext FAIL! Exiting with code 213
        RunInContext FAIL! Exiting due to unhandled exception in the test: System.IO.FileLoadException: Could not load file or assembly 'System.Threading.Thread, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. An operation is not legal in the current state. (0x80131509 (COR_E_INVALIDOPERATION))
        File name: 'System.Threading.Thread, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
         ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
           at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
           at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
           at TestAssemblyLoadContext.Load(AssemblyName name) in /_/src/tools/runincontext/runincontext.cs:line 179
           at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
           at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
           at System.Drawing.SafeNativeMethods.Gdip.ClearThreadData()
           at System.Drawing.SafeNativeMethods.Gdip.Shutdown()
           at System.Drawing.SafeNativeMethods.Gdip.OnProcessExit(Object sender, EventArgs e)
           at System.EventHandler.Invoke(Object sender, EventArgs e)
           at System.AppContext.OnProcessExit()
        
        
        Expected: 100
        Actual: 213
        END EXECUTION - FAILED
        FAILED
        Test Harness Exitcode is : 1
        To run the test:
        > set CORE_ROOT=C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Payload
        > C:\dotnetbuild\work\f45d24b9-3b86-45ba-a105-8639bd52afeb\Work\051fe643-e9da-4146-97d0-833c5589d0f8\Exec\JIT\Regression\JitBlue\GitHub_25468\GitHub_25468\GitHub_25468.cmd
  Finished:    JIT.Regression.XUnitWrapper
```

**Comment by janvorli** [comment]
I'll take a look at the test. It is possible that it needs to be marked as incompatible with unloadability testing.

**Comment by janvorli** [comment]
I guess I understand what's going on:
* The unloading of the test assembly fails for some reason
* The runincontext tool reports that (RunInContext FAIL! Exiting with code 213)
* The runincontext tool starts to exit. Now since the unloading failed, the TestAssemblyLoadContext is still there with all the assemblies loaded. And System.Drawing has registered handler for OnProcessExit event, which fires due to the testing tool exiting.
* In that event, System.Drawing tries to use a type or a method from an assembly that was not loaded yet and so it calls into ALC.Load. And it correctly throws since the unloading was initiated before and thus we cannot load anything into the ALC.

So the question is why unloading of the GitHub_25468 test fails. It can be the case that something the test or its dependencies does prevents unloading in an expected way. In such case, the test should be marked as unloadability incompatible. Or, there is a bug that needs to be fixed.

**Comment by janvorli** [comment]
The problem happens only because the GitHub_25468 test fails to unload if loaded into the unloadable context. If the unload succeeded, the problem would not happen, since the System.Drawing would get unloaded before the OnProcessExit event fires.

Maybe you already know, but just to make sure we are on the same page - this reported failure happens only in the special test run when we run the GitHub_25468 using the runincontext tool. The test itself doesn't do anything unloadability related. 

Anyways, I've looked into what's preventing the unload of the test and it turns out it is actually the System.AppContext.OnProcessExit event handler. The event handler is registered to point to the System.Drawing.SafeNativeMethods.Gdip.OnProcessExit. The actual event lives in the default context while the System.Drawing is loaded into the unloadable context. That keeps the System.Drawing alive forever, preventing the unload.

Since loading the framework assemblies into the unloadable context is not a supported scenario, I would just exclude the test from the unloadability testing.
Or alternatively, maybe it is time to change the runincontext tool to actually load only the test assemblies into the unloadable context and keep the framework in the default context. I've made the runincontext tool to load everything except S.P.C. to the unloadable context at the very beginning since I wanted to make it kind of a stress testing, but also because at that time, I didn't know it will not be a supported scenario. But now things have settled down, the supported scenarios are much clearer and so we could change the tool.

As for the actual problem, developers can remedy such a case in their assemblies by hooking the Unload event and in its handler, removing their OnProcessExit handler.

**Comment by marklio** [comment]
> Since loading the framework assemblies into the unloadable context is not a supported scenario, I would just exclude the test from the unloadability testing.

@janvorli how does a developer know about this? Are there things in place that would prevent this from happening in normal scenarios?

**Comment by janvorli** [comment]
> Are there things in place that would prevent this from happening in normal scenarios?

The only way how it can happen is that the code either explicitly loads a framework assembly into the context or an override of the AssemblyLoadContext.Load method does that. If this overload uses the AssemblyDependencyResolver to resolve the assemblies (which is used in our official examples), then no framework assembly gets loaded into a non-default context.

@vitek-karas do you know if we mention somewhere that loading framework assemblies into a non-default AssemblyLoadContext is not a supported scenario?

**Comment by jeffschwMSFT** [comment]
@janvorli loading Framework assemblies is not explicity not support (customers do that), but when they have issues we discourage them from doing it and ask what they are trying to achieve.

To @marklio's point, what if the assembly was not a framework assembly but rather an assembly that was hooking OnProcessExit.  Further, what if the app developer did not have control of that code and they were loading it into a plug-in.  That I feel is the core scenario that is being discussed.

**Comment by vitek-karas** [comment]
To answer @janvorli : We have this in the docs: https://docs.microsoft.com/en-us/dotnet/api/system.runtime.loader.assemblyloadcontext?view=netcore-2.2#technical-challenges
>  Caution
> Loading multiple copies or different versions of framework assemblies can lead to unexpected and hard to diagnose behavior.

As @jeffschwMSFT points out, there are unfortunately cases where it's somewhat useful as a workaround to problems in the framework itself (for example internal caches which hold on to types making unloadability hard to achieve). But in general we discourage it and only suggest it as a last chace workaround in specific cases.

**Comment by janvorli** [comment]
> what if the assembly was not a framework assembly but rather an assembly that was hooking OnProcessExit.

As you know, the AssemblyLoadContext unloadability is based on GC references. So if anything outside of an unloadable context holds a strong reference to something inside of the context, the context cannot be unloaded until that reference is gone. The event handler like OnProcessExit handler is one of such cases. These cases are described in https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability-howto#troubleshoot-unloadability-issues
Maybe we can explicitly call out the OnProcessExit event there as a specific example there.

> Further, what if the app developer did not have control of that code and they were loading it into a plug-in

Then there is nothing that can be done besides fixing or not using the third party component. Except of some ugly reflection hacks, of course.
