### ISSUE TITLE
AVs in corefx CI runs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#2638]
I'm concerned some recent coreclr change (VM? JIT?) for Unix is causing AVs.
cc: @jkotas, @janvorli, @sergiy-k, @LLITCHEV, @joshfree 

Most of our Unix CI runs failed overnight, e.g.
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/ubuntu_release_tst/243/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/centos7.1_release_tst/234/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/opensuse13.2_release_tst/242/console
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/osx_release_tst/165/consoleFull

Example failures:
```
22:13:09       System.AggregateException : One or more errors occurred.
22:13:09       ---- System.NullReferenceException : Object reference not set to an instance of an object.
22:13:09       Stack Trace:
22:13:09 
22:13:09 Unhandled Exception: 
22:13:09 Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
22:13:09    at System.Linq.Parallel.SortHelper`2.MergeSortCooperatively()
22:13:09    at System.Linq.Parallel.SortHelper`2.Sort()
22:13:09    at System.Linq.Parallel.OrderPreservingSpoolingTask`2.SpoolingWork()
22:13:09    at System.Linq.Parallel.SpoolingTaskBase.Work()
22:13:09    at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
22:13:09    at System.Threading.Tasks.Task.Execute()
22:13:09    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
22:13:09    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
22:13:09    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
22:13:09    at System.Threading.ThreadPoolWorkQueue.Dispatch()
22:13:10 ./run-test.sh: line 130:   407 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
```

Another:
```
22:17:19 Unhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
22:17:19    at TestSupport.Collections.Common_GenericICollectionTest.ICollection_T_Test`1.VerifyItems(ArraySegment`1 actualItems, ArraySegment`1 expectedItems, VerificationLevel verificationLevel)
22:17:19    at TestSupport.Collections.Common_GenericICollectionTest.ICollection_T_Test`1.VerifyItems(T[] actualItems, T[] expectedItems, VerificationLevel verificationLevel)
22:17:19    at TestSupport.Collections.Common_GenericICollectionTest.ICollection_T_Test`1.CopyTo_Tests()
22:17:19    at TestSupport.Collections.Common_GenericICollectionTest.ICollection_T_Test`1.RunAllTests()
22:17:19    at TestSupport.Collections.IList_T_Test`1.Verify_ICollection(IList`1 collection, T[] items, Int32 index, Int32 count)
22:17:19    at TestSupport.Collections.IList_T_Test`1.ICollection_Tests()
22:17:19    at TestSupport.Collections.IList_T_Test`1.RunAllTests()
22:17:19    at VerifyReadOnlyIList`1.Verify(IList`1 list, T[] items, GenerateItem`1 generateItem)
22:17:19    at List_AsReadOnly.Driver`1.EmptyCollection(GenerateItem`1 generateItem)
22:17:19    at AsReadOnly.RunTests()
22:17:19    --- End of inner exception stack trace ---
22:17:19    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
22:17:19    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
22:17:19    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
22:17:19    at Xunit.Sdk.TestInvoker`1.CallTestMethod(Object testClassInstance)
22:17:19    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<<InvokeTestMethodAsync>b__1>d.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass46_1.<InvokeTestMethodAsync>b__1()
22:17:19    at Xunit.Sdk.ExecutionTimer.<AggregateAsync>d__4.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction)
22:17:19    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__9.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code)
22:17:19    at Xunit.Sdk.TestInvoker`1.<InvokeTestMethodAsync>d__46.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestInvoker`1.InvokeTestMethodAsync(Object testClassInstance)
22:17:19    at Xunit.Sdk.TestInvoker`1.<<RunAsync>b__45_0>d.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestInvoker`1.<RunAsync>b__45_0()
22:17:19    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
22:17:19    at Xunit.Sdk.XunitTestRunner.<InvokeTestAsync>d__4.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.XunitTestRunner.InvokeTestAsync(ExceptionAggregator aggregator)
22:17:19    at Xunit.Sdk.ExceptionAggregator.<RunAsync>d__10`1.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code)
22:17:19    at Xunit.Sdk.TestRunner`1.<RunAsync>d__43.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestRunner`1.RunAsync()
22:17:19    at Xunit.Sdk.TestCaseRunner`1.<RunAsync>d__19.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestCaseRunner`1.RunAsync()
22:17:19    at Xunit.Sdk.TestMethodRunner`1.<RunTestCasesAsync>d__32.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestMethodRunner`1.RunTestCasesAsync()
22:17:19    at Xunit.Sdk.TestMethodRunner`1.<RunAsync>d__31.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestMethodRunner`1.RunAsync()
22:17:19    at Xunit.Sdk.TestClassRunner`1.<RunTestMethodsAsync>d__38.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestClassRunner`1.RunTestMethodsAsync()
22:17:19    at Xunit.Sdk.TestClassRunner`1.<RunAsync>d__37.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestClassRunner`1.RunAsync()
22:17:19    at Xunit.Sdk.TestCollectionRunner`1.<RunTestClassesAsync>d__28.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestCollectionRunner`1.RunTestClassesAsync()
22:17:19    at Xunit.Sdk.TestCollectionRunner`1.<RunAsync>d__27.MoveNext()
22:17:19    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
22:17:19    at Xunit.Sdk.TestCollectionRunner`1.RunAsync()
22:17:19    at System.Threading.Tasks.Task`1.InnerInvoke()
22:17:19    at System.Threading.Tasks.Task.Execute()
22:17:19    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
22:17:19    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
22:17:19    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
22:17:19    at Xunit.Sdk.MaxConcurrencySyncContext.RunOnSyncContext(SendOrPostCallback callback, Object state)
22:17:19    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
22:17:19    at Xunit.Sdk.MaxConcurrencySyncContext.WorkerThreadProc()
22:17:19    at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
22:17:19    at System.Threading.Tasks.Task.Execute()
22:17:19    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
22:17:19    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
22:17:19    at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
22:17:19    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
22:17:19 ./run-test.sh: line 130: 10628 Aborted                 (core dumped) ./corerun xunit.console.netcore.exe $testDllName -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=$xunitOSCategory -notrait Benchmark=true
```

Another (this one isn't an AV, but we've not seen this test fail before, and this code hasn't changed recently, so I'm guessing it's related):
```
21:50:32    System.Numerics.Tests.ToStringTest.RunRegionSpecificStandardFormatToStringTests [FAIL]
21:50:32       Unexpected Exception:System.IndexOutOfRangeException: Index was outside the bounds of the array.
21:50:32          at System.Numerics.BigNumber.FormatBigInteger(BigInteger value, String format, NumberFormatInfo info)
21:50:32          at System.Numerics.BigInteger.ToString(String format)
21:50:32          at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
21:50:32       Expected: True
21:50:32       Actual:   False
21:50:32       Stack Trace:
21:50:33             at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, IFormatProvider provider, Boolean expectError, String expectedResult)
21:50:33             at System.Numerics.Tests.ToStringTest.VerifyToString(String test, String format, String expectedResult)
21:50:33             at System.Numerics.Tests.ToStringTest.RunStandardFormatToStringTests(Random random, String format, String negativeSign, Int32 precision, StringFormatter formatter)
21:50:33             at System.Numerics.Tests.ToStringTest.RunRegionSpecificStandardFormatToStringTests()
```

**Comment by stephentoub** [comment]
From looking over some of the logs, it appears that the failed builds all picked up the coreclr build at this commit/PR:
https://github.com/dotnet/coreclr/pull/2624
and that builds which picked up the prior coreclr succeeded.
cc: @sivarv

**Comment by stephentoub** [comment]
I ran one of the failing tests with a debug coreclr, and it hits this assert:
```
~/netcore$ ./corerun xunit.console.netcore.exe System.Linq.Parallel.Tests.dll -method "System.Linq.Parallel.Tests.GroupByTests.GroupBy_NotPipelined"
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Linq.Parallel.Tests
Discovered:  System.Linq.Parallel.Tests
Starting:    System.Linq.Parallel.Tests

Assert failure(PID 12507 [0x000030db], Thread: 12507 [0x30db]): Assertion failed '!(node->gtFlags & GTF_SPILL)' in 'System.Linq.Parallel.SortHelper`2[__Canon,Int32][System.__Canon,System.Int32]:MergeSortCooperatively():this' (IL size 955)

    File: /mnt/j/workspace/dotnet_coreclr/debug_ubuntu/src/jit/codegenxarch.cpp Line: 704
    Image: /home/stoub/netcore/corerun

**** MessageBox invoked, title 'corerun - Assert Failure (PID 12507, Thread 12507/0x30db)' ****
  Assertion failed '!(node->gtFlags & GTF_SPILL)' in 'System.Linq.Parallel.SortHelper`2[__Canon,Int32][System.__Canon,System.Int32]:MergeSortCooperatively():this' (IL size 955)


/mnt/j/workspace/dotnet_coreclr/debug_ubuntu/src/jit/codegenxarch.cpp, Line: 704

Abort - Kill program
Retry - Debug
Ignore - Keep running


Image:
/home/stoub/netcore/corerun

********

Aborted (core dumped)
```
The generated code for the relevant method:
```
```
Here's the JIT dump for the method:
[JITDump.txt](https://github.com/dotnet/coreclr/files/89068/JITDump.txt)

**Comment by jkotas** [comment]
Yes, #2624 seems to be the offending change - @stephentoub thanks for tracking it down.

I have submitted PR to revert it.
