### ISSUE TITLE
Test failure: baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType/FixedAddressValueType.sh

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#26426]
Test `baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType/FixedAddressValueType.sh` has failed.
```
Error message
Return code: 1
Raw output file: /root/helix/work/workitem/baseservices/compilerservices/Reports/baseservices.compilerservices/FixedAddressValueType/FixedAddressValueType/FixedAddressValueType.output.txt
Raw output:
BEGIN EXECUTION
in takeLock
/root/helix/work/correlation/crossgen /Platform_Assemblies_Paths /root/helix/work/correlation:/root/helix/work/workitem/baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType/IL:/root/helix/work/workitem/baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType /in FixedAddressValueType.org /out FixedAddressValueType.dll\nMicrosoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
Copyright (c) Microsoft Corporation. All rights reserved.

Native image FixedAddressValueType.dll generated successfully.
in ReleaseLock
in takeLock
/root/helix/work/correlation/corerun FixedAddressValueType.dll ''
in ReleaseLock
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:
> set CORE_ROOT=/root/helix/work/correlation
>/root/helix/work/workitem/baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType/FixedAddressValueType.sh
Expected: True
Actual: False

Stack trace
at baseservices_compilerservices._FixedAddressValueType_FixedAddressValueType_FixedAddressValueType_._FixedAddressValueType_FixedAddressValueType_FixedAddressValueType_sh() in /__w/1/s/bin/tests/Linux.arm.Release/TestWrappers/baseservices.compilerservices/baseservices.compilerservices.XUnitWrapper.cs:line 622
```
Details:
https://dnceng.visualstudio.com/internal/_build/results?buildId=328392&view=ms.vss-test-web.build-test-results-tab&runId=9607846&resultId=107652&paneView=debug

**Comment by BruceForstall** [comment]
```
R2R Linux arm Release no_tiered_compilation @ (Debian.9.Arm32)Ubuntu.1604.Arm32@mcr.microsoft.com/dotnet-buildtools/prereqs:debian-9-helix-arm32v7-74c9941-20190620155841
```

**Comment by BruceForstall** [comment]
I think this is a dup of https://github.com/dotnet/coreclr/issues/26424.

If it happens again, with the fix to that bug, please re-open.

**Comment by AriNuer** [comment]
Same test `baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType/FixedAddressValueType.sh` failed again:
```

Error message
Return code: 1
Raw output file: /root/helix/work/workitem/baseservices/compilerservices/Reports/baseservices.compilerservices/FixedAddressValueType/FixedAddressValueType/FixedAddressValueType.output.txt
Raw output:
BEGIN EXECUTION\n/root/helix/work/correlation/corerun FixedAddressValueType.dll ''
Expected: 100
Actual: 255
END EXECUTION - FAILED
Test Harness Exitcode is : 1
To run the test:\n
> set CORE_ROOT=/root/helix/work/correlation
>/root/helix/work/workitem/baseservices/compilerservices/FixedAddressValueType/FixedAddressValueType/FixedAddressValueType.sh
Expected: True
Actual: False

Stack trace
at baseservices_compilerservices._FixedAddressValueType_FixedAddressValueType_FixedAddressValueType_._FixedAddressValueType_FixedAddressValueType_FixedAddressValueType_sh() in /__w/1/s/bin/tests/Linux.arm.Release/TestWrappers/baseservices.compilerservices/baseservices.compilerservices.XUnitWrapper.cs:line 622
```

Build: -[20190908.1](https://dnceng.visualstudio.com/internal/_build/results?buildId=344087)(master)
Details:
https://dnceng.visualstudio.com/internal/_build/results?buildId=344087&view=ms.vss-test-web.build-test-results-tab&runId=10272764&resultId=107157&paneView=debug
