### ISSUE TITLE
Local variable getting modified by function call

### ISSUE THREAD

**Issue by r-ramesh** [dotnet/coreclr#26537]
Local variable gets modified by an unrelated function call, with .NET Core 3.0. Admittedly the type in question is a bit weird, lifted from a CoreCLR test case.

In the code snippet below, "instance" mutates from being an object of type "GenInt" to a "List<FieldInfo" magically. Calling GetAllInstanceFields shouldn't modified the local of the caller.

Observed output:
ClrIssueRepro.GenInt
System.Object

Expected output:
ClrIssueRepro.GenInt
ClrIssueRepro.GenInt

Here is the code snippet:

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Runtime.Serialization;
#pragma warning disable 649, 169
namespace ClrIssueRepro
{
    [StructLayout(LayoutKind.Sequential)]
    public class GenBase<T>
    {
        public T Fld10;

        public int _int0 = 0;
        public double _double0 = 0;
        public string _string0 = "string0";
        public Guid _Guid0 = new Guid();

        public T Fld11;

        public int _int1 = int.MaxValue;
        public double _double1 = double.MaxValue;
        public string _string1 = "string1";
        public Guid _Guid1 = new Guid(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

        public T Fld12;
    }

    [StructLayout(LayoutKind.Explicit)]
    public class GenInt : GenBase<int>
    {
        [FieldOffset(0)] public int sFld10;

        [FieldOffset(16)] public int _sint0 = 0;
        [FieldOffset(24)] public double _sdouble0 = 0;
        [FieldOffset(32)] public string _sstring0 = "string0";
        [FieldOffset(40)] public Guid _sGuid0 = new Guid();

        [FieldOffset(56)] public int sFld11;

        [FieldOffset(72)] public int _sint1 = int.MaxValue;
        [FieldOffset(80)] public double _sdouble1 = double.MaxValue;
        [FieldOffset(88)] public string _sstring1 = "string1";
        [FieldOffset(96)] public Guid _sGuid1 = new Guid(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

        [FieldOffset(112)] public int sFld12;
    }

    class Program
    {
        private static FieldInfo[] GetAllInstanceFields(Type type)
        {
            List<FieldInfo> result = new List<FieldInfo>();
            for (Type t = type; t != null; t = t.BaseType)
            {
                // Stop iterating once we get to System.ValueType. There should be no fields in it
                // or System.Object, it's base class. This is ok to do for desktop & ProjectN.
                if (t == typeof(ValueType))
                {
                    break;
                }

                FieldInfo[] fieldsOnType = t.GetFields(
                    BindingFlags.Public |
                    BindingFlags.NonPublic |
                    BindingFlags.Instance |
                    BindingFlags.DeclaredOnly);
                result.AddRange(fieldsOnType);
            }

            return result.ToArray();
        }

        private static object CreateInstance(Type t)
        {
            return t.IsValueType ? Activator.CreateInstance(t) : FormatterServices.GetUninitializedObject(t);
        }

        static void Main(string[] args)
        {
            Type type = typeof(GenInt);

            object instance = CreateInstance(type);
            // instance is of type GenInt.

            Console.WriteLine(instance.GetType());

            System.Reflection.FieldInfo[] fields = GetAllInstanceFields(type);
            // is it still?

            Console.WriteLine(instance.GetType());
            Debugger.Break();
        }
    }
}

**Comment by r-ramesh** [comment]
Note this doesn't repro on Desktop framework.

**Comment by mattwarren** [comment]
I was intrigued by this, so I put together a minimal repo, in case its useful to anyone else:

``` C#
using System;
using System.Reflection;
using System.Runtime.InteropServices;
#if (NETCOREAPP1_0 || NETCOREAPP1_1 || NETCOREAPP2_0 || NETCOREAPP2_1 || NETCOREAPP2_2 || NETCOREAPP3_0)
using System.Runtime.Versioning;
#endif

namespace ClrIssueRepro
{
    // If you remove '[StructLayout(LayoutKind.Sequential)]', you get:
    // Unhandled exception. System.TypeLoadException: 
    // Could not load type 'ClrIssueRepro.GenInt' from assembly '...' 
    //    because the format is invalid.
    //  at ClrIssueRepro.Program.Main(String[] args)
    [StructLayout(LayoutKind.Sequential)]
    public class GenBase<T>
    {
        public string _string0 = "string0";
        public string _string1 = "string1";
    }

    [StructLayout(LayoutKind.Explicit)]
    public class GenInt : GenBase<int>
    {
        // Commenting out either one of these fields fixes things!?
        [FieldOffset(0)] public string _sstring0 = "string0";
        [FieldOffset(16)] public string _sstring1 = "string1";
    }

    // This works! (it's GenInt with [StructLayout(LayoutKind.Explicit)] and [FieldOffset(..)] removed)
    public class GenIntNormal : GenBase<int>
    {
        public string _sstring0 = "string0";
        public string _sstring1 = "string1";
    }

    class Program
    {
        static void Main(string[] args)
        {
#if (NETCOREAPP1_0 || NETCOREAPP1_1 || NETCOREAPP2_0 || NETCOREAPP2_1 || NETCOREAPP2_2 || NETCOREAPP3_0)
            var framework = Assembly
                .GetEntryAssembly()
                .GetCustomAttribute<TargetFrameworkAttribute>()
                .FrameworkName;
            Console.WriteLine(framework);
#endif

            // If you comment this line out, you get
            //    Unhandled exception. System.TypeLoadException: 
            //    Could not load type 'ClrIssueRepro.GenInt' from assembly '...'
            //    at ClrIssueRepro.Program.Main(String[] args)
            // in Debug and Release builds?!
            Type type = typeof(GenInt);

            object instance = new GenInt();

            // GenIntNormal has the same fields as GenInt, but has
            // [StructLayout(LayoutKind.Explicit)] and [FieldOffset(..)] REMOVED
            //object instance = new GenIntNormal(); // works fine!!

            Console.WriteLine(instance.GetType()); // System.String?!
        }
    }
}
```

If you run `dotnet run -c Debug -f netcoreapp3.0` you get:

```
.NETCoreApp,Version=v3.0
System.String
```

If you do `dotnet run -c Release -f netcoreapp3.0` you instead get:

```
Unhandled exception. System.TypeLoadException: Could not load type 'ClrIssueRepro.GenInt' from assembly 'WierdBug-CoreCLR-26537, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at ClrIssueRepro.Program.Main(String[] args)
```

I get exactly the same output (Debug and Release) if I run with `-f net45` or `-f net46`. 

However if I paste the above code into a **.NET Framework 4.7.2** console app (in Visual Studio), both Debug and Release builds print 'ClrIssueRepro.GenInt' as expected?
