### ISSUE TITLE
Test failed: tracing/eventpipe/buffersize/buffersize/buffersize.sh

### ISSUE THREAD

**Issue by VincentBu** [dotnet/coreclr#26554]
**Job:**
[coreclr-outerloop 20190905.7](https://dev.azure.com/dnceng/public/_build/results?buildId=339271)
Run Test Pri1 R2R OSX x64 checked

**Detail:**
console log: https://helix.dot.net/api/2019-06-17/jobs/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/workitems/PayloadGroup0/console

**OS & Arch:** 
OSX x64

**Mode:** 
    RunCrossGen=1
    COMPlus_TieredCompilation=0

**Failed tests:**
tracing/eventpipe/buffersize/buffersize/buffersize.sh
tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh

**Note:**
These failures **don't repro** on our OSX x64 machine.

**Log:**
```
tracing/eventpipe/buffersize/buffersize/buffersize.sh [FAIL]
      
      Return code:      1
      Raw output file:      /private/tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Work/557401af-9032-472a-8131-66fb6aa90e5b/Exec/tracing/eventpipe/Reports/tracing.eventpipe/buffersize/buffersize/buffersize.output.txt
      Raw output:
      BEGIN EXECUTION
      in takeLock
      /tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Payload/crossgen /Platform_Assemblies_Paths /tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Payload:/private/tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Work/557401af-9032-472a-8131-66fb6aa90e5b/Exec/tracing/eventpipe/buffersize/buffersize/IL:/private/tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Work/557401af-9032-472a-8131-66fb6aa90e5b/Exec/tracing/eventpipe/buffersize/buffersize /in buffersize.org /out buffersize.dll
      Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
      Copyright (c) Microsoft Corporation.  All rights reserved.
      
      Native image buffersize.dll generated successfully.
      in ReleaseLock
      in takeLock
      /tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Payload/corerun buffersize.dll ''
        0.0s: ==TEST STARTING==
        0.0s: Connecting to EventPipe...
        0.3s: System.InvalidOperationException: Sequence contains more than one matching element
         at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException() in /_/src/System.Linq/src/System/Linq/ThrowHelper.cs:line 22
         at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate) in /_/src/System.Linq/src/System/Linq/Single.cs:line 150
         at Microsoft.Diagnostics.Tools.RuntimeClient.DiagnosticsIpc.IpcClient.GetTransport(Int32 processId) in /_/src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcClient.cs:line 43
         at Microsoft.Diagnostics.Tools.RuntimeClient.DiagnosticsIpc.IpcClient.SendMessage(Int32 processId, IpcMessage message, IpcMessage& response) in /_/src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcClient.cs:line 84
         at Microsoft.Diagnostics.Tools.RuntimeClient.EventPipeClient.CollectTracing(Int32 processId, SessionConfiguration configuration, UInt64& sessionId) in /_/src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs:line 51
         at Tracing.Tests.Common.IpcTraceTest.Validate() in /Users/vsts/agent/2.155.1/work/1/s/tests/src/tracing/eventpipe/common/IpcTraceTest.cs:line 175
         at Tracing.Tests.Common.IpcTraceTest.RunAndValidateEventCounts(Dictionary`2 expectedEventCounts, Action eventGeneratingAction, Nullable`1 sessionConfiguration, Func`2 optionalTraceValidator) in /Users/vsts/agent/2.155.1/work/1/s/tests/src/tracing/eventpipe/common/IpcTraceTest.cs:line 297
        0.3s: ==TEST FINISHED: FAILED!==
      in ReleaseLock
      Expected: 100
      Actual: 255
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1

tracing/eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.sh [FAIL]
      
      Return code:      1
      Raw output file:      /private/tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Work/557401af-9032-472a-8131-66fb6aa90e5b/Exec/tracing/eventpipe/Reports/tracing.eventpipe/rundownvalidation/rundownvalidation/rundownvalidation.output.txt
      Raw output:
      BEGIN EXECUTION
      in takeLock
      /tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Payload/crossgen /Platform_Assemblies_Paths /tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Payload:/private/tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Work/557401af-9032-472a-8131-66fb6aa90e5b/Exec/tracing/eventpipe/rundownvalidation/rundownvalidation/IL:/private/tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Work/557401af-9032-472a-8131-66fb6aa90e5b/Exec/tracing/eventpipe/rundownvalidation/rundownvalidation /in rundownvalidation.org /out rundownvalidation.dll
      Microsoft (R) CoreCLR Native Image Generator - Version 4.5.30319.0
      Copyright (c) Microsoft Corporation.  All rights reserved.
      
      Native image rundownvalidation.dll generated successfully.
      in ReleaseLock
      in takeLock
      /tmp/helix/working/04af6fb9-85f4-42d7-ab4b-0d5bb40960e9/Payload/corerun rundownvalidation.dll ''
        0.0s: ==TEST STARTING==
        0.1s: Connecting to EventPipe...
        0.3s: System.InvalidOperationException: Sequence contains more than one matching element
         at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException() in /_/src/System.Linq/src/System/Linq/ThrowHelper.cs:line 22
         at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate) in /_/src/System.Linq/src/System/Linq/Single.cs:line 150
         at Microsoft.Diagnostics.Tools.RuntimeClient.DiagnosticsIpc.IpcClient.GetTransport(Int32 processId) in /_/src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcClient.cs:line 43
         at Microsoft.Diagnostics.Tools.RuntimeClient.DiagnosticsIpc.IpcClient.SendMessage(Int32 processId, IpcMessage message, IpcMessage& response) in /_/src/Microsoft.Diagnostics.Tools.RuntimeClient/DiagnosticsIpc/IpcClient.cs:line 84
         at Microsoft.Diagnostics.Tools.RuntimeClient.EventPipeClient.CollectTracing(Int32 processId, SessionConfiguration configuration, UInt64& sessionId) in /_/src/Microsoft.Diagnostics.Tools.RuntimeClient/Eventing/EventPipeClient.cs:line 51
         at Tracing.Tests.Common.IpcTraceTest.Validate() in /Users/vsts/agent/2.155.1/work/1/s/tests/src/tracing/eventpipe/common/IpcTraceTest.cs:line 175
         at Tracing.Tests.Common.IpcTraceTest.RunAndValidateEventCounts(Dictionary`2 expectedEventCounts, Action eventGeneratingAction, Nullable`1 sessionConfiguration, Func`2 optionalTraceValidator) in /Users/vsts/agent/2.155.1/work/1/s/tests/src/tracing/eventpipe/common/IpcTraceTest.cs:line 297
        0.3s: ==TEST FINISHED: FAILED!==
      in ReleaseLock
      Expected: 100
      Actual: 255
      END EXECUTION - FAILED
      Test Harness Exitcode is : 1
```

**Comment by sywhang** [comment]
https://github.com/dotnet/coreclr/pull/26573 should prevent failures like this from happening again.
