### ISSUE TITLE
Issue when using Entity Framework

### ISSUE THREAD

**Issue by lsvMoretti** [dotnet/coreclr#26791]
Hey, sorry this is my first real issue to post anywhere.

I have Pomelo Entity Framework MySQL and I have also tried MySql.Data.EntityFrameworkCore, both stable and pre-release versions, how ever using the latest .net core SDK, I have an issue when doing anything with Entity Framework.

My Code:

```
try
            {
                Console.WriteLine("Before Context");
                using Context context = new Context();
                Console.WriteLine("After Context");
                List<Models.Vehicle> vehicles = context.Vehicle.Where(x => x.Spawned).ToList();

                Console.WriteLine($"Resetting {vehicles.Count} Vehicle Spawn Status");

                foreach (Models.Vehicle vehicle in vehicles)
                {
                    vehicle.Spawned = false;
                    context.SaveChanges();
                }

                Console.WriteLine("Completed resetting vehicle spawn statuses");
                context.Dispose();
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
```

The error

```
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Extensions.Configuration.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. An operation is not legal in the current state. (0x80131509)
File name: 'Microsoft.Extensions.Configuration.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
 ---> System.InvalidOperationException: AssemblyLoadContext is unloading or was already unloaded.
   at System.Runtime.Loader.AssemblyLoadContext.VerifyIsAlive()
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at AltV.Net.Host.ResourceAssemblyLoadContext.Load(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUsingLoad(AssemblyName assemblyName)
   at System.Runtime.Loader.AssemblyLoadContext.Resolve(IntPtr gchManagedAssemblyLoadContext, AssemblyName assemblyName)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NamedConnectionStringResolverBase.ResolveConnectionString(String connectionString)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection..ctor(RelationalConnectionDependencies dependencies)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Linq.IQueryable.get_Provider()
   at System.Linq.Queryable.Where[TSource](IQueryable`1 source, Expression`1 predicate)
   at Server.Vehicle.LoadVehicle.ResetAllVehiclesSpawnStatus() in F:\Andrew\Documents\Los Santos V\Development\Github\Los-Santos-V\Server\Vehicle\LoadVehicle.cs:line 21
```
Line 21 is the .ToList line.

**Comment by jeffschwMSFT** [comment]
@Pilchie based on the callstack this looks like EntityFramework is trying to load an assembly into an AssemblyLoadContext which has been unloaded.  is there someone on your team that can take a look?

**Comment by lsvMoretti** [comment]
I've tried using SQL and MySQL both having the same issue. Any updates? My programs are currently unable to work due to this error.

**Comment by Pilchie** [comment]
@AndriySvyryd ? Can you route?  Or if you want me to move this to the EF repo, let me know.

**Comment by lsvMoretti** [comment]
After getting help from a developer of Pomelo it was an issue with one of my dependencies.

See:

https://github.com/FabianTerhorst/coreclr-module/issues/58

This can be closed if you wisg

**Comment by Pilchie** [comment]
Thanks for getting back to us.  Closing.
