### ISSUE TITLE
dotnet segfaults when COMPlus_PerfMapEnabled=1

### ISSUE THREAD

**Issue by tmds** [dotnet/coreclr#26917]
```
$ dotnet --version
3.0.100
$ COMPlus_PerfMapEnabled=1 dotnet new console
Getting ready...
Segmentation fault (core dumped)
```
stacktrace:
```
(gdb) bt
#0  0x00007ffff6f77caa in PerfInfo::LogImage(PEFile*, char16_t*) () from /home/tmds/Downloads/dotnet-3.0/shared/Microsoft.NETCore.App/3.0.0/libcoreclr.so
#1  0x00007ffff6f76e57 in PerfMap::LogImage(PEFile*) () from /home/tmds/Downloads/dotnet-3.0/shared/Microsoft.NETCore.App/3.0.0/libcoreclr.so
#2  0x00007ffff70b156a in Assembly::CreateDynamic(AppDomain*, CreateDynamicAssemblyArgs*) ()
   from /home/tmds/Downloads/dotnet-3.0/shared/Microsoft.NETCore.App/3.0.0/libcoreclr.so
#3  0x00007ffff710552a in AppDomainNative::CreateDynamicAssembly(AssemblyNameBaseObject*, StackCrawlMark*, int) ()
   from /home/tmds/Downloads/dotnet-3.0/shared/Microsoft.NETCore.App/3.0.0/libcoreclr.so
```

**Comment by tmds** [comment]
dup of https://github.com/dotnet/coreclr/issues/26883.
