### ISSUE TITLE
Changing process affinity from 1 to N cores causes memory corruption and deadlocks

### ISSUE THREAD

**Issue by GPSnoopy** [dotnet/coreclr#26990]
**To reproduce the problem**
- Launch a process with its initial thread affinity pinned to 1 core.
- Process unpins itself from 1 core to multiple cores.
- Process runs several asynchronous Tasks.
- Process will randomly experience memory corruption (including deadlocks and spurious exceptions).

We suspect the problem has been introduced in .NET 4.8 as well as .NET Core 2.1 (or earlier).

**Notes**
- Confirmed to happen on Windows 7, Windows 10.
- Confirmed to happen on .NET Framework 4.8, .NET Core 2.1, .NET Core 3.0.
- Confirmed not to happen on .NET Framework 4.7 (as long as .NET Framework 4.8 has not been installed on the machine).
- The more tasks are started, the more likely it will go wrong.
- Setting initial affinity to 0x0001 (rather than 0x0002) fails to reproduce the problem.
- Subsequent affinity needs to be any number of cores other than 1 (0x0FFF being used here as the test machine had 12 cores, you will need to switch to a smaller mask if your machine has less cores).

**How come we are doing this**
When submitting a job to our internal compute farm, its process gets assigned to the specific CPU cores allocated for the job to run on. Most jobs only request one CPU core, therefore their affinity mask gets set to one core.

In the case of our GPU compute farm, the CPUs are not the limiting resource. Instead we want to pin the process to the CPU cores closest to the GPU we've been assigned to. Because our farm scheduler does not seem to be able to understand the complexity of GPU and NUMA node topologies., we apply the logic above once the job has started from within the job process itself.

**Comment by GPSnoopy** [comment]
Adding reproducible example: 
[Net48Tester_20191002.zip](https://github.com/dotnet/coreclr/files/3681555/Net48Tester_20191002.zip)

Targets net48, netcoreapp2.1 and netcoreapp3.0.

**Comment by janvorli** [comment]
cc: @Maoni0

**Comment by Maoni0** [comment]
I'm unfamiliar with these exceptions - how could you tell these are due to memory corruption? @stephentoub do these seem like exceptions caused by memory corruption to you?

are you using Server GC at all? if you are using the default which is Workstation GC it doesn't care about the affinity of the process.

**Comment by GPSnoopy** [comment]
@Maoni0 While trying to reproduce these errors, I've seen hundreds of different errors and exceptions. I believe they are just symptoms of general undefined behaviour rather than pointing to the real culprit. I've seen many AccessViolationException instances as well as clear evidence of corrupted memory locations. The root cause could be a race condition or a dangling pointer.

The GC type does not seem impact the reproducibility of this issue. I've seen it on my Windows 10 desktop with the code above as well as on Windows Server 2016 using production code. Turning concurrent GC on and off had no impact either.

For the laugh, here are a couple more (using .NET 4.8), including a clear memory access violation:
```
Launching subprocess...
CPU affinity: 0000000000000002
New affinity: 0000000000000FFF
ERROR: System.AggregateException: One or more errors occurred. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Threading.Tasks.RangeWorker.FindNewWork(Int64& nFromInclusiveLocal, Int64& nToExclusiveLocal)
   at System.Threading.Tasks.RangeWorker.FindNewWork32(Int32& nFromInclusiveLocal32, Int32& nToExclusiveLocal32)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int32 fromInclusive, Int32 toExclusive, Action`1 body)
   at Net48Tester.Program.Child(Process current) in D:\Temporary\Net48Tester\Net48Tester\Tester\Program.cs:line 127
   at Net48Tester.Program.Main(String[] args) in D:\Temporary\Net48Tester\Net48Tester\Tester\Program.cs:line 20
---> (Inner Exception #0) System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Threading.Tasks.RangeWorker.FindNewWork(Int64& nFromInclusiveLocal, Int64& nToExclusiveLocal)
   at System.Threading.Tasks.RangeWorker.FindNewWork32(Int32& nFromInclusiveLocal32, Int32& nToExclusiveLocal32)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass17_0`1.<ForWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
   at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)<---
```
```
Launching subprocess...
CPU affinity: 0000000000000002
New affinity: 0000000000000FFF

Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.String.Concat(String str0, String str1, String str2)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at System.Exception.ToString(Boolean needFileLineInfo, Boolean needMessage)
   at System.AggregateException.ToString()
   at Net48Tester.Program.Main(String[] args) in D:\Temporary\Net48Tester\Net48Tester\Tester\Program.cs:line 35
```

Do note that so far I've not been able to reproduce the problem on Linux (Ubuntu 18.04 with .NET Core 3.0). I suspect part of the answer might be in the C++ internals of the CLR.

**Comment by janvorli** [comment]
I've just realized it could also be related to the thread pool. @kouvel does it seem possible to you?

**Comment by GPSnoopy** [comment]
@janvorli My hunch so far is either the thread pool implementation, or something related like the work queues. These are also the parts that appear the most often in the stack traces.

I've cloned the coreclr repo and inspected it, but it's a big haystack.

**Comment by jkotas** [comment]
This is a problem with the UP allocation helpers. We use `GetCurrentProcessCpuCount` to decide whether it is ok to use them here: https://github.com/dotnet/coreclr/blob/master/src/vm/gcheaputilities.h#L130
but the implementation of the UP allocation helpers does not use interlocked operations, e.g. here:
https://github.com/dotnet/coreclr/blob/master/src/vm/amd64/JitHelpers_Slow.asm#L174

We either need to use total CPU count to decide whether it is ok to use them; or make them multi-processor safe by using interlocked operations.

**Comment by jkotas** [comment]
> The GC type does not seem impact the reproducibility of this issue. 

This repros with workstation GC only, but you do not see it because of we ignore the request to use server GC if the process is affinitized to a single processor during startup: https://github.com/dotnet/coreclr/blob/master/src/vm/ceemain.cpp#L456

**Comment by jkotas** [comment]
> We suspect the problem has been introduced in .NET 4.8 as well as .NET Core 2.1 

You are right. This problem was introduced by https://github.com/dotnet/coreclr/pull/10065/

**Comment by jkotas** [comment]
Reopening for 3.1 port

**Comment by jkotas** [comment]
For .NET Framework, we are currently planning to fix this for January 2020 update.

**Comment by JohnFredMeyer** [comment]
I just wanted to add that I ran across this issue as well and noticed that if I ran on a virtual machine with ONE vCPU and .net 4.7.2 that the issue still arose for me but if I ran on a virtual machine with TWO or more vCPU and .net 4.7.2 it was not reproducible. The inverse was true for .net 4.8 where a virtual machine with ONE vCPU and .net 4.8  could not reproduce but with a virtual machine with TWO or more vCPU and .net 4.8 I could reproduce.
