### ISSUE TITLE
Test failure : System.Runtime.CompilerServices.UnsafeTests.RefIsAddressLessThan

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#27279]
**Job:**
[coreclr-corefx : 20191017.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=391287)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/1d928d1c-439e-4f3c-90bb-5dc9ebadfa88/workitems/System.Runtime.CompilerServices.Unsafe.Tests/console

**OS & Arch:**
Windows x86

**Mode:**
set COMPlus_TieredCompilation=0

**Note:**
This failure **repro** on our windows x86 machine.

**Log:**
```
C:\dotnetbuild\work\1d928d1c-439e-4f3c-90bb-5dc9ebadfa88\Work\ecca1366-293c-42bd-bd59-6fa4019e510f\Exec>"C:\dotnetbuild\work\1d928d1c-439e-4f3c-90bb-5dc9ebadfa88\Payload\dotnet.exe" exec --runtimeconfig System.Runtime.CompilerServices.Unsafe.Tests.runtimeconfig.json xunit.console.dll System.Runtime.CompilerServices.Unsafe.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\1d928d1c-439e-4f3c-90bb-5dc9ebadfa88\Payload\CoreFX.issues.rsp 
  Discovering: System.Runtime.CompilerServices.Unsafe.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.CompilerServices.Unsafe.Tests (found 52 test cases)
  Starting:    System.Runtime.CompilerServices.Unsafe.Tests (parallel test collections = on, max threads = 2)
    System.Runtime.CompilerServices.UnsafeTests.RefIsAddressLessThan [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs(631,0): at System.Runtime.CompilerServices.UnsafeTests.RefIsAddressLessThan()
  Finished:    System.Runtime.CompilerServices.Unsafe.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.CompilerServices.Unsafe.Tests  Total: 108, Errors: 0, Failed: 1, Skipped: 0, Time: 18.384s
----- end Thu 10/17/2019 10:55:51.69 ----- exit code 1 ----------------------------------------------------------
```

**Comment by VincentBu** [comment]
**Job:**
[coreclr-corefx #20191027.1 Run Test Pri1 CoreFX Windows_NT x86 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=403696)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/bc5e3041-5569-46ef-aab9-c47c7763676a/workitems/System.Runtime.CompilerServices.Unsafe.Tests/console

**OS & Arch:**
windows x86

**Mode:**
COMPlus_TieredCompilation=0

**Note:**
This failure **repros**  on our windows x64 machine

**Log:**
```
System.Runtime.CompilerServices.UnsafeTests.RefIsAddressLessThan [FAIL]
      Assert.False() Failure
      Expected: False
      Actual:   True
      Stack Trace:
        /_/src/System.Runtime.CompilerServices.Unsafe/tests/UnsafeTests.cs(631,0): at System.Runtime.CompilerServices.UnsafeTests.RefIsAddressLessThan()
  Finished:    System.Runtime.CompilerServices.Unsafe.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.CompilerServices.Unsafe.Tests  Total: 110, Errors: 0, Failed: 1, Skipped: 0, Time: 19.991s
----- end Sun 10/27/2019 11:17:25.49 ----- exit code 1
```

**Comment by BruceForstall** [comment]
@jkotas Do you know a suggested owner for this area?

**Comment by jkotas** [comment]
I think it is codegen bug.

**Comment by jkotas** [comment]
The bug is triggered by `clt.un` IL instruction that takes two byrefs.

**Comment by jkotas** [comment]
Minimal repro:

```
static void Main() {
    Console.WriteLine(Unsafe.IsAddressLessThan(ref Unsafe.AsRef<byte>((void*)(-1)), ref Unsafe.AsRef<byte>((void*)(1))).ToString());
}
```

Expected result (this is what you get with `COMPlus_TieredCompilation=1`): False

Actual result (this is what you get `COMPlus_TieredCompilation=0`): True

**Comment by BruceForstall** [comment]
@sandreenko Can you look at this one?
