### ISSUE TITLE
[JitStressRegs=3] System.Net.Requests.Tests failed with System.ArgumentNullException : Value cannot be null 

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2730]
**Configuration**

Linux
Coreclr checked build
Corefx release build

Coreclr: 761fa46 (Wed Jan 13 18:15:58 2016 -0500)
Corefx: 0824d9745687271503f7538d16f44f17f5ef5f18 (Tue Jan 12 14:49:52 2016 -0800)

**Failure**

Fail with JitStressReg=0x3 and 0x80
Pass without JitStressReg

```
corefx/bin/tests/Linux.AnyCPU.Release/System.Net.Requests.Tests/dnxcore50$ COMPlus_JitStressRegs=3 ./corerun xunit.console.netcore.exe System.Net.Requests.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true
xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Net.Requests.Tests
Discovered:  System.Net.Requests.Tests
Starting:    System.Net.Requests.Tests
   System.Net.Tests.HttpWebRequestTest.Headers_GetResponseHeaders_ContainsExpectedValue(remoteServer: http://corefx-net.azurewebsites.net/Echo.ashx) [FAIL]
      System.ArgumentNullException : Value cannot be null.
      Parameter name: SafeHandle cannot be null.
      Stack Trace:
            at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
            at Interop.GlobalizationInterop.CompareString(SafeSortHandle sortHandle, Char* lpStr1, Int32 cwStr1Len, Char* lpStr2, Int32 cwStr2Len, CompareOptions options)
            at System.Globalization.CompareInfo.CompareString(String string1, Int32 offset1, Int32 length1, String string2, Int32 offset2, Int32 length2, CompareOptions options)
            at System.__DTString.MatchSpecifiedWord(String target, Int32 endIndex)
            at System.DateTimeParse.MatchAbbreviatedDayName(__DTString& str, DateTimeFormatInfo dtfi, Int32& result)
            at System.DateTimeParse.ParseByFormat(__DTString& str, __DTString& format, ParsingInfo& parseInfo, DateTimeFormatInfo dtfi, DateTimeResult& result)
            at System.DateTimeParse.DoStrictParse(String s, String formatParam, DateTimeStyles styles, DateTimeFormatInfo dtfi, DateTimeResult& result)
            at System.DateTimeParse.TryParseExactMultiple(String s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, DateTimeResult& result)
            at System.DateTimeParse.TryParseExactMultiple(String s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, DateTime& result, TimeSpan& offset)
            at System.DateTimeOffset.TryParseExact(String input, String[] formats, IFormatProvider formatProvider, DateTimeStyles styles, DateTimeOffset& result)
            at System.Net.Http.HttpRuleParser.TryStringToDate(String input, DateTimeOffset& result)
            at System.Net.Http.Headers.DateHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
            at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(String name, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
            at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(String name, HeaderStoreItemInfo info)
            at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(String name, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
            at System.Net.Http.Headers.HttpHeaders.<GetEnumerator>d__20.MoveNext()
            at System.Net.HttpWebResponse.get_Headers()
            at System.Net.Tests.HttpWebRequestTest.<Headers_GetResponseHeaders_ContainsExpectedValue>d__46.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   System.Net.Tests.HttpWebRequestTest.Headers_GetResponseHeaders_ContainsExpectedValue(remoteServer: https://corefx-net.azurewebsites.net/Echo.ashx) [FAIL]
      System.ArgumentNullException : Value cannot be null.
      Parameter name: SafeHandle cannot be null.
      Stack Trace:
            at System.StubHelpers.StubHelpers.SafeHandleAddRef(SafeHandle pHandle, Boolean& success)
            at Interop.GlobalizationInterop.CompareString(SafeSortHandle sortHandle, Char* lpStr1, Int32 cwStr1Len, Char* lpStr2, Int32 cwStr2Len, CompareOptions options)
            at System.Globalization.CompareInfo.CompareString(String string1, Int32 offset1, Int32 length1, String string2, Int32 offset2, Int32 length2, CompareOptions options)
            at System.__DTString.MatchSpecifiedWord(String target, Int32 endIndex)
            at System.DateTimeParse.MatchAbbreviatedDayName(__DTString& str, DateTimeFormatInfo dtfi, Int32& result)
            at System.DateTimeParse.ParseByFormat(__DTString& str, __DTString& format, ParsingInfo& parseInfo, DateTimeFormatInfo dtfi, DateTimeResult& result)
            at System.DateTimeParse.DoStrictParse(String s, String formatParam, DateTimeStyles styles, DateTimeFormatInfo dtfi, DateTimeResult& result)
            at System.DateTimeParse.TryParseExactMultiple(String s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, DateTimeResult& result)
            at System.DateTimeParse.TryParseExactMultiple(String s, String[] formats, DateTimeFormatInfo dtfi, DateTimeStyles style, DateTime& result, TimeSpan& offset)
            at System.DateTimeOffset.TryParseExact(String input, String[] formats, IFormatProvider formatProvider, DateTimeStyles styles, DateTimeOffset& result)
            at System.Net.Http.HttpRuleParser.TryStringToDate(String input, DateTimeOffset& result)
            at System.Net.Http.Headers.DateHeaderParser.TryParseValue(String value, Object storeValue, Int32& index, Object& parsedValue)
            at System.Net.Http.Headers.HttpHeaders.TryParseAndAddRawHeaderValue(String name, HeaderStoreItemInfo info, String value, Boolean addWhenInvalid)
            at System.Net.Http.Headers.HttpHeaders.ParseSingleRawHeaderValue(String name, HeaderStoreItemInfo info)
            at System.Net.Http.Headers.HttpHeaders.ParseRawHeaderValues(String name, HeaderStoreItemInfo info, Boolean removeEmptyHeader)
            at System.Net.Http.Headers.HttpHeaders.<GetEnumerator>d__20.MoveNext()
            at System.Net.HttpWebResponse.get_Headers()
            at System.Net.Tests.HttpWebRequestTest.<Headers_GetResponseHeaders_ContainsExpectedValue>d__46.MoveNext()
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
         --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
            at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Finished:    System.Net.Requests.Tests

=== TEST EXECUTION SUMMARY ===
   System.Net.Requests.Tests  Total: 111, Errors: 0, Failed: 2, Skipped: 0, Time: 17.136s
```

**Comment by sejongoh** [comment]
This also looks a duplicate of #2380.
