### ISSUE TITLE
Test failure : System.Numerics.Tests.ComplexTests.Pow

### ISSUE THREAD

**Issue by AriNuer** [dotnet/coreclr#27332]
**Job:**
[coreclr-corefx-jitstressregs:20191020.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=394941)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/f0c1a15f-48eb-40e9-a2b1-a9a6077cda59/workitems/System.Runtime.Numerics.Tests/console

**OS & Arch:**
Windows x64

**Note:**

- There are no `MicrosoftPrivateCoreFxNETCoreAppVersion` in eng\Versions.props in coreclr repo, but `MicrosoftPrivateCoreFxNETCoreAppPackageVersion`
- This failure **doesn't repro** on our windows x64 machine with `MicrosoftPrivateCoreFxNETCoreAppPackageVersion`.

**Log:**
```
===========================================================================================================

C:\dotnetbuild\work\f0c1a15f-48eb-40e9-a2b1-a9a6077cda59\Work\646a12f5-c82f-47bb-aee2-b5f8851693eb\Exec>"C:\dotnetbuild\work\f0c1a15f-48eb-40e9-a2b1-a9a6077cda59\Payload\dotnet.exe" exec --runtimeconfig System.Runtime.Numerics.Tests.runtimeconfig.json xunit.console.dll System.Runtime.Numerics.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\f0c1a15f-48eb-40e9-a2b1-a9a6077cda59\Payload\CoreFX.issues.rsp 
  Discovering: System.Runtime.Numerics.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Numerics.Tests (found 219 of 225 test cases)
  Starting:    System.Runtime.Numerics.Tests (parallel test collections = on, max threads = 2)
    System.Numerics.Tests.ComplexTests.Pow(real: 1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: 1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
  Finished:    System.Runtime.Numerics.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Numerics.Tests  Total: 2086, Errors: 0, Failed: 4, Skipped: 0, Time: 105.001s
----- end Sun 10/20/2019 12:21:42.12 ----- exit code 1 ----------------------------------------------------------
```

**Comment by BruceForstall** [comment]
@tannergooding Would you know about this?

**Comment by tannergooding** [comment]
The produced results look to be as expected and the tests/implementation haven't changed in ~4 years (line numbers are definitely off, however).

I'll see if I can repro locally.

**Comment by tannergooding** [comment]
I've not been able to repro yet.

My best guess is that something about JitStressRegs=3 is causing a bug on the machine in question.

**Comment by VincentBu** [comment]
**Job:**
[coreclr-corefx-jitstressregs #20191027.1 Run Test Pri1 CoreFX Windows_NT x64 checked](https://dev.azure.com/dnceng/public/_build/results?buildId=403701)

**Detail:**
https://helix.dot.net/api/2019-06-17/jobs/f5d8835d-615b-4c9d-bc8d-89e732b466c2/workitems/System.Runtime.Numerics.Tests/console

**OS & Arch:**
windows x64

**Mode:**
COMPlus_TieredCompilation=0
COMPlus_JitStressRegs=3

**Note:**
This failure **repros** on our windows x64 machine.

**Log:**
```
System.Numerics.Tests.ComplexTests.Pow(real: 1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: 1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
  Finished:    System.Runtime.Numerics.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Numerics.Tests  Total: 2086, Errors: 0, Failed: 4, Skipped: 0, Time: 102.024s
----- end Sun 10/27/2019 12:04:30.38 ----- exit code 1
```

**Comment by AriNuer** [comment]
**Job:**
[coreclr-corefx-jitstress2-jitstressregs:20191118.1](https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=430521)

**Details:**
https://helix.dot.net/api/2019-06-17/jobs/8032d567-1bcb-425e-b963-bd45b98d6ced/workitems/System.Runtime.Numerics.Tests/console

**OS & Arch:**
Windows x64

**Mode:**
set COMPlus_TieredCompilation=0
set COMPlus_JitStress=2
set COMPlus_JitStressRegs=3

**Note:**
This failure **repros** on our windows x64 machine.

**Log:**
```
C:\dotnetbuild\work\8032d567-1bcb-425e-b963-bd45b98d6ced\Work\a68d407b-e12a-4374-8dca-eb41b9946680\Exec>"C:\dotnetbuild\work\8032d567-1bcb-425e-b963-bd45b98d6ced\Payload\dotnet.exe" exec --runtimeconfig System.Runtime.Numerics.Tests.runtimeconfig.json xunit.console.dll System.Runtime.Numerics.Tests.dll -xml testResults.xml -nologo -nocolor -notrait category=nonnetcoreapptests -notrait category=nonwindowstests -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing @C:\dotnetbuild\work\8032d567-1bcb-425e-b963-bd45b98d6ced\Payload\CoreFX.issues.rsp 
  Discovering: System.Runtime.Numerics.Tests (method display = ClassAndMethod, method display options = None)
  Discovered:  System.Runtime.Numerics.Tests (found 219 of 225 test cases)
  Starting:    System.Runtime.Numerics.Tests (parallel test collections = on, max threads = 2)
    System.Numerics.Tests.ComplexTests.Pow(real: 1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1.7976931348623157E+308, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1.7976931348623157E+308
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: 1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: 1
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
    System.Numerics.Tests.ComplexTests.Pow(real: -1, imaginary: 0) [FAIL]
      Failure at line 1303. Expected real: 0. Actual real: -1
      Expected: True
      Actual:   False
      Stack Trace:
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1951,0): at System.Numerics.Tests.ComplexTests.VerifyRealImaginaryProperties(Complex complex, Double real, Double imaginary, Int32 lineNumber)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1304,0): at System.Numerics.Tests.ComplexTests.VerifyPow_Complex_Complex(Double realValue, Double imaginaryValue, Double realPower, Double imaginaryPower)
        /_/src/System.Runtime.Numerics/tests/ComplexTests.cs(1275,0): at System.Numerics.Tests.ComplexTests.Pow_Complex_Complex(Double real, Double imaginary)
  Finished:    System.Runtime.Numerics.Tests
=== TEST EXECUTION SUMMARY ===
   System.Runtime.Numerics.Tests  Total: 2086, Errors: 0, Failed: 4, Skipped: 0, Time: 29.877s
----- end Mon 11/18/2019  9:50:39.30 ----- exit code 1 ----------------------------------------------------------
```
