### ISSUE TITLE
GcStress: BoxUnbox tests failed for MixedAllStruct Linux

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2763]
In the following tests:
```
JIT/Directed/nullabletypes/castclassvaluetype_d/castclassvaluetype_d.sh
JIT/Directed/nullabletypes/castclassvaluetype_do/castclassvaluetype_do.sh
JIT/Directed/nullabletypes/castclassvaluetype_r/castclassvaluetype_r.sh
JIT/Directed/nullabletypes/Desktop/boxunboxvaluetype_r/boxunboxvaluetype_r.sh
```
One of the `BoxUnbox` variants in this test fail for `MixedAllStruct`
The failure is not 100% deterministic, but fails most of the time.

```
corerun JIT/Directed/nullabletypes/castclassvaluetype_d/castclassvaluetype_d.exe

--- char? s = Helper.Create(default(char)) ---
--- char? s = null ---
--- char u = Helper.Create(default(char)) ---
--- bool? s = Helper.Create(default(bool)) ---
--- bool? s = null ---
--- bool u = Helper.Create(default(bool)) ---
--- byte? s = Helper.Create(default(byte)) ---
--- byte? s = null ---
--- byte u = Helper.Create(default(byte)) ---
--- sbyte? s = Helper.Create(default(sbyte)) ---
--- sbyte? s = null ---
--- sbyte u = Helper.Create(default(sbyte)) ---
--- short? s = Helper.Create(default(short)) ---
--- short? s = null ---
--- short u = Helper.Create(default(short)) ---
--- ushort? s = Helper.Create(default(ushort)) ---
--- ushort? s = null ---
--- ushort u = Helper.Create(default(ushort)) ---
--- int? s = Helper.Create(default(int)) ---
--- int? s = null ---
--- int u = Helper.Create(default(int)) ---
--- uint? s = Helper.Create(default(uint)) ---
--- uint? s = null ---
--- uint u = Helper.Create(default(uint)) ---
--- long? s = Helper.Create(default(long)) ---
--- long? s = null ---
--- long u = Helper.Create(default(long)) ---
--- ulong? s = Helper.Create(default(ulong)) ---
--- ulong? s = null ---
--- ulong u = Helper.Create(default(ulong)) ---
--- float? s = Helper.Create(default(float)) ---
--- float? s = null ---
--- float u = Helper.Create(default(float)) ---
--- double? s = Helper.Create(default(double)) ---
--- double? s = null ---
--- double u = Helper.Create(default(double)) ---
--- decimal? s = Helper.Create(default(decimal)) ---
--- decimal? s = null ---
--- decimal u = Helper.Create(default(decimal)) ---
--- IntPtr? s = Helper.Create(default(IntPtr)) ---
--- IntPtr? s = null ---
--- IntPtr u = Helper.Create(default(IntPtr)) ---
--- UIntPtr? s = Helper.Create(default(UIntPtr)) ---
--- UIntPtr? s = null ---
--- UIntPtr u = Helper.Create(default(UIntPtr)) ---
--- Guid? s = Helper.Create(default(Guid)) ---
--- Guid? s = null ---
--- Guid u = Helper.Create(default(Guid)) ---
--- GCHandle? s = Helper.Create(default(GCHandle)) ---
--- GCHandle? s = null ---
--- GCHandle u = Helper.Create(default(GCHandle)) ---
--- ByteE? s = Helper.Create(default(ByteE)) ---
--- ByteE? s = null ---
--- ByteE u = Helper.Create(default(ByteE)) ---
--- IntE? s = Helper.Create(default(IntE)) ---
--- IntE? s = null ---
--- IntE u = Helper.Create(default(IntE)) ---
--- LongE? s = Helper.Create(default(LongE)) ---
--- LongE? s = null ---
--- LongE u = Helper.Create(default(LongE)) ---
--- EmptyStruct? s = Helper.Create(default(EmptyStruct)) ---
--- EmptyStruct? s = null ---
--- EmptyStruct u = Helper.Create(default(EmptyStruct)) ---
--- NotEmptyStruct? s = Helper.Create(default(NotEmptyStruct)) ---
--- NotEmptyStruct? s = null ---
--- NotEmptyStruct u = Helper.Create(default(NotEmptyStruct)) ---
--- NotEmptyStructQ? s = Helper.Create(default(NotEmptyStructQ)) ---
--- NotEmptyStructQ? s = null ---
--- NotEmptyStructQ u = Helper.Create(default(NotEmptyStructQ)) ---
--- NotEmptyStructA? s = Helper.Create(default(NotEmptyStructA)) ---
--- NotEmptyStructA? s = null ---
--- NotEmptyStructA u = Helper.Create(default(NotEmptyStructA)) ---
--- NotEmptyStructQA? s = Helper.Create(default(NotEmptyStructQA)) ---
--- NotEmptyStructQA? s = null ---
--- NotEmptyStructQA u = Helper.Create(default(NotEmptyStructQA)) ---
--- EmptyStructGen<int>? s = Helper.Create(default(EmptyStructGen<int>)) ---
--- EmptyStructGen<int>? s = null ---
--- EmptyStructGen<int> u = Helper.Create(default(EmptyStructGen<int>)) ---
--- NotEmptyStructGen<int>? s = Helper.Create(default(NotEmptyStructGen<int>)) ---
--- NotEmptyStructGen<int>? s = null ---
--- NotEmptyStructGen<int> u = Helper.Create(default(NotEmptyStructGen<int>)) ---
--- NotEmptyStructConstrainedGen<int>? s = Helper.Create(default(NotEmptyStructConstrainedGen<int>)) ---
--- NotEmptyStructConstrainedGen<int>? s = null ---
--- NotEmptyStructConstrainedGen<int> u = Helper.Create(default(NotEmptyStructConstrainedGen<int>)) ---
--- NotEmptyStructConstrainedGenA<int>? s = Helper.Create(default(NotEmptyStructConstrainedGenA<int>)) ---
--- NotEmptyStructConstrainedGenA<int>? s = null ---
--- NotEmptyStructConstrainedGenA<int> u = Helper.Create(default(NotEmptyStructConstrainedGenA<int>)) ---
--- NotEmptyStructConstrainedGenQ<int>? s = Helper.Create(default(NotEmptyStructConstrainedGenQ<int>)) ---
--- NotEmptyStructConstrainedGenQ<int>? s = null ---
--- NotEmptyStructConstrainedGenQ<int> u = Helper.Create(default(NotEmptyStructConstrainedGenQ<int>)) ---
--- NotEmptyStructConstrainedGenQA<int>? s = Helper.Create(default(NotEmptyStructConstrainedGenQA<int>)) ---
--- NotEmptyStructConstrainedGenQA<int>? s = null ---
--- NotEmptyStructConstrainedGenQA<int> u = Helper.Create(default(NotEmptyStructConstrainedGenQA<int>)) ---
--- NestedStruct? s = Helper.Create(default(NestedStruct)) ---
--- NestedStruct? s = null ---
--- NestedStruct u = Helper.Create(default(NestedStruct)) ---
--- NestedStructGen<int>? s = Helper.Create(default(NestedStructGen<int>)) ---
--- NestedStructGen<int>? s = null ---
--- NestedStructGen<int> u = Helper.Create(default(NestedStructGen<int>)) ---
--- ExplicitFieldOffsetStruct? s = Helper.Create(default(ExplicitFieldOffsetStruct)) ---
--- ExplicitFieldOffsetStruct? s = null ---
--- ExplicitFieldOffsetStruct u = Helper.Create(default(ExplicitFieldOffsetStruct)) ---
--- MarshalAsStruct? s = Helper.Create(default(MarshalAsStruct)) ---
--- MarshalAsStruct? s = null ---
--- MarshalAsStruct u = Helper.Create(default(MarshalAsStruct)) ---
--- ImplementOneInterface? s = Helper.Create(default(ImplementOneInterface)) ---
--- ImplementOneInterface? s = null ---
--- ImplementOneInterface u = Helper.Create(default(ImplementOneInterface)) ---
--- ImplementTwoInterface? s = Helper.Create(default(ImplementTwoInterface)) ---
--- ImplementTwoInterface? s = null ---
--- ImplementTwoInterface u = Helper.Create(default(ImplementTwoInterface)) ---
--- ImplementOneInterfaceGen<int>? s = Helper.Create(default(ImplementOneInterfaceGen<int>)) ---
--- ImplementOneInterfaceGen<int>? s = null ---
--- ImplementOneInterfaceGen<int> u = Helper.Create(default(ImplementOneInterfaceGen<int>)) ---
--- ImplementTwoInterfaceGen<int>? s = Helper.Create(default(ImplementTwoInterfaceGen<int>)) ---
--- ImplementTwoInterfaceGen<int>? s = null ---
--- ImplementTwoInterfaceGen<int> u = Helper.Create(default(ImplementTwoInterfaceGen<int>)) ---
--- ImplementAllInterface<int>? s = Helper.Create(default(ImplementAllInterface<int>)) ---
--- ImplementAllInterface<int>? s = null ---
--- ImplementAllInterface<int> u = Helper.Create(default(ImplementAllInterface<int>)) ---
--- WithMultipleGCHandleStruct? s = Helper.Create(default(WithMultipleGCHandleStruct)) ---
--- WithMultipleGCHandleStruct? s = null ---
--- WithMultipleGCHandleStruct u = Helper.Create(default(WithMultipleGCHandleStruct)) ---
--- WithOnlyFXTypeStruct? s = Helper.Create(default(WithOnlyFXTypeStruct)) ---
--- WithOnlyFXTypeStruct? s = null ---
--- WithOnlyFXTypeStruct u = Helper.Create(default(WithOnlyFXTypeStruct)) ---
--- MixedAllStruct? s = Helper.Create(default(MixedAllStruct)) ---
--- MixedAllStruct? s = null ---
--- MixedAllStruct u = Helper.Create(default(MixedAllStruct)) ---
Test FAILED

System.Exception: [False]!=[True]: BoxUnboxToNQ
   at Assert.AreEqual(Boolean result, Boolean expected, String comment)
   at NullableTest45.Run()
   at Test.Main()
<Returns 154>

```

Repro steps are:

* cp \scratch2\scratch\swaroops\coredistools\libcoredistools.so somewhere
* export LD_LIBRARY_PATH=somewhere
* export COMPlus_GCStress=0xC
* Run the above test

**Comment by swaroop-sridhar** [comment]
@LLITCHEV This test involves structs.

**Comment by sivarv** [comment]
Taking over from Lubo for investigation.
