### ISSUE TITLE
Build Failed - 80040154 Class not registered (CLSID {B86AE24D-BF2F-4AC9-B5A2-34B14E4CE11D})

### ISSUE THREAD

**Issue by axefrog** [dotnet/coreclr#280]
I'm trying to build CoreCLR on a Windows 8.1 machine. I have VS2010, 2012 and 2013 installed. The first 6 or so minutes of the build goes fine, and then it fails following a COM exception regarding a not-registered class ID.

Here's the first part of the error:

```
daccess.cpp
         Microsoft (R) CLR External Data Access Data Table Generator Version 0.3
         Copyright (C) Microsoft Corp.  All rights reserved.

         BUILDMSG: System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {B86AE24D-BF2F-4AC9-B5A2-34B14E4CE11D} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
            at Dia.Util.DiaFile..ctor(String pdbFile, String dllFile)
            at PdbSymbolProvider..ctor(String symbolFilename, String dllFilename)
            at Shell.DoMain(String[] args)
            at Shell.Main(String[] args)
    19>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073: The command "setlocal\r [D:\DotNetCore\coreclr\binaries\
       CMake\src\dlls\mscoree\coreclr\coreclr.vcxproj]
       C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(132,5): error MSB3073 ...
```

[I've uploaded the full build log here.](https://mega.co.nz/#!ZI0hHDiR!dzGfjbBELouWRDyWm1jhx2YP8cgFGXg1BrIjogh31BU)

Thanks in advance for any pointers in the right direction.

**Comment by axefrog** [comment]
Found some information here, I'm investigating:
https://social.msdn.microsoft.com/Forums/en-US/bcfa59de-5231-4c52-8ca6-534ca3a9f65e/event-source-vsttexecution-comexception-0x80040154-clsid?forum=tfssetup

**Comment by axefrog** [comment]
I guess it would help if I had copied the DIA SDK from VS 11.0 and not 10.0. Consider this issue closed.
