### ISSUE TITLE
[JitStress=1,2] System.Numerics.Vectors.Tests fails with result value mismatch from System.Numerics.Tests.GenericVectorTests.SquareRootUInt16 [FAIL]

### ISSUE THREAD

**Issue by sejongoh** [dotnet/coreclr#2886]
**Configuration**

Linux
Coreclr checked (commit 9593cbbbe4e434b30b9f12ba4c51ad2e57e4247f)
Corefx release (commit 7cac5729f1ac5b65a57f741077e798537f1c7f07)

**Failure**

Pass without any stress option
Fail with JitStress =1 and 2

```
./corerun xunit.console.netcore.exe System.Numerics.Vectors.Tests.dll -xml testResults.xml -notrait category=failing -notrait category=OuterLoop -notrait category=nonlinuxtests -notrait Benchmark=true

xUnit.net console test runner (64-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Numerics.Vectors.Tests
Discovered:  System.Numerics.Vectors.Tests
Starting:    System.Numerics.Vectors.Tests
   System.Numerics.Tests.GenericVectorTests.SquareRootUInt16 [FAIL]
      Assert.Equal() Failure
      Expected: 178
      Actual:   0
      Stack Trace:
            at System.Numerics.Tests.GenericVectorTests.<>c__DisplayClass533_0`1.<TestSquareRoot>b__0(Int32 index, T val)
            at System.Numerics.Tests.GenericVectorTests.ValidateVector[T](Vector`1 vector, Action`2 indexValidationFunc)
            at System.Numerics.Tests.GenericVectorTests.TestSquareRoot[T]()
   System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02 [FAIL]
      Matrix4x4.CreateShadow did not provide expected value.
      Expected: True
      Actual:   False
      Stack Trace:
            at System.Numerics.Tests.Matrix4x4Tests.Matrix4x4CreateShadowTest02()
Finished:    System.Numerics.Vectors.Tests
```

**Comment by erozenfeld** [comment]
@sivarv and I looked at the dumps and it appears to be an LSRA issue. An address-taken shadow variable is getting a register and is not getting spilled. Reassigning to @sivarv to continue the investigation.
