### ISSUE TITLE
GCStress: JitStress: StructsInRegs Test Failed

### ISSUE THREAD

**Issue by swaroop-sridhar** [dotnet/coreclr#2967]
Test3 failed under the following settings:

```
COMPlus_GCStress=0xC
COMPlus_JitStress=2
COMPlus_ZapDisable=1
```

```
corerun JIT/Methodical/structs/systemvbringup/structinregs/structinregs.exe
test1 Result: 3
test2 Result: 3
test3 Result: 3

System.Exception: Failed test3 test!
   at structinreg.Program0.Main1()
   at structinreg.Program.Main()
100
```

**Comment by LLITCHEV** [comment]
NOt reproducing anymore. It is most likely fixed by PR #3351 .
