### ISSUE TITLE
Request for updating linux-instructions.md

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#3002]
I have been trying coreclr+corefx in a bare metal Linux system. (x64 and armv7l)

Anyway, in order to run the HelloWorld.cs of 
https://github.com/dotnet/coreclr/blob/master/Documentation/building/linux-instructions.md
(https://raw.githubusercontent.com/dotnet/corefxlab/master/demos/CoreClrConsoleApplications/HelloWorld/HelloWorld.cs),
we need additional dll files not mentioned in the instruction:
System.Core.dll (4.0.0.0)
System.Collections.dll (4.0.10)
System.Linq.dll (4.0.0.0)

Without them, I get errors such as:

```
bash-3.2# ./corerun HelloWorld.exe linux
Hello, Linux...

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   at System.TermInfo.Database..ctor(String term, Byte[] data)
   at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
   at System.TermInfo.Database.ReadDatabase(String term)
   at System.TermInfo.Database.ReadActiveDatabase()
   at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__28_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.ConsolePal.TerminalFormatStrings.get_Instance()
   at System.ConsolePal.WriteResetColorString()
   at System.ConsolePal.ResetColor()
   at System.Console.ResetColor()
   at Program.DrawLinux()
   at Program.Main(String[] args)
Aborted (core dumped)
bash-3.2#

```

Please add the three dll files in your https://www.myget.org/F/dotnet-corefx/ repository and update packages.config in the instruction accordingly.

MyungJoo

**Comment by sergiy-k** [comment]
@stephentoub, I'm curious why we need System.Linq.dll to run a HelloWord app?

**Comment by stephentoub** [comment]
> I'm curious why we need System.Linq.dll to run a HelloWord app?

It shouldn't.  I'll fix it.  Looks like the dependency snuck in.

**Comment by stephentoub** [comment]
Fixed: https://github.com/dotnet/corefx/pull/5870

**Comment by myungjoo** [comment]
Uh.. does it fix System.Core, System.Collection as well? (or are you updating the instruction document accordingly?)

**Comment by stephentoub** [comment]
Sorry, GitHub closed the bug when I referenced it.

System.Core doesn't exist in coreclr/corefx, so it's not required.  Where are you seeing it that you believe it is required?

I've added System.Collections to the list.

**Comment by myungjoo** [comment]
It was from the same HelloWorld.cs compiled by mcs as described in the linux-insturction.

It first said "System.Core" was missing.
So, I've added System.Core.dll from mono (yes, I've just find it from my Ubuntu machine and put it where the runtime is, in my barebone Linux emulator (chroot'ed))

Then, corerun HelloWorld.exe said that it requires System.Collection. So, I've put it from nuget that time.

Then, corerun HelloWorld.exe linux said that it requires System.Linq. When I've put it there with nuget, it stopped complaining and shows the penguin.

If you need more (the output from console), I'll probably be able to capture it tomorrow (due to moving today, I'll need to setup the machines tomorrow.)

**Comment by myungjoo** [comment]
Here goes the original execution log, which shows that System.Core was also required for the HelloWorld.cs

'
bash-3.2# mkdir backup
bash-3.2# mv System.Core.dll System.Collections.dll System.Linq.dll backup/
bash-3.2# ./corerun HelloWorld.exe  linux
Hello, Linux...

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' or one of its dependencies. The system cannot find the file specified.

   at System.Console.get_IsOutputRedirected()
   at System.ConsolePal.WriteResetColorString()
   at System.ConsolePal.ResetColor()
   at System.Console.ResetColor()
   at Program.DrawLinux()
   at Program.Main(String[] args)
Aborted (core dumped)
bash-3.2# cp backup/System.Core.dll .
bash-3.2# ./corerun HelloWorld.exe  linux
Hello, Linux...

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Collections, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   at System.TermInfo.Database..ctor(String term, Byte[] data)
   at System.TermInfo.Database.ReadDatabase(String term, String directoryPath)
   at System.TermInfo.Database.ReadDatabase(String term)
   at System.TermInfo.Database.ReadActiveDatabase()
   at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__28_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.ConsolePal.TerminalFormatStrings.get_Instance()
   at System.ConsolePal.WriteResetColorString()
   at System.ConsolePal.ResetColor()
   at System.Console.ResetColor()
   at Program.DrawLinux()
   at Program.Main(String[] args)
Aborted (core dumped)
bash-3.2# cp backup/System.Collections.dll .
bash-3.2# ./corerun HelloWorld.exe  linux
Hello, Linux...

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   at System.ConsolePal.TerminalFormatStrings..ctor(Database db)
   at System.ConsolePal.TerminalFormatStrings.<>c.<.cctor>b__28_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.ConsolePal.TerminalFormatStrings.get_Instance()
   at System.ConsolePal.WriteResetColorString()
   at System.ConsolePal.ResetColor()
   at System.Console.ResetColor()
   at Program.DrawLinux()
   at Program.Main(String[] args)
Aborted (core dumped)
bash-3.2# cp backup/System.Linq.dll .
bash-3.2# ./corerun HelloWorld.exe  linux
Hello, Linux...

'
