### ISSUE TITLE
ARM/Linux infinite looping with exception handling

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#3859]
We've found another case of infinite loops (GDB tracking: https://github.com/myungjoo/coreclr/issues/3 )
related with src/vm/exceptionhandling.cpp:UnwindManagedExceptionPass1()'s while loop at line 4590, where somehow controlPc directs a dangling stack which cannot be unwinded anymore and still is a unmanaged frame according to IsManagedCode(), which incurs infinitely looping inside the while loop.

Maybe we can workaround that by checking if the "previous" controlPC == "current" controlPC in the loop; however, before that, I'd like to know how it has reached there first.

**Comment by janvorli** [comment]
@myungjoo if I can see it correctly from your GDB log, the issue happens when we have unwound past some managed frames, hit the first native frame (PC=0xb655803d) and then try to use native unwinder to unwind from that position to a next frame, where we get PC=0xb6d5f000 and we cannot move out of that frame. Am I correct?
I would recommend checking if those two native PC addresses are valid (try disassembling the methods at those addresses, see if the PC addresses are after calls).
To debug the issue further, I would dump PC, SP and LR from the frameContext each time when we hit source lines 4557 and 4601 (right after each unwind) so that we can see how the managed and native frames are being unwound and where the values deviate from the expected ones.

Btw, the last frameContext you have printed - the first managed frame the UnwindManagedExceptionPass1 gets - seems to have strange LR value - LR is 0xb1c8ea19 and PC is 0xb1c8ea18.

I don't think we can use the workaround you've suggested. If we fail to move to a next frame, it is a fatal issue (unless the frame was the bottom of the stack).

**Comment by myungjoo** [comment]
@janvorli Thanks for the advice. I'll track the unwinding instance from the start for the broken case and verify if it's passing through managed frames. Right now, I see some probability that this is causing #3856 as well in case of some exceptions (#3309 seems to be resolved partially; there are still exceptions not properly resolved although my test cases of that time passed) 

For other two comments:
- In GDB tracking, LR appears to be almost always PC+1. It was mind boggling, but GDB/ARM shows such behaviours with other native binaries as well.
- Although that might not be a workaround for the problem, we may still need to say "I'm dead" and quit if such indefinite loops happen.

Now, I start to understand why Android forked and why my colleagues had tried that hard not to use libunwind for the toolchains. Maybe, I'll need to try Android-libunwind for coreclr as well later as it has a lot of updates for ARM even including fixes that I've been locally testing.

**Comment by myungjoo** [comment]
It appears that  `while (!ExecutionManager::IsManagedCode(controlPc))` of `VOID DECLSPEC_NORETURN UnwindManagedExceptionPass1(...)` is keep unwinding through all stack frames. I may get more useful data by extracting additional log from the front part of UnwindManagedExceptionPass1(). 

```
sh-3.2# ./corerun csc.exe
Potentionally Going to be ****ed.Arg_MethodAccessException
You are at Exception's Init()
Message:Attempt to access the method failed.
1 
2 
MSGAttempt to access the method failed.
SRC
I'm at MethodAccessException.cs...
exceptionhandling.cpp: PC b644e52f SP beb1cd10 ==> 
exceptionhandling.cpp: ==> PC b6317ac0 SP beb1cd20 
exceptionhandling.cpp: PC b6317ac0 SP beb1cd20 ==> 
exceptionhandling.cpp: ==> PC b6317964 SP beb1d140 
exceptionhandling.cpp: PC b6317964 SP beb1d140 ==> 
exceptionhandling.cpp: ==> PC b63188c6 SP beb1d198 
exceptionhandling.cpp: PC b63188c6 SP beb1d198 ==> 
exceptionhandling.cpp: ==> PC b62de100 SP beb1d388 
exceptionhandling.cpp: PC b62de100 SP beb1d388 ==> 
exceptionhandling.cpp: ==> PC b647bae8 SP beb1d3e0 
exceptionhandling.cpp: PC b647bae8 SP beb1d3e0 ==> 
exceptionhandling.cpp: ==> PC b6479aae SP beb1d4f8 
exceptionhandling.cpp: PC b6479aae SP beb1d4f8 ==> 
exceptionhandling.cpp: ==> PC b6479980 SP beb1d550 
exceptionhandling.cpp: PC b6479980 SP beb1d550 ==> 
exceptionhandling.cpp: ==> PC b6479c46 SP beb1d600 
exceptionhandling.cpp: PC b6479c46 SP beb1d600 ==> 
exceptionhandling.cpp: ==> PC b6206d38 SP beb1d8c0 
exceptionhandling.cpp: PC b6206d38 SP beb1d8c0 ==> 
exceptionhandling.cpp: ==> PC b61d3d38 SP beb1da20 
exceptionhandling.cpp: PC b61d3d38 SP beb1da20 ==> 
exceptionhandling.cpp: ==> PC 00013d04 SP beb1dad8 
exceptionhandling.cpp: PC 00013d04 SP beb1dad8 ==> 
exceptionhandling.cpp: ==> PC 00013382 SP beb1dc28 
exceptionhandling.cpp: PC 00013382 SP beb1dc28 ==> 
exceptionhandling.cpp: ==> PC 00013430 SP beb1dd00 
exceptionhandling.cpp: PC 00013430 SP beb1dd00 ==> 
exceptionhandling.cpp: ==> PC b6ca3236 SP beb1dd20 
exceptionhandling.cpp: PC b6ca3236 SP beb1dd20 ==> 
exceptionhandling.cpp: ==> PC 00012f54 SP beb1de68 
exceptionhandling.cpp: PC 00012f54 SP beb1de68 ==> 
exceptionhandling.cpp: ==> PC 00012f54 SP beb1de68 
exceptionhandling.cpp: PC 00012f54 SP beb1de68 ==> 
exceptionhandling.cpp: ==> PC 00012f54 SP beb1de68 
exceptionhandling.cpp: PC 00012f54 SP beb1de68 ==> 
exceptionhandling.cpp: ==> PC 00012f54 SP beb1de68 
exceptionhandling.cpp: PC 00012f54 SP beb1de68 ==> 
exceptionhandling.cpp: ==> PC 00012f54 SP beb1de68 
exceptionhandling.cpp: PC 00012f54 SP beb1de68 ==> 
exceptionhandling.cpp: ==> PC 00012f54 SP beb1de68 
exceptionhandling.cpp: PC 00012f54 SP beb1de68 ==> 
exceptionhandling.cpp: ==> PC 00012f54 SP beb1de68 
exceptionhandling.cpp: PC 00012f54 SP beb1de68 ==> 
```

Note that 0x12f54 is THE "_start()".
```
(gdb) x/i 0x00012f54
   0x12f54 <_start+32>:	blx	0x12cd8 <abort@plt>

```


More debugging data will follow soon.

**Comment by myungjoo** [comment]
Adding the front part of the function `VOID DECLSPEC_NORETURN UnwindManagedExceptionPass1(...)`


```
PAL_VU: PC,SP(b698e453,beefb438) ==>(b698e3d2,beefb608) R1 (S0)
PAL_VU: PC,SP(b698e3d2,beefb608) ==>(b61e5b5a,beefb6e8) R1 (S0)
PAL_VU: PC,SP(b6406c17,beefb728) ==>(b63584dc,beefb940) R1 (S0)
PAL_VU: PC,SP(b63584dc,beefb940) ==>(b450ced8,beefbcb8) R1 (S0)
```
Now we are at the first managed frame `(b450ced8,beefbcb8)`

```
exceptionhandling.cpp: PC b450ced8 SP beefbcb8 (STARTS / M1)
```
`UnwindManagedExceptionPass1()`'s given frame is managed (M1)

In the loop of `while (!ExecutionManager::IsManagedCode(controlPc))`, the first given frame is
native and from that point all frames are managed.

```
PAL_VU: PC,SP(b63582e7,beefb940) ==>(b450ced8,beefbcb8) R1 (S0)
exceptionhandling.cpp: PC b6419563 SP beefbd10 ==> PAL_VU 
PAL_VU: PC,SP(b6419563,beefbd10) ==>(b62e2ac0,beefbd20) R1 (S0)
...
PAL_VU: PC,SP(00012f54,beefce68) ==>(00012f54,beefce68) R0 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00012f54 SP beefce68 
exceptionhandling.cpp: PC 00012f54 SP beefce68 ==> PAL_VU 
PAL_VU: PC,SP(00012f54,beefce68) ==>(00012f54,beefce68) R0 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00012f54 SP beefce68 
exceptionhandling.cpp: PC 00012f54 SP beefce68 ==> PAL_VU 
PAL_VU: PC,SP(00012f54,beefce68) ==>(00012f54,beefce68) R0 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00012f54 SP beefce68 
exceptionhandling.cpp: PC 00012f54 SP beefce68 ==> PAL_VU 
PAL_VU: PC,SP(00012f54,beefce68) ==>(00012f54,beefce68) R0 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00012f54 SP beefce68 
exceptionhandling.cpp: PC 00012f54 SP beefce68 ==> PAL_VU 
PAL_VU: PC,SP(00012f54,beefce68) ==>(00012f54,beefce68) R0 (S0)
```


Thus, the code before reaching the loop somehow skips all the managed frames not leaving any managed frame behind for the loop. So it is probably unwinding too much before going into the loop or the frames are not in the assumed shape. (it seems the given frames are: [top] [1. native] [2. managed] [3. native] [bottom]; if you try to find managed after unwinding all of 2., you will not be able to find one.)

**Comment by myungjoo** [comment]
Ok. Here goes the full stack traversing log with UnwindManagedExceptionPass1()

```
I'm at MethodAccessException.cs...
PAL_VU: PC,SP(b69b159b,bee71438) ==>(b69b151a,bee71608) R1 (S0)
PAL_VU: PC,SP(b69b151a,bee71608) ==>(b6208b5a,bee716e8) R1 (S0)
PAL_VU: PC,SP(b6429ccf,bee71728) ==>(b637b4dc,bee71940) R1 (S0)
PAL_VU: PC,SP(b637b4dc,bee71940) ==>(b1b13ed8,bee71cb8) R1 (S0)
UnwindManagedExceptionPass1:4511: PC b1b13ed8 SP bee71cb8 (STARTS / M1)
UnwindManagedExceptionPass1:4544 PC,SP(b1b13ed8,bee71cb8)M1 ==> RtlVU (L4554) RtlVU ==> PC,SP(b1b12ba9,bee71ce8)M1
PAL_VU: PC,SP(b637b2e8,bee71940) ==>(b1b13ed8,bee71cb8) R1 (S0)
UnwindManagedExceptionPass1:4544 PC,SP(b1b12ba9,bee71ce8)M1 ==> RtlVU (L4554) RtlVU ==> PC,SP(b1b1246b,bee71d08)M1
UnwindManagedExceptionPass1:4544 PC,SP(b1b1246b,bee71d08)M1 ==> RtlVU (L4554) RtlVU ==> PC,SP(b643c61b,bee71d10)M0
UnwindManagedExceptionPass1:4603: PC b643c61b SP bee71d10 ==> PAL_VU 
PAL_VU: PC,SP(b643c61b,bee71d10) ==>(b6305ac0,bee71d20) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6305ac0 SP bee71d20 
UnwindManagedExceptionPass1:4603: PC b6305ac0 SP bee71d20 ==> PAL_VU 
PAL_VU: PC,SP(b6305ac0,bee71d20) ==>(b6305964,bee72140) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6305964 SP bee72140 
UnwindManagedExceptionPass1:4603: PC b6305964 SP bee72140 ==> PAL_VU 
PAL_VU: PC,SP(b6305964,bee72140) ==>(b63068c6,bee72198) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b63068c6 SP bee72198 
UnwindManagedExceptionPass1:4603: PC b63068c6 SP bee72198 ==> PAL_VU 
PAL_VU: PC,SP(b63068c6,bee72198) ==>(b62cc100,bee72388) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b62cc100 SP bee72388 
UnwindManagedExceptionPass1:4603: PC b62cc100 SP bee72388 ==> PAL_VU 
PAL_VU: PC,SP(b62cc100,bee72388) ==>(b6469bd8,bee723e0) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6469bd8 SP bee723e0 
UnwindManagedExceptionPass1:4603: PC b6469bd8 SP bee723e0 ==> PAL_VU 
PAL_VU: PC,SP(b6469bd8,bee723e0) ==>(b6467b9e,bee724f8) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6467b9e SP bee724f8 
UnwindManagedExceptionPass1:4603: PC b6467b9e SP bee724f8 ==> PAL_VU 
PAL_VU: PC,SP(b6467b9e,bee724f8) ==>(b6467a70,bee72550) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6467a70 SP bee72550 
UnwindManagedExceptionPass1:4603: PC b6467a70 SP bee72550 ==> PAL_VU 
PAL_VU: PC,SP(b6467a70,bee72550) ==>(b6467d36,bee72600) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6467d36 SP bee72600 
UnwindManagedExceptionPass1:4603: PC b6467d36 SP bee72600 ==> PAL_VU 
PAL_VU: PC,SP(b6467d36,bee72600) ==>(b61f4d38,bee728c0) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b61f4d38 SP bee728c0 
UnwindManagedExceptionPass1:4603: PC b61f4d38 SP bee728c0 ==> PAL_VU 
PAL_VU: PC,SP(b61f4d38,bee728c0) ==>(b61c1d38,bee72a20) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b61c1d38 SP bee72a20 
UnwindManagedExceptionPass1:4603: PC b61c1d38 SP bee72a20 ==> PAL_VU 
PAL_VU: PC,SP(b61c1d38,bee72a20) ==>(00013d04,bee72ad8) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00013d04 SP bee72ad8 
UnwindManagedExceptionPass1:4603: PC 00013d04 SP bee72ad8 ==> PAL_VU 
PAL_VU: PC,SP(00013d04,bee72ad8) ==>(00013382,bee72c28) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00013382 SP bee72c28 
UnwindManagedExceptionPass1:4603: PC 00013382 SP bee72c28 ==> PAL_VU 
PAL_VU: PC,SP(00013382,bee72c28) ==>(00013430,bee72d00) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00013430 SP bee72d00 
UnwindManagedExceptionPass1:4603: PC 00013430 SP bee72d00 ==> PAL_VU 
PAL_VU: PC,SP(00013430,bee72d00) ==>(b6c91236,bee72d20) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6c91236 SP bee72d20 
UnwindManagedExceptionPass1:4603: PC b6c91236 SP bee72d20 ==> PAL_VU 
PAL_VU: PC,SP(b6c91236,bee72d20) ==>(00012f54,bee72e68) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00012f54 SP bee72e68 
UnwindManagedExceptionPass1:4603: PC 00012f54 SP bee72e68 ==> PAL_VU 
PAL_VU: PC,SP(00012f54,bee72e68) ==>(00012f54,bee72e68) R0 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00012f54 SP bee72e68 
Breaking because of possible infinite loop.
Segmentation fault (core dumped)
```


So after reaching to the first managed frame (0xb1b13ed8, 0xbee71cb8), UnwindManagedExceptionPass1 starts traversing managed frames (PC 0xb1b13ed8 ... PC 0xb1b1246b).
Then, from the next frames (PC 0xb643c61b ... to the bottom) are ALL native frames, which
inevitably let us loop indefinitely.


However, this UnwindManagedExceptionPass1 is usually meant to be the last place for a process
exiting to the shell; thus, would this be fine? (the one `if (savedPC == controlPC)`) As long as we are meant to be exit here, it seems it is normal to exit when we hit the bottom. (as commented, ultimately, we may need PAL_VirtualUnwind to give some notification that it hit the bottom)

```
        // Check whether we are crossing managed-to-native boundary
        while (!ExecutionManager::IsManagedCode(controlPc))
        {
            UINT_PTR sp = GetSP(frameContext);
            UINT_PTR savedPC = controlPc;

            printf("%s:%d: PC %8.8x SP %8.8x ==> PAL_VU \n", __func__, __LINE__,
                controlPc, sp);
            BOOL success = PAL_VirtualUnwind(frameContext, NULL);
            if (!success)
            {
                _ASSERTE(!"UnwindManagedExceptionPass1: PAL_VirtualUnwind failed");
                EEPOLICY_HANDLE_FATAL_ERROR(COR_E_EXECUTIONENGINE);
            }

            controlPc = GetIP(frameContext);

            printf("exceptionhandling.cpp: PAL_VU ==> PC %8.8x SP %8.8x \n",
                controlPc, GetSP(frameContext));

            // Better Approach: make PAL_VirtualUnwind notify us
            // that we have reached the bottom.
            if (savedPC == controlPc) {
                printf("Breaking because of possible infinite loop.\n");
                TerminateProcess(GetCurrentProcess(), 1);
                UNREACHABLE();
            }

```

**Comment by myungjoo** [comment]
The value of "disposition" in UnwindManagedExceptionPass1 after calling ProcessCLRException() has 0x0 for all the three instances in the above case.

(StackFrame() is not working for this exception :(  ). will continue tomorrow :)

**Comment by janvorli** [comment]
@myungjoo Looking at the trace, it looks like everything is going correctly. Since the UnwindManagedExceptionPass1 starts at the first managed frame, it unwinds all the managed frames and then there are no more managed frames present, which is expected - these are frames from start upto the point when the managed code is started. I can see the same number of native frames on x64.
So the issue is really that the native unwinder doesn't indicate that it was passed the stack bottom frame. We actually have the same problem on OSX, FreeBSD and ARM64 and it is handled in the PAL_VirtualUnwind implementation. So all you need to do to fix the problem is to change three `#if defined(__APPLE__) || defined(__FreeBSD__) || defined(_ARM64_)` to include `|| defined(ARM).

**Comment by janvorli** [comment]
I've forgotten to say that this way of stack unwinding is expected in case of an unhandled exception. If the exception in your test is supposed to be handled, then there is a problem in finding the catch handler. 
In case unhandled exception is not expected, can you share the source code of your test?

**Comment by myungjoo** [comment]
@janvori Thanks! It resolves the issue like a charm! One unfortunate thing is that this confirms #3856 (LR in the stack overwritten) is orthogonal to this one. I'll clean up and send PR soon.


LOG After Fix:
```
sh-3.2# ./corerun csc.exe
You are at Exception's Init()
Message:Attempt to access the method failed.
1 
2 
MSGAttempt to access the method failed.
SRC
I'm at MethodAccessException.cs...
PAL_VU: PC,SP(b6a826c7,bea56438) ==>(b6a82646,bea56608) R1 (S0)
PAL_VU: PC,SP(b6a82646,bea56608) ==>(b62d9b5a,bea566e8) R1 (S0)
PAL_VU: PC,SP(b64fadbb,bea56728) ==>(b644c4dc,bea56940) R1 (S0)
PAL_VU: PC,SP(b644c4dc,bea56940) ==>(b1ae3ed8,bea56cb8) R1 (S0)
UnwindManagedExceptionPass1:4513: PC b1ae3ed8 SP bea56cb8 (STARTS / M1)
UnwindManagedExceptionPass1:4546 PC,SP(b1ae3ed8,bea56cb8)M1 ==> RtlVU (L4556) RtlVU ==> PC,SP(b1ae2ba9,bea56ce8)M1
PAL_VU: PC,SP(b644c2e8,bea56940) ==>(b1ae3ed8,bea56cb8) R1 (S0)
UnwindManagedExceptionPass1:4578 00000000
UnwindManagedExceptionPass1:4546 PC,SP(b1ae2ba9,bea56ce8)M1 ==> RtlVU (L4556) RtlVU ==> PC,SP(b1ae246b,bea56d08)M1
UnwindManagedExceptionPass1:4578 00000000
UnwindManagedExceptionPass1:4546 PC,SP(b1ae246b,bea56d08)M1 ==> RtlVU (L4556) RtlVU ==> PC,SP(b650d707,bea56d10)M0
UnwindManagedExceptionPass1:4578 00000000
UnwindManagedExceptionPass1:4608: PC b650d707 SP bea56d10 ==> PAL_VU 
PAL_VU: PC,SP(b650d707,bea56d10) ==>(b63d6ac0,bea56d20) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b63d6ac0 SP bea56d20 
UnwindManagedExceptionPass1:4608: PC b63d6ac0 SP bea56d20 ==> PAL_VU 
PAL_VU: PC,SP(b63d6ac0,bea56d20) ==>(b63d6964,bea57140) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b63d6964 SP bea57140 
UnwindManagedExceptionPass1:4608: PC b63d6964 SP bea57140 ==> PAL_VU 
PAL_VU: PC,SP(b63d6964,bea57140) ==>(b63d78c6,bea57198) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b63d78c6 SP bea57198 
UnwindManagedExceptionPass1:4608: PC b63d78c6 SP bea57198 ==> PAL_VU 
PAL_VU: PC,SP(b63d78c6,bea57198) ==>(b639d100,bea57388) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b639d100 SP bea57388 
UnwindManagedExceptionPass1:4608: PC b639d100 SP bea57388 ==> PAL_VU 
PAL_VU: PC,SP(b639d100,bea57388) ==>(b653acb8,bea573e0) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b653acb8 SP bea573e0 
UnwindManagedExceptionPass1:4608: PC b653acb8 SP bea573e0 ==> PAL_VU 
PAL_VU: PC,SP(b653acb8,bea573e0) ==>(b6538c7e,bea574f8) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6538c7e SP bea574f8 
UnwindManagedExceptionPass1:4608: PC b6538c7e SP bea574f8 ==> PAL_VU 
PAL_VU: PC,SP(b6538c7e,bea574f8) ==>(b6538b50,bea57550) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6538b50 SP bea57550 
UnwindManagedExceptionPass1:4608: PC b6538b50 SP bea57550 ==> PAL_VU 
PAL_VU: PC,SP(b6538b50,bea57550) ==>(b6538e16,bea57600) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6538e16 SP bea57600 
UnwindManagedExceptionPass1:4608: PC b6538e16 SP bea57600 ==> PAL_VU 
PAL_VU: PC,SP(b6538e16,bea57600) ==>(b62c5d38,bea578c0) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b62c5d38 SP bea578c0 
UnwindManagedExceptionPass1:4608: PC b62c5d38 SP bea578c0 ==> PAL_VU 
PAL_VU: PC,SP(b62c5d38,bea578c0) ==>(b6292d38,bea57a20) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6292d38 SP bea57a20 
UnwindManagedExceptionPass1:4608: PC b6292d38 SP bea57a20 ==> PAL_VU 
PAL_VU: PC,SP(b6292d38,bea57a20) ==>(00013d04,bea57ad8) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00013d04 SP bea57ad8 
UnwindManagedExceptionPass1:4608: PC 00013d04 SP bea57ad8 ==> PAL_VU 
PAL_VU: PC,SP(00013d04,bea57ad8) ==>(00013382,bea57c28) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00013382 SP bea57c28 
UnwindManagedExceptionPass1:4608: PC 00013382 SP bea57c28 ==> PAL_VU 
PAL_VU: PC,SP(00013382,bea57c28) ==>(00013430,bea57d00) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00013430 SP bea57d00 
UnwindManagedExceptionPass1:4608: PC 00013430 SP bea57d00 ==> PAL_VU 
PAL_VU: PC,SP(00013430,bea57d00) ==>(b6d62236,bea57d20) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC b6d62236 SP bea57d20 
UnwindManagedExceptionPass1:4608: PC b6d62236 SP bea57d20 ==> PAL_VU 
PAL_VU: PC,SP(b6d62236,bea57d20) ==>(00012f54,bea57e68) R1 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00012f54 SP bea57e68 
UnwindManagedExceptionPass1:4608: PC 00012f54 SP bea57e68 ==> PAL_VU 
PAL_VU: PC,SP(00012f54,bea57e68) ==>(00000000,bea57e68) R0 (S0)
exceptionhandling.cpp: PAL_VU ==> PC 00000000 SP bea57e68 

Unhandled Exception: Potentionally Going to be Fucked.Word_At
Potentionally Going to be Fucked.StackTrace_InFileLineNumber
System.MethodAccessException: Attempt by method 'Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(System.Collections.Generic.IEnumerable`1<System.String>, System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.CommandLine.RequestLanguage, Microsoft.CodeAnalysis.CommandLine.CompileFunc, Microsoft.CodeAnalysis.IAnalyzerAssemblyLoader)' to access method 'System.IO.Directory.GetCurrentDirectory()' failed.
   at Microsoft.CodeAnalysis.CommandLine.DesktopBuildClient.Run(IEnumerable`1 arguments, IEnumerable`1 extraArguments, RequestLanguage language, CompileFunc compileFunc, IAnalyzerAssemblyLoader analyzerAssemblyLoader)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args, String[] extraArgs)
   at Microsoft.CodeAnalysis.CSharp.CommandLine.Program.Main(String[] args)
Aborted (core dumped)

```
