### ISSUE TITLE
Various Interop Failures

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/coreclr#3940]
Repro steps:

1) Build.cmd Release x86 skiptests
2) Download the latest build of runtimes.Win7-x86.Microsoft.NETCore.Runtime.CoreCLR packageand replace the contents of bin\product\WindowsNT.x86_Release with the package contents.
2) tests\buildtest.cmd Release x86 priority 1
3) tests\runtest.cmd x86Release

Interop._ArrayMarshalling_BoolArray_MarshalBoolArrayTest_MarshalBoolArrayTest_._ArrayMarshalling_BoolArray_MarshalBoolArrayTest_MarshalBoolArrayTest_cmd
\nUnhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.\r\n   at MarshalBoolArray.DoCallBackIn(CallBackIn callback)\r\n   at MarshalBoolArray.Main()\ncmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Interop\ArrayMarshalling\BoolArray\MarshalBoolArrayTest\MarshalBoolArrayTest.cmd Timed Out\r\n\n\nReturn code:      -100\nRaw output file:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Reports\Interop\ArrayMarshalling\BoolArray\MarshalBoolArrayTest\MarshalBoolArrayTest.output.txt\nRaw output:\nBEGIN EXECUTION\r\n "C:\Github\gkhanna79\coreclr\tests\..\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\corerun.exe" MarshalBoolArrayTest.exe  \r\ncmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Interop\ArrayMarshalling\BoolArray\MarshalBoolArrayTest\MarshalBoolArrayTest.cmd Timed Out\r\nTest Harness Exitcode is : -100\r\n\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Interop\ArrayMarshalling\BoolArray\MarshalBoolArrayTest\MarshalBoolArrayTest.cmd\n\r\nExpected: True\r\nActual:   False
   at Interop._ArrayMarshalling_BoolArray_MarshalBoolArrayTest_MarshalBoolArrayTest_._ArrayMarshalling_BoolArray_MarshalBoolArrayTest_MarshalBoolArrayTest_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x86_Release\Interop\Interop.XUnitWrapper.cs:line 105
1801.5650103s ✘  Interop._ICastable_Castable_Castable_._ICastable_Castable_Castable_cmd
cmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Interop\ICastable\Castable\Castable.cmd Timed Out\r\n\n\nReturn code:      -100\nRaw output file:      C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Reports\Interop\ICastable\Castable\Castable.output.txt\nRaw output:\nBEGIN EXECUTION\r\n "C:\Github\gkhanna79\coreclr\tests\..\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\corerun.exe" Castable.exe  \r\ncmdLine:C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Interop\ICastable\Castable\Castable.cmd Timed Out\r\nTest Harness Exitcode is : -100\r\n\nTo run the test:\n> set CORE_ROOT=C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Tests\Core_Root\n> C:\Github\gkhanna79\coreclr\bin\tests\Windows_NT.x86.Release\Interop\ICastable\Castable\Castable.cmd\n\r\nExpected: True\r\nActual:   False
   at Interop._ICastable_Castable_Castable_._ICastable_Castable_Castable_cmd() in C:\Github\gkhanna79\coreclr\tests\src\TestWrappers_x86_Release\Interop\Interop.XUnitWrapper.cs:line 243

**Comment by gkhanna79** [comment]
Also fail under GCStress:

Repro steps:

1) Build.cmd Release x86 skiptests
2) Download the latest build of runtimes.Win7-x86.Microsoft.NETCore.Runtime.CoreCLR packageand replace the contents of bin\product\WindowsNT.x86_Release with the package contents.
2) tests\buildtest.cmd Release x86 priority 1 gcstresslevel 15
3) tests\runtest.cmd x86Release
