### ISSUE TITLE
System.IntPtr(long) constructor throws overflow

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#4062]
The current .NET Framework on Windows and CoreCLR have the following implementation for System.IntPtr(long):

```
public unsafe IntPtr(long value)
{
    #if WIN32
        m_value = (void *)checked((int)value);
    #else
        m_value = (void *)value;
    #endif
}
```

This is quite unfortunate on 32-bit platforms because if you get a pointer value as a long which has the higher bit set, it will always throw an overflow exception.

To reproduce:

```
IntPtr ptr = new IntPtr(0x80000000);
```

The code should have been:

```
public unsafe IntPtr(long value)
{
    #if WIN32
        m_value = (void *)checked((uint)value);
    #else
        m_value = (void *)value;
    #endif
}
```

since we only care that the higher 32-bits of the long parameter are all zeros.

**Comment by manu-silicon** [comment]
Actually my proposed fix is not that correct since if a long is negative, the case would always fail. So we should have something like:
```
if (value < 0) {
    m_value = (void *)checked((int) value);
else
    m_value = (void*)checked((uint) value);
end
```

**Comment by Janiels** [comment]
I think that change would be a bit unfortunate. Consider:
```csharp
const long val1 = -1;
const long val2 = 0xffffffff;
bool b1 = val1 == val2; // false
bool b2 = new IntPtr(val1) == new IntPtr(val2); // true on 32-bit, false on 64-bit
```

I think it's the naming of the type that is problematic -- `IntPtr` really represents an integer of native size, but it is documented and named as if it represents a pointer. As a native integer the current behavior makes perfect sense.
The problem then arises from shoehorning a pointer into a native integer and the native integer being called `IntPtr`. A better fit would be to use `UIntPtr` when representing pointers but that type is not CLS compatible and unused in all of the BCL.

**Comment by manu-silicon** [comment]
@Janiels The current behavior makes it hard to write portable code between 32 and 64-bit platforms without any kind of runtime conditional. We used long to be able to represent an address on any platforms, but got bitten by this overflow check.

Also when you write 0xFFFFFFFF by itself assigned to a long, this is just an abbreviation for 0x00000000FFFFFFFF and I'm not surprised that the answer for comparing IntPtr(val1) and IntPtr(val2) is not the same depending on the platform. What is surprising is that if you only use the lower 32-bit of a long, you get a violation.

**Comment by manu-silicon** [comment]
This seems to be a blocking factor for Linux 32-bit platforms, as shown while testing the ARM 32-bit port:

```
FAILED   - GC/API/GC/Collect_Forced_1/Collect_Forced_1.sh
               BEGIN EXECUTION
               /home/ubuntu/local/Microsoft/tests/Tests/coreoverlay/corerun Collect_Forced_1.exe 0

               Unhandled Exception: System.OverflowException: Arithmetic operation resulted in an overflow.
                  at System.IntPtr.op_Explicit(Int64 value)
                  at System.Diagnostics.ProcessManager.CreateProcessInfo(ParsedStat procFsStat, ReusableTextReader reusableReader)
                  at System.Diagnostics.ProcessManager.CreateProcessInfo(Int32 pid, ReusableTextReader reusableReader)
                  at System.Diagnostics.ProcessManager.GetProcessInfo(Int32 processId, String machineName)
                  at System.Diagnostics.Process.EnsureState(State state)
                  at System.Diagnostics.Process.get_ProcessName()
                  at DefaultCollect.Main(String[] args)
               ./Collect_Forced_1.sh: line 62:  1069 Aborted                 $_DebuggerFullPath "$CORE_ROOT/corerun" Collect_Forced_1.exe $CLRTestExecutionArguments $Host_Args
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

Indeed in the ProcessManager class for Linux, the following line appears and it crashes because the address is of the form 0xbxxxxxxx:

```
                            _startAddress = (IntPtr)stat.startstack,
```
.

**Comment by Janiels** [comment]
It's only surprising because `IntPtr` is documented as if it represents a pointer. In reality it represents a signed integer of native size, and the long value `0xffffffff` cannot fit in a 32-bit signed integer.
I think your change would be surpising in the fact that `new IntPtr(0xffffffff)` would represent `-1` on 32-bit platforms and `0xffffffff` on 64-bit platforms.

I would also argue the bug is in `ProcessManager.CreateProcessInfo` rather than `IntPtr`. The correct way to represent pointers with `IntPtr` would be with `_startAddress = (IntPtr)(void*)stat.startsttack`, which does not have this issue at all.

**Comment by manu-silicon** [comment]
If you have code that has been using ```long``` to do pointer arithmetic that is portable among 32 and 64-bit system, casting to ```(void *)``` would be hiding potential bugs. This is why Microsoft added the checked cast to (int) in the first place for 32-bit systems. It is just unfortunate that they choose int.

I'm just arguing for the less surprising thing to do. Doing what I'm proposing would fix existing issues for 32-bit systems without breaking any existing code.

**Comment by Janiels** [comment]
I'm not entirely sure why `(void *)` would hide potential bugs?
I mean on 64-bit platforms the upper bit might be used when representing a pointer. So a negative value in a `long` that is used to represent a pointer does not represent an invalid pointer -- not if you are writing portable code. However you are right that it could be used for this in 32-bit code.

**Comment by poizan42** [comment]
Is this even the problem of the runtime? Roslyn has a lot of inconsistent and weird behaviour when it comes to IntPtrs. Why is Roslyn even calling System.IntPtr::op_Explicit(..) for conversions from/to integer types and IntPtrs when it's not for other integer types? The overflow check should be controlled by checked/unchecked in the C# code that performs the conversion and not in the runtime.

**Comment by Janiels** [comment]
@poizan42 Which integer types does it not use the explicit conversion operators defined on `IntPtr` for?

**Comment by poizan42** [comment]
@Janiels I meant that it's not using any explicit conversion operators for conversions between byte,short,int,long and char (not there's any defined anyways). It could just emit conv.i / conv.ovf.i directly to convert to IntPtr/native int.

**Comment by Janiels** [comment]
All of those types are either implicitly convertible to `int` or `long`, so the compiler is doing that implicit conversion first. However, you're still right: for `ulong` the compiler has special inconsistent behavior:
```csharp
ulong test = ulong.MaxValue;
IntPtr val = (IntPtr)test;
// val = -1 in both 32-bit and 64-bit
```
The IL produced is the following:
```
  .maxstack  1
  .locals init ([0] uint64 test,
           [1] native int val)
  IL_0000:  nop
  IL_0001:  ldc.i4.m1
  IL_0002:  conv.i8
  IL_0003:  stloc.0
  IL_0004:  ldloc.0
  IL_0005:  call       native int [mscorlib]System.IntPtr::op_Explicit(int64)
  IL_000a:  stloc.1
  IL_000b:  ret
```
For some reason the compiler took it upon itself to convert the value to a `long` first. This conversion is unaffected by `checked` and `unchecked`. What's even more strange is that this appears to have been affected by `checked` before Roslyn, according to this Stackoverflow answer: http://stackoverflow.com/a/15769569/553294
Definitely strange behavior going on here. I guess it's time to dig into Roslyn. :smile:

**Comment by poizan42** [comment]
@Janiels the "ldc.i4.m1, conv.i8" is simply one of the shortest IL sequence to load 2^64-1, so that's not so surprising. The CLI stack doesn't have any concept of signedness so this part is fine.

So why is it calling op_Explicit(int64) and not op_Explicit(uint64). Well the answer to that is simple - because there isn't any uint64 overload defined. But I don't really think that there's any problem in that outside of the fact that Roslyn compiler can't control whether the conversion is checked for overflow.

But to get back to the issue at hand, this results in inconsistent behaviour between 32-bit and 64-bit platforms.

Conversion to IntPtr of:
32-bit:
uint64 not representable as IntPtr: Fails (exception)

64-bit:
uint64 not representable as IntPtr: Succeeds (reinterpreted)

**Comment by Janiels** [comment]
@poizan42 You are right!

To add to your matrix there are also these cases:
32-bit:
uint32 with MSB set: Exception (what this issue is about)
uint64 with the 33 MSB bits set: reinterpreted as signed integer, succeeds as negative value

**Comment by GrabYourPitchforks** [comment]
@tannergooding Would the work being done with `nint` / `nuint` affect this at all? I know there was consideration for making `checked` and `unchecked` blocks honored when converting between existing primitive types and the newly proposed types. Wondered if that meant the following code would work:

```cs
long a = GetLong();
IntPtr b = (IntPtr)(nuint)a; // unchecked

long x = GetLong();
IntPtr y = (IntPtr)checked((nuint)x); // explicitly checked for overflow
```
