### ISSUE TITLE
Cannot compile with VS 2015 Update 2?

### ISSUE THREAD

**Issue by manu-silicon** [dotnet/coreclr#4083]
I'm not sure if this is related to my recent update to VS 2015 Update 2, but I cannot compile CoreCLR on Windows. I'm getting the following error:

```
 daccess.cpp
  Microsoft (R) CLR External Data Access Data Table Generator Version 0.3
  Copyright (C) Microsoft Corp.  All rights reserved.

  BUILDMSG: System.IO.FileNotFoundException: Retrieving the COM class factory for component with CLSID {3BFCEA48-620F-4B6B-81F7-B9AF75454C7
  D} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
     at Dia.Util.DiaFile..ctor(String pdbFile, String dllFile)
     at PdbSymbolProvider..ctor(String symbolFilename, String dllFilename)
     at Shell.DoMain(String[] args)
     at Shell.Main(String[] args)
```

**Comment by manu-silicon** [comment]
Repairing my VS 2015 Update 2 install solved this issue.
