### ISSUE TITLE
Console.Readline throws null reference exception

### ISSUE THREAD

**Issue by AshwiniChalla** [dotnet/coreclr#4642]
following is the stack trace
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.ConsolePal.TryGetSpecialConsoleKey(Char[] givenChars, Int32 startIndex, Int32 endIndex, ConsoleKeyInfo& key, Int32& keyLength)
   at System.IO.StdInStreamReader.MapBufferToConsoleKey(ConsoleKey& key, Char& ch, Boolean& isShift, Boolean& isAlt, Boolean& isCtrl)
   at System.IO.StdInStreamReader.ReadKey(Boolean& previouslyProcessed)
   at System.IO.StdInStreamReader.ReadLine(Boolean consumeKeys)
   at System.IO.SyncTextReader.ReadLine()
   at System.Console.ReadLine()

My scenario is following
My command takes inputs from user interactively.
I used expect,send to give inputs.
from the diag logs of expect, I can see that send sends the input properly. Yet I got this exception.
Can someone throw light?

**Comment by jkotas** [comment]
System.Console.dll implementation lives in https://github.com/dotnet/corefx repo. Could you please reopen the issue there?

**Comment by AshwiniChalla** [comment]
Reopened on corefx.
