### ISSUE TITLE
RyuJIT x86: Silent bad codegen in pi-digits.cmd

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/coreclr#4665]
JIT\Performance\CodeQuality\BenchmarksGame\pidigits\pi-digits\pi-digits.cmd

test output:

```
Unhandled Exception: System.OverflowException: Value was either too large or too small for a UInt32.
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)
   at pidigits.extract_digit(UInt32 nth)
   at pidigits.Calculate(Int32 n, Boolean verbose)
   at pidigits.Main(String[] args)
Expected: 100
Actual: -532462766
```

correct output:

```
3141592653      :10
Expected: 100
Actual: 100
```

**Comment by mikedn** [comment]
This one works fine for me.

**Comment by BruceForstall** [comment]
Closing as dup of #4664. Converted to NYI with #4732.
