### ISSUE TITLE
MSCORLIB/UNIX/LINUX: cannot probe OS name/version.

### ISSUE THREAD

**Issue by myungjoo** [dotnet/coreclr#4743]
Tested: ARM/Linux

System.Environment.OSVersion is supposed to get you the name and version of OS.
However, if you are not running on Windows, you get the following unhandled exception.

```
bash-3.2# ./corerun csc.exe /lib:. /r:mscorlib.dll hello.cs
Microsoft (R) Visual C# Compiler version 42.42.42.42
Copyright (C) Microsoft Corporation. All rights reserved.

bash-3.2# ./corerun hello.exe
Hello World

Unhandled Exception: System.InvalidOperationException: OSVersion's call to GetVersionEx failed.
   at System.Environment.get_OSVersion()
   at Dela.Mono.Examples.HelloWorld.Main(String[] args)
Aborted (core dumped)
bash-3.2# 
bash-3.2# cat hello.cs
using System;

namespace Dela.Mono.Examples
{
   public class HelloWorld
   {
      public static void Main(string[] args)
      {
         Console.WriteLine("Hello World");
     Console.WriteLine(System.Environment.OSVersion.ToString());
      }
   } 
}

bash-3.2#
```

The fix is trivial and will be posted soon. :)

**Comment by myungjoo** [comment]
After applying the PR,

```
bash-3.2# ./corerun hello.exe
Hello World
Unix/Linux 0.0.0.0
bash-3.2# 

```

**Comment by karelz** [comment]
It should be fixed now: https://github.com/dotnet/corefx/blob/2117bae3a6c9736033e6d1659821ff3a1069920b/src/System.Runtime.Extensions/src/System/Environment.Unix.cs#L374-L392
