### ISSUE TITLE
ProjectException: "Duplicated source project item"

### ISSUE THREAD

**Issue by meolafon** [dotnet/coreclr#5168]
_(Sorry if it's a wrong repo for this - I could not find more appropriate)_

Trying to run T4 transforms on 'Build' in xproj file.

1)
If "MyTemplate.tt" is inside of project, but not mentioned in xproj file directly, Microsoft.TextTemplating.targets cannot see it:
(output from build)

_....
Target "ExecuteTransformations" in file...
Full list of templates passed in :
1>           {none}
....
1>Done building target "ExecuteTransformations" in project "MyProject.xproj".
(end)_

In other words, nothing gets created from the template.

2)
If "MyTemplate" is mentioned in xproj as

```
  <ItemGroup>
      <None Include="MyTemplate.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <OutputFilePath>\somepath\</OutputFilePath>
      </None>
</ItemGroup>
```

I cannot open the project, with the following exception:

System.AggregateException: One or more errors occurred. ---> Microsoft.VisualStudio.ProjectSystem.ProjectException: Duplicated source project item: "MyTemplate.tt".
   at Microsoft.VisualStudio.ProjectSystem.Utilities.ProjectErrorUtilities.ThrowProjectExceptionHelper(Exception innerException, String unformattedMessage, Object[] args)
   at Microsoft.VisualStudio.ProjectSystem.Utilities.ProjectErrorUtilities.ThrowProjectException(String message, Object arg0)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.CollectAllItemsInProjectTree(IImmutableDictionary`2 currentProjectData, Dictionary`2 pendingItemsByDirectory, ConfiguredProjectExports configuredProjectExports)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.GenerateOriginalTree(ConfiguredProjectExports configuredProjectExports, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.ProjectSystem.Designers.PhysicalProjectTreeProvider.<GenerateOriginalTreeAsync>d__115.MoveNext()

**Comment by adityamandaleeka** [comment]
@davidfowl Can you route this to the right person?

**Comment by davidfowl** [comment]
@meolafon can you file this issue here https://github.com/aspnet/Tooling?
