### ISSUE TITLE
Crash with crossgen'ed CLI SDK

### ISSUE THREAD

**Issue by livarcocc** [dotnet/coreclr#5201]
The issue doesn't repro with `COMPlus_ZapDisable=1`and see below for the stack trace.

This contains the CLI SDK binary drop:
`\\scratch2\scratch\licavalc\crossgen\stage2.zip`
This contains the crash dump:
`\\scratch2\scratch\licavalc\crossgen\task.mdmp`

Clone https://github.com/livarcocc/cli-1/tree/clean_up_after_rc3.

Build this repo by doing build.cmd at root in a windows box.

The dotnet-build.Tests are going to fail with this issue. After the build, to repro just this issue without needing to do a full build, just navigate to:

`<repo root>\test\dotnet-build.Tests\bin\Debug\netcoreapp1.0\It_builds_projects_with_ruleset_relative_path\TestRuleSet\TestLibraryWithRuleSet`

and then run:

 `<repo root>\artifacts\win10-x64\stage2\dotnet.exe <repo root>\artifacts\win10-x64\stage
2\sdk\1.0.0-preview2-002850\csc.dll -noconfig @<repo root>\test\dotnet-build.Tests\bin\Debug\netcoreapp1.0\It_builds_projects_with_ru
leset_relative_path\TestRuleSet\TestLibraryWithRuleSet\obj\Debug\netstandard1.5\dotnet-compile-csc.rsp`

Debugger spew:

```
CLR: Managed code called FailFast, saying "System.ArgumentNullException: Value cannot be null.
Parameter name: action
   at System.Threading.Tasks.Task..ctor(Delegate action, Object state, Task parent, CancellationToken cancellationToken, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, TaskScheduler scheduler)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2..ctor(Task`1 antecedent, Delegate function, Object state, TaskCreationOptions creationOptions, InternalTaskOptions internalOptions, StackCrawlMark& stackMark)
   at System.Threading.Tasks.TaskExtensions.TransferAsynchronously[TResult,TInner](TaskCompletionSource`1 completionSource, Task`1 outer)
   at System.Threading.Tasks.TaskExtensions.Unwrap[TResult](Task`1 task)
   at Microsoft.CodeAnalysis.Diagnostics.AsyncQueue`1.WithCancellation[T](Task`1 task, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.<ProcessCompilationEventsCoreAsync>d__67.MoveNext()"
ntdll!ZwTerminateProcess+0x14:
00007ff9`4d7c5664 c3              ret
0:008> k
 # Child-SP          RetAddr           Call Site
00 000000a0`ef77ba98 00007ff9`4d77b185 ntdll!ZwTerminateProcess+0x14 [d:\th.obj.amd64fre\minkernel\ntdll\daytona\objfre\amd64\usrstubs.asm @ 531]
01 000000a0`ef77baa0 00007ff9`4b264d8a ntdll!RtlExitUserProcess+0xe5 [d:\th\minkernel\ntdll\rtlstrt.c @ 1356]
02 000000a0`ef77bb90 00007ff9`1a50e222 KERNEL32!FatalExit+0xa [d:\th\base\win32\client\process.c @ 3592]
03 (Inline Function) --------`-------- coreclr!EEPolicy::ExitProcessViaShim+0x8 [f:\dd\ndp\clr\src\vm\eepolicy.cpp @ 621]
04 000000a0`ef77bbc0 00007ff9`1a50ebee coreclr!SafeExitProcess+0x222 [f:\dd\ndp\clr\src\vm\eepolicy.cpp @ 583]
05 000000a0`ef77bd60 00007ff9`1a8258d6 coreclr!EEPolicy::HandleFatalError+0x12a [f:\dd\ndp\clr\src\vm\eepolicy.cpp @ 1518]
06 000000a0`ef77c330 00007ff9`1a825a0d coreclr!SystemNative::GenericFailFast+0x17a [f:\dd\ndp\clr\src\classlibnative\bcltype\system.cpp @ 580]
*** WARNING: Unable to verify checksum for C:\Users\licavalc\git\cli-1\artifacts\win10-x64\stage2\shared\Microsoft.NETCore.App\1.0.0-rc3-002850\Microsoft.CodeAnalysis.dll
07 000000a0`ef77c3b0 00007ff9`19234dd4 coreclr!SystemNative::FailFastWithException+0x9d [f:\dd\ndp\clr\src\classlibnative\bcltype\system.cpp @ 636]
08 000000a0`ef77c500 00007ff8`bb144a5b Microsoft_CodeAnalysis!Microsoft.CodeAnalysis.FatalError.ReportUnlessCanceled(System.Exception)+0x34 [F:\Builds\5569\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\InternalUtilities\FatalError.cs @ 84]
09 000000a0`ef77c530 00007ff9`1a54ab6c Microsoft_CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__67.MoveNext()+0x3db [F:\Builds\5569\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs @ 814]
0a 000000a0`ef77c590 00007ff9`1a54a3f7 coreclr!ExceptionTracker::CallHandler+0x128 [f:\dd\ndp\clr\src\vm\exceptionhandling.cpp @ 3367]
0b 000000a0`ef77c5f0 00007ff9`1a5494a5 coreclr!ExceptionTracker::ProcessManagedCallFrame+0xbbb [f:\dd\ndp\clr\src\vm\exceptionhandling.cpp @ 2943]
0c 000000a0`ef77c880 00007ff9`1a5488f8 coreclr!ExceptionTracker::ProcessOSExceptionNotification+0x725 [f:\dd\ndp\clr\src\vm\exceptionhandling.cpp @ 1864]
0d 000000a0`ef77d860 00007ff9`4d7c9afd coreclr!ProcessCLRException+0x478 [f:\dd\ndp\clr\src\vm\exceptionhandling.cpp @ 1036]
0e 000000a0`ef77d980 00007ff9`4d754fe9 ntdll!RtlpExecuteHandlerForException+0xd [d:\th\minkernel\ntos\rtl\amd64\xcptmisc.asm @ 131]
0f 000000a0`ef77d9b0 00007ff9`4d7c8c0a ntdll!RtlDispatchException+0x3a9 [d:\th\minkernel\ntos\rtl\amd64\exdsptch.c @ 550]
10 000000a0`ef77e0c0 00007ff9`4a0f1f28 ntdll!KiUserExceptionDispatch+0x3a [d:\th\minkernel\ntos\rtl\amd64\trampoln.asm @ 715]
11 000000a0`ef77e7e0 00007ff9`1a4c6418 KERNELBASE!RaiseException+0x68 [d:\th\minkernel\kernelbase\xcpt.c @ 865]
12 000000a0`ef77e8c0 00007ff9`1a567f8d coreclr!RaiseTheExceptionInternalOnly+0x3a4 [f:\dd\ndp\clr\src\vm\excep.cpp @ 3113]
13 000000a0`ef77e9f0 00007ff9`1a347000 coreclr!IL_Throw+0x175 [f:\dd\ndp\clr\src\vm\jithelpers.cpp @ 5396]
14 000000a0`ef77eba0 00007ff9`1a0e03e9 System_Private_CoreLib_ni!System.Threading.Tasks.Task..ctor(System.Delegate, System.Object, System.Threading.Tasks.Task, System.Threading.CancellationToken, System.Threading.Tasks.TaskCreationOptions, System.Threading.Tasks.InternalTaskOptions, System.Threading.Tasks.TaskScheduler)+0x3c05d0 [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\Tasks\Task.cs @ 557]
*** WARNING: Unable to verify checksum for C:\Users\licavalc\git\cli-1\artifacts\win10-x64\stage2\shared\Microsoft.NETCore.App\1.0.0-rc3-002850\System.Threading.Tasks.dll
*** ERROR: Module load completed but symbols could not be loaded for C:\Users\licavalc\git\cli-1\artifacts\win10-x64\stage2\shared\Microsoft.NETCore.App\1.0.0-rc3-002850\System.Threading.Tasks.dll
15 000000a0`ef77ec10 00007ff9`41154270 System_Private_CoreLib_ni!System.Threading.Tasks.ContinuationResultTaskFromResultTask`2[[System.__Canon, System.Private.CoreLib],[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib]]..ctor(System.Threading.Tasks.Task`1<System.__Canon>, System.Delegate, System.Object, System.Threading.Tasks.TaskCreationOptions, System.Threading.Tasks.InternalTaskOptions, System.Threading.StackCrawlMark ByRef)+0xffffffff`fff25699 [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\Tasks\TaskContinuation.cs @ 176]
16 000000a0`ef77ec90 00007ff9`41154185 System.Threading.Tasks.TaskExtensions.TransferAsynchronously[[System.__Canon, System.Private.CoreLib],[System.__Canon, System.Private.CoreLib]](System.Threading.Tasks.TaskCompletionSource`1<System.__Canon>, System.Threading.Tasks.Task`1<System.__Canon>)+0xa0
17 000000a0`ef77ed00 00007ff8`bb146761 System.Threading.Tasks.TaskExtensions.Unwrap[[System.__Canon, System.Private.CoreLib]](System.Threading.Tasks.Task`1<System.Threading.Tasks.Task`1<System.__Canon>>)+0xe5
18 000000a0`ef77ed50 00007ff8`bb144784 Microsoft_CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AsyncQueue`1[[System.__Canon, System.Private.CoreLib]].WithCancellation[[System.__Canon, System.Private.CoreLib]](System.Threading.Tasks.Task`1<System.__Canon>, System.Threading.CancellationToken)+0x2b1 [F:\Builds\5569\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\DiagnosticAnalyzer\AsyncQueue.cs @ 236]
19 000000a0`ef77edc0 00007ff8`bb1442c5 Microsoft_CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<ProcessCompilationEventsCoreAsync>d__67.MoveNext()+0x104 [F:\Builds\5569\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs @ 782]
1a 000000a0`ef77ee50 00007ff9`1922294e System_Private_CoreLib_ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.__Canon, System.Private.CoreLib]](System.__Canon ByRef)+0xffffffff`a10aa0a5 [f:\dd\ndp\clr\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 479]
1b 000000a0`ef77eeb0 00007ff8`bb143d6a Microsoft_CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver.ProcessCompilationEventsCoreAsync(Microsoft.CodeAnalysis.Diagnostics.AnalysisScope, Microsoft.CodeAnalysis.Diagnostics.AnalysisState, Boolean, System.Threading.CancellationToken)+0x8e
1c 000000a0`ef77ef60 00007ff8`bb143705 Microsoft_CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass66_0+<<ProcessCompilationEventsAsync>b__0>d.MoveNext()+0x7a [F:\Builds\5569\DevDiv\Roslyn-Stabilization-Signed-Release\src\Open\src\Compilers\Core\Portable\DiagnosticAnalyzer\AnalyzerDriver.cs @ 722]
1d 000000a0`ef77efe0 00007ff8`bb142f48 System_Private_CoreLib_ni!System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib]].Start[[System.__Canon, System.Private.CoreLib]](System.__Canon ByRef)+0xffffffff`a10a94e5 [f:\dd\ndp\clr\src\mscorlib\src\System\Runtime\CompilerServices\AsyncMethodBuilder.cs @ 479]
1e 000000a0`ef77f040 00007ff9`19fc5df9 Microsoft_CodeAnalysis!Microsoft.CodeAnalysis.Diagnostics.AnalyzerDriver+<>c__DisplayClass66_0.<ProcessCompilationEventsAsync>b__0()+0x88
1f 000000a0`ef77f0e0 00007ff9`19f88ea6 System_Private_CoreLib_ni!System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib]].InnerInvoke()+0x49 [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\Tasks\future.cs @ 676]
20 000000a0`ef77f130 00007ff9`19f5960e System_Private_CoreLib_ni!System.Threading.Tasks.Task.Execute()+0x46 [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\Tasks\Task.cs @ 2493]
21 000000a0`ef77f170 00007ff9`19f8943a System_Private_CoreLib_ni!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)+0x6e [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\ExecutionContext.cs @ 104]
22 000000a0`ef77f1e0 00007ff9`19f891ba System_Private_CoreLib_ni!System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)+0x23a [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\Tasks\Task.cs @ 2815]
23 000000a0`ef77f290 00007ff9`19ff5e00 System_Private_CoreLib_ni!System.Threading.Tasks.Task.ExecuteEntry(Boolean)+0x9a [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\Tasks\Task.cs @ 2751]
24 000000a0`ef77f2d0 00007ff9`1a845443 System_Private_CoreLib_ni!System.Threading.ThreadPoolWorkQueue.Dispatch()+0x1c0 [f:\dd\ndp\clr\src\mscorlib\src\System\Threading\ThreadPool.cs @ 815]
25 000000a0`ef77f370 00007ff9`1a4ebef7 coreclr!CallDescrWorkerInternal+0x83 [f:\dd\ndp\clr\src\vm\amd64\CallDescrWorkerAMD64.asm @ 101]
26 000000a0`ef77f3b0 00007ff9`1a649422 coreclr!MethodDescCallSite::CallTargetWorker+0x20f [f:\dd\ndp\clr\src\vm\callhelpers.cpp @ 653]
27 (Inline Function) --------`-------- coreclr!MethodDescCallSite::Call_RetBool+0xc [f:\dd\ndp\clr\src\vm\callhelpers.h @ 420]
28 000000a0`ef77f4c0 00007ff9`1a4a76f1 coreclr!QueueUserWorkItemManagedCallback+0x2a [f:\dd\ndp\clr\src\vm\comthreadpool.cpp @ 510]
29 000000a0`ef77f5b0 00007ff9`1a4a7a3c coreclr!ManagedThreadBase_DispatchMiddle+0x89 [f:\dd\ndp\clr\src\vm\threads.cpp @ 10162]
2a 000000a0`ef77f710 00007ff9`1a4a7ad6 coreclr!ManagedThreadBase_DispatchOuter+0xb4 [f:\dd\ndp\clr\src\vm\threads.cpp @ 10417]
2b (Inline Function) --------`-------- coreclr!ManagedThreadBase_FullTransitionWithAD+0x2b [f:\dd\ndp\clr\src\vm\threads.cpp @ 10480]
2c 000000a0`ef77f7c0 00007ff9`1a5d2d38 coreclr!ManagedThreadBase::ThreadPool+0x32 [f:\dd\ndp\clr\src\vm\threads.cpp @ 10523]
2d 000000a0`ef77f820 00007ff9`1a5cbfa6 coreclr!ManagedPerAppDomainTPCount::DispatchWorkItem+0xe4 [f:\dd\ndp\clr\src\vm\threadpoolrequest.cpp @ 760]
2e 000000a0`ef77f970 00007ff9`1a5ccafd coreclr!ThreadpoolMgr::ExecuteWorkRequest+0x13a [f:\dd\ndp\clr\src\vm\win32threadpool.cpp @ 1893]
2f 000000a0`ef77f9c0 00007ff9`1a4a220c coreclr!ThreadpoolMgr::WorkerThreadStart+0x4d5 [f:\dd\ndp\clr\src\vm\win32threadpool.cpp @ 2363]
30 000000a0`ef77fa60 00007ff9`4b258102 coreclr!Thread::intermediateThreadProc+0x80 [f:\dd\ndp\clr\src\vm\threads.cpp @ 2869]
31 000000a0`ef77fba0 00007ff9`4d77c5b4 KERNEL32!BaseThreadInitThunk+0x22 [d:\th\base\win32\client\thread.c @ 64]
32 000000a0`ef77fbd0 00000000`00000000 ntdll!RtlUserThreadStart+0x34 [d:\th\minkernel\ntdll\rtlstrt.c @ 994]
0:008> .dump /ma task.mdmp
```

cc @gkhanna79 @JohnChen0

**Comment by gkhanna79** [comment]
@livarcocc Is this blocking RTM?

**Comment by gkhanna79** [comment]
@JohnChen0 Can you PTAL?

**Comment by JohnChen0** [comment]
I'm investigating.

**Comment by gkhanna79** [comment]
@JohnChen0 Anything interesting?

**Comment by JohnChen0** [comment]
Still investigating. The existing crash dump wasn't helpful, but now I have a local repro.

**Comment by JohnChen0** [comment]
This has been fixed with PR #5262. I have verified the fix with a private build.
@livarcocc Please verify when an official build with the fix becomes available.

**Comment by gkhanna79** [comment]
@JohnChen0 Thanks for driving the fix John. Can you also prepare the fix for release branch port?

**Comment by JohnChen0** [comment]
Prepared PR #5272 for release branch port.

**Comment by joshfree** [comment]
@livarcocc @eerhardt can you please verify and close this issue on 24128-00?

Is there any further action required by CLR (@johnchen0)

**Comment by JohnChen0** [comment]
There should be no further action required by CLR.
