### ISSUE TITLE
Marshal.StructureToPtr: System.AccessViolationException: Attempted to read or write protected memory

### ISSUE THREAD

**Issue by tijoytom** [dotnet/coreclr#5517]
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at System.Runtime.InteropServices.Marshal.StructureToPtr(Object structure, IntPtr ptr, Boolean fDeleteOld)
   at System.Runtime.InteropServices.Marshal.StructureToPtr[T](T structure, IntPtr ptr, Boolean fDeleteOld)
   at Program.VerifyMarshalLongerByValArrayInAStruct()
   at Program.Main(String[] args)

**Comment by tijoytom** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/6175
