### ISSUE TITLE
Access violation in System.Collections.NonGeneric.Tests on Windows in release branch

### ISSUE THREAD

**Issue by stephentoub** [dotnet/coreclr#5689]
http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/release_1.0.0/job/windows_nt_debug_prtest/157/consoleText
```
  Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
     at System.Collections.Concurrent.ConcurrentQueue`1.TryDequeue(T& result)
     at Xunit.Sdk.MessageBus.DispatchMessages()
     at Xunit.Sdk.MessageBus.ReporterWorker()
     at Xunit.Sdk.XunitWorkerThread.<>c.<QueueUserWorkItem>b__5_0(Object _)
     at System.Threading.Tasks.Task.Execute()
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```
```
  Finished running tests.  End time= 9:47:19.72, Exit code = -1073741819
D:\j\workspace\windows_nt_de---494cfe0d\Tools\tests.targets(202,5): warning MSB3073: The command "D:\j\workspace\windows_nt_de---494cfe0d\bin/tests/AnyOS.AnyCPU.Debug/System.Collections.NonGeneric.Tests/netcoreapp1.0/RunTests.cmd D:\j\workspace\windows_nt_de---494cfe0d\packages/" exited with code -1073741819. [D:\j\workspace\windows_nt_de---494cfe0d\src\System.Collections.NonGeneric\tests\System.Collections.NonGeneric.Tests.csproj]
D:\j\workspace\windows_nt_de---494cfe0d\Tools\tests.targets(211,5): error : One or more tests failed while running tests from 'System.Collections.NonGeneric.Tests' please check log for details! [D:\j\workspace\windows_nt_de---494cfe0d\src\System.Collections.NonGeneric\tests\System.Collections.NonGeneric.Tests.csproj]
```

**Comment by gkhanna79** [comment]
@adityamandaleeka This could be related to https://github.com/dotnet/coreclr/issues/5687

**Comment by gkhanna79** [comment]
@rahku Will help look into this.

**Comment by gkhanna79** [comment]
@sergiy-k has been able to reproduce the crashes with stress logs. We are looking into them.

**Comment by gkhanna79** [comment]
CC @JohnChen0 @fadimounir

**Comment by sergiy-k** [comment]
Fixed by https://github.com/dotnet/coreclr/pull/5742
