### ISSUE TITLE
[ARM32] Null exception bug on Interface call site

### ISSUE THREAD

**Issue by chunseoklee** [dotnet/coreclr#5783]
On arm32/linux + commit 38a89155cb2c53a96, the following example code does not catch the null exception. (Although this issue may be related to issue #5542, the debug log is different)  
Here,  m_pJM( IJitManager) is null. 

```
using System;

public interface I
{
    void Foo();
}

public class X : I
{
    virtual public  void Foo()
    {
        System.Console.WriteLine("Foo in X");
        I nullp= null;
        nullp.Foo(); 
    }
} 

public class CMain
{
	public static void Main(){
              try {
                  X obj = new X();
                  obj.Foo();
              }
              catch (NullReferenceException){
                  System.Console.Write("PASS");
              }
        }
              
}

```

gdb log
``` 
[New LWP 28411]
[New LWP 28412]
Foo in X

Program received signal SIGSEGV, Segmentation fault.
0xb646f1da in EECodeInfo::GetFunctionEntry (this=0xbeffe0b4)
    at /home/twoflower/dev/coreclr/src/vm/jitinterface.cpp:13872
13872	        m_pFunctionEntry = m_pJM->LazyGetFunctionEntry(this);
(gdb) bt
#0  0xb646f1da in EECodeInfo::GetFunctionEntry (this=0xbeffe0b4)
    at /home/twoflower/dev/coreclr/src/vm/jitinterface.cpp:13872
#1  0xb664b7b4 in UnwindManagedExceptionPass1 (ex=..., frameContext=0xbeffe348)
    at /home/twoflower/dev/coreclr/src/vm/exceptionhandling.cpp:4526
#2  0xb664bcd8 in DispatchManagedException (ex=...)
    at /home/twoflower/dev/coreclr/src/vm/exceptionhandling.cpp:4683
#3  0xb650bbfe in VSD_ResolveWorker (pTransitionBlock=0xbeffec14, 
    siteAddrForRegisterIndirect=3047346192, token=3671236294, flags=0)
    at /home/twoflower/dev/coreclr/src/vm/virtualcallstub.cpp:1546
#4  0xb665e6c2 in ResolveWorkerAsmStub ()
    at /home/twoflower/dev/coreclr/src/vm/arm/asmhelpers.S:581
#5  0xb1cd89aa in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) 
```

**Comment by chunseoklee** [comment]
closed by cannot reproduce
