### ISSUE TITLE
Security transparency in Docker containers

### ISSUE THREAD

**Issue by chlowell** [dotnet/coreclr#5975]
I understand the security transparency model was disabled in CoreCLR (#1807). However, when using MEF in a Docker container, I'm seeing this:

```
Unhandled Exception: System.MethodAccessException: Attempt to access method System.CodeDom.Compiler.GeneratedCodeAttribute..ctor(System.String, System.String) in violation of security transparency rules failed.
   at System.RuntimeMethodHandle.CheckLinktimeDemands(IRuntimeMethodInfo method, RuntimeModule module, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttributes[T](MemberInfo element, Boolean inherit)
   at System.Composition.Convention.ConventionBuilder.GetCustomAttributes(Type reflectedType, MemberInfo member)
   at System.Composition.TypedParts.Discovery.TypeInspector.InspectTypeForPart(TypeInfo type, DiscoveredPart& part)
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at ConsoleApplication.Program.Main(String[] args)
Aborted (core dumped)
```

This occurs only in the container (works as expected on Windows and Linux), and only when composing types outside the entry assembly:
``` C#
...
using System.Composition.Convention;
using System.Composition.Hosting;
...

var conventions = new ConventionBuilder();
conventions.ForTypesDerivedFrom<IPlugin>()
    .Export<IPlugin>()
    .Shared();

var doesNotThrow = new ContainerConfiguration()
    .WithAssembly(Assembly.GetEntryAssembly(), conventions)
    .CreateContainer(); // no trouble

var assemblies = Directory.GetFiles(AppContext.BaseDirectory, "*.dll")
    .Select(AssemblyLoadContext.GetAssemblyName)
    .Select(Assembly.Load);

var throws = new ContainerConfiguration()
    .WithAssemblies(assemblies, conventions)
    .CreateContainer(); // MethodAccessException
```

A full repro is available at https://github.com/chlowell/container-security-transparency

**Comment by ellismg** [comment]
I looked into this a little bit.

The problem is not specific to docker, but rather a difference between when the app is running from build the output directory (i.e. via dotnet run) vs when it's running from the published folder (i.e. dotnet publish followed by dotnet <path-to-repro-dll-in-published-folder>.

The difference in these cases is that in the published case, the MEF implementation assemblies are SxS with repro.dll instead of being picked up from the package cache.  That means that this line:

```
var assemblies = Directory.GetFiles(AppContext.BaseDirectory, "*.dll")
    .Select(AssemblyLoadContext.GetAssemblyName)
    .Select(Assembly.Load);
```

Ends up pulling in `System.Composition.Convention.dll` and including it in the list of assemblies in the ContainerlConfiguration.

`System.Composition.Convention` contains a type, `Microsoft.Internal.Strings`, which contains resource strings and was auto-generated, so it is decorated with `System.Diagnostics.Tools!System.CodeDom.Compiler.GeneratedCodeAttribute`.  `System.Composition.Convention` also contains an assembly level `SecurityTransparent` attribute while `System.Diagnostics.Tools` has nothing, and if I recall correctly, in this case the runtime will treat this as "opportunistically critical" and make all the members security critical.

This results in a violation of the transparency security rules, since transparent members can not have critical attributes on them.

It's possible that we just need to extend the ifdeff in [runtimehandles.cpp](https://github.com/dotnet/coreclr/blob/master/src/vm/runtimehandles.cpp#L341) to handle this case (i.e. is any part of this method reasonable in CoreCLR now)?, but I'm not an expert in this area.  @gkhanna79 @jkotas who's the expert in this part of the code-base these days?

**Comment by jkotas** [comment]
These transparency checks should be wrapped with `if (Security::IsTransparencyEnforcementEnabled())` so that it does not run in CoreCLR.

**Comment by gkhanna79** [comment]
@rahku Can you PTAL?
