### ISSUE TITLE
System.IO: cannot read file named "\" on Linux

### ISSUE THREAD

**Issue by atsushieno** [dotnet/coreclr#6118]
On non-Windows platforms, backslash is a valid file name that can exist. When we try to read such a file using coreclr's System.IO API, it fails to open it. In my console dump below, you'd find that Unix cat works so as mono System.IO implementation.

```
~/Desktop$ cat bs.cs
public class Test
{
	public static void Main (string [] args)
	{
		System.Console.WriteLine (new System.IO.StreamReader (args [0]).ReadToEnd ());
	}
}
~/Desktop$ cat \\
TEST
~/Desktop$ mcs bs.cs
~/Desktop$ mono bs.exe \\
TEST

~/Desktop$ mcs bs.cs -noconfig -nostdlib -r:/sources/dotnet/coreclr/bin/Product/Linux.x64.Debug/System.Private.CoreLib.dll 
~/Desktop$ /sources/dotnet/coreclr/bin/Product/Linux.x64.Debug/corerun bs.exe \\
Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/home/atsushi/Desktop/\' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path, Boolean detectEncodingFromByteOrderMarks)
   at System.IO.StreamReader..ctor(String path)
   at Test.Main(String[] args)
Aborted (core dumped)
```

There would be several scenarios that this corner-case-looking issue could be generally problematic e.g. when implementing some sort of file manager.

**Comment by stephentoub** [comment]
> using coreclr's System.IO API

The issue here is that you're building against mscorlib.dll rather than against the contracts, and as a result you're using the System.IO implementation that's in mscorlib, which is really only for mscorlib itself; the System.IO.FileSystem.dll implementation in corefx provides the full cross-platform support here.  For 1.0, you need to build against the contracts to pick up the right functionality.  For the future, we're working on improving the binary compatibility between .NET Core and Mono to enable these kinds of situations.

```
~/repro$ cat Program.cs 
public class Test
{
    public static void Main (string [] args)
    {
        System.Console.WriteLine (new System.IO.StreamReader(System.IO.File.OpenRead(args[0])).ReadToEnd ());
    }
}
~/repro$ cat \\
TEST
stoub@stoublinux2:~/repro$ dotnet run \\
Project repro (.NETCoreApp,Version=v1.0) was previously compiled. Skipping compilation.
TEST
~/repro$ 
```

**Comment by atsushieno** [comment]
Ohh, alright. Yes that should be the right path that I had to try. The current state of implementation should be already fine. Thanks.
