### ISSUE TITLE
Regression in unittest JIT/Methodical/MDArray/basics/stringarr_cs_ro

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#6178]
environment: Linux/ARM 
CoreCLR Debug build & Unittest release build 

running 'JIT/Methodical/MDArray/basics/stringarr_cs_ro'

```
Element manipulation of 6 by 6 matrices with different arithmatic operationsexe  
Matrix element stores string converted from random double
array set/get, ref/out param are used

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at string1.Main()
Aborted
```

using GDB

```
Breakpoint 1, ExceptionTracker::ProcessManagedCallFrame (this=0x51ef0,
    pcfThisFrame=0x7effd8d0, sf=..., sfEstablisherFrame=...,
    pExceptionRecord=0x7effe388, STState=ExceptionTracker::STS_NewException,
    uMethodStartPC=1877694524, dwExceptionFlags=0,
    dwTACatchHandlerClauseIndex=0, sfEstablisherOfActualHandlerFrame=...)
    at /home/hseok82/git/coreclr/src/vm/exceptionhandling.cpp:2786
2786    /home/hseok82/git/coreclr/src/vm/exceptionhandling.cpp: No such file or directory.
(gdb) p EHClause
$1 = {Flags = COR_ILEXCEPTION_CLAUSE_NONE, TryStartPC = 804, TryEndPC = 880,
  HandlerStartPC = 1950, HandlerEndPC = 1972, {TypeHandle = 0x1000007,
    ClassToken = 16777223, FilterOffset = 16777223}}
(gdb) p pcfThisFrame->GetRelOffset()
$2 = 880
```

Try block: 804 <=  pc < 880 
pc: 880

I think this failure is related to exception handling with helper function. In the JIT-compiled code, it calls helper function 'CORINFO_HELP_RNGCHKFAIL' for array bound exception check.

**Comment by hseok-oh** [comment]
Code generated by JIT compiler

```
G_M49836_IG14:        ; offs=000366H, size=000AH, gcrefRegs=0000 {}, byrefRegs=0000 {}, byref
870) IN012c: 000366      movw    r3, 0x7cb5
874) IN012d: 00036A      movt    r3, 0x7662
878) IN012e: 00036E      blx     r3          // CORINFO_HELP_RNGCHKFAIL
```

src/vm/exceptionhandling.cpp#L1438-L1449
```
    if (pDispatcherContext->ControlPcIsUnwound)
    {
         ControlPCForEHSearch -= STACKWALK_CONTROLPC_ADJUST_OFFSET;
```

I think this code don't handle exception checked by CoreCLR helper function.

**Comment by parjong** [comment]
CoreCLR with Release build (on Release TC) also failed to execute those unittests:
```
FAILED   - [ 7324 :    3 sec ] JIT/Methodical/MDArray/basics/stringarr_cs_do/stringarr_cs_do.sh
FAILED   - [ 7325 :    3 sec ] JIT/Methodical/MDArray/basics/stringarr_cs_d/stringarr_cs_d.sh
FAILED   - [ 7326 :    3 sec ] JIT/Methodical/MDArray/basics/stringarr_cs_ro/stringarr_cs_ro.sh
FAILED   - [ 7327 :    3 sec ] JIT/Methodical/MDArray/basics/stringarr_cs_r/stringarr_cs_r.sh
```

**Comment by janvorli** [comment]
It is likely related to #6185

**Comment by parjong** [comment]
@janvorli It seems that there are multiple issues. I checked the patch in #6185, but I got the following results (which is quite random):
```
$ ./run ut/JIT/Methodical/MDArray/basics/stringarr_cs_d/stringarr_cs_d.exe
2D Array
Element manipulation of 6 by 6 matrices with different arithmatic operations
Matrix element stores string converted from random double
array set/get, ref/out param are used

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at string1.Process2DArray(String[,]& a)
   at string1.Main()
./run: line 12: 26213 Aborted                 ${SCRIPT_BASE}/${DOTNET_TAG}/corerun -c ${SCRIPT_BASE}/${DOTNET_TAG} $@

$ ./run ut/JIT/Methodical/MDArray/basics/stringarr_cs_d/stringarr_cs_d.exe
2D Array
Element manipulation of 6 by 6 matrices with different arithmatic operations
Matrix element stores string converted from random double
array set/get, ref/out param are used

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at string1.ProcessJagged2DArray(String[][]& a)
   at string1.Main()
./run: line 12: 26221 Aborted                 ${SCRIPT_BASE}/${DOTNET_TAG}/corerun -c 

$ ./run ut/JIT/Methodical/MDArray/basics/stringarr_cs_d/stringarr_cs_d.exe
2D Array
Element manipulation of 5 by 5 matrices with different arithmatic operations
Matrix element stores string converted from random double
array set/get, ref/out param are used

3D Array
Element manipulation of 5 by 6 by 5 matrices with different arithmatic operations

PASSED


```

**Comment by janvorli** [comment]
Random failures in this test case are strange. My guess is that it is either a GC related problem or possibly an OOM problem. 
Could you please run the test under GDB multiple times until you hit a SIGSEGV that would get translated to the NullReferenceException and see what it stems from?

**Comment by parjong** [comment]
@janvorli It seems that NullReference comes from managed code:
```
(gdb) r 
...

2D Array
Element manipulation of 7 by 7 matrices with different arithmatic operations
Matrix element stores string converted from random double
array set/get, ref/out param are used

Program received signal SIGSEGV, Segmentation fault.
0xb23ad0e8 in ?? ()

(gdb) bt
#0  0xb23ad0e8 in ?? ()
#1  0xb234d838 in ?? ()
```
SIGSEGV is rassed from the following code:
```
(gdb) x/16i $pc
=> 0xb23ad0e8:  ldr     r2, [r2, #32]
   0xb23ad0ea:  cmp     r3, r2
   0xb23ad0ec:  beq.n   0xb23ad0fc
   0xb23ad0ee:  ldr     r0, [sp, #20]
   0xb23ad0f0:  mov     r1, r4
   0xb23ad0f2:  movw    r3, #37977      ; 0x9459
   0xb23ad0f6:  movt    r3, #46757      ; 0xb6a5
   0xb23ad0fa:  blx     r3
   0xb23ad0fc:  ldr     r2, [r4, #12]
   0xb23ad0fe:  ldr     r3, [sp, #16]
   0xb23ad100:  ldr     r1, [r4, #20]
   0xb23ad102:  subs    r3, r3, r1
   0xb23ad104:  cmp     r3, r2
   0xb23ad106:  bcs.n   0xb23ad138
   0xb23ad108:  mov     r12, r3
   0xb23ad10a:  mov     r1, r2
(gdb) info reg
r0             0xb2f1a7a0       3002181536
r1             0x3      3
r2             0x0      0
r3             0xb26a5c60       2993314912
r4             0xb2f1a7a0       3002181536
r5             0xbefff298       3204444824
r6             0x0      0
r7             0xbefff1e8       3204444648
r8             0x1f38   7992
r9             0xbefff330       3204444976
r10            0x0      0
r11            0xbeffef5c       3204443996
r12            0xb23a1dac       2990153132
sp             0xbeffef58       0xbeffef58
lr             0xb234d839       -1305159623
pc             0xb23ad0e8       0xb23ad0e8
cpsr           0xa0000030       -1610612688
```

**Comment by janvorli** [comment]
Could you please run the test with `COMPlus_JitDisasm=Process2DArray` so that we get a full disass of the function with symbolic names?

**Comment by parjong** [comment]
@janvorli As I remember, Debug CoreCLR didsn't show the above error. Anyway, I'll check that again.

**Comment by janvorli** [comment]
@parjong, @hseok-oh said:
environment: Linux/ARM 
CoreCLR **Debug** build & Unittest release build

**Comment by parjong** [comment]
@janvorli I think that #6185 might cause the above exception for Debug build. Before the regression discussed in #6185 is introduced, I didn't see the above error in Debug build. Instead, I observed that exception in Release build. To make it clear, I'll check Debug build CLR after I merge the patch in #6185.

**Comment by parjong** [comment]
\CC @chunseoklee

**Comment by chunseoklee** [comment]
On a2b91aa81f8ece1fa8731e55a82b650c96a45824(#6617 PR) Debug build,   'JIT/Methodical/MDArray/basics/stringarr_cs_ro' passed. 
coreclr **release** build seems to have some issue.

**Comment by parjong** [comment]
@janorli @hseok-oh I repeated this test 10 times after merging the patch in #6185, but I failed to reproduce the error as @chunseoklee reported.

**Comment by hseok-oh** [comment]
@parjong I have same result with you and @chunseoklee in CoreCLR debug/Unittest release environment.

**Comment by parjong** [comment]
@janvorli @hseok-oh This issue seems to be related with ``libunwind``. I am currently evaluating Release CoreCLR from 12fbe4ba096, and find that this unittest doesn't crash if ``UNW_ARM_UNWIND_METHOD`` is set as 6.

**Comment by parjong** [comment]
I find that this unittest does not crash if all the .dbg files are removed from the test overlay.
