### ISSUE TITLE
An unhandled exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.ni.dll

### ISSUE THREAD

**Issue by NVentimiglia** [dotnet/coreclr#6413]
This class wraps the tcpclient yielded by the tcplistener. When I close the connection client side, the class throws a null ref exception. Early returning from the StartReceiving method evades the exception, so, my guess is this is some sort of race condition related to listeneing to a dead socket.

My problem is, I can not catch this exception. No matter how many of break points in the catch handles seems to catch anything. When I try to inspect the exception, I am pointed to System.Private.CoreLib, *which is not my code*.

### Exception
`````
 An unhandled exception of type 'System.NullReferenceException' occurred in System.Private.CoreLib.ni.dll
`````

### Call Stack

`````
System.Private.CoreLib.ni.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	System.Private.CoreLib.ni.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
`````

### Code

`````
 /// <summary>
    /// http://codereview.stackexchange.com/questions/82806/asynctcpclient-asynchronous-tcpclient
    /// https://github.com/sethcall/async-helper/blob/master/src/AsyncTcpClient/AsyncTcpClient.cs
    /// </summary>
    public class AsyncTcpClient : IDisposable
    {
        private bool disposed = false;
        public TcpClient tcpClient;
        public NetworkStream stream;
        private AsyncLock myLock = new AsyncLock();

        public event Action<byte[]> OnData = delegate { };
        public event Action OnClose = delegate { };
        public event Action<Exception> OnError = delegate { };


        public bool IsOpen
        {
            get
            {
                return !disposed && this.tcpClient != null && this.tcpClient.Connected;
            }
        }

        public AsyncTcpClient(TcpClient client)
        {
            tcpClient = client;
            tcpClient.NoDelay = true; // No nagel
            tcpClient.SendBufferSize = Signal.MAXIMUM_BUFFER_SIZE;
            tcpClient.ReceiveBufferSize = Signal.MAXIMUM_BUFFER_SIZE;

            stream = (tcpClient.GetStream());

            Task.Factory.StartNew(StartReceiving, TaskCreationOptions.LongRunning);
        }


        public async Task SendAsync(byte[] data, ushort size)
        {
            try
            {
                if (!IsOpen && !disposed)
                    return;

                //can only send one at a time
                using (var releaser = await myLock.LockAsync())
                {
                    //send payload
                    await stream.WriteAsync(data, 0, size);
                }
            }
            catch (Exception ex)
            {
                OnError(ex);
                Dispose();
            }
        }

        async void StartReceiving()
        {
            byte[] payloadBuffer = BufferFactory.Rent(Signal.MAXIMUM_BUFFER_SIZE);
            int payloadIndex = 0;
            ushort size = 0;

            try
            {
                while (IsOpen)
                {
                    try
                    {
                        //read the size header
                        payloadIndex += await stream.ReadAsync(payloadBuffer, payloadIndex, sizeof(ushort));

                        //sanity
                        if (!IsOpen)
                            break;

                        //get size
                        size = BufferHelper.ReadUInt16(payloadBuffer, 0);

                        //get rest of the header / payload
                        payloadIndex += await stream.ReadAsync(payloadBuffer, payloadIndex, size - sizeof(ushort));

                        //sanity
                        if (!IsOpen)
                            break;

                        //copy the payload and yield it 
                        byte[] copy = BufferFactory.Rent(size);
                        Buffer.BlockCopy(payloadBuffer, 0, copy, 0, size);
                        OnData(copy);

                        //reset
                        payloadIndex = 0;
                        size = 0;
                    }

                    catch (ObjectDisposedException)
                    {

                    }
                    catch (Exception ex)
                    {
                        OnError(ex);
                        Dispose();
                    }
                }
            }
            catch (Exception ex)
            {
                OnError(ex);
            }

            if (payloadBuffer != null)
            {
                BufferFactory.Return(payloadBuffer);
            }
        }

        public void Dispose()
        {
            if (!disposed)
            {
                try
                {
                    if (tcpClient != null)
                    {
                        tcpClient.Dispose();
                        tcpClient = null;
                    }
                    if (stream != null)
                    {
                        stream.Dispose();
                        stream = null;
                    }
                }
                catch (Exception ex)
                {
                    
                }

                GC.SuppressFinalize(this);

                disposed = true;
                OnClose();
            }
        }
    }
`````

**Comment by jkotas** [comment]
Could you please include repro steps for the crash? 

Good repro steps are very simple, something like: clone GitHub repo, open project in Visual Studio 2015 Update 3, press F5.

**Comment by NVentimiglia** [comment]
@jkotas 
https://github.com/NVentimiglia/TCPTests/tree/master

- Open Solution
- Run both projects client and server, this is a solution property
- Server runs on 5000, ensure nothing is using that port
- On the client terminal, press return. This will connect the client.
- On the client terminal, press return. This will terminate the client.
- Notice that the server crashes with a NRE from inside non client code.

**Comment by jkotas** [comment]
I see a nice NRE exception  in user code:

![image](https://cloud.githubusercontent.com/assets/6668460/17115799/dc373a86-5269-11e6-9b5e-02f81b06e700.png)

Similar result if I run it from command prompt:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SignalMQ.Transports.Tcp.TcpConnection.Client_OnError(Exception obj)
   at System.Action`1.Invoke(T obj)
   at SignalMQ.Transports.Tcp.AsyncTcpClient.<StartReceiving>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_1(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by NVentimiglia** [comment]
@jkotas  Thanks. I opened up the project on my work computer and saw the exception in my code. Very strange that I was seeing something else on my home computer, maybe I was just tired. 

Thanks for the assistance, everything is working fine.
