### ISSUE TITLE
[Linux/ARM] System.Linq.Expressions.Tests.dll fail

### ISSUE THREAD

**Issue by hseok-oh** [dotnet/coreclr#6667]
Linux / ARM32 (hardfp)
CoreCLR: release (-O1) build (deb00ad)
CoreFX: debug build (dotnet/corefx@a6e95d3)

CoreFX Unittest System.Linq.Expressions.Tests.dll fail
```
./corerun xunit.console.netcore.exe System.Linq.Expressions.Tests.dll -xml testResults.xml -notrait Benchmark=true -notrait category=OuterLoop -notrait category=failing -notrait category=nonlinuxtests -parallel none -showprogress
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Linq.Expressions.Tests
Discovered:  System.Linq.Expressions.Tests
Starting:    System.Linq.Expressions.Tests

...........

  System.Linq.Expressions.Tests.ConvertTests.ConvertDoubleToNullableULongTest(useInterpreter: False) [FAIL]
      Assert.Equal() Failure
      Expected: 18446744073709551615
      Actual:   0
      Stack Trace:
            at System.Linq.Expressions.Tests.ConvertTests.VerifyDoubleToNullableULong(Double value, Boolean useInterpreter)
            at System.Linq.Expressions.Tests.ConvertTests.ConvertDoubleToNullableULongTest(Boolean useInterpreter)

...........

   System.Linq.Expressions.Tests.ConvertTests.ConvertDoubleToULongTest(useInterpreter: False) [FAIL]
      Assert.Equal() Failure
      Expected: 18446744073709551615
      Actual:   0
      Stack Trace:
            at System.Linq.Expressions.Tests.ConvertTests.VerifyDoubleToULong(Double value, Boolean useInterpreter)
            at System.Linq.Expressions.Tests.ConvertTests.ConvertDoubleToULongTest(Boolean useInterpreter)

...........

Finished:    System.Linq.Expressions.Tests

=== TEST EXECUTION SUMMARY ===
   System.Linq.Expressions.Tests  Total: 26297, Errors: 0, Failed: 2, Skipped: 5, Time: 687.124s
Finished running tests. End time=13:07:28. Return value was 2
error: One or more tests failed while running tests from ''.  Exit code 2.

```

**Comment by hseok-oh** [comment]
It is related to casting problem: from negative double to unsigned integer(int/long) in ARM architecture
In ARM architecture, negative double is converted to zero when target is unsigned integer.

**Comment by hseok-oh** [comment]
Differet fail
Linux / ARM32 (hardfp)
CoreCLR: release (-O3) build (@633a65e + #6754)
CoreFX: debug build (dotnet/corefx@9490069)

```
System.Linq.Expressions.Tests.LiftedDivideNullableTests.CheckLiftedDivideNullableULongTest(useInterpreter: False) [FAIL]
   Assert.Throws() Failure
   Expected: typeof(System.DivideByZeroException)
   Actual:   (No exception was thrown)
   Stack Trace:
         at System.Linq.Expressions.Tests.LiftedDivideNullableTests.VerifyDivideNullableULong(Nullable`1 a, Nullable`1 b, Boolean useInterpreter)
         at System.Linq.Expressions.Tests.LiftedDivideNullableTests.CheckLiftedDivideNullableULongTest(Boolean useInterpreter)
System.Linq.Expressions.Tests.BinaryNullableDivideTests.CheckNullableULongDivideTest(useInterpreter: False) [FAIL]
   Assert.Throws() Failure
   Expected: typeof(System.DivideByZeroException)
   Actual:   (No exception was thrown)
   Stack Trace:
         at System.Linq.Expressions.Tests.BinaryNullableDivideTests.VerifyNullableULongDivide(Nullable`1 a, Nullable`1 b, Boolean useInterpreter)
         at System.Linq.Expressions.Tests.BinaryNullableDivideTests.CheckNullableULongDivideTest(Boolean useInterpreter)
........
System.Linq.Expressions.Tests  Total: 26430, Errors: 0, Failed: 6, Skipped: 5, Time: 183.838s
```

6 fail show similar message: 
```
   Assert.Throws() Failure
   Expected: typeof(System.DivideByZeroException)
   Actual:   (No exception was thrown)
```

**Comment by hseok-oh** [comment]
It is related to ValueNumer analysis (constant folding optimization).

When IL use unsigned long divide (or modulo) operation in 32bit architecture, JITC generate code that call helper function. But ValueNumber analysis does not classifies signed and unsigned value operation.

https://github.com/dotnet/coreclr/blob/e550cf35bd5ff8e7eefcb1a605219f71a3672d83/src/jit/valuenum.cpp#L7067-L7072

And JITC uses constant folding optimization based on signed integer(long size) operation.

https://github.com/dotnet/coreclr/blob/e550cf35bd5ff8e7eefcb1a605219f71a3672d83/src/jit/valuenum.cpp#L1701-L1706

https://github.com/dotnet/coreclr/blob/e550cf35bd5ff8e7eefcb1a605219f71a3672d83/src/jit/valuenum.cpp#L147-L171
