### ISSUE TITLE
JIT/Performance/CodeQuality/Serialization tests failing in CI

### ISSUE THREAD

**Issue by adityamandaleeka** [dotnet/coreclr#6725]
The Serialize and Deserialize tests seem to be failing consistently in Ubuntu CI jobs starting a few hours ago with the following errors:

```
FAILED   - JIT/Performance/CodeQuality/Serialization/Deserialize/Deserialize.sh
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/master/release_ubuntu_tst/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/corerun Deserialize.exe
               
               Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
                  at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
                  at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
                  at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
                  at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
                  at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
                  at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
                  at System.Runtime.Serialization.CollectionDataContract.IsCollectionDataContract(Type type)
                  at System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(Type type, Boolean tryCreate, DataContract& dataContract, Type& itemType, Boolean constructorRequired)
                  at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
                  at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
                  at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
                  at System.Runtime.Serialization.DataContractSerializer.get_RootContract()
                  at System.Runtime.Serialization.DataContractSerializer.InternalIsStartObject(XmlReaderDelegator reader)
                  at System.Runtime.Serialization.DataContractSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
                  at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
                  at System.Runtime.Serialization.XmlObjectSerializer.ReadObject(XmlDictionaryReader reader)
                  at JsonBenchmarks.DeserializeDataContractBenchInner(DataContractSerializer ds, MemoryStream ms)
                  at JsonBenchmarks.DeserializeObject()
                  at JsonBenchmarks.Main()
               ./Deserialize.sh: line 117:  8540 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" Deserialize.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
FAILED   - JIT/Performance/CodeQuality/Serialization/Serialize/Serialize.sh
               BEGIN EXECUTION
               /mnt/j/workspace/dotnet_coreclr/master/release_ubuntu_tst/bin/tests/Windows_NT.x64.Release/Tests/coreoverlay/corerun Serialize.exe
               
               Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Runtime.Serialization.Primitives, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
                  at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
                  at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
                  at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
                  at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
                  at System.Reflection.CustomAttribute.IsCustomAttributeDefined(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Int32 attributeCtorToken, Boolean mustBeInheritable)
                  at System.Reflection.CustomAttribute.IsDefined(RuntimeType type, RuntimeType caType, Boolean inherit)
                  at System.Runtime.Serialization.CollectionDataContract.IsCollectionDataContract(Type type)
                  at System.Runtime.Serialization.CollectionDataContract.IsCollectionOrTryCreate(Type type, Boolean tryCreate, DataContract& dataContract, Type& itemType, Boolean constructorRequired)
                  at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.CreateDataContract(Int32 id, RuntimeTypeHandle typeHandle, Type type)
                  at System.Runtime.Serialization.DataContract.DataContractCriticalHelper.GetDataContractSkipValidation(Int32 id, RuntimeTypeHandle typeHandle, Type type)
                  at System.Runtime.Serialization.DataContract.GetDataContract(RuntimeTypeHandle typeHandle, Type type, SerializationMode mode)
                  at System.Runtime.Serialization.DataContractSerializer.get_RootContract()
                  at System.Runtime.Serialization.DataContractSerializer.InternalWriteStartObject(XmlWriterDelegator writer, Object graph)
                  at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
                  at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
                  at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
                  at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)
                  at JsonBenchmarks.SerializeDataContractBenchInner(Object o, MemoryStream ms)
                  at JsonBenchmarks.SerializeObject()
                  at JsonBenchmarks.Main()
               ./Serialize.sh: line 117:  8555 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" Serialize.exe $CLRTestExecutionArguments
               Expected: 100
               Actual: 134
               END EXECUTION - FAILED
```

Example jobs:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/release_ubuntu_tst/1309/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/release_ubuntu_tst/1310/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/release_ubuntu_tst/1311/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/release_ubuntu_tst/1312/
http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/release_ubuntu_tst/1313/

**Comment by adityamandaleeka** [comment]
It looks like the binaries we're pulling from CoreFX builds now have `.ver 4:1:2:0` for System.Runtime.Serialization.Primitives instead of `.ver 4:2:0:0`.

@weshaggard I poked around and saw that you made a change to some CoreFX tests to revert to 4.1 in [this PR](https://github.com/dotnet/corefx/commit/19c1a45b76df1c439773876a1a21954bd34feab7). I don't know any of the context for that, but do we need to do something similar here as well?

**Comment by weshaggard** [comment]
Yes you will need to update the package to 4.1.1 stable or 4.1.2 prerelease.

**Comment by weshaggard** [comment]
I submitted a PR to update. This is a side-effect of the test compiling against packages yet actually taking the live builds from corefx.
