### ISSUE TITLE
[ARM/Linux] Segmentation fault while running CoreFX 'System.Net.NetworkInformation.Functional.Tests'

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#6787]
In ARM/Linux, CoreCLR shows the following segmentation fault while running CoreFX 'System.Net.NetworkInformation.Functional.Tests':
```
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.
Discovering: System.Net.NetworkInformation.Functional.Tests
Discovered:  System.Net.NetworkInformation.Functional.Tests
Starting:    System.Net.NetworkInformation.Functional.Tests

System.Net.NetworkInformation.Tests.NetworkInterfaceBasicTest.BasicTest_StaticIPv6LoopbackIndex_MatchesLoopbackNetworkInterface [STARTING]
Segmentation fault
```

**Comment by parjong** [comment]
I found that the following example shows similar behavior:
```
using System.Net.Sockets;

namespace Sample
{
    public class Runner
    {
      public static void Main()
      {
        try
        {
          System.Console.WriteLine("Before");
          System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces();
          System.Console.WriteLine("After");
        }
        catch (System.Exception ex)
        {
          System.Console.WriteLine("Caught");
          System.Console.WriteLine(ex);
        }
      }
    }
}
```

I expected to see the former one, but unfortunately got the latter one:
 - Expected:
```
Before
After
```
 - Actual:
```
Before
Segmentation fault
```

**Comment by parjong** [comment]
PR #6788 (although it is under evaluation) allows me to go a bit more. With PR #6787, I got the following output:
```
Before

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/proc/sys/net/ipv4/conf/lo:virtual/forwarding'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__0(String name, IpAddressInfo* ipAddr, IpAddressInfo* maskAddr)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
   at Sample.Runner.Main()
```

**Comment by parjong** [comment]
Interestingly, this issue can be reproduced from ubuntu 14.04 (x86_64) via creating a virtual network interface and then execute the above sample, as follows:
```
$ sudo ifconfig lo:virtual 192.168.222.1
$ corerun workspace-host/Failing.System.Net.NetworkInformation.Functional.Tests.dll
Before

Unhandled Exception: System.IO.FileNotFoundException: Could not find file '/proc/sys/net/ipv4/conf/lo:virtual/forwarding'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileStream.InternalOpen(String path, Int32 bufferSize, Boolean useAsync)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at System.Net.NetworkInformation.StringParsingHelpers.ParseRawIntFile(String filePath)
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties.GetIsForwardingEnabled()
   at System.Net.NetworkInformation.LinuxIPv4InterfaceProperties..ctor(LinuxNetworkInterface linuxNetworkInterface)
   at System.Net.NetworkInformation.LinuxIPInterfaceProperties..ctor(LinuxNetworkInterface lni)
   at System.Net.NetworkInformation.LinuxNetworkInterface..ctor(String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetOrCreate(Dictionary`2 interfaces, String name)
   at System.Net.NetworkInformation.LinuxNetworkInterface.<>c__DisplayClass5_0.<GetLinuxNetworkInterfaces>b__0(String name, IpAddressInfo* ipAddr, IpAddressInfo* maskAddr)
   at Interop.Sys.EnumerateInterfaceAddresses(IPv4AddressDiscoveredCallback ipv4Found, IPv6AddressDiscoveredCallback ipv6Found, LinkLayerAddressDiscoveredCallback linkLayerFound)
   at System.Net.NetworkInformation.LinuxNetworkInterface.GetLinuxNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterfacePal.GetAllNetworkInterfaces()
   at System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces()
   at Sample.Runner.Main()
Aborted (core dumped)
```

**Comment by parjong** [comment]
\CC @lemmaa

**Comment by gkhanna79** [comment]
Can you please file this issue in CoreFX, and close this one, so that we can track it in the correct repo? 

CC @weshaggard

**Comment by parjong** [comment]
@gkhanna79 I'm sorry for late response. It seems that the same issue is already reported in CoreFX as [#9761](https://github.com/dotnet/corefx/issues/9761).

At the beginning, I opened this issue because of the crash discussed above and that crash seems t o be related with CoreCLR (not CoreFX), and thus I would like to maintain this issue separately from the issues in CoreFX.

**Comment by parjong** [comment]
Oh, unfortunately [#9761](https://github.com/dotnet/corefx/issues/9761) is simialr, but not same. I opened a new issue [#11217](https://github.com/dotnet/corefx/issues/11217).
