### ISSUE TITLE
Could not load file or assembly 'System.Runtime, Version=4.1.0.0'

### ISSUE THREAD

**Issue by HamedFathi** [dotnet/coreclr#7154]
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.AppDomain.GetTargetFrameworkName()
```

I am using AssemblyLoadContext in my application so I have "System.Runtime.Loader": "4.0.0" as dependency but after publish my project I have above error.

```
dotnet --version
1.0.0-preview2-003121

{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    },
    "CommandLineArgumentsParser": "3.0.4",
    "System.Runtime.Loader": "4.0.0",
    "Microsoft.Extensions.DependencyModel": "1.0.0",
    "System.Runtime": "4.1.0"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

.NET Framework 4.6.2
```

with visual studio I can run my application but with dotnet command line I have above error.

of course I added System.Runtime.dll in publish folder by hand but I have another exception.

```
Unhandled Exception: System.ArgumentException: A BadImageFormatException has been thrown while parsing the signature. This is likely due to lack of a generic context. Ensure genericTypeArguments and genericMethodArguments are provided and contain enough context. ---> System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (Exception from HRESULT: 0x80131058) ---> System.BadImageFormatException: Cannot load a reference assembly for execution.
   --- End of inner exception stack trace ---
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Attribute.GetCustomAttributes(Assembly element, Type attributeType, Boolean inherit)
   at System.AppDomain.GetTargetFrameworkName()
```

my simple code (using AssemblyLoadContext)
```

           var path = @"?";
            var types = AssemblyLoadContext.Default.LoadFromAssemblyPath(path).GetTypes();
            var list = types.Select(x => x.FullName).ToList();
            foreach (var l in list)
            {
                Console.WriteLine(l);
            }
```

![untitled](https://cloud.githubusercontent.com/assets/8418700/18480720/f39b71ae-79ee-11e6-96d1-d76d8a0c49ee.png)

Can somebody help me ?

**Comment by HamedFathi** [comment]
Can anyone explain about error ?
This is a bug or a problem comes from my code?
If it is a bug Is there an alternative way ?

**Comment by gkhanna79** [comment]
Based upon the exception details above, you have the following message indicating the problem:

`System.BadImageFormatException: Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context`.

You are loading a reference assembly for System.Runtime.Dll instead of the implementation assembly. You can find the latter in the .NET Core installation folder.

**Comment by HamedFathi** [comment]
@gkhanna79 main error is first one , when I saw that error I copied that dll  by hand and error changed. I think when I use dotnet publish all dependency shuld be exist in publish folder but  System.Runtime does not exist. I think you can reproduce problem with my snippet code. anyway Can you guide me about loading unreferenced assembly in specific folder without any problem ?

**Comment by gkhanna79** [comment]
> I think when I use dotnet publish all dependency shuld be exist in publish folder but System.Runtime does not exist.

System.Runtime is part of Microsoft.NETCore.App framework and present in the location where .NET Core is installed. Thus, it is not expected to be published by dotnet to the publish folder. Are you suggesting that when using VS, System.Runtime.dll is published in your app folder? @brthor is this expected?

For https://github.com/dotnet/coreclr/issues/7186, I responded on that issue.

**Comment by brthor** [comment]
I wouldn't expect System.Runtime to be present in your output folder in any case. 

@HamedFathi perhaps VS is using `dotnet build` are you able get it working with `dotnet build` rather than `publish`?

As for System.Runtime, won't this already be loaded when your app is running? Can you just reflect on one of it's types to get it's Assembly object?

**Comment by HamedFathi** [comment]
@brthor  I updated .NET Core to last version 1.0.1 and No problem now !!!
![untitled](https://cloud.githubusercontent.com/assets/8418700/18539122/f5c99b68-7b29-11e6-9493-6e94122c95ad.png)

Microsoft ROCK !!!
Thanks for all of you
