### ISSUE TITLE
RyuJIT x86: [JitStress=2][JitStressRegs=1] JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.exe test fails by timing out.

### ISSUE THREAD

**Issue by sivarv** [dotnet/coreclr#7226]
This test also fails with the same symptom under JitStressRegs=8 alone.
This test also fails with the same symptom under JitStress=2 alone.

```
12:17:31   Raw output file:      D:\j\workspace\x86_ryujit_ch---5e4f5952\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314\b425314.output.txt
12:17:31   Raw output:
12:17:31   BEGIN EXECUTION
12:17:31          "D:\j\workspace\x86_ryujit_ch---5e4f5952\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" b425314.exe 
12:17:31         Timeout: The `CastClass' scenario exceeded the time limit (180s) without reaching the basic work thresholds.
12:17:31         Timeout: The `Unbox' scenario exceeded the time limit (180s) without reaching the basic work thresholds.
12:17:31         GenericMethod: Checks=2411754, Flips=70885513, Elapsed=00:00:03.2559358
12:17:31         4 exceptions were thrown
12:17:31         System.OverflowException: Arithmetic operation resulted in an overflow.
12:17:31            at CastClass.CheckObjects() in D:\j\workspace\x86_ryujit_ch---5e4f5952\tests\src\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.cs:line 483
12:17:31         
12:17:31         
12:17:31         System.Exception: Timeout: The `CastClass' scenario exceeded the time limit (180s) without reaching the basic work thresholds.
12:17:31         
12:17:31         
12:17:31         System.OverflowException: Arithmetic operation resulted in an overflow.
12:17:31            at Unbox.CheckObjects() in D:\j\workspace\x86_ryujit_ch---5e4f5952\tests\src\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.cs:line 624
12:17:31         
12:17:31         
12:17:31         System.Exception: Timeout: The `Unbox' scenario exceeded the time limit (180s) without reaching the basic work thresholds.
12:17:31         
12:17:31         
12:17:31         System.Exception: Failure
12:17:31            at Mutate.Main(String[] args) in D:\j\workspace\x86_ryujit_ch---5e4f5952\tests\src\JIT\Regression\CLR-x86-JIT\V2.0-Beta2\b425314\b425314.cs:line 952
12:17:31         Test FAILED
12:17:31         Expected: 100
12:17:31         Actual: 101
12:17:31         END EXECUTION - FAILED
12:17:31         FAILED
12:17:31         Test Harness Exitcode is : 1
```

Looks to be related to issue https://github.com/dotnet/coreclr/issues/5403

**Comment by adiaaida** [comment]
This does not repro for me locally. It also is not on the list of failing tests for the most recent JitStressRegs=8/JitStress=2 run:

http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_ryujit_checked_windows_nt_jitstress2_jitstressregs8/20/#showFailuresLink
