### ISSUE TITLE
error during standard build

### ISSUE THREAD

**Issue by giuliohome** [dotnet/coreclr#7245]
I've tried a few times but I'm stuck with the following error during the standard build process

```dos
Microsoft Windows [Versione 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tutti i diritti riservati.


C:\Git\coreclr>build -rebuild
BUILD: Commencing CoreCLR Repo build
BUILD: Checking prerequisites
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\VsDevCmd.bat"
Tools are already initialized.
Running: C:\Git\coreclr\Tools\dotnetcli\dotnet.exe C:\Git\coreclr\Tools\run.exe build -Project=C:\Git\coreclr\build.proj -generateHeaderWindows -NativeVersionHeaderFile="C:\Git\coreclr\bin\obj\_version.h" -BuildOS=Window
s_NT -BuildType=Debug -BuildArch=x64  -rebuild

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. Impossibile trovare i
l file specificato.
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
BUILD: Commencing build of native components for Windows_NT.x64.Debug
BUILD: Using environment: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\\..\..\VC\vcvarsall.bat" x86_amd64
BUILD: Regenerating the Visual Studio solution
-- VS_PLATFORM_TOOLSET is v140
-- VS_PLATFORM_NAME is x64
-- VS_WINDOWS_TARGET_PLATFORM_VERSION is
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Git/coreclr/bin/obj/Windows_NT.x64.Debug
Tools are already initialized.
Running: C:\Git\coreclr\Tools\dotnetcli\dotnet.exe C:\Git\coreclr\Tools\run.exe build -Project=C:\Git\coreclr\bin\obj\Windows_NT.x64.Debug\install.vcxproj -MsBuildLog=/flp:Verbosity=normal;LogFile="C:\Git\coreclr\bin\Log
s\CoreCLR_Windows_NT__x64__Debug.log" -MsBuildWrn=/flp1:WarningsOnly;LogFile="C:\Git\coreclr\bin\Logs\CoreCLR_Windows_NT__x64__Debug.wrn" -MsBuildErr=/flp2:ErrorsOnly;LogFile="C:\Git\coreclr\bin\Logs\CoreCLR_Windows_NT__
x64__Debug.err" -configuration=Debug  -BuildOS=Windows_NT -BuildType=Debug -BuildArch=x64  -rebuild

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. Impossibile trovare i
l file specificato.
   at Microsoft.DotNet.Execute.Executor.OpenFile()
   at Microsoft.DotNet.Execute.Executor.Main(String[] args)
BUILD: Error: native component build failed. Refer to the build log files for details:
    "C:\Git\coreclr\bin\Logs\CoreCLR_Windows_NT__x64__Debug.log"
    "C:\Git\coreclr\bin\Logs\CoreCLR_Windows_NT__x64__Debug.wrn"
    "C:\Git\coreclr\bin\Logs\CoreCLR_Windows_NT__x64__Debug.err"
```

**Comment by giuliohome** [comment]
Issue fixed with latest commits
