### ISSUE TITLE
Bug in the ConstructorArguments from CustomAttributes for null array of enum

### ISSUE THREAD

**Issue by giuliohome** [dotnet/coreclr#7346]
There is an issue with a **null** array of enum as CustomAttribute in the constructor (notice that it is ok for an empty array new Test[0] as a workaround).

StackTrace

`   at System.RuntimeTypeHandle.GetTypeByNameUsingCARules(String name, RuntimeModule scope)
   at System.Reflection.CustomAttributeTypedArgument.ResolveType(RuntimeModule scope, String typeName)
   at System.Reflection.CustomAttributeTypedArgument..ctor(RuntimeModule scope, CustomAttributeEncodedArgument encodedArg)
   at System.Reflection.CustomAttributeData.get_ConstructorArguments()`

Here is a full CoreCLR complaint example

```csharp
using System;
using System.Diagnostics;
using System.Reflection;

class Program
{
    [Test(new[] { Test.Foo }, null)]
    static void Main(string[] args)
    {
        var type = typeof(Program);
        var method = type.GetMethod("Main", BindingFlags.Static | BindingFlags.NonPublic);
        var attrEnum = method.CustomAttributes.GetEnumerator();
        attrEnum.MoveNext();
        int count = 0;
        try
        {
            var attr = attrEnum.Current.ConstructorArguments;
            count = attr.Count;
        }
        catch (Exception exc)
        {
            Debug.WriteLine(exc.Message);
            Debug.WriteLine(exc.StackTrace);
        }
        Console.WriteLine("Does the CoreCLR rock? {0}", count == 2);
        Console.ReadKey();
    }
}

public enum Test
{
    Foo,
    Bar
}

[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
public class TestAttribute : Attribute
{
    public TestAttribute(Test[] valuesOne, Test[] valuesTwo)
    {
    }
}
```

**Comment by giuliohome** [comment]
The fix is very simple

```csharp
    if (typeName == null) return (RuntimeType)typeof(object); // just check this, before the following
    RuntimeType type = RuntimeTypeHandle.GetTypeByNameUsingCARules(typeName, scope);
```
Here is a my proposed patch.diff including also a new unit test for this case

```diff
diff --git a/src/mscorlib/src/System/Reflection/CustomAttribute.cs b/src/mscorlib/src/System/Reflection/CustomAttribute.cs
index 463c976..162ab14 100644
--- a/src/mscorlib/src/System/Reflection/CustomAttribute.cs
+++ b/src/mscorlib/src/System/Reflection/CustomAttribute.cs
@@ -800,6 +800,8 @@ namespace System.Reflection
         }
         private static RuntimeType ResolveType(RuntimeModule scope, string typeName)
         {
+            if (typeName == null) return (RuntimeType)typeof(object);
+            
             RuntimeType type = RuntimeTypeHandle.GetTypeByNameUsingCARules(typeName, scope);
 
             if (type == null)
diff --git a/tests/src/readytorun/main.cs b/tests/src/readytorun/main.cs
index cce03b4..e97edfd 100644
--- a/tests/src/readytorun/main.cs
+++ b/tests/src/readytorun/main.cs
@@ -49,8 +49,33 @@ static class OpenClosedDelegateExtension
     }
 }
 
+
+public enum Test
+{
+    Foo,
+    Bar
+}
+
+[AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
+public class TestAttribute : Attribute
+{
+    public TestAttribute(Test[] valuesOne, Test[] valuesTwo)
+    {
+    }
+}
+
 class Program
 {
+    static void TestCtorAttr()
+    {
+        var type = typeof(Program);
+        var method = type.GetMethod("Main", BindingFlags.Static | BindingFlags.NonPublic);
+        var attributeEn = method.CustomAttributes.GetEnumerator();
+        attributeEn.MoveNext();
+        var attribute = attributeEn.Current.ConstructorArguments;
+        Assert.AreEqual(attribute.Count, 2);
+    }
+
     static void TestVirtualMethodCalls()
     {
          var o = new MyClass();
@@ -420,6 +445,7 @@ class Program
 
     static void RunAllTests()
     {
+        TestCtorAttr();
         TestVirtualMethodCalls();
         TestMovedVirtualMethods();
 
@@ -472,6 +498,7 @@ class Program
         GenericLdtokenFieldsTest();
     }
 
+    [Test(new[] { Test.Foo }, null)]
     static int Main()
     {
         // Code compiled by LLILC jit can't catch exceptions yet so the tests
```

**Comment by AtsushiKan** [comment]
This isn't the correct fix as it will cause CustomAttributeTypedArgument.ArgumentType to return the wrong value (Object[] rather than Type[]). (Making null a "legal" input to ResolveType is also case of making a global fix to solve a local problem.)

Since encodedArg probably doesn't contain the necessary information, you'll likely have to get it directly from CustomAttributeData.ConstructorInfo's parameter types. (I assume perf is the reason we don't just do that in the general case.)

Note that CoreRt implements this scenario correctly (including returning "Type[]" from CustomAttributeTypedArgument.ArgumentType)

**Comment by giuliohome** [comment]
Hi @AtsushiKan 
Thank you for your feedback. 

No problem for me to change my proposed fix as per your suggestion.

only one question: I'd assume that `(Object[])null` as well as `(AnyType[])null`  is the same as `null`... Isn't that correct?

I'll look also at the CoreRt implementation.
Thank you again

**Comment by AtsushiKan** [comment]
>I'd assume that (Object[])null as well as (AnyType[])null is the same as null... Isn't that correct?

Yes, but I believe it makes most sense for ArgumentType to return the formal parameter type rather than actual argument type (otherwise, the property doesn’t serve much purpose.)

Note that for non-enum array types (I tested string[]), it works this way for null values.

**Comment by giuliohome** [comment]
@AtsushiKan  Agreed, thanks. Let me review my code, I'll post it back here

**Comment by giuliohome** [comment]
>  (Making null a "legal" input to ResolveType is also case of making a global fix to solve a local problem.)

@AtsushiKan  Well, I guess that _ideally_ [this ](https://github.com/dotnet/coreclr/blob/master/src/vm/customattribute.cpp#L292-L306) should be the first place where to go for a fix:
my idea is that - before the break at Line 298 of vm/customattribute.cpp - we should use `pCaArg->type.cEnumName` ... just speculation, not yet tested (_will do later tonight_) but does it make sense? Your opinion is fundamental.

**Comment by AtsushiKan** [comment]
With the proviso that I haven’t looked at this code until … just now …, it looks to me like we already initialize pCaArg->type to whatever it right at the start of this:

   https://github.com/dotnet/coreclr/blob/master/src/vm/customattribute.cpp#L250

and that whatever it is, pCaArg->type.szEnumName is probably null in this case, given that that’s what popped out on the managed side.

However, this is based on a five minute static look at the code. Stepping through the code and testing is probably the best way to figure out the best path to fixing this.

**Comment by giuliohome** [comment]
> and that whatever it is, pCaArg->type.szEnumName is probably null in this case, given that that’s what popped out on the managed side.

@AtsushiKan ,
Actually, the _cause effect relationship_ is in the opposite direction: `Null `is what popped out on the managed side _because of_ the bug in the native C++ implementation: it is not trivial to step into it... but here it is the calling function from C#

```csharp
        private static extern void ParseAttributeArguments(
            IntPtr pCa, 
            int cCa, 
            ref CustomAttributeCtorParameter[] CustomAttributeCtorParameters,
            ref CustomAttributeNamedParameter[] CustomAttributeTypedArgument,
            RuntimeAssembly assembly);

        [System.Security.SecurityCritical]  // auto-generated
        internal static void ParseAttributeArguments(ConstArray attributeBlob, 
            ref CustomAttributeCtorParameter[] customAttributeCtorParameters,
            ref CustomAttributeNamedParameter[] customAttributeNamedParameters,
            RuntimeModule customAttributeModule)
        {
            if (customAttributeModule == null)
                throw new ArgumentNullException("customAttributeModule");
            Contract.EndContractBlock();

            Contract.Assert(customAttributeCtorParameters != null);
            Contract.Assert(customAttributeNamedParameters != null);

            if (customAttributeCtorParameters.Length != 0 || customAttributeNamedParameters.Length != 0)
            {
                unsafe
                {
                    ParseAttributeArguments(
                        attributeBlob.Signature,
                        (int)attributeBlob.Length,
                        ref customAttributeCtorParameters,
                        ref customAttributeNamedParameters,
                        (RuntimeAssembly)customAttributeModule.Assembly);
                }
            }
        }
        #endregion
```

Debugging this from VS can be tricky, anyway `customAttributeCtorParameters` has a private `m_type` with the `EnumName` **correctly filled** out. 
The `m_encodedArgument.CustomAttributeType.EnumName` should be copied from there. The internal bug is that `elementType.Init` is **skipped** in this case, due to the **early/wrong break** I mentioned above....
`

**Comment by giuliohome** [comment]
> This isn't the correct fix as it will cause CustomAttributeTypedArgument.ArgumentType to return the wrong value (Object[] rather than Type[]). 

the reality is different: what is happening now with the current version is that the method is **crashing**, while my proposed fix is working and returning the correct values (always) and types (when it makes sense, so, except **only** for null values)

Full test below

```csharp
    static void TestCtorAttr()
    {
        var type = typeof(Program);
        var method = type.GetMethod("Main", BindingFlags.Static | BindingFlags.NonPublic);
        var attributeEn = method.CustomAttributes.GetEnumerator();
        attributeEn.MoveNext();
        var attribute = attributeEn.Current.ConstructorArguments;
        Assert.AreEqual(attribute.Count, 2);
        Assert.AreEqual(attribute[0].ArgumentType, typeof(Test[]));
        Assert.AreEqual((Test)(((ReadOnlyCollection<CustomAttributeTypedArgument>)attribute[0].Value)[0].Value), Test.Foo);
        Assert.AreEqual(attribute[1].Value, null); 
        Assert.AreEqual(attribute[1].ArgumentType, typeof(Object)); 
    }
```

**Comment by AtsushiKan** [comment]
As I mentioned earlier, CoreRt (and hence, .NetNative) already implement the correct behavior so this test would fail on those platforms.

In general, a crash in one platform is preferable to two frameworks returning different values for the same scenarios. We’ve already shipped full frameworks with this bug so this isn’t a recent regression.

If this issue is causing an immediate problem for you, feel free to mark the issue “up for grabs” and get some more eyes on it.

**Comment by giuliohome** [comment]
Maybe what I don't understand is if the mscorlib source here is considered as the **reference source** of  [ResolveType](http://referencesource.microsoft.com/#mscorlib/system/reflection/customattribute.cs,eed4fa725ebadcb9): in that case my issue'd be also with .NET Framework 4.6.2 (otherwise this is off topic here)
@AtsushiKan  I guess I'd better accept  your suggestion to put it as "up for grabs" anyway, thanks!

**Comment by AtsushiKan** [comment]
Right, the bug is in .Net 4.6.2. I wouldn’t be surprised if it’s been around since .Net 4.0 – this is a pretty rare corner case.

**Comment by giuliohome** [comment]
Yes, since .Net 4.0, I can confirm this: I also tested this on a machine with only .Net 4.0 installed.

**Comment by giuliohome** [comment]
@AtsushiKan  I think I've found the solution in the meantime! 

Full test (notice that the expectd type is always `Test[]`)

```csharp
    static void TestCtorAttr()
    {
        var type = typeof(Program);
        var method = type.GetMethod("Main", BindingFlags.Static | BindingFlags.NonPublic);
        var attributeEn = method.CustomAttributes.GetEnumerator();
        attributeEn.MoveNext();
        var attribute = attributeEn.Current.ConstructorArguments;
        Assert.AreEqual(attribute.Count, 2);
        Assert.AreEqual(attribute[0].ArgumentType, typeof(Test[]));
        Assert.AreEqual((Test)(((ReadOnlyCollection<CustomAttributeTypedArgument>)attribute[0].Value)[0].Value), Test.Foo);
        Assert.AreEqual(attribute[1].Value, null); 
        // type Test[] also for null value!
        Assert.AreEqual(attribute[1].ArgumentType, typeof(Test[]));
    }
	
    static void RunAllTests()
    {
        TestCtorAttr();
```

My patch.diff

```diff
diff --git a/src/vm/customattribute.cpp b/src/vm/customattribute.cpp
index 48d79a2..899d61c 100644
--- a/src/vm/customattribute.cpp
+++ b/src/vm/customattribute.cpp
@@ -165,32 +165,36 @@ CustomAttributeManagedValues Attribute::GetManagedCaValue(CaValue* pCaVal)
         ULONG length = pCaVal->arr.length;
         BOOL bAllBlittableCa = arrayType != SERIALIZATION_TYPE_ENUM;
 
-        if (length == (ULONG)-1)
-            return gc;
-        
-        gc.array = (CaValueArrayREF)AllocateValueSzArray(MscorlibBinder::GetClass(CLASS__CUSTOM_ATTRIBUTE_ENCODED_ARGUMENT), length);
-        CustomAttributeValue* pValues = gc.array->GetDirectPointerToNonObjectElements();
+		if (length != (ULONG)-1)
+		{
+			gc.array = (CaValueArrayREF)AllocateValueSzArray(MscorlibBinder::GetClass(CLASS__CUSTOM_ATTRIBUTE_ENCODED_ARGUMENT), length);
+			CustomAttributeValue* pValues = gc.array->GetDirectPointerToNonObjectElements();
+
+			for (COUNT_T i = 0; i < length; i++)
+				Attribute::SetBlittableCaValue(&pValues[i], &pCaVal->arr[i], &bAllBlittableCa);
+		}
+
+		if (!bAllBlittableCa)
+		{
+			GCPROTECT_BEGIN(gc)
+			{
+				if (arrayType == SERIALIZATION_TYPE_ENUM)
+					gc.string = StringObject::NewString(pCaVal->type.szEnumName, pCaVal->type.cEnumName);
+
+				if (length != (ULONG)-1) for (COUNT_T i = 0; i < length; i++)
+				{
+					CustomAttributeManagedValues managedCaValue = Attribute::GetManagedCaValue(&pCaVal->arr[i]);
+					Attribute::SetManagedValue(
+						managedCaValue,
+						&gc.array->GetDirectPointerToNonObjectElements()[i]);
+				}
+			}
+			GCPROTECT_END();
+		}
+
+
 
-        for (COUNT_T i = 0; i < length; i ++)
-            Attribute::SetBlittableCaValue(&pValues[i], &pCaVal->arr[i], &bAllBlittableCa); 
 
-        if (!bAllBlittableCa)
-        {
-            GCPROTECT_BEGIN(gc)
-            {   
-                if (arrayType == SERIALIZATION_TYPE_ENUM)
-                    gc.string = StringObject::NewString(pCaVal->type.szEnumName, pCaVal->type.cEnumName);                      
-                
-                for (COUNT_T i = 0; i < length; i ++)
-                {
-                    CustomAttributeManagedValues managedCaValue = Attribute::GetManagedCaValue(&pCaVal->arr[i]);
-                    Attribute::SetManagedValue(
-                        managedCaValue,
-                        &gc.array->GetDirectPointerToNonObjectElements()[i]);
-                }
-            }
-            GCPROTECT_END();
-        }
     }
 
     return gc;
@@ -294,13 +298,13 @@ HRESULT Attribute::ParseCaValue(
         IfFailGo(ca.GetU4(&len));
         pCaArg->arr.length = len;
         pCaArg->arr.pSArray = NULL;
-        if (pCaArg->arr.length == (ULONG)-1)
-            break;
+        //if (pCaArg->arr.length == (ULONG)-1)
+        //    break;
 
         IfNullGo(pCaArg->arr.pSArray = pCaValueArrayFactory->Create()); 
         elementType.Init(pCaArg->type.arrayType, SERIALIZATION_TYPE_UNDEFINED, 
             pCaArg->type.enumType, pCaArg->type.szEnumName, pCaArg->type.cEnumName);
-        for (ULONG i = 0; i < pCaArg->arr.length; i++)
+		if (pCaArg->arr.length != (ULONG)-1) for (ULONG i = 0; i < pCaArg->arr.length; i++)
             IfFailGo(Attribute::ParseCaValue(ca, &*pCaArg->arr.pSArray->Append(), &elementType, pCaValueArrayFactory, pDomainAssembly));
 
         break;
@@ -584,6 +588,7 @@ FCIMPL5(VOID, Attribute::ParseAttributeArguments, void* pCa, INT32 cCa,
                 IfFailGo(Attribute::InitCaType(&gc.pArgs[i].m_type, &sstringFactory, &stackScratchBufferFactory, &caType));
 
                 pCaArgs[i].Init(caType);
+                //pCaArgs[1].val.type.cEnumName = pCaArgs[1].type.cEnumName;
             }
         }
```

**Comment by AtsushiKan** [comment]
Awesome, thanks! When you’re comfortable with the test results, please open a PR.
