### ISSUE TITLE
RyuJIT x86 [JitStress=2][JitStressRegs=1]: JIT\jit64\valuetypes\nullable\castclass\generics\castclass-generics018\castclass-generics018.cmd fails with InvalidOperationException

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#7479]
```
07:59:51 D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(147627): error : JIT._jit64_valuetypes_nullable_castclass_generics_castclass_generics018_castclass_generics018_._jit64_valuetypes_nullable_castclass_generics_castclass_generics018_castclass_generics018_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---0cf1dcc7\tests\runtest.proj]
07:59:51         
07:59:51   Unhandled Exception: System.InvalidOperationException: Nullable object must have a value.
07:59:51            at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
07:59:51            at NullableTest.BoxUnboxToQ[T](T o) in D:\j\workspace\x86_ryujit_ch---0cf1dcc7\tests\src\JIT\jit64\valuetypes\nullable\castclass\generics\castclass-generics018.cs:line 27
07:59:51            at NullableTest.Main() in D:\j\workspace\x86_ryujit_ch---0cf1dcc7\tests\src\JIT\jit64\valuetypes\nullable\castclass\generics\castclass-generics018.cs:line 37
07:59:51   
07:59:51   
07:59:51   Return code:      1
07:59:51   Raw output file:      D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\Reports\JIT\jit64\valuetypes\nullable\castclass\generics\castclass-generics018\castclass-generics018.output.txt
07:59:51   Raw output:
07:59:51   BEGIN EXECUTION
07:59:51          "D:\j\workspace\x86_ryujit_ch---0cf1dcc7\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" castclass-generics018.exe 
07:59:51         Expected: 100
07:59:51         Actual: -532462766
07:59:51         END EXECUTION - FAILED
07:59:51         FAILED
07:59:51         Test Harness Exitcode is : 1
07:59:51         
07:59:51   To run the test:
07:59:51   > set CORE_ROOT=D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
07:59:51   > D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\JIT\jit64\valuetypes\nullable\castclass\generics\castclass-generics018\castclass-generics018.cmd
07:59:51   
07:59:51         Expected: True
07:59:51         Actual:   False
07:59:51           D:\j\workspace\x86_ryujit_ch---0cf1dcc7\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(147627,0): at JIT._jit64_valuetypes_nullable_castclass_generics_castclass_generics018_castclass_generics018_._jit64_valuetypes_nullable_castclass_generics_castclass_generics018_castclass_generics018_cmd()
```

**Comment by pgavlin** [comment]
This is also addressed by #7504.
