### ISSUE TITLE
RyuJIT/x86:  JIT/Methodical/NaN/r4NaNdiv_cs_do fails under GCStress=0xC

### ISSUE THREAD

**Issue by pgavlin** [dotnet/coreclr#7694]
e.g. https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_ryujit_checked_windows_nt_gcstress0xc/9/console

```
21:25:38 D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(267687): error : JIT._Methodical_NaN_r4NaNdiv_cs_do_r4NaNdiv_cs_do_._Methodical_NaN_r4NaNdiv_cs_do_r4NaNdiv_cs_do_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---ddc305d1\tests\runtest.proj]
21:25:38         
21:25:38         Assert failure(PID 3292 [0x00000cdc], Thread: 8176 [0x1ff0]): Precondition failure: FAILED: HasPendingGCStressInstructionUpdate()
21:25:38         
21:25:38         CORECLR! CHECK::Trigger + 0x30E (0x708ea1b9)
21:25:38         CORECLR! Thread::ClearGCStressInstructionUpdate + 0x8D (0x70a35faa)
21:25:38         CORECLR! Thread::CommitGCStressInstructionUpdate + 0x94 (0x70a3605d)
21:25:38         CORECLR! ThreadSuspend::SuspendRuntime + 0xB0C (0x70a3b9fb)
21:25:38         CORECLR! ThreadSuspend::SuspendEE + 0x1C4 (0x70a3ab9b)
21:25:38         CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x3F4 (0x70e84966)
21:25:38         CORECLR! WKS::GCHeap::GarbageCollectTry + 0x59 (0x70e84b36)
21:25:38         CORECLR! WKS::GCHeap::GarbageCollect + 0xAA (0x70e8453a)
21:25:38         CORECLR! WKS::GCHeap::StressHeap + 0x500 (0x70e86f00)
21:25:38         CORECLR! VSD_ResolveWorker + 0x4D8 (0x70b682f9)
21:25:38             File: d:\j\workspace\x86_ryujit_ch---ddc305d1\src\vm\threads.h Line: 5163
21:25:38             Image: D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
21:25:38         
21:25:38         
21:25:38   
21:25:38   Return code:      1
21:25:38   Raw output file:      D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Methodical\NaN\r4NaNdiv_cs_do\r4NaNdiv_cs_do.output.txt
21:25:38   Raw output:
21:25:38   BEGIN EXECUTION
21:25:38          "D:\j\workspace\x86_ryujit_ch---ddc305d1\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" r4NaNdiv_cs_do.exe 
21:25:38         Expected: 100
21:25:38         Actual: 123456789
21:25:38         END EXECUTION - FAILED
21:25:38         FAILED
21:25:38         Test Harness Exitcode is : 1
21:25:38         
21:25:38   To run the test:
21:25:38   > set CORE_ROOT=D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
21:25:38   > D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\JIT\Methodical\NaN\r4NaNdiv_cs_do\r4NaNdiv_cs_do.cmd
21:25:38   
21:25:38         Expected: True
21:25:38         Actual:   False
21:25:38           D:\j\workspace\x86_ryujit_ch---ddc305d1\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(267687,0): at JIT._Methodical_NaN_r4NaNdiv_cs_do_r4NaNdiv_cs_do_._Methodical_NaN_r4NaNdiv_cs_do_r4NaNdiv_cs_do_cmd()
```

Looks like it may be an infrastructural issue. @swaroop-sridhar, any idea?

**Comment by pgavlin** [comment]
There is a similar failure of a different test under GCStress=0xC, JitStress=1: https://ci.dot.net/job/dotnet_coreclr/job/master/job/jitstress/job/x86_ryujit_checked_windows_nt_gcstress0xc_jitstress1/8/console

```
22:27:33 D:\j\workspace\x86_ryujit_ch---59c7f19c\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(207381): error : JIT._Methodical_eh_nested_general_throwinnestedfinally_r_throwinnestedfinally_r_._Methodical_eh_nested_general_throwinnestedfinally_r_throwinnestedfinally_r_cmd [FAIL] [D:\j\workspace\x86_ryujit_ch---59c7f19c\tests\runtest.proj]
22:27:33         
22:27:33         Assert failure(PID 3828 [0x00000ef4], Thread: 3192 [0x0c78]): Precondition failure: FAILED: HasPendingGCStressInstructionUpdate()
22:27:33         
22:27:33         CORECLR! CHECK::Trigger + 0x30E (0x70c7a1b9)
22:27:33         CORECLR! Thread::ClearGCStressInstructionUpdate + 0x8D (0x70dc5faa)
22:27:33         CORECLR! Thread::CommitGCStressInstructionUpdate + 0x94 (0x70dc605d)
22:27:33         CORECLR! ThreadSuspend::SuspendRuntime + 0xB0C (0x70dcb9fb)
22:27:33         CORECLR! ThreadSuspend::SuspendEE + 0x1C4 (0x70dcab9b)
22:27:33         CORECLR! WKS::GCHeap::GarbageCollectGeneration + 0x3F4 (0x71214966)
22:27:33         CORECLR! WKS::GCHeap::GarbageCollectTry + 0x59 (0x71214b36)
22:27:33         CORECLR! WKS::GCHeap::GarbageCollect + 0xAA (0x7121453a)
22:27:33         CORECLR! WKS::GCHeap::StressHeap + 0x500 (0x71216f00)
22:27:33         CORECLR! StubDispatchFixupWorker + 0x20B (0x70ef7bbe)
22:27:33             File: d:\j\workspace\x86_ryujit_ch---59c7f19c\src\vm\threads.h Line: 5163
22:27:33             Image: D:\j\workspace\x86_ryujit_ch---59c7f19c\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\CoreRun.exe
22:27:33         
22:27:33         
22:27:33   
22:27:33   Return code:      1
22:27:33   Raw output file:      D:\j\workspace\x86_ryujit_ch---59c7f19c\bin\tests\Windows_NT.x86.Checked\Reports\JIT\Methodical\eh\nested\general\throwinnestedfinally_r\throwinnestedfinally_r.output.txt
22:27:33   Raw output:
22:27:33   BEGIN EXECUTION
22:27:33          "D:\j\workspace\x86_ryujit_ch---59c7f19c\tests\..\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root\corerun.exe" throwinnestedfinally_r.exe 
22:27:33         Expected: 100
22:27:33         Actual: 123456789
22:27:33         END EXECUTION - FAILED
22:27:33         FAILED
22:27:33         Test Harness Exitcode is : 1
22:27:33         
22:27:33   To run the test:
22:27:33   > set CORE_ROOT=D:\j\workspace\x86_ryujit_ch---59c7f19c\bin\tests\Windows_NT.x86.Checked\Tests\Core_Root
22:27:33   > D:\j\workspace\x86_ryujit_ch---59c7f19c\bin\tests\Windows_NT.x86.Checked\JIT\Methodical\eh\nested\general\throwinnestedfinally_r\throwinnestedfinally_r.cmd
22:27:33   
22:27:33         Expected: True
22:27:33         Actual:   False
22:27:33           D:\j\workspace\x86_ryujit_ch---59c7f19c\bin\tests\Windows_NT.x86.Checked\TestWrappers\JIT\JIT.XUnitWrapper.cs(207381,0): at JIT._Methodical_eh_nested_general_throwinnestedfinally_r_throwinnestedfinally_r_._Methodical_eh_nested_general_throwinnestedfinally_r_throwinnestedfinally_r_cmd()
```

**Comment by swaroop-sridhar** [comment]
This is a known race condition in the GcStress  0xC infrastructure in the VM.

________________________________

**Comment by swaroop-sridhar** [comment]
@pgavlin  is this failure deterministic for the same test? 
If so, this is a better case to investigate.

**Comment by pgavlin** [comment]
@swaroop-sridhar I don't believe that these failures are deterministic. I'll re-run the jobs to check.

**Comment by pgavlin** [comment]
Indeed, these failures are not deterministic in nature.

**Comment by kouvel** [comment]
Closing in favor of https://github.com/dotnet/coreclr/issues/5310, which covers GCStress instruction update races
