### ISSUE TITLE
Segmentation fault in GC code on Linux while running an exception test

### ISSUE THREAD

**Issue by sergiy-k** [dotnet/coreclr#770]
On Linux we get a crash in GC when the following code is executed in a loop:

```CSharp
public static void Rethrow()
{
    try
    {
        try
        {
            try
            {
                Console.WriteLine("Throwing an exception");
                throw new Exception("Did you catch it in the right handler?");
            }
            catch (IndexOutOfRangeException e)
            {
                Console.WriteLine("Test Rethrow: Failed. Called wrong handler.\n" + e.ToString());
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Test Rethrow: Caught exception!\n" + ex.ToString());
            throw;
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine("Test Rethrow: success! Caught re-thrown exception!\n" + ex.ToString());
    }
}
```

Here is the call stack:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5555f06 in MethodTable::GetFlag (this=0x64006f0063006c, flag=MethodTable::enum_flag_HasComponentSize) at /home/sk/git/coreclr/src/vm/methodtable.h:3962
3962            return m_dwFlags & flag;
(gdb) bt
#0  0x00007ffff5555f06 in MethodTable::GetFlag (this=0x64006f0063006c, flag=MethodTable::enum_flag_HasComponentSize) at /home/sk/git/coreclr/src/vm/methodtable.h:3962
#1  0x00007ffff555f8d1 in MethodTable::HasComponentSize (this=0x64006f0063006c) at /home/sk/git/coreclr/src/vm/methodtable.h:1718
#2  0x00007ffff55a804c in MethodTable::GetComponentSize (this=0x64006f0063006c) at /home/sk/git/coreclr/src/vm/methodtable.h:1740
#3  0x00007ffff589a58d in MethodTable::SanityCheck (this=0x64006f0063006c) at /home/sk/git/coreclr/src/vm/methodtable.cpp:6814
#4  0x00007ffff589e309 in MethodTable::Validate (this=0x64006f0063006c) at /home/sk/git/coreclr/src/vm/methodtable.cpp:8934
#5  0x00007ffff58a664f in Object::ValidateInner (this=0x7fffcc02d6b8, bDeep=1, bVerifyNextHeader=1, bVerifySyncBlock=1) at /home/sk/git/coreclr/src/vm/object.cpp:1662
#6  0x00007ffff58a5d2c in Object::Validate (this=0x7fffcc02d6b8, bDeep=1, bVerifyNextHeader=1, bVerifySyncBlock=1) at /home/sk/git/coreclr/src/vm/object.cpp:1639
#7  0x00007ffff58a5b2e in Object::ValidatePromote (this=0x7fffcc02d6b8, sc=0x7fffffffadb8, flags=0) at /home/sk/git/coreclr/src/vm/object.cpp:1322
#8  0x00007ffff57d5658 in WKS::GCHeap::Promote (ppObject=0x7fffffffddb0, sc=0x7fffffffadb8, flags=0) at /home/sk/git/coreclr/src/gc/gc.cpp:33321
#9  0x00007ffff56c8304 in GCFrame::GcScanRoots (this=0x7fffffffdd80, fn=0x7ffff57d53a0 <WKS::GCHeap::Promote(Object**, ScanContext*, unsigned int)>, sc=0x7fffffffadb8) at /home/sk/git/coreclr/src/vm/frames.cpp:1000
#10 0x00007ffff59d1daf in GcStackCrawlCallBack (pCF=0x7fffffff9690, pData=0x7fffffffabb0) at /home/sk/git/coreclr/src/vm/gcenv.cpp:229
#11 0x00007ffff58e202c in Thread::MakeStackwalkerCallback (this=0x64fdb8, pCF=0x7fffffff9690, pCallback=0x7ffff59d1830 <GcStackCrawlCallBack(CrawlFrame*, void*)>, pData=0x7fffffffabb0, uFramesProcessed=12)
    at /home/sk/git/coreclr/src/vm/stackwalk.cpp:886
#12 0x00007ffff58e223d in Thread::StackWalkFramesEx (this=0x64fdb8, pRD=0x7fffffff9a70, pCallback=0x7ffff59d1830 <GcStackCrawlCallBack(CrawlFrame*, void*)>, pData=0x7fffffffabb0, flags=34048, pStartFrame=0x0)
    at /home/sk/git/coreclr/src/vm/stackwalk.cpp:967
#13 0x00007ffff58e2ca9 in Thread::StackWalkFrames (this=0x64fdb8, pCallback=0x7ffff59d1830 <GcStackCrawlCallBack(CrawlFrame*, void*)>, pData=0x7fffffffabb0, flags=34048, pStartFrame=0x0) at /home/sk/git/coreclr/src/vm/stackwalk.cpp:1050
#14 0x00007ffff59d26ea in GCToEEInterface::ScanStackRoots (pThread=0x64fdb8, fn=0x7ffff57d53a0 <WKS::GCHeap::Promote(Object**, ScanContext*, unsigned int)>, sc=0x7fffffffadb8) at /home/sk/git/coreclr/src/vm/gcenv.cpp:448
#15 0x00007ffff56cd1eb in CNameSpace::GcScanRoots (fn=0x7ffff57d53a0 <WKS::GCHeap::Promote(Object**, ScanContext*, unsigned int)>, condemned=0, max_gen=2, sc=0x7fffffffadb8) at /home/sk/git/coreclr/src/gc/gcscan.cpp:191
#16 0x00007ffff57b6d99 in WKS::gc_heap::mark_phase (condemned_gen_number=0, mark_only_p=0) at /home/sk/git/coreclr/src/gc/gc.cpp:19070
#17 0x00007ffff57afcbb in WKS::gc_heap::gc1 () at /home/sk/git/coreclr/src/gc/gc.cpp:14867
#18 0x00007ffff57c8fa2 in WKS::gc_heap::garbage_collect (n=0) at /home/sk/git/coreclr/src/gc/gc.cpp:16393
#19 0x00007ffff57a5985 in WKS::GCHeap::GarbageCollectGeneration (this=0x653378, gen=0, reason=WKS::reason_alloc_soh) at /home/sk/git/coreclr/src/gc/gc.cpp:34647
#20 0x00007ffff57a8de9 in WKS::gc_heap::try_allocate_more_space (acontext=0x64fe18, size=280, gen_number=0) at /home/sk/git/coreclr/src/gc/gc.cpp:12689
#21 0x00007ffff57a8f23 in WKS::gc_heap::allocate_more_space (acontext=0x64fe18, size=280, alloc_generation_number=0) at /home/sk/git/coreclr/src/gc/gc.cpp:12997
#22 0x00007ffff5819ad9 in WKS::gc_heap::allocate (jsize=274, acontext=0x64fe18) at /home/sk/git/coreclr/src/gc/gc.cpp:13028
#23 0x00007ffff580856a in WKS::GCHeap::Alloc (this=0x653378, acontext=0x64fe18, size=274, flags=0) at /home/sk/git/coreclr/src/gc/gc.cpp:34113
#24 0x00007ffff59d5287 in Alloc (size=274, bFinalize=0, bContainsPointers=0) at /home/sk/git/coreclr/src/vm/gchelpers.cpp:106
#25 0x00007ffff59d417c in FastAllocatePrimitiveArray (pMT=0x7ffff1f464f0, cElements=125, bAllocateInLargeHeap=0) at /home/sk/git/coreclr/src/vm/gchelpers.cpp:642
#26 0x00007ffff59ff83b in JIT_NewArr1 (arrayTypeHnd_=0x7ffff1f35da2, size=125) at /home/sk/git/coreclr/src/vm/jithelpers.cpp:3088
#27 0x00007ffff2035d72 in ?? ()
#28 0x00007fffffffb8e0 in ?? ()
#29 0x00007fffcc50d358 in ?? ()
#30 0x0000000000000000 in ?? ()
```

**Comment by janvorli** [comment]
Fixed by #794
