### ISSUE TITLE
Strange ToString output

### ISSUE THREAD

**Issue by litichevskiydv** [dotnet/coreclr#7728]
Nearly every four days I have strange exception in my program in class [`FieldElement`](https://github.com/litichevskiydv/GfPolynoms/blob/master/src/AppliedAlgebra.GfPolynoms/FieldElement.cs)

```
AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program Error on processing sample [(1,0),(6,0),(9,1),(8,0),(12,0),(26,0),(16,1),(14,0),(20,24),(7,0),(15,0),(17,0),(11,0),(2,0),(3,0),(18,2),(4,12),(24,0),(13,0),(23,0),(25,0),(10,0),(5,17),(21,0),(22,0),(19,0)]
 System.ArgumentException: Field 12 is not compatible to field GF27, irreducible polynomial 2+2x+x^3
   at AppliedAlgebra.GfPolynoms.FieldElement.ValidateArgument(FieldElement b) in /root/GfPolynoms/src/GfPolynoms/FieldElement.cs:line 16
   at AppliedAlgebra.GfPolynoms.FieldElement.Subtract(FieldElement b) in /root/GfPolynoms/src/GfPolynoms/FieldElement.cs:line 70
   at AppliedAlgebra.GfAlgorithms.LinearSystemSolver.GaussSolver.TransformSystemToTriangularView(FieldElement[,] a, FieldElement[] b) in /root/GfPolynoms/src/GfAlgorithms/LinearSystemSolver/GaussSolver.cs:line 50
   at AppliedAlgebra.GfAlgorithms.LinearSystemSolver.GaussSolver.Solve(FieldElement[,] a, FieldElement[] b) in /root/GfPolynoms/src/GfAlgorithms/LinearSystemSolver/GaussSolver.cs:line 114
   at AppliedAlgebra.WaveletCodesTools.ListDecoderForFixedDistanceCodes.GsBasedDecoder.SelectCorrectInformationPolynomials(Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, Int32 generationPolynomialLeadZeroValuesCount, IReadOnlyList`1 decodedCodeword, IEnumerable`1 frequencyDecodingResults) in /root/GfPolynoms/src/WaveletCodesTools/ListDecoderForFixedDistanceCodes/GsBasedDecoder.cs:line 74
   at AppliedAlgebra.WaveletCodesTools.ListDecoderForFixedDistanceCodes.GsBasedDecoder.Decode(Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, Tuple`2[] decodedCodeword, Int32 minCorrectValuesCount) in /root/GfPolynoms/src/WaveletCodesTools/ListDecoderForFixedDistanceCodes/GsBasedDecoder.cs:line 100
   at AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program.PlaceNoiseIntoSamplesAndDecode(AnalyzingSample sample, Int32 currentErrorNumber, Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, GsBasedDecoder decoder) in /root/GfPolynoms/src/Utils/WaveletCodesListDecodingAnalyzer/Program.cs:line 91
   at AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program.PlaceNoiseIntoSamplesAndDecode(AnalyzingSample sample, Int32 currentErrorNumber, Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, GsBasedDecoder decoder) in /root/GfPolynoms/src/Utils/WaveletCodesListDecodingAnalyzer/Program.cs:line 112
   at AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program.PlaceNoiseIntoSamplesAndDecode(AnalyzingSample sample, Int32 currentErrorNumber, Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, GsBasedDecoder decoder) in /root/GfPolynoms/src/Utils/WaveletCodesListDecodingAnalyzer/Program.cs:line 112
   at AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program.PlaceNoiseIntoSamplesAndDecode(AnalyzingSample sample, Int32 currentErrorNumber, Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, GsBasedDecoder decoder) in /root/GfPolynoms/src/Utils/WaveletCodesListDecodingAnalyzer/Program.cs:line 112
   at AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program.PlaceNoiseIntoSamplesAndDecode(AnalyzingSample sample, Int32 currentErrorNumber, Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, GsBasedDecoder decoder) in /root/GfPolynoms/src/Utils/WaveletCodesListDecodingAnalyzer/Program.cs:line 112
   at AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program.PlaceNoiseIntoSamplesAndDecode(AnalyzingSample sample, Int32 currentErrorNumber, Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, GsBasedDecoder decoder) in /root/GfPolynoms/src/Utils/WaveletCodesListDecodingAnalyzer/Program.cs:line 112
   at AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program.PlaceNoiseIntoSamplesAndDecode(AnalyzingSample sample, Int32 currentErrorNumber, Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, GsBasedDecoder decoder) in /root/GfPolynoms/src/Utils/WaveletCodesListDecodingAnalyzer/Program.cs:line 112
   at AppliedAlgebra.WaveletCodesListDecodingAnalyzer.Program.PlaceNoiseIntoSamplesAndDecodeWrapperForParallelRunning(AnalyzingSample sample, Int32 n, Int32 k, Int32 d, Polynomial generatingPolynomial, GsBasedDecoder decoder) in /root/GfPolynoms/src/Utils/WaveletCodesListDecodingAnalyzer/Program.cs:line 130
```

This looks strange because both `ToString` methods in classes [`PrimeOrderField`](https://github.com/litichevskiydv/GfPolynoms/blob/master/src/AppliedAlgebra.GfPolynoms/GaloisFields/PrimeOrderField.cs) and [`PrimePowerOrderField`](https://github.com/litichevskiydv/GfPolynoms/blob/master/src/AppliedAlgebra.GfPolynoms/GaloisFields/PrimePowerOrderField.cs) return message starts from symbols "GF" and here I have 12.

Moreover, I can't reproduce this exception in tests and then I recalculate sample there it happens everything works well.
## Environment

OS: Ubuntu 16.04 64bit,
dotnet: 1.0.0-preview2-003131.

Program lives [here](https://github.com/litichevskiydv/GfPolynoms/tree/master/src/Utils/WaveletCodesListDecodingAnalyzer), I start it by command `dotnet run -c Release`

**Comment by janvorli** [comment]
@litichevskiydv so if I read it correctly, it behaves as if it was calling ToString from the base class?
Can you try to add  GetType(this) into the exception message to see what the runtime thinks about the type of the object at the failure point?

**Comment by litichevskiydv** [comment]
@janvorli, yes you right. I added changes you suggested and updated code on server. 
Yesterday I've updated dotnet version on server, now it is 1.0.0-preview2-1-003177, and program uses .NET Core 1.1.
Now I'm waiting :smiley:

**Comment by litichevskiydv** [comment]
Everything has worked fine for more than 3 weeks, I'm going to close the issue.
