### ISSUE TITLE
Serialization and Raytracer performance tests are not posting results

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/coreclr#8027]
These two tests are not being run.  I need to investigate why they are failing and get them working.

**Comment by AndyAyersMS** [comment]
Serialize (and likely Deserialize) are failing with reflection-related errors similar to those encountered before the netstandard1.4 update. I tried bumping Json.Net to 9.0.1 but that didn't help.
```
CoreCLR>xunit.performance.run.exe Serialize.exe -runner xunit.console.netcore.exe -runnerhost corerun.exe -verbose -runid perf-Serialize  1>Serialize.out
Could not find constructor for 'Xunit.Sdk.CollectionPerClassTestCollectionFactory' with arguments type(s): Xunit.Sdk.TestAssembly
Error: Could not load type 'System.Object' from assembly 'System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' because the parent does not exist.
   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
...etc...
```

**Comment by AndyAyersMS** [comment]
Raytracer runs just fine for me locally under xunit-perf.

**Comment by RussKeldorph** [comment]
@sandreenko FYI.  RayTracer problem may be specific to SuperPMI.

**Comment by danmosemsft** [comment]
@valenis @DrewScoggins is this planned for the 2.0 release? if not please move to future.

**Comment by DrewScoggins** [comment]
This was fixed by moving to the new perf runner about 2 months ago, this PR https://github.com/dotnet/coreclr/pull/9947
