### ISSUE TITLE
Failure in keepalive test reading meminfo

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/coreclr#8061]
File.ReadAllLines uses FileAccess.Read. I guess someone else is writing?

```
03:09:09 FAILED   - GC/LargeMemory/API/gc/keepalive/keepalive.sh
03:09:09                BEGIN EXECUTION
03:09:09                /mnt/j/workspace/dotnet_coreclr/master/checked_ubuntu_tst_prtest/bin/tests/Windows_NT.x64.Checked/Tests/coreoverlay/corerun keepalive.exe 2048
03:09:09                
03:09:09                Unhandled Exception: System.IO.IOException: The process cannot access the file '/proc/meminfo' because it is being used by another process.
03:09:09                   at System.IO.FileStream.Init(FileMode mode, FileShare share)
03:09:09                   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
03:09:09                   at System.IO.File.Open(String path, FileMode mode, FileAccess access)
03:09:09                   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
03:09:09                   at System.IO.File.InternalReadAllLines(String path, Encoding encoding)
03:09:09                   at MemCheck.GetPhysicalMem()
03:09:09                   at KeepAliveTest.Main(String[] args)
03:09:09                ./keepalive.sh: line 124: 59062 Aborted                 (core dumped) $_DebuggerFullPath "$CORE_ROOT/corerun" keepalive.exe $CLRTestExecutionArguments
03:09:09                Expected: 100
03:09:09                Actual: 134
03:09:09                END EXECUTION - FAILED
```

https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_ubuntu_tst_prtest/1378/consoleFull#2096352037c7af6a29-b465-404a-b249-90a3911e4354
https://github.com/dotnet/coreclr/pull/8019

**Comment by stephentoub** [comment]
This looks like https://github.com/dotnet/corefx/pull/13459.

**Comment by danmosemsft** [comment]
Ah - I bet.
