### ISSUE TITLE
RyuJIT/x86: CoreFx System.Xml.XmlSerializer.Tests

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8165]
**Repro steps:**

coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -TestNugetRuntimeId=win7-x86 -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Xml.XmlSerializer.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
RunTests.cmd c:\git\corefx\packages
```
**Output**
```
Using c:\git\corefx\packages as folder for resolving package dependencies.
Executing in C:\git\corefx\bin\tests\AnyOS.AnyCPU.Release\System.Xml.XmlSerializer.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 17:12:47.65
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Xml.XmlSerializer.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Xml.XmlSerializer.Tests
Discovered:  System.Xml.XmlSerializer.Tests
Starting:    System.Xml.XmlSerializer.Tests
   XmlSerializerTests.Xml_TimeSpanAsRoot [FAIL]
      System.InvalidOperationException : There was an error generating the XML document.
      ---- System.OverflowException : Arithmetic operation resulted in an overflow.
      Stack Trace:
            at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
            at System.Xml.Serialization.XmlSerializer.Serialize(Stream stream, Object o, XmlSerializerNamespaces namespaces)
            at XmlSerializerTests.SerializeAndDeserialize[T](T value, String baseline, Func`1 serializerFactory, Boolean skipStringCompare, XmlSerializerNamespaces xns)
            at XmlSerializerTests.Xml_TimeSpanAsRoot()
         ----- Inner Stack Trace -----
            at System.Xml.Schema.XsdDuration..ctor(TimeSpan timeSpan, DurationType durationType)
            at System.Xml.XmlConvert.ToString(TimeSpan value)
            at System.Xml.Serialization.XmlSerializationPrimitiveWriter.Write_TimeSpan(Object o)
            at System.Xml.Serialization.XmlSerializer.SerializePrimitive(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces)
            at System.Xml.Serialization.XmlSerializer.Serialize(XmlWriter xmlWriter, Object o, XmlSerializerNamespaces namespaces, String encodingStyle, String id)
Finished:    System.Xml.XmlSerializer.Tests

=== TEST EXECUTION SUMMARY ===
   System.Xml.XmlSerializer.Tests  Total: 129, Errors: 0, Failed: 1, Skipped: 0, Time: 35.971s
Finished running tests.  End time=17:13:32.45, Exit code = 1
```

**Comment by mikedn** [comment]
Likely a dupe of #8170. The stack trace is different but the `OverflowException` is thrown from the same 
`XsdDuration..ctor` like in the other test.

**Comment by RussKeldorph** [comment]
Closing as dup.
