### ISSUE TITLE
RyuJIT/x86: CoreFx System.Runtime.Serialization.Json.ReflectionOnly.Tests System.OverflowException

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8168]
**Repro steps:**

coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -TestNugetRuntimeId=win7-x86 -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Serialization.Json.ReflectionOnly.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
RunTests.cmd c:\git\corefx\packages
```
**Output**
```
Using c:\git\corefx\packages as folder for resolving package dependencies.
Executing in C:\git\corefx\bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Serialization.Json.ReflectionOnly.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 17:44:47.89
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Runtime.Serialization.Json.ReflectionOnly.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Serialization.Json.ReflectionOnly.Tests
Discovered:  System.Runtime.Serialization.Json.ReflectionOnly.Tests
Starting:    System.Runtime.Serialization.Json.ReflectionOnly.Tests
   DataContractJsonSerializerTests.DCJS_TimeSpanAsRoot [FAIL]
      System.OverflowException : Arithmetic operation resulted in an overflow.
      Stack Trace:
            at System.Xml.Schema.XsdDuration..ctor(TimeSpan timeSpan, DurationType durationType)
            at System.Xml.XmlConvert.ToString(TimeSpan value)
            at System.Runtime.Serialization.TimeSpanDataContract.WriteXmlValue(XmlWriterDelegator writer, Object obj, XmlObjectSerializerWriteContext context)
            at System.Runtime.Serialization.Json.JsonDataContract.WriteJsonValueCore(XmlWriterDelegator jsonWriter, Object obj, XmlObjectSerializerWriteContextComplexJson context, RuntimeTypeHandle declaredTypeHandle)
            at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph)
            at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.InternalWriteObject(XmlWriterDelegator writer, Object graph)
            at System.Runtime.Serialization.XmlObjectSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(XmlDictionaryWriter writer, Object graph)
            at System.Runtime.Serialization.Json.DataContractJsonSerializerImpl.WriteObject(Stream stream, Object graph)
            at System.Runtime.Serialization.Json.DataContractJsonSerializer.WriteObject(Stream stream, Object graph)
            at DataContractJsonSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractJsonSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
            at DataContractJsonSerializerTests.DCJS_TimeSpanAsRoot()
Finished:    System.Runtime.Serialization.Json.ReflectionOnly.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Serialization.Json.ReflectionOnly.Tests  Total: 146, Errors: 0, Failed: 1, Skipped: 0, Time: 16.581s
Finished running tests.  End time=17:45:13.47, Exit code = 1
```

**Comment by mikedn** [comment]
Likely a dupe of #8170. `XsdDuration..ctor` doesn't contain any other code that could throw `OverflowException`.

**Comment by RussKeldorph** [comment]
Closing as dup.
