### ISSUE TITLE
RyuJIT/x86: CoreFx System.Runtime.Serialization.Xml.Tests System.OverflowException

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8169]
**Repro steps:**

coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -TestNugetRuntimeId=win7-x86 -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Serialization.Xml.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
RunTests.cmd c:\git\corefx\packages
```
**Output**
```
Using c:\git\corefx\packages as folder for resolving package dependencies.
Executing in C:\git\corefx\bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Serialization.Xml.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 17:48:53.04
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Runtime.Serialization.Xml.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Serialization.Xml.Tests
Discovered:  System.Runtime.Serialization.Xml.Tests
Starting:    System.Runtime.Serialization.Xml.Tests
Ok, stream released right after WriteValue
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
   DataContractSerializerTests.DCS_TimeSpanAsRoot [FAIL]
      System.OverflowException : Arithmetic operation resulted in an overflow.
      Stack Trace:
            at System.Xml.Schema.XsdDuration..ctor(TimeSpan timeSpan, DurationType durationType)
            at System.Xml.XmlConvert.ToString(TimeSpan value)
            at System.Runtime.Serialization.TimeSpanDataContract.WriteXmlValue(XmlWriterDelegator writer, Object obj, XmlObjectSerializerWriteContext context)
            at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)
            at DataContractSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
            at DataContractSerializerTests.DCS_TimeSpanAsRoot()
Finished:    System.Runtime.Serialization.Xml.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Serialization.Xml.Tests  Total: 192, Errors: 0, Failed: 1, Skipped: 0, Time: 20.903s
Finished running tests.  End time=17:49:23.45, Exit code = 1
```

**Comment by mikedn** [comment]
Likely a dupe of #8170. `XsdDuration..ctor` doesn't contain any other code that could throw `OverflowException`.

**Comment by RussKeldorph** [comment]
Closing as dup.
