### ISSUE TITLE
RyuJIT/x86: CoreFx System.Runtime.Serialization.Xml.ReflectionOnly.Tests System.OverflowException

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8170]
**Repro steps:**

coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -TestNugetRuntimeId=win7-x86 -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Serialization.Xml.ReflectionOnly.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
RunTests.cmd c:\git\corefx\packages
```
**Output**
```
Using c:\git\corefx\packages as folder for resolving package dependencies.
Executing in C:\git\corefx\bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Serialization.Xml.ReflectionOnly.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 17:53:12.45
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Runtime.Serialization.Xml.ReflectionOnly.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Serialization.Xml.ReflectionOnly.Tests
Discovered:  System.Runtime.Serialization.Xml.ReflectionOnly.Tests
Starting:    System.Runtime.Serialization.Xml.ReflectionOnly.Tests
Ok, stream released right after WriteValue
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
Ok, stream released right after WriteValue
Ok, stream released right after AsyncWriteValue
Ok, stream released right after AsyncWriteValueBase64
   DataContractSerializerTests.DCS_TimeSpanAsRoot [FAIL]
      System.OverflowException : Arithmetic operation resulted in an overflow.
      Stack Trace:
            at System.Xml.Schema.XsdDuration..ctor(TimeSpan timeSpan, DurationType durationType)
            at System.Xml.XmlConvert.ToString(TimeSpan value)
            at System.Runtime.Serialization.TimeSpanDataContract.WriteXmlValue(XmlWriterDelegator writer, Object obj, XmlObjectSerializerWriteContext context)
            at System.Runtime.Serialization.DataContractSerializer.InternalWriteObjectContent(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.DataContractSerializer.InternalWriteObject(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObjectHandleExceptions(XmlWriterDelegator writer, Object graph, DataContractResolver dataContractResolver)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(XmlDictionaryWriter writer, Object graph)
            at System.Runtime.Serialization.XmlObjectSerializer.WriteObject(Stream stream, Object graph)
            at DataContractSerializerTests.SerializeAndDeserialize[T](T value, String baseline, DataContractSerializerSettings settings, Func`1 serializerFactory, Boolean skipStringCompare)
            at DataContractSerializerTests.DCS_TimeSpanAsRoot()
Finished:    System.Runtime.Serialization.Xml.ReflectionOnly.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Serialization.Xml.ReflectionOnly.Tests  Total: 187, Errors: 0, Failed: 1, Skipped: 0, Time: 21.772s
Finished running tests.  End time=17:53:43.89, Exit code = 1
```

**Comment by mikedn** [comment]
Looks like long div/mod handling is broken. Code like
```C#
_nanoseconds = (uint)(ticksPos % 10000000) * 100;
```
generates
```
G_M55886_IG02:
       8B4508       mov      eax, dword ptr [ebp+08H]
       8B550C       mov      edx, dword ptr [ebp+0CH]
       B980969800   mov      ecx, 0x989680
       F7F1         div      edx:eax, ecx
       33C0         xor      eax, eax
       8BC2         mov      eax, edx
       6BC064       imul     eax, eax, 100
```
For large dividend values `div` throws an overflow exception because the result doesn't fit into 32 bit. But the result is supposed to be 64 bit here, a correct implementation shouldn't throw.

**Comment by mikedn** [comment]
JIT32 generates this:
```
G_M55886_IG02:
       8B4508       mov      eax, dword ptr [ebp+08H]
       8B550C       mov      edx, dword ptr [ebp+0CH]
       B980969800   mov      ecx, 0x989680
       3BD1         cmp      edx, ecx
       720A         jb       SHORT G_M55886_IG03
       8BD8         mov      ebx, eax
       8BC2         mov      eax, edx
       33D2         xor      edx, edx
       F7F1         div      edx:eax, ecx
       8BC3         mov      eax, ebx

G_M55886_IG03:
       F7F1         div      edx:eax, ecx
       6BC264       imul     eax, edx, 100
       33D2         xor      edx, edx
```
This won't be an easy fix if we want to continue not using a helper. The BB needs to be split in two and we don't currently have any utility to do that. Such expansion will probably need to be deferred to codegen.

**Comment by RussKeldorph** [comment]
@mikedn Thanks for the analysis!
/cc @dotnet/jit-contrib

**Comment by pgavlin** [comment]
> @mikedn Thanks for the analysis!

Seconded :)

I can take this one.

**Comment by pgavlin** [comment]
After further investigation, this is indeed specific to trees with either of the following forms:
- `(mod ulong (x ulong) (cast ulong (const int const_val)))`
- `(mod ulong (x ulong) (const ulong const_val))`
where `const_val` is in the range `[2, 0x3ffffffff]`. All other long-typed div/mod trees use a helper.

I see two options here:
1. Just use a helper in these cases. We will give up a bit of code quality for the sake of expediency.
2. Change the decomposition and code generation for long umod to the JIT32/legacy backend style.

@mikedn @dotnet/jit-contrib opinions?

**Comment by pgavlin** [comment]
Of course, there is also the third option: add an LIR utility to allow splitting a block at an arbitrary point and change decomposition to use it in this case. This is not terribly difficult, but the split operation is non-trivial as it involves finding all SDSU temps that would be live across the block boundary and spilling them to lclVars.

**Comment by mikedn** [comment]
I'd go with the helper call for now. This seems kind of rare (and the team seems to think the same way as they didn't implement magic division for unsigned types :grin:) and there are other CQ issues related to long on x86 that are probably more worthwhile to spend time on.

**Comment by pgavlin** [comment]
@mikedn: it ended up being pretty trivial to expand this correctly in codegen. https://github.com/dotnet/coreclr/pull/8198 has the changes.
