### ISSUE TITLE
RyuJIT/x86: CoreFx System.Runtime.Numerics.Tests bad output

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8171]
**Repro steps:**

coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -TestNugetRuntimeId=win7-x86 -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Numerics.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
RunTests.cmd c:\git\corefx\packages
```
**Output**
<details>
```
Using c:\git\corefx\packages as folder for resolving package dependencies.
Executing in C:\git\corefx\bin\tests\AnyOS.AnyCPU.Release\System.Runtime.Numerics.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 17:56:21.12
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Runtime.Numerics.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.Numerics.Tests
Discovered:  System.Runtime.Numerics.Tests
Starting:    System.Runtime.Numerics.Tests
   System.Numerics.Tests.powTest.RunPowPositive [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 25)
      Expected: ┬╖┬╖┬╖7683008515512768521713650302149162161179979006561675774412070┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖7683008515512768521739095889163876024558036744685930462639169┬╖┬╖┬╖
                                       Γåæ (pos 25)
      Stack Trace:
            at System.Numerics.Tests.powTest.VerifyPowString(String opstring)
            at System.Numerics.Tests.powTest.RunPowPositive()
   System.Numerics.Tests.ComplexTests.Sin_Advanced [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.ComplexTests.Cos_Advanced [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.modpowTest.ModPowAxiom [FAIL]
      Assert.Equal() Failure
                Γåô (pos 0)
      Expected: 35756117882162760394883167857088395196910┬╖┬╖┬╖
      Actual:   -33
                Γåæ (pos 0)
      Stack Trace:
            at System.Numerics.Tests.modpowTest.VerifyIdentityString(String opstring1, String opstring2)
            at System.Numerics.Tests.modpowTest.ModPowAxiom()
   System.Numerics.Tests.ComplexTests.Exp [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.ComplexTests.Cosh_Advanced [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.op_multiplyTest.RunMultiplyPositive [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 36)
      Expected: ┬╖┬╖┬╖6701045775033882228017334052661935847075464271800991226528542┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖6701045775033882228031500595866449599217042886593059041068755┬╖┬╖┬╖
                                       Γåæ (pos 36)
      Stack Trace:
            at System.Numerics.Tests.op_multiplyTest.VerifyMultiplyString(String opstring)
            at System.Numerics.Tests.op_multiplyTest.RunMultiplyPositive()
   System.Numerics.Tests.op_multiplyTest.RunMultiplyTests [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 26)
      Expected: ┬╖┬╖┬╖2278240356085911958312282048585909376613748417042912784564252┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖2278240356085911958309821985470873874364021968865128885235425┬╖┬╖┬╖
                                       Γåæ (pos 26)
      Stack Trace:
            at System.Numerics.Tests.op_multiplyTest.VerifyMultiplyString(String opstring)
            at System.Numerics.Tests.op_multiplyTest.RunMultiplyTests()
   System.Numerics.Tests.ComplexTests.Sinh_Advanced [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers_Threshold [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 36)
      Expected: ┬╖┬╖┬╖6701045775033882228017334052661935847075464271801170033442122┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖6701045775033882228031500595866449599217042886593059041068755┬╖┬╖┬╖
                                       Γåæ (pos 36)
      Stack Trace:
            at System.Numerics.Tests.multiplyTest.VerifyMultiplyString(String opstring)
            at System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers()
            at BigIntTools.Utils.RunWithFakeThreshold(String name, Int32 value, Action action)
            at System.Numerics.Tests.multiplyTest.<>c.<RunMultiply_TwoLargeBigIntegers_Threshold>b__3_0()
            at BigIntTools.Utils.RunWithFakeThreshold(String name, Int32 value, Action action)
            at System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers_Threshold()
   System.Numerics.Tests.ComplexTests.Reciprocal [SKIP]
      Condition(s) not met: \"Is64Bit\"
   System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt_Threshold [FAIL]
      Assert.Equal() Failure
                 Γåô (pos 1)
      Expected: -38776096123501334825274240210298033125015┬╖┬╖┬╖
      Actual:   -18889465607631406169342467084338106397442┬╖┬╖┬╖
                 Γåæ (pos 1)
      Stack Trace:
            at System.Numerics.Tests.modpowTest.VerifyModPowString(String opstring)
            at System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt()
            at BigIntTools.Utils.RunWithFakeThreshold(String name, Int32 value, Action action)
            at System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt_Threshold()
   System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 36)
      Expected: ┬╖┬╖┬╖6701045775033882228017334052661935847075464271800991226528542┬╖┬╖┬╖
      Actual:   ┬╖┬╖┬╖6701045775033882228031500595866449599217042886593059041068755┬╖┬╖┬╖
                                       Γåæ (pos 36)
      Stack Trace:
            at System.Numerics.Tests.multiplyTest.VerifyMultiplyString(String opstring)
            at System.Numerics.Tests.multiplyTest.RunMultiply_TwoLargeBigIntegers()
   System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt [FAIL]
      Assert.Equal() Failure
                                       Γåô (pos 30)
      Expected: ┬╖┬╖┬╖114494808774362973053522177428284780306484519494117131965505
      Actual:   ┬╖┬╖┬╖114494808774362973054202742162285113558476690872315175392321
                                       Γåæ (pos 30)
      Stack Trace:
            at System.Numerics.Tests.modpowTest.VerifyModPowString(String opstring)
            at System.Numerics.Tests.modpowTest.ModPow1Large2SmallInt()
Finished:    System.Runtime.Numerics.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.Numerics.Tests  Total: 1213, Errors: 0, Failed: 8, Skipped: 6, Time: 154.399s
Finished running tests.  End time=17:59:15.76, Exit code = 1
```
</details>

**Comment by adiaaida** [comment]
This seems to be happening in the function Is_Zero. With RyuJIT we generate:

```
G_M8097_IG02:        ; func=00, offs=000004H, size=0009H, gcrefRegs=00000002 {ecx}, byrefRegs=00000000 {}, byref, isz
New gcrReg live regs=00000002 {ecx}
gcrReg +[ecx]
IN0001: 000004 33D2         xor      edx, edx
IN0002: 000006 8B7104       mov      esi, dword ptr [ecx+4]
IN0003: 000009 85F6         test     esi, esi
IN0004: 00000B 7E13         jle      SHORT G_M8097_IG06

G_M8097_IG03:        ; func=00, offs=00000DH, size=000BH, gcrefRegs=00000002 {ecx}, byrefRegs=00000000 {}, byref, isz
IN0005: 00000D 0FB6441108   movzx    eax, byte  ptr [ecx+edx+8]
IN0006: 000012 85C0         test     eax, eax
IN0007: 000014 7405         je       SHORT G_M8097_IG05
IN0008: 000016 33C0         xor      eax, eax

G_M8097_IG04:        ; func=00, offs=000018H, size=0003H, epilog, nogc, emitadd
IN0010: 000018 5E           pop      esi
IN0011: 000019 5D           pop      ebp
IN0012: 00001A C3           ret      

G_M8097_IG05:        ; func=00, offs=00001BH, size=0005H, gcVars=00000000 {}, gcrefRegs=00000002 {ecx}, byrefRegs=00000000 {}, gcvars, byref, isz
IN0009: 00001B 42           inc      edx
IN000a: 00001C 3BF2         cmp      esi, edx
IN000b: 00001E 7FED         jg       SHORT G_M8097_IG03

G_M8097_IG06:        ; func=00, offs=000020H, size=0005H, gcrefRegs=00000000 {}, byrefRegs=00000000 {}, byref
New gcrReg live regs=00000000 {}
gcrReg -[ecx]
IN000c: 000020 B801000000   mov      eax, 1

G_M8097_IG07:        ; func=00, offs=000025H, size=0003H, epilog, nogc, emitadd
IN0013: 000025 5E           pop      esi
IN0014: 000026 5D           pop      ebp
IN0015: 000027 C3           ret      
```

But with legacy backend, we generate:

```
G_M8097_IG02:        ; func=00, offs=000004H, size=000AH, gcrefRegs=02 {ecx}, byrefRegs=00 {}, byref, isz
New gcrReg live regs=02 {ecx}
gcrReg +[ecx]
IN0001: 000004 33D2         xor      edx, edx
IN0002: 000006 8B7104       mov      esi, dword ptr [ecx+4]
IN0003: 000009 83FE00       cmp      esi, 0
IN0004: 00000C 7E11         jle      SHORT G_M8097_IG06

G_M8097_IG03:        ; func=00, offs=00000EH, size=0009H, gcrefRegs=02 {ecx}, byrefRegs=00 {}, byref, isz
IN0005: 00000E 807C110800   cmp      byte  ptr [ecx+edx+8], 0
IN0006: 000013 7405         je       SHORT G_M8097_IG05
IN0007: 000015 33C0         xor      eax, eax

G_M8097_IG04:        ; func=00, offs=000017H, size=0003H, epilog, nogc, emitadd
IN000f: 000017 5E           pop      esi
IN0010: 000018 5D           pop      ebp
IN0011: 000019 C3           ret      

G_M8097_IG05:        ; func=00, offs=00001AH, size=0005H, gcVars=00000000 {}, gcrefRegs=02 {ecx}, byrefRegs=00 {}, gcvars, byref, isz
IN0008: 00001A 42           inc      edx
IN0009: 00001B 3BF2         cmp      esi, edx
IN000a: 00001D 7FEF         jg       SHORT G_M8097_IG03

G_M8097_IG06:        ; func=00, offs=00001FH, size=0005H, gcrefRegs=00 {}, byrefRegs=00 {}, byref
New gcrReg live regs=00 {}
gcrReg -[ecx]
IN000b: 00001F B801000000   mov      eax, 1

G_M8097_IG07:        ; func=00, offs=000024H, size=0003H, epilog, nogc, emitadd
IN0012: 000024 5E           pop      esi
IN0013: 000025 5D           pop      ebp
IN0014: 000026 C3           ret      
```

**Comment by adiaaida** [comment]
The only difference I can see is in RyuJIT, we generate a test instruction to compare to zero, while in legacy backend, we generate a cmp.

**Comment by pgavlin** [comment]
@adiaaida: the difference you've pointed out could be the bug, as the behavior of the `test` and the `cmp` instructions are different w.r.t. the flags that each sets. In particular, the `test` instruction performs a bitwise and and derives the flags from the result, while the `cmp` instruction performs a bitwise subtract. This results in different behavior if the flags are used for much other than checking the value of the zero flag (in this case, the instruction that is consuming the flags is a `jle`, which will examine ZF, SF, and OF in order to decide whether or not to branch).

**Comment by adiaaida** [comment]
No, it turned out i had a wildcard in my altjit. Not the bug.

**Comment by pgavlin** [comment]
@adiaaida: yeah, after more thought I believe that `test` can be used as part of a `x <= 0` check. Sorry for the noise.

**Comment by adiaaida** [comment]
No problem. I found the actual function that has the bad codegen. It's Square. RyuJIT:

```
IN0024: 00009E shld     edi, eax, 1
IN0025: 0000A2 mov      ebx, eax
IN0026: 0000A4 shl      ebx, 1
IN0027: 0000A6 mov      edi, ebx
IN0028: 0000A8 add      edi, dword ptr [V46 ebp-64H]
IN0029: 0000AB mov      edx, dword ptr [V39 ebp-54H]
IN002a: 0000AE mov      ebx, dword ptr [V02 ebp+0CH]
IN002b: 0000B1 mov      dword ptr [ebx+4*edx], edi
IN002c: 0000B4 mov      edx, dword ptr [V46 ebp-64H]
IN002d: 0000B7 mov      edi, dword ptr [V47 ebp-68H]
IN002e: 0000BA shrd     edx, edi, 1
IN002f: 0000BE shr      edi, 1
**IN0030: 0000C0 adc      edi, dword ptr [V49 ebp-6CH]
IN0031: 0000C3 add      eax, edx**
IN0032: 0000C5 shrd     eax, edi, 31
IN0033: 0000C9 mov      edx, edi
IN0034: 0000CB shr      edx, 31
IN0035: 0000CE mov      dword ptr [V42 ebp-5CH], eax
IN0036: 0000D1 mov      dword ptr [V43 ebp-60H], edx
IN0037: 0000D4 inc      esi
IN0038: 0000D5 cmp      esi, ecx
IN0039: 0000D7 jl       SHORT G_M47313_IG08
```

Legacy Backend:

```
IN0022: 000095 shld     edx, eax, 1
IN0023: 000099 shl      eax, 1
IN0024: 00009B add      eax, ebx
IN0025: 00009D mov      edx, dword ptr [V39 ebp-68H]
IN0026: 0000A0 mov      ecx, dword ptr [V02 ebp+0CH]
IN0027: 0000A3 mov      dword ptr [ecx+4*edx], eax
IN0028: 0000A6 mov      eax, dword ptr [V09 ebp-30H]
IN0029: 0000A9 mov      edx, dword ptr [V09+0x4 ebp-2CH]
IN002a: 0000AC mov      ecx, ebx
IN002b: 0000AE mov      ebx, dword ptr [V08+0x4 ebp-24H]
IN002c: 0000B1 shrd     ecx, ebx, 1
IN002d: 0000B5 shr      ebx, 1
IN002e: 0000B7 add      eax, ecx
IN002f: 0000B9 adc      edx, ebx
IN0030: 0000BB shrd     eax, edx, 31
IN0031: 0000BF shr      edx, 31
IN0032: 0000C2 mov      dword ptr [V05+0x4 ebp-1CH], edx
IN0033: 0000C5 mov      ebx, eax
IN0034: 0000C7 inc      edi
IN0035: 0000C8 cmp      edi, esi
IN0036: 0000CA jl       SHORT G_M47313_IG04
```

There are a couple of things that seem wrong to me. 1) We generate adc followed by add, which is wrong, and 2) we appear to overwrite the result of the shld, which I'm not sure how wrong it is. For the add, which is definitely wrong, I'm not sure where we would be swapping the order.

**Comment by adiaaida** [comment]
For the add issue, this seems to stem from DecomposeShift, which potentially swaps the order of its operands, which seems to swap the order of the add calculation.
