### ISSUE TITLE
RyuJIT/x86 JitStressRegs=8 CoreFx System.Reflection.Metadata.Tests.BlobTests.WritePrimitive [FAIL]

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8280]
Commits:
dbf8ce1173faf78b176771946b0bca9f9863bc9b
dotnet/corefx@0d623b5b5e110a336eb743b6d9066f336a5177b4

Repro:
coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Reflection.Metadata.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=8
RunTests.cmd c:\git\corefx\packages
```
**Output**
```
Using c:\git\coref2\packages as folder for resolving package dependencies.
Executing in C:\git\coref2\bin\tests\AnyOS.AnyCPU.Release\System.Reflection.Metadata.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time:  7:56:37.06
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Reflection.Metadata.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Reflection.Metadata.Tests
Discovered:  System.Reflection.Metadata.Tests
Starting:    System.Reflection.Metadata.Tests
   System.Reflection.Metadata.Tests.BlobTests.WritePrimitive [FAIL]

      Expected:
      0x44, 0x33, 0x22, 0x11, 0x66, 0x55, 0x77, 0xFF, 0xEE, 0xDD, 0xCC, 0xBB, 0xAA, 0x99, 0x88, 0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0xFF, 0xFD, 0x01, 0x00, 0x21, 0x43, 0x65, 0x87, 0x09, 0xBA, 0xDC, 0xFE, 0x56, 0x55, 0x44, 0x34, 0x33, 0x22, 0x12, 0x11, 0x02, 0xD6, 0xE0, 0x9A, 0x94, 0x47, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF8, 0xFF, 0x00, 0x00, 0x80, 0xFF, 0x04, 0x03, 0x02, 0x01, 0x06, 0x05, 0x08, 0x07, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x04, 0x03, 0x02, 0x01, 0x06, 0x05, 0x08, 0x07, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10
      Actual:
      0x44, 0x33, 0x22, 0x11, 0x66, 0x55, 0x77, 0xFF, 0xEE, 0xDD, 0xCC, 0xBB, 0xAA, 0x99, 0x88, 0xFF, 0xFF, 0xFF, 0xFF, 0xFE, 0xFF, 0xFD, 0x01, 0x00, 0x21, 0x43, 0x65, 0x87, 0x09, 0xBA, 0xDC, 0xFE, 0x56, 0x55, 0x44, 0x34, 0x33, 0x22, 0x12, 0x11, 0xA0, 0xD6, 0xE0, 0x9A, 0x94, 0x47, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF8, 0xFF, 0x00, 0x00, 0x80, 0xFF, 0x04, 0x03, 0x02, 0x01, 0x06, 0x05, 0x08, 0x07, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x04, 0x03, 0x02, 0x01, 0x06, 0x05, 0x08, 0x07, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10
      Differences:
          0x44,     0x33,     0x22,     0x11,     0x66,     0x55,     0x77,     0xFF,     0xEE,     0xDD,     0xCC,     0xBB,     0xAA,     0x99,     0x88,     0xFF,     0xFF,     0xFF,     0xFF,     0xFE,     0xFF,     0xFD,     0x01,     0x00,     0x21,     0x43,     0x65,     0x87,     0x09,     0xBA,     0xDC,     0xFE,     0x56,     0x55,     0x44,     0x34,     0x33,     0x22,     0x12,     0x11, ++> 0xA0, --> 0x02,     0xD6,     0xE0,     0x9A,     0x94,     0x47,     0x09,     0x00,     0x00,     0x00,     0x00,     0x00,     0x00,     0x00,     0x00,     0x00,     0x00,     0x00,     0x00,     0xF8,     0xFF,     0x00,     0x00,     0x80,     0xFF,     0x04,     0x03,     0x02,     0x01,     0x06,     0x05,     0x08,     0x07,     0x09,     0x0A,     0x0B,     0x0C,     0x0D,     0x0E,     0x0F,     0x10,     0x04,     0x03,     0x02,     0x01,     0x06,     0x05,     0x08,     0x07,     0x09,     0x0A,     0x0B,     0x0C,     0x0D,     0x0E,     0x0F,     0x10

      Expected: True
      Actual:   False
      Stack Trace:
            at System.Reflection.Metadata.Tests.AssertEx.Equal[T](IEnumerable`1 expected, IEnumerable`1 actual, IEqualityComparer`1 comparer, String message, String itemSeparator, Func`2 itemInspector)
            at System.Reflection.Metadata.Tests.BlobTests.WritePrimitive()
Finished:    System.Reflection.Metadata.Tests
```

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by pgavlin** [comment]
@RussKeldorph: the title claims this is x86 with JitStressRegs=8, but the repro steps seem to use x64 with JitStressRegs=1. Which is correct? I can't repro any mix of those scenarios.

**Comment by RussKeldorph** [comment]
@pgavlin Sorry, copy-paste error.  I believe I intended that to be x86+jsr=8 per the title.  Incidentally, I seem to have unintentionally deleted the log this was based on, and my latest log doesn't show it.  If it doesn't repro, I may have opened this in error, and we should close it out.
