### ISSUE TITLE
RyuJIT/x86: JitStressRegs=4 CoreFx: System.Runtime.CompilerServices.UnsafeTests.InitBlockUnalignedUIntPtrUnmanaged [FAIL]

### ISSUE THREAD

**Issue by RussKeldorph** [dotnet/coreclr#8286]
Commits:
dbf8ce1173faf78b176771946b0bca9f9863bc9b
dotnet/corefx@0d623b5b5e110a336eb743b6d9066f336a5177b4

Repro:
coreclr *(assuming root=c:\git\coreclr)*
```
build x86 checked skiptests
```
corefx *(assuming root=c:\git\corefx)*
```
build -Release -SkipTests -- /p:BUILDTOOLS_OVERRIDE_RUNTIME=c:\git\coreclr\bin\Product\Windows_NT.x86.Checked
cd bin\tests\AnyOS.AnyCPU.Release\System.Runtime.CompilerServices.Unsafe.Tests\default.netcoreapp1.1
set COMPlus_AltJit=*
set COMPlus_AltJitName=protojit.dll
set COMPlus_JitStressRegs=4
RunTests.cmd c:\git\corefx\packages
```
**Output**
```
Using c:\git\coref2\packages as folder for resolving package dependencies.
Executing in C:\git\coref2\bin\tests\AnyOS.AnyCPU.Release\System.Runtime.CompilerServices.Unsafe.Tests\default.netcoreapp1.1\
Hard linking dependent files...
Finished linking needed files, moving to running tests.
Running tests... Start time: 13:26:22.81
Command(s):
call CoreRun.exe xunit.console.netcore.exe System.Runtime.CompilerServices.Unsafe.Tests.dll  -xml testResults.xml -notrait Benchmark=true -notrait category=nonnetcoreapp1.1tests  -notrait category=OuterLoop -notrait category=failing -notrait category=nonwindowstests
xUnit.net console test runner (32-bit .NET Core)
Copyright (C) 2014 Outercurve Foundation.

Discovering: System.Runtime.CompilerServices.Unsafe.Tests
Discovered:  System.Runtime.CompilerServices.Unsafe.Tests
Starting:    System.Runtime.CompilerServices.Unsafe.Tests
   System.Runtime.CompilerServices.UnsafeTests.InitBlockUnalignedUIntPtrUnmanaged(numBytes: 0, value: 1) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   1
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.InitBlockUnalignedUIntPtrUnmanaged(Int32 numBytes, Byte value)
   System.Runtime.CompilerServices.UnsafeTests.InitBlockUnalignedUIntPtrUnmanaged(numBytes: 10, value: 255) [FAIL]
      Assert.Equal() Failure
      Expected: 108
      Actual:   255
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.InitBlockUnalignedUIntPtrUnmanaged(Int32 numBytes, Byte value)
   System.Runtime.CompilerServices.UnsafeTests.InitBlockUIntPtrUnmanaged(numBytes: 0, value: 1) [FAIL]
      Assert.Equal() Failure
      Expected: 0
      Actual:   1
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.InitBlockUIntPtrUnmanaged(Int32 numBytes, Byte value)
   System.Runtime.CompilerServices.UnsafeTests.InitBlockUIntPtrUnmanaged(numBytes: 10, value: 255) [FAIL]
      Assert.Equal() Failure
      Expected: 133
      Actual:   255
      Stack Trace:
            at System.Runtime.CompilerServices.UnsafeTests.InitBlockUIntPtrUnmanaged(Int32 numBytes, Byte value)
Finished:    System.Runtime.CompilerServices.Unsafe.Tests

=== TEST EXECUTION SUMMARY ===
   System.Runtime.CompilerServices.Unsafe.Tests  Total: 101, Errors: 0, Failed: 4, Skipped: 0, Time: 20.856s
Finished running tests.  End time=13:26:48.28, Exit code = 1
```

**Comment by RussKeldorph** [comment]
@dotnet/jit-contrib

**Comment by pgavlin** [comment]
@sivarv @CarolEidt can one of you take a look at this one? This is a case of a lclVar being allocated to `eax` during an interval in which `eax` needs to hold a different value but the allocated lclVar is not spilled. I've posted a log of the affected method (`System.Runtime.CompilerServices.UnsafeTests:InitBlockUIntPtrUnmanaged`) [here](https://gist.github.com/pgavlin/2d766092fe48006fa7b4acbe660eeb59).

Here is a piece of the LSRA dump during allocation:

```
                    Alloc eax  |V0 a|V3 a|    |    |----|----|----|    |
 30.#23  V12  Def    Alloc ebx  |V0 a|V3 a|    |V12a|----|----|----|    |
 37.#24  V12  Use    Keep  ebx  |V0 a|V3 a|    |V12a|----|----|----|    |
 38.#25  I17  Def    Alloc esi  |V0 a|V3 a|    |V12a|----|----|I17a|    |
 41.#26  I18  Def    Alloc edi  |V0 a|V3 a|    |V12a|----|----|I17a|I18a|
 41.#27  V12  Use *  Keep  ebx  |V0 a|V3 a|    |V12a|----|----|I17a|I18a|
 41.#28  I17  Use *  Keep  esi  |V0 a|V3 a|    |V12a|----|----|I17a|I18a|
 41.#29  I18  Use *  Keep  edi  |V0 a|V3 a|    |V12a|----|----|I17a|I18a|
 42.#30  I19  Def    Alloc edi  |V0 a|V3 a|    |    |----|----|    |I19a|
 43.#31  I19  Use *  Keep  edi  |V0 a|V3 a|    |    |----|----|    |I19a|
 44.#32  V6   Def    Alloc ebx  |V0 a|V3 a|    |V6 a|----|----|    |    |
 47.#33  V1   Use *  ReLod NA   |V0 a|V3 a|    |V6 a|----|----|    |    |
                     Alloc edx  |V0 a|V3 a|V1 a|V6 a|----|----|    |    |
 48.#34  I20  Def    Alloc edx  |V0 a|V3 a|I20a|V6 a|----|----|    |    |
 49.#35  I20  Use *  Keep  edx  |V0 a|V3 a|I20a|V6 a|----|----|    |    |
 50.#36  V11  Def    Alloc edx  |V0 a|V3 a|V11a|V6 a|----|----|    |    |
 59.#37  edi  Fixd   Keep  edi  |V0 a|V3 a|V11a|V6 a|----|----|    |    |
 59.#38  V3   Use    Move  NA   |V0 a|    |V11a|V6 a|----|----|    |    |
                     Alloc edi  |V0 a|    |V11a|V6 a|----|----|    |V3 a|
 59.#39  eax  Fixd   Keep  eax  |V0 a|    |V11a|V6 a|----|----|    |V3 a|
 59.#40  V11  Use    Keep  edx  |V0 a|    |V11a|V6 a|----|----|    |V3 a|
 59.#41  ecx  Fixd   Keep  ecx  |V0 a|    |V11a|V6 a|----|----|    |V3 a|
 59.#42  V6   Use *  Keep  ebx  |V0 a|    |V11a|V6 a|----|----|    |V3 a|
 60.#43  ecx  Kill   Keep  ecx  |V0 a|    |V11a|    |----|----|    |V3 a|
 60.#44  edi  Kill   Spill edi  |V0 a|    |V11a|    |----|----|    |    |
                     Keep  edi  |V0 a|    |V11a|    |----|----|    |    |
--------------------------------+----+----+----+----+----+----+----+----+
Loc RP#  Name Type  Action Reg  |eax |ecx |edx |ebx |esp |ebp |esi |edi |
--------------------------------+----+----+----+----+----+----+----+----+
 64.#45  C21  Def    Alloc ecx  |V0 a|C21a|V11a|    |----|----|    |    |
 65.#46  C21  Use *  Keep  ecx  |V0 a|C21a|V11a|    |----|----|    |    |
 66.#47  V4   Def    Alloc ecx  |V0 a|V4 a|V11a|    |----|----|    |    |
 73.#48  V0   Use    Keep  eax  |V0 a|V4 a|V11a|    |----|----|    |    |
```

RP #40 is a use of `V12` with the `srcCandidates` set to `eax`: `<RefPosition #40  @59  ->#97  RefTypeUse <Ivl:11 V11> LCL_VAR BB01 regmask=[eax] fixed>
`. This use does not appear to be causing a spill of `V00`, however, which is allocated to `eax` when that ref appears.

**Comment by sivarv** [comment]
I will take a look at this.

**Comment by sivarv** [comment]
@pgavlin - I couldn't repro this when included your recent PR https://github.com/dotnet/coreclr/pull/8484
Prior to your PR, I could repro this failure.  Can you please confirm whether you can repro this failure against latest coreclr?

**Comment by pgavlin** [comment]
I can still repro this as of 64c2ad17351ac5bc0bb042216bfcbf1c5136d7cf and dotnet/corefx@0d623b5b5e110a336eb743b6d9066f336a5177b4.

**Comment by pgavlin** [comment]
(that commit in CoreCLR does include the changes from the PR you referenced)
