### ISSUE TITLE
Mac restore error: "This platform does not support getting the current color."

### ISSUE THREAD

**Issue by zephyrweb** [dotnet/coreclr#877]
Following these directions: https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-dnx-osx.md, I get:
```
14:59:36 ~/dev/msdotnet source dnvm
14:59:46 ~/dev/msdotnet dnvm use 1.0.0-beta5-11649 -r coreclr
Adding /Users/mattm/.dnx/runtimes/dnx-coreclr-darwin-x64.1.0.0-beta5-11649/bin to process PATH
14:59:47 ~/dev/msdotnet dnu restore
System.TypeInitializationException: The type initializer for 'Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole' threw an exception. ---> System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Framework.PackageManager.Program.CreateReports(Boolean verbose, Boolean quiet)
   at Microsoft.Framework.PackageManager.Program.<>c__DisplayClass3_1.<<Main>b__2>d.MoveNext()
System.PlatformNotSupportedException: This platform does not support getting the current color.
   at System.ConsolePal.get_ForegroundColor()
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..ctor(TextWriter writer)
   at Microsoft.Framework.Runtime.Common.CommandLine.AnsiConsole..cctor()
```

At first I thought it was my terminal (iTerm), but same thing happens using Terminal.app

**Comment by stephentoub** [comment]
You currently need to use mono for the restore step:
```
dnvm use 1.0.0-beta5-11649 -r mono
dnu restore
```

**Comment by zephyrweb** [comment]
Well, I discovered the issue (not running 'dnvm use 1.0.0-beta5-11649 -r mono' first), but leaving my stupidity here for posterity.
