### ISSUE TITLE
[x86/Linux] Action<Object> Invoke fail with Object

### ISSUE THREAD

**Issue by seanshpark** [dotnet/coreclr#8817]
`ActionInvoke` unit test fails inside `ActionFunction` when `obj.GetType()` is called.

Made a simple program and this also fails when `obj.GetType()` is executed.
```
using System;

namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Program p = new Program();
            p.Test();
        }

        public void Test()
        {
            Action<Object> actionDelegate;
            actionDelegate = new Action<Object>(ActionFunction);
            actionDelegate.Invoke(1);
        }

        public void ActionFunction<T>(T obj)
        {
            obj.GetType();
            Console.WriteLine("ActionFunction : " + obj);
        }
    }
}
```

Callstack
```
#0  0xb6beb554 in MethodTable::GetClass_NoLogging (this=0xb25ccbf0) at /home/maxwell/netcore/coreclr/src/vm/methodtable.inl:36
#1  0xb6be941f in MethodTable::GetClass (this=0xb25ccbf0) at /home/maxwell/netcore/coreclr/src/vm/methodtable.inl:83
#2  0xb6cd78f4 in MethodTable::SanityCheck (this=0xb25ccbf0) at /home/maxwell/netcore/coreclr/src/vm/methodtable.cpp:7710
#3  0xb6cdcbcf in MethodTable::Validate (this=0xb25ccbf0) at /home/maxwell/netcore/coreclr/src/vm/methodtable.cpp:9797
#4  0xb6cecacb in Object::ValidateInner (this=0xb6223bdc, bDeep=1, bVerifyNextHeader=1, bVerifySyncBlock=1) at /home/maxwell/netcore/coreclr/src/vm/object.cpp:1742
#5  0xb6ceb448 in Object::Validate (this=0xb6223bdc, bDeep=1, bVerifyNextHeader=1, bVerifySyncBlock=1) at /home/maxwell/netcore/coreclr/src/vm/object.cpp:1719
#6  0xb6cefb15 in OBJECTREF::OBJECTREF (this=0xbfffe198, pObject=0xb6223bdc) at /home/maxwell/netcore/coreclr/src/vm/object.cpp:2713
#7  0xb766f74d in ObjectNative::GetClass (pThis=0xb6223bdc) at /home/maxwell/netcore/coreclr/src/classlibnative/bcltype/objectnative.cpp:237
#8  0xb25b75ed in ?? ()
#9  0xb25b75ac in ?? ()
#10 0xb25b756b in ?? ()
#11 0xb25b7491 in ?? ()
#12 0xb707e5a7 in CallDescrWorkerInternal () at /home/maxwell/netcore/coreclr/src/vm/i386/asmhelpers.S:444
~~~
```

**Comment by janvorli** [comment]
@seanshpark Can you verify that the  ObjectNative::GetClass uses the right calling convention? This looks strange, like some historical thing.  I believe it should be defined as `__fastcall` unconditionally here, since the jitter generates the same x86 code as for windows now. As it is now, it would pass the first parameter in EAX, the second in ECX and the third in EDX.
```C++
#ifdef _TARGET_X86_

// Choose the appropriate calling convention for FCALL helpers on the basis of the JIT calling convention
#ifdef __GNUC__
#define F_CALL_CONV __attribute__((stdcall, regparm(3)))
#else
#define F_CALL_CONV __fastcall
#endif

```

**Comment by seanshpark** [comment]
> Can you verify that the ObjectNative::GetClass uses the right calling convention?

I'm not sure how to verify so I'll show you the dump codes. Please help me if possible.
```
Thread 1 "corerun" hit Breakpoint 9, ObjectNative::GetClass (pThis=0xb6223bdc) at /home/maxwell/netcore/coreclr/src/classlibnative/bcltype/objectnative.cpp:237
237         OBJECTREF objRef = ObjectToOBJECTREF(pThis);

   0xb766f6f0 <ObjectNative::GetClass(int, int, Object*)>:      push   %ebp
   0xb766f6f1 <ObjectNative::GetClass(int, int, Object*)+1>:    mov    %esp,%ebp
   0xb766f6f3 <ObjectNative::GetClass(int, int, Object*)+3>:    push   %ebx
   0xb766f6f4 <ObjectNative::GetClass(int, int, Object*)+4>:    push   %edi
   0xb766f6f5 <ObjectNative::GetClass(int, int, Object*)+5>:    push   %esi
   0xb766f6f6 <ObjectNative::GetClass(int, int, Object*)+6>:    and    $0xfffffff8,%esp
   0xb766f6f9 <ObjectNative::GetClass(int, int, Object*)+9>:    sub    $0x80,%esp
   0xb766f6ff <ObjectNative::GetClass(int, int, Object*)+15>:   call   0xb766f704 <ObjectNative::GetClass(int, int, Object*)+20>
   0xb766f704 <ObjectNative::GetClass(int, int, Object*)+20>:   pop    %esi
   0xb766f705 <ObjectNative::GetClass(int, int, Object*)+21>:   add    $0x5678fc,%esi
   0xb766f70b <ObjectNative::GetClass(int, int, Object*)+27>:   lea    0x70(%esp),%edi
   0xb766f70f <ObjectNative::GetClass(int, int, Object*)+31>:   mov    -0x15d8(%esi),%ebx
   0xb766f715 <ObjectNative::GetClass(int, int, Object*)+37>:   mov    %eax,0x30(%esp)
   0xb766f719 <ObjectNative::GetClass(int, int, Object*)+41>:   mov    %gs:0x14,%eax
   0xb766f71f <ObjectNative::GetClass(int, int, Object*)+47>:   mov    %eax,0x78(%esp)
   0xb766f723 <ObjectNative::GetClass(int, int, Object*)+51>:   mov    0x30(%esp),%eax
   0xb766f727 <ObjectNative::GetClass(int, int, Object*)+55>:   mov    %eax,0x48(%esp)
   0xb766f72b <ObjectNative::GetClass(int, int, Object*)+59>:   mov    %edx,0x44(%esp)
   0xb766f72f <ObjectNative::GetClass(int, int, Object*)+63>:   mov    %ecx,0x40(%esp)
   0xb766f733 <ObjectNative::GetClass(int, int, Object*)+67>:   mov    %ebx,0x3c(%esp)
=> 0xb766f737 <ObjectNative::GetClass(int, int, Object*)+71>:   mov    0x40(%esp),%ecx
   0xb766f73b <ObjectNative::GetClass(int, int, Object*)+75>:   mov    %edi,(%esp)
   0xb766f73e <ObjectNative::GetClass(int, int, Object*)+78>:   mov    %ecx,0x4(%esp)
   0xb766f742 <ObjectNative::GetClass(int, int, Object*)+82>:   mov    %esi,%ebx
   0xb766f744 <ObjectNative::GetClass(int, int, Object*)+84>:   mov    %esi,0x2c(%esp)
   0xb766f748 <ObjectNative::GetClass(int, int, Object*)+88>:   call   0xb6cefa30 <OBJECTREF::OBJECTREF(Object*)>

(gdb) info register
eax            0x0      0
ecx            0xb6223bdc       -1239270436
edx            0xb6223bdc       -1239270436
ebx            0xb766f6f0       -1217988880
esp            0xbfffe128       0xbfffe128
ebp            0xbfffe1b8       0xbfffe1b8
esi            0xb7bd7000       -1212321792
edi            0xbfffe198       -1073749608
eip            0xb766f737       0xb766f737 <ObjectNative::GetClass(int, int, Object*)+71>
```

as ObjectNative::GetClass is `FCIMPL1(Object*, ObjectNative::GetClass, Object* pThis)`
and I could see these in fcall.h
```
#define FCIMPL1(rettype, funcname, a1) \
rettype F_CALL_CONV funcname(int /* EAX */, int /* EDX */, a1) { FCIMPL_PROLOG(funcname)
```
pThis maybe first stack value?

When I continue and stops at SIGSEGV, EDX(or ECX) seems to be the Object* value.
```
Thread 1 "corerun" received signal SIGSEGV, Segmentation fault.
0xb6beb554 in MethodTable::GetClass_NoLogging (this=0xb25ccbf0) at /home/maxwell/netcore/coreclr/src/vm/methodtable.inl:36
36              return PTR_EEClass(PTR_MethodTable(canonicalMethodTable)->m_pCanonMT);

(gdb) p *(Object*)0xb6223bdc
$1 = {m_pMethTab = 0xb25ccbf0}
(gdb) p this
$2 = (MethodTable *) 0xb25ccbf0
```
and this $2 doesn't seem to be a valid MethodTable*.

**Comment by seanshpark** [comment]
I think this is the code of the above `Test()`. It seems ECX is the `obj`
```
=> 0xb25b75c0:  push   %ebp
   0xb25b75c1:  mov    %esp,%ebp
   0xb25b75c3:  sub    $0x10,%esp
   0xb25b75c6:  xor    %eax,%eax
   0xb25b75c8:  mov    %eax,-0xc(%ebp)
   0xb25b75cb:  mov    %eax,-0x10(%ebp)
   0xb25b75ce:  mov    %ecx,-0x4(%ebp)
   0xb25b75d1:  mov    %edx,-0x8(%ebp)
   0xb25b75d4:  cmpl   $0x0,0xb6223034
   0xb25b75db:  je     0xb25b75e2
   0xb25b75dd:  call   0xb6efcfe0 <JIT_DbgIsJustMyCode()>
   0xb25b75e2:  nop
   0xb25b75e3:  mov    -0x8(%ebp),%ecx
   0xb25b75e6:  cmp    %ecx,(%ecx)
   0xb25b75e8:  call   0xb766f6f0 <ObjectNative::GetClass(int, int, Object*)>
   0xb25b75ed:  mov    %eax,-0xc(%ebp)
   0xb25b75f0:  nop
   0xb25b75f1:  mov    0xb3e01140,%ecx
   0xb25b75f7:  mov    -0x8(%ebp),%edx
   0xb25b75fa:  call   *0xb5963c44
   0xb25b7600:  mov    %eax,-0x10(%ebp)
   0xb25b7603:  mov    -0x10(%ebp),%ecx
   0xb25b7606:  call   *0xb6225520
   0xb25b760c:  nop
   0xb25b760d:  nop
   0xb25b760e:  mov    %ebp,%esp
   0xb25b7610:  pop    %ebp
   0xb25b7611:  ret    $0x4
```

**Comment by janvorli** [comment]
I believe I was right. Looking at the code of ObjectNative::GetClass, it passes the value it got in ECX from its callee to the OBJECTREF::OBJECTREF. But the calling convention of the jitter is that it passes the third argument via stack.
Can you please try to change the F_CALL_CONV definition to be always __fastcall and try if it fixes the issue? I believe it will fix it.

**Comment by seanshpark** [comment]
With this change, (is this the one you are thinking of?)
```
 #ifdef __GNUC__
-#define F_CALL_CONV __attribute__((stdcall, regparm(3)))
+#define F_CALL_CONV __fastcall
 #else
 #define F_CALL_CONV __fastcall
 #endif
```
If fails in strange place
```
Thread 1 "corerun" received signal SIGSEGV, Segmentation fault.
0xbfffe880 in ?? ()
=> 0xbfffe880:  24 e9   and    $0xe9,%al
(gdb) bt
#0  0xbfffe880 in ?? ()
#1  0x00000000 in ?? ()
```

**Comment by janvorli** [comment]
Ah, actually, you'll also need to use the same definitions of FCDECL0 etc that are used on Windows. Can you please give it a try?

**Comment by janvorli** [comment]
And the same is actually needed for the block of FCIMPL0 defines futher in the file

**Comment by janvorli** [comment]
And HCIMP0 etc even futher

**Comment by janvorli** [comment]
Hmm I've tried that and there are some build issues. So it seems we should go back to the original code. In fact, @jkotas has just explained to me why was it made different for GNUC. In the past, long time before coreclr, we were using GCC. And GCC doesn't support the __fastcall keyword. So this __attribute__((stdcall, regparm(3))) together with the macros that swap the order of function arguments and add some dummy ones to make it work the way so that the actual parameters are passed in the registers the same way as on Windows (ecx, edx, the rest on stack).

**Comment by janvorli** [comment]
Looking at your disassembly again, so Object* really comes in the ECX and the function expects it there, as can be seen from the disassembly:
```asm
mov    %ecx,0x40(%esp)
.
.
mov    0x40(%esp),%ecx
.
.
mov    %ecx,0x4(%esp) ; the OBJECTREF::OBJECTREF expects the argument on stack
.
call   0xb6cefa30 <OBJECTREF::OBJECTREF(Object*)>
```

**Comment by seanshpark** [comment]
I've tried it with change `__GNUC__` to `__GNUC__xx` in the fcall.h and a little change in `FCSigCheck` for the build issues you mentioned. But unluckly the result was the same. 
I'll go on from the `Test()` method and see where it alters the `Object` value.

**Comment by seanshpark** [comment]
I've changed to `Test()` to have Object like this to see the obj value.
```
        public void Test()
        {
            Action<Object> actionDelegate;
            actionDelegate = new Action<Object>(ActionFunction);
            Object obj = new Object();
            actionDelegate.Invoke(obj);
        }
```
and while tracing in assembly codes, `CILJit::compileMethod` drops a sub looking like this for `actionDelegate.Invoke(obj);` call
```
(gdb) x/30i methodCodePtr
   0xb24b9578:  push   %ebp
   0xb24b9579:  mov    %esp,%ebp
   0xb24b957b:  sub    $0xc,%esp
   0xb24b957e:  mov    %ecx,-0x8(%ebp)
   0xb24b9581:  mov    %edx,-0xc(%ebp)
   0xb24b9584:  movl   $0xb24b9080,-0x4(%ebp)	>> 0xb24b9080 = PrecodeFixupThunk
   0xb24b958b:  mov    -0xc(%ebp),%ecx
   0xb24b958e:  push   %ecx
   0xb24b958f:  mov    -0x8(%ebp),%ecx
   0xb24b9592:  mov    $0xb6223bdc,%edx 	>> 0xb6223bdc = MethodDesc*
   0xb24b9597:  mov    -0x4(%ebp),%eax
   0xb24b959a:  call   *%eax
   0xb24b959c:  mov    %ebp,%esp
   0xb24b959e:  pop    %ebp
   0xb24b959f:  ret
```

Here, parameters are changed to something like this
```
# before
ecx 0xb2e070f8 : DelegateObject->_target
edx 0xb2e07124 : Object*
# after
ecx 0xb2e070f8 : DelegateObject->_target
edx 0xb6223bdc : MethodDesc*
stack : Object* (0xb2e07124)
```
where MethodDesc* dump is,
```
(gdb) p *(MethodDesc*)0xb6223bdc
$6 = {
	m_pszDebugMethodName = 0xb24cebf0 "ConsoleApplication.Program.ActionFunction[System.Object](System.Object)",
	m_pszDebugClassName = 0xb62239f0 "ConsoleApplication.Program",
	m_pszDebugMethodSignature = 0xb24cebf0 "ConsoleApplication.Program.ActionFunction[System.Object](System.Object)", 
	m_pDebugMethodTable = {m_addr = 3055696576},
	m_GcCover = 0x0, 
	m_wFlags3AndTokenRemainder = 3, 
	m_chunkIndex = 0 '\000', 
	m_bFlags2 = 3 '\003', 
	m_wSlotNumber = 5, 
	m_wFlags = 13,
	static s_ClassificationSizeTable = 0xb78ac35c <MethodDesc::s_ClassificationSizeTable>
}
```

After it jumps at `0xb24b959a:  call   *%eax` to `0xb24b9080` , related information looks like this
```
(gdb) x/30i 0xb24b9080
=> 0xb24b9080:  call   0xb707e660 <PrecodeFixupThunk>
(gdb) x/3b 0xb24b9085
0xb24b9085:     0x5e    0x00    0x00
				>> 5e = TypePrestub 
				>> 0  = m_MethodDescChunkIndex
				>> 0  = m_PrecodeChunkIndex
(gdb) x/1w 0xb24b9088
0xb24b9088:     0xb6223b68
(gdb) p *(MethodDesc*)0xb6223b68
$8 = {
	m_pszDebugMethodName = 0xb24ceb78 "ConsoleApplication.Program.ActionFunction[System.__Canon](System.__Canon)",
  	m_pszDebugClassName = 0xb62239f0 "ConsoleApplication.Program",
	m_pszDebugMethodSignature = 0xb24ceb78 "ConsoleApplication.Program.ActionFunction[System.__Canon](System.__Canon)", 
	m_pDebugMethodTable = {m_addr = 3055696576 = 0xb6223ac0},
	m_GcCover = 0x0, 
	m_wFlags3AndTokenRemainder = 3, 
	m_chunkIndex = 0 '\000', 
	m_bFlags2 = 8 '\b', 
	m_wSlotNumber = 5, 
	m_wFlags = 13,
	static s_ClassificationSizeTable = 0xb78ac35c <MethodDesc::s_ClassificationSizeTable>
}
```

Inside `ActionFunction<T>(T obj)` JITted code before calling `ObjectNative::GetClass` , register looks like this
```
eax 0x0
ecx 0xb6223bdc
edx 0xb6223bdc
esp 0xbfffe1cc
ebp 0xbfffe1dc
eip 0xb24b95d8
   0xb24b95d8:  call   0xb766f6f0 <ObjectNative::GetClass(int, int, Object*)>
```
if first two INT params are ECX and EDX, third one Object* should be in the stack but cannot see any code that access the value.

where the full code looks like this
```
(gdb) x/30i 0xb24b95b0
=> 0xb24b95b0:  push   %ebp
   0xb24b95b1:  mov    %esp,%ebp
   0xb24b95b3:  sub    $0x10,%esp
   0xb24b95b6:  xor    %eax,%eax
   0xb24b95b8:  mov    %eax,-0xc(%ebp)
   0xb24b95bb:  mov    %eax,-0x10(%ebp)

   0xb24b95be:  mov    %ecx,-0x4(%ebp) : 0xb2e070f8 = DelegateObject->_target
   0xb24b95c1:  mov    %edx,-0x8(%ebp) : 0xb6223bdc = MethodDesc* of "ConsoleApplication.Program.ActionFunction[System.Object](System.Object)"

   0xb24b95c4:  cmpl   $0x0,0xb6223034
   0xb24b95cb:  je     0xb24b95d2
   0xb24b95cd:  call   0xb6efcfe0 <JIT_DbgIsJustMyCode()>

   0xb24b95d2:  nop
   0xb24b95d3:  mov    -0x8(%ebp),%ecx
   0xb24b95d6:  cmp    %ecx,(%ecx)
   0xb24b95d8:  call   0xb766f6f0 <ObjectNative::GetClass(int, int, Object*)>
   0xb24b95dd:  mov    %eax,-0xc(%ebp)
   0xb24b95e0:  nop
   0xb24b95e1:  mov    0xb3e01140,%ecx
   0xb24b95e7:  mov    -0x8(%ebp),%edx
   0xb24b95ea:  call   *0xb5162c44
   0xb24b95f0:  mov    %eax,-0x10(%ebp)
   0xb24b95f3:  mov    -0x10(%ebp),%ecx
   0xb24b95f6:  call   *0xb6225520
   0xb24b95fc:  nop
   0xb24b95fd:  nop
   0xb24b95fe:  mov    %ebp,%esp
   0xb24b9600:  pop    %ebp
   0xb24b9601:  ret    $0x4
```

If `pThis` is forced to have what was Object* with `set pThis=0xb2e07124` , code seems to pass sanity check but fails afterwards.

**Comment by seanshpark** [comment]
Just tried this and passes my simple test program and also for Positive for `ActionInvoke.exe` but fails in Negative. I think negative is cause of exception is currently undo development.
```
$ ./corerun ActionInvoke.exe
Beginning test case ActionInvoke at 1/6/17 4:00:00 PM
Random seed: 20010415; set environment variable CORECLR_SEED to this value to repro

[Positive]
Beginning scenario: PosTest1: Action<int>.Invoke
Beginning scenario: PosTest2: Action<string>.Invoke

[Negative]
Beginning scenario: NegTest1: Action<int>.BeingInvoke EndInvoke

Assert failure(PID 3715 [0x00000e83], Thread: 3715 [0x0e83]): Reached the "unreachable": FAILED: <unreachable>
    File: /home/maxwell/netcore/coreclr/src/vm/i386/excepx86.cpp Line: 3731
    Image: /home/maxwell/netcore/coreclr/bin/Product/Linux.x86.Debug/corerun

Aborted (core dumped)
```

Changes
```
@@ -835,6 +837,13 @@ Stub * CreateInstantiatingILStub(MethodDesc* pTargetMD, void* pHiddenArg)
         pCode->EmitLoadThis();
     }

+#if defined(_TARGET_X86_) && defined(FEATURE_PAL)
+    for (unsigned i = 0; i < msig.NumFixedArgs();i++)
+    {
+        pCode->EmitLDARG(i);
+    }
+    pCode->EmitLDC((TADDR)pHiddenArg);
+#else
     // 2.2 Push the hidden context param
     // InstantiatingStub
     pCode->EmitLDC((TADDR)pHiddenArg);
@@ -844,6 +853,7 @@ Stub * CreateInstantiatingILStub(MethodDesc* pTargetMD, void* pHiddenArg)
     {
         pCode->EmitLDARG(i);
     }
+#endif
```

**Comment by janvorli** [comment]
I have looked into it a bit and it is actually a bit more complex. The rule for the generic context (hidden arg) position is as follows:
* If the actual function has 0 arguments (including this), the hiddenArg goes to ECX (the first argument register)
* If the actual function has 1 argument (including this), the hiddenArg goes to EDX (the second argument register)
* otherwise it is the last stack argument 

In other words, if all arguments of the function including "this" pointer fit into argument registers and we still have argument registers available, we store the hidden argument in the next available argument register. Otherwise it goes as the last stack argument.

So you'll need to do something like this to make it right for all the cases:
```C++
unsigned int numArgs = msig.NumFixedArgs();
if (msig.HasThis())
{
    // 2.1 Push the thisptr
    pCode->EmitLoadThis();
    numArgs++;
}

#if defined(_TARGET_X86_)
if (numArgs < 2)
{
#endif // _TARGET_X86_
    // 2.2 Push the hidden context param 
    // InstantiatingStub
    pCode->EmitLDC((TADDR)pHiddenArg);    
#if defined(_TARGET_X86_)
}
#endif // _TARGET_X86_

// 2.3 Push the rest of the arguments
for (unsigned i = 0; i < msig.NumFixedArgs();i++)
{
    pCode->EmitLDARG(i);
}

#if defined(_TARGET_X86_)
if (numArgs >= 2)
{
    // 2.2 Push the hidden context param 
    // InstantiatingStub
    pCode->EmitLDC((TADDR)pHiddenArg);    
}
#endif // _TARGET_X86_

```

**Comment by janvorli** [comment]
Actually, it would be better to use NUM_ARGUMENT_REGISTERS instead of the hardcoded 2 here.

**Comment by janvorli** [comment]
@jkotas this is not described in the https://github.com/dotnet/coreclr/blob/master/Documentation/botr/clr-abi.md, I have found it by looking at the code that generates the instantiating stub with the FEATURE_STUBS_AS_IL not defined. So I'd like to update the document, but I wanted to check with you that I am not missing some detail.

**Comment by jkotas** [comment]
I agree that it would be nice to update to update the document. I think you got it right.

This convention for the location of the instantiating arg on x86 is specially crafted to make `StubLinkerCPU::EmitInstantiatingMethodStub` tailcall stub in all cases, different from other platforms.

**Comment by seanshpark** [comment]
@janvorli , great!, thank you for more detailed explanation and the code. By your code, you used `_TARGET_X86_` without `FEATURE_PAL` , so this is also for Win32?
:)

**Comment by janvorli** [comment]
@seanshpark It would be if we ever switched Win32 to use stubs as IL.

**Comment by seanshpark** [comment]
@gkhanna79 , thanks for reminding this issue. I'll close as PR is merged.
