### ISSUE TITLE
[x86/Linux] EH Region Mismatch

### ISSUE THREAD

**Issue by parjong** [dotnet/coreclr#9042]
The following program is expected to print "Hello, World":
```
using System;
using System.Runtime.CompilerServices;

namespace ConsoleApplication { public class Program {

  [MethodImpl(MethodImplOptions.NoInlining)]
  public static int Throw(int n) {
     return 16 / n;
  }

  public static void Main(string[] args) {
    try
    {
      Throw(0);
    }
    catch (Exception)
    {
      Console.WriteLine("Hello World!");
    }
  }

} }
```

In x86/Linux, however, Core CLR shows the following message:
```
Unhandled Exception: System.DivideByZeroException: Attempted to divide by zero.
   at ConsoleApplication.Program.Throw(Int32 n) in /home/parjong/projects/dotnet/coreclr-analyze/eh-region/src/Program.cs:line 8
   at ConsoleApplication.Program.Main(String[] args) in /home/parjong/projects/dotnet/coreclr-analyze/eh-region/src/Program.cs:line 14
```

**Comment by parjong** [comment]
This issue seems to be related with #4496 and #6074.

**Comment by parjong** [comment]
\CC @seanshpark @wateret
