### ISSUE TITLE
Cannot catch exceptions from reverse P/Invoke on Linux

### ISSUE THREAD

**Issue by halter73** [dotnet/coreclr#9288]
The following app will print "Handled exception from reverse P/Invoke" on Windows and then exit. On Linux it will crash with an unhandled exception. I tested this using Microsoft.NETCore.App 1.1 on both platforms. I did not test this on macOS or with other versions of the dotnet runtime.

```c#
using System;
using System.Runtime.InteropServices;

namespace ConsoleApp1
{
    public class Program
    {
        public const int AsyncType = 1;
        public const int DefaultRunMode = 0;

        public delegate void uv_async_cb(IntPtr handle);

        [DllImport("libuv", CallingConvention = CallingConvention.Cdecl)]
        public static extern int uv_loop_size();

        [DllImport("libuv", CallingConvention = CallingConvention.Cdecl)]
        public static extern int uv_loop_init(IntPtr loop);

        [DllImport("libuv", CallingConvention = CallingConvention.Cdecl)]
        public static extern int uv_run(IntPtr loop, int mode);

        [DllImport("libuv", CallingConvention = CallingConvention.Cdecl)]
        public static extern int uv_handle_size(int handleType);

        [DllImport("libuv", CallingConvention = CallingConvention.Cdecl)]
        public static extern int uv_async_init(IntPtr loop, IntPtr async, uv_async_cb callback);

        [DllImport("libuv", CallingConvention = CallingConvention.Cdecl)]
        public static extern int uv_async_send(IntPtr async);

        public static void Main(string[] args)
        {
            var loop = Marshal.AllocHGlobal(uv_loop_size());
            var async = Marshal.AllocHGlobal(uv_handle_size(AsyncType));

            uv_loop_init(loop);
            uv_async_init(loop, async, _ =>
            {
                throw new Exception();
            });

            // Tell uv_run to call the async callback that throws
            uv_async_send(async);

            try
            {
                uv_run(loop, DefaultRunMode);
            }
            catch
            {
                Console.WriteLine("Handled exception from reverse P/Invoke.");
            }
        }
    }
}
```

Windows output:

```
> dotnet run
Handled exception from reverse P/Invoke.
```

Linux output:

```
$ dotnet run
Project ConsoleApp2 (.NETCoreApp,Version=v1.1) was previously compiled. Skipping compilation.

Unhandled Exception: System.Exception: Exception of type 'System.Exception' was thrown.
   at ConsoleApp1.Program.<>c.<Main>b__9_0(IntPtr _) in /home/shalter/ConsoleApp2/Program.cs:line 39
   at ConsoleApp1.Program.uv_run(IntPtr loop, Int32 mode)
   at ConsoleApp1.Program.Main(String[] args) in /home/shalter/ConsoleApp2/Program.cs:line 47
```

We expect to be able to catch and handle these exceptions in KestrelHttpServer.

**Comment by parjong** [comment]
Seems to be related with #7651.

**Comment by janvorli** [comment]
@halter73 this is by design in CoreCLR and we are going to make it behave the same way on Windows too (see #8459). For some details, please see https://github.com/dotnet/coreclr/pull/7652#issuecomment-254983802.

**Comment by DemiMarie** [comment]
Does that mean that one should wrap every callback in (pseudo-C#)

```c#
try
{
    some code that might throw
}
catch (System.Object o)
{
    if (o is System.Exception) {
        // log a stack trace maybe?
    }
}
```

**Comment by DemiMarie** [comment]
@halter73 note that libuv is likely in an inconsistent state even on Windows – as a C library it is not designed to handle this scenario.

**Comment by janvorli** [comment]
@DemiMarie yes, the exceptions need to be caught at that boundary. What the code does when the exception is caught is specific to the application / library. It might be logging and then ignoring the exception, it might be logging and failing fast or converting the exception to some kind of status that's propagated to the managed code that called the native code that called the faulting managed code.
