### ISSUE TITLE
[Arm64] Tests fail with System.OverflowException

### ISSUE THREAD

**Issue by jashook** [dotnet/coreclr#9460]
Failing Tests

<pre>
baseservices/threading/paramthreadstart/ThreadStartByte/ThreadStartByte.cmd
baseservices/threading/paramthreadstart/ThreadStartSByte/ThreadStartSByte.cmd
</pre>

Example Output

<pre>
TEST_CMD_LINE: baseservices\threading\paramthreadstart\ThreadStartByte> baseservices\threading\paramthreadstart\ThreadStartByte\ThreadStartByte.cmd 8466 
BEGIN EXECUTION
 "Tests2\Core_Root\corerun.exe" ThreadStartByte.exe 8466
Unhandled Exception: System.OverflowException: Value was either too large or too small for an unsigned byte.
   at System.Byte.Parse(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToByte(String value)
   at ThreadStartByte.Main(String[] args)
Expected: 100
Actual: -532462766
END EXECUTION - FAILED
FAILED

</pre>

**Comment by jashook** [comment]
Looks like this was fixed with #9523
