### ISSUE TITLE
dnu restore fails with error: FileNotFoundException

### ISSUE THREAD

**Issue by rupreetg** [dotnet/coreclr#971]
I wanted to try out sample project to understand coreCLR better and learn abour DNX family. 

I tried this link https://github.com/dotnet/coreclr/blob/master/Documentation/get-dotnetcore-dnx-windows.md to get started and followed everything as mentioned on my windows machine (8.1, x64)

When I run "dnu restore", I get the following error - 
--------------------------------------------------------------------------------
Restoring packages for D:\work\labs\coreCLR\firstAppUsingCoreclr\project.json
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='System.Console'.
----------
System.IO.FileNotFoundException: The local package source D:\Work\Grapine\Products\ErrorTracking\raygun4net-master\packages doesn't exist
File name: 'D:\Work\Grapine\Products\ErrorTracking\raygun4net-master\packages'
   at Microsoft.Framework.PackageManager.Restore.NuGet.PackageFolder.FindPackagesByIdAsync(String id)
   at Microsoft.Framework.PackageManager.RemoteWalkProvider.<FindLibrary>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibrary>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryByVersion>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<CreateGraphNode>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<>c__DisplayClass68_0.<<ExecuteCommand>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Framework.PackageManager.RestoreCommand.<ExecuteCommand>d__68.MoveNext()
----------
Restore failed
The local package source D:\Work\Grapine\Products\ErrorTracking\raygun4net-master\packages doesn't exist
---------------------------------------------------------------------------------------------------

Note here - my project.json looks exactly same as mentioned in the github link but its trying to find packages in one of my existing project which doesn't have any relation to it. 

I've tried searching on this but haven't found so posting it here. 

Here are some more info - 
"dnu list" gives this output - 
-----------------------------------------------------
Listing dependencies for firstAppUsingCoreclr (D:\work\labs\coreCLR\firstAppUsingCoreclr\project.json)

[Target framework DNX,Version=v4.5.1 (dnx451)]

Framework references:
  framework/Microsoft.CSharp 4.0.0.0
  framework/mscorlib 4.0.0.0
  framework/System 4.0.0.0
  framework/System.Core 4.0.0.0

[Target framework DNXCore,Version=v5.0 (dnxcore50)]

 references:
  System.Console 4.0.0-beta - Unresolved
-------------------------------------------------------

Command dnvm gives this output -
-----------------------------------------------------------
 .NET Version Manager v1.0.0-beta5-10375
By Microsoft Open Technologies, Inc.
usage: dnvm <command> [<arguments...>]

Current feed settings:
Default Stable: https://www.nuget.org/api/v2
Default Unstable: https://www.myget.org/F/aspnetvnext/api/v2
Current Stable Override: <none>
Current Unstable Override: <none>
----------------------------------------------------------------------

**Comment by rupreetg** [comment]
dnvm list gives output - 

Active Version           Runtime Architecture Location                        Alias
------ -------           ------- ------------ --------                        -----
       1.0.0-beta5-11744 coreclr x64          C:\Users\rupreetg\.dnx\runtimes
  *    1.0.0-beta5-11744 coreclr x86          C:\Users\rupreetg\.dnx\runtimes

**Comment by akoeplinger** [comment]
Check if you have any additional package sources defined in `%APPDATA%\NuGet\NuGet.Config`.

**Comment by rupreetg** [comment]
Yup, it has additional packages - 

<configuration>
  <packageRestore>
    <add key="enabled" value="True" />
    <add key="automatic" value="True" />
  </packageRestore>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
    <add key="Package source" value="C:\Users\rupreetg\Downloads\Xamarin.QuickUI.1.0.6041.nupkg(1)" />
    <add key="Raygun" value="D:\Work\Grapine\Products\ErrorTracking\raygun4net-master\packages" />
    <add key="SoiChat" value="D:\Work\SioChat\Soichat.App-master\packages" />
  </packageSources>
  <disabledPackageSources />
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
</configuration>

But I am still confused as to why its failing?

**Comment by akoeplinger** [comment]
Presumably because that local package folder isn't what dnu expects (does it contain actual nupkgs?).

**Comment by rupreetg** [comment]
I am assuming the actual packages have moved or not placed in that folder any more hence it fails. I agree that dnu is expecting the packages to be there but it seems it shouldn't fail if any existing package doesn't exist in nuget config, especially if that package isn't part of the program I trying to compile. Not sure if this is by design or a bug.

**Comment by akoeplinger** [comment]
dnu/nuget doesn't know that the package source doesn't contain relevant packages, it just tries every package source until it finds the package in one of them.

It looks like restore failing on a non-existing local package source was a deliberate change introduced in https://github.com/aspnet/dnx/pull/1032. Just remove the package source from NuGet.config ;)

**Comment by rupreetg** [comment]
Yup, i was able to move ahead post removing the non-existent packages! Thanks for your help!

The PR link you gave was helpful in understanding the behavior and why it was done this way, so :+1:
