### ISSUE TITLE
CoreCLR failing to restore build tools on OSX

### ISSUE THREAD

**Issue by janvorli** [dotnet/coreclr#9734]
```
18:08:54 Running init-tools.sh
18:08:54 Installing dotnet cli...
18:09:18 Restoring BuildTools version 1.0.27-prerelease-01209-01...
18:09:19 
18:09:19 Unhandled Exception: System.ArgumentNullException: Value cannot be null.
18:09:19 Parameter name: path1
18:09:19    at System.IO.Path.Combine(String path1, String path2, String path3)
18:09:19    at Microsoft.DotNet.ProjectModel.Resolution.PackageDependencyProvider.ResolvePackagesPath(String rootDirectory, GlobalSettings settings)
18:09:19    at Microsoft.DotNet.Configurer.NuGetCacheSentinel.get_NuGetCachePath()
18:09:19    at Microsoft.DotNet.Configurer.NuGetCacheSentinel.Exists()
18:09:19    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.ShouldPrimeNugetCache()
18:09:19    at Microsoft.DotNet.Configurer.DotnetFirstTimeUseConfigurer.Configure()
18:09:19    at Microsoft.DotNet.Cli.Program.ConfigureDotNetForFirstTimeUse(INuGetCacheSentinel nugetCacheSentinel)
18:09:19    at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
18:09:19    at Microsoft.DotNet.Cli.Program.Main(String[] args)
18:09:19 /Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx_tst_prtest@2/tests/../init-tools.sh: line 164: 68854 Abort trap: 6           $__DOTNET_CMD restore "$__PROJECT_JSON_FILE" --no-cache --packages $__PACKAGES_DIR --source $__BUILDTOOLS_SOURCE >> $__init_tools_log
18:09:19 
ERROR: Could not restore build tools correctly. See '/Users/dotnet-bot/j/workspace/dotnet_coreclr/master/checked_osx_tst_prtest@2/init-tools.log' for more details.1
```

**Comment by janvorli** [comment]
The first build failed with this issue in CI is
https://ci.dot.net/job/dotnet_coreclr/job/master/job/checked_osx_flow_prtest/3149/

**Comment by janvorli** [comment]
I am unable to repro the issue on my local OSX machine.

**Comment by janvorli** [comment]
CC: @gkhanna79

**Comment by gkhanna79** [comment]
@livarcocc @piotrpMSFT Can you PTAL?

**Comment by gkhanna79** [comment]
@janvorli Can you please move this issue to CLI repo?

**Comment by janvorli** [comment]
Issue moved to [dotnet/cli #5930](https://github.com/dotnet/cli/issues/5930) via [**ZenHub**](https://www.zenhub.com/)
